### ISSUE TITLE
Popover smart positioning issues in docs example

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#100]
smart positioning doesn't really do anything right now in the popover example. perhaps we should demonstrate the usage of some other Tether constraint.

![2016-11-12 11 08 26](https://cloud.githubusercontent.com/assets/723999/20239182/93a3d88c-a8c8-11e6-82ec-8a5339e74c0e.gif)

**Comment by giladgray** [comment]
huh i wonder why it doesn't work on the docs? perhaps this is an indicator that we should remove it, just support the more configurable and useful `constraints`.

**Comment by giladgray** [comment]
wow none of the constraints have any effect on the docs site and I can't figure out why 😭

**Comment by tgreenwatts** [comment]
Didn't we deprecate `useSmartPositioning`? Can we close this? Or remove from the docs?

**Comment by adidahiya** [comment]
The docs should demonstrate _some_ kind of smart positioning, they shouldn't use the `useSmartPositioning` API though

**Comment by adidahiya** [comment]
Fixed in 2.0
