### ISSUE TITLE
Only console.warn Empty tooltip warning if tooltip is also not disabled/open

### ISSUE THREAD

**Issue by styu** [palantir/blueprint#1000]
### Bug report

- __Package version(s)__: 1.14.0
- __Browser and OS versions__: Chrome, OSX

I have many elements on the page with disabled tooltips, but in dev mode this causes my console to blow up with warnings :(

From this it looks like it'll always spit out a warning if the content is empty, regardless of if the tooltip is disabled or not (i'm disabling the tooltip if the content is empty): https://github.com/palantir/blueprint/blob/master/packages/core/src/components/tooltip/tooltip.tsx#L164

Could we only console.warn in the case where you're trying to actually show the tooltip? i.e. `isOpen` is true and/or `disabled` is false?

![image](https://cloud.githubusercontent.com/assets/1143755/25108200/32f6896c-23a2-11e7-9b63-605420488111.png)

**Comment by giladgray** [comment]
Woo #1000! 💯🎉

Good catch, will fix this week.
