### ISSUE TITLE
[Table] Refactor Table examples into one example with toggles

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1006]
Currently, we have several Table examples that each display orthogonal bits of `Table` functionality. Would be nice to combine all those examples into one and have various features toggle-able in that one table. Reduces docs bloat and makes it easier to test perf when multiple `Table` features are simultaneously enabled.

**Comment by tgreenwatts** [comment]
Close as success?!

**Comment by llorca** [comment]
@tgreenwatts yes! Success!
