### ISSUE TITLE
Portal should support setting classname on .pt-portal element

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#1007]
can't change the behavior of `portalClassName`, so this will have to be a new prop that deprecates that one

**Comment by giladgray** [comment]
`portalContainerClassName`?

**Comment by giladgray** [comment]
moving where `portalClassName` gets applied up one element in the tree would be a mild API break, yeah?

**Comment by adidahiya** [comment]
yeah, that would be an API break. can't do that in 1.x. `portalContainerClassName` sounds good

**Comment by dserrano-geo** [comment]
Hi.

I'm trying to organize the portals by z-index, but this is not possible with the portalClassName property, because portalClassName is inside from .pt-portal div. Is there a way to apply changes on demand in the .pt-portal class of each div?

Regards.

**Comment by adidahiya** [comment]
No, you shouldn't have to control z-index of popovers. Why do you need to do this? Do you have multiple popovers open at once?

**Comment by dserrano-geo** [comment]
We have a group of buttons that have tooltips, when you click, a popover is displayed with a component. While the popover is displayed, the tooltips are below the popover, we need the tooltips always to be above, because that's what the design requires. We are looking for ways to handle this.

**Comment by giladgray** [comment]
fixed in #2205

**Comment by giladgray** [comment]
@dserrano-geo check this out: http://blueprintjs.com/docs/v1/#core/components/tooltip.combining-with-popover
