### ISSUE TITLE
Docs FR: "edit this section" link

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#101]
Would be cool to have an "edit this section" link on every KSS section that takes you to the Github file on the master branch.

**Comment by giladgray** [comment]
this would be cool!

but the thing is, KSS sections don't know which file they came from. KSS doesn't expose that data from its API, and it processes all the files at once so I can't easily figure it out myself. 😢

**Comment by llorca** [comment]
What is the goal of this FR? Is it about being able to quickly edit the docs on GitHub when a correction needs to be made?

**Comment by adidahiya** [comment]
@llorca yep, exactly, to make it easy for anyone to send corrections or enhancements. I've seen this on a number of other projects that have high-quality docs

**Comment by llorca** [comment]
Hopefully will be doable once we have full Markdown docs

**Comment by giladgray** [comment]
requires change in documentalist to link to source md file
