### ISSUE TITLE
[Table] Truncated icons persist in cells even when text isn't truncated

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1022]
To reproduce:
On the Formatted Content example, expand the date column to where it does not need the truncation ellipsis
Expected: Truncation ellipsis goes away
Actual: Ellipsis stays
Now scroll down and come back
Expected: Scrolling changes nothing
Actual: Now the ellipsis is gone!

![ellipsis](https://cloud.githubusercontent.com/assets/24398123/25254399/3dd0750c-25da-11e7-91cf-ec148dab14fc.gif)

This is a Regression

**Comment by adidahiya** [comment]
almost certainly due to #998

**Comment by cmslewis** [comment]
Yep, probably an erroneous `@PureRender` or `shouldComponentUpdate` somewhere.
