### ISSUE TITLE
Trigger menu close with a custom menu item?

### ISSUE THREAD

**Issue by samdenicola** [palantir/blueprint#1024]
Hey there -- love the library we've been enjoying using it for our new projects!

I'm building a custom column header menu to implement filter by functionality similar to Google's spreadsheets tool. The Menu component here is a collection of MenuItems as well as divs with the select, input, and button components. I've added the "Ok" and "Cancel" buttons to the bottom of the menu in a div instead of a MenuItem so that both buttons can be on one line. Is there a way to have their onClick close the Menu component? 

<img width="455" alt="screen shot 2017-04-20 at 4 47 04 pm" src="https://cloud.githubusercontent.com/assets/13247167/25256956/74966056-25e9-11e7-9740-b146f0402a30.png">

Thanks!

**Comment by giladgray** [comment]
@samdenicola `className="pt-popover-dismiss"`
http://blueprintjs.com/docs/#core/components/popover.opening---closing-popovers

**Comment by samdenicola** [comment]
@giladgray excellent! Thanks :) I'll close this as that answers my question.
