### ISSUE TITLE
Datetime: Rendering date picker inside a Menu component

### ISSUE THREAD

**Issue by samdenicola** [palantir/blueprint#1026]
### Bug report

- __Package version(s)__: core 1.15, datetime 1.13
- __Browser and OS versions__: Mac OS Sierra, Chrome 57

#### Steps to reproduce

1. Add a `<div>` with a `<DateInput>` to a `<Menu>` component. 
2. Focus the date input

#### Actual behavior

Date picker popover does not display on focus (although inspecting props shows isOpen = true)
<img width="547" alt="screen shot 2017-04-21 at 11 57 07 am" src="https://cloud.githubusercontent.com/assets/13247167/25292401/cbcaaafc-268a-11e7-8e76-3ab764cde560.png">

#### Expected behavior

Date picker popover should display.

Have a feeling this has something to do with popover positioning -- maybe I'm just doing something wrong.

Any tips? Thanks!

**Comment by giladgray** [comment]
typically, nested popovers must be made `inline`.
@samdenicola try `<DateInput popoverProps={{ inline: true }} />`.

**Comment by samdenicola** [comment]
@giladgray hmm no luck with `<DateInput popoverProps={{ inline: true }} />`

Any other ideas?

**Comment by samdenicola** [comment]
Looks like the issue was css caused. pt-menu-item has `overflow:hidden` which was causing the overlay for the `DateInput` to be hidden. Removing that css for the date input allowed the overlay to be displayed.
