### ISSUE TITLE
[Hotkeys] Customize "Show dialog" hotkey

### ISSUE THREAD

**Issue by vinz243** [palantir/blueprint#1028]
Right now, the `SHOW_DIALOG_KEY` is set to `?`. This key is not accessible for non-american keyboards (eg azerty) since the `?`character is accessible by pressing <kbd>Maj</kbd> + <kbd>,</kbd> (which registers as such). It would be great to find a key that does not depend on the layout, such as `M`. And make this key editable (as opposed to a constant).

Thanks in advance

**Comment by llorca** [comment]
Agree, `?` is a good default but should be customizable. I also see a hardcoded string or two that we should expose for customization, such as "Global hotkeys"

**Comment by vinz243** [comment]
up, would realy like to see this through; in addition it would be greta if we could open the dialog programatically for a button for example

**Comment by warpdesign** [comment]
I am using a french keyboard and here, pressing `shift + ,` which usually prints the `?` doesn't bring the hotkeys dialog.

Instead, I have to press `shift + :` which is supposed to print `/`.

I guess this is a bug.
