### ISSUE TITLE
content from icons.json doesn't seem correct

### ISSUE THREAD

**Issue by nchen63** [palantir/blueprint#1032]
in icons.json, I see:

```
  {
    "name": "Edit",
    "className": "pt-icon-edit",
    "tags": "annotate, pen, modify",
    "group": "action",
    "content": "\\270E"
  },
```

but the value in content isn't very useful. I'd expect it to be "\u270E", which is the actual blueprint icon character. Or is this supposed to be parsed another way?

**Comment by giladgray** [comment]
interesting find! that file is used to generate four files at build time which define all the icon variables in both Sass and JS. [it is intended to be parsed, apparently, as we do a string replace to add the `u`](https://github.com/palantir/blueprint/blob/master/gulp/icons.js#L33). the generated files are not tracked in git so i can't link to it but here's a sample:

```
// _icon_contents.scss
$pt-icon-geosearch: "\e613";
$pt-icon-heatmap: "\e614";
$pt-icon-drive-time: "\e615";
$pt-icon-select: "\e616";
```

```
// iconContents.ts
SEARCH_AROUND: "\ue608",
GRAPH_REMOVE: "\ue609",
GROUP_OBJECTS: "\ue60a",
MERGE_LINKS: "\ue60b",
```

**Comment by giladgray** [comment]
that said, it seems more than reasonable for the json file to be correct and to invert the parsing in our script (to fix the Sass output instead of the JS)

**Comment by nchen63** [comment]
when fixing this, please use `\u270E` instead of `\\u270E` since apparently it's impossible (at least I couldn't easily find a way) to unescape this
