### ISSUE TITLE
[EditableText] Uncontrolled EditableText should not update value to defaultValue on rerender

### ISSUE THREAD

**Issue by jchomicki** [palantir/blueprint#1033]
### Bug report

- __Package version(s)__: 1.15.0
- __Browser and OS versions__: 
Chrome 57.0.2987.133 (64-bit)
macOS Sierra 10.12.4 (16E195)

#### Steps to reproduce

1. Create an EditableText in Uncontrolled mode (`defaultValue` set)
1. Use `onChange` to cause a rerender whenever the event is fired

#### Actual behavior

The EditableText value changes back to the `defaultValue` on every rerender

#### Expected behavior

The value should not be affected by rerenders. DefaultValue should only affect the initial render.

**Comment by cmslewis** [comment]
Fixed by #1068.
