### ISSUE TITLE
DateRangeInput's behavior is very different between the controlled and uncontrolled uses

### ISSUE THREAD

**Issue by nomcopter** [palantir/blueprint#1040]
The UX for DateRangeInput works as expected when used in an uncontrolled fashion. Focus between the fields switches as one expects and it is possible for a user to select a range using only the calendars.
However, when used in a controlled fashion, focus does not change and it is only possible to select a date range if a user manually changes the focus of the text fields. Definitely poor UX.

I propose that the uncontrolled behavior remains the same, and that the controlled behavior is changed to behave more like it. `onChange` should only be called when a user closes the date range popup and state should be managed internally while it is open.

**Comment by adidahiya** [comment]
looks similar to #971 -- does that one capture most of the issues?

**Comment by nomcopter** [comment]
It captures some of it. The uncontrolled version has a fair amount of logic https://github.com/palantir/blueprint/blob/master/packages/datetime/src/dateRangeInput.tsx#L375 that I think should all be preserved in the controlled version.
