### ISSUE TITLE
NumericInput doesn't constain min and max on text entry

### ISSUE THREAD

**Issue by thejjmiller** [palantir/blueprint#1044]
When you have a min and/or max property specified only the up and down arrows are constrained. You can still type in much larger or smaller numbers.

**Comment by cmslewis** [comment]
@thejjmiller We've thought about this in the past. This is not technically a bug; this is consistent with how default `input[type="number"]`s work.

**Comment by thejjmiller** [comment]
I agree. That is how I implemented it on my own. On blur set the value to max if it is over max and if under min set to min. 

I understand that is what input[type=number] does but still seems like part of having a framework like blueprint is to help fix some of those problems.

Also wanted to say that we really have loved Blueprint and love getting so many new releases.

**Comment by cmslewis** [comment]
@thejjmiller I opened a PR. Take a look! https://github.com/palantir/blueprint/pull/1057

**Comment by thejjmiller** [comment]
Thank you. Works perfect now.
