### ISSUE TITLE
Docs don't render correctly in Mobile Safari

### ISSUE THREAD

**Issue by andrew** [palantir/blueprint#105]
Can't read the left side of the page on mobile safari (iPhone 6 with iOS 10.1.1)

![img_4042](https://cloud.githubusercontent.com/assets/1060/20240183/015e6838-a90a-11e6-983f-94fe07616251.PNG)

**Comment by giladgray** [comment]
yep known issue! Blueprint doesn't really support mobile in its current state so we never implemented this. will do now because people seem to love reading longform documentation on tiny screens!

**Comment by giladgray** [comment]
for the record, fix is a simple `meta` tag with `initial-scale=1`.

**Comment by sixinli** [comment]
Also seeing this:
![image](https://cloud.githubusercontent.com/assets/4587468/20240468/c31a8660-a8e6-11e6-89ff-e0dab03f40d9.png)


Hopefully it will be addressed too?

**Comment by llorca** [comment]
@sixinli Can you please provide your iOS version and iPhone model

**Comment by nahuel** [comment]
@giladgray do you have plans / a roadmap to add mobile support to blueprint?

**Comment by llorca** [comment]
@nahuel No plan yet, it's low priority for us. We'll keep you guys posted when that changes!

**Comment by minimaxir** [comment]
No mobile support, in 2016, makes Blueprint a nonstarter for anyone working on an external-facing project.

The fact that mobile priority is *low-priority* is enough of a caveat that it should be added to the README.

**Comment by llorca** [comment]
We'll make sure to clarify that Blueprint is a **desktop-only** solution and not available for mobile.

**Comment by tedyoung** [comment]
Isn't readable on an iPad either, so not just "tiny screens".

**Comment by PaulBGD** [comment]
This is really disappointing. I saw the toolkit and was really excited, but no mobile support is a killer.

**Comment by adidahiya** [comment]
main issue has been fixed by #148. issue in this comment https://github.com/palantir/blueprint/issues/105#issuecomment-260143805 will be fixed by #171.
