### ISSUE TITLE
[DateRangePicker] Option to have a separator between two months

### ISSUE THREAD

**Issue by kendraknittel** [palantir/blueprint#1052]
It would be nice to have the option to separate the two months in the DateRangePicker and DateRangeInput - something such as the following:

![image](https://cloud.githubusercontent.com/assets/14883799/25587739/4a4b8442-2e73-11e7-8afb-8ef519d984ea.png)

**Comment by giladgray** [comment]
@kendraknittel can you add this with some custom CSS on your end? perhaps share the styles with us and we'll see if it makes sense to integrate into the full API.

**Comment by llorca** [comment]
I could see us trying that out for the case where months aren't contiguous, but I wouldn't do it otherwise. For now you can achieve this style by simply adding a `border` or box-shadow` rule on `.DayPicker-Month` for instance :+1:

**Comment by kendraknittel** [comment]
@llorca It doesn't seem to be possible with custom CSS due to the fact that the class `DayPicker-Day--outside` somehow blocks the border from showing, do you know how to work around this?
![image](https://cloud.githubusercontent.com/assets/14883799/25910906/f6e963e6-357f-11e7-9a11-1b8c8aefef92.png)
![image](https://cloud.githubusercontent.com/assets/14883799/25910924/07002d00-3580-11e7-9a07-5dca6e749a69.png)

**Comment by llorca** [comment]
@kendraknittel try removing `border-collapse: collapse;` from `.DayPicker-Month`

**Comment by giladgray** [comment]
closing as stale. will not implement.
