### ISSUE TITLE
[Feature Req] Releasing the Sketch file for designers using blueprintjs

### ISSUE THREAD

**Issue by marekdlugos** [palantir/blueprint#1054]
Guys, quick question. Do you plan to release the .sketch file for designers that use blueprintjs? It would be super helpful for people who doesn't code (most of the designers).

**Pros:**
- Fast way for designers to prototype with blueprintjs
- Easy to test concepts/design (layouts, etc.) if designers know that dev will use blueprintjs
- Easier collaboration in multidisciplinary teams (ux designer -> visual designer -> front-end dev)

**Cons:**
- Maintenance of 2 blueprintjs 'projects' (keeping the .sketch file up to date with repo and vise-versa)

**Might be helpful**
[Render React components to Sketch; tailor-made for design systems](https://github.com/airbnb/react-sketchapp)

**Comment by giladgray** [comment]
We planned, and we did! http://blueprintjs.com/docs/#core/resources

**Comment by cmslewis** [comment]
@giladgray Can we close this?

**Comment by marekdlugos** [comment]
@giladgray lovely! Sorry for spam. Feel free to close this.

**Comment by jtheisen** [comment]
The sketch files are not on the linked resource page (any longer?).

**Comment by adidahiya** [comment]
@jtheisen they're here: https://blueprintjs.com/docs/#resources. but they need an update. #2817

**Comment by Jenniferwilson197873** [comment]
Cancel my github account

**Comment by TuuZzee** [comment]
Are the sketch files not issued anymore and linked on the resource page? It seems that they are the same on [v5](https://blueprintjs.com/docs/versions/5/#resources) and [v4](https://blueprintjs.com/docs/versions/4/#resources).

**Comment by adidahiya** [comment]
@TuuZzee we stopped using Sketch; we hope to eventually open-source our Figma library, see https://github.com/palantir/blueprint/discussions/5743
