### ISSUE TITLE
NPM installation command in blueprintjs.com does not match the one in blueprintjs.com/docs/

### ISSUE THREAD

**Issue by dcarrot2** [palantir/blueprint#106]
NPM installation command in blueprintjs: `npm install --save-dev @blueprint/core`

NPM installation command in the docs: `npm install --save-dev @blueprintjs/core`

Installing using `@blueprint/core` errors out given that npm cannot find the non existing package

**Comment by giladgray** [comment]
yowza! good catch my friend.
