### ISSUE TITLE
Programatically select *and* jump to row in table

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1065]
Hi there,

First off, thank you for your wonderful set of components!

I was wondering if it was possible to programatically jump to a row in the data table. 

For example, say I have this function to update my state (and thus update the selected region of the table)
```js
const select10thRow = () => {
      this.setState({selectedRegions: [{rows: [10, 10]}]})
    }
```

But if the 10th row is no longer within view (because the user's scrolled), the row will be selected, but the table will not jump to it. Is there a way to get it to jump as well?

I saw this issue, but it looks like it is more for jumping on keyboard interactions:
https://github.com/palantir/blueprint/issues/915

Thanks!

**Comment by backnotprop** [comment]
Can this issue be reopened? Or reason why it was closed? The PR did not address this.

**Comment by backnotprop** [comment]
^ Disregard, we can manually implement this
