### ISSUE TITLE
Main website performs poorly on Firefox

### ISSUE THREAD

**Issue by electic** [palantir/blueprint#108]

**Comment by JKillian** [comment]
See https://news.ycombinator.com/item?id=12939756 for for more info

**Comment by cmslewis** [comment]
Hi @electic, thanks for reporting! Cat got out of the bag a little earlier than we expected w/r/t broader publicity, but we do have a couple engineers working through issues at the moment. We'll try to address the Firefox issue(s) you're seeing today and/or tomorrow, before we come back to the office with a vengeance on Monday.  👍

**Comment by electic** [comment]
Thanks Chris! Btw, great job on the components. Really blown away.
