### ISSUE TITLE
Right click menu behavior improvements in table

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#1083]
- [x] When the right-click menu is open, we should block scrolling
- [x] Right-click menu should be dismissed when clicking outside of it
- [x] Right-clicking on a selection shouldn't change the selection
- [x] Right-clicking on a cell/column/row should select said cell/column/row

**Comment by cmslewis** [comment]
Final point was fixed in #1523 and #1584.

**Comment by llorca** [comment]
@cmslewis <3 some legit UX milestone right here
