### ISSUE TITLE
Accessibility with popovers

### ISSUE THREAD

**Issue by samdenicola** [palantir/blueprint#1084]
I have a popover as an item in my header navigation bar that when clicked brings up a menu of some sub-options. When I tab through the options the popover does not get selected. I expect to be able to tab on the popover, hit enter, and have the sub menu open which then could be tabbed into and an enter key press would result in some app navigation.

This is how the popover is written in the app:
```
<Popover
  className={"header-link-button"}
  content={InventoryMenu}
  position={Position.BOTTOM}
>
  <span>
    <span className={"pt-icon-standard " + "pt-icon-database"} />
    Inventory
  </span>
</Popover>
```

This is what the menu code looks like:
```
const InventoryMenu = (
  <Menu>
    <Link to="/plates">
      <div className={"pt-popover-dismiss pt-menu-item menu-link"}>
        Plates
      </div>
    </Link>
    <Link to="/materials">
      <div className={"pt-popover-dismiss pt-menu-item menu-link"}>
        Materials
      </div>
    </Link>
    <Link to="/samples">
      <div className={"pt-popover-dismiss pt-menu-item menu-link"}>
        Samples
      </div>
    </Link>
    <Link to="/aliquots">
      <div className={"pt-popover-dismiss pt-menu-item menu-link"}>
        Aliquots
      </div>
    </Link>
  </Menu>
);
```
This is a gif of the missed tab interaction:
![popovermissingtab](https://cloud.githubusercontent.com/assets/13247167/25924480/c413e532-3597-11e7-9b16-77065f7bcded.gif)

And here is the opened popover:
<img width="298" alt="screen shot 2017-05-10 at 3 46 37 pm" src="https://cloud.githubusercontent.com/assets/13247167/25924510/e46628d6-3597-11e7-923b-94be82653112.png">

Thanks for any help! Not sure if this is a bug or if I am implementing the popover wrong.

As always -- lovin' the components :)

**Comment by llorca** [comment]
Hi Sam! Thanks!

Check out the popover docs: http://blueprintjs.com/docs/#core/components/popover

I'm correctly able to `tab` to the "Popover target" button, hit `space` to open the popover, then `tab` again to access the inside of the popover and then `space` again to trigger whatever is inside the popover.

Sounds like you're trying to hit `enter` instead of `space`

**Comment by samdenicola** [comment]
Hey @llorca 

It looks like that actually wasn't the problem -- both `space` and `enter` are working for me. The issue was that my "popover target" was a `span` element. I switched it to a minimal `Button` and `tab` worked.

Gonna close this for now.

Thanks!

**Comment by xaun** [comment]
@llorca I know this is an old issue, but when I go to the docs right now and follow your steps, after hitting space to open the popover, then tab again, it tabs to the appearance configuration controls on the right instead of the actions inside the popover.
