### ISSUE TITLE
Date picker time showing incorrectly

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1089]
>There also seems to be a time zone issue: when I do succeed in selecting the hour, it shows as selected hour – 4 (so if I type in 6, it will show 2; if I type in 7, it will show 3, etc). 
https://pl.ntr/eX
@cmslewis can you take a look at this?
@jchomicki  for SA

**Comment by giladgray** [comment]
sounds like #890

**Comment by cmslewis** [comment]
Fixed locally by permitting the popover to close only when the user manually selects/updates a date, not when the user manually updates the time. Will push changes after my next meeting.

**Comment by cmslewis** [comment]
Folding the remaining issue in the description into #890.
