### ISSUE TITLE
selected radio button render issue

### ISSUE THREAD

**Issue by samdenicola** [palantir/blueprint#1090]
I've seen this in my own app and now in the docs. Sometimes a selected radio button flickers with its filled in color -- see below (from the docs) the selected button is only half filled in. Not sure whats causing the issue here.

<img width="506" alt="screen shot 2017-05-11 at 3 13 45 pm" src="https://cloud.githubusercontent.com/assets/13247167/25974188/8ab233be-365c-11e7-94ee-260f28f1a93f.png">

**Comment by llorca** [comment]
Never seen that. I would assume it's a Chrome rendering issue.

Can you add more details about your setup? OS, browser, Blueprint version, etc.

**Comment by samdenicola** [comment]
Sure! The above picture was taken from the docs website here: http://blueprintjs.com/docs/#datetime/daterangeinput
OS: macOS Sierra 10.12.4
Browser: Chrome 58
Blueprint version: Whatever you guys have on the docs site (I imagine it was 1.17?)

**Comment by llorca** [comment]
Damn, I've got the same setup than you but I'm unable to repro :(

**Comment by tgreenwatts** [comment]
I've seen this before, @adidahiya said it was a chrome bug - I can't reproduce it right now

**Comment by giladgray** [comment]
cannot repro.
