### ISSUE TITLE
DateRangeInput popover not staying within window even when passing tether props

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1091]
### Bug report

- __Package version(s)__: "@blueprintjs/datetime": "^1.13.0"
- __Browser and OS versions__: Mac 10.12 , Chrome most recent

#### Steps to reproduce
Hey there, I am trying to get the DateRangeInput component to stay within the window. I assumed it would be as simple as:

```js
<DateRangeInput
              popoverProps={{
                tetherOptions: {
                  constraints: { attachment: "together", to: "window", pin: true },
                }
              }}
              onChange={selectedDates => {
                handleFilterValueChange(selectedDates);
              }}
            />
```

But, instead it is rendering like this:

![image](https://cloud.githubusercontent.com/assets/2730609/25976457/f84a8aa4-3669-11e7-9d45-11e99ffc1009.png)

Perhaps the tetherOptions aren't making it onto the popover? Or I'm doing something else wrong. Any guidance would be appreciated. Thanks!

**Comment by llorca** [comment]
@tnrich have you tried passing a `position` to `popoverProps`?

**Comment by tnrich** [comment]
hey @llorca , I had not tried passing a `position` prop, but I did figure out what I needed to do thanks to a helpful blueprint warning: 
```
[Blueprint] <Popover inline={true}> ignores tetherOptions, constraints, and useSmartPositioning
```

So all I needed to override the default inline positioning (and my tetherOptions were poorly formatted, but I got an error in the tether code that alerted me to that)!

My component now looks like this
```html
       <DateRangeInput
              {...onEnterHelper(handleFilterSubmit)}
              popoverProps={{
                inline:false,
                tetherOptions: {
                  constraints: [{
                    attachment: "together",
                    to: "window",
                    pin: true
                  }]
                }
              }}
              maxDate={new Date()}
              onChange={selectedDates => {
                handleFilterValueChange(selectedDates);
              }}
            />
```

**Comment by tnrich** [comment]
Hey there, so I thought that this had been solved by setting `inline:false` and specifing `tetherOptions`:

```
<DateRangeInput
  popoverProps={{
    inline: false,
    tetherOptions: {
      constraints: [
        {
          attachment: "together",
          to: "window",
          pin: true
        }
      ]
    }
  }}
  maxDate={new Date()}
  onChange={selectedDates => {
    handleFilterValueChange(selectedDates);
  }}
/>
```
Here is a gif of that component being used:
![asdfasdfasd](https://cloud.githubusercontent.com/assets/2730609/26363155/1797b9a2-3f95-11e7-9143-7bf72549983b.gif)

As you can see I have inline false, the tetherOptions work, but the dateRangeInput **closes unexpectedly** after the first click. I assume this is because the dateRangeInput is embedded in another modal? 

If `inline:true`, the dateRangeInput works as expected but the tether options don't work. 

Any help solving this would be greatly appreciated. Thanks!

**Comment by giladgray** [comment]
closing as Popper.js should handle this much better. 
@tnrich feel free to re-open if it still presents itself in 2.0.
