### ISSUE TITLE
Classname doesn't work on `Table`

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1105]
Below is my code on using `Table`

```
export const renderCell = (rowIndex) => {
  return <Cell>{`$${(rowIndex * 10).toFixed(2)}`}</Cell>;
};

export const StepsTable = (stages) => {
  return (<Table className="my-class-name-table1" numRows={stages.length}>
    <Column name="Dollars" renderCell={renderCell} />
  </Table>);
};
```

I have specified the class name on `Table` but the dom doesn't have the class name `my-class-name-table1`.

**Comment by giladgray** [comment]
@zhaoyi0113 the prop is definitely implemented correctly... https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L456-L461

have you queried the DOM for your class? it may not be on the element you expect (though it is on the root element of the table)

**Comment by zhaoyi0113** [comment]
Actually I have dumped all dom structure of the whole page but I couldn't find the class name. I found a `div` with className `bp-table-container`, is it the top-level table dom? I am importing the table from below code. Is it correct?

`import {Cell, Column, Table} from '@blueprintjs/table';
`

**Comment by giladgray** [comment]
Yes it should be on `bp-table-container`. Are you on the latest version?

**Comment by zhaoyi0113** [comment]
I am using this version:

```
"@blueprintjs/core": "^1.11.1",
    "@blueprintjs/table": "^1.9.0"
```

**Comment by giladgray** [comment]
That is not the latest. Please update and confirm

**Comment by zhaoyi0113** [comment]
Updated to the latest version fix the issue. Thanks for your suggestion.

**Comment by giladgray** [comment]
👍 this is why "version number" is the first question in our issue template
