### ISSUE TITLE
Can't set column with by `flex: 1`

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1106]
I want to set each column width based on `flex` value. But from the document I see `columnWidths` and `defaultColumnWidth` expect a value of number. How can I set the column's `flex` value? I tried to set them through css selector(see below code) but it only works for column width not for row's width. 

```
.bp-table-header{
          width: auto !important;
          flex-basis: 0 !important;
        }

        .bp-table-header:nth-child(1) {
          flex: 1;
        }
        .bp-table-header:nth-child(2) {
          flex: 2;
        }
        .bp-table-header:nth-child(3) {
          flex: 1;
        }
        .bp-table-header:nth-child(4) {
          flex: 1;
        }
        .bp-table-header:nth-child(5) {
          flex: 3;
        }
```

**Comment by gscshoyru** [comment]
Table column widths (and row heights!) are set by pixel values in the styles, and don't use flex. (You can see this by inspecting on the table cells.) A lot of the math we do in table for what cells to show and not show for virtual rendering is based on knowing these numbers, so even if you do override the styles there, you are not likely to like the results you get. 

At present, we don't support anything other than absolute pixel widths for columns and absolute pixel heights for rows.

**Comment by zhaoyi0113** [comment]
Alright, could you let me know how to handle different window sizes? How can I fill in the full size of a parent dom through `Table`?

**Comment by llorca** [comment]
@zhaoyi0113 check out the docs at http://blueprintjs.com/docs/#table-js.loading-states, we achieve this by setting `width: 100%` on `.bp-table-container`

**Comment by zhaoyi0113** [comment]
By setting `.bp-table-container` to 100% width doesn't work well for the column. It seems that `columnWidths` property is the way for me to adjust the width of each column. But it only accepts number value.  I can't make the total width of columns to be equal to the `100%` width of the table.  For example, below is the code I am using:

`<Table numRows={stages.length} columnWidths={[50, 20, 50, 20, 20]}>`

the total width of the column is 160 but the table width could be more or less than 160. How can I make the column to fill in the full width of the table?

**Comment by zhaoyi0113** [comment]
Actually, I am expecting something like: 
```
<Table numRows={stages.length} columnWidths={['30%', '10%', '30%', '20%', '10%']}>
```

**Comment by giladgray** [comment]
sounds like you want #969. duplicate?

**Comment by zhaoyi0113** [comment]
seems duplicate. Any plan on providing the fix on this?

**Comment by giladgray** [comment]
unfortunately no plans, as it's not a "fix" but an entire new feature (dynamic column widths).

**Comment by zhaoyi0113** [comment]
Alight, thanks anyway. I will try to find a worksround.
