### ISSUE TITLE
Icons16 font is removed from the font-family of the body tag

### ISSUE THREAD

**Issue by jackkainov** [palantir/blueprint#1107]
### Bug report

- __Package version(s)__: @blueprintjs/core@1.17.1

While using blueprint with webpack and css-loader, which uses css-nano for minification, font "Icons16" is removed from the body tag.

Css nano has a rule `removeAfterKeyword `
Which will remove `Icons16`, because it stands after sans-serif in `$pt-font-family` variable.
https://github.com/ben-eb/postcss-minify-font-values

The fix is simple - put `Icons16` before `sans-serif`

**Comment by llorca** [comment]
I'm pretty sure I remember us explicitly putting `Icons16` last for a reason but can't remember right now -- @giladgray should know the answer!

**Comment by giladgray** [comment]
`Icons16` is in there so you can use icon unicode strings in your text. i figured it belongs in last place, but if it works correctly in penultimate place then let's just do that. this issue has come up before, sounds like #1060.

**Comment by jackkainov** [comment]
Hi. Yes, sounds like exactly #1060, although i dig a little bit father and found an issue in using css-nano for styles minifying. I've solved issue by explicitly putting `font-family` with `Icons16` font. If a different order, accepted by default by minifies works for you too, then would be nice to change that and eliminate such issues posted here in the future :)
