### ISSUE TITLE
Text jumps around in text input in popover

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1111]
### Bug report

- __Package version(s)__: 0.15.0
- __Browser and OS versions__: Chrome  58.0.3029.110, on Mac screen
 
![jiggle_external](https://cloud.githubusercontent.com/assets/24398123/26168139/ec53a6ee-3aed-11e7-8bca-58c69afdab1d.gif)

Does happen for other fonts
Does not happen when plugged into full screen
@llorca for more details

**Comment by llorca** [comment]
I've only experienced this issue on high DPI screens (i.e. retina). No problem on 1x screens

**Comment by giladgray** [comment]
closing as stale. reopen if needed.
