### ISSUE TITLE
Is there a way to remove table cell grid lines?

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1116]
This may not be an issue. Is there an option on `Table` to remove the grid line among cells? I looked at this link http://blueprintjs.com/docs/#table-js but didn't find the answer.

**Comment by giladgray** [comment]
@zhaoyi0113 there is no such option because we're pretty into them, design-wise. if you really want to get rid of grid lines then you should be able to do it through custom CSS--they're just `box-shadow`s and removing them should not affect functionality.

**Comment by zhaoyi0113** [comment]
alright, thanks. I will try that.
