### ISSUE TITLE
Don't include sourcemaps in docs and landing distribution builds

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#112]

**Comment by adidahiya** [comment]
Also, the landing page doesn't need the blueprint JS components, just the CSS. this can save a lot of bundle size in blueprint-landing.js

**Comment by adidahiya** [comment]
I see that #67 was a good step forward, but I still see some sourcemaps in various webpacked modules in http://blueprintjs.com/blueprint-landing.js

**Comment by themadcreator** [comment]
This looks like the sourcemaps are coming from core's typescript compilation step.

**Comment by themadcreator** [comment]
[This is the line that does it ](https://github.com/palantir/blueprint/blob/master/gulp/typescript.js#L55)

**Comment by giladgray** [comment]
ah yes can we make those sourcemaps external too?
