### ISSUE TITLE
Add documentation for classes.ts

### ISSUE THREAD

**Issue by diegobfernandez** [palantir/blueprint#1126]
I see in some places you guys use classes.ts however there is no documentation on the site for it.
I think it is great and can be very useful sometimes.
My suggestion is to add the appropriate constants in each components doc page for easy reference.

**Comment by giladgray** [comment]
I can't think of a good / clean way to list the `Classes` constants for a component on its docs page. That feels like more noise than signal. However, simply mentioning `Classes` somewhere in the docs as a place where you can find all the CSS constants should be easy enough!

**Comment by giladgray** [comment]
oh hey this was done in #2325
