### ISSUE TITLE
Checkbox prop indeterminate has a bit of a confusing name

### ISSUE THREAD

**Issue by rnadrag** [palantir/blueprint#1127]
Hi all,

I came across the `Checkbox` `indeterminate` prop and I have to admit I was a bit confused by the name, wondering if `partiallyChecked` (or similar) would be a less confusing name.

Thanks

**Comment by adidahiya** [comment]
`indeterminate` is the name of the [DOM API](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Indeterminate_state_checkboxes), so that's not going to change, but maybe we could expand the prop's description to include the keyword "partial"

**Comment by rnadrag** [comment]
I see, yes, maybe this would help. Again, this is a super minor P4 thing but I do feel it is more of a `partial` state rather than `indeterminate `.

**Comment by cmslewis** [comment]
@rnadrag we don't even have `P4` as a label, so I'll promote this to `P3`. :)

**Comment by rnadrag** [comment]
Haha I see, fair enough!

**Comment by giladgray** [comment]
@rnadrag see #1132, let me know if the wording needs work

**Comment by rnadrag** [comment]
@giladgray looks good to me!
