### ISSUE TITLE
Improve typings: RadioGroup's onChange property should take a FormEvent<HTMLInputElement>

### ISSUE THREAD

**Issue by dphilipson** [palantir/blueprint#1128]
Hi Blueprint!

`RadioGroup`'s `onChange` prop has type `FormEvent<HTMLElement> => void`. Presumably it is intended that the function provided to this prop will read out the value of the selected radio button, which can be done by evaluating `event.currentTarget.value`, where `event.currentTarget` turns out to be an `<input>`. However, this fails to typecheck because `HTMLElement` does not have a value property. The correct type should be `FormEvent<HTMLInputElement>` instead, after which the above typechecks correctly.

**Comment by cmslewis** [comment]
Thanks, @dphilipson! Do you want to do this? Would be nice to have one more "external" contributor. If not, I can take it.

**Comment by dphilipson** [comment]
Sure! I might not get around to it for a day or two, but happy to contribute.

**Comment by cmslewis** [comment]
Awesome. Assigning to you!

**Comment by giladgray** [comment]
oops i just did it...

**Comment by dphilipson** [comment]
Haha, you're just too productive Gilad. Thanks for the quick turnaround!
