### ISSUE TITLE
Standalone Icons

### ISSUE THREAD

**Issue by warent** [palantir/blueprint#1130]
Would be nice if there was an officially supported package of the blueprint icons for standalone use. Is this possible?

**Comment by llorca** [comment]
Hi @warent! Current icon system is deeply tied with `core`, but I suspect we can look into it after https://github.com/palantir/blueprint/issues/365 is completed

**Comment by giladgray** [comment]
to be fair, all the icons [font files](https://github.com/palantir/blueprint/tree/master/packages/core/resources/icons) and [svg images](https://github.com/palantir/blueprint/tree/master/resources/icons) are accessible in this repo. @warent you can easily download them separately. 

note that the svg images are not published in any NPM package; they are only accessible from this git repo.

**Comment by warent** [comment]
Understood, thank you. The main benefit is if the icons were updated, I would just do a quick npm update rather than having to manually redownload. For now will just download, but in the future definitely would be a nice-to-have!

**Comment by giladgray** [comment]
there is now an `@blueprintjs/icons` package that contains the icon font and a bunch of other constants!
