### ISSUE TITLE
Turn off autocomplete by default for DateInput

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1131]
![8547208e-3bdd-11e7-805b-1086369d4220](https://cloud.githubusercontent.com/assets/24398123/26322607/a5fc11e4-3ee0-11e7-9c5f-02b5e37cef22.png)

Prevent issues like this where IE is giving autocomplete options that don't make sense for `DateInput`

**Comment by giladgray** [comment]
also NumericInput, i imagine
