### ISSUE TITLE
Switch to node-sass-chokidar

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#1134]
[create-react-app's dev guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) explains a few of the benefits (look for "Why node-sass-chokidar?"). Also see the [package README](https://www.npmjs.com/package/node-sass-chokidar).

**Comment by dmackerman** [comment]
Curious what you guys typically see as build times for your SASS? It's definitely the slowest part of the webpack build for us, so I'm always looking for ways to speed that up.

**Comment by giladgray** [comment]
@dmackerman we compile sass outside of webpack because I have found that the webpack sass-loader pipeline is _very slow_. this also allows the JS and CSS to be re-compiled independently (definitely improves recompile times).

Compilation times are pretty quick in gulp, and most run in parallel:
```
[10:52:14] Finished 'sass-core' after 2.39 s
[10:52:15] Finished 'sass-site-landing' after 732 ms
[10:52:15] Finished 'sass-docs' after 1.06 s
[10:52:15] Finished 'sass-table' after 1.06 s
[10:52:15] Finished 'sass-datetime' after 1.23 s
[10:52:16] Finished 'sass-site-docs' after 799 ms
```

**Comment by dmackerman** [comment]
@giladgray That makes sense. Might look into using a separate gulp task for SCSS in dev.
