### ISSUE TITLE
EditableText exits edit mode, even if isEditing is set to true

### ISSUE THREAD

**Issue by Que3216** [palantir/blueprint#1137]
Version: 1.17.1

If you have:

```
<EditableText
    isEditing={true}
 />
```

Then you'd expect it to be impossible for the user to get out of the editing state.

However if the user hits enter, it'll leave the editing state.

This makes it impossible to validate user input.

**Comment by llorca** [comment]
@Que3216 try using the different callbacks provided to control/validate user input: `onCancel`, `onChange`, `onConfirm`, `onEdit`

**Comment by giladgray** [comment]
not enough information
