### ISSUE TITLE
Isn't the pt-icon-key-delete supposed to point to the left?

### ISSUE THREAD

**Issue by rclai** [palantir/blueprint#1138]
### Bug report

- __Package version(s)__: All
- __Browser and OS versions__: Any

#### Steps to reproduce
Just look at it.

#### Actual behavior

Points to the right

#### Expected behavior

Points to the left

**Comment by llorca** [comment]
For reference:
![image](https://cloud.githubusercontent.com/assets/199754/26371205/ed7ecf24-3fae-11e7-90a0-da5ccc6b517e.png)

I think the current icon is accurate. "Delete" removes characters from the right, whereas "Backspace" removes characters from the left. Note that we also have an icon for "Backspace":
![image](https://cloud.githubusercontent.com/assets/199754/26371457/a6556968-3faf-11e7-80e3-fff2dd489de7.png)

Worth noting that some keyboards use the same icon than ours for "Delete":
![image](https://cloud.githubusercontent.com/assets/199754/26371316/3e657e60-3faf-11e7-97e1-df654eea3546.png)

**Comment by rclai** [comment]
Oh didn't see the backspace icon, thanks.
