### ISSUE TITLE
Add isFocused to EditableText

### ISSUE THREAD

**Issue by pwilczynski** [palantir/blueprint#1142]
- __Package version(s)__: 1.11.1

I'm trying to create an `EditableText` field which has the same behavior as Github Issues, but Editable Text cannot support both Enter and Shift + Enter for newline, and `onConfirm` gets triggered when users click outside the `EditableText` component.

My desired behavior:
- _Enter_: creates a new line
- _Enter + Shift_: creates a new line
- _Enter + CTRL or CMD_: confirm
- _Clicking outside the component_: lose focus

Currently, this behavior is handled by a combination of:

- `confirmOnEnterKey`
- `isEditing`
- `onConfirm`
- `onCancel`

The current model, however, does not provide consumers with a way to differentiate between losing focus and confirming.

**Comment by giladgray** [comment]
@pwilczynski i don't understand the specific feature request here, but i'm quite sure that `isFocused` is not the correct solution: controlling HTML focus state through React is a recipe for disaster. can you clarify what sorts of changes would enable your use case?

**Comment by pwilczynski** [comment]
@giladgray - Here's a fiddle of the rough UI I'm trying to implement; it's basically the same as the Github Editable Text feature where clicking off of the text doesn't exit edit mode, and instead there is a "Add Comment" button, which is also triggered with CMD-Enter.

Does that make sense?

https://jsfiddle.net/4kqphf7t/

**Comment by pwilczynski** [comment]
@giladgray thinking about this more, it's probably out of scope for `EditableText` the real feature that I'm probably looking for is more like `InputText` where the behavior is more like a traditional input, but with your bound key shortcuts and nice scrolling and line controls that `EditableText` has. Rather than onConfirm being triggered onBlur, I would imagine that onConfirm would only trigger with CMD-Enter or Enter depending on whether `confirmOnEnterKey` was set.

This fiddle is a quick and dirty version of what I'm thinking of: https://jsfiddle.net/4kqphf7t/

Does that make sense?

**Comment by llorca** [comment]
Sounds like a `textarea` with an autoresize behavior based on content. The cmd+enter shortcut seems like a custom shortcut for that particular use case

**Comment by giladgray** [comment]
@pwilczynski It seems like you're using `EditableText` for the autosize behavior only, but ET provides much more than that (and enforces specific interactions). In the short term, you may have better results using some [react autosize component](https://www.google.com/search?q=react+autosize&oq=react+autosize) for that specific piece and implementing your own interactions. You can always slap a `.pt-input` on it and get the expected visuals.

**Comment by pwilczynski** [comment]
Yeah, @giladgray that sounds like the right solution. Thanks so much for your support, that worked great.
