### ISSUE TITLE
Rename InputGroup to Input

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#1147]
There's an opportunity to simplify this naming by merging input and input groups together into `Input` or `TextInput`. They're really the same thing. Thoughts?

**Comment by giladgray** [comment]
`Input` seems sufficient to me. The Blueprint `Input` is simply more awesome than HTML's `<input>`; ours supports left icons and right elements!

**Comment by dmackerman** [comment]
I like the change. We wrap `InputGroup` internally as `Input`, and essentially it's just a passthrough.

**Comment by giladgray** [comment]
sticking with `InputGroup` to clarify that it's not just an `Input`.
