### ISSUE TITLE
Does an input text component support input masks?

### ISSUE THREAD

**Issue by nomadus** [palantir/blueprint#1148]
Does an input text component support input masks? e.g. credit card number, xxxx-xxxx-xxxxx-xxxx

**Comment by llorca** [comment]
That is not currently supported

**Comment by nomadus** [comment]
That was a quick answer! Thank you!

**Comment by sesm** [comment]
@nomadus you could use something like `Cleave.js` and use Blueprint's CSS classes for styling.

**Comment by giladgray** [comment]
closing as stale. plenty of other libraries that you can compose with blueprint to achieve this.
