### ISSUE TITLE
pt-small hides icons for buttons with no content

### ISSUE THREAD

**Issue by greglo** [palantir/blueprint#1153]
Here is a button group I have:
![image](https://cloud.githubusercontent.com/assets/2872321/26508164/761803f4-4208-11e7-94ff-42fdf6caab09.png)

Here is what it looks like if I add `pt-small` to the container with class `pt-button-group`:
![image](https://cloud.githubusercontent.com/assets/2872321/26508185/8d928da6-4208-11e7-88a1-8fdfda9dfaa1.png)

Perhaps the icon should not be hidden if there is no text?

**Comment by giladgray** [comment]
Small icons do not support buttons; this is mentioned in the docs. The
icons are too late for small buttons.

Sorry but your use case is not supported natively.

**Comment by adidahiya** [comment]
What should we do here then? Segmented buttons with advanced options in a dropdown next to the main action are pretty common for us.

**Comment by pkwi** [comment]
Ideally, we would keep caret icons in small buttons. These are required for segmented buttons and don't suffer from the small button/icon size issue.

**Comment by llorca** [comment]
@pkwi so allow carets only and disable other icons?

**Comment by pkwi** [comment]
It's basically one icon that we make visible at any size. To make segmented buttons available at all sizes.
