### ISSUE TITLE
Empty pages in docs

### ISSUE THREAD

**Issue by waltonseymour** [palantir/blueprint#1158]
http://blueprintjs.com/docs/#core/components/progress appears blank:

![screen shot 2017-05-30 at 1 43 46 pm](https://cloud.githubusercontent.com/assets/7594493/26596820/08199c8a-453e-11e7-8432-834c10bc18e9.png)

**Comment by giladgray** [comment]
this is expected: Progress is a page group that only contains other pages. Progress bars, Spinners, and Skeletons have the actual docs for those components. 

this will be resolved by some upcoming docs design work.

**Comment by waltonseymour** [comment]
Ah didn't realize that. Thanks.
