### ISSUE TITLE
Speed up CI builds with parallelization

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#116]
As a first stab, we should investigate if we can run the different packages' unit tests in different containers.

**Comment by adidahiya** [comment]
Also, let's avoid running unit tests when only `packages/landing` has changed.

**Comment by llorca** [comment]
@adidahiya Is it fair to add this to the 2.0 milestone? I suppose it'll be very much needed when we integrate upcoming 2.0 things to the current repo, right?

**Comment by adidahiya** [comment]
I wouldn't say it's urgent or necessary for 2.0; we should look into it as time allows or if our builds start getting very slow. Right now we're at ~5min, which seems ok, but if they creep up to 7+ min, this will get more important.
