### ISSUE TITLE
Improve reordering column/row visuals

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1161]
- [x] Extend the line into the header
- [X] Thicken the line for visibility [won't do]

Per feedback from: https://pl.ntr/fk

**Comment by llorca** [comment]
> Extend the line into the header
👍 

> Thicken the line for visibility
👎

**Comment by cmslewis** [comment]
Agree with @llorca at first glance.

**Comment by cmslewis** [comment]
Seems fixed now! (Table v1.27.0)

![2017-10-04 19 25 37](https://user-images.githubusercontent.com/443450/31208446-d8534fd6-a939-11e7-80e4-6292e102a965.gif)
