### ISSUE TITLE
Weird focus actions when combine redux-form Field with Blueprint Dialog

### ISSUE THREAD

**Issue by JuoCode** [palantir/blueprint#1166]
### Bug report

- __Package version(s)__: 1.18.0
- __Browser and OS versions__: Chrome 58.0.3029.110, macOS 10.12.3

#### Steps to reproduce

1. Wrap a form that contains two InputGroup use redux-form
1. Render wrapped form into Dialog
1. Click the first input
1. Click the second input

#### Actual behavior
When click the second input, first input is blur, but the second input not focus.

#### Expected behavior
The second input should focus when first input blur

#### Fixes
Set the Dialog's autoFocus to false can fix this problem.

**Comment by giladgray** [comment]
This is in fact expected behavior, and `<Dialog autoFocus={false}>` is the correct solution. Glad you found it.
