### ISSUE TITLE
[Table] Add drag handle to interaction bar 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1173]
Per mocks 
![f1- drag- hover 1](https://cloud.githubusercontent.com/assets/24398123/26656756/44fd6c08-4615-11e7-96ba-c8f8b2ecfef9.png)
![f2- drag- active](https://cloud.githubusercontent.com/assets/24398123/26656757/45ce29c4-4615-11e7-8062-dd6439b30be2.png)

Possibility of adding something to the non-interaction bar table as well, but not scoped here

**Comment by cmslewis** [comment]
Closed via #1250
