### ISSUE TITLE
Add option to swap month and year in the header of the date components' calendar view

### ISSUE THREAD

**Issue by qcz** [palantir/blueprint#1174]
In some locales (e.g. Hungarian) the year precedes the month. Currently there is no way (AFAIK) to swap these in the header of the calendar view of blueprint datetime components.

![chrome_2017-06-01_14-58-32](https://cloud.githubusercontent.com/assets/304384/26680938/914a93c6-46db-11e7-89f1-2c980a7c2701.png)

Built in Chrome datepicker input:
![kep](https://cloud.githubusercontent.com/assets/304384/26680989/c7f9c5b8-46db-11e7-872f-f7a745bac13e.png)
Built in Edge datepicker input:
![kep](https://cloud.githubusercontent.com/assets/304384/26681004/d65c11d8-46db-11e7-9679-ec85cda8948f.png)

**Comment by cmslewis** [comment]
Hi @qcz, do clarify, do you mean swapping the positions of the month and year dropdown menus?

`[year ▼] [month ▼]`

**Comment by qcz** [comment]
@cmslewis: Yes.

**Comment by giladgray** [comment]
@qcz the team will not have bandwidth to implement this anytime soon. I wonder if this is possible in the short term with a wee bit of CSS (on your end) to flip the position of the two `<select>` elements?

**Comment by qcz** [comment]
@giladgray: I do not like to use hacky solutions like that as they tend to broke when components are refactored or improved. But as you accept PRs for this, I'll try to implement a solution.
