### ISSUE TITLE
InputGroup should have maxLength property

### ISSUE THREAD

**Issue by cjjojoba** [palantir/blueprint#1175]
Like EditableText, it should have a maxLength property.

**Comment by giladgray** [comment]
`InputGroup` supports all HTML props so this is already implemented. @cjjojoba did you try it?

![image](https://cloud.githubusercontent.com/assets/464822/26696814/d2918716-46c4-11e7-8ede-cc894e016c1b.png)

**Comment by giladgray** [comment]
`InputGroup` supports all HTML `<input>` props (this is mentioned in the docs) so this is already implemented. @cjjojoba did you try it first?

![image](https://cloud.githubusercontent.com/assets/464822/26696814/d2918716-46c4-11e7-8ede-cc894e016c1b.png)

**Comment by cjjojoba** [comment]
@giladgray didn't know, thanks!
