### ISSUE TITLE
Tooltips never disappear with disabled buttons

### ISSUE THREAD

**Issue by thasner** [palantir/blueprint#1179]
### Bug report

- __Package version(s)__: "@blueprintjs/core": "^1.17.1",
- __Browser and OS versions__: Chrome on Mac Sierra 10.12.5

#### Steps to reproduce

```
<Tooltip content="Please go away">
    <Button disabled={true} intent={Intent.DANGER} text="scary"  />
</Tooltip>
```

1) Hover over button
2) Un-hover

#### Actual behavior

stays forever

#### Expected behavior

goes away

**Comment by qcz** [comment]
I just had the same problem. Use AnchorButton instead of Button.
See: #967

**Comment by adidahiya** [comment]
![image](https://cloud.githubusercontent.com/assets/723999/26692967/94e354ba-46d0-11e7-9b38-c8eeb962b180.png)

**Comment by thasner** [comment]
interesting, thanks all
