### ISSUE TITLE
Closing a Popover that is in a Dialog should not remove 'pt-overlay-open' from the document body

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#1182]
### Bug report

- __Package version(s)__:  1.18.0
- __Browser and OS versions__: all

#### Steps to reproduce

create a dialog with a popover inside:
```
<Dialog isOpen>
     <Popover
        content='Popover text content'
      >
          <Button>
                popover target
          </Button>
     </Popover>
</Dialog>
```
#### Actual behavior

When the dialog opens it adds the class 'pt-overlay-open' to document.body so that the body doesn't scroll while the dialog is open. However, if you open and close a popover in the dialog it removes the class from the body even though the dialog is still open.

#### Expected behavior

The pt-overlay-open class should not be removed if the dialog is still open.

**Comment by giladgray** [comment]
oh snap sounds like a job for the `Overlay` stack.
