### ISSUE TITLE
Move table locator from state

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1186]
The Table's locator is in the state, which means when the Table mounts, the locator isn't necessarily set yet. This means apps can't do things like `resizeByTallest` on mount, which is unideal

**Comment by giladgray** [comment]
i feel like a logical step is missing in this issue... locator living in state (or not) should have no bearing on its existence at mount time--that can be achieved correctly in both cases (probably in `componentWillMount`). 

what's the real problem here?

**Comment by gscshoyru** [comment]
Not quite clear, sorry -- the locator is set in the state of table's componentDidMount (which it needs to be because it needs the DOM elements) -- and so we call setState in componentDidMount. The problem is that it's not immediately propogated to the state when we do that (obviously) so if a parent tries to a function that uses it in _its_ componentDidMount it won't work. 

I'm not sure why the locator is in the state in the first place though, honestly -- it probably shouldn't be.

**Comment by giladgray** [comment]
why is it set in `componentDidMount` vs `componentWillMount`? state properties that are needed at render time should use `Will`.

**Comment by gscshoyru** [comment]
@giladgray it needs access to the DOM elements, as stated above. It can't get at those except via ref's, so it can't be added until after mount. 

With that said -- I'm not sure if it needs to be in state or not. My original thought when first discussing this is that it really shouldn't be -- but to some degree, putting it in state allows the table to re-render to pass it down to the children. I'm not sure how to make it re-render, doing that, without it being in state. 

That said: we can put it in both places without a problem. 

To be clear on what it's used for -- it's used for locating positions of things (clicks) and sizes of things on events (clicking, selecting, etc). It's not actually used to render the table itself.

**Comment by adidahiya** [comment]
> The problem is that it's not immediately propogated to the state when we do that (obviously) so if a parent tries to a function that uses it in its componentDidMount it won't work

can you point to some code for this? who's trying to access the locator/

**Comment by gscshoyru** [comment]
@adidahiya we have a consumer of Blueprint that wants to call `resizeByTallest` immediately on render -- in `componentDidMount`. `resizeByTallest` wants the locator.
