### ISSUE TITLE
FR Blueprint Table: Add drag handle into header cell

### ISSUE THREAD

**Issue by Que3216** [palantir/blueprint#1189]
Currently you can't just drag a column. You have to select it, release the mouse, and then re-drag. Our users are finding this confusing.

Would it be possible to add a prop that changes the behavior of the table, so that you can drag columns without selecting them first?

Maybe if the selection mode is set to disable selection of columns, then the table could behave like this automatically.

**Comment by adidahiya** [comment]
Makes sense, we'd take a PR for this.

**Comment by cmslewis** [comment]
I was just starting to think about this last week; definitely agree that this should be a thing. There's a fair bit of rejiggering we'd have to do in the code, but it seems doable without too much headache.

**Comment by Que3216** [comment]
Sweet! For now we've done a bunch of rather fragile CSS hacks in Hubble to replicate this behavior by leveraging the new interaction bar. Would be great to get rid of these hacks though. I think you're right that a lot of Palantir products will want this.

**Comment by cmslewis** [comment]
Fixed this to an extent in #1250. The interaction bar needs to be enabled though. @tgreenwatts @llorca what do you think?

**Comment by llorca** [comment]
@cmslewis Yeah we can close this out now, solved with the interaction bar

**Comment by Que3216** [comment]
When the column headers are not editable etc. the interaction bar is not
the right UX. The whole header should be draggable.

**Comment by tgreenwatts** [comment]
Reopening to track adding the drag handle into the header cell when there is no interaction bar

Not currently prioritized

**Comment by tgreenwatts** [comment]
Some css hackery we've seen to get this done

```/*
   * We override a bunch of Blueprint table classes,
   * in order to make the full column title draggable,
   * even when the column isn't selected.
   *
   * Tracking here: https://github.com/palantir/blueprint/issues/1189
   */
  .bp-table-column-name {
    flex-direction: row;
  }

  .bp-table-column-headers .bp-table-interaction-bar {
    display: flex;
    align-items: center;
    height: 100%;
    position: absolute;
    width: 100%;
  }

  .bp-table-reorder-handle-target {
    position: inherit;
    width: 100%;
    height: 100%;
    top: inherit;
    display: flex;
    align-items: center;
  }

  .bp-table-column-name-text {
    margin-left: @pt-grid-size;
    margin-right: @pt-grid-size * 2.5;
  }

  .bp-table-interaction-bar .bp-table-th-menu-container {
    margin-right: @pt-grid-size / 2;
    line-height: @pt-grid-size * 3;
    opacity: 1;
    display: flex;
  }

  .bp-table-interaction-bar .bp-table-th-menu-container-background {
    display: none;
  }```
