### ISSUE TITLE
IE11: In non-ideal state, long description text doesn't wrap

### ISSUE THREAD

**Issue by AlexLandau** [palantir/blueprint#1193]
### Bug report

- __Package version(s)__: 1.18.0
- __Browser and OS versions__: IE 11.916, Windows 10

#### Steps to reproduce

Create any non-ideal state page with a sufficiently long description text, or alternatively:

1. Open http://blueprintjs.com/docs/#core/components/non-ideal-state in IE
2. In the example non-ideal state, replace (via F12 developer tools) the sample text "Create a new file to populate the folder." with something much longer.

#### Actual behavior

The text doesn't wrap:

<img width="1302" alt="screen shot 2017-06-05 at 5 56 28 pm" src="https://cloud.githubusercontent.com/assets/5733346/26809279/64112b32-4a18-11e7-9296-bd4d789bf032.png">

#### Expected behavior

The text wraps like in other browsers.

Among the possible fixes here is adding a "max-width: 100%" style to the .pt-non-ideal-state-description class.

**Comment by tgreenwatts** [comment]
😱

**Comment by llorca** [comment]
I can look at it later when I get my hands on a Windows machine, otherwise would gladly accept a contribution
