### ISSUE TITLE
Visually jarring button default button styles

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1195]
The default disabled button styles are jarring when used in a button group:

![screen shot 2017-06-06 at 2 24 28 pm](https://user-images.githubusercontent.com/3681045/26845397-5fc80e7c-4ac4-11e7-9b6a-211eb9b46136.png)

In the above component, both clicked and un-clicked buttons have a slight 3D feel due to the color gradient. The disabled button on the end is absolutely flat and doesn't visually belong here. Is it possible to either:

- make default buttons flat
- make default disabled buttons not-flat

**Comment by adidahiya** [comment]
I don't really see a problem with the disabled button being flat... maybe we could add a light border on it?

**Comment by giladgray** [comment]
border could help, but i think it's pretty clear that that button is not interactive.

**Comment by llorca** [comment]
Our main principle here is that if a button is interactive, we have affordances such as very lightweight gradient and shading; if it's not interactive, we remove those affordances. Making a disabled button 3D or a regular button flat would go opposite of our principle.

Gonna close this out as we don't plan on changing just a single state -- if we iterate, it'll be part of a larger button redesign.
