### ISSUE TITLE
Text align vertically center in cell

### ISSUE THREAD

**Issue by raviteja83** [palantir/blueprint#1213]
Vertical center align text in cells when the default height is increased. currently it is positioned absolutely at top: 0. is there any possible way to change this? Also cell className prop is not used.

**Comment by giladgray** [comment]
@raviteja83 can you implement this with some custom css in your app? worst case, add your own `<div class="my-custom=class">` around the content to position it as desired.

**Comment by tgreenwatts** [comment]
I think this is possible already, so closing this.
