### ISSUE TITLE
[Table] EditableCell doesn't grow to match the row like EditableName does with defaultRowHeight set

### ISSUE THREAD

**Issue by seansfkelley** [palantir/blueprint#1235]
### Bug report

- __Package version(s)__: core: 1.20.0, table: 1.17.0 
- __Browser and OS versions__: Chrome 58.0.3029.110, OS X 10.12.5

#### Steps to reproduce

```jsx
<Table numRows={1} defaultRowHeight={30}>
    <Column
        name="foo"
        renderCell={() => <EditableCell/>}
        renderColumnHeader={() => <ColumnHeaderCell renderName={() => <EditableName/>} />}
    />
</Table>
```

#### Actual behavior

Header has the right size:

![image](https://user-images.githubusercontent.com/2101409/27131948-3cf689e2-510d-11e7-9df8-86e4a2d694f2.png)

But the cell doesn't:

![image](https://user-images.githubusercontent.com/2101409/27131970-49c55ec8-510d-11e7-8e41-a35554ea1118.png)

#### Expected behavior

`EditableCell`s grow to fit the size of their containing row.

This is extra sad because then the click target for the editable area is small even if the row is very large.

**Comment by gscshoyru** [comment]
To be clear, if we do this, it's going to look something like this: 

<img width="231" alt="screen shot 2017-10-05 at 11 41 37 am" src="https://user-images.githubusercontent.com/2463526/31236528-507ce3f4-a9c2-11e7-8ff2-ef87d6e45ad4.png">

Is that really what we want? @llorca

**Comment by gscshoyru** [comment]
To be clear -- none of the text goes onto other lines, there, it's all on one line, even with all the vertical space.

**Comment by llorca** [comment]
@gscshoyru yeah that makes sense to me. One liner as a default, but theoretically text could wrap onto multiple lines if wrapping enabled

**Comment by gscshoyru** [comment]
@llorca -- well, right now we just have `input`s -- we'd need `textarea` to be able to do wrapping -- something to look into later -- but yeah, just wanted to be sure.
