### ISSUE TITLE
Shift + ? does not dismiss hotkeys dialogs

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1238]
Shift + ? shows the hotkeys dialog but does not dismiss it.

From @gjavitt:

> shift + ? should dismiss, but there should also be a pt-icon-cross in the top right or a dismiss button, probably the former

**Comment by llorca** [comment]
Wouldn't mind `shift+?` acting as a toggle. Cross / dismiss button aren't necessary as you can already either press `esc` or click outside

**Comment by gjavitt** [comment]
Does clicking on the backdrop also dismiss?
I was worried about less technical users getting stuck here and not figuring out how to dismiss it. Have met users who don't use their keyboards if they can avoid it.

**Comment by llorca** [comment]
Yes, that's what I meant by "clicking outside", i.e. clicking on the backdrop

**Comment by gjavitt** [comment]
Ah, misread. sgtm

**Comment by cmslewis** [comment]
Taking a look at this now.
