### ISSUE TITLE
[DateInput] Today's date looks like it's selected but is in fact not

### ISSUE THREAD

**Issue by marwahaha** [palantir/blueprint#1246]
### Bug report

- __Package version(s)__: 1.20.0
- __Browser and OS versions__: Chrome 58.0.3029.110

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/#datetime/dateinput
2. Set precision to something (not None)
3. Click on input and remove date
4. Click away and click again on (empty input)

#### Actual behavior

5. Today's date is "selected" on the calendar

#### Expected behavior

5. Today's date is not "selected" on the calendar.

You can contrast this with skipping step 2, and seeing no bug.
![dateinput](https://user-images.githubusercontent.com/2541209/27236155-c2cab838-5291-11e7-9176-aa7ab2c52abd.gif)

**Comment by llorca** [comment]
Uh oh, good catch. We'll look at it next week, hopefully it's a quick fix

**Comment by cmslewis** [comment]
Update: after investigating, looks like `this.state.value` _is_ being updated properly on deselect, but `this.state.valueString` is not. On it.

**Comment by marwahaha** [comment]
Hi @cmslewis @llorca , I tried my reproduction steps on the Blueprint website and it still wasn't working. Can you re-open this?

**Comment by cmslewis** [comment]
Yep, looks like it reselects today's date when the popover is reopened. Dang.

**Comment by lintardec** [comment]
Hi @cmslewis @llorca,

I'm seeing the same issue in the DateTimePicker component

blueprintjs/datetime package : 2.0.3

when my props.value is undefined the current date is selected
>    <DateTimePicker
>        value={isUndefined(props.value) ? undefined : props.formattedStringToDate(props.value)}
>        onChange={(selectedDate: Date, isUserChange: boolean) =>
>        props.updateQueryData(props.name, props.dateToFormattedString(selectedDate))}
>    />
unlike using DatePicker
>    <DatePicker
>        value={isUndefined(props.value) ? undefined : props.formattedStringToDate(props.value)}
>        onChange={(selectedDate: Date, isUserChange: boolean) =>
>        props.updateQueryData(props.name, props.dateToFormattedString(selectedDate))}
>    />

should this be raised as a new bug?
