### ISSUE TITLE
[Table] Editable ColumnHeaderCell shows old value after reordering columns

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1257]
### Bug report

- __Package version(s)__: v1.20.0
- __Browser and OS versions__: Chrome 59 on OS X Sierra

#### Steps to reproduce

1. Enable column-name editing and column reordering.
2. Reorder some columns.

#### Actual behavior

The body content updates (even if the body content is editable), but the column header content does not update.

![reorder-bug](https://user-images.githubusercontent.com/443450/27400905-89b4d806-5676-11e7-951c-4d28ef0ae0aa.gif)

#### Expected behavior

Both the body content and header content update properly after reordering.

![reorder-expected](https://user-images.githubusercontent.com/443450/27400883-762d883c-5676-11e7-9e39-545f95b120c4.gif)

**Comment by cmslewis** [comment]
Related to #1234?

**Comment by backnotprop** [comment]
Seeing a lot of strange behavior when passing in new columns (removing old, adding new) and the table relying on old state... not sure if this is related to this problem or many others.

**Comment by adidahiya** [comment]
this is an old issue, i'm going to close it for now... @backnotprop I think your issues are probably related to a bunch of others around table lifecycle bugs in v3.8.x... see the milestone: https://github.com/palantir/blueprint/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22table+3.8.x%22

for now, I would recommend downgrading to table v3.7.x (latest core version should work with this range just fine)
