### ISSUE TITLE
[Table] Scrolling quickly from high-numbered to low-numbered rows ruins alignments

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1259]
### Bug report

- __Package version(s)__: v1.20.0
- __Browser and OS versions__: Chrome 59 on Mac OS X Sierra

#### Steps to reproduce

1. Scroll quickly from a high-numbered, multi-digit row to a low-numbered, fewer-digit row (by clicking and dragging the scroll bar pill, e.g.).

#### Actual behavior

Column header alignment gets out of sync until you scroll again:
![scroll-bug](https://user-images.githubusercontent.com/443450/27402039-25d938e6-567a-11e7-8c21-b403a1d88dad.gif)

#### Expected behavior

Column headers remain aligned with cells.

**Comment by tgreenwatts** [comment]
Is this still true @cmslewis ?

**Comment by cmslewis** [comment]
@tgreenwatts yep
