### ISSUE TITLE
[Table] Add callback for viewport changes to public API

### ISSUE THREAD

**Issue by themadcreator** [palantir/blueprint#1260]
Users who want to use the loading state as a standin for loaded data need to know what data to load based on the visible cells in the viewport.

We currently use the `viewportRect` and `Grid` to update the visible cell indices internally, but we should also expose these values in a callback so users can kick off a data load.

I propose a prop on `<Table>` like this:
```tsx
onVisibleCellsChange?: (rowStartIndex: number, rowEndIndex: number, colStartIndex: number, colEndIndex: number) => void;
```

**Comment by cmslewis** [comment]
Seems valuable to me. 👍
