### ISSUE TITLE
[Table] Resolve differences between <EditableCell> and <EditableName>

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1262]
### Bug report

- __Package version(s)__: v1.20.0

### Changes proposed

There are some differences between `EditableCell`  and `EditableName` that we should resolve:
- Should emit the `columnIndex` as a second parameter in `onCancel`, `onChange`, and `onConfirm` callbacks
- Should fully control the value so that updating `props.name` actually renders the new name. (See: #1257, #1234)

**Comment by gscshoyru** [comment]
Note: so far as I can tell, doing the first part here is going to require cloning the results of renderName the same way we do for table cells, so it knows what index it is. Is this alright? I'm somewhat loathe to do more cloning, 'cause I know it tends to impact perf.
