### ISSUE TITLE
[Table] Fix behavior when reordering multiple disjoint selections 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1273]
### Bug report

- __Package version(s)__: v1.21.0
- __Browser and OS versions__: Chrome 59 on Mac OS X Sierra

#### Steps to reproduce

1. `Cmd + Click` to select multiple disjoint columns.
1. Drag to reorder them.

#### Actual behavior

Not all of the columns come along for the reordering ride, and the result is a weird selected state after the fact (particularly if you reorder a column that was _not_ the most recently selected one).

_Example:_ If you reorder a column that _was_ the most recently selected one:
![reorder-disjoint2](https://user-images.githubusercontent.com/443450/27490593-bbbff99c-57f3-11e7-8e77-817ae9a2f5ba.gif)

_Example:_ If you reorder a columns that was _not_ the most recently selected one:
![reorder-disjoint](https://user-images.githubusercontent.com/443450/27490517-6b17c560-57f3-11e7-8168-9ca16e63e357.gif)

#### Expected behavior

(Suggestion:) all disjoint selections are joined into one, then the clump is reordered to the new index?

**Comment by llorca** [comment]
+1 with expected behavior 💯
