### ISSUE TITLE
Mobile styling issues with docs

### ISSUE THREAD

**Issue by jasonm23** [palantir/blueprint#128]
Noticed that the docs pages aren't displayed properly on my mobile device 

![screenshot_2016-11-13-14-56-11-322_com android chrome](https://cloud.githubusercontent.com/assets/71587/20244180/c5d64efe-a9b1-11e6-8026-4f2c34814951.png)

**Comment by jasonm23** [comment]
This is Chrome on Android  (up to date versions as of today)

**Comment by phereford** [comment]
This same issue presents itself in the latest version of mobile safari as well.

**Comment by jasonm23** [comment]
iOS Chrome on iPhone 6 confirmed

**Comment by adidahiya** [comment]
should be fixed by #148 and #121
