### ISSUE TITLE
Month picker

### ISSUE THREAD

**Issue by diegobfernandez** [palantir/blueprint#1280]
I would like to request a new feature. I have some date filtering to do regarding the graphics that are on my app's dashboard, but my data are aggregated monthly.
Since there are no need to show a calendar with days on it, I would like to have a date range picker that the user selects only the months. It doesn't really matter if the final value are "real" dates with days on it.

**Comment by cmslewis** [comment]
Hi @diegobfernandez, interesting thought. Take a look at the range of designs that Google Images returns when searching for "month picker ui": [link](https://www.google.com/search?q=month+picker+ui&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiKtt2j-dvUAhVI-2MKHVQ4AloQ_AUICigB&biw=1440&bih=799). It's not clear to me that any of those is appreciably better than a simple pair of native `<select>`s: one for month selection and one for year selection.

Are there any drawbacks with that approach for your use case?

**Comment by llorca** [comment]
Yeah, seems like this is solved by a pair of `<select>` elements, or even better our new `<Select>`. I don't see any UI work required on our side

**Comment by diegobfernandez** [comment]
So, my main problem is that I want a range of months and 4 `<select>`s seem too much. Besides the month range I have a lot of filters available.
In summary, I'm working on a picker based on `RangeSlider`.
As soon as I get a nice version working I will post a link to a gist.

**Comment by llorca** [comment]
Awesome! I'm gonna close this issue as there's no work required from the Blueprint team, but if you find a bug or any other problem, please feel free to open a new issue. 👍
