### ISSUE TITLE
[Hotkeys] Change "meta" to "cmd" or "command"

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1281]
![pasted image at 2017_06_26 11_50 am](https://user-images.githubusercontent.com/3681045/27548423-ed1dd714-5a66-11e7-89e6-330300ca0ec1.png)

While most mac users already know what this icon means, the text would be better as "cmd" or "command" since keyboards do not have a key named "meta".

**Comment by tgreenwatts** [comment]
+1, I didn't know what it was and it's a little confusing for novice users

**Comment by michael-yx-wu** [comment]
> I think what we want is `[ Ctrl ] [ K ]` not `[ ^ ctrl ] [ K ] `
> and `[ Cmd ] [ K ]` on Mac
> @markschafer

I agree we may want to get rid of the `^` for Windows but I think we should keep the command icon on Mac.

**Comment by markschafer** [comment]
Here's a screenshot of what it currently looks like on PC:
![Uploading image.png…]()

**Comment by markschafer** [comment]
Summarizing desired changes:

- Mac: `[⌘ Cmd ] [ K ]`
- PC: `[ Cmd ] [ K ]`
- make button heights the same

**Comment by giladgray** [comment]
@markschafer  PC: `[ Ctrl ] [ K ]` I think, not cmd.
