### ISSUE TITLE
[Table] Investigate why cell dividers are lost in zebra striping example

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1286]
<img width="405" alt="image 7" src="https://user-images.githubusercontent.com/24398123/27559896-129ad478-5a77-11e7-977a-759217c709f6.png">

**Comment by cmslewis** [comment]
Seems fixed now.

![image](https://user-images.githubusercontent.com/443450/31208324-dde31d7e-a938-11e7-9676-a71f251e83f7.png)
