### ISSUE TITLE
Tag's onClick's parameter has the wrong type

### ISSUE THREAD

**Issue by seansfkelley** [palantir/blueprint#1293]
### Bug report

- __Package version(s)__: core 1.21.0

#### Steps to reproduce

```
<Tag onClick={(e: React.MouseEvent<HTMLElement>) => console.log(e)}/>
```

#### Actual behavior

```
...
  Type '(e: MouseEvent<HTMLElement>) => void' is not assignable to type 'EventHandler<MouseEvent<Tag>>'.
    Types of parameters 'e' and 'event' are incompatible.
      Type 'MouseEvent<Tag>' is not assignable to type 'MouseEvent<HTMLElement>'.
        Type 'Tag' is not assignable to type 'HTMLElement'.
          Property 'accessKey' is missing in type 'Tag'.
```

#### Expected behavior

The type of the parameter to the callback is `React.MouseEvent<HTMLElement>` or perhaps `React.MouseEvent<HTMLSpanElement>`. `React.MouseEvent<Tag>` is incorrect; the callback is going to receive a reference to the DOM element and not the React component. This appears to have erroneously changed in abb4f5d5e12e97b92df6b1bfc4b2518d2971eed6.

**Comment by cmslewis** [comment]
Thanks @seansfkelley. I'll let @giladgray chime in, since he has the most context here.

**Comment by giladgray** [comment]
@seansfkelley I'm confused... nowhere does the prop mention `MouseEvent<Tag>` (nor is that even valid React--gotta be a DOM node). The change linked above changed type from `HTMLSpanElement` to `HTMLButtonElement` to correctly represent that actual DOM element used.

**Comment by seansfkelley** [comment]
It's because it extends from `HTMLAttributes`: https://github.com/palantir/blueprint/commit/abb4f5d5e12e97b92df6b1bfc4b2518d2971eed6#diff-fec26cef1dfe0e5b893fc0a34c69f7faR17

**Comment by giladgray** [comment]
oh snap
