### ISSUE TITLE
[Popover in Dialog] can't scroll to view full content when popover is in dialog and popover's content out of viewport

### ISSUE THREAD

**Issue by liesislukas** [palantir/blueprint#1312]
### Bug report

if popover is inside dialog and user clicks to open it and popover is out of viewport user can't scroll to see contents.

It's more bug of dialog itself while it renders position on initial load and is not scrollable. There should be an option to scroll dialog instead of background. At least at [geekystats.com](https://www.geekystats.com) when dialog is visible user cares about dialog's contents and would like to scroll it as it is "main thing" at screen, not background contents.

- __Package version(s)__: 1.21.0
- __Browser and OS versions__:  Chrome & OS X  Version 59.0.3071.115 (Build officiel) (64 bits)

#### Steps to reproduce
1. create dialog with some contents & button to show popover
2. Add a little more contents to popover so popover's content would appear out of viewport

#### Actual behavior

Some contents are unable to see, scroll doesn't work, content is just not visisble because out of viewport

#### Expected behavior

scroll to see content

zoomed out full UI:

![image](https://user-images.githubusercontent.com/2733862/27761864-26340770-5e6e-11e7-8c1d-50f8f4f93ede.png)

100% zoom with popover's content out of viewport:

![image](https://user-images.githubusercontent.com/2733862/27761874-60dad796-5e6e-11e7-9c9c-26f2c5920316.png)

**Comment by giladgray** [comment]
@liesislukas have you read this section? may prove helpful.
http://blueprintjs.com/docs/#core/components/overlay.scrollable-overlays

if not, i'm planning to basically rewrite `Popover` in the next two weeks per #1202 which will hopefully improve this experience.

**Comment by liesislukas** [comment]
yes, i have read that part, i saw that you have some custom code for scrolling events. I'm not a fan of custom code for basic interaction like scroll because such code often lead to crazy bugs on some platforms, some browsers for some users and it's hard to debug & test with all environments. 

Maybe you like this:

When dialog is shown place it as any element and just hover all other elements with that dark background. Place it on top of the page and scroll to the top after shown OR add extra margin from top just same amount user is scrolled down, so it would be in viewport w/o any extra scroll. There could be couple props: 

```
<Dialog
  marginTop={250} 
  scrollMarginTop={50}
  ...
/>
```
it would add whitespace of 250px from top & scroll to 50px from top of the page when shown

or it could be:
```
<Dialog
  marginTop={'auto'} 
  scrollMarginTop={50}
  ...
/>
```

and this would open dialog, add `marginTop` === `px user scrolled from top` +  `scrollMarginTop` and it would be in viewport initialy.

Dialog would stay fixed in position and if all page is 5000px height and dialog is 150px height and is 50px from top, when shown user would be scrolled to top of the page and would see dialog but also user could scroll down and would see dark background with some opacity and no dialog, while he/she scrolled out of it and dialog is 50px from top of all page and she/he is 4k+ px scrolled down and dialog is out of the viewport.

**Comment by FishOrBear** [comment]
Hi.
any progress?

I want to control the size of the Dialog, but I found that I can't use the Flex layout.

I tried to modify the DialogContainer.Style =>

     Display: flex;
     Align-items: stretch;
     Align-content: stretch;

This allows me to use Flex in DialogBody without overflowing. (Display the scrollbar correctly.)
And control the size of the Dialog. (Although not so successful.)

**Comment by giladgray** [comment]
i think this issue is fixed with Popper.js -- popovers will no longer leave the screen.

@FishOrBear try setting `width` and `height` via `<Dialog className>`
