### ISSUE TITLE
[Dialog] scrolling UX is bad because dialog is not scrolling when hovered overlay

### ISSUE THREAD

**Issue by liesislukas** [palantir/blueprint#1313]
Hi, i'm making usability testing and already see a lot feedback about bad UX with dialogs because when user is trying to scroll dialog scrolling does work only when mouse cursors is over the dialog contents if mouse is over the overlay scroll scrolls background page but not dialog, which is primary active content at that moment.

At least there should be a property if you really want to let user scroll background page when dialog is active.

### Bug report

- __Package version(s)__: 1.21.0
- __Browser and OS versions__: Version 59.0.3071.115 (Build officiel) (64 bits)

#### Steps to reproduce

1. create random site with some html/text
2. use dialog component `Dialog`
3. scroll while hovered over dialog and when hovered overlay

#### Actual behavior

scroll is working not like users expect it to work. Bad ux.

#### Expected behavior

Dialog is scrolling always no matter where the mouse is, while dialog is primary active content.

![image](https://user-images.githubusercontent.com/2733862/27764925-bf12e88c-5ead-11e7-9272-b110aa7f3d6f.png)

**Comment by giladgray** [comment]
@liesislukas huh interesting, [dialogs on the docs site](http://blueprintjs.com/docs/#core/components/dialog) do not exhibit this behavior, and i can't figure out from inspecting your CSS why your page would scroll. any suggestions?
thanks for the detailed report!

**Comment by liesislukas** [comment]
In fact on docs site dialog sometimes works one way, sometimes another. Here's a short video:

https://youtu.be/5grSqlJvDWM

you can check my dialog here:

https://www.geekystats.com/company/1/seoRank/monitor?viewMore=1&viewMoreTab=keyword

Use login: **demo@gmail.com** and psw: **demo@gmail.com**

p.s. if you find geekystats.com interesting just register with your email and i will send you notification when it's ready 👍

**Comment by giladgray** [comment]
@liesislukas we've narrowed this issue down to something entirely out of our control: retina screens seem to support scrolling from the backdrop, but normal monitors _do not_. this can be repro'ed readily by plugging an external monitor into a Retina MBP and dragging a chrome window back and forth between monitors.

#1373 attempts to fix some of the scrolling woes in CSS but there seems to be little we can do about _this_ particular issue.

**Comment by giladgray** [comment]
@liesislukas actually ignore my comment above, #1373 totally fixes this now!

**Comment by liesislukas** [comment]
just updated, I confirm that update fixes this issue on my app. Thank you :) 👍
