### ISSUE TITLE
allowMultipleSelection={false} doesn't seem to stop shift+select multiple

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1323]
### Bug report

- __Package version(s)__:     "@blueprintjs/table": "^1.18.0",
- __Browser and OS versions__: mac chrome

#### Steps to reproduce
<Table
   {...defaultTablePropsAndSomeTableData}
              allowMultipleSelection={false}
            >

#### Actual behavior

Hitting shift allows for the selection of multiple rows

#### Expected behavior

Shouldn't be able to select multiple rows with shift-click

Here is a gif of the behavior. You can see in the side panel that the allowMultipleSelection prop has been set to false:
![timing](https://user-images.githubusercontent.com/2730609/27903127-0412ced8-61ed-11e7-9781-6e52532c9c11.gif)

**Comment by tnrich** [comment]
Also, I was trying to set up a little fiddle for people to quickly see the error for themselves, but had trouble doing so. Would someone mind taking a look at why the fiddle doesn't seem to be working?

https://jsfiddle.net/ct2f7uo6/1/

Thanks very much!

**Comment by giladgray** [comment]
@tnrich there seem to be a few things wrong with fiddle, as well as an actual issue in `table.bundle.js` (missing file in webpack import):

1. add dom4 dependency
2. put table dep _after_ core dep
3. fix the error in `table.bundle.js` (this one's on us)
