### ISSUE TITLE
Icon docs should emphasise sizing class requirement

### ISSUE THREAD

**Issue by thomas-mcdonald** [palantir/blueprint#1327]
Recently done two frontend workshops as an intro to React/Redux which uses Blueprint components as building blocks.

In both I've noticed people miss the requirement to include the sizing class (but using eg. arrow icons which have renderable codepoints in the system font so don't look super broken), which I think suggests that there should be some more emphasis on the requirement for the sizing class.

Not sure what the best fix for this could be, perhaps a stronger callout for the example codeblock? Could the click-to-copy functionality on each icon split out into standard/large/custom selection and copy the whole tag?

**Comment by llorca** [comment]
Not sure what's best either, the docs is very short and half of it is the code block + callout.

**Comment by giladgray** [comment]
closing as 2.0 icons do not require sizing!
