### ISSUE TITLE
(2,1): error TS2688: Cannot find type definition file for 'dom4'.

### ISSUE THREAD

**Issue by Ciantic** [palantir/blueprint#133]
I'm getting following error in TypeScript:

```
ERROR in node_modules\@blueprintjs\core\dist\components\collapse\collapse.d.ts
(2,1): error TS2688: Cannot find type definition file for 'dom4'.
```

Using TypeScript 2.0.3, installed the blueprint using:

`npm install --save @blueprintjs/core`

**Comment by giladgray** [comment]
you'll need to manually install typings for `dom4` (and `react`, as you'll discover soon enough). we'll update the typescript installation instructions to include a full list of the external typings you'll need. in the meantime, here it is:

- @types/dom4
- @types/pure-render-decorator
- @types/react
- @types/react-addons-css-transition-group
- @types/react-addons-transition-group
- @types/react-dom
