### ISSUE TITLE
Tabs2 using CDN

### ISSUE THREAD

**Issue by 3d0** [palantir/blueprint#1332]
### Bug report

- __Package version(s)__: Core 1.20 to 1.22
- __Browser and OS versions__: Chrome 59
#### Steps to reproduce

1. Build a simple page with a buildless react (with addons)
1. Add the CDN support of Blueprint
1. Build a simple app with tabs2 using Javascript
#### Actual behavior

the tabs are rendered , but there is no bar under the name of the selected tab. Also there is an error every time a tab is changed in the console
`Uncaught TypeError: this.tablistElement.queryAll is not a function
    at Tabs2.getTabElements...`  
or
`Uncaught TypeError: this.tablistElement.query is not a function
    at Tabs2.moveSelectionIndicator`
which makes dificult use tools like React-devtools

#### Expected behavior

Something like the doc?

#### Evidence

https://jsfiddle.net/qek4c6q8/2/

**Comment by giladgray** [comment]
@3d0  you're missing a dependency on `dom4`

**Comment by 3d0** [comment]
I did a test adding the dom4 library and it worked. But it should be reflected on the documentation, because is part of Blueprint.Core.

**Comment by giladgray** [comment]
@3d0 ah nuts i see it's missing from that big HTML example. will fix! DOM4 is mentioned elsewhere in the usage guide, and of course it's listed in package.json.
