### ISSUE TITLE
Delete roundSize.tsx

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1334]
We don't need `roundSize.tsx` anymore as of #1333. It's currently exposed to consumers but isn't used anywhere else, so we should delete it when we 2.0.

**Comment by giladgray** [comment]
a quick code search (internally) should reveal if anyone is actually using `RoundSize`. if not, let's just remove it and not worry about 2.0. This is simply an artifact of using ES6 modules for everything: the Table exposes a lot of identifiers that aren't really "public" APIs, but they _could_ still be imported by zealous users.
