### ISSUE TITLE
DateInput There are no option to select future year.

### ISSUE THREAD

**Issue by khoacoi** [palantir/blueprint#1348]
### Bug report

- __Package version(s)__:  blueprintjs/datetime: "1.18.0",
- __Browser and OS versions__: Chrome

#### Steps to reproduce

Add component DateInput
Select year dropdown
Current year is displayed in last option.

#### Actual behavior

Cannot select a date in future year.
Ex: 01/01/2018

#### Expected behavior

Should be able to select future years.

**Comment by cmslewis** [comment]
`maxDate` is getting in your way. Does setting the `maxDate` prop to something far in the future not work for you?

**Comment by khoacoi** [comment]
awesome, thanks for your response.
maxDate do the trick!

Thanks again,
