### ISSUE TITLE
[Table] Add a resizeEachRowToTallestCell

### ISSUE THREAD

**Issue by Que3216** [palantir/blueprint#1354]
Blueprint already has a `resizeRowsByTallestCell` method (https://github.com/palantir/blueprint/blob/44f5cd0cbde1e7f78be3ae2938d64776acd7c56b/packages/table/src/table.tsx#L514) but this resizes all rows to the same height. This means the rows generally become way too high. We really want each row to be as tall as it needs to be, but no taller.

How about adding a `resizeEachRowToTallestCell` method?

**Comment by tgreenwatts** [comment]
That would be great! But currently it'd be a large perf hit, which is why we added `resizeRowsByTallestCell`. So yes, but don't expect in the short-term

**Comment by cmslewis** [comment]
@Que3216 take a look at PR #1718 and let me know what you think!

**Comment by Que3216** [comment]
Looks great!
