### ISSUE TITLE
Support i18n of DateRangeInput placeholder text

### ISSUE THREAD

**Issue by AlexLandau** [palantir/blueprint#1365]
For the DateRangeInput, the "Start date" and "End date" placeholder text (which is prominently displayed in most cases) is currently (as of July 19) hardcoded, meaning it can't be replaced by the user for i18n purposes:

https://github.com/palantir/blueprint/blob/57e4093d2b5165b61a2014ad39b243933f608de0/packages/datetime/src/dateRangeInput.tsx#L768

```
    private getInputPlaceholderString = (boundary: DateRangeBoundary) => {
        ...
        } else if (isStartBoundary) {
            return isInputFocused ? this.state.formattedMinDateString : "Start date";
        } else if (isEndBoundary) {
            return isInputFocused ? this.state.formattedMaxDateString : "End date";
        } else {
        ...
    }
```

**Comment by giladgray** [comment]
you can use `start|endInputProps.placeholder` to override those hardcoded values.

`<DateRangePicker endInputProps={{ placeholder: "Shalom" }} />`

**Comment by giladgray** [comment]
@AlexLandau per my comment above, I believe this is already supported. can you confirm that it meets your needs?

**Comment by AlexLandau** [comment]
Ah, I see now. Thanks for the help!
