### ISSUE TITLE
Couldn't find Type Defination file

### ISSUE THREAD

**Issue by kunjee17** [palantir/blueprint#137]
I was trying to pull Type Defination using typings. But I couldn't found single file having all the definitions in file. Like `blueprint.core.d.ts`. 

Can you tell me where I can find them? 

PS: Please close the issue if it is not appropriate or in pending task. I filled a issue as I can't find twitter of it.

**Comment by adidahiya** [comment]
Type declaration files are bundled in the NPM package. They are not published to DefinitelyTyped (they don't need to be; the library itself is authored in TypeScript). The compiler should resolve them automatically ([docs](http://blueprintjs.com/docs/#components.usage.npm)).

![image](https://cloud.githubusercontent.com/assets/723999/20264636/8df08e58-aa3a-11e6-8677-0d0d5ef47575.png)

**Comment by kunjee17** [comment]
@adidahiya hey, thanks for reply. Basically I was trying to convert them to F#. So, single file would be good. For multiple file have to write script ;). 

You mind if I can close it. Or you can always do the honor. :)

**Comment by adidahiya** [comment]
Interesting! There is no good way to compile modular type declarations into a single file in the same way that webpack bundles JS modules into a single script. We did write a pretty hacky tool to do this a little while back before the introduction of UMD module definitions in the TS compiler -- https://github.com/palantir/global-typings-bundler -- this is now deprecated and I would not recommend using it, but it demonstrates the general idea.

**Comment by giladgray** [comment]
Closing as discussion seems resolved. This is a special use case which will require special handling.
