### ISSUE TITLE
Props to control batching behavior

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#1374]
Follow up from https://github.com/palantir/blueprint/issues/1368

Current UX is okay for the average table. For scenarios where a table is as simple as text only, consumers should be able to render more cells per frame. For cases where the table is large and contains complex cells, we may want to decrease the number of cells per frame.

**Comment by llorca** [comment]
From @cmslewis:
> Another idea is, instead of a prop `useBatchRendering?: boolean;`, to add a `renderOptimizationMode?: RenderOptimizationMode;` prop (working title) that accepts values like:
> - `RenderOptimizationMode.BATCH`: render as many new cells as possible per frame, and no more (this is what we currently have, and this scheme also has the strongest guarantee against bringing the UI to a crawl)
> - `RenderOptimizationMode.DEBOUNCE`: debounce scrolling, hiding cells on scroll start and rendering cells all at once after the scroll event finishes (this has a risk of locking the UI if the cells are small/numerous/complex/have truncated content, e.g.)
> - `RenderOptimizationMode.NONE`: no optimizations, just render everything (useful for smaller tables, but can easily bring the UI to a crawl on larger tables)
> 
> (Maybe also a `RenderOptimizationMode.THROTTLE` for throttling scrolling).

**Comment by tgreenwatts** [comment]
Need to get at least ability to turn off batching by 9/1, for consumers who are creating PDFs of tables

**Comment by tgreenwatts** [comment]
Going to close this, can open a new one with other modes and ideas
