### ISSUE TITLE
[Popover] Make it easier to overwrite the Popover Arrow

### ISSUE THREAD

**Issue by ConneXNL** [palantir/blueprint#1375]
It's currently not possible to disable the arrow other than hiding its CSS or tweaking the actual component that is being rendered.

It would be really helpfull if the arrow part:
https://github.com/palantir/blueprint/blob/69a05ef7685de5dc57d6b8637d9875faa0052105/packages/core/src/components/popover/popover.tsx#L451-L456

Gets moved to a seperate function so we can atleast customize the arrow by extending the Popover class without having to copy the entire contents of the RenderPopover function:
https://github.com/palantir/blueprint/blob/69a05ef7685de5dc57d6b8637d9875faa0052105/packages/core/src/components/popover/popover.tsx#L451-L456

Would you allow a PR ?

Also would it make sense to make these functions to become `protected `instead of `private`?

**Comment by cmslewis** [comment]
Sit tight; we're literally rewriting Popover as I type this, and this is one of the newly supported features IIRC.  👍

**Comment by giladgray** [comment]
yes this should be addressed by #1202

**Comment by giladgray** [comment]
`arrow?: boolean` prop added in 2.0 makes removing the arrow as easy as possible 👍
