### ISSUE TITLE
Text colour of dropdown with dark theme

### ISSUE THREAD

**Issue by andrzej-aa** [palantir/blueprint#138]
### Bug Report

- __Package version(s)__: 1.0.1 (?)

#### Describe the issue:

In the docs page http://blueprintjs.com/docs/#components.datetime I noticed that the text colour of drop-down in select is very light, although the background is still white. Here is a screenshot http://prntscr.com/d71f7c I use the latest stable Chrome on Windows 10.

#### Actual behavior:

Light text colour on white background

#### Expected behavior:

Contrasting colours

**Comment by adidahiya** [comment]
pasting your screenshot directly:

![image](https://cloud.githubusercontent.com/assets/723999/20264681/c33ae248-aa3a-11e6-8b4b-7e6b5c439fe2.png)
