### ISSUE TITLE
Minimal Button and AnchorButton keep focus after click, causes bad styling

### ISSUE THREAD

**Issue by acolombi** [palantir/blueprint#1381]
In Chrome on Mac OS, clicking a `pt-minimal` Button of AnchorButton will keep focus after the click. This leaves the styling like `:hover` even after you've moved the mouse away. See gif below.

![button-click](https://user-images.githubusercontent.com/707331/28586005-21629006-7127-11e7-85d4-e107de9b05dd.gif)

**Comment by giladgray** [comment]
@acolombi this is simply how focus works in the browser - it remembers the last element you focused. Don't think there's any work to be done here, it's basically "by design"

**Comment by llorca** [comment]
What Gilad said. This is specifically designed for minimal buttons, we intentionally apply the same styles on hover and focus. Basically, it addresses a few visual accessibility concerns that were particular to minimal buttons, such as keyboard navigation styles, contrast, visibility...

**Comment by JKillian** [comment]
It is a somewhat jarring visual effect though - it feels like the button "got stuck down". I've seen it confuse users in an app I've worked on

**Comment by llorca** [comment]
I traced back some old PRs internally, and it looks like we matched focus styles to hover styles before we ever had the `FocusStyleManager`, which makes a lot of sense with regards to accessibility and keyboard navigation. Might be safe to remove now!
