### ISSUE TITLE
Replace Lorem Ipsum with more representative text samples

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#139]
Throughout the docs examples we sometimes use Lorem ipsum and other times have nicer, more engaging text. Would be great to do a pass over the sample text and remove all instances of boring Lorem Ipsum.

**Comment by llorca** [comment]
@thisisalessandro any recommendation for nicer placeholder text?

**Comment by thisisalessandro** [comment]
We should choose a non-Palantir theme and do a pass making it representative (but fictional).

**Comment by tgreenwatts** [comment]
So there are only 10 instances of "Lorem ipsum" being used today, think we can just close this out?

**Comment by llorca** [comment]
I think it's still a valid issue, just a P5 at this point. I will tackle it in June/July when I go through all the examples before we ship 2.0

**Comment by giladgray** [comment]
@llorca @thisisalessandro suggestions for lorem ipsum replacements?

**Comment by llorca** [comment]
First pass auditing where the lorem ipsum is:
- **Callouts**: can't change the CSS ones, they're generated via intents
- **Cards**: can change, will come up with something
- **Dialogs**: can change, will come up with something
- **Popovers**: can change, will come up with something

**Comment by giladgray** [comment]
@adidahiya can we clarify the goal of this issue? my understanding is you're asking to replace _all_ "lorem ipsum" instances (in both JS and CSS examples) with more engaging text. 

two directions i could see this going (not mutually exclusive):
- use a sillier text generator, like http://www.cipsum.com/
- more realistic examples, perhaps borrowed from OS components (great examples of dialogs and forms in OS X preferences, for instance)

**Comment by llorca** [comment]
I started working on this in between 3 other things, but IMO this isn't a requirement for 2.0

**Comment by giladgray** [comment]
yeah it's just docs polish, can happen at any time
