### ISSUE TITLE
[Toaster] property to hide [x] button so can pass in message with jsx and custom button easily w/o creating all component for Toast message

### ISSUE THREAD

**Issue by liesislukas** [palantir/blueprint#1395]
![image](https://user-images.githubusercontent.com/2733862/28704613-26b78684-7374-11e7-8225-e283c7b0c0d0.png)

```javascript
const doToast = Toaster.create({
  position: Position.BOTTOM,
});
doToast.show({message, intent: bluePrintIntent[intent.toUpperCase()]});
```
expecting to have `showClose: false` or similar prop:

```javascript
doToast.show({showClose: false, message, intent: bluePrintIntent[intent.toUpperCase()]});
```

I saw your docs for http://blueprintjs.com/docs/#core/components/toast.react-component
But would be great to have simple prop to hide [x]

For now, I'm using `action` property, which is OK but still would like to hide [x] while it is not needed in this situation.

```javascript
...
action: {
          onClick: () => openInTab({url: action.data.payUrl}),
          text: 'Open',
        },
...
```

![image](https://user-images.githubusercontent.com/2733862/28704743-02990628-7375-11e7-98a7-d0d55db4b410.png)

**Comment by giladgray** [comment]
@liesislukas the thing about the X is it's sort of always needed--it gives the user a reliable way to dismiss a toast when they're done with it (regardless of timeout). the `Toast` API is opinionated to offer a specific experience: ephemeral, dismissible messages.

if you're looking for something custom, just use `Overlay` and the `.pt-toast` CSS classes directly to get _exactly_ what you need.
