### ISSUE TITLE
[Labs] Can't override input placeholder on MultiSelect

### ISSUE THREAD

**Issue by viggyfresh** [palantir/blueprint#1398]
### Bug report

- __Package version(s)__: 1.24.0
- __Browser and OS versions__: Electron 1.6.11

#### Steps to reproduce

1. Try to override the input placeholder on a `MultiSelect` as follows (culled almost directly from the docs):
    ```JSX
    <ElosMultiSelect
        items={this.props.items}
        itemListPredicate={this.filterItems}
        itemRenderer={this.renderMenuItem}
        noResults={
            <MenuItem
                disabled={true}
                text={"Nothing easy"}
            />
        }
        onItemSelect={this.onItemSelect}
        selectedItems={this.state.selectedItems}
        tagInputProps={{
            'tagProps': {
                'className': tagClasses,
                'intent': Intent.PRIMARY,
            },
            'className': tagInputClasses,
            'inputProps': {
                'placeholder': this.props.placeholder,
            },
            'onRemove': this.handleTagRemove,
        }}
        tagRenderer={renderTag}
    />
    ```
2. Try to select (either via the Enter button or a click) any item from the multiselect.

#### Actual behavior

```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at MultiSelect._this.handleItemSelect (http://localhost:6789/build/bundle.js:100148:24)
    at Object.safeInvoke (http://localhost:6789/build/bundle.js:5936:21)
    at QueryList._this.handleKeyUp (http://localhost:6789/build/bundle.js:99985:30)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:6789/build/bundle.js:33638:16)
    at executeDispatch (http://localhost:6789/build/bundle.js:33423:21)
    at Object.executeDispatchesInOrder (http://localhost:6789/build/bundle.js:33446:5)
    at executeDispatchesAndRelease (http://localhost:6789/build/bundle.js:29279:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:6789/build/bundle.js:29290:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:6789/build/bundle.js:40678:9)
```

#### Expected behavior

I don't think this should cause an error; apologies if this is me being an idiot, but as far as I can tell the order of property spreading shouldn't overwrite the necessary `ref` callback, especially since I'm not providing anything other than `placeholder` in `inputProps`.

Removing the section:
```
'inputProps': {
    'placeholder': this.props.placeholder,
},
```

from `tagInputProps` makes everything work.

I read the section on controlled usage and didn't see anything that would prevent me from overriding placeholder...any thoughts on this?

**Comment by llorca** [comment]
You're not being an idiot! Looks like we're not spreading properly: https://github.com/palantir/blueprint/blob/master/packages/labs/src/components/select/multiSelect.tsx#L122

**Comment by giladgray** [comment]
issue is a little further down, these two lines should be flipped: https://github.com/palantir/blueprint/blob/master/packages/labs/src/components/select/multiSelect.tsx#L150-L151

**Comment by viggyfresh** [comment]
Phew 😅 thanks folks for the quick response!

Random other finding that isn't nearly as urgent but was surprising - making the `MultiSelect` "large" (via making the `TagInput` large) doesn't resize the placeholder text, which remains at the normal font size. This one is easier to work around with some quick CSS, but figured I'd flag it as well!

```CSS
.pt-tag-input.pt-large .pt-input-ghost {
    font-size: $pt-font-size-large;
}
```

**Comment by sushain97** [comment]
Thanks, @giladgray! Your recommended change works perfectly and unblocks me till an upstream fix.

**Comment by strickland84** [comment]
I am experiencing this bug again in the latest release (1.26.0), almost exactly as described by @viggyfresh. 

`	render() {
		return (
			<GroupMultiSelect className='max-width' items={this.props.GroupsStore.groups} itemListPredicate={this.filterGroup.bind(this)} selectedItems={this.props.GroupsStore.childGroupsToCreate} tagRenderer={this.renderTag.bind(this)} itemRenderer={this.renderGroup.bind(this)} onItemSelect={this.handleGroupSelect.bind(this)} tagInputProps={{
				tagProps: {
					className: Classes.MINIMAL,
					intent: Intent.PRIMARY
				},
				className: 'pt-tag-input',
				onRemove: this.handleGroupRemove.bind(this)
			}} popoverProps={{
				position: Position.BOTTOM_LEFT
			}} noResults={this.renderResultSearch()}></GroupMultiSelect>
		);
	}`

That works fine, but when adding 'inputProps' with placeholder as below:

`	render() {
		return (
			<GroupMultiSelect className='max-width' items={this.props.GroupsStore.groups} itemListPredicate={this.filterGroup.bind(this)} selectedItems={this.props.GroupsStore.childGroupsToCreate} tagRenderer={this.renderTag.bind(this)} itemRenderer={this.renderGroup.bind(this)} onItemSelect={this.handleGroupSelect.bind(this)} tagInputProps={{
				tagProps: {
					className: Classes.MINIMAL,
					intent: Intent.PRIMARY
				},
				inputProps: {
					placeholder: 'Test'
				},
				className: 'pt-tag-input',
				onRemove: this.handleGroupRemove.bind(this)
			}} popoverProps={{
				position: Position.BOTTOM_LEFT
			}} noResults={this.renderResultSearch()}></GroupMultiSelect>
		);
	}`

I receive the following error: 

`multiSelect.js?64c9:50 Uncaught TypeError: Cannot read property 'focus' of undefined
    at MultiSelect._this.handleItemSelect (multiSelect.js?64c9:50)
    at Object.safeInvoke (utils.js?394f:28)
    at QueryList._this.handleItemSelect (queryList.js?2e3f:21)
    at handleClick (multiSelect.js?64c9:135)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js?dc41:69)
    at executeDispatch (EventPluginUtils.js?5d8c:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js?5d8c:105)
    at executeDispatchesAndRelease (EventPluginHub.js?0f32:43)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js?0f32:54)
    at Array.forEach (<anonymous>)`

Note, I also have onItemSelect defined in the component.

Thanks
