### ISSUE TITLE
[Labs / Select] Allow value container to be an input that filters items

### ISSUE THREAD

**Issue by sushain97** [palantir/blueprint#1407]
Currently, labs' `<Select>` does not display the selected value itself, the docs opt to display the value in a `<Button>` which is nice. However, for a consistent UX when both `<MultiSelect>` and `<Select>` are being used in tandem, it would be perfect if the selected value could be displayed inside an `<InputGroup>` which supports filtering rather than filtering through a popover. Of course, using an `<InputGroup>` instead of  `<Button>` to hold the selected value is possible with a couple hacks to make the focus less janky. This however results in a double input field UI-quirk:

![image](https://user-images.githubusercontent.com/4211838/28949899-e6235728-788d-11e7-9d3a-f722080a3a83.png)

I tried to disable filtering and make the `<InputGroup>` that holds the selected value control the query and filter the items. However, this is gnarly to accomplish since it requires controlling a bunch of keyboard events e.g. moving the cursor to the start of the input, hiding the selected value during input, and manually controlling the popover. I could implement it manually using `<QueryList>` but that seems sub-optimal and this seems like a reasonable enough use case/argument for visual consistency to warrant inclusion in the "core".

I might be able to send a PR for some progress on this if this makes sense as a core feature (let me know).

Prior Art: https://jedwatson.github.io/react-select/

cc: @llorca thanks for all your help!

**Comment by dmackerman** [comment]
+1 for this one.

**Comment by cmslewis** [comment]
This was always on the radar for us since tackling the typeahead work over the past couple months, and it's now released as the new `Suggest` component. Closing!
