### ISSUE TITLE
[Labs / MultiSelect] Add support for right icons (e.g. for spinner or clear all)

### ISSUE THREAD

**Issue by sushain97** [palantir/blueprint#1408]
Currently, `<MultiSelect>` uses an ordinary `<input>` for user input. This makes it difficult (not possible?) to add a spinner at the right hand side to indicate options being loaded asynchronously, a clear all button or something else of that nature.

@llorca mentioned that a concern here was that the icon would take up the entire vertical height. Maybe they could be centered vertically the way that `react-select` does it:

![image](https://user-images.githubusercontent.com/4211838/28976298-524dc78a-790b-11e7-99b6-9e9f39d3d7be.png)

or top as Select2 does:

![image](https://user-images.githubusercontent.com/4211838/28992534-b25339ec-796c-11e7-8e15-cadeee517bad.png)

**Comment by giladgray** [comment]
implemented in #1420
