### ISSUE TITLE
Expose showWeekNumbers and onWeekClick in the DateRangePicker

### ISSUE THREAD

**Issue by cesarp** [palantir/blueprint#1414]
First, thanks for the awesome work in Blueprint. 

We have a request in our app to be able to pick weeks in the date range picker and the way we wanted to implement it was to use the enable showWeekNumbers, add an onWeekClick handler and change the value from numberOfMonths to 1 so only a single month was visible using the react-day-picker props but there is currently no way to pass those values from the blueprint component. 

It would be nice if they were exposed, for now we had to duplicate the code from blueprint in our project.

**Comment by giladgray** [comment]
@cesarp love this feature request and should be pretty straightforward to expose more react-day-picker features. Unfortunately datetime is low on the team's priority list. How would you feel about contributing a PR?

**Comment by cesarp** [comment]
Sure I can give it a try, I might need some guidance but would be happy to help.

**Comment by giladgray** [comment]
@cesarp awesome! start here https://github.com/palantir/blueprint/wiki/Development-practices, and check the other wiki pages in the sidebar under Contributing. we'll review your code as soon as it's up!

**Comment by llorca** [comment]
Resolved with #1647
