### ISSUE TITLE
Table scrolling performance is slow and jittery since 1.12

### ISSUE THREAD

**Issue by mwebb33** [palantir/blueprint#1415]
### Bug report

- __Package version(s)__:  1.21 
- __Browser and OS versions__: Chrome Version 59.0.3071.115 (64-bit) / OSX 10.12.5

#### Steps to reproduce

I have a large table with 2000 rows and 8 columns. I am having some strange blocking behavior on scroll. The right side scroll bar will disappear and hang for a noticeable amount of time. In general, it feels like it is not running anywhere near 60fps, and the virtualization is not keeping up (it is also rendering batches out of order, as mentioned in [#1368](https://github.com/palantir/blueprint/issues/1368)) 

I thought that perhaps this just needed a batching update tweak, so I changed the ADD_LIMIT, UPDATE, REMOVE from 20 to 5. This significantly helps scrolling performance, but cells update and add crazy slow, much slower than 1.11. I noticed 1.11 did have a smooth 60fps scrolling and much faster cell rendering than 1.21 with batching set at "5". In general, 1.11 had very impressive performance.

I found this by installing every table version since 1.11, and they all has this behavior, so I suspect 1.12 really gunked up the render pipeline somehow.

**Comment by cmslewis** [comment]
@mwebb33 - We've done a lot of work on `Table` scrolling performance over the past couple months. Is it possible for you to update to the latest version of Blueprint?

**Comment by cmslewis** [comment]
Also, take a look at the scroll-perf improvements #1416. Once the frozen columns/rows feature merges, I think we'll see better scrolling in general.

**Comment by mwebb33** [comment]
@cmslewis:

Thanks for the reply. Sorry this post was a bit light on details- I am running 1.21. 

I will check out #1416 and see if that helps. I also plan on following up with a bit more of a performance investigation. I really really want to use this library, it is very nice, especially the selection features, but react-virtualized and fixed-data-table just feel more responsive to me. I mostly posted that it was surprising to me that perceived performance took a big hit from 1.11 to 1.12, at least for my use case.

**Comment by tgreenwatts** [comment]
@mwebb33 you said you were going to do more performance investigation, did anything come of that?

**Comment by mwebb33** [comment]
@tgreenwatts:

Unfortunately, the project was delayed. It is picking back up but I am not sure when I will get back to this. 

Honestly, this could be closed and reopened if someone has more technical details, but I am still finding from my hand testing that 1.11 is dramatically smoother than 1.23. The table performance is a pretty huge deal for our app, and it looks like we are not there yet.

**Comment by tgreenwatts** [comment]
We're seeing some similar issues on other stacks, so we can reproduce now. #1503 will allow you to customize what type of rendering you want (batching like in 1.23 or not like in 1.11), so going to close this. Feel free to file a new issue if you see problems in future
Thanks!
