### ISSUE TITLE
How to set table body max height via table props?

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1417]
Hey there, is there a recommended way to set the max height of a table body? I see it being done with CSS in the example tables, but it seems like it would be nice if this could also be done via props on the table component. 

Also, if CSS is the recommended way, if a little note in the docs about what class to apply the max-height property would be appreciated. 

Thanks!

**Comment by tgreenwatts** [comment]
@cmslewis can you take a look at this?

**Comment by cmslewis** [comment]
@tnrich whoops, sorry for the delay. CSS is the recommended way, yes. We've had a couple folks get tripped up by this now, so happy to add a note to our docs!

**Comment by pawsong** [comment]
Is it possible to introduce a props item to set table max height? e.g. Table component's `style` object props is passed to [here](https://github.com/palantir/blueprint/blob/537acca14224a2b77821c9c8b011b817bdea2e7b/packages/table/src/table.tsx#L611).

**Comment by llorca** [comment]
@pawsong why a prop for something you can do with simple CSS?

**Comment by pawsong** [comment]
@llorca It seems my comments was ambiguous, sorrt! I am building spreadsheet solution built on the top of this library, and thought it would be nice if I could provide inline style interface to users :)

**Comment by giladgray** [comment]
use CSS
