### ISSUE TITLE
Global hotkeys aren't properly grouped in the Hotkeys dialog

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#142]
### Bug Report

- __Package version(s)__: v1.0.1
- __Browser and OS versions__:
  - Chrome 54.0.2840.71 (64-bit) on OS X 10.11.6
  - Safari 10.0.1 on OS X 10.11.6
  - Firefox 42.0 on OS X 10.11.6

#### Describe the issue:

On the Hotkeys page of the Blueprint docs (http://blueprintjs.com/docs/#components.hotkeys), two overlayed hotkey dialogs when you press `Shift + /` (i.e. `?`)

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/443450/20278324/1f3f6a1e-aa59-11e6-9b73-6195d99b628e.png)

#### Expected behavior:

The "Focus the Piano" hotkey should be rendered below in the other global hotkeys in the underlying dialog.

**Comment by adidahiya** [comment]
@cmslewis is this an issue with the Hotkeys component or only a problem with its usage in the docs?

**Comment by cmslewis** [comment]
Delved into this. I'm still pretty new to the codebase, but it looks like it might be related to the build. Two instances of the `HotkeysDialog` are being created from different versions of the same file (`.tsx` and `.js`); this didn't happen prior to the open-source build/repo reorg:

![image](https://cloud.githubusercontent.com/assets/443450/20284307/63cbceb2-aa71-11e6-9b6f-9b4c538676db.png)
