### ISSUE TITLE
Add key icon

### ISSUE THREAD

**Issue by volkandkaya** [palantir/blueprint#1431]
Would be great to have a key icon.

**Comment by giladgray** [comment]
Sorry @volkandkaya, we can't accept icon requests from the community at this time.

But what kind of key are you referring to? The kind that goes with a lock, or with a value?

**Comment by volkandkaya** [comment]
I want to represent an API key, I am sure that is huge with this community.

http://fontawesome.io/icon/key/

**Comment by giladgray** [comment]
for sure, we'll look into it internally
