### ISSUE TITLE
[labs/select] Provide mechanism for disabling Select handlers

### ISSUE THREAD

**Issue by thomas-mcdonald** [palantir/blueprint#1436]
I'm trying to disable a Select input... use case is that one select should be filled out before the second one. There are two pieces here - I can disable the underlying button/child element for the visual side of things but need a way to disable the handlers on the `Select`  component.

![screen recording 2017-08-09 at 05 57 pm](https://user-images.githubusercontent.com/197928/29145820-97b5a7fa-7d2c-11e7-998f-c11488cb7b61.gif)

**Comment by thomas-mcdonald** [comment]
Since I need this today, going to try writing a HOC that switches out the Select w/Button child for just a disabled Button if `disabled={true}` is passed

**Comment by llorca** [comment]
@thomas-mcdonald I think a `disabled` prop for `Select` would make sense here. Want to submit a PR for that functionality?

**Comment by thomas-mcdonald** [comment]
What I ended up creating was a [frankencomponent](https://gist.github.com/thomas-mcdonald/e703bcc940e16ee6ba8fff8bc554fdb1) which worked in the interim - the disabled select ended up not making UX sense in the app I was working on, so moved away from this being a direct issue (although kept the rough HOC so my `Select`s take text and automatically get the `Button` with dropdown caret as per a 'standard' browser select)

Happy to work on a PR next week, I think the only thing I wasn't sure about is naming/responsibilities - `disabled` suggests to me it will handle the visual aspects of the component being disabled. Maybe `disableHandlers`? Unsure if there is a one stone way of passing `disabled={true}` and pushing that through to children.

**Comment by JuoCode** [comment]
Select has `popoverProps` and Popover has `isDisabled`, you should know it.

**Comment by brieb** [comment]
Yes, as suggested, adding `popoverProps={{ isDisabled: true }}` should work. Though adding a top-level `disabled` prop would be clearer.
