### ISSUE TITLE
[Labs] Support option groups in <Select>/<MultiSelect>

### ISSUE THREAD

**Issue by sushain97** [palantir/blueprint#1440]
#### Motivation

Options within an `<Select>` or `<MultiSelect>` can often benefit from grouping cf. native HTML `<optgroup>`s . For example, consider a select field that's used to select assignees for a particular ticket. The assignees can be either "groups" of users, or users themselves. Visually delineating these within the options of the select is more effective than the alternatives:

1) Using multiple select fields (more complex interaction)
2) Distinguishing the options with extra text within the options (cluttered interface)

#### Prior art

- `Select2`: https://select2.github.io/options.html#does-select2-support-nesting-options
- `react-select-plus`: https://github.com/HubSpot/react-select-plus

#### Straw-man API proposal

Currently `<Select>` and `<MultiSelect>` are typed with `items: T[]`. Proposal is to switch this to `items: ISelectItems<T>` where

```
export interface ISelectGroup<T> {
    items: T[];
}

export type ISelectItems<T> = T[] | ISelectGroup<T>[];
```

Then,

```
export interface ISelectGroupRendererProps<T> {
    index: number;
    group: ISelectGroup<T>;
}
```

(Note: this does not consider making groups focusable/clickable)

Then, a `groupRenderer: ISelectGroupRendererProps<G> => JSX.Element` (a recommendation to implement with http://blueprintjs.com/docs/#core/components/menu.section-headers). Typically, users will extend `ISelectGroup` to include their own properties such as a `label` to help with creating the group section headers.

Finally, a `showEmptyGroups: boolean` determining whether to show empty groups (i.e. no items) during render. The rendered groups would not react to clicks by default and not receive extra styling on focus/hover.

cc @giladgray, @llorca

**Comment by cmslewis** [comment]
@llorca what do you think of this? Sounds reasonable to me, but I'd be interested to hear your thoughts, since you were around for the design of these components.

**Comment by sushain97** [comment]
BTW, happy to put together a PR for this if helpful after discussion ends.

**Comment by giladgray** [comment]
I've got some thoughts on this but I'm on the road today. Will put a comment together later today or tomorrow.

**Comment by sushain97** [comment]
I spoke with @llorca briefly on Slack and the approach he proposed to me is having something akin to a `dropdownRenderer` to mirror the `itemRenderer`. 

`dropdownRenderer` would take as input the items, filtered items, active item, etc. and render the dropdown itself. By default, this would be the current behavior which is rendering the items within a `<Menu>`. 

A consumer could easily provide their own `dropdownRenderer` which uses e.g. the `group` key in each of their items to create groups and render them. This approach has the advantage of being much less complex on the Blueprint end. Alternative names include `contentRenderer` `itemsRenderer` and `menuRenderer`. I opted for `dropdownRenderer` since the docs describe the menu as a dropdown.

**Comment by sushain97** [comment]
The implementation of such a solution is relatively straightforward as well: https://gist.github.com/sushain97/c512dd4c5a4128b4484b387d6fb96c7a. The types are a bit gnarly...

**Comment by reiv** [comment]
Sorry for the necro, but is this FR still being considered? I'm holding off on opening a new issue because my use case (integration with `react-virtualize` for large item sets) would also be covered by the addition of a `dropdownRenderer` prop as described above.

Are there any arguments against going forward with this change?

**Comment by giladgray** [comment]
@reiv you can use `QueryList` today to compose `react-virtualized` with any other Blueprint components. This issue is not specifically about `dropdownRenderer`, so if that's a thing you want then feel free to file a new issue (I'm gonna label it __help wanted__ so you're welcome to submit a PR too!)
