### ISSUE TITLE
[Table] When enableFocus becomes true, show the focus cell right away

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1443]
### Bug report

- __Package version(s)__: v1.24.0

#### Steps to reproduce

1. Set `enableFocus` to true on a `Table`.

#### Actual behavior

No focus cell shown until you make a selection, then it persists as expected.

#### Expected behavior

Show a focus cell right away.

**Comment by llorca** [comment]
Dupe of https://github.com/palantir/blueprint/issues/1072?

**Comment by cmslewis** [comment]
@llorca _Almost._ This is a piece of #1072 if we got through with that, specifically with respect to the `componentWillReceiveProps` logic.
