### ISSUE TITLE
Allow animations to be disabled on a per-component basis

### ISSUE THREAD

**Issue by willadamskeane** [palantir/blueprint#1446]
There is currently no way to completely disable the enter/leave transition on a component (at least for a Popover, which is what I was trying to do). The best I can do is override the transition duration in CSS, and set it to `1ms`. Setting this duration to `0ms` causes the popover to unreliably show and hide. 
Ideally there would be a prop that could be passed, such as `disableTransition`, that would completely disable these transitions.

Thank you!

Ref: [https://stackoverflow.com/questions/45662677/how-can-i-completely-disable-transition-for-popover](https://stackoverflow.com/questions/45662677/how-can-i-completely-disable-transition-for-popover)

**Comment by giladgray** [comment]
As you noted, it is not possible to set transition duration to 0 with `CSSTransitionGroup`. 1ms is in fact the best you can do, and that's the expected workaround here.

A simple CSS class that forces `transition-duration: 1ms !important` should be enough in most cases, though it's going to make things look real bad, which is kind of _not_ the point of Blueprint.

Have you seen our [minimal transitions for Popover](http://blueprintjs.com/docs/#core/components/popover.minimal-popovers)?

**Comment by willadamskeane** [comment]
I have - the minimal popover class applies a `100ms` transition by default. The `1ms` override looks pretty bad, as you mentioned. I really need a way to completely disable the transition.

**Comment by cmslewis** [comment]
@willadamskeane - out of interest, not nosiness: could you give a little more detail to help us understand your use case and the motivation for disabling the transition? Is it an aesthetic preference, or do you need to test something synchronously, etc?

**Comment by willadamskeane** [comment]
It is an aesthetic preference. I'm building a menu system that sits at the top of the application, closely mimicking the menu style and function of the OSX menu bar. Clicking on a menu item opens a dropdown popover with child menu items. Ideally the menu items are accessible as quickly as possible as they will be used frequently.

**Comment by llorca** [comment]
@willadamskeane then the minimal animation should work just fine, I designed it for the exact use case you described. Even if we were to make the animation 0ms, it wouldn't actually speed up your workflow -- by the time the current 100ms is done, you're barely done clicking and the popover has just opened.

Side note, I can confirm that overriding the transition duration in both CSS in JS to 1ms doesn't work. Looks like it falls back to 100ms anyway, even after cancelling custom transforms and such.

**Comment by willadamskeane** [comment]
I totally get that in most cases `100ms` is short enough that it won't disrupt the workflow. However, in my case I allow the user to click on a menu which toggles an 'active' menu state, meaning that the user can simply move the mouse without clicking to activate other menus. Purely from an aesthetic point of view, it is jarring to see menus fading in and out, especially considering they could open like 5 popovers in 100ms just by quickly moving the mouse over items. To see what I mean, try messing around with the OSX menu bar. You'll see that menus open and close* instantly, which makes it feel very responsive.

*except when the menu closes is the last one open, in which case it fades out.

**Comment by llorca** [comment]
Yup I see what you mean! When you first open a menu on Mac, it actually takes 100ms, but you can then smoothly navigate between other menus instantly. That, we don't support yet.

**Comment by giladgray** [comment]
@willadamskeane turns out it's quite easy to disable animations on a per-component basis (but it doesn't look very good, fair warning):

```jsx
<Dialog transitionName="none">
```

passing an unknown `transitionName` will change the CSS classes generated by `CSSTG` to something that doesn't have any associated styles. I used `"none"` above to make the intention obvious, but really anything other than the default value of `"pt-overlay"` will do it.

🎊

**Comment by willadamskeane** [comment]
Looks like `transitionName="none"` doesn't have any effect on a Popover?

**Comment by giladgray** [comment]
Is the prop listed in the docs? Might be missing, in which case we'll accept a small PR to add it.

**Comment by isTravis** [comment]
For Popovers, I've been using `transitionDuration={-1}` and it's been working sufficiently well. I'm not sure how this would be any different than setting it to 0 and I haven't experienced the unreliable show/hide problem you mention, @willadamskeane, so take it with a grain of salt. 

```js
<Popover
	content={<div>blah</div>}
	interactionKind={PopoverInteractionKind.CLICK}
	position={Position.BOTTOM_RIGHT}
	transitionDuration={-1}
>
```

![sdfo3vxghe](https://user-images.githubusercontent.com/1000455/29687985-33e4c640-88ec-11e7-93d0-5f42cfa99dba.gif)

That said - this seems like a hack that happens to work rather than a stable solution, so `transitionName="none"` is obviously preferred if that PR lands.

**Comment by giladgray** [comment]
workaround available

**Comment by SachinRaghunathan** [comment]
This workaround (setting transition duration to -1) doesn't seem to work for MultiSelect. Is there a better solution available?
