### ISSUE TITLE
Hotkeys get disabled when focusing form controls

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#145]
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: macOS, Chrome 54

#### Describe the issue:

Global hotkeys are correctly disabled when using a **text** input, because the user is looking to input text.

They should still be enabled after focusing checkboxes, switches, radios. It's not the case now, see GIF below.

#### Actual behavior:

![screen recording google chrome](https://cloud.githubusercontent.com/assets/199754/20280286/c689d140-aa60-11e6-8b96-ba06e635621b.gif)

#### Expected behavior:

Focusing an `<input>` shouldn't kill hotkeys, unless the input is a text input, I suppose?

**Comment by cmslewis** [comment]
PR: #155
