### ISSUE TITLE
[Labs] MultiSelect typing does not allow tags to be arbitrary elements

### ISSUE THREAD

**Issue by sushain97** [palantir/blueprint#1454]
I think that per

https://github.com/palantir/blueprint/blob/5d35803cea062541776490ac2ea3cfbbd7bb3f64/packages/labs/examples/tagInputExample.tsx#L22

this

https://github.com/palantir/blueprint/blob/fd8c319991a7e9a5b656b0dd40b6fc3ca1a90630/packages/labs/src/components/select/multiSelect.tsx#L66

should be

```typescript
tagRenderer: (item: T) => React.ReactNode;
```

Unfortunately, this makes it so that the new changes can't be taken advantage of for `MultiSelect` without ditching TS's safe world and making things `any` that shouldn't be.

Happy to send a brief PR if my understanding is correct.

cc @giladgray

**Comment by giladgray** [comment]
Please send a PR! Write a unit test if you can.
