### ISSUE TITLE
Select all and clear selection buttons for multi-select

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1457]
Would BP consider adding "select all" and "clear" buttons for the multi-select component? For large multi select lists, it's not uncommon to see these features to minimize the amount of clicking.

**Comment by llorca** [comment]
I want the capability, but wouldn't want to add specific props for the behavior. Another reason to allow consumers to render their own popover content? https://github.com/palantir/blueprint/issues/1440#issuecomment-322319856
