### ISSUE TITLE
Nested Tabs2 inherit pt-large from outer Tabs2

### ISSUE THREAD

**Issue by nickcharles** [palantir/blueprint#1466]
### Bug report

- __Package version(s)__: `"@blueprintjs/core": "^1.24.0"`
- __Browser and OS versions__: Chrome 60.0.31112.90, OS X

#### Steps to reproduce

```jsx
<Tabs2 className="pt-large" id="top-tabs">
    <Tab2
        id="tab-uno"
        title="Tab Uno"
        panel={
            <Tabs2 id="nested-tabs" >
                <Tab2 id="tab-small-uno" title="Small Tab Uno" />
                <Tab2 id="tab-small-dos" title="Small Tab Dos" />
            </Tabs2>
        }
    />
    <Tab2
        id="tab-dos"
        title="Tab Dos"
    />
</Tabs2>
```

#### Actual behavior

Both sets of tabs are displayed as large tabs.

#### Expected behavior

The outer set of tabs is displayed as large and the inner set is displayed as normal.

**Comment by rheinheimer** [comment]
I second this bug. I was about to post this exact same issue. Having nested tabs of different sizes is very much needed. Thank you Palantir for Blueprint.

**Comment by giladgray** [comment]
should be a quick fix, around [these lines](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/tabs/_tabs.scss#L123-L126) in _tabs2.scss. we'll happily accept a PR.

**Comment by nickcharles** [comment]
Woo
