### ISSUE TITLE
Checkbox checked attribute is always `on`

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1468]
I am using below code to create a <Checkbox> component:

```
         import {Checkbox} from '@blueprintjs/core';
          <Checkbox
                  checked={o.checked}
                  label={o.label}
                  className="db-backup-gzip"
                  onChange={() => o.onChange()}
                />
```

it works fine from UI point of view but when I inspect this element, I see the below dom structure:
```
<label class="pt-control pt-checkbox db-backup-gzip">
      <input type="checkbox" label="gzip" class="db-backup-gzip" tabindex="0" value="on">
         <span class="pt-control-indicator"></span>
         <!-- react-text: 6414 -->gzip<!-- /react-text -->
</label>
```
You can see that the value of the `input` dom is `on` but I passed in `true`. When I unselect the checkbox the value is still `on`. I know there is additional css style to control the selection/unselection style but I wonder whether I can make it to use the `input value`. That because I am writing test cases through `webdriver.io` and I need to select/unselect the dom by its value. Also I need to use `webdriver.io` API to check whether a checkbox dom is selected or not. It would be easier to use value.
The blueprintjs version I am using is: `"@blueprintjs/core": "^1.17.1",`

**Comment by giladgray** [comment]
@zhaoyi0113 you say it works from a UI perspective, but the DOM shows some weird state? doesn't sound like a bug. in fact, you're misinterpreting the purpose of the `value` attribute: see MDN's [Checkbox Examples](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Examples) and you'll notice that the `value` attribute __does not represent the checked state, but rather the form value__ that this checkbox provides to its `name`.

when querying for checked checkboxes, I prefer the [`:checked`](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked) pseudoselector.

**Comment by giladgray** [comment]
(renamed issue because this is not about the `checked` attribute)
