### ISSUE TITLE
Error when build css from scss with sass-loader and webpack

### ISSUE THREAD

**Issue by Tiscs** [palantir/blueprint#1469]
### Bug report

- __Package version(s)__: 1.25.0
- __Browser and OS versions__: macos 10.12.6, chrome 60.0.3112.101

#### Steps to reproduce

1. `@import "~@blueprintjs/core/src/blueprint";`
2. `yarn add -D webpack@3.5.5 sass-loader@6.0.6 node-sass@4.5.3 ...`
3. `{ test: /\.scss$/, use: "style-loader!sass-loader"}` in webpack.config.js

#### Actual behavior

Error when build css from scss with sass-loader and webpack:
```
File to import not found or unreadable: common/icons.
Parent style sheet: /.../@blueprintjs/core/src/components/icon/_icons.scss
```
When I replace `@import "common/icons";` with `@import "../../common/icons";` in file `/.../node_modules/@blueprintjs/core/src/components/icon (line 6)`, build will successed with no errros.

#### Expected behavior

Build will successed.

**Comment by Tiscs** [comment]
It's fixed in version 1.25.1.

**Comment by will-stone** [comment]
I believe this has regressed: https://github.com/palantir/blueprint/pull/1916/files#diff-a33725d4e26c6abd5f056d831cc5d180 Should we be relying on environments having `~` support? Let me know if you'd like this logged as a new issue.

**Comment by giladgray** [comment]
@will-stone if you want to compile our sass then yes you better have `~` support. it's easy to add.
https://github.com/palantir/blueprint/blob/develop/packages/node-build-scripts/sass-compile.sh#L15
