### ISSUE TITLE
.pt-portal causes display issues.

### ISSUE THREAD

**Issue by dmackerman** [palantir/blueprint#147]
### Bug Report

- __Package version(s)__: 1.0.1

#### Describe the issue:
When the class is displayed - due to an overlay, or popover - having `display: inline-block` can cause layout issues.

#### Possible Fix
Changing `.pt-portal` to `{ display: block; }` corrects this behavior.

**Comment by adidahiya** [comment]
Can you elaborate on your layout issues? Many of the docs examples utilize `.pt-portal` and they work fine.

**Comment by dmackerman** [comment]
I have 2 divs that are arranged horizontally with flexbox - but I'm not sure that's relevant. What appears to be happening is when the `pt-portal` is displayed, it shifts my entire application upwards.

You can see that when the dropdown is clicked and the `pt-portal` div get's rendered, the shift happens. The Dropdown is a custom component I'm writing, but I haven't done anything in terms of custom styling. 

Here's a GIF:
![jump](https://cloud.githubusercontent.com/assets/289938/20284516/ae827024-aa7a-11e6-8aa1-658b6a3604d4.gif)

**Comment by adidahiya** [comment]
Have you seen the callout in the Portal docs that suggests using `position: absolute` for 100% height+width layouts?

http://blueprintjs.com/docs/#components.portal.js

![image](https://cloud.githubusercontent.com/assets/723999/20284768/92e6e04a-aa8c-11e6-9d0b-7dadbfefc9ed.png)

**Comment by dmackerman** [comment]
Strange enough, this is only in Chrome Canary. Works fine in Safari and Chrome Stable.

**Comment by adidahiya** [comment]
Can you still reproduce the issue in Chrome Canary after applying the suggested fix I linked above?

**Comment by dmackerman** [comment]
Yes. Those styles have no effect.

**Comment by adidahiya** [comment]
`display: inline-block` &rarr; `display: block` actually sounds like a legit change to make for `.pt-portal`... what do you think @giladgray? I tried to git blame the internal repo and didn't find a good reason why we have it as inline-block. Will require some cross browser testing of course.

**Comment by giladgray** [comment]
wow that's like the only rule in that file. `block` sounds fine to me though we'll have to do some testing to be sure.
