### ISSUE TITLE
[Labs] Omnibox doesn't render items if query is empty string

### ISSUE THREAD

**Issue by nowyasimi** [palantir/blueprint#1473]
### Bug report

- __Package version(s)__: ^0.5.0
- __Browser and OS versions__: MacOS Chrome 60.0.3112.90

#### Steps to reproduce

1. Open Omnibox (without entering a query)

#### Actual behavior

My itemListPredicate function returns a list of recent searches if the query length is 0. Currently, the Omnibox doesn't render this list if the query length is 0. 

#### Expected behavior

The Omnibox should render an itemList regardless of the query length. I was able to resolve the issue by changing the three occurences of `this.state.query.length > 0` to `this.state.query.length >= 0` in omnibox.tsx.

**Comment by cmslewis** [comment]
@llorca since you worked on `Omnibox` originally: thoughts on this?

**Comment by llorca** [comment]
@nowyasimi sounds like the `noResults` prop is what you're looking for:
> React child to render when filtering items returns zero results.

**Comment by nowyasimi** [comment]
Thanks for your reply. However, I believe that noResults only works if the query string length is greater than 0. 

The feature I'm implementing for the omnibox displays recent searches and I would like to display this before the user starts typing their query.

**Comment by llorca** [comment]
Oh right, I misread. Sounds like you're looking for an "empty state" kind of prop, which we don't have at the moment

**Comment by nowyasimi** [comment]
Thanks to everyone that helped out with this!
