### ISSUE TITLE
[Table] TypeError: core_1.Utils.throttleReactEventCallback is not a function

### ISSUE THREAD

**Issue by healingfromjava** [palantir/blueprint#1486]
### Bug report

- __Package version(s)__: blueprintjs/table@1.22.0
- __Browser and OS versions__: Version 62.0.3188.2 (Official Build) dev (64-bit); Ubuntu 17.04

#### Steps to reproduce

1. `yarn-upgrade-interactive`
1. `yarn start
`
#### Actual behavior

>   224 | //   causes sync'd quadrants to lag behind. thus, we preventDefault for onWheel and instead
>   225 | //   manually update all relevant quadrants using event.delta{X,Y} later, in the callback.
>   226 | //   this keeps every sync'd quadrant visually aligned in each animation frame.
> > 227 | _this.throttledHandleMainQuadrantScroll = core_1.Utils.throttleReactEventCallback(_this.handleMainQuadrantScroll);
>   228 | _this.throttledHandleWheel = core_1.Utils.throttleReactEventCallback(_this.handleWheel, { preventDefault: true });
>   229 | return _this;
>   230 | var _a, _b;
> 

Full output from console: https://gist.github.com/healingfromjava/3075f9aa02d462c8523d774c8a1c4920

#### Expected behavior

Table renders onscreen.

**Comment by giladgray** [comment]
@healingfromjava what version of __core__ are you using? this util function comes from that package (not from __table__) and was only added very recently.

**Comment by healingfromjava** [comment]
@giladgray At the time of reporting, I was using **core v1.24.0**. I've since upgraded again my dependencies to the following but the error is still present:

- blueprintjs/core: "^1.25.1"
- blueprintjs/datetime": "^1.20.0"
- blueprintjs/table": "^1.22.1"

**Comment by healingfromjava** [comment]
For what it's worth, **table v1.21.0** is working as expected with the latest version of **core v1.25.1**.

**Comment by giladgray** [comment]
can you check which versions of __core__ are actually being installed? it's possible that more than one is being brought in (from `yarn.lock`, for instance) and you're actually using an older version. that's the most likely casue here--the function is actually undefined cuz you're running old code.

**Comment by healingfromjava** [comment]
@giladgray That was the issue!

1. ```rm yarn.lock```
2. ```rm -rf node_modules```
3. ```npm install```

Would this be a Yarn-related issue or is there something going on with core that's causing multiple versions to be specified in the yarn.lock file?

(Feel free to close this if you like)

[bad_blueprint_yarn_lock.txt](https://github.com/palantir/blueprint/files/1247261/bad_blueprint_yarn_lock.txt)
