### ISSUE TITLE
Expose inputRef prop in <NumericInput />

### ISSUE THREAD

**Issue by joyt** [palantir/blueprint#1490]
Currently there's no clean way to access the input element reference in `<NumericInput />`. It should expose the same API as `<InputGroup />`.

Current workaround as suggested by @cmslewis is to access
`numericInputInstance as any).inputElement` after mounting.

**Comment by cathyxz** [comment]
I can take a stab at this, but I don't know if there are any weird edge cases that this could potentially break or what are appropriate tests to write for this. I'm curious to know what situations would merit the use of this `inputRef` on `NumericInput`?

**Comment by cmslewis** [comment]
@cathyxz The right solution here will actually be to add an `inputProps` prop, as in `TagInput`, `Omnibox`, `DateInput`, and others. This will give consumers much more control over the input group, and it will make `NumericInput`'s API consistent with those of other input-dependent components. The prop should look like this:

```tsx

interface INumericInputProps {
    // ...

    /**
      * Props to pass to the [input group](#core/components/forms/input-group.javascript-api).
      * `disabled` and `value` will be ignored in favor of the top-level props on this component.
      * `type` is fixed to "text" and `ref` is not supported; use `inputRef` instead.
      */
    inputProps?: HTMLInputProps & IInputGroupProps;

    // ...
}
```

Search the codebase for `inputProps.inputRef` for code samples.
