### ISSUE TITLE
Tabs2 indicator does not move when tabs are removed

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1491]
### Bug report

- __Package version(s)__:  @blueprintjs/core v1.25.1
- __Browser and OS versions__:  Firefox 55 and Chrome 60 on Ubuntu 17.04

#### Steps to reproduce

1. Create a Tabs2 component with several tabs
1. Select a tab
1. Make one of the previous tabs disappear

#### Actual behavior

The selection box or underline showing the selected tab doesn't move (both vertical and horizontal tabs)
![bug](https://user-images.githubusercontent.com/23741599/29620381-132224c6-881e-11e7-951d-b3e8b5f9ba99.png)

#### Expected behavior

The selection box or underline showing the selected tab should move following the selected tab

Check the following example code:

    import React, {Component} from "react";
    import "@blueprintjs/core/dist/blueprint.css";
    import {Tabs2, Tab2, Button} from "@blueprintjs/core";

    export class Tabs2Example extends Component {

        constructor(props) {
            super(props);
            this.state = {
                id: null,
                tabs: [{"name": "Tab 1", "id": "a", "visible": true}, 
                    {"name": "Tab 2", "id": "b", "visible": true}, 
                    {"name": "Tab 3", "id": "c", "visible": true}]
            }
        }

        visibleTab = index => {
            let newTabs = this.state.tabs;
            newTabs[index].visible = !newTabs[index].visible;
            this.setState({tabs: newTabs});
        };

        render() {
            return (
                <div>
                    {this.state.tabs.map((tab, index) => <Button key={index} style={{marginBottom: "20px"}} active={!this.state.tabs[index].visible} onClick={() => this.visibleTab(index)}>{"Tab " + (index + 1)}</Button>)}
                    <Tabs2 selectedTabId={this.state.id} vertical onChange={event => this.setState({id: event}, console.log(event))} >
                        {this.state.tabs.filter(i => i.visible).map((tab, index) =>
                            <Tab2 id={tab.id} key={index}
                                  title={tab.name} panel={null}/>)}
                    </Tabs2>
                </div>
            )
        }
    }

**Comment by giladgray** [comment]
bug is right here https://github.com/palantir/blueprint/blob/master/packages/core/src/components/tabs2/tabs2.tsx#L154: changing tabs doesn't move selection indicator.
