### ISSUE TITLE
[Table] Column resizing errors when using isRowHeaderShown={false}

### ISSUE THREAD

**Issue by jdiprizio** [palantir/blueprint#1500]
### Bug report

- __Package version(s)__: core : 1.26.0 ; table: 1.23.0
- __Browser and OS versions__: Chrome 60.0.3112.101 / Ubuntu 17.04

#### Steps to reproduce

Minimal repro code (Babel required):

```
import React from 'react';
import { Table, Column, Cell } from '@blueprintjs/table';

export default () =>
  (<Table isRowHeaderShown={false}>
    <Column name="Resize" renderCell={() => <Cell />} />
  </Table>);
```

#### Actual behavior

Throws `Uncaught TypeError: Cannot read property 'clientWidth' of undefined` and resizing can't be cancelled (stuck with column resizing).

#### Expected behavior

Resizing.

**Comment by cmslewis** [comment]
Whoops. Good catch! Will fix for our next release.
