### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by vaibhavswarnkar** [palantir/blueprint#1504]
Do we have a plan to a **Navigation Drawer** in the components suite of Blueprint? Navigation Drawer is a common pattern used nowadays.

**Comment by cmslewis** [comment]
@vaibhavswarnkar No plans at this time (Blueprint doesn't really aim to offer layout-specific components), but take a look at https://github.com/palantir/blueprint/issues/243 for past discussion on a similar idea, and take a look at `Overlay` for a component that may help you on your way to building a Navigation Drawer of your own.
