### ISSUE TITLE
[Core/Tabs2 regression] cannot set to large anymore when using component's API

### ISSUE THREAD

**Issue by bbenezech** [palantir/blueprint#1506]
This is a recent regression.
The CSS property`.pt-large` has been moved to `.pt-tab-list` level (instead of the top-level the component before).
Yet there is no (obvious or documented?) way to set it there when using the API (that generates the `.pt-tab-list` part).
I suggest adding a `large` property on the component (to mimic the `vertical` one).

Cheers and thanks for the excellent work!

**Comment by cmslewis** [comment]
Oy, sorry about that @bbenezech. Looks like we were distracted enough by `Table` issues last week that we didn't do a thorough enough pass on #1476. Fixing in PR #1510.

**Comment by cmslewis** [comment]
[P1 due to the regression]
