### ISSUE TITLE
Documentation site for 1.26.0 says version is 1.25.2

### ISSUE THREAD

**Issue by markhepburn** [palantir/blueprint#1508]
### Bug report

- __Package version(s)__: 1.26.0

![image](https://user-images.githubusercontent.com/56747/29754987-a08ffe42-8bd3-11e7-950d-a00a37c8af94.png)

I had a quick look around, but it looks like perhaps the site was built on an uncommitted version (there's no release-1.25.2 tag)

**Comment by cmslewis** [comment]
@markhepburn Hmm, weird. I'll look into it today.

**Comment by markhepburn** [comment]
Given there's already a new release (love your pace, btw :)) and the site looks fine again, do you want me to close this?  I'll leave it open in case you're worried there might still be a problem lurking.

**Comment by giladgray** [comment]
yep safe to close 👍

**Comment by cmslewis** [comment]
For what it's worth I know what happened last time that led to that weirdness, so the lesson is learned  👍
