### ISSUE TITLE
[Portal] Switch from unstable_renderSubtreeIntoContainer() to unstable_createPortal() for compatibility with React Fiber

### ISSUE THREAD

**Issue by sandys** [palantir/blueprint#1509]
we are facing the same issues as mentioned here - https://github.com/reactjs/react-modal/issues/484 and https://github.com/facebook/react/issues/9808#issuecomment-308085984

need to replace unstable_renderSubtreeIntoContainer with unstable_createPortal

**Comment by giladgray** [comment]
we cannot make this switch until we officially support React 16 #866, which will not happen for several months (until internal apps are ready to make the switch). 

i'm going to close this issue in favor of #866 for a single place to track the work.
