### ISSUE TITLE
Arbitrary sizes for icons

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1525]
Hey I'm just wondering if anyone knows a way to apply an arbitrary size to an icon. With css or via a prop? 

Thanks very much!

**Comment by tnrich** [comment]
Hmm it seems that it can be done via setting a font-size css attribute. Is that the recommended way?

**Comment by giladgray** [comment]
there's a callout in the [`Icon` component docs](http://blueprintjs.com/docs/#core/components/icon.css-api) that explains how to use non-standard sizes:

> Generally, icons should only be used at either 16px or 20px. However, if a non-standard size is necessary, set a `font-size` that is whole multiple of 16 or 20 with the relevant size class. You can instead use the class `pt-icon` to make the icon inherit its size from surrounding text.

**Comment by tnrich** [comment]
Whoops didn't see that. Thanks! 

I think as a naive user I would have expected most things, not just icons, to take a size prop (like buttons, icons etc). I like the standard sizes for most things, but sometimes you just need to set an arbitrary size. Maybe something to consider?

**Comment by llorca** [comment]
Icons are pixel-fitted for both 16px and 20px sizes (standard and large), so it wouldn't make sense to natively support additional sizes. If really needed, you can set a custom `font-size` yourself but note that you'll end up with a blurry icon.
