### ISSUE TITLE
Link to official base fiddle from docs

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1526]
Hi there,

I find myself often wanting to play around with a particular blueprint component (especially when trying to create a simple reproducible case to file a new issue) but don't know where to start. 

I know that fiddles have been created in the past, but maybe an official, up to date one could be mentioned and linked to in the docs? 

I know it would definitely help me out! 

Thanks!

P.S. I think it might be better to use something more modern like https://codesandbox.io/ than jsfiddle

**Comment by tnrich** [comment]
Here is the start of a fiddle on codesandbox: https://codesandbox.io/s/rjrlv1q3p

I think it has everything needed to run all of blueprint

**Comment by tnrich** [comment]
I still think this is extremely important/relevant. It should also probably be included in the issue template. I would love an updated v2 codesandbox also now..

**Comment by tnrich** [comment]
Here is a v2 updated one (in case I google this again looking for a blueprint codesandbox): https://codesandbox.io/s/4q9nv325jw

**Comment by llorca** [comment]
- make a sandbox that works
- save it somewhere convenient
- add link to issue templates

**Comment by tnrich** [comment]
Hmm I am still having trouble finding the official fiddle.. I would recommend adding it to a few more locations: 

- the bug report template under steps to reproduce: 
![image](https://user-images.githubusercontent.com/2730609/44431345-68dcc400-a552-11e8-92cf-8b4f76e8d812.png)

- the find functionality in the omni search of the docs: 

![image](https://user-images.githubusercontent.com/2730609/44431365-7c882a80-a552-11e8-8729-c92d2c7328b7.png)

If you did that I'm sure I wouldn't struggle with this anymore. Thanks!

Ps I did eventually find it here: 
![image](https://user-images.githubusercontent.com/2730609/44431415-a5102480-a552-11e8-8ede-7b9f7922861a.png)
