### ISSUE TITLE
Popover background is transparent by default? 

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1530]
Here is a link to a fiddle where both Popover and Popover2 look bad with default settings. Is that how they're supposed to work?
https://codesandbox.io/s/rjrlv1q3p

![image](https://user-images.githubusercontent.com/2730609/30128631-64a5770a-9311-11e7-8007-f3de3ce46149.png)

Thanks!

**Comment by adidahiya** [comment]
Popovers aren't meant to contain simple text content -- Tooltips are preferred for that; they come with extra padding that makes plain text look good inside them.

If you need the popover to have padding, we provide a standard padding style with `popoverClassName="pt-popover-content-sizing"`. This is mentioned in the docs.

![image](https://user-images.githubusercontent.com/723999/30144703-b27f450c-9341-11e7-8f43-aa877aecb547.png)
