### ISSUE TITLE
Export CSS variable strings for JS consumption

### ISSUE THREAD

**Issue by rcchen** [palantir/blueprint#1531]
I'm currently using [typestyle](https://github.com/typestyle/typestyle) in a couple of projects and am interested in having `variables.scss` available as an autogenerated typed JS importable equivalent.

Example:

```ts
import { Variables } from "@blueprintjs/core";

// some valid variables
// * Variables.PT_ELEVATION_SHADOW_0
// * Variables.PT_DIALOG_BOX_SHADOW
```

**Comment by awdyson** [comment]
👍  for the request and a current workaround, for scss at least:

- Install [sass-all-variable-loader](https://github.com/milichev/sass-all-variable-loader)

- As a module rule in `webpack.config.js`:
```
{
  test: /variables\.scss$/,
  use: [scssDefinitionsLoader, {
    loader: 'sass-all-variable-loader',
    // due to a bug, make sure the options object exist, whether or not you want to camelCase the output
    options: { camelCase: true },
  }],
}
```

- Add a declaration file that `tsconfig.json` knows of:
```
declare module '*.scss' {
  const content: {[variable: string]: string};  
  export = content;
}
```

- Import what you need:
```
import { lightGray5, ptElevationShadow1 } from '@blueprintjs/core/lib/scss/variables.scss';
```

---

While this approach will let you import variables, the declaration file will allow you to try accessing properties that don't exist. If anyone has more experience with WebPack, I'd be curious to see if we could generate more accurate definitions.

**Comment by lukeshiels** [comment]
Is there any update on this? I don't think it would be too hard to implement with 'node-sass' and 'sass-extract'
