### ISSUE TITLE
Missing first row of ghost cells 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1535]
### Bug report

- __Package version(s)__: 
- __Browser and OS versions__: chrome, mac

#### Steps to reproduce
 
![image](https://user-images.githubusercontent.com/24398123/30190597-1c095036-93f0-11e7-9cd1-e39d0d9600e4.png)

**Comment by cmslewis** [comment]
@tgreenwatts is this still a problem as of the latest release? I can't repro, and I thought I fixed it in #1515.

**Comment by tgreenwatts** [comment]
Sorry about that, can't repro in the release PR (I could in other PRs, but I'll trust the release one)
