### ISSUE TITLE
[Tree] large icons with tooltip

### ISSUE THREAD

**Issue by dixitk13** [palantir/blueprint#1536]
[Trees component](http://blueprintjs.com/docs/#core/components/tree.tree-node-interface)

Can we have an ability to set large icons and have tooltips on top of them?

Currently all I could get to was standard icon with tooltips next to the space to it. Would like to have the icons themselves to have tooltips with ability to set large sizes. 

![screen shot 2017-09-07 at 8 48 38 pm](https://user-images.githubusercontent.com/8632659/30195393-f97c086a-940d-11e7-96af-b942815ed7a3.png)

**Comment by llorca** [comment]
Large icons for trees would only make sense in the context of large tree items (i.e. 40px height), which we don't support right now. Happy to take a contribution for `.pt-large` on `.pt-tree` with large icons
