### ISSUE TITLE
How to create a dialog which can be dragged around the window?

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1540]
I am using `http://blueprintjs.com/docs/#core/components/dialog` to create a dialog. It works fine but it doesn't support drag movement. I want to move the dialog by drag the title of the dialog around the window. How can I do that in this dialog component?

**Comment by adidahiya** [comment]
I recommend creating your own dialog using the `<Overlay>` component and adding drag interactions to it.

**Comment by zhaoyi0113** [comment]
ok got it. I will have a try. thanks.
