### ISSUE TITLE
Component Focus Outline

### ISSUE THREAD

**Issue by vaibhavswarnkar** [palantir/blueprint#1543]
I am getting focus outline on each component after click on them. Is it a default behavior for all of the components?

Do I have to add `focus:none` property on each component or there is a global solution available.

**Comment by llorca** [comment]
@vaibhavswarnkar http://blueprintjs.com/docs/#core/accessibility.focus-management

**Comment by vaibhavswarnkar** [comment]
@llorca Thanks for pointing to documentation, I did not look carefully, sorry for making noise.
