### ISSUE TITLE
pt-icon list name

### ISSUE THREAD

**Issue by jsina** [palantir/blueprint#1545]
How could I find the list of icons' name?

**Comment by jsina** [comment]
the tricky way is look for all css class name begin with ".pt-icon-" on blueprintjs/core/blueprint.css :)

**Comment by llorca** [comment]
There's a search at http://blueprintjs.com/docs/#core/icons

**Comment by CrommVardek** [comment]
> There's a search at http://blueprintjs.com/docs/#core/icons

Link is no longer correct.

New link is [https://blueprintjs.com/docs/#icons](https://blueprintjs.com/docs/#icons)
