### ISSUE TITLE
[Table] Quick ideas for perf exploration

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1547]
- __Package version(s)__: v1.27.0

- [ ] Make sure we're using `shouldComponentUpdate` properly in every `Table` component.
    - Enforce expectations with unit tests (e.g. whether a particular prop change needs to be shallow or deeply unequal to trigger an update).
    - Can use [`why-did-you-update`](https://github.com/garbles/why-did-you-update) to help here.

- [ ] Consider introducing a higher-order component to accept additional props instead of mutating props on user-provided `<Cell>`s etc. (e.g. when injecting `resizeHandle`s).
    - Goal is to prevent shallowly unequal `resizeHandle` instances etc. from failing `shouldComponentUpdate` equality checks.

**Comment by tgreenwatts** [comment]
Also "unit test `shouldComponentUpdate`" right?

**Comment by cmslewis** [comment]
@tgreenwatts That's what I tried to say with this point:

> Enforce expectations with unit tests (e.g. whether a particular prop change needs to be shallow or deeply unequal to trigger an update).

**Comment by cmslewis** [comment]
A new idea, definitely helpful:

- Because of the `Grid`'s default bleed, we're rendering extra, _entirely hidden_ columns and rows in the `TOP`, `LEFT`, and `TOP_LEFT` quadrants. We should be more strict with those quadrants; in fact, we should never need to render bleed columns in the `LEFT` quadrant, bleed rows in the `TOP` quadrant, or either in the `TOP_LEFT` quadrant. This will save us a lot of wasted rendering effort!

Will move on this as soon as #1578 is merged.

**Comment by cmslewis** [comment]
Another idea, also helpful:

```tsx
private shouldHideLeftQuadrants() {
    const { isRowHeaderShown, numFrozenColumns } = this.props;
    return !isRowHeaderShown && numFrozenColumns != null && numFrozenColumns === 0;
}
```

Then in `tableQuadrantStack.tsx`:

```tsx
const shouldHideLeftQuadrants = this.shouldHideLeftQuadrants();
const maybeLeftQuadrant = shouldHideLeftQuadrants ? undefined : /* <TableQuadrant /> */;
const maybeTopLeftQuadrant = shouldHideLeftQuadrants ? undefined : /* <TableQuadrant /> */;


return (
    <div>
        <TableQuadrant quadrantType={QuadrantType.MAIN} />
        <TableQuadrant quadrantType={QuadrantType.TOP} />
        {maybeLeftQuadrant}
        {maybeTopLeftQuadrant}
    </div>
);
```

Will then need to comb through the rest of the file and make sure all references to `LEFT` and `TOP_LEFT` elements are first null-checked before being accessed.

**Comment by cmslewis** [comment]
^ Both of those somewhat dramatically reduce the number of cells being rendered; currently, we're rendering a lot of cells that are forever hidden because of those bleed cells.

**Comment by tgreenwatts** [comment]
I think we can close this? @cmslewis ?

**Comment by cmslewis** [comment]
Yeah, we can go ahead and close.
