### ISSUE TITLE
Add Custom renderDay inside DateRangePicker

### ISSUE THREAD

**Issue by bluematter** [palantir/blueprint#1548]
Currently, there isn't a way to prepend a 0 on all dates 1-9. It would be nice to have an option for this or to add props into the DayPicker.

I see the `react-day-picker` library is being used. There is a prop called `renderDay` that is going to waste. Here is an example https://github.com/gpbl/react-day-picker/blob/16a3cfb91542b1de1957228b085d3120d62dbd85/docs/examples/src/advanced-day.js

Would love to prepend a 0. Looks aesthetically pleasing to me.

<img width="725" alt="screen shot 2017-09-11 at 11 50 03 am" src="https://user-images.githubusercontent.com/1669104/30291441-c705239e-96e7-11e7-848f-bcc1682f59c0.png">

**Comment by giladgray** [comment]
@bluematter thanks for reporting! any interest in contributing a fix? should be straightforward to expose that `renderDay` prop.

**Comment by llorca** [comment]
Resolved with #1647
