### ISSUE TITLE
Allow tables to have columnHeaderCell menu only in interaction bar

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1555]
It's my understanding that today if a table has a `renderMenu` set on the `ColumnHeaderCell`, it will always appear both in the dropdown caret and header cell context menu. Should we allow users to opt out of the context menu?

**Comment by tgreenwatts** [comment]
@llorca for thoughts

**Comment by llorca** [comment]
No, we shouldn't. If you declare a menu, you get it both via the caret and the context menu.

I'm curious though, what makes you think we should disallow context menus?
