### ISSUE TITLE
Use Popover2 in Table truncated popover

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1557]
Truncated cells at the edge of the table go off the edge of the screen. We should use Popover2 to prevent this and smart position

**Comment by adidahiya** [comment]
how about:

> The React component to use for popovers inside the table. The default is `Popover` from `@blueprintjs/core`, but you also may choose `Popover2` from `@blueprintjs/labs`.

```ts
popoverComponent: React.Component<IPopoverSharedProps, any>;
```

**Comment by giladgray** [comment]
something more generic like `popoverRenderer: (content: React.ReactNode) => JSX.Element` does not require some shared props interface.

**Comment by tgreenwatts** [comment]
Would this be done as part of the Blueprint2.0 work? @cmslewis

**Comment by cmslewis** [comment]
We already swapped to `Popover2` under the hood, so this is already resolved.
