### ISSUE TITLE
Development server does not work on Windows

### ISSUE THREAD

**Issue by costagolub** [palantir/blueprint#1559]
Have a problem with running the development server. Spent for a while but can't fix it. Is anyone knows how to fix it, maybe someone encouraged the same problem?
windows 10
Node  7.10
npm 4.2.0

And that's a piece of code from the terminal 
```
[13:54:19] Starting 'sass-variables'...
[13:54:20] 'sass-variables' errored after 318 ms
[13:54:20] Error in plugin 'gulp-less'
Message:
    'mixins.less' wasn't found. Tried - F:\projects\Github.com\blueprint\packages\core\dist\mixins.less,mixins.less in file F:\projects\Github.com\blueprint\packages\core\dist\variables.less line no. 175
Details:
    type: File
    filename: F:\projects\Github.com\blueprint\packages\core\dist\variables.less
    index: 4117
    line: 175
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: @import "colors";,@import "mixins";,
    lineNumber: 175
    fileName: F:\projects\Github.com\blueprint\packages\core\dist\variables.less
```

**Comment by giladgray** [comment]
@costaglub sorry bud, windows development is not supported. IIRC there's a task that relies on some UNIX commands and we can't be bothered to fix it cuz the whole team uses Macs. 

Happy to accept contributions though!

**Comment by giladgray** [comment]
What command are you running there?

**Comment by costagolub** [comment]
I see, probably that's the reason.
the `yarn gulp`
Thanks!
