### ISSUE TITLE
[Table] Rename the onFocus prop

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1562]
- __Package version(s)__: v1.27.0

`Table`'s `onFocus` callback conflicts with `DOMAttributes<T>`'s `onFocus` callback:
- The former is invoked when the focused cell moves.
- The latter is invoked when a DOM element receives `focus` and becomes the `document.activeElement`.

We should probably rename `Table`'s callback to something else to clarify the difference. Ideas:
- `onCellFocus`
- `onFocusedCellChange`

**Comment by cmslewis** [comment]
// FYI @giladgray

**Comment by llorca** [comment]
`onCellFocus` SGTM

**Comment by giladgray** [comment]
> invoked when the focused cell moves

this sounds like a `Change` event, not a `Focus` event, so `onFocusedCellChange` is more accurate.

**Comment by adidahiya** [comment]
> this sounds like a Change event, not a Focus event, so onFocusedCellChange is more accurate.

with that logic you could argue that `focus` on regular DOM elements also _changes_ the `document.activeElement` and reach a conclusion that it should be called `onFocusChange` instead of `onFocus`...

so I'm with @llorca here, `onCellFocus` SGTM

**Comment by cmslewis** [comment]
Yeah, the focused cell doesn't receive literal `focus`, but it does get a blue box around it and serve as the point of "focus" from which tons of other behaviors emanate in the table.

Another consideration: if we went with `onCellFocus`, would literally `focus`ing in an `EditableCell` lead to excessive conceptual/naming confusion? That's the one major case where something could be properly "`focus`'d" within the table.

I could go either way.

**Comment by adidahiya** [comment]
fixed by #1890
