### ISSUE TITLE
[Labs/Select] Select doesn't stay attached to target when window resized

### ISSUE THREAD

**Issue by brieb** [palantir/blueprint#1564]
### Bug report

The Select component doesn't stay attached to the target element when window resized

- __Package version(s)__: master branch

#### Steps to reproduce

1. Open `<Select>`
1. Resize browser window

#### Actual behavior

![sep-13-2017 14-00-16](https://user-images.githubusercontent.com/723547/30400530-08479576-988c-11e7-8a17-ff63f10c6c2c.gif)

#### Expected behavior

`<Select>` stays pinned to the target element

**Comment by brieb** [comment]
Umm... on second thought this doesn't appear to be happening on v1.27.0 on http://blueprintjs.com/docs/#labs.select

**Comment by llorca** [comment]
Most likely fixed with `Popover2` anyway
