### ISSUE TITLE
[Core] Menus - pass popoverProps property

### ISSUE THREAD

**Issue by AlexMarvelo** [palantir/blueprint#1567]
I want to open submenu popover on click, not on hover. Seems like there is no way to control `interactionKind` inside menuItem component.

What about passing `popoverProps` object to menuItem, like in `Labs/Select`?

**Comment by cmslewis** [comment]
@llorca what are your thoughts from an interaction-design perspective?

**Comment by giladgray** [comment]
certainly part of the reason for not exposing `popoverProps` (aside from the fact that we weren't in the habit of doing so when the component was written) was to keep the interactions consistent across all menus.

**Comment by llorca** [comment]
Gilad's correct, we used to be more opinionated. Harder to justify now that we have `popoverProps` in many places. I think we can (and should) definitely still be opinionated about nice & consistent interaction defaults, and I wouldn't be opposed to also providing `popoverProps` in this case

**Comment by giladgray** [comment]
💯  agreed
