### ISSUE TITLE
Multiline EditableText height isn't calculated correctly for long strings with no spaces

### ISSUE THREAD

**Issue by szabolcsx** [palantir/blueprint#1572]
### Bug report

- __Package version(s)__: 1.27.0
- __Browser and OS versions__: Chrome 60.0.3112.113 on Windows 10

#### Steps to reproduce

1. Open http://blueprintjs.com/docs/#core/components/editable-text
1. Type in a really long string without any spaces to the multiline EditableText, until all the vertical space is covered with text. Example text used: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

#### Actual behavior

A vertical scrollbar appears instead of the component's height being increased.

#### Expected behavior

The component's height should increase to fit the text.

I was able to reproduce the error with the current latest version and also on the BlueprintJS documentation page.
If you keep adding newlines to the EditableText, it's height starts to grow. It only has this problem with long strings without spaces which are taking up more space than what is available without the component having to be resized.

**Comment by giladgray** [comment]
fix: add `word-wrap: break-word;` on `.pt-editable-text.pt-multiline .pt-editable-content`
