### ISSUE TITLE
[DatePicker] disable outside days option

### ISSUE THREAD

**Issue by popaulina** [palantir/blueprint#1574]
Is there a way to disable `enableOutsideDays`? It is done by default in react-day-picker, and I'd like to use that option.

**Comment by cmslewis** [comment]
@popaulina Not at the moment. Can you elaborate on your use case? This is one of those details on which we decided to take a stance early in the design process, but I don't know if any of us feels particularly strongly about requiring the outside days to be shown at this point. @llorca for thoughts.

**Comment by llorca** [comment]
What about exposing `react-day-picker` props via composition? We have similar issues open, this one for instance https://github.com/palantir/blueprint/issues/1548.

**Comment by popaulina** [comment]
@cmslewis For what I need, I have to have disabled dates and while that is something that can be worked around, if a disabled date is an outside date then it shows up looking like an outside date rather than a disabled one. I'm not even sure why minDate & maxDate needed to override disabled dates rather than just passing them down as modifiers.

**Comment by cmslewis** [comment]
@popaulina sorry, haven't had bandwidth to work on this and won't for the forseeable future. Would you be interested in working on a PR? Happy to help shepherd it through once it's open.

**Comment by llorca** [comment]
Resolved with #1647
