### ISSUE TITLE
Icon Contribution

### ISSUE THREAD

**Issue by moviemaria** [palantir/blueprint#1575]
We would like to know if you have any standard guidelines for the icon creation.

Do you have a list of icons existing so that we can create and contribute to the existing list.

We have created a set of icons and we would like to add those icons to the blueprint.js core             components, Can we contribute the icons to the blueprint.js core components.

**Comment by adidahiya** [comment]
Unfortunately we won't be taking third-party contributions to Blueprint's icon font.

We would like to support better extensibility of icons though, this is an open feature request here: https://github.com/palantir/blueprint/issues/365

**Comment by llorca** [comment]
As Adi said, with #365, you'll be able to roll your own icon set 👍
