### ISSUE TITLE
[Labs/Select] Page scrolls when popover opens

### ISSUE THREAD

**Issue by brieb** [palantir/blueprint#1582]
When you click on the button and the popover opens, the page scrolls all the way back up.

**Comment by brieb** [comment]
Surfaced here https://github.com/palantir/blueprint/pull/1579

**Comment by brieb** [comment]
Note that this doesn't happen if we do `autoFocus={false}` here https://github.com/palantir/blueprint/blob/874b757/packages/labs/src/components/select/select.tsx#L165

**Comment by llorca** [comment]
Maybe I'm missing something, but I don't think `InputGroup` supports `autoFocus`, that's an `Overlay` thing. Is it about `<input autofocus />`?

Problem with removing `autoFocus={false}` from that `InputGroup` is that it breaks the UX: you can click on the button to trigger the popover, but the search input isn't automatically focused, requiring another extra click to search

**Comment by brieb** [comment]
Ya it is on the input. Not saying that we should remove the behavior, just
a clue for narrowing in on the bug. I 100% agree that the ux would break if
we were to remove it.
