### ISSUE TITLE
[Labs/Tooltip2] Tooltip not closing on  disabled button

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1591]
### Bug report

- __Package version(s)__: 0.9.0
- __Browser and OS versions__: Google Chrome

#### Steps to reproduce

1. Create a Tootltip2 component with a button inside
2. Make the button have a disabled state

#### Actual behavior

The tooltip will not close once that it's open. I experience this on Google Chrome, not on Firefox. For example:
`<Tooltip2 content={"Testing Tooltip2"}>
                    <Button className="pt-minimal"
                            disabled
                            iconName="full-circle"/>
                </Tooltip2>`
If I change from a disabled state to a disabled appearance it does work as expected:
`<Tooltip2 content={"Testing Tooltip2"}>
                    <Button className="pt-minimal pt-disabled"
                            iconName="full-circle"/>
                </Tooltip2>` 

#### Expected behavior

Tooltip should only be open on hover

**Comment by llorca** [comment]
We're calling this out in both the `Button` and `Tooltip` docs:
- http://blueprintjs.com/docs/#core/components/button.javascript-api
- http://blueprintjs.com/docs/#core/components/tooltip

You should be good to go with `AnchorButton`
