### ISSUE TITLE
Consider migrating away from BSD+Patents license

### ISSUE THREAD

**Issue by ilbmiller** [palantir/blueprint#1613]
Facebook has abandoned the BSD+Patents licensing approach for React due to Open Source push back (they are moving React to MIT License).    See https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

@blueprintjs has the same licensing approach (BSD+Patents).  Unfortunately, my company's legal department is uncomfortable with the BSD+Patents approach (and I'm not legally qualified to debate the merits).  This is sad as @blueprintjs is a very nice product!

So this issue is simply a request for @blueprintjs to consider migrating to using a MIT License (or Apache 2.0).  I believe this would help @blueprintjs grow their user base.

Thanks for your consideration!

**Comment by llorca** [comment]
Our legal department is currently evaluating alternative licenses for Blueprint. Watch this issue for updates in the near-ish future.

**Comment by vilav** [comment]
+1 Exact thoughts and concerns as @ilbmiller

**Comment by chenfanggm** [comment]
I was evaluate UI Component Lib for my company today. And I was so exited to find Blueprint until I see the LICENSE. Please seriously consider change it to MIT, so more and more company can join and contribute to this project. Especially that Blueprint's look and feel is more likely a tool like theme. Most user would come from the company wise. However, now I have to give it up. Please again ask the legal department, and hopefully I could propose it before my evaluation ends.
Thanks for all your hardworking.

Best,
Chen

**Comment by adidahiya** [comment]
We're now on Apache 2.0. The next releases (core 1.33.0, table 1.30.0, datetime 1.24.0, labs 0.13.0) will include this license.

**Comment by magdmartin** [comment]
Should we reopen since we are waiting for more feedback from Palantir legal? See [#1751#issuecomment-346198034](https://github.com/palantir/blueprint/pull/1751#issuecomment-346198034)

**Comment by llorca** [comment]
Nope. We already migrated to Apache 2.0

**Comment by pombredanne** [comment]
This is not an Apache 2.0 license, but something that looks like one and is IMHO misleading. Please see #2602
