### ISSUE TITLE
Table header leaving room for actions menu caret when interaction bar enabled

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1615]
Interaction bar is enabled so we don't need to reserve this space

![image](https://user-images.githubusercontent.com/24398123/30832416-dfc52f28-a1ff-11e7-9683-d77ef20b8f00.png)

```.bp-table-column-name-text {
    padding-right: 30px;```

**Comment by cmslewis** [comment]
Noice catch @tgreenwatts. 👍

**Comment by tgreenwatts** [comment]
Noice catch ~~@tgreenwatts~~ @llorca . 👍

**Comment by cmslewis** [comment]
@tgreenwatts @llorca I can't repro this with Blueprint default styles.

**Comment by llorca** [comment]
Gotcha, can't repro either: 
![image](https://user-images.githubusercontent.com/199754/30927076-17b79e94-a36c-11e7-979a-ae0a64ed83ff.png)

Again, I bet this has to do with the lack of restriction on header content and how folks can do whatever they want. The original screenshot of this issue probably means they had some leftover styles from a previous feature
