### ISSUE TITLE
[Table] Proposal: prop-name changes

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1625]
Filing as of:
- __Package version(s)__: 1.28.0

Opening this issue to track proposed prop-name changes for an eventual `table` 2.0 release:

- [x] `renderColumnHeader` -> `renderColumnHeaderCell`
    - a `ColumnHeader` is a fundamentally different component in the table codebase than a `ColumnHeaderCell`. Would be nice if the prop name reflected more clearly what the function is returning.
- [x] `renderRowHeader` -> `renderRowHeaderCell`
    - Same reasoning as above.
- [x] `onFocus` -> `onCellFocus` OR `onFocusedCellChange` (see: #1562)
    - The term "focus" can be confused with the first-class browser concept of focusing an `<input>`, and there are `onFocus` callbacks elsewhere in the codebase that are invoked when that event happens. We should rename our focused-cell callback to something more clear. 

And generally: I'd love to move toward a simpler, more consistent naming scheme for all of the feature-flag props.
- [x] `allowMultipleSelection` -> `enableMultipleSelection` (sidenote: this prop is a little unclear; I originally thought it meant "enable disjoint selections," not "enable multi-row/column selections AND disjoint selections")
- [x] `enableFocus` -> `enableFocusedCell`
- [x] `fillBodyWithGhostCells` -> `enableGhostCells`
- [x] `isColumnReorderable` -> `enableColumnReordering`
- [x] `isColumnResizable` -> `enableColumnResizing`
- [x] `isRowHeaderShown` -> `enableRowHeader`
- [x] `isRowReorderable` -> `enableRowReordering`
- [x] `isRowResizable` -> `enableRowResizing`
- [x] `useInteractionBar` -> `enableColumnInteractionBar`

Others?

**Comment by cmslewis** [comment]
// CC @llorca for thoughts

**Comment by llorca** [comment]
Love this! A few comments and questions:
- agree `enableMultipleSelection` isn't quite clear, plus you could argue that with `enableMultipleSelection=false`, you can select a single column containing multiple cells which kinda means a multiple selection in the end...
- `useInteractionBar` -> `enableColumnInteractionBar`: can you imagine use cases where we'd need some kind of extra interaction bar for row headers?
- naive question, but is enabling resizing on rows and columns separately legit? Shouldn't it be a global table resizing option?

**Comment by cmslewis** [comment]
> `enableMultipleSelection`
Yeah, this one will take more thinking to get right. Maybe it's okay now; I don't know.

> `enableColumnInteractionBar`
It's possible `enableInteractionBar` would be sufficient. I just thought `...Column...` would make things clearer, since that's what the prop affects.

> is enabling resizing on rows and columns separately legit
I don't see harm in keeping them separate, but I'm not sure how often people actually do that.

**Comment by llorca** [comment]
👍 

Is `enableMultipleSelection` actually necessary? Can't you achieve the behavior of `enableMultipleSelection={false}` with the transformed regions API or something?

**Comment by cmslewis** [comment]
> Can't you achieve the behavior of enableMultipleSelection={false} with the transformed regions API or something?

That sounds messy, plus there's a bunch of nuanced logic that looks into the `allowMultipleSelection` prop (as currently named). I'd rather not depend on `selectedRegionTransform` for first-class operations like the single-cell selection mode.

**Comment by billyjanitsch** [comment]
Shouldn't `renderColumnHeader` -> `columnHeaderCellRenderer`, etc., per #293?

**Comment by giladgray** [comment]
@cmslewis @themadcreator status here? have these renames been completed?

**Comment by adidahiya** [comment]
fixed by #1890
