### ISSUE TITLE
Suggestion for documentation on including blueprint.css

### ISSUE THREAD

**Issue by elementswebsolutions** [palantir/blueprint#1626]
Hi, please accept my apologies if this is the wrong place to post this kind of thing.

On this page of the documentation -- http://blueprintjs.com/docs/#blueprint -- it says to include blueprint.css in the html file as follows:

`   <link href="path/to/node_modules/@blueprintjs/core/dist/blueprint.css" rel="stylesheet" />`

However, for me that generated this error:

_blueprint.css was not loaded because its MIME type, “text/html”, is not “text/css”._

What worked was to include the following in my js file:

`import '../node_modules/@blueprintjs/core/dist/blueprint.css';`

I'm not sure if the documentation is out of date, or if there is something different about my setup.  Perhaps the instructions there will work for other people.  But my suggestion is to put a note there to tell people about this other way of including the file, if they get that error.  

Thanks

**Comment by cmslewis** [comment]
Does this work for you:

`<link href="path/to/node_modules/@blueprintjs/core/dist/blueprint.css" rel="stylesheet" type="text/css" />`

?

**Comment by adidahiya** [comment]
It depends on the web server you're using and how you're hosting the file. `type="text/css"` is not always necessary. This is mostly out of scope for the blueprint documentation site.

**Comment by elementswebsolutions** [comment]
I am running on localost:3000 on a Windows machine.
