### ISSUE TITLE
Popover does not inherit theme change till second click

### ISSUE THREAD

**Issue by abrooksv** [palantir/blueprint#163]
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Windows 10, Firefox 49.0.2

#### Describe the issue:

1.  Go to http://blueprintjs.com/docs/#components.popover
2.  Make sure inherit theme is selected
3.  Change theme using the icon in navbar
4.  Click button 'Popover target'
5. Dismiss and click it again

#### Actual behavior:

Does not inherit the theme change till second click

#### Expected behavior:

Should inherit the team change on first click

**Comment by adidahiya** [comment]
Acknowledged as a bug; however, this is low priority. In practice, this mostly just applies to the docs site because applications don't dynamically change themes often.
