### ISSUE TITLE
Popover with disabled actuation button still shows on button click

### ISSUE THREAD

**Issue by rheinheimer** [palantir/blueprint#1635]
### Bug report

- __Package version(s)__: 1.29
- __Browser and OS versions__: n/a

#### Steps to reproduce

1. Create a Popover with a child Button
1. Set Button prop `disabled = {true}`
1. Click the button

#### Actual behavior

The Popover is shown (in my case, showing a Menu, as in http://blueprintjs.com/docs/#core/components/menu.dropdown-menus). The image below shows the popup, even though the button is disabled.

![image](https://user-images.githubusercontent.com/9124277/30943744-05837860-a3c1-11e7-828e-2fc1f41cea34.png)

#### Expected behavior

The Popover should not be shown if the actuating button is disabled.

**Comment by cmslewis** [comment]
Try passing `isDisabled=true` to the Popover as well. The popover target can be arbitrary JSX content, so we don't have a foolproof way of reaching into it and determining if the target is disabled (e.g. imagine if you have a `<div>` around your disabled `Button`).

@giladgray correct me if I'm wrong.
@brieb also dealt with this recently in other feature work.

**Comment by cmslewis** [comment]
@rheinheimer I'll close for now. LMK if I'm totally off-base and I can reopen.

**Comment by llorca** [comment]
Dupe of https://github.com/palantir/blueprint/issues/967 https://github.com/palantir/blueprint/issues/1591? Try `AnchorButton` instead of `Button`
