### ISSUE TITLE
[Table] Utils.shallowCompareKeys is not a function

### ISSUE THREAD

**Issue by locnguyen** [palantir/blueprint#1639]
I'm unclear about what could be wrong here. I copied this out of my app where I'm trying to get the simplest example working with some hardcoded data. Any suggestions?

blueprintjs/core: 1.29.0
blueprintjs/table: 1.26.1

```
import * as React from 'react';
import { Table, Column, Cell } from '@blueprintjs/table';

class HomePage extends React.Component<{}, {}> {
    render() {
        return (
            <div>
                <h1>Home</h1>

                <Table numRows={10}>
                    <Column name="Foobar" renderCell={idx => <Cell>{idx}</Cell>} />
                </Table>
            </div>
        );
    }
}

export default HomePage;
```

![screen shot 2017-09-29 at 7 49 54 am](https://user-images.githubusercontent.com/21346/31021570-09d6304e-a4eb-11e7-955d-edc696abbe86.png)

**Comment by cmslewis** [comment]
Hmm, we recently moved that and a few other utility functions from `@blueprintjs/table` into `@blueprintjs/core`. Lemme investigate the state of things and get back to you in a bit.

**Comment by cmslewis** [comment]
Okay, I think I found the problem. I think it's a botched `1.26.1` patch release on our end (oh the irony) and will be fixed in our next release, which I hope to cut today.

**Comment by patrickdevivo** [comment]
@cmslewis has this been resolved?

**Comment by cmslewis** [comment]
@patrickdevivo Will be resolved today in 1.30.0 (#1642).

**Comment by cmslewis** [comment]
Just cut the 1.30.0 release. Should be resolved now!

**Comment by lukas1994** [comment]
could you push 1.30.0 to npm?

**Comment by cmslewis** [comment]
@lukas1994 the build/publish failed due to a flaky test. Retriggered just now.

**Comment by cmslewis** [comment]
@lukas1994 @patrickdevivo - should be published on npm now!
