### ISSUE TITLE
MenuItem's submenu is closed when clicking the MenuItem

### ISSUE THREAD

**Issue by msmontoya** [palantir/blueprint#1640]
### Bug report

- Blueprintjs core v1.29.1
- Chrome v61

#### Steps to reproduce

1. Visit the v1.29.1 docs (this has been around for awhile though, i think) [Context Menu page](http://blueprintjs.com/docs/#core/components/context-menu)
1. Trigger the context menu & hover over a MenuItem with a submenu (e.g. 'Insert..."), the submenu will appear
1. Click the same MenuItem ('Insert...'). The submenu will disappear.
1. The only way to get the submenu back is to re-hover over the MenuItem

#### Actual behavior

Clicking on a MenuItem with a submenu will close the submenu, and subsequent clicks do not cause it to re-appear

#### Expected behavior

Most context menus I use, the submenu will persist regardless of # of clicks on the primary menu item.

Thanks for what you folks are doing with this library, it's great.

**Comment by strickland84** [comment]
I have the same issue, it would be great to see a fix soon. Thanks for the library!

**Comment by llorca** [comment]
Accepting contributions, feel free to propose a fix

**Comment by giladgray** [comment]
this seems resolved in 2.0, but unlikely to be port-able to 1.0 as it requires Popover2 / Popper.js.
