### ISSUE TITLE
Datepicker throws in test enviroment

### ISSUE THREAD

**Issue by tobilen** [palantir/blueprint#1643]
### Bug report

- __Package version(s)__: 1.22.0
- __Browser and OS versions__: Enzyme2, Jest 21.2.1

#### Steps to reproduce

1. mount DateInput component with enzyme test renderer
2. get runtime error `clientHeight` of undefined. Undefined refers to targetElement in `packages/core/src/components/popover/popover.tsx` ( https://github.com/tobilen/blueprint/blob/2e78513ed14a2407447028b8551138fa6394fce6/packages/core/src/components/popover/popover.tsx#L424 )

#### Actual behavior

Tries to access HTMLElement references, which are not really accessible in the testing enviroment.

#### Expected behavior

Should not set state if no targetElement can be found.

Repro repo: https://github.com/tobilen/blueprint-issue-1643

**Comment by tobilen** [comment]
still exists in `1.30.0`. Doesnt look like the fix is published

**Comment by adidahiya** [comment]
Yeah, it's not published, but we close the issue as soon as it's merged into master.

**Comment by tobilen** [comment]
ok, thanks for clearing that up 👍
