### ISSUE TITLE
[Table] Investigate proper controlled usage of columnWidths and rowHeights

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1649]
### Bug report

- __Package version(s)__: v1.27.0

#### Steps to reproduce

1. Pass a `columnWidths` array of defined, numeric values to `<Table>` with `isColumnResizable=true`
1. Resize the first column.

#### Actual behavior

Column is resized despite being controlled.

#### Expected behavior

Column _not_ resized. New size should be emitted via `onColumnWidthChanged`, and the consumer should have to pass in the new size via `columnWidths`.

**Comment by cmslewis** [comment]
Another consideration: when you use an instance method to resize many rows at once, (1) that should only actually happen if `rowHeights` and/or `columnWidths` are _not_ controlled, and (2) `Table` should thus invoke a callback with every affected row/column index and its new size. Our current callbacks provide only a single `index` and `size` at a time, so we'd need to refactor our callbacks to something that takes many in bulk.

**Option 1: Array of all sizes.**

```tsx
onRowHeightsChange(rowHeights: number[])
onColumnWidthsChange(columnWidths: number[])
```

This works fine, because you can just toss the returned array straight back into the corresponding prop on the `Table`, but it's a little annoying if you're trying to tell which indices actually _changed_.

**Option 2: Array of all sizes + array of changed indices.**

```tsx
onRowHeightsChange(rowHeights: number[], changedIndices: number[])
onColumnWidthsChange(columnWidths: number[], changedIndices: number[])
```

Maybe we could provide the changed indices in a second array parameter to each callback. Would this be useful to consumers?

**Option 3: Map of changes indices => new sizes**

```tsx
interface IIndexSizeMap {
    [index: number]: number;
}

onRowHeightsChange(indexSizes: IIndexSizeMap)
onColumnWidthsChange(indexSizes: IIndexSizeMap)
```

This resolves the weird two-parameter approach into a single parameter, but it also requires post-processing to convert the sparse index map into a complete array that will be passed into the `Table` anew. That's annoying.

--

Seems like **Option 2** works best if people care about the indices that changed, or we could fall back to **Option 1** if not.

**Comment by giladgray** [comment]
closing as a) investigated b) decided not to implement.
