### ISSUE TITLE
Checkbox, Radio, and Switch Example Github Links are broken

### ISSUE THREAD

**Issue by zfranklyn** [palantir/blueprint#1650]
### Bug report
- __Package version(s)__: core 1.29.0
- __Browser and OS versions__: Mac OSX High Sierra (10.13 (17A365)), Chrome (Version 61.0.3163.100 (Official Build) (64-bit))

Checkbox, Switch, and Radio Github example links are broken (lead to 404 Not Found).

I suspect this is due to the way in which Blueprint currently generates `sourceUrl`. It seems that `sourceUrl` is generated for all examples in the file `reactExamples.ts` through the following code:

```ts
function addPackageExamples(
    packageName: string,
    packageExamples: { [name: string]: React.ComponentClass<IBaseExampleProps> },
) {
    for (const exampleName of Object.keys(packageExamples)) {
        const example = packageExamples[exampleName];
        **const fileName = exampleName.charAt(0).toLowerCase() + exampleName.slice(1) + ".tsx";**
        reactExamples[exampleName] = {
            render: props => React.createElement(example, { ...props, themeName: getTheme() }),
            sourceUrl: [SRC_HREF_BASE, packageName, "examples", fileName].join("/"),
        };
    }
}
```

The problem is that both the Checkbox, Switch, and Radio examples are exported from a larger file called `controlExamples.tsx`, and do not each have their own files. This means the above code is generating `sourceUrl`s for files that do not exist.

Some ideas for a fix are by separating Radio/Switch/Checkbox into their own files, or by changing `reactExample.tsx` to account for this inconsistency (is there some way to access `import` filepaths?).

Tiny bug, but would love an opportunity to start contributing to this fantastic project in whatever ways possible!

#### Steps to reproduce

1. Navigate to BlueprintJS (either locally or directly to the [official BlueprintJS docs](http://blueprintjs.com/docs/#core/components/forms/radio))
2. Navigate to either the Form Controls > Radio Button page, OR the Form Controls > Checkbox page
2. Click on "View on Github"

#### Actual behavior
Github returns a 404 page not found error.

#### Expected behavior

Should return a Github page containing the example source code.

**Comment by giladgray** [comment]
@zfranklyn thanks for reporting! great to hear from you 😄 

splitting the one `controlsExamples.tsx` into separate files is likely the easiest/most reliable fix here. 

feel free to submit a PR when you have the chance! (or pick up another issue, whatever suits your fancy 👗)
