### ISSUE TITLE
Proposing Blueprint Lite

### ISSUE THREAD

**Issue by vilav** [palantir/blueprint#1657]
Hello,

The Blueprint UI is very polished but maybe the React / Typescript features put it beyond use for some legacy development HTML/CSS/JS pipeline.

Would love a 'lite' UI framework (simlar to Bootstrap or [MDL](https://getmdl.io/)) that essentially is simpler code for components for use with traditional skills and pipelines, if possible.

Thanks!

**Comment by dmackerman** [comment]
>  legacy development HTML/CSS/JS pipeline.

Curious what you mean when you say this? If you're entire app is not written with React, you can still use the Blueprint components as ad-hoc pieces. It still requires React to do the rendering, but you can build re-usable pieces of functionality and then drop them into an existing JS codebase (jQuery, Backbone, whatever) pretty easily. We did this before we migrated our entire app over to using React. 

http://blueprintjs.com/docs/#blueprint.vanilla-js-apis

**Comment by adidahiya** [comment]
Also you can simply use the CSS files _without_ JS too, you just have to build your own HTML markup.

**Comment by giladgray** [comment]
The CSS APIs and Vanilla JS usage (both noted above) have always been our two-pronged approach to Blueprint Lite:

1. You can simply use our CSS classes on your own HTML elements, with or without a JS framework.
2. You can use the React components directly using `ReactDOM.render`, with or without a different JS framework.

Closing this issue as it seems we've done our part and doing any more work here is against the goals of the project.
