### ISSUE TITLE
[Button] hover styling not working properly with multiple buttons wrapped inside a label component

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1658]
### Bug report

- __Package version(s)__: 1.30.0

#### Actual behavior

Wrapping a set of buttons inside a `<label/>` component, the hover action highlights the first button and the one in which the mouse is over:

```ts
            <label>
                {["Button 1", "Button 2", "Button 3"].map((button, index) =>
                    <Button key={index} className="pt-minimal">
                        {button}
                    </Button>)}
            </label>
```

![bug](https://user-images.githubusercontent.com/23741599/31177861-8ea8b6fe-a917-11e7-8258-96e210dec726.png)

#### Expected behavior

Doing the same thing inside a `<div/>` component it works fine:

```ts
            <div>
                {["Button 1", "Button 2", "Button 3"].map((button, index) =>
                    <Button key={index} className="pt-minimal">
                        {button}
                    </Button>)}
            </div>
```

**Comment by adidahiya** [comment]
This isn't really an intended use case for `<label>`. Why do you need to put multiple buttons in there?

**Comment by giladgray** [comment]
@franciscofabian not only is this not an intended use case for `<label>`, but the behavior exhibited is actually the _expected behavior_ when putting an interactive element (like `input` or `button`) inside a `<label>`: nesting a control in a label causes the label to act as a caption for that input and **function as an extended click target. interactions with the `<label>` transfer to the first control inside it.**

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Usage_notes

And check out this fiddle (modified from one on the MDN link above) that demonstrates this behavior with standard HTML `<label>` and `<button>`: https://jsfiddle.net/9d8txfbo/3/
