### ISSUE TITLE
run test suite against both React 15 & 16

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#1659]
Enzyme 2.x does not support React 16 and [migrating to Enzyme 3.x](http://airbnb.io/enzyme/docs/guides/migration-from-2-to-3.html) is not trivial. Fortunately, Enzyme 3 makes testing against multiple versions of React quite possible!

For 2.0, we should run the test suite against both React 15 and 16, in parallel CircleCI containers.

This issue is casually blocked on the non-existence of `@types/enzyme` for 3.x.

Related: https://github.com/palantir/blueprint/issues/866#issuecomment-334017087

**Comment by adidahiya** [comment]
we decided not to do this since we're enforcing a minimum dep on React 16
