### ISSUE TITLE
[Core/Labs] Not possible to set className for rootElement of Popover/Tooltip/2

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/blueprint#1661]
It should be possible to set the className for the root element of a popover2, ie this element: https://github.com/palantir/blueprint/blob/d90adf5c9f03ef8ca1fb37824fb2d5d38e7bf14d/packages/labs/src/components/popover/popover2.tsx#L304

**Comment by giladgray** [comment]
let's try to clean up all the className props that `Popover` supports: I suspect they're not all equally useful, and here's a great use case that simply isn't covered. 

Currently supported props:

- `className`
- `backdropClassName` / `backdropProps.className`
- `popoverClassName`
- `portalClassName`

**Comment by giladgray** [comment]
this is fixed in 2.0 👍
