### ISSUE TITLE
Cannot select multiple disjoint sections on IE  

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1669]
Windows (IE or Chrome)

Cannot ctrl+click to select multiple disjoint selections

**Comment by tgreenwatts** [comment]
Sounds like this is caused by specifically relying on the cmd key, so we should replace cmd with meta across the board, so we always work on Windows

**Comment by cmslewis** [comment]
The bug is here: https://github.com/palantir/blueprint/blob/master/packages/table/src/interactions/selectable.tsx#L223

But on Windows, I'm running into a problem where the `metaKey` flag isn't `true` when I `metaKey + click`. Maybe it's just a VM issue. Will look into it next week.

**Comment by llorca** [comment]
I don't think it's `metaKay`, Bill was talking about `mod`

**Comment by adidahiya** [comment]
Closing because we are no longer supporting IE11 in Blueprint v5.0.
