### ISSUE TITLE
[Docs] Difficult to select text above heading

### ISSUE THREAD

**Issue by anisylen** [palantir/blueprint#167]
#### Actual behavior:

In the docs, you cannot select text just above the heading or click links because the element is oversized and has had massive padding applied which is layering above the text just above it.

In the below screenshot
![screen shot 2016-11-15 at 3 09 47 pm](https://cloud.githubusercontent.com/assets/13653918/20300541/b3c4ee42-ab45-11e6-8184-b461d3de17af.png)

We see that the padding for the heading overlaps the text making it difficult to select.

#### Expected behavior:

The headers should only be taking as much space as they are supposed to and all text and links across the documentation should be selectable and clickable respectively

**Comment by webpty** [comment]
This behavior can be found on other elements of the site.
I found this one while trying to get to the Github link on the [Toaster page](http://blueprintjs.com/docs/#components.toaster.js):

![screen shot 2016-11-15 at 17 17 09](https://cloud.githubusercontent.com/assets/11739306/20326617/931427e6-ab57-11e6-92fb-9b2071a24c5f.png)

**Comment by giladgray** [comment]
oh it's everywhere! it's also fixed in PR #173. had a nasty problem with that `position: fixed` navbar hiding the top 50px of the page.

**Comment by aniforprez** [comment]
Yeah this is fixed across docs now. Thanks!
