### ISSUE TITLE
Row headers initial misaligned

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1676]
### Bug report

- __Package version(s)__: table 1.26.0
- __Browser and OS versions__: Chrome 61.0.3163.100 / Mac 10.12.16

#### Steps to reproduce

1. render a table

#### Actual behavior

Row headers are misaligned. 
![screen shot 2017-10-06 at 6 07 17 pm](https://user-images.githubusercontent.com/3681045/31273477-75a0a1e8-aac1-11e7-85ae-4808accdbfbc.png)

Scrolling the first few rows out of the virtual render range will cause to re-render in the proper position.

#### Expected behavior

Row headers should be aligned on first render.

**Comment by cmslewis** [comment]
Fixed in #1663.
