### ISSUE TITLE
Keybindings for Table Component

### ISSUE THREAD

**Issue by aeid** [palantir/blueprint#1686]
This is a feature request for keybindings in the table component which are common in most spreadsheet applications. For example: 
arrow keys to move active cell 
cmd+c to copy active or range content 
cmd+p to paste content in active cell
"=" to type in formula in active cell
etc...

**Comment by cmslewis** [comment]
RE: arrow keys: this is already implemented. Make sure you have `enableFocus=true.`
<img src="https://user-images.githubusercontent.com/443450/31347943-e7961ab8-acd2-11e7-82c1-6cf2d824f40e.gif" width="200" />

RE: <kbd>Cmd + C</kbd> should already be possible. See the `getCellClipboardData` prop here: http://blueprintjs.com/docs/#table-js.table.

RE: <kbd>Cmd + P</kbd>: I'm assuming you mean <kbd>cmd+v</kbd>. This gets into spreadsheet-y features, which we're starting to consider more actively.

RE: type-char-to-enter-edit mode: We've had this on our radar for a bit, but I can't find the issue actually. 

I've added the latter two tasks to our existing issue about keyboard shortcuts: https://github.com/palantir/blueprint/issues/1080. Will close this in the meantime.

**Comment by akoskm** [comment]
> This gets into spreadsheet-y features, which we're starting to consider more actively.

Hi @cmslewis 👋 any updates on this?

**Comment by adidahiya** [comment]
@akoskm this is an old issue; I've opened a new one to track the pasting feature request here https://github.com/palantir/blueprint/issues/5123

**Comment by akoskm** [comment]
Thanks @adidahiya 🙌
