### ISSUE TITLE
[Table]mouse wheel scroll is always captured by table.

### ISSUE THREAD

**Issue by sesm** [palantir/blueprint#1690]
### Bug report

- __Package version(s)__: blueprint/table 1.27
- __Browser and OS versions__: any

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/#table-js
1. Scroll to first table ('Dollars')
1. Hover mouse over the table
1. Try to scroll the page with mouse wheel

#### Actual behavior

Page is not scrolling

#### Expected behavior

Page should be scrolling, because that table has no scrollbar of its own.

**Comment by sesm** [comment]
This could be fixed with https://github.com/palantir/blueprint/pull/1674
I'll test `master` and write back

**Comment by sesm** [comment]
Yes, this is fixed on `master`. Closing.

**Comment by cmslewis** [comment]
Yep, just addressed this.
