### ISSUE TITLE
[Button] Wrong onHover style on active, disabled and minimal button

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1701]
### Bug report

- __Package version(s)__: 1.31.0

#### Steps to reproduce
Button and AnchorButton with "pt-minimal" style and active and disabled props `<Button className="pt-minimal" text="Button" disabled active/>` don't have the style that I would expect when on hover. This is how the button looks without having the pointer over it:
![bug_1](https://user-images.githubusercontent.com/23741599/31409452-3fb6bfba-ae0c-11e7-9e42-9aad8c1248cf.png)
And this is how it looks when the mouse is over it:
![bug_2](https://user-images.githubusercontent.com/23741599/31409471-4ffc621c-ae0c-11e7-8b87-5c5998b6db66.png)
With that style the button doesn't look active, it has the same style as a minimal and disabled button but not active.

**Comment by giladgray** [comment]
seems legit. should be straightforward to fix the CSS, I hope?

**Comment by 14rcole** [comment]
I can take a look at this if nobody is working on it yet.  Would you expect the button to become darker on hover, or simply to not become as light?

**Comment by franciscofabian** [comment]
@14rcole I have started to work on it, so feel free to do it. I would expect it to behave in the same as a non-minimal button, so that the darkness doesn't change
Another thing that I have found is that if adding also a intent prop to it, it also looks not active even without the pointer over it. It shouldn't be like that, it looks like there are a few small issues with the styling of minimal buttons.

**Comment by llorca** [comment]
So... minimal, active and disabled button looks like this, as shown by Francisco earlier:
![](https://user-images.githubusercontent.com/23741599/31409452-3fb6bfba-ae0c-11e7-9e42-9aad8c1248cf.png)

It should simply not change on hover as the interactions are supposed to be disabled
