### ISSUE TITLE
[Table] Rich text in EditableCell

### ISSUE THREAD

**Issue by pawsong** [palantir/blueprint#1702]
As EditableCell and EditableText receive `value` as string, it does not seem to be possible to render rich text in EditableCell when it is not in edit mode. Is there any recommended workaround? 

If not, I would try to build (and share) a custom EditableCell which supports rich text and controllable edit mode initial value. If there is a similar progress in the blueprint team, please let me know so I can avoid to reinvent a wheel :)

**Comment by giladgray** [comment]
@pawsong our own `EditableText` is explicitly _not_ a rich text formatter so yes a custom `EditableCell` is the correct approach here. Would love to see there result!

**Comment by giladgray** [comment]
not supported
