### ISSUE TITLE
Create-able MultiSelect

### ISSUE THREAD

**Issue by dixitk13** [palantir/blueprint#1710]
### MultiSelect with Create-able options.

Currently MultiSelect can select from a given list. 

Would like an option where given a prop(say allowCreate), it allows to create a new Tag from a user which doesn't exist in the predefined list.

**Comment by llorca** [comment]
Haven't tried it myself -- maybe use the `noResults` prop to render a menu item that adds the query to your items

**Comment by dmackerman** [comment]
We've done this ourselves, it's pretty straightforward. Like @llorca said, just use the `noResults` prop to render a `MenuItem` that does what you need.

**Comment by shuyangli** [comment]
@giladgray Can we reopen? The above workaround doesn't clear the input text in the `MultiSelect`, which makes a subpar experience as the user needs to delete the text themselves to select something else

**Comment by giladgray** [comment]
@shuyangli you can easily control the `query` to clear it as needed.

**Comment by shuyangli** [comment]
It'd be great if this could be done in an unmanaged way (similar to ReactSelect)

**Comment by dixitk13** [comment]
+1 on this @giladgray @shuyangli . I have a random [react-select](https://github.com/JedWatson/react-select) in my application which is styled with targetted styles to achieve the same. Would be great if blueprintJS did this in an un-managed way.
