### ISSUE TITLE
[Labs/Popover2] Update popper when the content changes size

### ISSUE THREAD

**Issue by tyscorp** [palantir/blueprint#1719]
Right now this isn't possible to do in userland because we don't have access to [Popper#scheduleUpdate](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#Popper.scheduleUpdate).

This can be done in react-popper like [this](https://github.com/souporserious/react-popper/issues/60).

If this functionality isn't implemented in blueprint directly because of added complexity and/or dependencies then allowing access to `scheduleUpdate` would be enough.

I think giving access to `scheduleUpdate` would require allowing `content` to be either a component or function and passing `scheduleUpdate` as props/arguments...

**Comment by llorca** [comment]
closing in favor of https://github.com/palantir/blueprint/issues/692
