### ISSUE TITLE
Time picker always uses local time zone

### ISSUE THREAD

**Issue by jtheisen** [palantir/blueprint#1721]
I want to use the time picker to select a duration - which has nothing to do with time zones.

Nevertheless, when I initialize the time picker with a time of `new Date(someSmallTimeValue)` it will add some whole hours to the value in the display in accordance with my local time zone.

I also can't just hide the hours field - only the lesser significant time parts can be hidden.

I think there should be either full time zone support (which is probably somewhat difficult) or simply a way to disable time zone awareness completely (which should be easy).

**Comment by giladgray** [comment]
I've encountered this issue myself: the `TimePicker` is designed explicitly for times, not for durations 😞. Because it only speaks `Date` objects, there's not even a good way to allow it to support non-time durations (like 28 hours or 200 minutes). 

@jtheisen Not sure that timezone support is relevant to your actual feature request of durations?

**Comment by jtheisen** [comment]
@giladgray No, it's not relevant to my use case of durations.

**Comment by giladgray** [comment]
declining this feature. TimePicker is for times, not duration.

**Comment by jtheisen** [comment]
I don't see the difference. In .NET, the type `TimeSpan` is used for durations and the time part of a `DateTime`. That works because it's the same thing.

The problem here is really that you can't bind this component in a way that is agnostic to the timezone the browser is set to, which is surprising and annoying.

Why can't we at least have an option to choose to bind as UTC?

Here's a codesandbox to show the current behavior again: https://codesandbox.io/s/9jw2m01rww
