### ISSUE TITLE
Sketch file not able to import into design tool due to obsolete sketch format

### ISSUE THREAD

**Issue by JPaveg** [palantir/blueprint#1724]
### Bug report

This isn't necessarily a bug report - 

There is a free design tool called Gravit Designer (https://designer.io) which is useful for people that don't have access to a Mac / Sketch.

Unfortunately, this tool can only import sketch files from Sketch v43 or above - if someone is able to download and re-export your sketch file in the newer format, I would be able to import the sketch package into this free tool to use. It would be a great help.

**Comment by llorca** [comment]
Our file has an issue with newer versions of Sketch -- a bunch of vectors broke. I've reached out to the Sketch team, still waiting for their answer. Once they fix it we'll update the Sketch file.

**Comment by mk26** [comment]
The Core Kit Sketch file doesn't seem to work when I import it as a Library in recent versions of Sketch - guessing it's related to this - any thoughts on how to fix it? Or is an updated version of the Sketch file going to be out?

**Comment by llorca** [comment]
@mk26 I have not used Libraries, so I wouldn't be able to help. Maybe it happens because the Core Kit doesn't have any symbol?
