### ISSUE TITLE
^1.16.0 causes pdf.js module to throw an error.

### ISSUE THREAD

**Issue by nschwan94** [palantir/blueprint#1732]
### Bug report

- __Package version(s)__: ^1.16.0
- __Browser and OS versions__: Chrome, Electron, Mac.

#### Steps to reproduce

install `react-pdf@2.0.0`, setup `Document` and `Page` components to display a pdf file loaded by Webpack with `file-loader`, import a `@blueprintjs/core` component into the parent.

#### Actual behavior

`pdf.js` module throws error with `@blueprintjs/core@1.16.0` and above:
```
Uncaught TypeError: Cannot read property 'PDFJS' of undefined
    at Object.defineProperty.value (pdf.js:13270)
    at __w_pdfjs_require__ (pdf.js:45)
    at Object._typeof (pdf.js:7416)
    at __w_pdfjs_require__ (pdf.js:45)
    at Object.defineProperty.value (pdf.js:88)
    at pdf.js:91
    at webpackUniversalModuleDefinition (pdf.js:18)
    at Object../app/node_modules/pdfjs-dist/build/pdf.js (pdf.js:25)
    at __webpack_require__ (bootstrap 53283a0…:686)
    at fn (bootstrap 53283a0…:105)
```

#### Expected behavior

When `@blueprintjs/core` is not imported into the component tree, the above error doesn't surface and the `react-pdf` module works as expected.

I've forked a boilerplate repo (https://github.com/nschwan94/electron-react-boilerplate/tree/master/app), and provided a reproduction on the branch `blueprintjs_reactpdf_issue`. I'm submitting this issue to `pdf.js` repo as well since it's unclear to me why this is breaking.

**Comment by nschwan94** [comment]
wojtekmaj/react-pdf#90

**Comment by giladgray** [comment]
@nschwan94 have you tried with the latest version of core? 1.30+. I'll bet it still fails but always helps us when you test against the latest code (we're not going to ship a patch on 1.16).

**Comment by nschwan94** [comment]
I'm sorry I didn't make it clear, yeah I first observed this on 1.31 (and subsequently tested on 1.32 to no avail). I guess it doesn't help to know what the earliest version that breaks it is. I understand this is confusing. It is to me too. I haven't observed this type of thing before. Not sure if incompatible is the right word, or just doesn't play well together at the moment. I just put it in both `blueprint` and `pdf.js` issues to see if anybody might have a guess or a clue that I could run with considering this is my case of dependency blues.

**Comment by nschwan94** [comment]
I realized today that the error is not reproducible when using npm v5.0.0. it does occur when using yarn v1.1

**Comment by nschwan94** [comment]
sorry guys, this ended up being a messed up webpack config on my part. turns out when all the signs point to a configuration issue... it's not a dependency issue. if I've learned anything it's don't decide to modify your bundler config, change package managers, and update a slew of production dependencies on the same day.

**Comment by giladgray** [comment]
Resolution: webpack config.

**Comment by giladgray** [comment]
@nschwan94 perhaps our own [webpack config](https://github.com/palantir/blueprint/blob/master/packages/webpack-build-scripts/webpack.config.base.js) would be of educational value to you? 
it's actually published on npm  `@blueprintjs/webpack-build-scripts` 😮
