### ISSUE TITLE
Type improvement: renderContextMenu in IContextMenuTarget should allow null or undefined

### ISSUE THREAD

**Issue by AlexLandau** [palantir/blueprint#1743]
The ContextMenuTarget code already handles cases where renderContextMenu() returns null or undefined, using the default context menu in that case. However, using TypeScript with strict null checks enabled flags the `| null` here as a type error:

```
@ContextMenuTarget
export class MyComponent extends React.Component<MyComponentProps, MyComponentState> {
  ...
  renderContextMenu(): JSX.Element | null {
    ...
  }
}
```

I believe the type of IContextMenuTarget should be expanded to cover a null case (and the documentation updated). I could probably write a PR for this, if I know your preference for `| null` vs. `| undefined`.

**Comment by adidahiya** [comment]
Good catch. Changing the return type to `JSX.Element | undefined` sounds good to me.
