### ISSUE TITLE
[EditableText] Opening an EditableText on Chrome should scroll to the end of the input

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1761]
When you double click on an editable cell, the cursor is at the end of the contents, but if the contents are long, the end isn't actually visible. The contents should shift so the cursor is visible. 
![double](https://user-images.githubusercontent.com/24398123/32126207-5035ceec-bb24-11e7-9757-8588ee0cb7d8.gif)

**Comment by gscshoyru** [comment]
Note: apparently, this is a chrome-only bug -- and a bug in editable text, not the table. We're using code that _should_ work properly for this (in editable text) but... for some reason, in chrome, it doesn't.

**Comment by cmslewis** [comment]
@gscshoyru Fair to label this as `Status: Blocked`?

**Comment by gscshoyru** [comment]
Not necessarily. I've seen other jsfiddles and such on the internet that work perfectly fine in chrome. It's just ours that doesn't and _only_ in chrome. For instance: https://stackoverflow.com/questions/1962168/scroll-to-the-very-right-of-a-long-text-input works just fine. I don't know why ours doesn't, but it's likely something specific to us -- as well as chrome.

**Comment by cmslewis** [comment]
Gotcha.
