### ISSUE TITLE
User selection doesn't work in Dialogs

### ISSUE THREAD

**Issue by thasner** [palantir/blueprint#1765]
### Bug report

- __Package version(s)__:  1.32.0
- __Browser and OS versions__: Chrome Version 62.0.3202.62 (Official Build) (64-bit), Mac Sierra Version 10.12.6

#### Steps to reproduce

1. Create a dialog with text content
1. Attempt to select (highlight) text with the mouse
1. 

#### Actual behavior

Nothing happens

#### Expected behavior

Text is selected

This is because of:
```
.pt-dialog-container {
    user-select: none;
}
```
I don't think chrome supports selecting sub-elements of `user-select: none`. (though it used to)

HACK: Adding the following fixes the issue:
```
.pt-dialog-container {
    user-select: initial !important;
}
```

**Comment by llorca** [comment]
Fixed in https://github.com/palantir/blueprint/pull/1746
