### ISSUE TITLE
Will all future demos be in typescript only?

### ISSUE THREAD

**Issue by shahzeb1** [palantir/blueprint#1766]
I noticed on the [toast documentation](http://blueprintjs.com/docs/#core/components/toast) that the documentation was in typescript. As someone who is committed to being in a project which is currently not using typescript, figuring out how components work is a little bit of a struggle.

So: will only typescript be shown in all future/current demo's in the documentation?

**Comment by shahzeb1** [comment]
For anyone still looking for Toast specific help, this comment here was helpful: https://github.com/palantir/blueprint/issues/255#issuecomment-263430141

**Comment by giladgray** [comment]
> ignore anything after a colon and _it's just ES6 javascript_.

@shahzeb1 all of our examples are in typescript, as is all the source code. fortunately, typescript is nearly identical to vanilla ES6, with the helpful addition of type signatures. there's a section in the docs intro about [understanding typescript](http://blueprintjs.com/docs/#blueprint.understanding-typescript) for precisely this issue!

**Comment by shahzeb1** [comment]
thank you. closing this issue for now.

ps. love this framework. keep up the awesome work.
