### ISSUE TITLE
[Core/Slider] Pixel => Value logic is a little off when tick size is smaller than handle size

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1769]
### Bug report

- __Package version(s)__: 1.32.0

#### Steps to reproduce

1. Create a **range** slider that's `150px` wide or less.
1. Click on the last pixel (the one that should correspond to the `max` value).

#### Actual behavior

The `max` value is not selected; rather, a value ~1 tick lower is selected.

![2017-11-01 11 12 01](https://user-images.githubusercontent.com/443450/32289916-89b08e12-bef5-11e7-922f-c12de329f4b2.gif)

#### Expected behavior

The `max` value is selected. (Likewise for the `min` value when clicking the first pixel.)

**Comment by giladgray** [comment]
closing as stale. percentage should be better.
