### ISSUE TITLE
Popover2 weird flipping behavior?

### ISSUE THREAD

**Issue by FezVrasta** [palantir/blueprint#1771]
### Bug report

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Steps to reproduce

1. Open http://blueprintjs.com/docs/#labs/popover2
1. Scroll the page (not the demo area)

#### Actual behavior

![bug](https://user-images.githubusercontent.com/5382443/32330488-8d714834-bfe0-11e7-99f9-f8e01e40fd8d.gif)

#### Expected behavior

No flipping at all.

----

This may be a Popper.js bug, but I see that it happens even if I only disable the "flip" and "prevent overflow" modifiers, which, with vanilla Popper.js, should make the popper not flip at all for any reason.

**Comment by cmslewis** [comment]
@giladgray can you chime in here? You know popper best.

**Comment by giladgray** [comment]
@FezVrasta certainly knows Popper best (he wrote it 😄).

But yeah I've noticed this behavior since the first day I integrated Popper.js and I have no further insight into what causes it. @FezVrasta, if you've got any pointers, I'm happy to investigate further.

**Comment by FezVrasta** [comment]
May you make sure the controls to disable the modifiers are working properly please? If they do, I'd say there are little chances for the behavior to be related to a Popper.js bug
