### ISSUE TITLE
Choose another default shortcut for opening the omnibox

### ISSUE THREAD

**Issue by leeavital** [palantir/blueprint#1772]
when using the Omnibox in Firefox, the shortcut `cmd-k` is overridden by firefox's default behavior, which is to focus on the the search bar.

This makes the omnibox effectively inaccessible for firefox users unless launched through a button

**Comment by giladgray** [comment]
`<Omnibox hotkey="cmd+f">` ?

**Comment by leeavital** [comment]
My vote would be for `cmd-shift-k`

**Comment by giladgray** [comment]
sorry, I was trying to suggest adding a `hotkey` prop to allow the user to customize the hotkey, not changing the default to `cmd+f` (that's clearly worse).

**Comment by leeavital** [comment]
That sounds like a useful flag, although I also think there should be a more reasonable default hotkey. Otherwise different blueprint users who want to support firefox will inevitably end up using  a different hotkey to launch the omnibox.

**Comment by cmslewis** [comment]
`Tab + ....` is a useful scheme that doesn't conflict with much—if anything—across systems. FWIW that's the scheme that Asana uses: https://asana.com/guide/help/faq/shortcuts

**Comment by giladgray** [comment]
perhaps we should have _no_ default and provide the `hotkey` prop as an opt-in approach?

**Comment by thasner** [comment]
I don't think the Omnibox has a default key combination. afaik it's only available as a controlled component.

Either way, is `cmd-k` is a reasonable sample for the docs?

For my App, I'm going to keep `cmd-k`, and allow `shift-k` as a duplicate mapping.

**Comment by llorca** [comment]
`cmd+k` is just a shortcut for the example, it's not built into the component and there's no default key. If you need a hotkey, add it with `renderHotkeys()`/`Hotkey` ([docs](http://blueprintjs.com/docs/#core/components/hotkeys)) and choose the right combo for you.
