### ISSUE TITLE
Nested MenuItems disappear before you can click them

### ISSUE THREAD

**Issue by yaronlavi** [palantir/blueprint#1773]
### Bug report

- __Package version(s)__: v1.32.0
- __Browser and OS versions__: Chrome on Win 10

#### Steps to reproduce

1. Create a menuItem with one or more sub menus.
1. when the sub menu is shown, try to click one of the items. you'll notice in many case the sub menu is hidden before you can click it.
1. you can even see this in the menu documentation at http://blueprintjs.com/docs/#core/components/menu.sample-usage; open the 'Style' or 'Miscellaneous' sub items and see that unless you move your mouse there REALLY REALLY quick, the sub items disappears.

#### Actual behavior

sub menu items disappear before you can select.

#### Expected behavior

sub menu items should stay visible when the mouse is moving over the menu surface.

**Comment by giladgray** [comment]
@yaronlavi oh snap something is quite broken here! definitely used to let you select submenu items...

**Comment by yaronlavi** [comment]
And also the menu item width is strange; instead of being as large as the longest item text, it is clipped after two-three words showing ...

Thanks,
Yaron

On 2 Nov 2017, at 19:04, Gilad Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


@yaronlavi<https://github.com/yaronlavi> oh snap something is quite broken here! definitely used to let you select submenu items...

**Comment by giladgray** [comment]
oh boy fun stuff... issue _does not_ repro in Safari or Firefox: submenus work precisely as expected.

seems like a new chrome bug!

**Comment by gscshoyru** [comment]
@giladgray -- just tested this in FF and Safari -- the bug is there as well -- why do you think it's a chrome-only bug?

**Comment by mfedderly** [comment]
This also seems to happen in JXBrowser 3.14 and 3.15. It also seems to happen in FF latest (56.0.2). Interestingly this seems to have worked in blueprint 1.24.0, but not in 1.32.0.

**Comment by mfedderly** [comment]
Looks like this was the offending commit, @llorca
https://github.com/palantir/blueprint/pull/1672

**Comment by giladgray** [comment]
@gscshoyru it definitely did not repro in FF or Safari when I tested this 6 days ago...

**Comment by ekros** [comment]
Reproduced in Chrome 61, FF 56 and Edge 25.1. It's quite annoying, unless you are Flash :)
