### ISSUE TITLE
[DateTime/DateRangeInput]: End date not displaying correctly in DateRangePicker when dates more than two months apart

### ISSUE THREAD

**Issue by jovangrbic** [palantir/blueprint#1774]
### Bug report

- __Package version(s)__:  1.23.0
- __Browser and OS versions__: Chrome latest,  Win7, but any would do

#### Steps to reproduce

1. open DateRangeInput doc page on http://blueprintjs.com/docs/#datetime/daterangeinput
2. disable "Constrain calendar to contiguous months" option
3. enter dates similar to following: "05/25/2017" -> "07/15/2017" (MM/DD/YYYY format used). You could also use the popover to choose the dates.
4. open the DateRangePicker again, and observe that the right side is displaying the month following the left side instead of marking the end date; if you navigate to the correct month, you will see that the selection is correct.

#### Actual behavior
Right side view is displaying the month after the month displayed on left side, even though contiguous months are disabled and end date is set.

#### Expected behavior

Right side displaying the selected end date.

**Comment by cmslewis** [comment]
Sounds reasonable. 👍
