### ISSUE TITLE
pt-skeletons do not work correctly in Firefox

### ISSUE THREAD

**Issue by kendraknittel** [palantir/blueprint#1777]
### Bug report

- __Package version(s)__: 1.28.0
- __Browser and OS versions__: Firefox 55.0.3, Mac OS Sierra 10.12.6

#### Steps to reproduce

View an element that has the class `pt-skeleton` in Firefox.

#### Actual behavior

Skeleton animation does not work - just shows gray background with no pulsating. Does not look like the element is loading.

#### Expected behavior

Skeleton animation should work the way that it does in other browsers, with animation visible.

**Comment by isTravis** [comment]
Any update on this? It is still an issue on the new Firefox: 57.0.1
