### ISSUE TITLE
Minimal Button group adds extra separator on the end

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#1780]
<img width="430" alt="screen shot 2017-11-02 at 4 43 25 pm" src="https://user-images.githubusercontent.com/10415101/32355636-0f481f3e-bfed-11e7-88e5-17110fc3f2bc.png">

I don't think this is the intended behavior. The separators should be in between the buttons but not before the first button or after the last.

Thanks!

**Comment by giladgray** [comment]
@tgreen7 that should only happen if there's an extra element inside the `.pt-button-group` after the Export button. can you please check the HTML on your end?

notice that this does not repro in the docs http://blueprintjs.com/docs/#core/components/button-group.

**Comment by tgreen7** [comment]
Yes you are correct. There was a dialog hidden next to the button. Thanks!
