### ISSUE TITLE
Problem with blueprint.css.map request

### ISSUE THREAD

**Issue by stephensong** [palantir/blueprint#1781]
### Bug report

- __Package version(s)__: blueprintjs core 1.32.0
- __Browser and OS versions__:  Chrome browser on Windows 10

#### Steps to reproduce

Using webpack,  include a css file containing this line:

    @import "~@ blueprintjs/core/dist/blueprint.css";   

(the previous line fails to display correctly if I don't include the space after the @ sign .... )

#### Actual behavior

Unwanted requests appear at the server for '/blueprint.css.map'.  Even more annoyingly, no FetchEvent is generated in my service-worker for this file, so my server is obligated to continually serve it.

After much head-scratching, I eventually discovered it was due to the following line at the end of the
blueprint.css file:

  /*# sourceMappingURL=blueprint.css.map */

Removing this line fixed my problem, but it is not acceptable to have to manually edit files installed under node_modules.  The problem is destined to reappear on future installs, it's not going to appear in git history etc. etc.

#### Expected behavior

The rogue requests should not appear at the server.   

It seems to me that the line in question is either incorrect or redundant.

many thanks.

**Comment by shahzeb1** [comment]
Btw:

Place your code within \`...code...\`.

So the code will display as `@import "~@blueprintjs/core/dist/blueprint.css";` and it won't give you a hard time.

**Comment by giladgray** [comment]
@stephensong this can be accomplished with a build task that removes sourcemap information when importing CSS files. the actual solution will be specific to your build system.
