### ISSUE TITLE
Visually distinguish trailing whitespace

### ISSUE THREAD

**Issue by NeilRickards** [palantir/blueprint#1784]
We have had a lot of problems where data contained trailing whitespace or was only whitespace.  This was impossible to determine from the visual table.

The ideal would be a configuration where the background colour for trailing whitespace in a table cell could be set.

**Comment by cmslewis** [comment]
This is already possible. You can style and mark up your data however you want via `Column`'s [`renderCell`](http://blueprintjs.com/docs/#table-js.column) prop; just put a `<span class="whatever">` around your trailing white space and slap a `background-color` on it.
