### ISSUE TITLE
[DateRangeInput] Allow Position to be passed as prop

### ISSUE THREAD

**Issue by sprazzeus** [palantir/blueprint#1791]
Would you guys consider allowing `position` to be passed as a prop to `DateRangeInput`?

In one use case: due to its location on our page and the picker's built-in  `Position.BOTTOM_LEFT`, the picker gets obstructed by our chat widget and also extends the page horizontally, requiring slight scrolling to see the full component.

It'd be great to have the usual control for this 👍

**Comment by llorca** [comment]
@sprazzeus already possible! Since `DateRangeInput` composes `Popover`, you can pass `position` in `popoverProps` 👍
