### ISSUE TITLE
[DateTime] Fields don't "commit" the inputed date on 'Enter'

### ISSUE THREAD

**Issue by erinmarchand** [palantir/blueprint#1798]
This is a feature request to support the use of "enter" when selecting dates from the Blueprint Date Picker.

**Comment by cmslewis** [comment]
@erinmarchand Doesn't this already work with `DatePicker` _and_ `DateInput`? See these GIFs:

![2017-11-10 12 09 20](https://user-images.githubusercontent.com/443450/32676590-0ba66ed4-c610-11e7-854a-fff21fe873ae.gif)

![2017-11-10 12 10 14](https://user-images.githubusercontent.com/443450/32676614-25b83cb2-c610-11e7-9463-383e47b00ed1.gif)

**Comment by LindsayWard** [comment]
@cmslewis -- Hey Chris, 

So if you type into the input, as you have typed a valid date you are it is correctly choosing it in the pop up but if you hit enter it does not move you to the next field or dismiss the flyout.  You are correct if you tab thorough and the highlight is actually on the date in the picker (as I show for the end date) it DOES select and it exit appropriately.  

![datepicker](https://user-images.githubusercontent.com/12377437/32793501-ef52751c-c91a-11e7-8b49-1b89f06a1290.gif)

**Comment by cmslewis** [comment]
That's a `DateRangeInput`, a whole different story! @erinmarchand - precision with the component name is appreciated in these issues. Happy to take a look.

**Comment by dalessi** [comment]
@cmslewis Thoughts on when you might be able to get this in? Want to be able to communicate back to Sigfred (who requested the feature).

**Comment by adidahiya** [comment]
Unsure when we'll get to this; the best way would be to submit a PR to fix. Shouldn't be too complex.

**Comment by erinmarchand** [comment]
@cmslewis  thanks for getting this fixed! Will there be a release soon we can pull from?
