### ISSUE TITLE
[Table] Table only renders the first 201 rows

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1807]
### Bug report

Table only renders the first 201 rows, the remaining rows are not rendered but an empty space for them is created.

**Comment by llorca** [comment]
@franciscofabian please provide details about your setup, show what your code looks like and maybe share a screenshot if possible. Thank you!

**Comment by cmslewis** [comment]
@franciscofabian `Table` renders only the cells in view (virtualized rendering), so it needs to manage its own scrolling and impose a limit on the number of rows it's willing to render at one time. Make sure you're not overriding the table's CSS positioning rules.

**Comment by franciscofabian** [comment]
It happens for me with any table, for example expanding this simple one



`import React, { Component } from "react";`
`import "normalize.css/normalize.css";`
`import "@blueprintjs/core/dist/blueprint.css";`
`import "@blueprintjs/table/dist/table.css";`
`import { Cell, Column, Table } from "@blueprintjs/table";`
`export class TableExample extends Component {`
`    render() {`
`        return (`
`            <Table numRows={220}>`
`                <Column name="Test" renderCell={rowIndex => <Cell>{rowIndex}</Cell>} />`
`            </Table>`
`)}}`
`export default TableExample;`

See the screenshot.
![testtable](https://user-images.githubusercontent.com/23741599/32775739-96512d4e-c930-11e7-98b9-81619e8996c1.png)

**Comment by cmslewis** [comment]
Show me your CSS? Your `Table` looks fine, but it needs to be in a fixed-height container if it contains more than a screen's worth of rows (~50). That will trigger scrolling.

As is, I suspect you're rendering the whole table inline without a height bound, so it's hitting the default `200`-row cutoff.

**Comment by franciscofabian** [comment]
Yes, it works if it's bounded in a fixed height element. But it doesn't work if I have it for example in a element with `maxHeight` instead of `height`.

This works fine:
```
<div style={{height: "500px"}}>
    <Table .../>
</div>
```
but this doesn't:
```
<div style={{maxHeight: "500px"}}>
    <Table .../>
</div>
```

I would expect it to work in both cases.

**Comment by giladgray** [comment]
set explicit height in CSS.
