### ISSUE TITLE
[Table] Slow rendering updating cells in large tables

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1808]
### Bug report

Rendering a table in which (most of) the cells are editable makes the rendering significaly slower. I think that having many edit le cells shouldn’t have any noticeable impact on performance.

**Comment by llorca** [comment]
We're working on editable cells at the moment. Can you provide more details about your setup and code? We'd also appreciate a screencast of the rendering perf you're seeing

**Comment by franciscofabian** [comment]
I have looked more into this issue, it happens with both cells and editable cells for big tables when updating after a status change, e.g.
`import React, { Component } from "react";`
`import "normalize.css/normalize.css";`
`import "@blueprintjs/core/dist/blueprint.css";`
`import "@blueprintjs/table/dist/table.css";`
`import { Button } from "@blueprintjs/core";`
`import { Cell, Column, Table } from "@blueprintjs/table";`
`export class CellsExample extends Component {`
`constructor(props) {`
`super(props);`
`this.state = {loading: false}`
`}`
`render() {`
`const numColumns = new Array(20).fill(0);`
`return (`
`<div>`
`<Button onClick={() => this.setState({loading: !this.state.loading})}>Reload</Button>`
`<Table numRows={200}>`
`{numColumns.map((i, index) => <Column key={index} name="Test" renderCell={rowIndex => <Cell loading={this.state.loading}>{rowIndex}</Cell>} />)}`
`</Table>`
`</div>`
`)}}`
`export default CellsExample;`

Re-rendering after any state change, not only `loading`, is very slow for a large tables, see here
![change_state](https://user-images.githubusercontent.com/23741599/32781108-0fc0863a-c944-11e7-80d9-ca251524c9d0.gif)

**Comment by giladgray** [comment]
@franciscofabian use triple-backticks "```" for code blocks please. https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by sceptre12** [comment]
Is this an issue that still exists?

**Comment by adidahiya** [comment]
This is an old issue, I'm going to close it in favor of more recent ones related to table rendering listed here: https://github.com/palantir/blueprint/milestone/41
