### ISSUE TITLE
https needed on the documentation website

### ISSUE THREAD

**Issue by raisedadead** [palantir/blueprint#1809]
Hi, 

First of all I would like to thank for this awesome library. And I have a small feature request to enable https on the documentation website.

I am unable to access this site due to the network policy at my organisation.

Since this is being served of GitHub pages, it would be fair to activate `https` on the same.

Here is a fairly good 'work around' for custom domains as in your case.
https://blog.raisedadead.com/moving-on-and-setting-the-records-straight-1a2128964ed3
Jump directly to Step 3 of the article.

**Comment by giladgray** [comment]
@raisedadead that is unfortunate! it's non-trivial to set up SSL for our custom domain and we don't have the time to invest in it. an easy workaround would be to run the documentation site locally. you could just checkout the repo and `open docs/index.html`.

**Comment by raisedadead** [comment]
Sure,

Thanks for getting back.
It took me literally a couple minutes to have a better workaround by just forking

https://git.raisedadead.com/blueprint/

**Comment by jeroenvisser101** [comment]
With https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ and https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html, maybe this issue can be revisited?

**Comment by jeroenvisser101** [comment]
I see the documentation is now served over HTTPS, so I guess this can be closed, thanks!
