### ISSUE TITLE
Context menu target does not support non-HTML components

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#1812]
#### Steps to reproduce

```typescript
@ContextMenuTarget
class A extends React.Component {
    public render() {
        return (
            <B>
                <div>content</div>
            </B>
        );
    }

    public renderContextMenu() {
        …
    }
}

class B extends React.Component {
    public render() {
        return React.Children.only(this.props.children);
    }
}
```

#### Actual behavior

Context menu does not open upon right-clicking the `div`.

#### Expected behavior

Context menu opens upon right-clicking the `div`.

#### Cause

The context menu does not open, because the `onContextMenu` props is injected into the direct child of the `ContextMenuTarget`, in this case the `<B>` instance (see [contextMenuTarget:58](https://github.com/palantir/blueprint/blob/11f3acd/packages/core/src/components/context-menu/contextMenuTarget.tsx#L58)). Since `B` doesn't actually take that prop, it's never applied to any DOM element.

#### Workaround

```typescript
interface IProps {
    a: any;
    b: any;
}
class B extends React.Component<IProps> {
    public render() {
        const element = React.Children.only(this.props.children);
        // the array in the removeNonHTMLProps call must be the name of all props this component takes
        return React.cloneElement(element, removeNonHTMLProps(this.props, ["a", "b"]), element.props.children);
    }
}
```

**Comment by adidahiya** [comment]
We could either document this limitation (that you must use an HTML element as the root of the context menu target DOM) or make `ContextMenuTarget` inject a wrapper element (like `Popover`). I lean slightly towards the former since it gives you more control over your DOM and is a non-breaking change.

**Comment by giladgray** [comment]
I too lean towards the former. This is related to #1725 and #931 (decorator issues).

**Comment by adidahiya** [comment]
This is noted in the docs, and there is a relevant console warning when you don't return a valid HTML element in `render()`.
