### ISSUE TITLE
Table API examples missing from GitHub

### ISSUE THREAD

**Issue by jason-henriksen** [palantir/blueprint#1818]
### Bug report

latest in git : 
any

#### Steps to reproduce

1. visit this documentation link: http://blueprintjs.com/docs/#table-js
2. scroll down to the first link that says "View source on GitHub"
3. Click the link

#### Actual behavior

Receive a 404 that the example code is not present.
I also poked around in github directly.  As far as I can see, no example code for table is present

#### Expected behavior

Show the examples so I can figure out how to nicely manage the api.
My actual problem is getting column widths that don't look bad.  But I feel like I'd be able to sort that out myself if I could see some sample code for the component.

**Comment by giladgray** [comment]
ahh all the examples just moved with #1741. they're all in the docs-app package now: https://github.com/palantir/blueprint/tree/master/packages/docs-app/src/examples

**Comment by adidahiya** [comment]
sorry about that, should be fixed by https://github.com/palantir/blueprint/pull/1817/commits/25252211ea49a363376a5fb177eb89fc32bbbf17

**Comment by adidahiya** [comment]
Fixed now
