### ISSUE TITLE
Select (labs) extends beyond bottom of screen

### ISSUE THREAD

**Issue by rheinheimer** [palantir/blueprint#1823]
### Bug report

- __Package version(s)__: 1.30
- __Browser and OS versions__: all

#### Steps to reproduce

1. Create a Select (labs) with many items in it.

#### Actual behavior

Items extend to beyond bottom of screen, rendering them inaccessible.

#### Expected behavior

Either the page should scroll or the menu should be limited to within the screen area. This is achieved in the docs by applying css like:
```
.pt-popover-content .pt-menu {
    max-height: 250px;
    min-width: 300px;
    overflow-y: auto;
}
```
However, this is not ideal, as this would not apply to all of those classes. The bigger problem might be that I can't figure out how to pass custom classes to the Popover2 component created by the Select component. I tried `popoverProps={{className: "myclass"}}`, but that did not work.

**Comment by giladgray** [comment]
@rheinheimer try `popoverProps={{ popoverClassName: "myclass" }}`

**Comment by rheinheimer** [comment]
@giladgray Thanks
