### ISSUE TITLE
[Core] Radio Button Selected state

### ISSUE THREAD

**Issue by kudigaracoder** [palantir/blueprint#1832]
### Bug report

- __Package version(s)__:
1.33.0
- __Browser and OS versions__:
Safari 11.0
MacOS 10.13

#### Steps to reproduce

1) Visit Documentation link http://blueprintjs.com/docs/#core/components/forms/radio
2) Select any of the Radio buttons

#### Actual behavior
<img width="222" alt="screen shot 2017-11-21 at 6 20 11 pm" src="https://user-images.githubusercontent.com/3305383/33073596-5f800e70-cee9-11e7-90c2-b0da20071930.png">

#### Expected behavior
<img width="160" alt="screen shot 2017-11-21 at 6 21 46 pm" src="https://user-images.githubusercontent.com/3305383/33073609-6a6dc430-cee9-11e7-802c-cdd4c433f17d.png">

#### Description
Noticed this only in 1.33.0, unsure if this existed in earlier versions as well

**Comment by llorca** [comment]
is this a macOS High Sierra thing? I can't repro on 10.12 with Safari 11

**Comment by kudigaracoder** [comment]
The expected behaviour screenshot is from Chrome 62/Firefox 57 on High Sierra. They seem to render fine.

**Comment by giladgray** [comment]
closing stale issue that we haven't been able to reproduce.
