### ISSUE TITLE
[Labs] MultiSelect needs a disabled prop

### ISSUE THREAD

**Issue by paulpooch** [palantir/blueprint#1834]
Do you want this PR'd?

**Comment by llorca** [comment]
@paulpooch good call, would appreciate a contribution on this one

**Comment by marvinsum** [comment]
@paulpooch we recently added a `disabled` property to the `TagInput` component, which is a child of the `MultiSelect` component. I haven't looked at the implementation of the `MultiSelect`, but you might just be able to get away with declaring the `disabled` property on `MultiSelect.tagInputProps`.

Check out #1819
