### ISSUE TITLE
[TagInput] Clear all button in the TagInput repositions itself strangely as more tags are added

### ISSUE THREAD

**Issue by celinenguyen** [palantir/blueprint#1837]
![strange scrolling](https://user-images.githubusercontent.com/1417844/33103079-e4445a40-ced4-11e7-8d4f-0183c1721dee.gif)

* **Package version(s):** @blueprintjs/labs 0.13.0

Depending on the length of the tags you add to the TagInput, you can get into a weird state where:

* Even though it looks like there's enough space for the tag + `x` button to stay on the same line, the `x` button moves to a new line
* The `x` button shifts between being positioned on the left of the input or the right (see below for another example)

![strange scrolling 2](https://user-images.githubusercontent.com/1417844/33103146-7a60fa60-ced5-11e7-8c8c-f076726d63c0.gif)

**Comment by llorca** [comment]
I had this fixed a few months ago while working on https://github.com/palantir/blueprint/issues/1425

**Comment by giladgray** [comment]
oh yeah the three-column flex thing would fix this. right now it's a simple artifact of DOM positioning, based on which line the `<input>` element is on.

**Comment by giladgray** [comment]
this is fixed. it's always on the right.
