### ISSUE TITLE
Customising styles

### ISSUE THREAD

**Issue by yoamomonstruos** [palantir/blueprint#184]
Guys, killing it 👍 

Would be awesome to have a bit more explanation/examples around customising the styles. I know you touch on using inline styles, but that would only get applied to the top level element in a component, so would be pretty limiting if you wanted to make any big stylistic changes.

Is the best way to import the stylesheets and overwrite the variables?

**Comment by adidahiya** [comment]
Right now the best way to override styles is probably to use more specific selectors in your own stylesheet. First-class support for importing and tweaking the Sass code is an open FR, you can watch its progress here https://github.com/palantir/blueprint/issues/123

**Comment by yoamomonstruos** [comment]
Ah my bad didn't see that dude. Look forward to seeing that, would 100% use it otherwise 👍
