### ISSUE TITLE
Unable to render Callout component using javascript API

### ISSUE THREAD

**Issue by imawuman** [palantir/blueprint#1842]
### Bug report
- __Package version(s)__: 1.32.0
- __Browser and OS versions__: Chrome Version 62.0.3202.94 on MacOS

#### Steps to reproduce
Unable to render `Callout` component using code:
```
<Callout
    className="custom-classname"
    iconName={IconClasses.INFO_SIGN}
    intent={Intent.PRIMARY}
>
    Callout description
</Callout>  
```

Also tried using `<span>Callout description</span>` instead and still no luck.

#### Actual behavior
Unable to render and getting a bunch of console errors:
![screen shot 2017-11-22 at 5 15 51 pm](https://user-images.githubusercontent.com/3641039/33155976-1f4e0b88-cfaa-11e7-886e-68b441c1ed00.png)

#### Expected behavior
Expected to see a callout component.

The errors in the console seem to indicate blueprint is not exporting the `Callout` class correctly, and I double checked I was on the correct version that released it.

**Comment by cmslewis** [comment]
@imawuman This error indeed appears when you try to render an unrecognized or illegal value as a react component:

![image](https://user-images.githubusercontent.com/443450/33156263-f5b745fc-cfac-11e7-833b-045bb71116ab.png)

Are you sure you have the proper version of `core` and that you're importing the `Callout` component properly? It's being exported from `index.ts`, and tests are passing.

**Comment by imawuman** [comment]
It looks like this issue was caused by yarn.lock resolutions choosing a previous version of blueprint. Don't think there is a bug here, closing out!
