### ISSUE TITLE
Feature Request: Popover2 custom ARROW_SPACING

### ISSUE THREAD

**Issue by ConneXNL** [palantir/blueprint#1844]
There is currently no way to customize the ARROW_SPACING.

I've found 4px to be really on the short end when being used for tooltips.

It would be great if this value can be customized in Popover2/Tooltip2:

https://github.com/palantir/blueprint/blob/master/packages/labs/src/components/popover/popperUtils.ts#L71

**Comment by adidahiya** [comment]
That constant was not designed to be customized. I don't think this be easy to change as it would require a CSS change as well. Can you elaborate on your use case, share screenshots, etc.?
