### ISSUE TITLE
[DateRangeInput] Support format as a function in DateRangeInputProps

### ISSUE THREAD

**Issue by Que3216** [palantir/blueprint#1849]
Currently you can provide a string for the format for DateRangeInput, but we have a use case where we want to make it clear to users that they're selecting a relative range:

   `| 60 days ago |    | 30 days ago | `

http://blueprintjs.com/docs/#datetime/daterangeinput

Would it be possible to change the format prop from:

```
format?: string;
```

to

```
format?: string | (date: Date) => string;
```

@ragunaru for SA

**Comment by giladgray** [comment]
@Que3216 sure, we'll happily accept a PR adding this functionality!
