### ISSUE TITLE
Progress bar starts filling from halfway point

### ISSUE THREAD

**Issue by dylhunn** [palantir/blueprint#1859]
I'm having an issue in which my progress bar starts filling halfway across the bar's space.

`<Blueprint.ProgressBar value={0.3} className="pt-no-animation pt-no-stripes"/>`

This renders as the following:

[Image](https://imgur.com/a/oFmEF)

I have this issue regardless of whether I use the React Component, or the CSS usage in the [docs](http://blueprintjs.com/docs/#core/components/progress/progress-bar.javascript-api).

**Comment by cmslewis** [comment]
We'll need you to provide a minimal repro; I'm not seeing what you're seeing right now. There might be some conflicting CSS in your app. Can you poke around with dev tools and see if that might be the case?

**Comment by dylhunn** [comment]
Thanks Chris. I identified the offending CSS.

I had the following CSS style applied to an ancestor div:

```
.App {
  text-align: center;
}
```

Removing it corrected the problem (but also unaligned my text). Is `text-align` supposed to affect the progress bars?

**Comment by cmslewis** [comment]
1. Is all text in your app really centered? 😛 
2. `pt-progress-meter` element is styled as `display: inline-block`, so it does indeed respond to `text-align`. I, like you, find that side effect surprising and unnecessary. We could probably afford to make the progress fill `position: absolute` within its immediate `pt-progress-bar` parent.

@giladgray @llorca - thoughts?

**Comment by adidahiya** [comment]
a simpler fix would just be `.pt-progress-meter { text-align: left; }`

**Comment by cmslewis** [comment]
@adidahiya hat's not guaranteed to win a specificity war (imagine ancestor elements styled as `.parent .child { text-align: center; }`), and the purist in me doesn't like that the progress bar responds to `text-align` at all.

**Comment by llorca** [comment]
An even simpler fix is to remove `display: inline-block` from `.pt-progress-meter` -- block display works fine and width/height percentages still work. But I suppose this `inline-block` is here for a reason, @giladgray should know why

**Comment by cmslewis** [comment]
@llorca `display: block` sounds good. Looking at the styling, it's weird that we have `position: absolute` with `display: inline-block` in the first place. I've never had to do that in my experience.

**Comment by cmslewis** [comment]
PR: https://github.com/palantir/blueprint/pull/1864
