### ISSUE TITLE
Update Portal to use React 16 Portals for simpler unit testing with Enzyme.

### ISSUE THREAD

**Issue by UselessPickles** [palantir/blueprint#1860]
Enzyme has been updated to support React 16 Portals.

React 16 Portals: https://reactjs.org/docs/portals.html
Relevant Enzyme issue: https://github.com/airbnb/enzyme/issues/1150
Relevant Enzyme pull request: https://github.com/airbnb/enzyme/pull/1345

If Blueprint.Portal was updated to make use of ReactDOM.createPortal, then components involving Blueprint.Portals would be much easier to unit test via Enzyme, because Enzyme's wrapper methods (find, etc.) are now able to work across portal boundaries.

It may even simplify the implementation of Blueprint.Portal.

**Comment by giladgray** [comment]
this will likely happen in 2.0, coming very soon!

**Comment by kudigaracoder** [comment]
2.0? 😃 By end of the year?

**Comment by cmslewis** [comment]
@kudigaracoder That's the goal, yep.

**Comment by kudigaracoder** [comment]
Good luck with the 2.0 update guys! Are you introducing new components?(that's not part of Labs)
