### ISSUE TITLE
[InputGroup] Add default paddingRight to input without rightElement

### ISSUE THREAD

**Issue by alxmiron** [palantir/blueprint#1861]
Hello team!
Just noticed a small issue with text input groups. As I understand, CSS component `TextInput` should display same as default `InputGroup` JS component.
However, `TextInput` has `padding-right: 12px`, but `InputGroup` (withou rightElement) has `padding-right: 0` (inline style rule). 

CSS:
<img width="504" alt="screenshot at dec 04 17-48-07" src="https://user-images.githubusercontent.com/10484318/33561795-4fe7f47c-d91c-11e7-9b67-b3b2728763c9.png">

JS:
<img width="336" alt="screenshot at dec 04 17-49-03" src="https://user-images.githubusercontent.com/10484318/33561853-7458903c-d91c-11e7-8230-f581427486ef.png">

I guess `InputGroup` also should have padding-right.
The problem reason is [here](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/inputGroup.tsx#L117)

**Comment by cmslewis** [comment]
The `InputGroup` isn't actually a 1:1 mapping to `.pt-input`, but we do have an issue open to make that a thing for 2.0, at least as far as naming goes. This is a good thing to track together with that.  👍

**Comment by llorca** [comment]
yup, also this issue may help with styling inconsistencies https://github.com/palantir/blueprint/issues/1425

**Comment by nickensoul** [comment]
@cmslewis @llorca can you approve this changes has been delivered into release?
Looks like on the 3rd version there is no changes about paddings and still adds inline padding.
It's just a bad way to stylish via inline styles, maybe add className tot the `input` that reflects right icon existence?

**Comment by adidahiya** [comment]
@nickensoul this is an old issue, please open a new one if you wish to file a bug
