### ISSUE TITLE
[Core/ButtonGroup] Minimal button groups don't elegantly handle child popover targets

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1866]
### Bug report

- __Package version(s)__: v1.29.0

#### Steps to reproduce

1. Make a minimal button group with two buttons.
1. Put a tooltip around the first one.
1. Hover over the border.

#### Actual behavior

The tooltip flickers, because the minimal-button-group divider is added after the button but _within_ the `pt-popover target`.

![2017-12-05 13 56 49](https://user-images.githubusercontent.com/443450/33633140-a542a838-d9c4-11e7-9255-95c357231d6e.gif)

#### Expected behavior

The divider renders `:after` the `pt-popover-target`.

**Comment by llorca** [comment]
should be solved with https://github.com/palantir/blueprint/issues/754 in 2.0

**Comment by giladgray** [comment]
solved with #754 in 2.0
