### ISSUE TITLE
All documentation links to examples are broken

### ISSUE THREAD

**Issue by hungrysquirrel** [palantir/blueprint#1869]
### Example
All documentation example links are broken.
http://blueprintjs.com/docs/#core/components/tabs2

<img width="603" alt="blueprint_ _documentation" src="https://user-images.githubusercontent.com/232397/33678634-2418dacc-da71-11e7-8461-6e2a401be2ff.png">

**Comment by llorca** [comment]
https://github.com/palantir/blueprint/issues/1854
