### ISSUE TITLE
[showcase] How I've been using Blueprint for the past 2 months.

### ISSUE THREAD

**Issue by shahzeb1** [palantir/blueprint#1875]
Just thought I'd share that for the past 2 months or so I've been using Blueprint to create a central IoT (Internet of Things) hub for a Hackathon.

Youtube demo video: https://youtu.be/w8vM3m2M1ro

Live demo: https://d10rxl2p9vddcd.cloudfront.net/

If you think this project looks cool, consider casting a [vote via the "Vote for this project!"](https://devpost.com/software/oasis-ckwve1) button.

I just wanted to thank the Blueprint team for being awesome and share what I'd been up to with Blueprint! 😄

**Comment by giladgray** [comment]
@shahzeb1 very cool! thank you for sharing how you're using Blueprint! I dig all the dialogs and little Popover menus 👌

**Comment by shahzeb1** [comment]
Thank you. 🙏
