### ISSUE TITLE
best way to prevent button from expanding to fill parent div

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1876]
Hey there,

Just wondering what the best way is to prevent all blueprint buttons from expanding to fill the height of their parent div?

The following keeps happening to me: 

![image](https://user-images.githubusercontent.com/2730609/33790008-ac00726c-dc31-11e7-8c3a-8d16a33fab19.png)

Is this due to some funky css on my end? Or is this just the default of blueprint buttons? 

Thanks!

**Comment by giladgray** [comment]
@tnrich buttons shouldn't do that ordinarily, so it's likely a symptom of the container styles.
that growth is consistent with flex box `align-items: stretch` behavior.

**Comment by giladgray** [comment]
@tnrich have you had a chance to investigate this on your end?

**Comment by tnrich** [comment]
@giladgray we ended up hardcoding all bp button heights to 30px. Kind of rigid but it works

**Comment by DrewDennison** [comment]
@tnrich that sounds hard to maintain. I've seen similar behavior and I've done `align-items: center` or `align-items: flex-start` on the container and it works perfectly. Happy to help debug if you send me sample code that's causing the problem.

**Comment by giladgray** [comment]
this is a flex box issue. should be easily resolved with one line of CSS (likely `align-items` in this screenshot).
