### ISSUE TITLE
FR: Toaster.showOrUpdate(toast, key)

### ISSUE THREAD

**Issue by mcintyret** [palantir/blueprint#1894]
`Toaster` should have a `showOrUpdate(toast, key)` method.

There are times when you want to update a given toast if it already exists, or show it if it doesn't. Tracking the keys returned by `Toaster.show()` and passing them to `Toaster.update()` will fail if the toast has already timed out, and I don't want to track that in my app as well.

A related and smaller FR: it would be nice to be able to optionally pass in keys to `Toaster.show()`, so they can be based on data, rather than having to manually track the keys that are returned.

Happy to put together a PR if you agree.

**Comment by giladgray** [comment]
@mcintyret seems reasonable, would happily review a PR for this feature!
