### ISSUE TITLE
Document normalize.css and blueprint-datetime.css requirements

### ISSUE THREAD

**Issue by thisbejim** [palantir/blueprint#190]
Two details that could be added to the blueprint docs for clarity:

1. In order for all blueprint components to display as expected the user must include [normalize.css](https://github.com/necolas/normalize.css/) in their project.
2. In order for the datetime components to display as expected the user must include ```@blueprintjs/datetime/dist/blueprint-datetime.css``` in addition to the standard ```@blueprintjs/core/dist/blueprint.css```.

**Comment by adidahiya** [comment]
1. You're right, we should really add a section about CSS resources in the usage instructions here http://blueprintjs.com/docs/#components
2. We have a note about this for all the packages in the docs index page -- see the primary callout http://blueprintjs.com/docs/#overview

**Comment by thisbejim** [comment]
Oh yes I can see I completely missed the docs about css for other blueprint packages, my bad!
