### ISSUE TITLE
Table component support onRowClick and onRowDoubleClick callback

### ISSUE THREAD

**Issue by ripitrust** [palantir/blueprint#191]
Hi everyone,
Does the Table component support onRowClick and onRowDoubleClick callback ?

**Comment by llorca** [comment]
@themadcreator I don't remember if you ever built this?

**Comment by themadcreator** [comment]
No, but we've received a number of requests for this. Even perhaps adding a mode full-row selection from cell clicks.

**Comment by alminde** [comment]
I would love if there were a full-row selection mode, or even just `onRowClick` and `onRowDoubleClick` callbacks as a start. Is there anything I can do to help?

**Comment by ripitrust** [comment]
@themadcreator  this sounds like a function with valid and frequent user scenario
please let me know if I can help

**Comment by adidahiya** [comment]
sure, we'd take a PR for this @ripitrust. before you send along the code, could you provide a more detailed proposal of the API changes here?

**Comment by ripitrust** [comment]
@adidahiya  Sure,  let me look into this and update here later

**Comment by llorca** [comment]
@ripitrust @alminde Blueprint 1.2.0 was just released and includes #253 which should enable the use cases mentioned above. Let us know if it works out 👍
