### ISSUE TITLE
[Labs] MultiSelect Search broken in 0.14.1

### ISSUE THREAD

**Issue by benny-medflyt** [palantir/blueprint#1919]
`@blueprintjs/labs` version 0.14.0 works fine.
`@blueprintjs/labs` version 0.14.1 is broken.

The "search" functionality doesn't work for MultiSelect.

The user types keys on the keyboard but they don't appear. Using the mouse to right click and paste a search string in the search input does work.

Chrome devtools shows that there is a "keydown" event handler attached to the input. It seems to be blocking all keys. Deleting the event handler from the Chrome devtools results in the search functionality working correctly.

**Comment by giladgray** [comment]
the actual bug here is in `TagInput` -- can't type in it anymore.

**Comment by giladgray** [comment]
fixed in #1959
