### ISSUE TITLE
Feature request: ExpansionPanel and Divider

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#192]
THIS. IS. AWESOME! Thanks so much guys for this fantastic toolkit. It is exactly what my team has been looking for - since weeks!

Any chance that you may later add 
1.  an [ExpansionPanel](https://material.google.com/components/expansion-panels.html) component or another, accordion-like component;
2.  a [Divider](https://material.google.com/components/dividers.html) component?

All the best

**Comment by adidahiya** [comment]
Thanks for the kind words!

1. The closest thing we have to ExpansionPanel is the [Collapse component](http://blueprintjs.com/docs/#components.collapse). Try it out and let us know if its API could be improved / added to.
2. No divider component for now. I could potentially see this being useful, but it might be tricky to make work in lots of different contexts. In our applications we usually implement borders in CSS, something like `border: solid 1px $pt-divider-black`.

btw, do those material design docs have interactive examples? I couldn't click on anything there

**Comment by llorca** [comment]
No interactive examples, it's just a spec. Gotta look at specific implementations such as [this one](https://material.angularjs.org/latest/demo/autocomplete)

**Comment by forman** [comment]
@adidahiya, yes, in fact I'm already on my way implementing my own ExpansionPanel using Collapse, whose API is everything I need.
