### ISSUE TITLE
[blueprintjs/datetime] allow for optional moment locales

### ISSUE THREAD

**Issue by mscolnick** [palantir/blueprint#1930]
react-day-picker is trying to get `.firstDayOfWeek()` but its trying to get its through `moment.localeData`
https://github.com/gpbl/react-day-picker/blob/ac85a53929e47ba025b523b05d3f6e1c7f112da7/src/addons/MomentLocaleUtils.js#L3

which is commonly excluded in webpack via:

```
const plugins = [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
];
```

this will break for some i18n users

quick solution is to add back locales, but we remove it since it increases build size. it would be nice to be able to use the DatePicker without include locales

**Comment by mscolnick** [comment]
might need a change to react-day-picker, but would be great if possible in bp

**Comment by bbenezech** [comment]
@mscolnick This is what you are looking for: https://github.com/moment/moment/issues/2517#issuecomment-185836313
