### ISSUE TITLE
Anchor links in documentation do not work

### ISSUE THREAD

**Issue by mmoutenot** [palantir/blueprint#1936]
### Bug report

- v1.33.0
- Firefox 58, Chrome 63

#### Steps to reproduce

1. Access [Blueprint Table Documentation](http://blueprintjs.com/docs/#table-js)
1. Click a subsection

#### Actual behavior

No navigation/scrolling occurs. The view remains at the top of the page.

#### Expected behavior

I expect it to navigate/scroll to that subsection.

**Comment by tgreenwatts** [comment]
Same goes for the rest of the site I believe. Tested with Colors

**Comment by adidahiya** [comment]
Fixed on master and release/1.x, I believe
