### ISSUE TITLE
!default for scss variables

### ISSUE THREAD

**Issue by Ciantic** [palantir/blueprint#194]
Currently all variables in SCSS are defined using without !default. 

In order for them to be overrideable all of them should be defined using [!default, see SCSS references](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_)

This is related to #123 

At least these files should be modified:

https://github.com/palantir/blueprint/blob/master/packages/core/src/common/_font-imports.scss#L7
https://github.com/palantir/blueprint/blob/master/packages/core/src/common/_variables.scss
https://github.com/palantir/blueprint/blob/master/packages/core/src/common/_color-aliases.scss

I'm not sure does this need a default in it:

https://github.com/palantir/blueprint/blob/master/packages/core/src/common/_colors.scss

**Comment by dmackerman** [comment]
There are also some cases where components aren't consuming variables, for example `Button` doesn't respect `$pt-font-family`.  I'll see if I can put together a PR will all of these changes.

**Comment by adidahiya** [comment]
why does Button need to define font-family? Shouldn't it just inherit from [base-typography](https://github.com/palantir/blueprint/blob/365232ca4d26988bd96988785cfe534b8af106c4/packages/core/src/common/_mixins.scss#L44) which is applied to `body`?

**Comment by dmackerman** [comment]
@adidahiya I found it strange also, but the font didn't change unless I added the variable to `@mixin pt-button-base()`

**Comment by Reaverart** [comment]
So far I remember, webkit form elements not inherits font-family from body and uses default browser font. `font-family: inherit;` should fix.

**Comment by ugogo** [comment]
Shouldn't all vars has the `!default` param?

**Comment by dmackerman** [comment]
So now that the `~` import syntax is supported, this seems like something I could take a crack at doing now.

**Comment by giladgray** [comment]
certainly crack-worthy, i'd wager 🎩
