### ISSUE TITLE
Select and Suggest ignore className prop

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#1941]
As of labs 0.14.1 (I haven't checked develop) both `Select` and `Suggest` ignore the `className` prop.

It's possible to pass a class name to their popover target using `listProps.className` or `popoverProps.className`, and to `Suggest`'s input using `inputProps.className`, but the plain `className` prop is never actually used in either component.

**Comment by adidahiya** [comment]
Fixed in 1.x, will merge into master soon
