### ISSUE TITLE
Dialog position is fixed in middle screen and cannot be set using some style attributes

### ISSUE THREAD

**Issue by hysoftwareeng** [palantir/blueprint#1957]
### Bug report

- __Package version(s)__: 1.35.0 
- __Browser and OS versions__: Chrome 61.0.3163.100

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/#core/components/dialog, click Show Dialog
![image](https://user-images.githubusercontent.com/7006810/34270183-4f036050-e655-11e7-8906-8d15d4cb3fcd.png)

1. Open Chrome Debugger, click Select Element to Inspect
![image](https://user-images.githubusercontent.com/7006810/34270218-6e2994c2-e655-11e7-87ee-89423cf53612.png)

1. Manually add style (e.g. top: -500px) to pt-dialog to mimic adding style through JS
![image](https://user-images.githubusercontent.com/7006810/34270633-d3e9fe40-e656-11e7-9f9f-2ff0f3a5decd.png)

#### Actual behavior

Dialog position cannot be moved up the screen instead of centered by setting the style prop (such as top). It appears to be always centered in the middle of the screen or needs to be set using margin. 

#### Expected behavior

Dialog positions should be changeable by setting style prop.

**Comment by giladgray** [comment]
@hysoftwareeng this Dialog centering is very much by design (#552 discussion, #1373 implementation). 

we're using simple flex box to ensure the dialog is always centered so of course `top` has no effect. if you want to reposition it, you'll need to modify the flex box layout styles on the `.pt-dialog-container` element (parent of `.pt-dialog`).

**Comment by hysoftwareeng** [comment]
@giladgray Thanks for the response, I am aware that indeed `.pt-dialog` is wrapped in `.pt-dialog-container` in version 1.25.0 onward. Is changing the CSS the only way to modify the flex box layout styles on the `.pt-dialog-container` if I am using a Dialog component and not rendering the `.pt-dialog` markup by hand?

**Comment by giladgray** [comment]
@hysoftwareeng yes CSS is the only way. try passing a `<Dialog className="my-custom-class">` and then writing some styles for `.my-custom-class .pt-dialog-container`.

**Comment by hysoftwareeng** [comment]
@giladgray Thank you! I will close this ticket now.

**Comment by tomzaku** [comment]
@giladgray How can I apply in scss?
```
.menuPopup  {
	.bp3-dialog-container & {
		align-items: flex-start;
		justify-content: flex-start;
	}

}
```
or
```
.menuPopup .bp3-dialog-container {
	align-items: flex-start;
	justify-content: flex-start;
}
```
I tried both but without success
