### ISSUE TITLE
Better control relative height of TabPanel so that content can have scrollbars

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#197]
### Issue Report

- __Package version(s)__: 1.0.1

#### Describe the issue:

I have a single-page app with body taking width:100vw and height:100vh. Body comprises a header, a midsection, a footer. Header and footer have fixed height, the midsection has height:100% - holy grail layout.

Say, I now want to display images of fixed size within the midsection, each image in a `TabPanel`. I want scrollbars to automatically appear when image size is larger than available  `TabPanel` space:

```tsx
const imagePanelStyle = {
    width: "100%",
    height: "100%",
    overflow: "auto",
};

const tabs = ( 
    <Tabs>
        <TabList>
            <Tab>SST</Tab>
            <Tab>OC</Tab>
        </TabList>
        <TabPanel>
            <div style={imagePanelStyle}>
                <img src="resources/SST.png"/>
            </div>
        </TabPanel>
        <TabPanel>
            <div style={imagePanelStyle}>
                <img src="resources/OC.png"/>
            </div>
        </TabPanel>
    </Tabs>
);
```

#### Actual behavior:

The problem that now occurs is that the `div` that holds the image will be of the same height as the `Tabs` element, and this includes the (unknown) height of the `TabList` component! I can only get around this if I make my `div` having the style 

```tsx
const imagePanelStyle = {
    width: "100%",
    height: "calc(100% - 50px)",
    overflow: "auto",
};
```` 

where the hard-coded `50px` are the `30px` of the `TabList` plus `20px` for the extra `TabPanel` margin-top space. This is very unsatisfying.

Note I am still a TS/CSS beginner and maybe I am doing something wrong.

#### Expected behavior:

It would be nice if there was a property for `TabPanel` that controls the way extra space (height) is assigned. The mode I need here is `height = calc(100% - heightOfTabList).

**Comment by giladgray** [comment]
sorry this should not have been closed, but i'm sure the answer is flex box.

**Comment by forman** [comment]
I agree, Tab2 API solves the issue.
