### ISSUE TITLE
Select-style button for MultiSelect dropdown (feature request)

### ISSUE THREAD

**Issue by rheinheimer** [palantir/blueprint#1970]
Feature request: I am trying to create a compact multi-select, effectively some combination of Select and MultiSelect, with the ability to 1) have checkmarks in the select dropdown (MultiSelect), 2) have the dropdown stay open (MultiSelect), and 3) have a button-style renderer (Select). This is similar to, say, [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/examples/)'s "multiple select boxes". Having the tag-style selections is nice with the MultiSelect, but technically redundant. Having a Select-style button renderer would allow, e.g., "3 items selected" instead of the full list of tags.

If I can already achieve this, please let me know. Perhaps there is a way to keep Select open until closed, in a manner similar to MultiSelect?

**Comment by llorca** [comment]
Any luck with controlled usage? http://blueprintjs.com/docs/#labs/select-component.controlled-usage

**Comment by rheinheimer** [comment]
Controlled usage is one approach, especially in combination with resetOnSelect=false. I ended up going with the very new [react-picky](https://github.com/Aidurber/react-picky), which exactly addresses this issue of needing a multi-select with more than just a few selections. I did, however, style it with Blueprint styles, as much as possible at the moment.

**Comment by giladgray** [comment]
@rheinheimer you could even use `QueryList` directly (just like `Select` and `MultiSelect` do internally) for the filtering and keyboard handling!

either way, seems this issue is resolved.

**Comment by arunmmanoharan** [comment]
> Controlled usage is one approach, especially in combination with resetOnSelect=false. I ended up going with the very new [react-picky](https://github.com/Aidurber/react-picky), which exactly addresses this issue of needing a multi-select with more than just a few selections. I did, however, style it with Blueprint styles, as much as possible at the moment.
> 
> EDIT:
> 
> For anyone else needing this, I ended up using Popover2 + Menu. Easy, and the effect is the same. Here's my component, more or less, where `itemRenderer` is similar to that of `MultiSelect`: a `MenuItem` component, with icons of tick or blank, depending on `isSelected`, and `shouldDismissPopover` optionally set to true to prevent closing on select.
> 
> ```
> <Popover2 minimal placement="bottom-start">
>     <Button text={!selected.length ? ("Select something...") : selected.length === 1 ? items.find(i => i.id === selected[0]).name : (`${selected.length} selected`)}/>
>     <Menu>
>         {items.map(item => itemRenderer(item, {
>             index: item.id,
>             handleClick: this.handleClick,
>             isSelected: selected.includes(item.id)
>         }))}
>     </Menu>
> </Popover2>
> ```

Could you share your implementation please?
