### ISSUE TITLE
Context Menu renders unneeded transparent padding, yielding bad look.

### ISSUE THREAD

**Issue by yaronlavi** [palantir/blueprint#1973]
### Bug report

- __Package version(s)__: @blueprintjs/core 1.35.0
- __Browser and OS versions__: Chrome 63.0.3239.108 (Official Build) (64-bit), on Windows 10

#### Steps to reproduce

1. Create a Tree
1. on the Tree's onNodeContextMenu event, use ContextMenu.show static function to show a menu on the tree node the user right-clicked.

#### Actual behavior
The context menu is shown, but has unneeded left and right padding, which is also semi-transparent - hence the background is showing on the menu, resulting is bad user experience (see attachments).
![context_menu_issue2](https://user-images.githubusercontent.com/26144112/34516584-0c5f293e-f080-11e7-9897-ff58691dc540.jpg)
![context_menu_issue1](https://user-images.githubusercontent.com/26144112/34516585-0c7de310-f080-11e7-9075-036ffaf8e6e3.jpg)

Further digging shows (see context_menu_issue2) the menu is wrapped with a div having pt-minimal class doing the unneeded padding. I cannot remove it, since the className passed to the contextMenu is applied to a child UL far down the chain.

This seems a bug to me. I'm about to release  a production build soon, and will appreciate a WA or a fix.

#### Expected behavior
No extra padding for the context menu.

**Comment by giladgray** [comment]
@yaronlavi that `.pt-minimal { }` selector you've highlighted does not seem to exist in Blueprint's codebase. I just searched for it: we always qualify that modifier with at least one other class; it never appears by itself in a selector.

is it possible _you_ added that rule in your app?

**Comment by yaronlavi** [comment]
Nope; all I need is add a ContextMenu.show static call. Can this b related to the menu itself? the menu I've constructed uses a title in a divider and so on - can this be related?

**Comment by yaronlavi** [comment]
To clarify, we are not stating that we are seeing this selector acting like a single selector, but after investigation is seems that this is the root cause for the transparency and padding issue.


Thanks,
Yaron

On 3 Jan 2018, at 23:46, Gilad Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


@yaronlavi<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaronlavi&data=02%7C01%7C%7C2b7ed2ab335543ae379908d552f375ad%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636506127960779339&sdata=mRVbyAQRVF4Vpddh69TsjogPaf9E21OtwATeg7bHifE%3D&reserved=0> that .pt-minimal { } selector you've highlighted does not seem to exist in Blueprint's codebase. I just searched for it: we always qualify that modifier with at least one other class; it never appears by itself in a selector.

is it possible you added that rule in your app?

**Comment by giladgray** [comment]
yes that selector is the root cause of this issue, and i'm fairly certain that it is not coming from any of Blueprint's own stylesheets. possible someone added it to your codebase intended to target some other use of the `.pt-minimal` __modifier__ class?

"minimal" is a __modifier__ in Blueprint: it doesn't mean anything on its own, it only has meaning when used **to modify a component that supports it**, such as `.pt-button.pt-minimal`.

**Comment by yaronlavi** [comment]
Checked again and nothing is added on our side.

If you’ll take the tree sample you have in your site, and call ContextMenu.show on the nodeRightClick I’m pretty sure you’ll see that too.

Thanks,
Yaron

On 4 Jan 2018, at 21:08, Gilad Gray <notifications@github.com<mailto:notifications@github.com>> wrote:


yes that selector is the root cause of this issue, and i'm fairly certain that it is not coming from any of Blueprint's own stylesheets. possible someone added it to your codebase intended to target some other use of the .pt-minimal modifier class?

"minimal" is a modifier in Blueprint: it doesn't mean anything on its own, it only has meaning when used to modify a component that supports it, such as .pt-button.pt<http://pt-button.pt>-minimal.

**Comment by giladgray** [comment]
@yaronlavi this does not reproduce on the documentation site example, which uses both methods of opening a context menu: http://blueprintjs.com/docs/#core/components/context-menu.

i'm telling you, the bug is not in our code because it goes against the very definition of a modifier, which is a central piece of the blueprint ecosystem.
