### ISSUE TITLE
[Table] onVisibleCellsChange not called on scroll in React 16.x

### ISSUE THREAD

**Issue by jdiprizio** [palantir/blueprint#1974]
### Bug report

- __Package version(s)__: `"@blueprintjs/core": "^1.35.0"` `"@blueprintjs/table": "^1.31.0"`
- __Browser and OS versions__: `Chrome 63.0.3239.108` `Ubuntu 17.10`

#### Steps to reproduce

1. Add handler with console.log for `onVisibleCellsChange` on a table with fixed height and lots of rows
1. Scroll table
1. Note that handler is called on mount but not on scroll

#### Actual behavior

`onVisibleCellsChange` is not called on scroll

#### Expected behavior

`onVisibleCellsChange` should be called on scroll

#### Fix

The issues lies in [updateViewportRect](https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L2087) method in `table.tsx`.

Code below:
```
this.setState({ viewportRect: nextViewportRect });
const { viewportRect } = this.state;

const didViewportChange =
            (viewportRect != null && !viewportRect.equals(nextViewportRect)) ||
            (viewportRect == null && nextViewportRect != null);
```
is incorrect because `viewportRect` is destructured after the setState. React recent updates have changed the way setState is executed and state may be set immediately, thus causing `didViewportChange` to be false and the `onVisibleCellsChange` to not be invoked. Simply swapping the first two lines fixes the issue.

**Comment by giladgray** [comment]
@jdiprizio thanks for the bug report, and double thanks for finding the offending code!! would happily accept a PR for this.
