### ISSUE TITLE
Select not styled

### ISSUE THREAD

**Issue by kschrader02** [palantir/blueprint#1975]
Hi, I've just been getting started with blueprintjs and have noticed that quite a few of the github source links on the website are broken and give 404 errors. I have been able to find the related examples in the github repo, but some of them do not quite match the explained example in the documentation. For example, the Select example. It places the Select component in the blueprintjs/select package, although it is in blueprintjs/labs package as far as I can tell and the implementation is slightly different. I got it to work, but for some reason the component looks unstyled even though I have imported blueprint.css. Also, it does not show you the options in a scrollable container, it just opens up all the way down the page. Shouldn't this by default look and act like the example on the website? I essentially copied the example in the repo and took out the toggled option switches.

I have installed:

blueprintjs/core  ^1.35.0
blueprintjs/labs ^0.14.2
blueprintjs/docs ^1.2.0
blueprintjs/table ^1.31.0

**Comment by giladgray** [comment]
Check out the `release/1.x` branch! We're working on 2.0 on master which
will release in the next few weeks. Until then, the docs site is still for
1.0.

**Comment by kschrader02** [comment]
I'll look at that, thanks!

**Comment by kschrader02** [comment]
@giladgray Well, my select still looks weird. I've attached a screenshot of a simple application with just the multiselect example on it. It doesn't look like the example given on the website, is there some other css I'm missing? I've only included blueprintjs/core/dist/blueprint.css.

<img width="1680" alt="screen shot 2018-01-05 at 1 50 16 pm" src="https://user-images.githubusercontent.com/19213552/34625717-68a581d4-f21f-11e7-9de8-d8ba0a0bb320.png">

**Comment by kschrader02** [comment]
Here's what it looks like open. 

<img width="1680" alt="screen shot 2018-01-05 at 1 54 46 pm" src="https://user-images.githubusercontent.com/19213552/34625892-16a0208c-f220-11e7-8f5a-eef45d34099f.png">

**Comment by kschrader02** [comment]
So I found out that the select looks more properly styled on my macbook than it does on my linux desktop for some reason, but the dropdown still goes all the way down for both rather than having a scrollable container. (and yes, I know the screenshot is a multiselect. It has the same issue)

**Comment by giladgray** [comment]
@kschrader02 looks like you're missing the labs stylesheet. you'll need blueprint.css from core and blueprint-labs.css from labs.

**Comment by giladgray** [comment]
refocusing this issue on your lack of labs stylesheet. broken links are tracked here #1936

**Comment by kschrader02** [comment]
@giladgray got it, thanks!

**Comment by trevorhalvorson** [comment]
@giladgray I'm still seeing the `Select` dropdown go all the way down the page, but it is styled.

> you'll need blueprint.css from core and blueprint-labs.css from labs.

I've imported blueprint.css from core, but how can I import blueprint-labs.css from labs? I don't see it in my `node_modules`.

Versions:
 ```
"@blueprintjs/core": "^1.35.4",
"@blueprintjs/labs": "^0.15.3",
```

**Comment by adidahiya** [comment]
@trevorhalvorson `@blueprintjs/labs` 0.15 is not compatible with `@blueprintjs/core` 1.x -- check out the dependencies in package.json

**Comment by rheinheimer** [comment]
@kschrader02 Did you end up resolving the CSS styling for the input itself? I can't figure out at all how to do it. The closest I've come to the docs is as below:
![image](https://user-images.githubusercontent.com/9124277/37943317-14125e84-3145-11e8-95ff-694814e842db.png)
This is with core@1.35.x, labs@0.14.x, select@2.0.0, pulling in CSS from each. Maybe there's some incompatibility here, and once I get over to 100% 2.0.0 things will resolve. Still, it would be good to know what works pre-2.0.

**Comment by giladgray** [comment]
@rheinheimer avoid using 2.0.0 packages with 1.x packages. you're seeing conflicting styles for selects and icons due to core 1.35 and core 2.0 (brought in by select 2.0). either do the upgrade fully, or don't do it at all 🌴

**Comment by rheinheimer** [comment]
Thanks @giladgray
