### ISSUE TITLE
Cards JavaScript API docs reference incorrect Elevation variable

### ISSUE THREAD

**Issue by chiubaka** [palantir/blueprint#1976]
The `Card` JavaScript API doc references `Card.ELEVATION_TWO` as an example for how to set the elevation of a `Card`. This member does not exist on `Card`. There is, however, an exported enumeration `Elevation`. The example should read

```
<Card interactive={true} elevation={Elevation.TWO}>
    <h5><a href="#">Card heading</a></h5>
    <p>Card content</p>
    <Button>Submit</Button>
</Card>
```

**Comment by llorca** [comment]
@chiubaka good catch! fix over there https://github.com/palantir/blueprint/pull/1979
Next time feel free to directly edit the typo, we'd appreciate it. Thank you 🙏
