### ISSUE TITLE
[Core/NumericInput] Document that `minorStepSize` and `majorStepSize` can be null

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1978]
It's not documented, but you can pass `null` for `minorStepSize` or `majorStepSize` to disable the corresponding Alt+increment or Shift+increment interaction. Should document this.

**Comment by giladgray** [comment]
bummer the docs don't include `null`-able types. enabling `strictNullChecks` should cause them to be emitted in the docs data, but that's a huuuuuge undertaking.
