### ISSUE TITLE
Add option to KeyCombo component to hide key text

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1980]
It would be nice to have the option to not have the little text next to the special keys. 
![image](https://user-images.githubusercontent.com/2730609/34729074-8f725564-f510-11e7-8c08-08d4cdd591df.png)
Aka there would no longer be "shift", just the icon.

**Comment by cmslewis** [comment]
Cool idea / makes sense. Would happily review a PR if you want to try tackling this, @tnrich!

**Comment by giladgray** [comment]
while i'm not opposed a feature that hides the name, i will say that we deliberately decided to always include the key name because the special symbols are not as widely known or used. omitting the name is a quick path to accessibility problems.

**Comment by tnrich** [comment]
@giladgray I think that makes sense most of the time but I was interested in a condensed version for use as context menu labels.

**Comment by giladgray** [comment]
@tnrich I think this component will be too visually heavy for menu item labels -- it's got a strong shadow so it looks like a keyboard key.

**Comment by tnrich** [comment]
@cmslewis I put in a PR above. @giladgray I am just updating the css in my app to make it look nice but I think it would be a cool use case to build this component into blueprint MenuItem component as a keyCombo prop or something.

**Comment by llorca** [comment]
Why not use the icon directly if you need it as a label within a context menu?

**Comment by tnrich** [comment]
I am using the KeyCombo component because it makes it a little easier to
just put for example meta+c  and have it look correct on windows and mac

**Comment by giladgray** [comment]
@tnrich yo i actually implemented this in #2256 without realizing there was an issue! `<KeyCombo minimal>` removes the `<kbd>` frames and the "Shift" text. see it in action in the new docs sidebar for button hotkeys.
