### ISSUE TITLE
Custom style for Alert confimation/cancel buttons

### ISSUE THREAD

**Issue by franciscofabian** [palantir/blueprint#1986]
I would like to be able to set my own style for the confirmation and cancel buttons on the Alert component. I want to possibility to have a minimal style for those buttons, this is not currently possible.

**Comment by giladgray** [comment]
@franciscofabian the `Alert` component was designed to present a very specific UI, so this is not currently supported. if you'd like to submit a PR to add `confirm/cancelButtonProps` then go for it!

**Comment by adidahiya** [comment]
I'd like @llorca's input first -- Alert is designed to be very opinionated, and you can easily achieve the result you want with a Dialog.

**Comment by llorca** [comment]
as said previously, considering that `Alert` is a very opinionated interaction, and considering that the API is super specific, I don't see an elegant solution to this issue 😕  definitely use `Dialog` in the meantime for full flexibility, you can do what you request and customize every piece of it

**Comment by franciscofabian** [comment]
Ok, I understand that, the only reason why I don’t use the `Dialog` component is because it doesn’t have the restrictions that it cannot be closed by clicking the overlay or pressing `esc`. And since I use minimal style for all my buttons, I would like to use them as well in `Alert`.

**Comment by giladgray** [comment]
@franciscofabian not to worry, there are props on `Dialog` for those behaviors!
![image](https://user-images.githubusercontent.com/464822/34854477-ca7e68a2-f6ee-11e7-8e1e-6e5f60e0bfe9.png)

if you really want default buttons _everywhere_, just set `Button.defaultProps.className = "pt-minimal", lol

**Comment by franciscofabian** [comment]
That's great! You learn something new everyday, thanks! 😂 
How can I set `Button.defaultProps.className = "pt-minimal"`? I'm not able to make it work

**Comment by giladgray** [comment]
Literally just that line of code before you use it. The goal is to override
a static member.

**Comment by franciscofabian** [comment]
@giladgray it isn't working for `Button` or `AnchorButton`, I see that the components do not have defined the static member that you mention `public static defaultProps: IButtonProps = {...}` as other components do, like `Dialog`. Is it that a bug?

**Comment by giladgray** [comment]
@franciscofabian so define the static member... we chose not to define it as it's not strictly necessary. modifying `defaultProps` is a hacky workaround anyway, but is fully supported by React.
