### ISSUE TITLE
minimize @blueprintjs footprint size in bundle.js

### ISSUE THREAD

**Issue by yaronlavi** [palantir/blueprint#1987]
### Bug report

- __Package version(s)__: 1.0.35
- __Browser and OS versions__: Windows 10, chrome latest

#### Steps to reproduce
Hi,
we're using @blueprintjs/core with a webapp having 10 pages. The client's bundle.js size is about 5 megs, of which @blueprintjs footprint is 2.5 megs (see attached picture)

is that normal? it's huge. Is there a way to remove/minify the deployment (such as removing unneeded icon formats, or cutting out unneeded styles from blueprint.css?

![bundlejs_size](https://user-images.githubusercontent.com/26144112/34821190-988715b0-f6cb-11e7-865f-0f5661960377.jpg)

**Comment by adidahiya** [comment]
Are you stripping comments from the imported CSS file? Are you minifying it properly?

**Comment by yaronlavi** [comment]
I’m using webpack loader to load @blueprintjs. Is there anything else I should do?

Didn’t see anything about this in the docs either.

Thanks,
Yaron

On 11 Jan 2018, at 18:00, Adi Dahiya <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you stripping comments from the imported CSS file? Are you minifying it properly?

**Comment by adidahiya** [comment]
Which webpack loader? There are a lot of ways you could be using webpack to bundle blueprint. For example, we pull in the CSS through our Sass pipeline. You can see our [webpack config here](https://github.com/palantir/blueprint/blob/ccdc895c25f8d58d37c4a4c5985ae531c0a89b5f/packages/webpack-build-scripts/webpack.config.base.js#L127) and the [blueprint.css import here](https://github.com/palantir/blueprint/blob/ccdc895c25f8d58d37c4a4c5985ae531c0a89b5f/packages/docs-app/src/index.scss#L7).

Blueprint ships unminified assets and expects you to do your own optimization for production builds.

**Comment by giladgray** [comment]
i think the outrageous size of blueprint.css is really on us. it has the same 200-line comment included dozens of times.

**Comment by adidahiya** [comment]
Which 200-line comment?

I see no extraneous text in blueprint's CSS in the production builds of our products, so you'll have to convince me otherwise.

https://github.com/palantir/blueprint/blob/master/docs/blueprint-landing.css

**Comment by adidahiya** [comment]
Now, there could be an argument here for stripping `/* Styleguide */` comments from `dist/blueprint.css`. But it's not a high priority issue because of my previous statement.

**Comment by yaronlavi** [comment]
we have added a minimize attribute the the cssloader and indeed the CSS footprint was dramatically reduced. thanks for that!

Now, is there a way I can remove some of the icon fonts safely, or all formats (ttf, woff2, eot) are needed for all browsers? what do you recommend?

**Comment by yaronlavi** [comment]
turns out that all format but woff can be removed when working with modern browsers, and my loader now filters out the rest of the formats. 
this issue/question can be closed.

**Comment by joehanko** [comment]
Hey @yaronlavi how did you make the treemap?

**Comment by tony** [comment]
@joehanko https://github.com/webpack-contrib/webpack-bundle-analyzer
