### ISSUE TITLE
custom data object for each treenode

### ISSUE THREAD

**Issue by yaronlavi** [palantir/blueprint#1989]
We're using the tree component, and have the need to a custom data object for **each node**; alas, I could not find any userData or similar property in ITreeNodeProps.

Can this feature be added, or some workaround be suggested? this is quite critical for any production-level app using a tree.

**Comment by giladgray** [comment]
@yaronlavi such a thing does not seem to exist, but we'd happily accept a PR to add such a feature.

either a new `userData` key or simply `[key: string]: any` index support would solve this handily.

**Comment by yaronlavi** [comment]
a userData:any seems more generic and common to me. PR #1998 opened. 
thanks.

**Comment by adidahiya** [comment]
We require all nodes to have a unique ID. I think you can use your own data structure to store this data and simply look up the data object you need for each node.

**Comment by giladgray** [comment]
@adidahiya's id lookup proposal actually seems sufficient for this feature.
