### ISSUE TITLE
Let RangeSlider be only as wide as necessary

### ISSUE THREAD

**Issue by SuhairZain** [palantir/blueprint#1991]
Hi,
I'm currently using the `RangeSlider` component in a space limited UI and would like to reduce the width of the slider to be about 110px for 5 steps. The problem is that the component seems to have a minWidth set and thus has issues when I reduce it below about 150px. Is there a way to bypass this limitation?

**Comment by giladgray** [comment]
@SuhairZain can you simply override the `min-width` with your own CSS selector?

**Comment by giladgray** [comment]
closing as stale. nothing to do here.
