### ISSUE TITLE
Swap confirm and newline key entries for EditableText's multiline mode

### ISSUE THREAD

**Issue by cyu06** [palantir/blueprint#20]
Requested by benh.

> there should still be an option to allow the non-multiline mode to text wrap [and preserving confirm on `Enter`].

**Comment by cmslewis** [comment]
@cyu i have some bandwidth for additional issues before EOW. Want me to take this one?

**Comment by cyu06** [comment]
Sure, thanks

**Comment by cmslewis** [comment]
Can you describe what needs to be done in a little more detail? By my current reading, the objective here is to just swap the hotkeys to <kbd>Enter</kbd> for submitting and <kbd>Ctrl/Cmd</kbd> + <kbd>Enter</kbd> for adding a newline in `multiline` mode? (Incidentally, I think <kbd>Shift</kbd> + <kbd>Enter</kbd> is a common hotkey for that.)

**Comment by cyu06** [comment]
From @llorca last comment it seemed like he just wanted the current behavior to not fall under the multiline={true} case. The reason I didn't do this originally was because that's basically saying you have a singleline mode, e.g. multiline={false} that can wrap. Underneath it will still need to be a text area.

The basic use case is a user wanted a single line of text that could effectively wrap, while still confirm with the plain Enter key. So that it doesn't run off off the input and ellipsis. They were using this for a column header and wanted to be able to always see the whole text that was input. So they began using the multiline={true} case but didn't want to have to train users to Ctrl/Cmd + Enter to Confirm.

@giladgray suggested widening the combo group to be inclusive of shift, control, option, or command + enter, so the keypress requires minimal training.

The last state I QE'ed this seemed to match the expected behavior. Antoine was just concerned with the prop choice to enable this swap (as well as concerned we shouldn't swap confirm to begin with for consistency sake). I am of the camp that the developer using the library should have the choice.

**Comment by cmslewis** [comment]
Cool. So what are the exact action items? Or does this still need further discussion?

**Comment by cyu06** [comment]
I don't believe so. I was just going to change the prop configuration so it is only possible under multiline={false}. But again, on the PR comments, this will still use a textarea under the hood.

Widening the entry group was agreed upon with gilad awhile ago. But perhaps the view has changed.
