### ISSUE TITLE
document peer dependencies during npm install

### ISSUE THREAD

**Issue by dongyuhappy** [palantir/blueprint#201]
when i run `npm install --save @blueprintjs/core` to install .I got this error

> │ ├── UNMET PEER DEPENDENCY react@^15.0.0 || ^0.14.0
> │ └── tether@1.3.7
> ├── UNMET DEPENDENCY react@^15.3.2
> ├── UNMET PEER DEPENDENCY react-addons-css-transition-group@^15.0.1 || ^0.14
> └── UNMET DEPENDENCY react-dom@^15.3.2
> 
> npm WARN @blueprintjs/core@1.0.1 requires a peer of react@^15.0.1 || ^0.14 but none was installed.
> npm WARN @blueprintjs/core@1.0.1 requires a peer of react-addons-css-transition-group@^15.0.1 || ^0.14 but none was installed.
> npm WARN @blueprintjs/core@1.0.1 requires a peer of react-dom@^15.0.1 || ^0.14 but none was installed.
> npm WARN pure-render-decorator@1.1.1 requires a peer of react@^15.0.0 || ^0.14.0 but none was installed.

**Comment by giladgray** [comment]
this is expected behavior--you have to install React alongside @blueprintjs/core. we chose to use peer dependencies so you can choose the version of React instead of it being imposed upon you by our library.

`npm install` those three libraries and you'll be good to go!

we'll add this to the documentation.

**Comment by dongyuhappy** [comment]
then i got this error

> NMET PEER DEPENDENCY react-addons-css-transition-group@^15.0.1 || ^0.14

**Comment by adidahiya** [comment]
Sure, we could add a _very brief_ note to the documentation but honestly I don't see how NPM's _inline console messages_ could be any more clear in this case. The first few google results for "unmet peer dependency" also tell you what to do. http://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency

**Comment by vyorkin** [comment]
btw I've just spent some time debugging issue with missing `@types/tether` dependency, it isn't specified in `@blueprintjs/core`, I guess it should be. Please correct me if I've missed smth.

**Comment by Swivelgames** [comment]
There appears to be an actual issue here.

```
{
  "name": "reactdemo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "1.0.14"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-dom": "^16.0.0",
    "react-transition-group": "^1.2.1",
    "@blueprintjs/core": "^1.32.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Running `npm i` results in the following:

```
reactdemo@0.1.0
├─┬ @blueprintjs/core@1.32.0
│ ├── @types/dom4@1.5.20
│ ├── @types/tether@1.4.3
│ ├── classnames@2.2.5
│ ├── dom4@1.8.5
│ ├── normalize.css@4.1.1
│ ├── pure-render-decorator@1.2.1
│ ├── UNMET PEER DEPENDENCY react@^15.0.0 || ^0.14.0
│ ├── tether@1.4.0
│ └── tslib@1.8.0
├─┬ UNMET PEER DEPENDENCY react@16.0.0
│ ├─┬ fbjs@0.8.16
│ │ ├── core-js@1.2.7
...truncated...
```

**Comment by adidahiya** [comment]
@Swivelgames If you're using React 16, we're currently in an awkward in-between state where we need react-addons-css-transition group for pre-16 support, hence the peer dep warnings. They should be safe to ignore for now. Follow #866 for more updates.

**Comment by Swivelgames** [comment]
@adidahiya Thanks for the update!
