### ISSUE TITLE
Clean up tree node props

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#2014]
- `path` is completely unused
- `depth` should be auto-computed

**Comment by giladgray** [comment]
there's a critical distinction to be made between `ITreeNode` (the public interface that users supply to `<Tree contents>`); and `ITreeNodeProps`, which extends ITreeNode with handlers and internal fields, including `path` and `depth`.

**`path` and `depth` do not appear in `ITreeNode`, so users do not have to supply them.**

1. `path` _is used_, but only in `Tree`: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tree/tree.tsx#L138-L139
1. `depth` _is_ auto-computed.

not sure there's any actual work to be done here?

**Comment by adidahiya** [comment]
ah, right, that makes sense, seems like I was skimming the code. no change necessary.
