### ISSUE TITLE
@light-blue colors please!

### ISSUE THREAD

**Issue by spefley** [palantir/blueprint#2017]
I see a lot of lighten(@blue5, 15%) going on for selection and such. I know we have pt-text-selection-color, but sometimes you want a hover & a selection for both color and background color. It would be nice to have these lighter blues standardized.

**Comment by pkwi** [comment]
I cant think of any selections that would use 15% blue. There are only few places where we use them in Blueprint - hover state for the primary minimal buttons, background colour for the primary callouts and Table cell active state.
Could you provide examples of selections using 15% blue?

**Comment by giladgray** [comment]
@llorca @pkwi do we need this?

**Comment by llorca** [comment]
Piotr is right, we actually rarely use transparent blues for selection, it's usually a solid blue. We do this a lot more for grays, but I'm not sure what the right semantics would be here.

One idea could be to provide some sort of `minimal(color)` mixin that given a color returns the same color but transparentized. Not sure if that makes a ton of sense 🤷‍♂️

**Comment by giladgray** [comment]
cool sounds like a soft no
