### ISSUE TITLE
[docs] all type aliases should be de-referenced

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#2020]
even with #1982, we still have some references that are opaque and not useful, like `TreeEventHandler`:

![image](https://user-images.githubusercontent.com/723999/35109775-4e738150-fc45-11e7-9c10-b994777d1dcb.png)

**Comment by giladgray** [comment]
@adidahiya my next docs PR will introduce an API browser that includes type aliases, so you'll be able to click on `TreeEventHandler` and see what it aliases. does that address this issue? we could take it a step further and put a popover on aliases that shows aliased type?

**Comment by adidahiya** [comment]
Either of those approaches would work. Popover is better UX.
