### ISSUE TITLE
npm package @blueprintjs/core/lib does not contain folders for scss and less variables

### ISSUE THREAD

**Issue by Kafkalasch** [palantir/blueprint#2024]
### Bug report

The installed core packe is missing some files and folders in core/lib

- __Package version(s)__: 2.0.0-beta.1

#### Steps to reproduce

npm install @blueprintjs/core

#### Actual behavior

the folder node_modules/@blueprintjs/core/lib contains only the folders:

-  cjs
-  css
-  esm

#### Expected behavior

the folder node_modules/@blueprintjs/core/lib contains the folders:
- css/ for styles
- scss/ for variables.scss
- less/ for variables.less
- cjs/ for CJS modules
- esm/ for ES modules

as proposed in Issue [1929](https://github.com/palantir/blueprint/issues/1929) and documented in the [official doc](http://blueprintjs.com/docs/v2/#core/variables)

**Comment by adidahiya** [comment]
You're right, I can verify on unpkg: https://unpkg.com/@blueprintjs/core@2.0.0-beta.1/lib/

The dist/ folder is also missing, along with the UMD bundle.

**Comment by paulpooch** [comment]
I used to do `@import "@blueprintjs/core/dist/variables.scss";` but now this is longer possible.

**Comment by adidahiya** [comment]
Fixed in 2.0.0-beta.3! https://unpkg.com/@blueprintjs/core@2.0.0-beta.3/lib/scss/variables.scss

**Comment by Kafkalasch** [comment]
thanks a lot!
