### ISSUE TITLE
Table element no height on Safari

### ISSUE THREAD

**Issue by benheymink** [palantir/blueprint#203]
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Safari 10.0.1 (12602.2.14.0.7)

#### Describe the issue:

Table elements not rendering correctly.

#### Actual behavior:

Table elements are rendered with a very small height. This can be observed on the documentation example when using Safari.

#### Expected behavior:

Table elements should expand to fill the number of rows specified.
![screen shot 2016-11-18 at 14 21 02](https://cloud.githubusercontent.com/assets/824764/20433146/42c7229e-ad9a-11e6-93dc-eda97f24a8d7.png)

**Comment by cmslewis** [comment]
Thanks for the report, @benheymink! As you probably saw before, we've added this issue to our 1.2.0 milestone to be released on Dec 2nd; we'll do our best to get the fix in by then.
