### ISSUE TITLE
[Popover2] Popovers don't update nested popovers' position when updated

### ISSUE THREAD

**Issue by tyscorp** [palantir/blueprint#2031]
When a Popover's position is updated, [scheduleUpdate](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#Popper.scheduleUpdate) needs to be called on all children Popovers.

This can be solved similarly to [this issue](https://github.com/palantir/blueprint/issues/2030).

**Comment by giladgray** [comment]
@tyscorp sure thing! interested in submitting a PR?

**Comment by giladgray** [comment]
@tyscorp is this issue still relevant? we've upgrade popper several times and now invoke `scheduleUpdate` when target or content are resized.
