### ISSUE TITLE
DateInput v2 focus highlight with Chrome is broken

### ISSUE THREAD

**Issue by LittlePony** [palantir/blueprint#2038]
### Bug report

- __Package version(s)__: 2.0.0-beta.2, 2.0.0-beta.3
- __Browser and OS versions__:  Chrome 63 Linux, Chrome 63 Windows

#### Steps to reproduce

1. open http://blueprintjs.com/docs/v2/#datetime/dateinput
2. set focus to DateInput

#### Actual behavior

No highlight (outline) visible. 

#### Expected behavior

Highlight (outline) visible.

**Comment by adidahiya** [comment]
🤔  works fine in FF and Safari, but I can reproduce the bug in Chrome. Thanks for reporting!

**Comment by LittlePony** [comment]
this happening only if value or defaultValue defined (not empty)

**Comment by giladgray** [comment]
outline getting clipped again. we've seen this shiz before 😢
