### ISSUE TITLE
v2 Suggest is broken

### ISSUE THREAD

**Issue by nikitaulshin** [palantir/blueprint#2040]
### Bug report

- __Package version(s)__: @blueprintjs/select@latest
- __Browser and OS versions__: chrome@latest

#### Steps to reproduce

        const itemRenderer = ({ handleClick, isActive, item }) => {
            return (
                <MenuItem
                    label='label'
                    key={ Date.now() }
                    onClick={ handleClick }
                    text='text'
                />
            );
        };

                <Suggest
                    items={ [] }
                    inputValueRenderer={ city => city.title }
                    itemRenderer={ itemRenderer }
                />

#### Expected behavior
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `TransitionGroup`.

The above error occurred in the <span> component:
    in span (created by TransitionGroup)
    in TransitionGroup (created by Blueprint.Overlay)
    in div (created by Blueprint.Portal)
    in Blueprint.Portal (created by Blueprint.Overlay)
    in Blueprint.Overlay (created by Blueprint.Popover)
    in span (created by Manager)
    in Manager (created by Blueprint.Popover)
    in Blueprint.Popover (created by Blueprint.QueryList)
    in Blueprint.QueryList (created by Blueprint.Suggest)
    in Blueprint.Suggest

**Comment by adidahiya** [comment]
It works in the [documentation site](http://blueprintjs.com/docs/v2/#select/suggest), so there must be something else causing this in your project. Can you share more details like your package.json and lockfile?

**Comment by nikitaulshin** [comment]
I strongly doubt that it's my fault, because the above code is enough to reproduce the error.

I'm using 
    "@blueprintjs/core": "^2.0.0-beta.3",
    "@blueprintjs/select": "^2.0.0-beta.3",

    "@blueprintjs/core": {
      "version": "2.0.0-beta.3",
      "resolved": "https://registry.npmjs.org/@blueprintjs/core/-/core-2.0.0-beta.3.tgz",
      "integrity": "sha512-6YpSMQidGcboiaRCzeSqYUTtvmNJ2j//ILtY7+T/4b85tYWS8XxTeq0adB2erBtoEmUIiv3fP9I7IAj2PJfbmQ==",
      "requires": {
        "@blueprintjs/icons": "2.0.0-beta.3",
        "@types/dom4": "1.5.20",
        "classnames": "2.2.5",
        "dom4": "1.8.5",
        "normalize.css": "7.0.0",
        "popper.js": "1.12.9",
        "react-popper": "0.7.5",
        "tslib": "1.9.0"
      }
    },
    "@blueprintjs/icons": {
      "version": "2.0.0-beta.3",
      "resolved": "https://registry.npmjs.org/@blueprintjs/icons/-/icons-2.0.0-beta.3.tgz",
      "integrity": "sha512-+5bj90JPMUftYQnehl0oVWEd7qdw6ApeEa+H6yJ/Am7tZ1J2/PTVzjkEM9huy42qGj3/RGMj9oH3WNdUlqrIag==",
      "requires": {
        "classnames": "2.2.5",
        "tslib": "1.9.0"
      }
    },
    "@blueprintjs/select": {
      "version": "2.0.0-beta.3",
      "resolved": "https://registry.npmjs.org/@blueprintjs/select/-/select-2.0.0-beta.3.tgz",
      "integrity": "sha512-Gz45k1Bo6yqHRP3l75yj0JxBsSdKRVXOMo79qXxong98F/Qr5b+7Gb+s27KrJlnEoU22RA/tKishHq3RRAErIA==",
      "requires": {
        "@blueprintjs/core": "2.0.0-beta.3",
        "classnames": "2.2.5",
        "tslib": "1.9.0"
      }
    },

**Comment by nikitaulshin** [comment]
I manually installed in the project core-js features and react-transition-group, that solved issue for me! Thanks!
