### ISSUE TITLE
Classes missing "pt-running-text" and "pt-running-text-small"

### ISSUE THREAD

**Issue by jchild3rs** [palantir/blueprint#2047]
### Bug report

- ^2.0.0-beta.3

#### Actual behavior
`pt-running-text` and `pt-running-text-small` are not defined in `Classes`.

#### Expected behavior
Expected `pt-running-text` and `pt-running-text-small` to be defined in `Classes`.

**Comment by giladgray** [comment]
@jchild3rs truth! you open to submitting a PR? there are a number of other constants missing from that file, if you have any interest in hunting them down.
