### ISSUE TITLE
Docs: icons context menu does not dismiss on body click

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#205]
### Bug Report

- __Package version(s)__: 1.0.1

#### Describe the issue:

![image](https://cloud.githubusercontent.com/assets/723999/20437158/ea83e7a2-ad80-11e6-8dc1-da283e94c13d.png)

#### Actual behavior:

The only way to dismiss this menu is by clicking one of the menu items.

#### Expected behavior:

I should be able to click outside the menu to dismiss it.

**Comment by adidahiya** [comment]
Also, the download links are broken because they have the wrong branch -- `develop` instead of `master`

**Comment by cmslewis** [comment]
Seems like the click-anywhere-to-dismiss behavior works now. Not sure what changed or when. I'm fixing the download links though.

**Comment by llorca** [comment]
@cmslewis It works on Chrome and Safari but it's broken on Firefox. On Firefox, right-clicking also scrolls to the bottom of the page instantly 😭

**Comment by llorca** [comment]
Looks unrelated though, it's a wider context menu bug

**Comment by llorca** [comment]
@adidahiya you didn't mention the browser version, but I suspect it's Firefox: https://github.com/palantir/blueprint/issues/273

**Comment by adidahiya** [comment]
I was on Chrome, but somewhere between 1.0 and now, this seems to have gotten fixed... your linked issue is a little different though @llorca

**Comment by cmslewis** [comment]
Reopening because this is actually still happening on Firefox.

**Comment by cmslewis** [comment]
Just looked into this again on every browser, and it appears it _was_ fixed in 1.2.0 (can't repro on blueprintjs.com/docs or on master). Weird. Closing.
