### ISSUE TITLE
Unable to import Blueprint 2 in LESS through webpack

### ISSUE THREAD

**Issue by kaiyoma** [palantir/blueprint#2057]
### Bug report

- __blueprint version__: 2.0.0-beta.3
- __webpack version__: 3.10.0

#### Steps to reproduce

I also posted about this [here](https://stackoverflow.com/questions/48531621/how-do-you-import-blueprint-2-in-less-through-webpack) but haven't heard anything.

The [Blueprint docs](http://blueprintjs.com/docs/v2/#blueprint.npm-installation) say to use this:

```
@import "~@blueprintjs/core";
```

However, if I try that, I get this error from webpack:

```
Can't resolve '@blueprintjs/core.less'
```

#123 deals with similar issues and a lot of people suggested using this:

```
@import "~@blueprintjs/core/dist/blueprint.css";
```

webpack doesn't like that either:

```
Module not found: Error: Can't resolve '@blueprintjs/core/dist/blueprint.css'
```

Looking in the `dist/` directory, I can see that there's only a JS file in there:

```
$ ls node_modules/\@blueprintjs/core/dist/
core.bundle.js
```

After some trial and error, I found that this works:

```
@import "~@blueprintjs/core/lib/css/blueprint.css";
```

But this doesn't seem right to me. Also, none of the icons are loaded via this method.

What's the correct way to do this?

**Comment by adidahiya** [comment]
Icons are not included in blueprint core anymore; there's a new package called `@blueprintjs/icons`.

```less
@import "~@blueprintjs/core/lib/css/blueprint.css";
```

this is correct. most of the built assets moved from `/dist/` to `/lib/`.

**Comment by kaiyoma** [comment]
Ah, okay, I don't think that's in the docs anywhere. It looks like your v2 docs don't reflect some of the changes that have been made since v1.

For posterity:

1. Both `@blueprintjs/core` and `@blueprintjs/icons` need to be installed.
2. In your LESS, import both Blueprint stylesheets:

```less
@import '~@blueprintjs/core/lib/css/blueprint.css';
@import '~@blueprintjs/icons/lib/css/blueprint-icons.css';
```

3. Make sure to add appropriate loaders to your webpack configuration (for LESS/CSS files and the icon fonts).
