### ISSUE TITLE
Blueprint 2 docs don't open in IE11

### ISSUE THREAD

**Issue by kaiyoma** [palantir/blueprint#2059]
### Bug report

- __Browser and OS versions__: IE11 on Windows 10

#### Steps to reproduce

1. Try to open the v2 docs: http://blueprintjs.com/docs/v2/

#### Actual behavior

Nothing loads and the page is completely blank. The console reveals a syntax error due to a fat-arrow function in the JS that's being delivered to the browser, but I don't think IE11 can handle ES6 syntax.

**Comment by kaiyoma** [comment]
BTW, the v1 docs don't work so well either. A lot of the links in the left column don't work and clicking on a search result (when filtering in the input at the top of the page) doesn't do anything. It looks like the URL changes, but there's no actual navigation.

**Comment by giladgray** [comment]
@kaiyoma as an IE user yourself, do you have any insight into why the docs are so darn borked on IE11? perhaps you've come across issues like this in your travels?

**Comment by kaiyoma** [comment]
I think you guys just have some JS errors. When I open the IE console and load the v1 docs, I get this error message:

```
Unable to set property 'scrollTop' of undefined or null reference
```

That would explain why clicking the links changes the URL but doesn't actually scroll the page. The JS delivered to the browser is minified, so unfortunately I don't think I can be any more help here, but if you have access to your source, it should be easy to track down the bad reference.

**Comment by giladgray** [comment]
i'm seeing IE syntax errors due to arrow functions and shorthand objects, which is incredibly obnoxious to fix as it goes all the way down to dependencies.
