### ISSUE TITLE
time to introduce Responsive (to support small devise)

### ISSUE THREAD

**Issue by yoosuf** [palantir/blueprint#2063]
Things are moving ahead and it is better to introduce Responsive design for these gorgeous components.

**Comment by adidahiya** [comment]
Please see the first question in the FAQ: https://github.com/palantir/blueprint/wiki/Frequently-asked-questions

We are open to supporting responsive features for certain components, and if there are specific ones you're interested in, we'd be willing to take a look, but an umbrella issue for overall responsiveness is not really helpful for request tracking purposes.

**Comment by yoosuf** [comment]
@adidahiya that means not around the corner.
