### ISSUE TITLE
iconName ⇒ icon, accept JSX

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2066]
refactor `iconName?: IconName` props to `icon?: IconName | JSX.Element` to allow for custom icon components. the `IconName` shorthand will render a Blueprint `<Icon iconName />`.

also, don't forget to use 20px icon in `Icons` download menu: 
<img width="277" alt="screen shot 2018-02-01 at 3 42 34 pm" src="https://user-images.githubusercontent.com/23030180/35688268-b3ed07e4-0768-11e8-9786-5b152b2ac327.png">

**Comment by giladgray** [comment]
@adidahiya API question. how should I implement this new `icon` prop type in the various components that support it? there are at least a dozen such components.

1. inline ternary every time: 
    ```jsx
    {typeof icon === "string" ? <Icon iconName={icon} /> : icon}
    ```
1. interpolate function, exported next to `Icon` component: 
    ```jsx
    {iconOrElement(this.props.icon)}
    ```
1. SFC, exported next to `Icon` component: 
    ```jsx
    <IconOrElement icon={this.props.icon} />
    ```
1. `Icon` takes `icon` prop and maybe does a pass-through render: 
    ```jsx
    <Icon icon={this.props.icon} />
    ```

I started with (2) because it seems the most efficient but (4) requires the smallest code change.

**Comment by adidahiya** [comment]
(4) looks pretty attractive as long as it doesn't break TS autocompletion on the string literal union
