### ISSUE TITLE
[Core] Page grows downwards while editing EditableText

### ISSUE THREAD

**Issue by alxmiron** [palantir/blueprint#2083]
### Bug report

- blueprintjs/core v1.35.1
- Chrome v64

#### Steps to reproduce

1. Add many lines to EditableText
1. Keep EditableText focused. Scroll down to page bottom.

#### Actual behavior

There is unexpected free space under page content

#### Expected behavior

Page bottom stays as usual 

![feb-05-2018 20-34-11](https://user-images.githubusercontent.com/10484318/35822172-03f843a4-0ab4-11e8-8977-a74b21897192.gif)

**Comment by giladgray** [comment]
cannot reproduce on 2.0 docs site.

**Comment by alxmiron** [comment]
@giladgray I can reproduce it on 2.0 docs site. The inserted text must have bigger height than the page itself. Try with 40 paragraphs from https://uk.lipsum.com/

**Comment by giladgray** [comment]
@alxmiron i cannot reproduce this on the v2 site

**Comment by giladgray** [comment]
ah yes i see this now. probably the span with the actual text is way too big.

**Comment by giladgray** [comment]
cannot reproduce on latest site.
