### ISSUE TITLE
Disabled button inside a popover can still close the popover

### ISSUE THREAD

**Issue by kaiyoma** [palantir/blueprint#2091]
### Bug report

- __Package version(s)__: 2.0.0-beta.3
- __Browser and OS versions__: Chrome 64 on Windows 10

#### Steps to reproduce

1. Render a popover with a Button inside
2. Set the `pt-popover-dismiss` class on the Button and also `disabled={true}`

#### Actual behavior

The button appears to be disabled, the mouse cursor changes when hovering over the button, but clicking causes the popover to close.

#### Expected behavior

The button should be disabled, the mouse cursor should change when hovering over the button, and clicking should do nothing.

According to the [Blueprint Button docs](http://blueprintjs.com/docs/v2/#core/components/button.javascript-api):

> Button uses the native disabled attribute on the <button> tag so the browser disables all interactions ...

If all interactions are being disabled, how does clicking cause the popover to close?

**Comment by giladgray** [comment]
@kaiyoma perhaps remove the `pt-popover-dismiss` class from the disabled button?
