### ISSUE TITLE
Popover/tooltip inside a popover doesn't work well

### ISSUE THREAD

**Issue by kaiyoma** [palantir/blueprint#2092]
### Bug report

- __Package version(s)__: 2.0.0-beta.3
- __Browser and OS versions__: Chrome 64 on Windows 10

#### Steps to reproduce

1. Have a popover which contains a target for another popover or a tooltip.

#### Actual behavior

If you click inside the second popover, both popovers close. If you use a tooltip instead, the tooltip opens but doesn't close when it should; also, everything closes if you click inside the tooltip.

#### Expected behavior

Everything should behave rationally.

**Comment by giladgray** [comment]
@kaiyoma have you seen #2030? this might have already been fixed, though we haven't cut a release containing it yet.

**Comment by kaiyoma** [comment]
Yes, that sounds like the same issue, though it's unclear if it will address the tooltip-within-a-popover problems I was seeing also. In that case, I'm seeing a problem simply with hovering (no clicking).

I'm happy to try this again after the next release. Any ETA on that?
