### ISSUE TITLE
[popover] Width control for popover content

### ISSUE THREAD

**Issue by alxmiron** [palantir/blueprint#2094]
Hello

Are there any options to align popover content width with popover target width (see attachment)? I think it's pretty common UI pattern for dropdowns.

<img width="787" alt="screenshot at feb 06 20-35-08" src="https://user-images.githubusercontent.com/10484318/35877275-8e211ac8-0b7d-11e8-8290-eff9b46b9fab.png">

**Comment by giladgray** [comment]
@AlexMarvelo there's no built-in support for such a thing (though I've considered adding it, may happen at some point). Popovers with `usePortal={false}` (`inline={true}` in 1.x) can easily be styled with a small amount of custom CSS* to inherit the width of the target as they live inside the same container.

\* - mostly slapping `width: 100%` on a `.pt-popover` and `.pt-transition-container` and making the wrapper `display: block`

**Comment by TheTourer** [comment]
> * - mostly slapping width: 100% on a .pt-popover and .pt-transition-container and making the wrapper display: block

I tried this, and the popover is then 100% the width of the body, not the parent. Any idea what could be going wrong?

**Comment by alxmiron** [comment]
Set `inline={true}`

**Comment by giladgray** [comment]
`inline={true}` becomes `usePortal={false}` in 2.0+

**Comment by adidahiya** [comment]
This is pretty close to the request in #2956, which has more info, so I'm going to close this out as a duplicate
