### ISSUE TITLE
[core] Using Hotkeys breaks with react-hot-loader

### ISSUE THREAD

**Issue by benhjames** [palantir/blueprint#2095]
### Bug report

The line here causes projects that use `react-hot-loader` to fall over:

https://github.com/palantir/blueprint/blob/57e66a7f884f7ea49dd47caa92bf5c69a9e53e42/packages/core/src/components/hotkeys/hotkey.tsx#L85

i.e. this is always false whether or not the instance is actually an instance of `Hotkey`, because `react-hot-loader` proxies the component so it fails the equality check as described here:

https://github.com/gaearon/react-hot-loader/tree/next#checking-element-types
https://github.com/gaearon/react-hot-loader/tree/master#checking-element-types

Ultimately it means that hotkeys are never registered! 😱

There are a few solutions outlined on the pages above - which do you like best? 🙂 I can make a PR!

- __Package version(s)__: 2.0.0-beta.3

**Comment by giladgray** [comment]
@benhjames both of those`const HotkeyType = <Hotkey {req'd props} />.type` seems quite reasonable! second choice would be some `isHotkeyType` flag. can't use that `react-hot-loader` function as it's not a dependency (and shouldn't be).

we do element type checks in a few places (I know `Popover` has a check for `Tooltip` children). perhaps you could write a util function `isElementType(expected, actual)` to encapsulate this logic in one place?

**Comment by benhjames** [comment]
Sure thing - will get on it!

**Comment by benhjames** [comment]
Sorry - I completely missed a couple more instances in the `table` package - will try and get around to this when I get a free moment!

**Comment by mmoutenot** [comment]
@benhjames you're a hero. Thank you

**Comment by mmoutenot** [comment]
@benhjames seems like you're a bit busy. If it doesn't look like you'll get to it in the next few weeks, I'm happy to help out. Let me know

**Comment by benhjames** [comment]
Hey @mmoutenot - sorry - I think it's best if you could take this on!

See here for some of the work https://github.com/benhjames/blueprint/commit/93983c427f0147d788de807ccc1cf3566862d378
