### ISSUE TITLE
Gatsby Error with DatePicker

### ISSUE THREAD

**Issue by tobilen** [palantir/blueprint#2100]
### Bug report

- __Package version(s)__: @blueprintjs/datetime 1.25.3

#### Steps to reproduce

1. Import DatePicker in gatsby installation (version 1.9.158):
```jsx
import React from 'react'

import { DateInput } from '@blueprintjs/datetime';

const SecondPage = (props) => {
	return (
	  <div>
			<DateInput />
	  </div>
	);
}

export default SecondPage
```
2. Navigate to page
3. Upon trying to open the `DatePicker`, an error will be thrown:
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Blueprint.DatePicker`.
```

#### Actual behavior

It appears that since webpack 1 (which gatsby uses) has issues with asterisk imports, the `import * as ReactDayPicker from 'react-day-picker` import breaks when trying to render it as component.

#### Expected behavior

Renders datepicker correctly.

In action:
![gatsby-error](https://user-images.githubusercontent.com/8217788/35939555-c7fa7d46-0c4c-11e8-898c-d8e62bc3a653.gif)

**Comment by giladgray** [comment]
@tobilen this sounds like an environment incompatibility, so there's not much to be done from the blueprint side: we can't _not_ use that `import * as` statement. please encourage Gatsby to upgrade to webpack 3 or 4, as the recent versions are freaking great and totally worth it.

**Comment by giladgray** [comment]
fix belongs on the gatsby side.
