### ISSUE TITLE
[table] column filter

### ISSUE THREAD

**Issue by jewway** [palantir/blueprint#2111]
Hi everyone,  
this is great project,  have any suggestion to implement  column filter feature ? 
![image](https://user-images.githubusercontent.com/3501899/35963743-a611d70c-0cf0-11e8-9706-3640c373f3e2.png)

**Comment by ulziibay** [comment]
I am wondering what was the decision or resolution on this? Is it going to be supported or not?

**Comment by cramatt** [comment]
Any updates here? Sorting (supported) and filtering (question here) are pretty common table interactions, so it would be nice to know if Blueprint plans to support this or not.
