### ISSUE TITLE
[Table component] Customize nested headers

### ISSUE THREAD

**Issue by archerchiu** [palantir/blueprint#2112]
Hi,

We would like to customize nested headers of table component. Had anyone do the same thing?
![image](https://user-images.githubusercontent.com/2604264/35964559-0b438bbe-0cf3-11e8-970a-b62ef08c50f2.png)

Thanks

**Comment by giladgray** [comment]
@archerchiu the table does not support merged cells like your screenshot, so I don't think this is possible?

**Comment by archerchiu** [comment]
@giladgray thanks for your reply. I found the #1691 discussion, we are going to follow such issues. Thanks anyway.
