### ISSUE TITLE
Add ability to have a minimal cancel button in Alert component

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2121]
I do not see support for adding a className to the buttons inside of an alert. Throughout our app we usually have cancel buttons minimal. It would be great to be able to do this inside of alerts as well.

**Comment by giladgray** [comment]
This is not supported by `Alert`. The component presents a very particular
UI. Minimal buttons would disappear into the background, presenting a
suboptimal UX.

Use `Dialog` to build your own alert if you really want this.
