### ISSUE TITLE
user-select needs vendor prefixing

### ISSUE THREAD

**Issue by reiv** [palantir/blueprint#2122]
There are several uses of the `user-select` property which do not take effect without vendor prefixing in certain browsers; for example, sliders in Firefox after dragging the handle:

![slider](https://user-images.githubusercontent.com/205631/36079393-8cee2b10-0f82-11e8-833e-7d6adca9eed8.png)

 According to [this compatibility chart from MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#Browser_compatibility) no browser other than Chrome supports the unprefixed version yet. Adding `-webkit-user-select` should satisfy most cases.

**Comment by giladgray** [comment]
@reiv seems legit. got a moment to submit a fix?

**Comment by adidahiya** [comment]
postcss should be doing this for us; we shouldn't be writing vendor prefixes by hand.

**Comment by giladgray** [comment]
*autoprefixer. is it, though? maybe we need to enable a feature.

**Comment by reiv** [comment]
Correct me if I'm wrong, but looking at the [sass-compile](https://github.com/palantir/blueprint/blob/f77e4f7fc69670f7e733a7b97d46efda75eb5bd9/packages/node-build-scripts/sass-compile#L11) script, postcss actually isn't in the build pipeline?

**Comment by adidahiya** [comment]
postcss runs through the webpack build step: https://github.com/palantir/blueprint/blob/f77e4f7fc69670f7e733a7b97d46efda75eb5bd9/packages/webpack-build-scripts/webpack.config.base.js#L84

**Comment by giladgray** [comment]
@adidahiya only docs-app uses that build script. i think @reiv is right -- postcss is _not_ included in the regular blueprint*.css builds that use `sass-compile`.

**Comment by adidahiya** [comment]
I guess we could add an additional `dist/blueprint.css` file in the NPM package which does run postcss... but it's not a high priority for us. I like how our current setup works, where we just run postcss once at the end wherever we bundle our applications with webpack.
