### ISSUE TITLE
Button alignment within File upload is broken

### ISSUE THREAD

**Issue by kudigaracoder** [palantir/blueprint#2130]
### Bug report

- __Package version(s)__: 2.0.0-rc.1
- __Browser and OS versions__: macOS 10.13.2, Safari 11.0.2 / Chrome 64.0.3282.167 / Firefox 58.0.2

#### Steps to reproduce

1. Button alignment within the input field is broken in v2.

#### Actual behavior

<img width="870" alt="screen shot 2018-02-14 at 12 11 47 pm" src="https://user-images.githubusercontent.com/3305383/36190965-0295033e-1181-11e8-9aa4-f7317726889f.png">

#### Expected behavior

Button should be aligned proportionately.

**Comment by adidahiya** [comment]
Good catch. I can repro this in Chrome as well.

**Comment by giladgray** [comment]
oh yeah def missed this in the flex stuff
