### ISSUE TITLE
Allow esc key to hide multiselect options

### ISSUE THREAD

**Issue by jhudson8** [palantir/blueprint#2135]
Clicking on a canvas element will not hide the multiselect options.  If most of the page is a canvas element this makes things difficult.

It would be great if the  `esc` key would hide the multiselect menu.  I think it would be fairly simple (although I haven't been in the code much)

Handle key down event to detect when escape key is clicked
https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/select/multiSelect.tsx#L140

Set state `isOpen` to `false` and blur the input field

Thanks

**Comment by giladgray** [comment]
oh yeah seems it's trying to close on escape (from `Popover`), but the input focus re-opens it. eas to fix, as you suggested above.

**Comment by danielbh** [comment]
This is very straightforward as you said. You can just put a `this.input.blur()` [here](https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/select/multiSelect.tsx#L236).  However, I'm having trouble creating test coverage. What I was thinking was just to put a test spy on `onBlur`, but I'm having trouble accessing it. What do you recommend?

**Comment by giladgray** [comment]
@danielbh the `select` package does not have coverage requirements so don't bother too hard with tests. would love to see your change, please push it up to a branch and set up CircleCI!
