### ISSUE TITLE
Uncontrolled support for Slider component

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2136]
Hey there,

I'm trying to use the <Slider/> component in an uncontrolled manner. I only want to modify my state in the onRelease callback. I'm using the slider like so: 

```
<Slider
          onRelease={val => {
            this.setState({ charWidthInLinearView: val });
          }}
          renderLabel={false}
          stepSize={0.01}
          initialValue={10}
          max={16}
          min={0}
        />
```

Unfortunately the handle does not seem to show up in the correct spot (probably because I'm not providing a `value` prop.

![image](https://user-images.githubusercontent.com/2730609/36233075-2354141c-1199-11e8-9508-a84a081cb5e6.png)

 It would be great if I could use this component like I'm attempting to in an uncontrolled manner and have it manage its internal state if not passed an explicit value. Is doing so possible or was the 
Slider not set up to work like that?

Thanks!

**Comment by tnrich** [comment]
As a follow up, I see that you write this in the docs: 

> Slider is a controlled component, so the value prop determines its current appearance. Provide an onChange handler to receive updates and an onRelease handler to determine when the user has stopped interacting with the slider.

In my use case it would be nice to have an uncontrolled version as well. So maybe this should be a feature request instead of a bug.

**Comment by giladgray** [comment]
@tnrich as you noted, `Slider` does not support uncontrolled usage (mainly cuz it's much easier, and typically you're gonna listen to it anyway, so just pass `value` down).

further, `initialValue` is not the same as `defaultValue` (or we would have called it that). rather, it determines "where the fill starts from." so `initialValue={10}` causes the blue fill to stretch from 10 to the handle (which is at 0). so your screenshot is actually the expected behavior.

**Comment by tnrich** [comment]
For anyone who wants an uncontrolled slider I ended up just wrapping the slider like so: 

```
class UncontrolledSlider extends React.Component {
  state = { value: 0 };
  componentWillMount() {
    const { initialValue } = this.props;
    this.setState({
      value: initialValue
    });
  }
  render() {
    const { value } = this.state;
    const { initialValue, ...rest } = this.props;

    return (
      <Slider
        {...{ ...rest, value }}
        onChange={value => {
          this.setState({ value });
        }}
      />
    );
  }
}
```

**Comment by giladgray** [comment]
ok sure you just wrapped it to hide the value state. seems wholly overkill but you do you 👍

**Comment by tnrich** [comment]
In my case it was controlling the zoom level of a fairly heavy to render
component so having it be uncontrolled was necessary to stop the component
from rendering onChange

**Comment by giladgray** [comment]
Ok interesting use case! New respect for uncontrolled usage.
