### ISSUE TITLE
NumericInput doesn't respond to continuous mouse down input

### ISSUE THREAD

**Issue by kaiyoma** [palantir/blueprint#2146]
### Bug report

- __Package version(s)__: 2.0.0-beta.3
- __Browser and OS versions__: Chrome 64 on Windows 10

#### Steps to reproduce

Click the up/down arrow button for a `NumericInput` component and hold down the mouse button.

#### Actual behavior

Nothing happens until you release the mouse button.

#### Expected behavior

The value in the input should change rapidly while the mouse button is held down.

**Comment by giladgray** [comment]
yes this feature is not implemented, but it would be sweet! happy to accept a PR. IIRC, one of the DOM key events (down or press) will fire continuously when held so we can just use that.

**Comment by giladgray** [comment]
oh my comment was about holding the keys, sorry. there's no such continuous event for the mouse, so we'd have to implement it manually with a flag and interval timer 😢
