### ISSUE TITLE
Docs display bug in sidebar

### ISSUE THREAD

**Issue by garritfra** [palantir/blueprint#2148]
### Bug report

- __Package version(s)__: v1.35.1
- __Browser and OS versions__: Chrome Version 64.0.3282.140, macOS 10.13.3

#### Steps to reproduce

1. Open the docs

#### Actual behavior

When clicking on a link in the docs sidebar, the item that gets selected is the one above the actual item i want to view. When clicking on the same item again, the item above the previously selected item gets selected and so on.

#### Expected behavior
expected the selected item to be the one i clicked on

**Comment by garritfra** [comment]
I can actually try to fix this myself as i am trying to contribute to open source. I just wanted to document this issue

**Comment by giladgray** [comment]
this is already fixed on develop, we just haven't deployed the site in a while 👍

**Comment by giladgray** [comment]
you can verify the behavior is fixed by trying out a preview link on any recent PR, like this one: https://github.com/palantir/blueprint/pull/2147#issuecomment-366408683

**Comment by garritfra** [comment]
My bad!:)
