### ISSUE TITLE
Is there a way to inline a set of label / text boxes?

### ISSUE THREAD

**Issue by theogravity** [palantir/blueprint#215]
I'd like to inline text input all on one line. Is there a prescribed way to do this? I only see examples for radio / check boxes.

eg how `pt-inline` does `display: inline-block` for radio / checkboxes, I'd like to do that too for text input

**Comment by adidahiya** [comment]
As with most questions about layout using Blueprint, I think flex box is your best bet here. In fact we should probably update all inline form component layouts to use flex box. This deserves better docs.

**Comment by giladgray** [comment]
closing in favor of #737
