### ISSUE TITLE
Issue with icon showing up as a square in production

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2152]
Hey there,

I'm hitting a strange issue where the icon I'm trying to add to a div isn't showing up correctly in a compiled version of the code, but works fine while in development. 

Here is the code I'm using:

```js
       <div
              className={
                "ve-clickable-black ve-close-panel-button pt-icon-menu"
              }
              onClick={showTabRightClickContextMenu}
              style={{
                background: "white",
                padding: "4px",
                top: "5px",
                right: "0px",
                position: "absolute"
              }}
            />
```

And here it is working: 

![image](https://user-images.githubusercontent.com/2730609/36363412-bf95ad8a-14f1-11e8-8030-44804cb3317f.png)

And here it is embedded in a production site: 
![image](https://user-images.githubusercontent.com/2730609/36363398-958cebca-14f1-11e8-8718-f9e2776b0db9.png)

For some reason it just renders as a blank square. Other icons (not used in the <div> form but using <Button> or <Icon> seem to work still. Any help troubleshooting this would be appreciated. I'm not sure why this would be happening or how to fix it so I'm willing to try anything. 

Thanks!

**Comment by giladgray** [comment]
I suspect it's not working in prod for one of two reasons:

1. Font files won't load (should be easy to confirm by request error log in
console)
2. Missing size class (and span tag): `span.pt-icon-standard`

Note that in 2.0 our `Icon` component now renders SVGs instead of using the
font.

>
>

**Comment by tnrich** [comment]
Hey @giladgray thanks for getting back to me. It appears changing the div to a span fixes my issue. Great! Thank you!
