### ISSUE TITLE
DateInput ESC key handler regression

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#2155]
had to skip a unit test in https://github.com/palantir/blueprint/pull/2154 because the "ESC key on input to close popover" functionality broke in DateInput somewhere during the merge into 2.0 code

**Comment by adidahiya** [comment]
@mud I seem to have broken your feature when I merged `release/1.x` into `develop`, sorry about that 😢 

would you have some time to take a look and debug? Search for `https://github.com/palantir/blueprint/issues/2155` in the codebase and you'll find the `it.skip` skipped unit tests.

**Comment by mud** [comment]
Sure thing. Looks like react-day-picker was bumped and the tabindex behavior changed a bit. I'll work on a PR.
