### ISSUE TITLE
Warning when using other components in MenuItem

### ISSUE THREAD

**Issue by eleveurdechevres** [palantir/blueprint#2158]
### Bug report

- __Package version(s)__: 1.35.1
- __Browser and OS versions__: Windows 7 + Chrome/Firefox, or Redhat7 + firefox 58.0.2

#### Steps to reproduce

1. Create a ContextMenu with MenuItem
2. Create Components inside a MenuItem like this :

```
import {ContextMenu, Menu, MenuItem, Button } from "@blueprintjs/core"

...

showContextMenu = (x, y) => {
     var menu = (
     <Menu>
          <MenuItem text="add something">
               <input defaultValue="someting" onChange={(event) => {this.myValue = event.target.value}}/>
               <Button text="add" onClick={() => {this.handleAddSomething()}}/>
          <MenuItem>
     </Menu>
     );

     ContextMenu.show( menu, {left: x, top: y}, () => {}) 
}
```

#### Actual behavior

The behaviour is correct : a submenu item opens with an input and a button. The value is correctly used by my handler.

But at the first time I open this submenu, I have a React Warning : 
Warning: React does not recognize the `submenuViewportMargin` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `submenuviewportmargin` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input
    in ul (created by Blueprint.Menu)
    in Blueprint.Menu (created by Blueprint.MenuItem)
    in div (created by Blueprint.Popover)
    in div (created by Blueprint.Popover)
    in div (created by Blueprint.Popover)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup (created by Blueprint.Overlay)
    in span (created by Blueprint.Overlay)
    in Blueprint.Overlay (created by Blueprint.Popover)
    in span (created by Blueprint.Popover)
    in Blueprint.Popover (created by Blueprint.MenuItem)
    in li (created by Blueprint.MenuItem)
    in Blueprint.MenuItem
    in ul (created by Blueprint.Menu)
    in Blueprint.Menu
    in div (created by ContextMenu)
    in div (created by Blueprint.Popover)
    in div (created by Blueprint.Popover)
    in div (created by Blueprint.Popover)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup (created by Blueprint.Overlay)
    in div
printWarning @ undefined@undefined:7
warning @ undefined@undefined:7
validateProperty$1 @ undefined@undefined:7
warnUnknownProperties @ undefined@undefined:7
validateProperties$2 @ undefined@undefined:7
validatePropertiesInDevelopment @ undefined@undefined:7
setInitialProperties$1 @ undefined@undefined:7
finalizeInitialChildren @ undefined@undefined:7
completeWork @ undefined@undefined:7
completeUnitOfWork @ undefined@undefined:7
performUnitOfWork @ undefined@undefined:7
workLoop @ undefined@undefined:7
callCallback @ undefined@undefined:7
invokeGuardedCallbackDev @ undefined@undefined:7
invokeGuardedCallback @ undefined@undefined:7
renderRoot @ undefined@undefined:7
performWorkOnRoot @ undefined@undefined:7
performWork @ undefined@undefined:7
requestWork @ undefined@undefined:7
scheduleWorkImpl @ undefined@undefined:7
scheduleWork @ undefined@undefined:7
enqueueSetState @ undefined@undefined:7
Component.setState @ undefined@undefined:7
Popover.setOpenStateDirectly @ undefined@undefined:7
Popover.setOpenStateByPropCallback @ undefined@undefined:7
(anonymous) @ undefined@undefined:7
setTimeout (async)
AbstractComponent.setTimeout @ undefined@undefined:7
Popover.setOpenStateByPropCallback @ undefined@undefined:7
Popover._this.handleMouseEnter @ undefined@undefined:7
callCallback @ undefined@undefined:7
invokeGuardedCallbackDev @ undefined@undefined:7
invokeGuardedCallback @ undefined@undefined:7
invokeGuardedCallbackAndCatchFirstError @ undefined@undefined:7
executeDispatch @ undefined@undefined:7
executeDispatchesInOrder @ undefined@undefined:7
executeDispatchesAndRelease @ undefined@undefined:7
executeDispatchesAndReleaseTopLevel @ undefined@undefined:7
forEachAccumulated @ undefined@undefined:7
processEventQueue @ undefined@undefined:7
runEventQueueInBatch @ undefined@undefined:7
handleTopLevel @ undefined@undefined:7
handleTopLevelImpl @ undefined@undefined:7
batchedUpdates @ undefined@undefined:7
batchedUpdates @ undefined@undefined:7
dispatchEvent @ undefined@undefined:7

#### Expected behavior

Same behaviour, without the warning

**Comment by adidahiya** [comment]
This is fixed in 2.x. Since it's only a warning and not an error, I don't think we'll backport it to 1.x.

**Comment by eleveurdechevres** [comment]
Ok thank you very much for your answer.I will try 2.x when it will be possible
