### ISSUE TITLE
Select causes dialog to close

### ISSUE THREAD

**Issue by rheinheimer** [palantir/blueprint#2159]
### Bug report

- __Package version(s)__: @blueprintjs/select@2.0.0-rc.2
- __Browser and OS versions__: Chrome (latest, Ubuntu)

#### Steps to reproduce

1. Create a `Dialog` with a `Select` component in it, the latter from `@blueprintjs/select`.
2. Try to use the Select.

#### Actual behavior

The dialog disappears

#### Expected behavior

The dialog should not disappear. I use `Select` with no problem outside a dialog, but no luck within a dialog. There is no problem with Select from `@blueprintjs/labs`.

**Comment by adidahiya** [comment]
try `popoverProps={ usePortal: true }` to make the Select inline inside the Dialog. this is typically required for nested overlays like dialog & popover.

**Comment by rheinheimer** [comment]
Didn't work. This is a very low priority of course since the Labs version works, but still worth noting. Thanks anyway

**Comment by giladgray** [comment]
i'll bet this is related to #2092, something about nested portals.

@rheinheimer did you put `usePortal: true` on the `Select`? that's the one that should not use a portal.

**Comment by k-simons** [comment]
@giladgray  I tried `usePortal: true` on the popover props of the Select and it did not solve the issue

**Comment by giladgray** [comment]
@k-simons definitely want `usePortal: false` on the inner guy, my bad above

**Comment by k-simons** [comment]
@giladgray Perfect that worked

**Comment by rheinheimer** [comment]
`popoverProps={ usePortal: true }` did the trick. Thanks!
