### ISSUE TITLE
Missing docs for CSSTransition, Intent

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#2162]
The docs seem to be missing references to enums like `Intent` and `CSSTransition`. Have I just missed these? I tried the search feature, but that turned up no results.

**Comment by giladgray** [comment]
which docs? v2 docs now feature clickable links for things like `Intent`. 

`CSSTransition` comes from an [external library](https://reactcommunity.org/react-transition-group/#CSSTransition), so the docs can be found there. (it's also not a part of the public API so you can't interact directly with the `CSSTransition` elements we render, therefore not necessary to document).

**Comment by giladgray** [comment]
links in v2 docs: ![image](https://user-images.githubusercontent.com/464822/36876955-8813184c-1d6c-11e8-821e-6049e810b0e6.png)

**Comment by adidahiya** [comment]
Closing as this is fixed in both v1 and v2 docs.
