### ISSUE TITLE
Collapse isOpen is not updating always

### ISSUE THREAD

**Issue by Ciantic** [palantir/blueprint#217]
If one programmatically changes Collapse isOpen property quickly twice in a row, it seems to loose the plot. E.g. if you hook the isOpen to value that is updated quickly back and forth.

I think it has something to do with the timeouts, they should be cleared in few more places.

**Comment by adidahiya** [comment]
Seems reasonable that less-than-perfect handling of timeouts may be causing such bugs.

To get a sense of priority, since I haven't seen this bug before: How often do you encounter this issue in a real (not contrived) application? How important is the fix?

**Comment by Ciantic** [comment]
It happened on each refresh for me as I had hooked the isOpen to url fragment. My app did multiple redirects in succession and I noticed the collapse isOpen is not updating.

I don't think it's critical I found a workaround for my case, but if someone else encounters this, it might be worth investigating.

**Comment by leebyp** [comment]
@Ciantic My hunch is that this should fix the problem (from the timeouts as discussed above): https://github.com/palantir/blueprint/pull/415

Happy to take another look if that still doesn't solve the issue after merging.
