### ISSUE TITLE
Basic support for building on Windows

### ISSUE THREAD

**Issue by reiv** [palantir/blueprint#2172]
Currently there are a few things in `package.json` (top-level and subpackages) that prevent getting a build going on Windows:

1. use of single quotes instead of double quotes
2. setting environment variables in an npm/yarn command
3. running scripts without specifying an interpreter (`./compile-docs-data`)

1 is a matter of search and replace.
For 2, a common workaround is to use [`cross-env`](https://www.npmjs.com/package/cross-env) to set environment variables.
For 3, the fix is to prepend `node` to the script to execute.

Still can't get `yarn verify` to run without errors, but it's a start: at least the dev server and test commands now work. Would you be open to a PR with these changes?

**Comment by adidahiya** [comment]
Yeah, we'd take a PR for this. Thanks for looking into it.

**Comment by giladgray** [comment]
fixed in #2173
