### ISSUE TITLE
[label] missing space between text and helperText

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2175]
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Chrome 64, macOS Sierra 10.12.6

#### Steps to reproduce

```js
<Label
  text="Username"
  helperText="(blah blah)"
>
  <input autoFocus={true} className="pt-input" type="text" />
</Label>
```
#### Actual behavior

Label= "Username(blah blah)"

#### Expected behavior

Label= "Username (blah blah)"

**Comment by llorca** [comment]
@will-stone we'd gladly take a PR for this if you get a chance!

**Comment by will-stone** [comment]
Looks like @danielbh is on the job but yes, I'm happy to send pull requests. In fact, I nearly did the other day but noticed there were quite a few rules and didn't have time to read them, but I will; I'm now using BluePrint a lot and want to contribute back. If I don't have time to log pull-requests, I will try to log issues first.
