### ISSUE TITLE
Skeleton does not hide icons

### ISSUE THREAD

**Issue by univerio** [palantir/blueprint#2176]
### Bug report

- __Package version(s)__: 1.35.5, 2.0.0-rc.2
- __Browser and OS versions__: Linux, Chrome 64

#### Steps to reproduce

```
<button type="button" class="pt-button pt-skeleton pt-icon-cog" tabindex="-1">Submit</button>
```

#### Actual behavior

![image](https://user-images.githubusercontent.com/1037172/36575951-955bd666-1802-11e8-8a48-4e81bb61d8ff.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/1037172/36575982-be744dc6-1802-11e8-83f9-7accad4775c1.png)

#### Proposed patch

```diff
diff --git packages/core/src/components/skeleton/_skeleton.scss packages/core/src/components/skeleton/_skeleton.scss
index 1b44d320..1d64f8aa 100644
--- packages/core/src/components/skeleton/_skeleton.scss
+++ packages/core/src/components/skeleton/_skeleton.scss
@@ -52,5 +52,16 @@ Styleguide pt-skeleton
   animation: $skeleton-animation;
   pointer-events: none;
   user-select: none;
+
+  // hide icon font icons
+  &[class*="pt-icon-"]::before,
+  [class*="pt-icon-"]::before {
+    color: transparent !important;
+  }
+
+  // hide SVG icons
+  * {
+    visibility: hidden !important;
+  }
 }
 /* stylelint-enable declaration-no-important */
```

Happy to submit a PR.

**Comment by llorca** [comment]
@univerio we'd gladly take a PR for this. Thank you!
