### ISSUE TITLE
NumericInput with `value` set does not behave as Controlled component

### ISSUE THREAD

**Issue by ablakey** [palantir/blueprint#2186]
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Ubuntu 16.04, Chrome 64.0.3282.186

#### Steps to reproduce

1. Create a basic NumericInput component. It can be as simple as this:
```
<NumericInput
  value={1.0}
  onValueChange={v => console.log(v)}
/>
```
2. Type in a different value.
3. Notice that the value does change.

#### Actual behavior

The component freely changes value despite the `value` property being set to a constant.

#### Expected behavior

The component's value shall never change unless the `value` property is changed.

**Comment by ablakey** [comment]
Forgive me if I'm missing something. It looks like NumericInput is simply not implemented to be a controlled component, despite the documentation:

https://github.com/palantir/blueprint/blob/f4e9f758/packages/core/src/components/forms/numericInput.tsx#L180

I don't see anything that enforces that `this.props.value` takes precedence over `this.state.value`

The best I can guess is that it's "controlled" in the sense that `this.props.value` will just override `this.state.value` each re-render. But that does not help us if the component is not being re-rendered. What should happen is that changing the value invokes the `onValueChange` callback, but it should *not* re-render because `state` was changed since `this.props.value` is not `undefined`.

**Comment by benjaminbours** [comment]
👍 I'm facing the same unexpected behaviour. Would be nice and probably not a lot of work to fix it, I Will do it soon if I got some time. This behaviour currently prevent me to implement a cleaner force value to integer, as described [here](https://github.com/palantir/blueprint/issues/1956). Because finally what you push into value, is only the first displayed value in the field, due to the internal re-render described by @ablakey

**Comment by benjaminbours** [comment]
Investigating, I realised that the behaviour is the same with the component [InputGroup](https://github.com/palantir/blueprint/blob/f4e9f758ccf4c7e76a6599d3413733b84587798e/packages/core/src/components/forms/inputGroup.tsx) and this issue has already a duplicate here => #3553
