### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by mmoutenot** [palantir/blueprint#2187]
### Bug report

- __Package version(s)__: master
- __Browser and OS versions__: Chrome, OSX

#### Steps to reproduce

1. visit `http://blueprintjs.com/docs/`

#### Actual behavior

Website is down

#### Expected behavior

Website is up

**Comment by romanr** [comment]
DNS error

**Comment by giladgray** [comment]
Hmm works fine for me, but it's a redirect. Try adding /v2 to the end of the URL to go straight to the latest docs.

**Comment by romanr** [comment]
DNS cannot be resolved. It’s globally down when checked with any website like https://www.websitedown.info/blueprints.com

**Comment by atav32** [comment]
Definitely down in some places / for some people

<img width="614" alt="screen shot 2018-02-27 at 10 08 48 am" src="https://user-images.githubusercontent.com/622185/36746060-3cb69ed6-1ba6-11e8-83a4-a7029ca5dfac.png">

<img width="619" alt="screen shot 2018-02-27 at 10 08 05 am" src="https://user-images.githubusercontent.com/622185/36746064-3f9a767c-1ba6-11e8-882e-88d542963c33.png">

<img width="715" alt="screen shot 2018-02-27 at 10 04 44 am" src="https://user-images.githubusercontent.com/622185/36746079-480dffa4-1ba6-11e8-9355-9ab30dde2083.png">

<img width="743" alt="screen shot 2018-02-27 at 10 05 16 am" src="https://user-images.githubusercontent.com/622185/36746090-5011c9a6-1ba6-11e8-94f6-a5a4f5095570.png">

<img width="803" alt="screen shot 2018-02-27 at 10 06 28 am" src="https://user-images.githubusercontent.com/622185/36746095-540f5672-1ba6-11e8-87cb-8eb8d1a2a572.png">

<img width="1090" alt="screen shot 2018-02-27 at 10 07 42 am" src="https://user-images.githubusercontent.com/622185/36746100-566e1692-1ba6-11e8-94ac-8aa000a4b81d.png">

**Comment by mmoutenot** [comment]
It is accessible for me again!

**Comment by giladgray** [comment]
Glad it's back up :+1:

Our website is hosted on GitHub Pages (see the `master` branch), so there's
not much we could have done anyway!
