### ISSUE TITLE
Question: are these components mobile friendly?

### ISSUE THREAD

**Issue by jeveloper** [palantir/blueprint#219]
Type: Question

trying out the components on safari proved otherwise
Not sure if this framework is best for desktop.

Some components don't react well with touch, some don't work.
Perhaps this isn't the right choice or do you have a tip.

Thanks

**Comment by llorca** [comment]
Not at the moment. So far, we've optimized the interactions for desktop use cases. Some components will work on mobile; the most complex ones won't. If you rely heavily on mobile interactions and are looking for a mobile-first UI toolkit, this may not be for you.

**Comment by adidahiya** [comment]
Check out the README in the repo and FAQ on the wiki.

**Comment by jeveloper** [comment]
Thank you
