### ISSUE TITLE
[Docs] .docs-page element shouldn't have .pt-running-text

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#2190]
`.docs-page` is at the top level of the page and also has `.pt-running-text`. This leads to things like this:
![image](https://user-images.githubusercontent.com/199754/36806547-37bd29c0-1c75-11e8-97cf-e666646fa5e1.png)

Instead, `.pt-running-text` should be applied to individual running paragraphs

**Comment by adidahiya** [comment]
duplicate of https://github.com/palantir/blueprint/issues/2167

**Comment by adidahiya** [comment]
closing in favor of that one
