### ISSUE TITLE
[Trees] Open / close "hinge" animation doesn't feel right

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2194]
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Firefox 58 and latest Chrome, macOS

#### Steps to reproduce

1. Use JavaScript API version of Trees and open close a branch

#### Actual behavior

The caret icon hinges around when opening and closing

#### Expected behavior

I would expect the icon to simply rotate from the centre.

![ezgif-5-059c0e38f0](https://user-images.githubusercontent.com/654103/36907804-7752e63e-1e31-11e8-90b7-8cea2f7ab366.gif)

**Comment by adidahiya** [comment]
This is probably a regression in 2.0, thanks for flagging.
