### ISSUE TITLE
TagInput - Documentation Links no longer valid

### ISSUE THREAD

**Issue by Kamin-Day-CCS** [palantir/blueprint#2195]
### Bug report
On the blueprint JS documentation site, the Example Source Code link is broken for labs/taginput
http://blueprintjs.com/docs/v1/#labs/tag-input

https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/labs-examples/tagInputExample.tsx

#### Actual behavior
404 document not found

#### Expected behavior
Example Source Code on Github

**Comment by adidahiya** [comment]
All the labs links are broken since those components have moved to different packages on develop (2.0). I admit this is a bug, but as a temporary workaround you can navigate to the [release/1.x branch](https://github.com/palantir/blueprint/tree/release/1.x).

**Comment by giladgray** [comment]
fixed in #2237
