### ISSUE TITLE
dateInput.js:251 Uncaught TypeError: parseDate is not a function

### ISSUE THREAD

**Issue by johnthomas00** [palantir/blueprint#2196]
### Bug report

- __Package version(s)__:     
```
    "@blueprintjs/core": "^2.0.0-rc.2",
    "@blueprintjs/datetime": "^2.0.0-rc.2",
```
- __Browser and OS versions__: 
  Chrome Version 64.0.3282.186 (Official Build) (64-bit)
  Windows 10

#### Steps to reproduce

1. Create a `<DateInput />`
1. Try to use

#### Actual behavior

dateInput.js:251 Uncaught TypeError: parseDate is not a function
    at DateInput../node_modules/@blueprintjs/datetime/lib/esm/dateInput.js.DateInput.parseDate (dateInput.js:251)
    at DateInput._this.handleInputBlur (dateInput.js:98)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)

#### Expected behavior

No error

**Comment by giladgray** [comment]
@johnthomas00 did you supply the required `parseDate` prop? this was added in 2.0, see #2117

**Comment by johnthomas00** [comment]
@giladgray Thank you!! I had not, that was it, an oversight on my part.  Thanks again!
