### ISSUE TITLE
Option to prevent duplicate Toasts

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2203]
Hey there,

I'm just wondering if you would be interested in supporting an option to prevent duplicate toast messages from appearing. I think it would be really useful and is also a good candidate for being handled internally because the Toaster system is best set up to know if a duplicate Toast is already being displayed (and it could elongate that toast's display time). 

Thanks!

**Comment by giladgray** [comment]
@tnrich I'm fairly certain your use case is already supported by the `key` option: `toaster.show({ key: "unique", ... })`. Repeated shows with the same key will update a single toast instance.

**Comment by tnrich** [comment]
Ahh interesting thank you I will try it.

**Comment by tnrich** [comment]
Hmm I am not able to get it to work as you're suggesting. Maybe I'm doing something wrong? 

Here's my code: 
```

const toastr = Toaster.create({
  className: "top-toaster",
  position: Position.TOP
});


const generateToast = intent => (message) => {
  
  toastr.show({
    key: message,
    intent,
    message
  }); 
};

if (!window.toastr) window.toastr = {};
if (!window.toastr.success) {
  window.toastr.success = generateToast(Intent.SUCCESS);
}

if (!window.toastr.error) {
  window.toastr.error = generateToast(Intent.DANGER);
}

if (!window.toastr.warning) {
  window.toastr.warning = generateToast(Intent.WARNING);
}

if (!window.toastr.info) {
  window.toastr.info = generateToast(Intent.PRIMARY);
}
```

elsewhere I'm calling: 
```
<Button onClick = ()=>{
	window.toastr.success("Success!")
} />



```

But multiple still show up when I click the button repeatedly. Do you see anything wrong with my code? Thanks!


As a side note, if this does work, it is not at all clear from the docs that this is an option and they should be updated.

**Comment by giladgray** [comment]
@tnrich use a constant for the `key`, not the argument `message` (exactly like the React `key` prop). try `key: intent` in your example code above.

**Comment by tnrich** [comment]
@giladgray doesn't seem to change anything..

**Comment by giladgray** [comment]
oh snap my bad, my code was wrong! always check the docs. 

it's `.show(props, key)`

**Comment by tnrich** [comment]
Hmm still not working.. This is not described in the docs though also: 

![image](https://user-images.githubusercontent.com/2730609/37050241-38c6fc3a-2128-11e8-8ba6-1931f826df4e.png)

**Comment by giladgray** [comment]
ahhh 1.0! i've been talking 2.0 APIs this whole time.

in 1.0, you call `.show()` the first time to get a key and then `.update(thatKey, newProps)` afterwards. it's messy and not fun, which is why we merged `show` and `update` for 2.0: #1962

**Comment by tnrich** [comment]
Aha! Okay interesting.. When is 2.0 going to be stable?

**Comment by giladgray** [comment]
it's been stable since the first RC, feel free to pick it up! we're just polishing rough edges but not planning any more API breaks.

**Comment by giladgray** [comment]
@tnrich success? i suspect this issue is ready to close.

**Comment by tnrich** [comment]
@giladgray this will work for me although seeing it in action, it isn't quite what I had in mind. For example, I would like to be able to display multiple different success messages at the same time, so long as they aren't the same exact message. 

I just want to prevent duplicates from occurring. 

Could I key them using the message to achieve that?

**Comment by giladgray** [comment]
@tnrich sure, that's completely possible through choosing the correct key: one unique key per success message. the message itself would work, though using a full sentence as a key is kinda awkward.

**Comment by giladgray** [comment]
closing as i think you've got the tools you need. feel free to re-open if something is wrong.
