### ISSUE TITLE
Namespaced CSS Classes for text color and tag color

### ISSUE THREAD

**Issue by kevinschaich** [palantir/blueprint#2204]
### Feature Request - Namespaced CSS Classes for text color and tag color

Hoping for some way to directly alter text/tag color via a CSS classname. For example, something along the lines of this (open to suggestions for the class names themselves):

```html
<span class="pt-text-color pt-intent-gold5">Hello World</span>
```

or this:

```html
<span class="pt-tag pt-intent-gold-5">Hello World</span>
```

The current set of 4 `intent-*` colors are rather limiting and it would be awesome to expand this to the [full set of namespaced colors in Blueprint](http://blueprintjs.com/docs/v2/#core/colors). Benefit would be to allow dynamic templating of these colors from string input. For my use case, I'd like to create a dashboard with a text field to inject Blueprint CSS classes to alter the appearance of text (text color/tag color).

**Comment by cmslewis** [comment]
Initial opinion: this API doesn't seem appropriate for Blueprint. Intents are designed to be semantic, opinionated, and restrictive—and therefore perfectly consistent across design system. This API would make it too easy to stray from those standard intents, enabling a veritable text-color free-for-all. 

For instance, the system should make it easy to render "success" text according to the design system's specs. The system should _not_ make it easy to render any version of green text that I want, even if Blueprint offers those colors. That would enable bad practices like:

- Color overload (too many hues)
- Color inconsistency (too many variants of each hue) 
- Poor contrast ratios:
![image](https://user-images.githubusercontent.com/443450/37051765-3c70cdc6-212c-11e8-9c0e-29d29b2f083b.png)
![image](https://user-images.githubusercontent.com/443450/37051799-507ef7ca-212c-11e8-8904-31bc9cbb586d.png)

There might be room for a `pt-intent-{success,warning,danger,primary}`-esque modifiers for standalone text. But we'd need to learn more about the motivating use case.

@kevinschaich can you describe your use case in more detail? (Omit details as needed.)

**Comment by giladgray** [comment]
I fully agree with @cmslewis. We chose to provide **variables** instead of **classes** for all the colors because they're much more flexible: you can use a variable in any CSS property (`color`, `background`, `border`, whatever), but a CSS class would only set specific properties (which is not generally useful here).

This feature is easily achieved in your app with a few lines of custom CSS; it does not belong in Blueprint itself.

**Comment by llorca** [comment]
@will-stone that seems much more reasonable than the previous proposal, although let's have @giladgray chime in quickly before moving forward

**Comment by ejose19** [comment]
Is there any updates on this? Using text that is intent aware is very useful, only workaround I've found in the meanwhile is to use an empty FormGroup with helper text, but honestly it feels more like a hack than Text supporting intent natively
