### ISSUE TITLE
publish the upgrade script

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2214]
currently the upgrade script lives in the root `scripts/` directory, not in a published package: https://github.com/palantir/blueprint/blob/develop/scripts/upgrade-blueprint-2.0.0-rename

this isn't particularly useful for consumers. where should it be published? perhaps in `core 2.0`? or a new short-lived `upgrade` package?

**Comment by adidahiya** [comment]
publish in core 2.0, add it as a binary [with this syntax](https://github.com/palantir/blueprint/blob/2d7f7564ca4528e1d5de00f17ebd9a9e7cd82a24/packages/node-build-scripts/package.json#L8)
