### ISSUE TITLE
Horizontal tab inside vertical tab panel still uses the vertical style class

### ISSUE THREAD

**Issue by hans-permana** [palantir/blueprint#222]
Hi guys,

I encountered an issue when trying to create a horizontal tablist inside a vertical tab panel. Here are the details:

### Environment

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Chromium 53 inside Electron 1.4.7

### Issue

I created a horizontal tab inside one of vertical tab panels. Unfortunately, the inner tabs seemed to inherit the vertical tab style. 

### Actual behavior:

The inner tabs are always forced to use the same tabs on the higher level.

### Expected behavior:

Each individual tabs should be independent of prior styling on the parent elements.

Thank you for an awesome library! Looking forward to hearing from you soon.

**Comment by cmslewis** [comment]
Hi @hans-permana, can you add a screenshot of the issue—and maybe a code snippet? Not quite following your nomenclature.

**Comment by hans-permana** [comment]
Hi @cmslewis, I am sorry for not being clearer. 

I hope this screenshot can help me in describing the issue better :)
![image](https://cloud.githubusercontent.com/assets/7643370/20630872/03b78a0e-b334-11e6-853e-f35bf3913e44.png)

In the screenshot, as you can see there are 2 Tabs being used, one as a child of another (indirectly). What I wanted is for the parent Tablist to be vertical, which it is, and the child Tablist to be horizontal, which is not. I have highlighted the CSS source on why the child Tablist is also vertical despite only "pt-tabs" class name is used. It seems to still adopt the "pt-vertical" class. I do not think this is the intended behaviour. 

I have checked with the generated CSS file and identified where the possible changes should be (have done some experiment as well) 
```
.pt-tabs.pt-vertical .pt-tab-list {
    -webkit-flex-direction: column;
            flex-direction: column;
    -webkit-align-items: flex-start;
            align-items: flex-start; }
.pt-tabs.pt-vertical .pt-tab {
    width: 100%;
    padding: 0 10px; }
.pt-tabs.pt-vertical .pt-tab-indicator-wrapper .pt-tab-indicator {
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    border-radius: 3px;
    background-color: rgba(19, 124, 189, 0.2);
    height: auto; }
.pt-tabs.pt-vertical .pt-tab-panel {
    margin-top: 0;
    padding-left: 20px; }
```

I hope this is more understandable now. And I am looking forward to the fix.

Hans

**Comment by cmslewis** [comment]
Ah okay, I see the problem now. Thanks for clarifying with a screenshot and code snippet! I have a fix for it. @giladgray the fix here will necessarily change the specificity of certain CSS selectors for the tab component. Not sure how strict we want to be with semver here—might want to wait till a major-version bump. Happy to chat more in a PR.
