### ISSUE TITLE
Buggy Tooltip

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2220]
### Bug report

- __Package version(s)__:  2.0.0-rc.2
- __Browser and OS versions__: Chrome 64.0.3282.186, MacOS 10.13.3

![buggy-popover](https://user-images.githubusercontent.com/10415101/37264375-4620c820-256a-11e8-90da-1ca39624af17.gif)

here is a site with a demo of the problem:
https://tgreen7.github.io/blueprint-test/

here is the code:
https://github.com/tgreen7/blueprint-test

**Comment by tnrich** [comment]
I'm seeing an even weirder bug.. Too strange to really believe. In my code if I change the tooltip text from "Hide cut sites" to "Hide features" an infinite loop is hit and my app crashes. 

I'll try to reproduce this in a minimal example, but this has to be one of the strangest bugs I have ever seen..

**Comment by tnrich** [comment]
I'm seeing an even weirder bug.. Too strange to really believe. In my code if I change the tooltip text from "Hide cut sites" to "Hide features" an infinite loop is hit and my app crashes. 

I'll try to reproduce this in a minimal example, but this has to be one of the strangest bugs I have ever seen..

**Comment by tnrich** [comment]
I think mine might be related to #2030 

Has a fix been released for that yet?

**Comment by adidahiya** [comment]
@tnrich yeah, you can trace the tags which include the commit which fixed #2030: https://github.com/palantir/blueprint/commit/ff76c4a8b666073e358167d0ec45b565df30c8a8

**Comment by giladgray** [comment]
@tgreen7 try disabling the `preventOverflow` modifier from popper:
`<Popover modifiers={{ preventOverflow: { enabled: false } }} ... />`

**Comment by tgreen7** [comment]
@giladgray Thanks so much! That did it.

**Comment by tgreen7** [comment]
for future use popover throws a bunch of warnings if you add the above code. You must disable hide.
```<Popover modifiers={{ preventOverflow: { enabled: false }, hide: { enabled: false } }} ... />```

**Comment by tgreen7** [comment]
This seems like it was changed again in version 3.9.0 as can be seen here https://github.com/palantir/blueprint/compare/@blueprintjs/core@3.8.0...@blueprintjs/core@3.9.0

To override this change and get a tooltip working outside of its boundaries you need to add these modifiers:
```
{
  preventOverflow: { enabled: false, boundariesElement: 'scrollParent' },
  flip: {
    boundariesElement: 'viewport'
  },
  hide: { enabled: false }
}
```
