### ISSUE TITLE
[Tag] Remove Buttons do not use Icon class

### ISSUE THREAD

**Issue by rmendelovits** [palantir/blueprint#2225]
In the new version of Blueprint, my team only uses the new Icon class. However, your tag inputs still use the class version of icons so they do not show in my project.

**Comment by adidahiya** [comment]
Have you included the `@blueprintjs/icons` CSS file? This is still required for Blueprint 2.

However, you're right, the tag remove button does use the icon font, when it should instead use an `<Icon>` component.

**Comment by giladgray** [comment]
@rmendelovits PR up at #2231 if you want to follow along 😄

**Comment by rmendelovits** [comment]
Thank you @giladray and @adidahiya
