### ISSUE TITLE
PopperJS compilation issues

### ISSUE THREAD

**Issue by LucasSeveryn** [palantir/blueprint#2226]
### Bug report

- __Package version(s)__: v2
- __Browser and OS versions__: N/A, Ubuntu 14.04.5 LTS

#### Steps to reproduce

1. `npm install -g create-react-app`
1. `create-react-app my-app --scripts-version=react-scripts-ts`
1.  `yarn add @blueprintjs/core`
1. `npm i`
1.  `npm run start`

#### Actual behavior

```
Failed to compile.

/home/lucas/app/node_modules/@blueprintjs/core/lib/esm/components/popover/popover.d.ts
(4,39): 'PopperJS' only refers to a type, but is being used as a namespace here.
```

#### Expected behavior

project should compile

#### How to fix:

Change the references in affected files from:

`import PopperJS from "popper.js";`

to:

`import * as PopperJS from "popper.js";`

**Comment by adidahiya** [comment]
I traced the problem to an unintended breaking change in the popper.js library: https://github.com/FezVrasta/popper.js/pull/539

For now, you can work around this by pinning your version of popper.js to `~1.12.6` in your package.json.

**Comment by adidahiya** [comment]
I pushed a fix to the popper.js library -- try upgrading to 1.14.1
