### ISSUE TITLE
Toasts position is broken

### ISSUE THREAD

**Issue by Grmiade** [palantir/blueprint#2232]
### Bug report

- __Package version(s)__: 2.0-rc3
- __Browser and OS versions__: Tested on Chrome

#### Steps to reproduce

1. In docs, select a position
2. And click on buttons to show toasts

#### Actual behavior

The chosen position seems not be correctly applied. And break the toast style 😱 

<img width="1399" alt="screen shot 2018-03-14 at 11 18 20" src="https://user-images.githubusercontent.com/11244106/37396681-dd2e945c-2779-11e8-82ac-ed0438dff5fd.png">
<img width="1399" alt="screen shot 2018-03-14 at 11 18 27" src="https://user-images.githubusercontent.com/11244106/37396682-dd7ab710-2779-11e8-8bcd-279783c611b7.png">
<img width="1399" alt="screen shot 2018-03-14 at 11 18 36" src="https://user-images.githubusercontent.com/11244106/37396683-dd9c6392-2779-11e8-89b3-d61e32783955.png">

#### Expected behavior

The old behavior :) With correct position.

**Comment by reiv** [comment]
This seems to be a regression introduced in https://github.com/palantir/blueprint/commit/2d7f7564ca4528e1d5de00f17ebd9a9e7cd82a24.
