### ISSUE TITLE
[Select] Expose query to itemRenderer for highlighting purposes

### ISSUE THREAD

**Issue by reiv** [palantir/blueprint#2239]
It would be pretty neat if `itemRenderer` had access to the query string so it could be used for highlighting (partial) matches. This would be especially helpful for users to understand the filtered results if a fuzzy string search algorithm is used. Of course, there is some overlap here with `itemPredicate` and `itemListPredicate`, because `itemRenderer` could then be (ab)used to filter items directly by returning `null` if the query doesn't match. I can't think of a way around that, other than perhaps combining `itemRenderer` and `itemPredicate` (leaving `itemListPredicate` for filtering the items wholesale).

Example:
![select-highlight](https://user-images.githubusercontent.com/205631/37433204-3ee3cf08-27db-11e8-8f5f-48acc2d613a9.png)

To facilitate this even more, I'd love it if we could have a style for highlighted `<span>`s that provides adequate contrast on a `<MenuItem>` (`pt-search-highlight` or something like that).

Thoughts?

**Comment by giladgray** [comment]
@reiv love it, totally down for this.
