### ISSUE TITLE
Dismissing a Popover that is in a Dialog is closing the Dialog

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2240]
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Chrome 64.0.3282.186, MacOS 10.13.3

![closing-dialog](https://user-images.githubusercontent.com/10415101/37434402-af3eb374-279c-11e8-980c-280cdc0d419f.gif)

**test site**: https://tgreen7.github.io/blueprint-popover/
**test repo**: https://github.com/tgreen7/blueprint-popover

**Comment by adidahiya** [comment]
This is expected, since the popover is outside the dialog, and outside clicks are allowed to close the dialog. You can get around this by disabling `canOutsideClickClose` on the Dialog or making the Popover `usePortal={false}`.

**Comment by tnrich** [comment]
@adidahiya this has only started happening in v2 of blueprint though. Was this change in behavior expected?

**Comment by giladgray** [comment]
@tnrich i'm not sure that's true--fairly sure this would happen in 1.0 too. we haven't touched the logic that closes on backdrop click.

**Comment by tgreen7** [comment]
@giladgray here is a test in 1.0 https://tgreen7.github.io/blueprint-popover-v1/
it seems to be working fine there. (repo https://github.com/tgreen7/blueprint-popover-v1)

**Comment by giladgray** [comment]
(incorrect close, wrong issue number in PR)

**Comment by giladgray** [comment]
other related issues exist
