### ISSUE TITLE
Overlay causes Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by branko-d** [palantir/blueprint#2246]
### Bug report

- __Package version(s)__: 
    blueprintjs/core 2.0.0-rc.3

- __Browser and OS versions__: 
    Probably doesn't depend on OS and browser. I tried under Windows 10, under following browsers:
        - Firefox 58.0.2 (64-bit)
        - Chrome 64.0.3282.186 (Official Build) (64-bit)
        - Edge 41.16299.248.0

#### Steps to reproduce

1. Show the Dialog component.

#### Actual behavior

Works, but the browser console shows:

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Blueprint2.Overlay`. See https://fb.me/react-warning-keys for more information.
    in CSSTransition (created by Blueprint2.Overlay)
    in Blueprint2.Overlay (created by Blueprint2.Dialog)
    in Blueprint2.Dialog (created by ..)
    in ...

```

#### Expected behavior

Same as above, but without the warning.

My guess is that the problem is in `@blueprintjs\core\src\components\overlay\overlay.tsx`, line 167...

```
const childrenWithTransitions = isOpen ? React.Children.map(children, this.maybeRenderChild) : [];
```
...which doesn't supply keys.

**Comment by giladgray** [comment]
@branko-d ah yep definitely missing a `key` when we create the `CSSTransition` element in `this.maybeRenderChild`. would love a PR!
