### ISSUE TITLE
Slider onRelease and onChange don't always match

### ISSUE THREAD

**Issue by nchen63** [palantir/blueprint#2248]
### Bug report

- __Package version(s)__: 1.35
- __Browser and OS versions__: Chrome, OSX 10.12.6

#### Steps to reproduce

1. Create a slider that logs the onRelease and onChange values
1. move the slider around rapidly, stopping and starting 

#### Actual behavior

about 1 in 5 times, the last onChange value and the onRelease values don't match

#### Expected behavior

They should match

I debugged the issue, and it's caused because `getBoundingClientRect` values lag the actual slider handle position. This occurs in line https://github.com/palantir/blueprint/blob/62aed9031a515b86344dd110ffcb8ef2ae17fb44/packages/core/src/components/slider/handle.tsx#L207. 

Here's what I logged (note how the x value of DOMRect keeps changing in between `handleMovedTo` and `handleMoveEndedAt` even though the pixel position hasn't changed:
```
handleMovedTo called pixel=559 clientToValue(pixel)=50
    getHandleMidpointAndOffset called: DOMRect {x: 553, y: 302, width: 16, height: 16, top: 302, …}
    getHandleMidpointAndOffset called: DOMRect {x: 553, y: 302, width: 16, height: 16, top: 302, …}
    getHandleMidpointAndOffset called: DOMRect {x: 549, y: 302, width: 16, height: 16, top: 302, …}
    getHandleMidpointAndOffset called: DOMRect {x: 549, y: 302, width: 16, height: 16, top: 302, …}
    getHandleMidpointAndOffset called: DOMRect {x: 549, y: 302, width: 16, height: 16, top: 302, …}
handleMoveEndedAt called pixel=559 clientToValue(pixel)=51
```

Possible fix is to use the most recent `onChange` calculated value for `onRelease`

**Comment by giladgray** [comment]
if a DOM method is out of sync with reality, then wrapping it in a `requestAnimationFrame` should allow it to catch up.
