### ISSUE TITLE
SVGTooltip no longer exists in 2.0

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2250]
What should we use instead?

**Comment by giladgray** [comment]
yeah we killed it because it wasn't helping us anymore. you should be able to use regular `Tooltip` with `rootElementTag` prop (that's all `SVGTooltip` ever was). please let us know if you see warnings, but we have no plans to bring the component back.

**Comment by tgreen7** [comment]
@giladgray we tried with rootElementTag="g". It is making the pt-popover-wrapper a g element but the pt-popover-target is a div, so the whole thing just isn't showing up.

**Comment by giladgray** [comment]
@tgreen7 happy to accept a PR here, but this is not a priority for the team.

**Comment by tgreen7** [comment]
@giladgray I looked at react-popper and received this response https://github.com/souporserious/react-popper/issues/107. So if blueprintjs just added the ability to pass a component prop to the Target in popper (maybe a targetComponent prop to Tooltip or Popover), then that would help solve this issue. (sorry but I don't really know how to go about opening a pr here / typescript)

**Comment by tgreen7** [comment]
@giladgray I think I have found the solution. Do I have to fork blueprint to create the pr?

**Comment by giladgray** [comment]
@tgreen7 indeed you do

**Comment by giladgray** [comment]
closed in #2276
