### ISSUE TITLE
Make Dialog grow to contain children

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2254]
### Bug report

<img width="924" alt="screen shot 2018-03-15 at 3 28 08 pm" src="https://user-images.githubusercontent.com/10415101/37494341-a862e808-2865-11e8-87f9-59ad5007525b.png">

- __Package version(s)__:  2.0.0-rc.2

#### Steps to reproduce

1. Dialog with a 
```
<div
              style={{
                background: 'red',
                width: 800,
                height: 200
              }}
            />
```
inside

#### Actual behavior

div falls outside of dialog

#### Expected behavior

dialog will contain div

**Comment by llorca** [comment]
@tgreen7 tweak the `width` property of your dialog—it's 500px by defaut
