### ISSUE TITLE
2.0 QE

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#2266]
Aggregating all the issues and regressions that show up in 2.0 release candidates.

### Docs
- [x] in "Dialogs", the example dialog body text is 16px instead of the normal 14px UI text, because of a `pt-running-text` above in the tree
<img width="604" alt="screen shot 2018-03-19 at 8 03 10 pm" src="https://user-images.githubusercontent.com/199754/37633723-b7c3aadc-2bb0-11e8-836d-8b15eebac0a1.png">

- [x] in "Popovers" (dark theme only), the colored text in position buttons need to be lighter
![image](https://user-images.githubusercontent.com/199754/37549767-89348406-2940-11e8-89fe-9a87f3ace5fb.png)
- [x] selected low level nav item no longer updates on page scroll
![screen recording google chrome](https://user-images.githubusercontent.com/199754/37549148-a93cecbc-293a-11e8-928c-cf9176edb011.gif)
- [x] Color scheme "Copied to clipboard" confirmation has wrong icon (though color palette one is fine)
![image](https://user-images.githubusercontent.com/199754/37549215-20ec0c84-293b-11e8-8194-58c60ffc0581.png)
- [x] Some input shadows are cut off again
![image](https://user-images.githubusercontent.com/199754/37549495-ce7b4c50-293d-11e8-83e6-53ad9c969534.png)
![image](https://user-images.githubusercontent.com/199754/37549501-e82e212c-293d-11e8-9881-b0b38953e457.png)
- [x] Banner seems to only show when the URL hash is declared but empty (e.g. `/index.html#`). in some rare cases it appears half cut off as well
![image](https://user-images.githubusercontent.com/199754/37549726-357cb536-2940-11e8-9f25-8dbda05a8480.png)

- [x] "Color aliases" table styles are broken
![image](https://user-images.githubusercontent.com/199754/37549178-e2fecbb4-293a-11e8-90f2-4a1e206e6121.png)

- ~~pages ending with props table lack bottom padding (and have too much top margin)~~ no repro
![image](https://user-images.githubusercontent.com/199754/37549336-21d98e18-293c-11e8-9427-3c6e7bfe200e.png)

- ~~remove left icon of anchor button example~~ useful to show this case
![image](https://user-images.githubusercontent.com/199754/37549356-5f30bd86-293c-11e8-97fd-72a0d6e69175.png)

- [x] second alert example should be intent danger
![image](https://user-images.githubusercontent.com/199754/37549270-8a56669c-293b-11e8-978c-4c28190d53fb.png)

- [x] move alignment button group to second column
![image](https://user-images.githubusercontent.com/199754/37549384-a15ec536-293c-11e8-8063-60bc7d1290be.png)

- [x] in "Callouts" & "Radios", broken interface description (_only_ when outside of the docs API overlay)
![image](https://user-images.githubusercontent.com/199754/37549401-d621a48c-293c-11e8-93af-ab82c02f0b6e.png)
![image](https://user-images.githubusercontent.com/199754/37549560-7ed50f8c-293e-11e8-9b6c-bbcb49b6dee6.png)

- ~~"Collapsible list" & "Context menus" & "Editable text" & "Labels" & "Form groups" & "Overlays" & a bunch of other pages end with almost no padding~~ no repro
![image](https://user-images.githubusercontent.com/199754/37549427-19546500-293d-11e8-87b2-b973de0902a2.png)

- ~~"Dialogs" & "Checkboxes" & "Text inputs" pages end with no padding~~ no repro
![image](https://user-images.githubusercontent.com/199754/37549447-6069219c-293d-11e8-84da-c44bace3be26.png)

- [x] make this gross links interactive tags instead (blocked on https://github.com/palantir/blueprint/pull/2251)
![image](https://user-images.githubusercontent.com/199754/37549435-327586d6-293d-11e8-8500-198a9f8dbc87.png)

- [x] in "Checkboxes" & "Switches" & "Radios" & "Text input groups", `.pt-align-right`-style classes shouldn't wrap
![image](https://user-images.githubusercontent.com/199754/37549535-326ed9ca-293e-11e8-8452-903d391dc92e.png)

- [x] in "Navbars", there's a bunch of empty props table. either hide "Props" and "Description" headers, or hide the whole thing
![image](https://user-images.githubusercontent.com/199754/37549686-e490f362-293f-11e8-8a92-7968bf4350ec.png)

### Core
- [x] file input button lost shadow (only light theme)
![image](https://user-images.githubusercontent.com/199754/37549609-15e9d416-293f-11e8-842c-e1d7de59f9a1.png)
- [x] numeric input buttons are no longer sized properly (both light and dark themes)
![image](https://user-images.githubusercontent.com/199754/37549619-31f33c74-293f-11e8-8c52-65c0deb0a709.png)

### Datetime
- [ ] in "Date range picker", wrong color for month selection caret icons
![image](https://user-images.githubusercontent.com/199754/37549820-48554cbc-2941-11e8-9fa3-9b773f93c9c3.png)

- [x] in "Date range picker", wrong alignment for reverse month/year selection
![image](https://user-images.githubusercontent.com/199754/37549826-5f3fdd66-2941-11e8-9932-d0d2d2a44509.png)

- [x] date input shadow is gone
![image](https://user-images.githubusercontent.com/199754/37549857-d2e68238-2941-11e8-95dc-8bbc40abadaa.png)
- [x] in "Date range picker", mispositioned icon for month selection with disabled calendar
![image](https://user-images.githubusercontent.com/199754/37549834-84009816-2941-11e8-96fb-3f7df5b756e1.png)

- [x] time picker shouldn't have default margins/paddings
![image](https://user-images.githubusercontent.com/199754/37549848-a666085a-2941-11e8-848d-977a81060641.png)

- [x] in "Date input", "no date" label too close to input
![image](https://user-images.githubusercontent.com/199754/37549886-25dfab54-2942-11e8-9530-208386ed885f.png)

- ~~in "Date range input", "no date" label moves on input focus~~ intentional so you can see the label when oppover is open
![screen recording google chrome](https://user-images.githubusercontent.com/199754/37549882-201d1f9e-2942-11e8-9b77-2aaf59a54462.gif)

- in "Date range input", focusing the input with a selected range gives broken visuals
![image](https://user-images.githubusercontent.com/199754/37686022-f60630ba-2c52-11e8-9cc2-f172c7cdbc0c.png)

### Table
- [x] for every table example, margin is needed between `View source on GitHub` and the table
![image](https://user-images.githubusercontent.com/199754/37551716-01263140-2963-11e8-9fc4-69b0807a65e0.png)
- [x] "Editing" example displays a broken table
![image](https://user-images.githubusercontent.com/199754/37551717-1057a0e0-2963-11e8-9163-77999182a45e.png)
- [x] `IRegion` doesn't render the proper interface description element
![image](https://user-images.githubusercontent.com/199754/37551705-ca29ff14-2962-11e8-8909-bfa7c9f1afb5.png)

- [x] `RenderMode` shouldn't have a copyright header as interface description
![image](https://user-images.githubusercontent.com/199754/37551709-e1c773fe-2962-11e8-9cf0-4946bb7b9b28.png)

- [x] "Reordering" table example displays broken icon
![image](https://user-images.githubusercontent.com/199754/37551724-293917ce-2963-11e8-86d2-b477c85bc6dd.png)
![image](https://user-images.githubusercontent.com/199754/37551725-39e254dc-2963-11e8-8e2a-2added630d7e.png)

**Comment by babybumblebee** [comment]
https://github.com/palantir/blueprint/issues/2137 Any chance of this getting fixed in the rcs?

**Comment by sei15** [comment]
https://github.com/palantir/blueprint/issues/2137 Any chance of this getting fixed in the rcs?

**Comment by llorca** [comment]
@sei15 #2137 isn't a blocker to ship 2.0, so probably not as we're pretty strapped here. but we'd happy accept a contribution if you'd like to take a look at it!

**Comment by sei15** [comment]
I'll give it a shot

**Comment by giladgray** [comment]
remaining issues: @cmslewis will tackle the table issues, i'll do the DatePicker caption ones. not gonna worry about the rest today (small docs stuff).

**Comment by cmslewis** [comment]
@giladgray @llorca FYI if you refresh the page while looking at the Table Features, you see this on page load:

![image](https://user-images.githubusercontent.com/443450/37726729-47f4bf54-2cf3-11e8-8b17-7417b6d8c552.png)

I think the docs app still suffers from a Flash of Unstyled Content bug that's causing the table to mis-measure what "width: 100%" is.

**Comment by giladgray** [comment]
@cmslewis that sounds in line with what i've observed. can we add an `rAF` somewhere to delay the measuring?

**Comment by cmslewis** [comment]
Working on it.

**Comment by cmslewis** [comment]
🙄 

```tsx
    public componentWillMount() {
        requestAnimationFrame(() => {
            this.hasDelayedBeforeInitialRender = true;
            this.forceUpdate();
        });
    }

    public render() {
        if (!this.hasDelayedBeforeInitialRender) {
            return null;
        }
        // ...
    }
```

**Comment by giladgray** [comment]
filed #2292 for follow up. we did it!
