### ISSUE TITLE
label helperText no longer accepting React nodes

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2279]
### Bug report

- __Package version(s)__: 2.0.0-rc.3
- __Browser and OS versions__: Chrome, macOS

#### Steps to reproduce

1. Use a React node as helperText on a Label

```js
<Label
  text="Username"
  helperText={
      <span style={{ display: 'block', fontSize: '80%' }}>
          blah
       </span>
  }
>
  ...
</Label>
```

#### Actual behavior

This now displays as : `Username [object Object]`

#### Expected behavior

The helperText displays React node.

I suggest changing to:

```js
{helperText && <span className={classNames(Classes.TEXT_MUTED)}>{" "}{helperText}</span>}
```

**Comment by llorca** [comment]
@will-stone have some time to put a PR together? would be much appreciated

**Comment by will-stone** [comment]
Sure. Actually, work's a bit slow: I'll do it now :-)
