### ISSUE TITLE
[Menu items] Broken large styles

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#2281]
![image](https://user-images.githubusercontent.com/199754/37679784-319ee9e6-2c3f-11e8-948c-4b3d66813b42.png)
with 2.0, large menu item styles are a bit broken:
- the vertical centering is off, as well 
- the icon is 16px instead of 20px

### Expected
![image](https://user-images.githubusercontent.com/199754/37679746-18871ae6-2c3f-11e8-8d8d-930f00634e0f.png)

**Comment by giladgray** [comment]
@llorca you can't just slap the `.pt-large` modifier and expect things to work anymore... icons can only be made large through JS.

**Comment by giladgray** [comment]
you'll notice that the CSS API example looks great when large.

**Comment by giladgray** [comment]
we should add large support to the JS API, though. seems that's missing.
