### ISSUE TITLE
Sass custom variables

### ISSUE THREAD

**Issue by cosmophile** [palantir/blueprint#2287]
Hello and thanks, blueprint is awesome.

I have a tiny question: why does [`typography.scss`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/_typography.scss#L6) reimport `common/variables` when it is already imported in [`blueprint.scss`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/blueprint.scss#L10)?

I ask because I have a sass setup where I am overriding certain global blueprint variables, and without that line it seems I can do something like
```
@import "~@blueprintjs/core/src/common/resets";
@import "~@blueprintjs/core/src/common/variables";
@import "~@blueprintjs/core/src/common/colors";
@import "custom_variables"; 
@import "~@blueprintjs/core/src/typography"; 
@import "~@blueprintjs/core/src/accessibility";
@import "~@blueprintjs/core/src/components/index";
```

Thanks again for any help you can provide.

**Comment by giladgray** [comment]
@cosmophile this shouldn't be a problem because we've marked all our variables as `!default`, so redefining them will overwrite our values. try putting your `custom_variables` import first?

**Comment by cosmophile** [comment]
Ah that makes sense. SMH

Thank you!

**Comment by giladgray** [comment]
Sure thing!
