### ISSUE TITLE
Compiler warning and Javascript error involving Popper.js

### ISSUE THREAD

**Issue by nkohari** [palantir/blueprint#2299]
### Bug report

- __Package version(s)__: 2.0.0-rc.4
- __Browser and OS versions__: MacOS Sierra 10.12.6, Chrome Version 65.0.3325.162 (Official Build) (64-bit)

#### Steps to reproduce

1. Install `@blueprintjs/core@2.0.0-rc.4` via yarn.
2. Attempt to start simple boilerplate app.

#### Actual behavior

I receive this warning during Webpack compilation:

```
WARNING in ./node_modules/react-popper/lib/Popper.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/nkohari/path/to/project/client/node_modules/react-popper/lib/Popper.js
    Used by 1 module(s), i. e.
    /Users/nkohari/path/to/project/client/node_modules/react-popper/lib/react-popper.js
* /Users/nkohari/path/to/project/client/node_modules/react-popper/lib/popper.js
    Used by 2 module(s), i. e.
    /Users/nkohari/path/to/project/client/node_modules/react-popper/lib/Popper.js
 @ ./node_modules/react-popper/lib/Popper.js
 @ ./node_modules/react-popper/lib/react-popper.js
 @ ./node_modules/@blueprintjs/core/lib/esm/components/popover/popover.js
 @ ./node_modules/@blueprintjs/core/lib/esm/components/index.js
 @ ./node_modules/@blueprintjs/core/lib/esm/index.js
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?https://projectname.test:8081 webpack/hot/dev-server ./src
```

In my `index.tsx` file, which initializes my React app, I'm calling:

```jsx
import { FocusStyleManager } from "@blueprintjs/core"; 
FocusStyleManager.onlyShowFocusOnTabs();
```

At the `import` statement, the following Javascript error occurs in my browser:

```
popper.js?acfd:232 Uncaught TypeError: Cannot read property 'placements' of undefined
    at eval (popper.js?acfd:232)
    at Object../node_modules/react-popper/lib/popper.js (bundle.js:4790)
    at __webpack_require__ (bundle.js:710)
    at fn (bundle.js:95)
    at eval (Popper.js?d753:17)
    at Object../node_modules/react-popper/lib/Popper.js (bundle.js:4766)
    at __webpack_require__ (bundle.js:710)
    at fn (bundle.js:95)
    at eval (react-popper.js?d575:16)
    at Object../node_modules/react-popper/lib/react-popper.js (bundle.js:4802)
```

I'm not actually using Popover in Blueprint, and I'm not using Popper.js directly. This seems to happen immediately when I import Blueprint.

#### Expected behavior

No compiler warning, and no Javascript error. 😄

**Comment by polakluk** [comment]
This is probably caused by this open issue in [react-popper](https://github.com/souporserious/react-popper/issues/76)

**Comment by giladgray** [comment]
@polakluk seems like there's a workaround mentioned in that issue, about removing `NODE_PATH=` from environment? either way, this is an external issue.

**Comment by nkohari** [comment]
Sorry for the delay! I just installed `@blueprintjs/core@2.0.0` and I'm still getting the same issue. The versions of Popper are:

```
$ yarn list --pattern popper
yarn list v1.5.1
├─ popper.js@1.14.1
└─ react-popper@0.8.3
```

I haven't altered `NODE_PATH`, but I do have the following in my Webpack configuration which has a similar effect:

```
resolve: {
  modules: [
    'node_modules',
    '.'
  ]
}
```

I wonder if that's the trouble? I can test this, but I'll need to re-do most of my imports, so it'll take bit of effort. :) Happy to do it if it sounds like it might be the cause.

**Comment by giladgray** [comment]
@nkohari check the thread in https://github.com/souporserious/react-popper/issues/76. try installing `react-popper@next` and see if the error persists.

**Comment by nkohari** [comment]
If I just `yarn add popper@next`, yarn will ignore it and give Blueprint the old version:

```
$ yarn list --pattern popper
yarn list v1.5.1
├─ @blueprintjs/core@2.0.0
│  └─ react-popper@0.8.3
├─ popper.js@1.14.1
└─ react-popper@0.9.0
```

So I added a `resolutions` block to my `package.json`:

```
  "resolutions": {
    "react-popper": "^0.9.0"
  },
```

This will force the version of `react-popper` to 0.9.0:

```
$ yarn list --pattern popper
yarn list v1.5.1
├─ popper.js@1.14.1
└─ react-popper@0.9.0
```

...but unfortunately the problem persists. Anything else I can try? (I'll comment on issue on `react-popper` as well.)

**Comment by giladgray** [comment]
@nkohari this conversation should move to the `react-popper` issue. there's basically nothing to be done in this codebase.

**Comment by giladgray** [comment]
actually i'll leave this open cuz we will have to bump a dep.

**Comment by nkohari** [comment]
I was able to find [a workaround](https://github.com/souporserious/react-popper/issues/76#issuecomment-375817520) which I'll link here in case anyone else runs into the same trouble. Sorry for the trouble, and thanks for your help!

**Comment by giladgray** [comment]
external issue from user's webpack config
