### ISSUE TITLE
"night" color scheme bug

### ISSUE THREAD

**Issue by c-smile** [palantir/blueprint#230]
### Bug Report

- __Package version(s)__: (1.0.1)
- __Browser and OS versions__: (GC on Windows)

#### Describe the issue:

When using "Night"/dark scheme popup list items are not visible.

For example click on "Intent" select here:
http://blueprintjs.com/docs/#components.editable 

#### Actual behavior:

Popup list items are not visible.

#### Expected behavior:

Popup list items shall be visible.

**Comment by cmslewis** [comment]
Thanks for the bug report, @c-smile! I believe PR #158 from earlier today will correct the issue you're seeing. Should be going live shortly.
