### ISSUE TITLE
Bundle size optimization (only react vs blueprint@1.x vs blueprint@2.0)

### ISSUE THREAD

**Issue by avevlad** [palantir/blueprint#2306]
### Bug report

- __Package version(s)__: 1.0.0 and 2.0.0
- __Browser and OS versions__:  mac

### Bundle size:

| Only React | React + blueprint@1.35.7 | React + blueprint@2.0.0 |
|------------|---------------------|---------------------|
| 97 KiB     | 293 KiB             | 594 KiB             |

#### Test code https://github.com/AveVlad/palantir_blueprint_playground

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Button } from '@blueprintjs/core';

const container = document.getElementById('app-container');

ReactDOM.render((<div><Button>123</Button></div>), container);
```

webpack: https://github.com/AveVlad/palantir_blueprint_playground/blob/master/common/webpack.common.js

#### Steps to reproduce

1. `git clone https://github.com/AveVlad/palantir_blueprint_playground`
1. `npm install`
1. `node bundle_size.shell.js -i`
1. `node bundle_size.shell.js -b | grep "main"`

### Questions

> Only React vs blueprint@1.35.7

Why such a big difference?

> Only React vs blueprint@2.0.0

Why so much a big difference? 🦊 

Blueprint is awesome lib, Thanks!

**Comment by giladgray** [comment]
@AveVlad the big difference is from the new icons package: a few hundred kb of SVG paths in the JS files.

the upside is that you should no longer have to load the icon fonts, so the net difference is roughly zero.

**Comment by rayshan** [comment]
Can icons package be tree-shaked during build?

**Comment by giladgray** [comment]
@rayshan not currently, but we're definitely open to suggestions! 
please discuss icon tree-shaking on #2193.

**Comment by adidahiya** [comment]
closing in favor of #2193
