### ISSUE TITLE
[Popover] Content immediately hidden after target focused

### ISSUE THREAD

**Issue by sushain97** [palantir/blueprint#2307]
### Bug report

- __Package version(s)__:

Core 2.0.0 (repro'd on currently live docs site)

- __Browser and OS versions__:

Chrome 65.0.3325.181 on Windows Server 2008 R2 Enterprise (pretty sure it's also a problem on Windows 7 Enterprise but I haven't replicated with latest BP there)

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/v2/#core/components/popover.opening-and-closing.
1. Click on the link icon besides "Opening and closing".
1. `Tab` twice. (onto the Hover)

#### Actual behavior

Popover opens and then immediately closes.

#### Expected behavior

Popover opens and stays open so I can tab through the menu items since `openOnTargetFocus=true`.

If this is the expected behavior, I suppose this should be a feature request instead.

**Comment by giladgray** [comment]
@sushain97 ah dang that's a bummer. not expected, should work. we may need to add "return focus to previous place" to `Overlay` focus-trap behavior.

**Comment by giladgray** [comment]
seems fixed, possibly related to #2745
