### ISSUE TITLE
MultiSelect should support clear all selected tags

### ISSUE THREAD

**Issue by janewuwz** [palantir/blueprint#2309]
I think MultiSelect should have a clear button and so you can click it to clear selected items. 
Like this:

![show](https://user-images.githubusercontent.com/11661209/37873179-6fd1e282-3049-11e8-866c-73cf91214612.gif)

TagInput support rightElement and has achieved it. So It will be very simple.

**Comment by giladgray** [comment]
@janewuwz this is very easy to add yourself via `tagInputProps`

**Comment by janewuwz** [comment]
@giladgray yes you're right.There's nothing to do with MultiSelect component.I think you can close the issue or I made a pr to complete it in the MultiSelect example. #2318
