### ISSUE TITLE
Weird table headers when Table component is in a hidden Tab

### ISSUE THREAD

**Issue by pcdv** [palantir/blueprint#2313]
### Bug report

- __Package version(s)__: Core + Table 2.0.0
- __Browser and OS versions__: Linux (ubuntu 14.04) chrome + firefox, same on MacOS

When a table is within a tab that is not active, its header is wrongly formatted when switching to its enclosing tab.

I think the problem is the same on all browsers.

#### Steps to reproduce

See this [fiddle](https://jsfiddle.net/6uLwv7c3/4/)

#### Actual behavior

![image](https://user-images.githubusercontent.com/1318831/37918712-2d6132a2-3122-11e8-83b6-833bf2131a5f.png)

Note that resizing a column fixes the rendering.

#### Expected behavior

![image](https://user-images.githubusercontent.com/1318831/37918876-9bcf1132-3122-11e8-99f6-ec25d66c3b63.png)

**Comment by giladgray** [comment]
@pcdv known issue with hidden tabs (like of course, table can't measure itself if it's invisible). can you perhaps issue a `forceUpdate()` when changing to the tab containing the table? should cause it to re-measure.

**Comment by pcdv** [comment]
The weird thing is the rest of the table seems to be _almost_ able to measure itself: only the header is badly rendered.

Anyway I don't need the row header in that particular case so I just added `enableRowHeader={false}`

**Comment by pcdv** [comment]
Looks like `renderActiveTabPanelOnly={true}` is the right way to fix this problem (maybe this prop did not exist at the time of my initial issue).

See new example in https://codesandbox.io/s/yzr6v6x7j
