### ISSUE TITLE
iOS Safari column resize not working

### ISSUE THREAD

**Issue by k1tzu** [palantir/blueprint#2314]
### Bug report

- __Package version(s)__: 2.0.0
- __Browser and OS versions__: iOS 11.1.2

#### Steps to reproduce

Open http://blueprintjs.com/docs/v2/#table/api.table in iOS Safari
Try to resize a column

#### Actual behavior

The row with header cells is moving

#### Expected behavior

Column is resizing

ps
do I need to open a separate issue for "Touch and hold on ColumnHeaderCell doesn't act like right-click?"

**Comment by llorca** [comment]
yes, please open a separate issue for each feature request.

also please note that according to our [README header](https://github.com/palantir/blueprint/blob/develop/README.md), Blueprint is optimized for desktop apps. it hasn't been fully optimize for mobile usage, therefore if you rely heavily on mobile interactions and are looking for a mobile-first UI toolkit, Blueprint may not be the right tool for you.

**Comment by giladgray** [comment]
@k1tzu reiterating what @llorca said above: **Blueprint is a desktop UI library**, so most components do not support touch events out of the box. the table was decidedly _not_ designed for mobile so this behavior is basically by design.

if you're keen on mobile support for the table, we'll happily review PRs. but i'd kinda urge you not to do that, as the table package is _very_ complex and likely to be replaced soon (spoilers).

**Comment by giladgray** [comment]
prior art: #265, in which someone submits a PR to add touch support for `Slider` (still the only component with actual `touch` event support).

**Comment by k1tzu** [comment]
It's 2018. Desktops are nearly past. I wasn't expecting the solution to be "desktop only" Several weeks of development based on your UI goes down the drain.

**Comment by llorca** [comment]
- Read. It's literally in the intro of the README.
- Contribute. Make Blueprint mobile-friendly.
- Don't be rude. This software is free, open source, and provided as is.

**Comment by k1tzu** [comment]
* Yes this is all my fault. I never read intros. Straight to examples and API.
* "table package is very complex and likely to be replaced soon" - so no point to contribute as I see.
* We're natively not very polite here in Russia. Sorry for that. I really liked the package more than any other I looked at here on github. It looks better than anyone. You did great.
