### ISSUE TITLE
Tabs with no active tab after navigation from other Tabs instance

### ISSUE THREAD

**Issue by pcdv** [palantir/blueprint#2317]
### Bug report

- __Package version(s)__:  Core 2.0.0
- __Browser and OS versions__: All

#### Steps to reproduce

https://jsfiddle.net/6uLwv7c3/19/

#### Actual behavior

When a Tabs instance is replaced by another one, no tab is active.

![image](https://user-images.githubusercontent.com/1318831/37953555-843e0466-31a3-11e8-98ca-6f31085e159c.png)

#### Expected behavior

By default, the first tab should always be active.

![image](https://user-images.githubusercontent.com/1318831/37953579-94d2d3f6-31a3-11e8-9af6-f069841becfc.png)

It looks like something missing in componentWillReceiveProps() to reset the state of the component.

**Comment by pcdv** [comment]
I had missed the following prop:
```ts
    /**
     * Initial selected tab `id`, for uncontrolled usage.
     * Note that this prop refers only to `<Tab>` children; other types of elements are ignored.
     * @default first tab
     */
    defaultSelectedTabId?: TabId;
```
I guess I can use this to fix my issue but it seems the "@default first tab" contract is not applied here.

**Comment by giladgray** [comment]
@pcdv if you simply add a `key` prop to the `Tabs` component then it works as expected. this is because in your current implementation _it's all the same `Tabs` instance_, so when you delete a tab it puts the component in a bad state. if you change the `Tabs` `key` at the same time then React will actually create a new instance and state will be initialized as expected.

**Comment by giladgray** [comment]
alternately you can simply control the active tab using `selectedTabId`. then you won't have to create new instances and can change the tab id outside of the component's lifecycle, but you will have to track state.

**Comment by pcdv** [comment]
Fair enough. I had taken the habit of resetting the state in my components in case of reuse by React but using key= is a good trick. Thanks.
