### ISSUE TITLE
Improve visual design of truncated cell content

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#232]
### A request for micro-interaction design review

In a table that uses `<JSONFormat>` to render cell contents, it's easy to produce columns that look like this:

![image](https://cloud.githubusercontent.com/assets/723999/20576957/1d181ff6-b18e-11e6-8426-57c74d385c08.png)
![image](https://cloud.githubusercontent.com/assets/723999/20576963/20fbcbfe-b18e-11e6-86b5-e05701cde44b.png)

To an user, it can be confusing why some cells use normal ellipses + a browser tooltip and others have a fancy popover that renders longer content. In the source code, it is clear that this truncation threshold is 80 characters, and you get into this undesirable state when columns are < 80 chars wide while content length hovers above and below 80 chars.

No clean solution jumps out to me. Changing the truncation threshold _might_ help, but feels a bit like a band-aid. Some ideas:

- Change the "..." icon that triggers the popover
- Never use `text-overflow` truncation & browser tooltips with `<JSONFormat>` -- instead always use the fancy popover

Thoughts?

**Comment by llorca** [comment]
Just talked to Bill, we propose using the fancy popover truncation not just for JSON cells anymore, but for any type of cells. That will make the interaction consistent across all cells that are truncated.
