### ISSUE TITLE
Icons not aligned (centered) correctly (Blueprintjs 2.0)

### ISSUE THREAD

**Issue by vladeck** [palantir/blueprint#2320]
### Bug report

- __Package version(s)__: `@blueprintjs/core` __2.0.0__ / `@blueprintjs/icons` __2.0.0__
- __Browser and OS versions__: Windows 10 x64 1709 / Chrome 65

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/v2/#core/components/icon
2. Select `eye-open` icon
3. Icon is __not__ centered

![blueprintjs_icons_issue](https://user-images.githubusercontent.com/16443718/37966503-02d149ee-31c9-11e8-8755-5cac0b71f817.png)

__NOTE__: there are more icons with this issues. If it would help, I can go through them all and list those that have this issue?

Thank you.

**Comment by giladgray** [comment]
@vladeck sure, a list like that would be helpful

**Comment by vladeck** [comment]
Additional icons that exhibit similar problems: `calendar` and `clipboard` (somewhat).

**Comment by pkwi** [comment]
there is definitely something wrong with that `eye-open` icon. Thanks for bringing this up to our attention @vladeck!

`calendar` and `clipboard` icons use the odd number of pixels so they might look a tiny bit off when resized.

**Comment by llorca** [comment]
`social-media` also looks messed up:
![image](https://user-images.githubusercontent.com/199754/38118693-766ddbca-3371-11e8-8e99-9df4966236fc.png)

**Comment by pkwi** [comment]
I have replaced Social Media and Heart icons here https://github.com/palantir/blueprint/pull/2349. There is something extremely odd about the Heart icon as the icon looks perfectly fine here https://github.com/palantir/blueprint/blob/develop/resources/icons/20px/heart.svg

**Comment by vladeck** [comment]
I have noticed something but I'm not at my computer to confirm: if I show eye-open icon, but use CSS to size it (16x16 grid version will be used) - it is centered correctly no matter the rendered size. However, using `props` to size it over 20 (20x20 grid version will be used) will render icon that is not centered. Maybe there is some kind of issue with 20x20 grid?

**Comment by pkwi** [comment]
Seems that some issues were happening due to the svgo optimization. Re-exporting the heart icon fixed the issues [here](https://github.com/palantir/blueprint/pull/2349).

**Comment by giladgray** [comment]
@llorca @pkwi is this issue resolved?

**Comment by llorca** [comment]
yes, everything that been mentioned so far has been fixed. we can reopen if another bug comes up
