### ISSUE TITLE
InputGroup onChange should be declared as React.FormEvent<HTMLInputElement>

### ISSUE THREAD

**Issue by thasner** [palantir/blueprint#2322]
[The docs](http://blueprintjs.com/docs/v2/#core/components/forms/input-group.javascript-api) say "Use event.target.value for new value.", but this is not possible without a cast from `HTMLElement` to `HTMLInputElement`. BP Docs uses this ick https://github.com/palantir/blueprint/blob/33ddd80f15c5e5102f683132a0f731e18cba567d/packages/docs-theme/src/components/baseExample.tsx#L108

**Comment by giladgray** [comment]
@thasner great idea, got a PR for me?

**Comment by giladgray** [comment]
btw that `handleStringChange` is to simplify the unwrapping process, not to sidestep the element type.

**Comment by thasner** [comment]
I've got something started on https://github.com/palantir/blueprint/pull/2324, but don't have time to get a dev environment set up to figure out what's going on with compilation. Hopefully someone else can pick it up

**Comment by giladgray** [comment]
@thasner this doesn't actually seem fixable currently via props typings... `React.InputHTMLProps<T>` already [declares `onChange?: ChangeEventHandler<T>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1444), but that actually conflicts with the `FormEventHandler` definition in the base `DOMAttributes` interface. 

the end result is that an inline event handler cannot properly type the event arg:
```tsx
( <InputGroup onChange={evt => /* evt is any */} /> )
```

so my takeaway here is that as you already have to define the type of the event arg in your bound handler anyway, there's really little value in a fix here.

```tsx
class MyComponent extends R.C {
    render() { return <InputGroup onChange={this.handleChange} />; }
    handleChange = (evt: React.FormEvent<HTMLInputElement>) => { /* cool */ }
}
```

**Comment by giladgray** [comment]
won't fix. see comment above.

**Comment by lwouis** [comment]
Posting here in case someone faces the same issue I did.

Here is the issue: declaring the handler as for example:

```ts
const handler: React.FormEvent<HTMLInputElement> = (event) => {
    console.log(event.target.value) // typescript complains here that 'value' doesn't exist on the type
}
```

Here is the fix: declaring with another type, which is compatible with Blueprint, but correctly shows the existence of 'value':

```ts
const handler: ChangeEventHandler<HTMLInputElement> = (event) => {
    console.log(event.target.value)
}
```
