### ISSUE TITLE
"Cannot read property 'show' of null" when using ContextMenu.show (Blueprint v2)

### ISSUE THREAD

**Issue by gflores** [palantir/blueprint#2326]
After the migration to blueprint 2.0, I am getting an error with this code:

`    menu = <Menu>{menuItems}</Menu>;`
`    let clientX = get(event, "clientX");`
`    let clientY = get(event, "clientY");`
 `   this.setState({selectedFileId: fileId}, () => {`
**`      ContextMenu.show(menu, {left: clientX, top: clientY});`**
`    });`

It breaks at the `ContextMenu.show(...)`

![selection_042](https://user-images.githubusercontent.com/1119607/38010040-c22f4c1c-3289-11e8-9248-3a951a08445a.png)

Any idea ?

**Comment by giladgray** [comment]
@gflores this would suggest that line 100 is returning `null`. are there any other console errors?

**Comment by gflores** [comment]
No It's the only error I see...
![Uploading Selection_043.png…]()

I am calling this from an onClick handler

**Comment by gflores** [comment]
But it was working before the migration to v2

**Comment by gflores** [comment]
Found the answer actually, I had to change from\

```
    this.setState({selectedFileId: fileId}, () => {
      ContextMenu.show(menu, {left: clientX, top: clientY});
    });
```
to

```
    this.setState({selectedFileId: fileId});
    ContextMenu.show(menu, {left: clientX, top: clientY});
```

I guess it doesn't like to show() in the callbacb of setState
