### ISSUE TITLE
Control-group element borders don't necessarily align in dark theme

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#233]
### Bug Report

- __Package version(s)__: v1.1.0
- __Browser and OS versions__: Chrome 54.0.2840.71 (64-bit) on OS X 10.11.6

#### Describe the issue:

In the dark theme, `intent`-ful control group elements don't necessarily have aligned borders. See this example from the numeric stepper:

![image](https://cloud.githubusercontent.com/assets/443450/20587883/af1dad62-b1c5-11e6-9df4-263e393600ef.png)

#### Actual behavior:

Note that the red input-field border doesn't align with the red buttons' edges.

#### Expected behavior:

Would be nice if they did align. Sort of a tricky case though.

**Comment by cmslewis** [comment]
@llorca would love your thoughts here

**Comment by llorca** [comment]
Good catch! I'll look into it, numerical stepper revealed a few visual bugs around dark theme control groups
