### ISSUE TITLE
Slider and RangeSlider do not properly redraw on container resize

### ISSUE THREAD

**Issue by iongion** [palantir/blueprint#2338]
### Bug report

- 2.x
- Any OS and browser

#### Steps to reproduce

1. Add a Slider or RangeSlider in a fluid container (one that resizes when you resize the window)
2. Resize the window
1. The slider does not visually update(internally it does, as it makes a small jump to the proportional new value)

#### Actual behavior

The slider does not properly visually update its heads locations when resizing the parent container

#### Expected behavior

The slider should visually update its dimension proportionally to its width

I have attached a GIF with this behavior

![slider-on-resize](https://user-images.githubusercontent.com/867609/38130097-fb7f329c-3401-11e8-9acc-8bd0793fad45.gif)

You can see that the correct redrawing happens(the jump) at the first mouse click attempt on head or track.

It should behave like this:
![slider-on-resize-proper](https://user-images.githubusercontent.com/867609/38133165-60a019f0-340e-11e8-90a5-ea73de1935f5.gif)

For my slider cases, I mitigate it using this code, that I call in the windows resize, after changing state

```js
  fixSliders() {
    if (this.timelineRangeSliderRef.current) {
      const slider = this.timelineRangeSliderRef.current.trackElement.parentNode;
      const track = slider.querySelector('.pt-slider-track');
      const progress = slider.querySelector('.pt-slider-progress');
      const handles = Array.prototype.slice.call(slider.querySelectorAll('.pt-slider-handle'));
      if (!slider || !track) {
        return;
      }
      try {
        const [left, right] = handles;
        const scale = track.offsetWidth;
        const handle = left.offsetWidth;
        const leftPercentage = this.state.playbackTimeline.range[0] * (100 / TIMELINE_SCALE_MAX);
        const leftProportionalPosition = ((leftPercentage * scale) / 100) - handle;
        const rightPercentage = this.state.playbackTimeline.range[1] * (100 / TIMELINE_SCALE_MAX);
        const rightProportionalPosition = ((rightPercentage * scale) / 100) - handle;
        const progressProportionalWidth = rightProportionalPosition - leftProportionalPosition;
        const progressProportionalPosition = leftProportionalPosition + handle;
        // set new sizes and locations
        left.style.left = `${leftProportionalPosition}px`;
        right.style.left = `${rightProportionalPosition}px`;
        progress.style.width = `${progressProportionalWidth}px`;
        progress.style.left = `${progressProportionalPosition}px`;
      } catch (error) {
        console.error(error);
      }
    }
    if (this.timelinePlayheadSliderRef.current) {
      const slider = this.timelinePlayheadSliderRef.current.trackElement.parentNode;
      const track = slider.querySelector('.pt-slider-track');
      const progress = slider.querySelector('.pt-slider-progress');
      const left = slider.querySelector('.pt-slider-handle');
      if (!slider || !track || !left) {
        return;
      }
      try {
        const scale = track.offsetWidth;
        const handle = left.offsetWidth;
        const handleMiddle = handle / 2;
        const percentage = this.state.playbackTimeline.playhead * (100 / TIMELINE_SCALE_MAX);
        const proportionalPosition = ((percentage * scale) / 100) - handleMiddle;
        const progressProportionalWidth = proportionalPosition + handleMiddle;
        left.style.left = `${proportionalPosition}px`;
        progress.style.width = `${progressProportionalWidth}px`;
      } catch (error) {
        console.error(error);
      }
    }
  }
```

Called
```js
      this.windowResizeListener = () => {
        const verticalOffset = HEADER_HEIGHT + FOOTER_HEIGHT + HEADER_HEIGHT;
        this.setState({
          ...this.state,
          container: {
            width: window.innerWidth,
            height: window.innerHeight - verticalOffset,
          },
        }, () => {
          this.fixSliders();
        });
      };
      window.addEventListener('resize', this.windowResizeListener);
      this.windowResizeListener();
```

I have created this CodeSandbox demo that you can access here https://codesandbox.io/s/3v2qr0j5mm

**Comment by iongion** [comment]
I have created this CodeSandbox demo that you can access here https://codesandbox.io/s/3v2qr0j5mm

**Comment by iongion** [comment]
@reiv Thank you, I might indeed, I am using percentage myself, never knew `forceUpdate` existed.
Feel free to close this, the idea using percentage by default will make the sliders even more useful, exposing an additional `percentValue` will make it even more generic(not related to the issue)

Feel free to close this whenever you want.

**Comment by reiv** [comment]
It's still a valid issue IMO. The current slider implementation assumes that the width does not change during the component's lifecycle, making it bug out if used in resizable/responsive layouts. `forceUpdate()` is a workaround, but it feels hacky.

**Comment by llorca** [comment]
Good points! Sounds like we could use percentages indeed, but let's have Gilad chime in next week, I'd assume there's a reason he didn't go the percentage route in the first place

**Comment by reiv** [comment]
@llorca I went ahead and tried rewriting the thing to use percentages. At first glance it seems to work OK but I'm sure there's a bunch of minor quirks that need to be ironed out.

**Comment by giladgray** [comment]
percentages seems legit, honestly a little bummed i didn't build it that way originally. i'm sure we can iron it out.
