### ISSUE TITLE
Local development issue

### ISSUE THREAD

**Issue by ugogo** [palantir/blueprint#234]
### Bug Report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Chrome OSX

#### Describe the issue:

Hey guys 👋 

I just cloned your project and tried to submit my first PR, but I ran into an issue : local changes doesn't change anything into the local server.

##### What did I do?

- `git clone https://github.com/palantir/blueprint.git && cd blueprint`
- `npm install && npm run bootstrap && npm run gulp` as said into the [README](https://github.com/palantir/blueprint/blob/master/README.md#development)
- Navigate to `localhost:9000/packages/docs/dist/`
- Add `display: none !important;` (just for a very basic test) into `packages/core/src/components/callout/_callout.scss`

#### Actual behavior:

The page reload (`http://localhost:9000/packages/docs/dist/#components.callout`), but callouts are still visible, and no sign of my change into the Chrome devtools.

#### Expected behavior:

Changes taken into account.

I'm apparently missing something, if anyone can help me,
Thanks 🙏

**Comment by llorca** [comment]
I can repro on my end. We'll get to this ASAP

**Comment by giladgray** [comment]
For now, you can just reload the page! We're working on the live reload
experience but it certainly still recompiles.

**Comment by adidahiya** [comment]
what's the output in your `gulp` console? is it picking up the .scss changes and re-bundling the docs application?

**Comment by ugogo** [comment]
@giladgray Even if I reload the page myself, there's no change.

I recorded my screen : https://www.dropbox.com/s/5jrxnguraf8hzu1/blueprint-local-dev-issue.mov?dl=0

**Comment by ugogo** [comment]
Can I provide you more informations to help you?

**Comment by giladgray** [comment]
@ugogo it seems like livereload does not work for individual packages, but it does work for the docs package itself. try saving `docs.scss` after editing `_callout.scss` and see if that causes your changes to appear in the browser.

**Comment by ugogo** [comment]
@giladgray Still no changes.
I also removed everything into `blueprint.scss` and `docs.scss`, and still no changes ☹️

**Comment by ugogo** [comment]
Maybe those leads can help you :

Leads 1 - I removed everything into `docs.scss` and `blueprint.scss`, and nothing changes too. Then, I tried `npm run gulp sass` manually, and with it, I had some warnings ('files cannot be empty', yey!)

Leads 2 - I removed the `docs/docs/docs.css` file, reloaded the page, the style was well removed. But, even after relaunching `npm run gulp`, the dist CSS was not re-generated.

**Comment by giladgray** [comment]
are you actually looking at localhost:9000/packages/docs/dist/? 
as opposed to localhost:9000/docs/, which is the compiled GHPages site and is _not_ updated during development (only `npm run build:site`).

**Comment by ugogo** [comment]
Hah nice catch for this one.
Running manually `npm run gulp sass` did update the CSS for `localhost:9000/packages/docs/dist`!

**Comment by ugogo** [comment]
Ok, I added `sass` after `sass-variables` here: https://github.com/palantir/blueprint/blob/master/gulp/watch.js#L23, it works.
But I don't think it's a good idea, and if the linter throw an error, there's no coming back \o/

**Comment by ugogo** [comment]
Thanks guys 👍
