### ISSUE TITLE
Tabs2 not rendered properly when using react-hot-loader v4

### ISSUE THREAD

**Issue by SuhairZain** [palantir/blueprint#2345]
### Bug report

- __Package version(s)__: Tested both core@1.35.3 and core@1.35.7.
- __Browser and OS versions__: macOS High Sierra, Google Chrome 65.0.3325.181

#### Steps to reproduce

1. Use react-hot-loader-v4 during development
1. Use Tabs2 component to render 2 tabs

#### Actual behavior
<img width="633" alt="screen shot 2018-03-31 at 9 10 55 am" src="https://user-images.githubusercontent.com/5249794/38159595-57a26b44-34c9-11e8-8b83-8b9f6718af5a.png">
<img width="447" alt="screen shot 2018-03-31 at 9 53 46 am" src="https://user-images.githubusercontent.com/5249794/38159602-70a9ea90-34c9-11e8-8e19-ef29f067d29e.png">

The tabs do not render properly. The titles are not displayed and the screen is split into 2 horizontally, with each tabs taking half width of the screen. The rendered HTML when running in dev(with react-hot-loader doing HMR) and in production(with no HMR) is attached.

#### Expected behavior

<img width="856" alt="screen shot 2018-03-31 at 9 11 43 am" src="https://user-images.githubusercontent.com/5249794/38159596-58055574-34c9-11e8-9e36-1ed06c21c378.png">
<img width="510" alt="screen shot 2018-03-31 at 9 53 35 am" src="https://user-images.githubusercontent.com/5249794/38159601-703eb91e-34c9-11e8-9f07-dbb7e5a43e9b.png">
The titles should be displayed and each tab should take up the full width.

**Comment by reiv** [comment]
This has to do with the way react-hot-loader proxies components, making checks such as this fail:

Blueprint 2.0 uses a more robust check which works with react-hot-loader:

**Comment by giladgray** [comment]
@SuhairZain this has been in fixed in Blueprint 2.0. 

if you truly need it in a 1.x release, I encourage you to explore porting the fix from #2099 to the `release/1.x` branch. the team does not have bandwidth to work on this request, but we'll happily review PRs.
