### ISSUE TITLE
Inconsistency in validateProps documentation

### ISSUE THREAD

**Issue by billyjanitsch** [palantir/blueprint#2347]
[`AbstractComponent`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/abstractComponent.ts#L68) and [`AbstractPureComponent`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/abstractPureComponent.ts#L68) both contain a comment regarding `validateProps` that is no longer true: "In contrast to propTypes, these runtime checks are _always_ run, not just in development mode."

As of #977, `validateProps` is only run in development. Was this an intentional change?

**Comment by giladgray** [comment]
@billyjanitsch yep definitely intentional! Didn't realize the docs said that. would happily accept a PR to fix the language.

**Comment by billyjanitsch** [comment]
Happy to fix the language, but are you sure this behavior is desirable? It would be fine if implementations of `validateProps` only ever printed to the console, but some [throw](https://github.com/palantir/blueprint/blob/e53d5d4c266d8a00c03c2b4079debee91e8337d1/packages/core/src/components/popover/popover.tsx#L385) [errors](https://github.com/palantir/blueprint/blob/e53d5d4c266d8a00c03c2b4079debee91e8337d1/packages/table/src/table.tsx#L866), which means that different functional code paths will be followed in dev vs. prod. Generally this is considered dangerous -- React itself goes to great lengths to avoid doing this (which is why `propTypes` don't throw).

It seems like the original intent of `validateProps` was to be a hard-erroring runtime check in all environments (intentionally different from `propTypes` in this regard). It seems like Blueprint is now moving towards console errors, which is fine, but I would suggest finishing that migration before moving to a dev-only check.

**Comment by giladgray** [comment]
There are some show stopping errors that throw, but most validations are
just warnings as they're not game-breaking.

This is intentional; the docs are out of date. We don't want to run
validation in prod. Dev errors make it clear that you should fix it before
shipping.

>
