### ISSUE TITLE
Question: suggest charts/graphs library which can be used with blueprint

### ISSUE THREAD

**Issue by neevany** [palantir/blueprint#235]
please suggest charts/graphs library which can be used with react/blueprint

**Comment by adidahiya** [comment]
Hi @neevany, we're actively working on [palantir/plottable](https://github.com/palantir/plottable) now (after a short development hiatus...) and one of our goals in the next few months is to achieve high quality interop with Blueprint via a declarative React API layer that will be a new package called `@blueprintjs/chart`. Stay tuned; we'll update this issue with major milestones.

cc @palantir/plottable

**Comment by giladgray** [comment]
https://github.com/palantir/plottable! 3.0.0 is out and it's better than ever, with plenty more to come in the coming months.

**Comment by gaving** [comment]
In a similar vein, I don't suppose anybody on the Palantir team has any recommendations for a library that would handle network graphs (preferably interactive)? Had a look at plottable but doesn't seem to support this.

I'm currently trying to theme VisJS to fit in with Blueprint, but it's a bit of a chore. :face_with_thermometer:

**Comment by cmslewis** [comment]
@gaving we have a graph library internally, but it's not in a state for open source yet.

**Comment by gaving** [comment]
@cmslewis Figured as much, seen some screens of Gotham and it looks neat. :)

But hope you’s eventually get around to doing that, there’s not much in the space.

**Comment by ysz** [comment]
@adidahiya update about palantir/plottable  interop `@blueprintjs/chart` ?
