### ISSUE TITLE
Add overlayProps as a prop on Dialog

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2354]
- __Package version(s)__: 2.0.1

This would be useful to have. Right now I am experiencing an issue where a click event inside a Dialog (or the Overlay) is bubbling up.

**Comment by giladgray** [comment]
@tgreen7 how would the addition of `overlayProps` solve your problem?

**Comment by tgreen7** [comment]
@giladgray I pretty sure I could use e.stopPropagation() inside the overlay onClick() to prevent the event from escaping. But I am not sure if that would solve it.

**Comment by llorca** [comment]
Cool, will close in this issue for now
