### ISSUE TITLE
[Design] BP Docs doesn't scale well

### ISSUE THREAD

**Issue by adamstorr** [palantir/blueprint#2355]
### Bug report
- __Browser and OS versions__: Happens on all browsers

#### Steps to reproduce
Resize the browser to 1000px or less.

#### Actual behavior
Page doesn't shrink well below 1000px

#### Expected behavior
Padding exists somewhere (`.docs-app`?) so it's not squished.

![image](https://user-images.githubusercontent.com/155064/38279793-d873b004-3756-11e8-9cf0-fe819c46eaec.png)

**Comment by llorca** [comment]
Fixed in https://github.com/palantir/blueprint/pull/2305
