### ISSUE TITLE
Navbar align left causes issues in children

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#2358]
### Bug report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Chrome 65, Windows 10

#### Steps to reproduce

1. Create a `<Navbar>` component and add a `<Button>` in it. Set the width of this button to something large like 200px.
1. The new button has its text and icon aligned to the left due to the alignment being inherited from the Navbar.
1. This is the CSS rule causing the problem:

![image](https://user-images.githubusercontent.com/4096676/38291486-98930b7a-37a5-11e8-8fbd-9e23b79e158c.png)

#### Actual behavior

Text and icon are aligned to the left.

#### Expected behavior

Text and icon are aligned to the center.

![image](https://user-images.githubusercontent.com/4096676/38291531-c05aa60e-37a5-11e8-84d3-e56a6cd524c8.png)

This is a regression in 2.0.0.

**Comment by llorca** [comment]
@shravan2x thanks for the report! we'd really appreciate a contribution, if you get a chance

**Comment by shravan2x** [comment]
@llorca A temporary fix I use is including this code to reset alignment on buttons:

```css
.pt-align-fix .pt-button-text {
    flex: none;
}
```

But I'm not too familiar with how things are styled in this library and I don't want to inadvertently break something else with a PR. I'll leave it anyone else.
