### ISSUE TITLE
Cant hover a rightElement button while input focused

### ISSUE THREAD

**Issue by Reaverart** [palantir/blueprint#236]
### Bug Report

- __Package version(s)__: (1.1.0)
- __Browser and OS versions__: (chrome 54, osX 10.11.6)

#### Describe the issue:

If input group lays inside of control group I cant hover a rightElement button of input group when input focused.
It happens because of this rule https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/_control-group.scss#L85
So inputs lays over rightElement button when focused
```
<div class="pt-control-group">
  <div class="pt-input-group">
    <span class="pt-icon pt-icon-search"></span>
    <input type="text" placeholder="Search..." class="pt-input" style="padding-right: 30px;">
    <span class="pt-input-action">
      <button class="pt-button pt-icon-small-cross pt-intent-warning pt-minimal" type="button"></button>
    </span>
  </div>
</div>
```
#### Actual behavior:

button unavailable

#### Expected behavior:

button should be available

**Comment by cmslewis** [comment]
Fixed by #239
