### ISSUE TITLE
[dev] Reduntant bundling of "iconSvgPaths.js"

### ISSUE THREAD

**Issue by hzub** [palantir/blueprint#2364]
### Bug report

- core@2.0.0-rc.4, icons@2.0.0-rc.4, datetime@2.0.0-rc.4 
- webpack 3.11.0

#### Steps to reproduce

1. Import few components from `datetime` package
2. Import few components from `core` package
3. Build an application using webpack with default module bundling rules

#### Actual behavior

A large file named `iconSvgPaths.js` is being bundled to the app twice. It doesn't seem like webpack issue, since it sees this dependency as a separate module.

Report from Webpack Bundle Analyzer:
![zrzut ekranu 2018-04-05 o 13 40 38](https://user-images.githubusercontent.com/8265332/38364181-ddfaeb8c-38d7-11e8-88a8-3c9ad1471821.png)

#### Expected behavior

`iconSvgPaths.js` is bundled only once.

**Comment by giladgray** [comment]
@hzub that image shows you have two copies of `icons` installed: one at the root and one inside `core`. you can resolve this with some dependency juggling, yarn.lock surgery, or by configuring webpack aliases so all references to `icons` resolve to one module.

**Comment by giladgray** [comment]
@hzub also try bumping to actual `2.0.0`!

**Comment by giladgray** [comment]
@hzub i'm going to close this as the fix is on you to resolve the duplicated `icons` dependency. feel free to comment or re-open if you have more questions.
