### ISSUE TITLE
Large Tag Input "X" Buttons incorrect Size

### ISSUE THREAD

**Issue by sbnon** [palantir/blueprint#2365]
In 2.0.0, the Tag Input's tags have too-small "X" buttons when in "large" mode.

To reproduce:

1. Go to: http://blueprintjs.com/docs/v2/#core/components/tag-input
2. Activate the "Large" toggle
3. The tags get bigger, but the "x" buttons say the same size.

**Comment by giladgray** [comment]
ah yep! should be easy to fix now that we have these `large` props on everything.
