### ISSUE TITLE
Datepicker CSS not showing

### ISSUE THREAD

**Issue by studioraygun** [palantir/blueprint#2369]
I've included `import { DateTimePicker } from "@blueprintjs/datetime"` which loads the component correctly, but it appears unstyled.

Adding `import '@blueprintjs/core/dist/blueprint.css'` doesn't seem to do anything however, when I import a Button, it appears styled correctly.

Actually my goal is to isolate the styling for this one component and use it as standalone within my app.

**Comment by giladgray** [comment]
to clarify: you've only done half the work @studioraygun. you imported the datetime JS code but have not yet included `blueprint-datetime.css` in your app, so of course the `DatePicker` is unstyled.

**Comment by badams** [comment]
Would be nice to get this added to the documentation somewhere, its not immediately obvious by looking at the documentation or example code

**Comment by antoniovj1** [comment]
If anyone need the CDN link for the styles, is here:

https://unpkg.com/@blueprintjs/datetime@2.0.3/lib/css/blueprint-datetime.css

**Comment by chandlervdw** [comment]
I'm importing `blueprint-datetime.css` but my styles are all jacked up and look nothing like the example at https://blueprintjs.com/docs/#datetime/dateinput – They're getting somewhat styled but it looks terrible. What am I missing?

**Comment by giladgray** [comment]
https://blueprintjs.com/docs/#blueprint/getting-started step 4

**Comment by switz** [comment]
As far as I can see, these instructions are not on that page.

**Comment by adidahiya** [comment]
@switz it's still there, just got reordered to step 3. The "simplest" way is to use a `<link>` tag in your HTML. Most web apps will use a bundler like webpack to load CSS `@import`s onto the page ([see an example in the blueprint docs-app here](https://github.com/palantir/blueprint/blob/659034c2c2c12509c5113f9b577c719373809cac/packages/docs-app/src/index.scss#L11)).

**Comment by tdehollain** [comment]
Unless I missed it it is not super easy to find what CSS file needs to be imported for this package, like the path and file name need to be guessed from the examples' pattern. 
I think it would be helpful to add a mention about this, maybe on the [main Datetime page](https://blueprintjs.com/docs/#datetime)

**Comment by adidahiya** [comment]
@tdehollain done in https://github.com/palantir/blueprint/commit/92a0c72324df63edca3ad56006baba763876636e
