### ISSUE TITLE
Checkbox component does not work in controlled mode

### ISSUE THREAD

**Issue by TheRealSpaceShip** [palantir/blueprint#2370]
### Bug report

blueprintjs/core: 2.1.1,
Browser: Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
OS: macOS Sierra 10.12.6 (16G1314)

#### Steps to reproduce

1. Use `Checkbox` component
2. Add `checked` and `onChange` property
3. Click on component

#### Actual behavior

Checkbox change indicator but `onChange` does not invoke

#### Expected behavior

Checkbox should invoke `onChange` when click on component happend

#### Example code
```
import React, {Component} from 'react';
import {Checkbox} from '@blueprintjs/core';

class Test extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isChecked: false
        };
    }

    handleEnabledChange() {
        this.setState({isChecked: !this.state.isChecked});
    }

    render() {
        return (
            <Checkbox
                checked={this.state.isChecked}
                label={this.state.isChecked ? 'Checked' : 'Unchecked'}
                onChange={this.handleEnabledChange}
            />
        );
    }
}

export default Test;
```
#### Note
I am not sure but probably this [change](https://github.com/palantir/blueprint/pull/2323/commits/6c8a29f65053310ee5bc399c7459d4f4dc379c78#diff-c3a6a2b0fe2f0ed4fefa920240aeb9f4R177) is cause this issue

**Comment by giladgray** [comment]
ah nuts seems i forgot to invoke the `onChange` prop in the new callback there! def a real bug. should be easy to resolve with a `safeInvoke(this.props.onChange, evt)` after line 218.

**Comment by tnrich** [comment]
Yikes this got us for a while too until we found this issue and pinned to an earlier version. Thanks @TheRealSpaceShip

**Comment by TheRealSpaceShip** [comment]
No problems guys. Thanks for quick response on this issue
