### ISSUE TITLE
404 on http://blueprintjs.com/docs/v2/#resources (Sketch files missing)

### ISSUE THREAD

**Issue by ramaboo** [palantir/blueprint#2372]
On http://blueprintjs.com/docs/v2/#resources both the links to download sketch files are broken :(

**Comment by reiv** [comment]
Already fixed but not yet updated: https://github.com/palantir/blueprint/pull/2363

[Core Kit.sketch](https://github.com/palantir/blueprint/tree/develop/resources/sketch/Core%20Kit.sketch), [Blueprint Colors.sketchpalette](https://github.com/palantir/blueprint/tree/develop/resources/sketch/Blueprint%20Colors.sketchpalette)

**Comment by giladgray** [comment]
closing as resolved. will update site soon. in the meantime, `s/master/develop/` on the url.
