### ISSUE TITLE
Tooltip pops up repeatedly on changing tab

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#2373]
### Bug report

- __Package version(s)__: 2.1.1
- __Browser and OS versions__: Chrome 65, Windows 10

#### Steps to reproduce

1. Wrap a button in a tooltip and place this inside an input group.
1. Pass focus to the button.
1. Change the tab out and back in.

Eg: The "Enter the password" example in the [docs](http://blueprintjs.com/docs/v2/#core/components/forms/input-group).

#### Actual behavior

Tooltips pops up every time the tab is switched to.

#### Expected behavior

Tooltip shouldn't display on its own.

**Comment by giladgray** [comment]
@shravan2x what version of `popper.js` do you have installed? there's a show-stopping bug in 1.14.2, so ensure it's not that one.

**Comment by shravan2x** [comment]
This issue is on 1.14.3.

**Comment by shravan2x** [comment]
@giladgray That seems to resolve the issue. Is this intended behavior?
