### ISSUE TITLE
@blueprintjs/datetime not found

### ISSUE THREAD

**Issue by BaReinhard** [palantir/blueprint#2376]
### Bug report

- __Package version(s)__: N/A
- __Browser and OS versions__: N/A

#### Steps to reproduce

1. npm install @blueprintjs/datetime

#### Actual behavior

```
npm install @blueprintjs/datetime
npm ERR! code E404
npm ERR! 404 Not Found: @blueprintjs/datetime@latest
```

#### Expected behavior

Expected the module to install.

**Comment by giladgray** [comment]
@BaReinhard it certainly exists: https://www.npmjs.com/package/@blueprintjs/datetime
try installing a specific version? perhaps your `.npmrc` is interfering?

**Comment by BaReinhard** [comment]
Ah, yes I believe it may be. Thanks for the quick response. Need to do some more reading up on it. thanks
