### ISSUE TITLE
TimePicker is losing focus

### ISSUE THREAD

**Issue by webpty** [palantir/blueprint#238]
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Chrome 54, Mac OS 10.12

#### Describe the issue:

This is my time picker code
```
<TimePicker onChange={this.handleStartTimeChange} value={this.state.startTime} />
```
I'm trying to reproduce the example in the docs page, however, incrementing the value either by number pad or by arrow keys causes the focus to be lost and requires to manually refocus in order to continue editing the values.

#### Actual behavior:

Loses focus as soon as the value is changed

#### Expected behavior:

Keep focus in order to continue editing the values.

**Comment by cmslewis** [comment]
I @webpty, I'm struggling to reproduce this on Chrome 54, Safari, and Firefox—all on OS X 10.11. Arrow-key shortcuts are working as expected for me in each browser (I'm on my laptop, so I can't test numpad at the moment). Could you maybe attach an animated GIF/some more code/some `console.log`s or something? That'll help me get to the bottom of this.

**Comment by webpty** [comment]
@cmslewis, thanks for the quick reply.

It seems I was wrong about the num pad, as you can see here I am able to delete and enter the desired numbers.

2 actions lead to the loss of focus: tab and arrow keys (up and down)

![timepicker](https://cloud.githubusercontent.com/assets/11739306/20628886/afc748fe-b2f6-11e6-84a4-39450cae34af.gif)

**Comment by cmslewis** [comment]
Gah, that looks infuriating, haha. Thanks for the GIF; I'll try to repro on my end soon.

**Comment by llorca** [comment]
I'm not able to repro on v1.6.0. @webpty were you able to figure out a solution?

**Comment by cmslewis** [comment]
// Emerging from the rabbit hole of the past year

Still have never been able to repro this on our end. Closing this issue for now. @webpty ping us if you still see it.

**Comment by webpty** [comment]
Thanks for this.
Unfortunately the project that used blueprint was scratched and I haven't worked with it since.
Thanks for the followup

**Comment by cmslewis** [comment]
@webpty Gotcha, I know how that goes.
