### ISSUE TITLE
Documentation is a dead link

### ISSUE THREAD

**Issue by schicks** [palantir/blueprint#2380]
#### Steps to reproduce

1. Go to [the documentation page](http://blueprintjs.com/docs/v2/)
2. Watch it be blank
3. Observe this message in the console; `TypeError: Not enough arguments to CSSStyleSheet.insertRule.`

#### Actual behavior

A working documentation page

#### Expected behavior

A blank page with a console error

**Comment by giladgray** [comment]
@schicks which browser are you using? Name and version. Cannot diagnose this without more information, as it definitely works in most browsers.
