### ISSUE TITLE
Unexpected table focus when multiple tables have focus

### ISSUE THREAD

**Issue by rayshan** [palantir/blueprint#2381]
### Bug report

- __Package version(s)__: @blueprintjs/table@2.0.0
- __Browser and OS versions__: Chrome 65, macOS 10.13.4

#### Steps to reproduce

App has 3 tables with `enableFocusedCell` set to `true`. Hit tab immediately after page load.
![screen shot 2018-04-11 at 10 20 31 am](https://user-images.githubusercontent.com/3760840/38632629-2c8b0ba8-3d72-11e8-950f-debf5826f656.png)

#### Actual behavior

Focus in bottom table moves to the right by 1 cell

![screen shot 2018-04-11 at 10 24 36 am](https://user-images.githubusercontent.com/3760840/38632784-8fece14e-3d72-11e8-8c5e-57d22b26096e.png)

#### Expected behavior

Focus in top table moves to the right by 1 cell

===

This can be fixed by not focusing until user interacts with the table: https://github.com/palantir/blueprint/issues/1098

**Comment by giladgray** [comment]
this seems quite expected to me: when multiple elements are focused at the same time, the last one will retain actual focus. so the fact that hitting tab affects the third table makes perfect sense.

having multiple focusable tables seems like an anti-pattern, as only one element can actually be browser-focused at a time. so this UI is going to be confusing to your users.

**Comment by giladgray** [comment]
@rayshan i would happily accept a contribution to fix #1098, but _this_ report is actually functioning as expected.

**Comment by rayshan** [comment]
That makes sense. I have some work to do to to defocus. Thanks.
