### ISSUE TITLE
Improve default date range picker

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2383]
Here is the current default date range picker: 

![image](https://user-images.githubusercontent.com/2730609/38697471-f9f71486-3e46-11e8-8701-865875056f3e.png)

I don't think most users would want to choose just 20 years in the past. I think that a default of 10 years on either side of the current date would be more appropriate for most people. 

I also think that it would be awesome to give an option to have the year field be a manual input field so users wouldn't have to be constrained whatsoever. Should be simple to change it to just a number input field.

(also note that setting a very large date range slows down the component greatly so that is not a good option for giving users an arbitrary date selection option: https://codesandbox.io/s/rrrkq5jj0q)

Just my 2 cents. 

Thanks!

**Comment by llorca** [comment]
We had this exact issue a year ago internally; we had 10 years in the past and in the future by default, and our experience, use cases and customers decided us on modifying the default to 20 years in the past. We don't plan on going back to previous defaults at this point; it's easily customizable anyway.

I would also not feel comfortable turning this select control into an input. This control shouldn't require typing, although it could be a second way of using it. We actually just started discussing the potential use of `<Select>` instead, let's continue the discussion over there https://github.com/palantir/blueprint/issues/2379

**Comment by tnrich** [comment]
Okay, makes sense about the defaults @llorca. I added my comments to https://github.com/palantir/blueprint/issues/2379
