### ISSUE TITLE
Spinner for Form loading state.

### ISSUE THREAD

**Issue by johnunclesam** [palantir/blueprint#2392]
### Bug report

- __Package version(s)__: 2.1.1

Is there a way to use `Spinner` for `form` loading state?

Is there a `Blueprint`'s `form` `loading` `state` at all?

**Comment by giladgray** [comment]
@johnunclesam there is no Blueprint "form" component (just the controls you put inside the form). however, it's pretty easy to put a `Spinner` in a `form` and make it centered. 

try using `<NonIdealState visual={<Spinner large />} />`

**Comment by johnunclesam** [comment]
Is there a beautiful way to dimmerize `NonIdealState`, like an opacity percentage? Useful when I overlap it on a form sending and something like this...

**Comment by llorca** [comment]
yeah, wrap it in a `<div>` and change the opacity of that div. for a more first class support, we'd need to add `style` prop support to `NonIdealState`
