### ISSUE TITLE
Closing tabs with an "X" button besides tab name? 

### ISSUE THREAD

**Issue by measdot** [palantir/blueprint#2395]
Thank you @giladgray.

I want to be able to show tabs with an icon in the right and a close button on the left, clicking on which closes the respective tab. Like below

<img width="343" alt="screen shot 2018-04-17 at 1 36 26 am" src="https://user-images.githubusercontent.com/5073326/38832340-e0936a5c-41df-11e8-8f12-f989f19f4df7.png">

and similar to this http://jsfiddle.net/vinodlouis/pb6EM/1/

Is there a way I could do that?

**Comment by giladgray** [comment]
@measdot `Tab` supports JSX content so you should easily be able to plop an `<Icon icon="remove" />` in there.
