### ISSUE TITLE
@import "~@blueprintjs/icons/src/icons" in other component scss.

### ISSUE THREAD

**Issue by johnunclesam** [palantir/blueprint#2397]
### Bug report

- __Package version(s)__: 2.1.1

#### Steps to reproduce

If I `@import "@blueprintjs/core/src/components/non-ideal-state/non-ideal-state";` it imports also: `@import "~@blueprintjs/icons/src/icons";` because in this latest file there is also:

```
@import "../../common/variables";
@import "../../common/mixins";
@import "~@blueprintjs/icons/src/icons";
```

Is this correct?

**Comment by giladgray** [comment]
@johnunclesam are you asking if the source code is correct? i would assume so! typically components will import the icons scss in order to use the icon mixins.

**Comment by johnunclesam** [comment]
Yes, but maybe I'm importing `non-ideal-state` and I dont' want to use font icons but `<Icon/>` component.

So I can choose to `@import "@blueprintjs/core/src/components/non-ideal-state/non-ideal-state";` without `icons`.

Do you agree?

**Comment by giladgray** [comment]
@johnunclesam simply importing the icons scss does not force you to use (or even to load) the icon fonts.
on closer inspection, it seems that this specific import is erroneous now. probably became unnecessary in 2.0. would happily accept a PR to remove it.

**Comment by johnunclesam** [comment]
https://github.com/palantir/blueprint/pull/2406
