### ISSUE TITLE
Inconsistency in interactive Card behavior

### ISSUE THREAD

**Issue by marvinsum** [palantir/blueprint#2398]
The docs states that when hovering over interactive cards...

> ...the elevation shadow on the card increases by two levels.

However, looking at the implementation, it seems like like the `box-shadow` on hover is always set to `$pt-elevation-3`, regardless of what the card's original box-shadow was. Which one is correct?

**Docs:**
http://blueprintjs.com/docs/v2/#core/components/card.interactive-cards

**Implementation:**
https://github.com/palantir/blueprint/blob/97023b90571bfe3da5e4b13d5990f48bec0438cd/packages/core/src/components/card/_card.scss#L93

**Comment by llorca** [comment]
set to `$pt-elevation-shadow-3` is correct. don't think these docs need to be so precise, we could just keep it to `the elevation shadow on the card increases.` wanna PR the docs @marvinsum?
