### ISSUE TITLE
Popover doesn't behave correctly when it has an autofocus'd input inside it 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#240]
### Bug Report

- __Package version(s)__: v1.1.0
- __Browser and OS versions__: OS X 10.11, Chrome 54

#### Describe the issue:

Weird things happen in the docs when you open a popover containing an `input` with `autofocus=true`. 

![popover-bug](https://cloud.githubusercontent.com/assets/443450/20616974/c78961f4-b29a-11e6-86cc-234a4577c514.gif)

#### Actual behavior:

Page jumps down several hundred pixels, and the popover doesn't open.

#### Expected behavior:

Something like this, but with the input field autofocused after the popover opens:

![expected](https://cloud.githubusercontent.com/assets/443450/20616996/f6959760-b29a-11e6-9f38-7f26695abfc2.gif)

**Comment by adidahiya** [comment]
> Page jumps down several hundred pixels

looks related to https://github.com/palantir/blueprint/issues/231

**Comment by eyalw** [comment]
This is still happening today in your docs

**Comment by adidahiya** [comment]
@eyalw this is a very old issue; if you're still seeing a similar problem, please file a new bug report.
