### ISSUE TITLE
rename lifecycle methods like props

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2402]
`popoverDidOpen`/`popoverWillClose` etc props are inconsistent with other callback prop names. I propose renaming these to:

- `popoverWillOpen` => `onOpening`
- `popoverDidOpen` => `onOpened`
- `popoverWillClose` => `onClosing`
- `popoverDidClose` => `onClosed`

The same changes will happen to the corresponding `Overlay` props. Note that the existing `onClose` callback fits nicely in this flow. And I'd happily add an `onOpen` for consistency.

This is identical to [CSSTransitionGroup](https://reactcommunity.org/react-transition-group/css-transition)'s lifecycle prop names.

**Comment by llorca** [comment]
answer from Gilad: because they're not methods but props

then, what about `didOpen` `willOpen` `didClose` `willClose`? or `onDidOpen` `onWillOpen` `onDidClose` `onWillClose`?

**Comment by llorca** [comment]
do the original proposal

**Comment by giladgray** [comment]
note that #2335 is also about a popover lifecycle bug
