### ISSUE TITLE
Dublicated header menu

### ISSUE THREAD

**Issue by Lojka59** [palantir/blueprint#2403]
### Bug report

- __Package version(s)__: 2.0.0
- __Browser and OS versions__: Win 7, Chrome 65

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/v2/#table/features
2. Hover column header
3. Left click on shevron (sorting menu shown)
4. Right click on menu item

#### Actual behavior

5. Second sorting menu shown (not expected)

#### Expected behavior

5. Second sorting menu never shown

**Comment by giladgray** [comment]
@Lojka59 hah yep this happens. the dropdown doesn't use `ContextMenu` so it doesn't have the singleton behavior. would happily accept a PR but the team will not fix this on our own.

**Comment by Lojka59** [comment]
not actual
