### ISSUE TITLE
Feature request: Allow configurable shortcuts for date range picker.

### ISSUE THREAD

**Issue by jonathanhotono** [palantir/blueprint#2404]
Current shortcuts is quite limited and predefined. I would like to request for a flexibility for developers to add/update shortcuts for date range picker.
![image](https://user-images.githubusercontent.com/6864547/38988643-509a12d6-4417-11e8-9366-0977744683e7.png)

Could probably add an extra props to receive shortcuts parameter based on moment/date object.

**Comment by giladgray** [comment]
this has always been supported via the `shortcuts` prop. docs!!!
![image](https://user-images.githubusercontent.com/464822/39009017-4ae9be02-43bf-11e8-8678-17a7aa40f352.png)

**Comment by jonathanhotono** [comment]
Whoops! Sorry for that! Must have been seeing things! I assume that this is the start/end date that receives normal date object?
![image](https://user-images.githubusercontent.com/6864547/39025135-9bf5521a-4488-11e8-8c53-6715336e00ca.png)
