### ISSUE TITLE
Chrome tooltip appears when hovering over Icon

### ISSUE THREAD

**Issue by jamesross3** [palantir/blueprint#2410]
Chrome doesn't display the "calendar" text for the icon in blueprint 1.x.
<img width="498" alt="screen shot 2018-04-19 at 10 49 36 pm" src="https://user-images.githubusercontent.com/24686554/39022298-630f0874-4424-11e8-97f9-2273f0295fc4.png">

**Comment by llorca** [comment]
is there an actual bug/problem here? that's actually an accessibility improvement over Blueprint 1.

if you want to get rid of it, set the `title` prop to `false` or `null`, as [described in the docs](http://blueprintjs.com/docs/v2/#core/components/icon)

**Comment by reiv** [comment]
Related: https://github.com/palantir/blueprint/issues/2321

@giladgray mentioned replacing the `<svg>` element's `<title>` tag with `<desc>`, which doesn't render as a tooltip, but still fulfills the accessibility requirement for screen readers and such.

**Comment by llorca** [comment]
sweet, we can follow up in #2321 then 👍
