### ISSUE TITLE
[Table] EditableCell styling regressing during editing

### ISSUE THREAD

**Issue by rayshan** [palantir/blueprint#2415]
### Bug report

- __Package version(s)__:

```
@blueprintjs/core..........[2.2.0]
@blueprintjs/table.........[2.1.0]
```

- __Browser and OS versions__:
macOS 10.13.4, Chrome 66

#### Steps to reproduce

1. Visit http://blueprintjs.com/docs/v2/#table/features.editing
1. Double click on cell with "editable"

#### Actual behavior

Active cell appears strange, but still functional

![screen shot 2018-04-20 at 2 11 10 pm](https://user-images.githubusercontent.com/3760840/39074363-e24c6bc8-44a5-11e8-9e02-de45508fb37c.png)

#### Expected behavior

Should look like this from the 2.0 release

https://12747-71939872-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html#table/features.editing

![screen shot 2018-04-20 at 2 25 55 pm](https://user-images.githubusercontent.com/3760840/39074566-d081949e-44a6-11e8-810a-62f0d33671c3.png)

**Comment by llorca** [comment]
Fixed in https://github.com/palantir/blueprint/pull/2413, will ship soon
