### ISSUE TITLE
[bug] missing space between label and requiredLabel

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2416]
Blueprint v2.2.1

<img width="499" alt="image" src="https://user-images.githubusercontent.com/654103/39115931-0395e610-46db-11e8-8ea1-e02434fdef94.png">

Problem appears to be here: https://github.com/palantir/blueprint/blob/31989e2efe6991d787d823e569baa28529985a82/packages/core/src/components/forms/formGroup.tsx#L90

Maybe it could be changed to something like this?

```js
return requiredLabel === true ? ' ' + FormGroup.DEFAULT_REQUIRED_CONTENT : requiredLabel;
```

**Comment by llorca** [comment]
Hmm, I thought we fixed this recently https://github.com/palantir/blueprint/pull/2180 https://github.com/palantir/blueprint/pull/2188

**Comment by giladgray** [comment]
that fix was for `helperText`, not `requiredText`, but the same approach should work. 

@will-stone prefer adding whitespace in the JSX rather than string concatenation.
