### ISSUE TITLE
Time Picker not present local time

### ISSUE THREAD

**Issue by thisroot** [palantir/blueprint#2421]
The DateInput not present local time when i pass default value from component.
Time printed without hours shift (GMT).

#### Steps to reproduce
GET => 2018-04-17T16:00:00.000Z
My local time +3
#### Actual behavior
Time Picker present 16:00,
#### Expected behavior
but must present 19:00

**Comment by thisroot** [comment]
The problem was soved.
Need to pass date formated to localtime.
Example:
1) Save time into my UTC (+3) locale 11.05.1018 00:00:00 
2) It save to backend as 10.05.2018 21:00:00
3) When i get the time from backend it need format to local UTC moment.utc(date).locale()

**Comment by metatron86** [comment]
is true => moment.utc(date).local().format()
