### ISSUE TITLE
[EditableText] Add value parameter to onEdit callback

### ISSUE THREAD

**Issue by TheMoniV** [palantir/blueprint#2422]
# Proposal: Editable Text - onEdit callback should have a value parameter
Concerning the `onEdit` event, it would be very helpful to make the Editable text component pass a value of it to the callback before it gets edited.
The prototype of the callback function would be as `onConfirm` event except _(as I mentioned before)_ that `value` would be the initial value of Editable text component:

> `onEdit`	`(value: string) => void` 
> 		Callback invoked after the user enters edit mode.

And thank you very much in advance for taking my proposal into consideration.

**Comment by giladgray** [comment]
@TheMoniV yeah seems reasonable! i'd be happy to review a PR submission.

**Comment by TheMoniV** [comment]
@giladgray I've made a PR, I'd be happy if you review it 😃 
Note: I didn't sign CLA yet because DocuSign won't load at all, I'll give it a try later.
