### ISSUE TITLE
Wiki Edit: Line 2 of Development Practices

### ISSUE THREAD

**Issue by cnrudd** [palantir/blueprint#2423]
Line 2 of Development Practices (https://github.com/palantir/blueprint/wiki/Development-practices)
is currently:
"Create a local feature branch off the latest `master` and switch to it."

Should it be:
"Create a local feature branch off the latest `develop` and switch to it."

The `master` branch's landing page suggests that this edit should be made.  It says:

> This branch contains the built assets for Blueprint's static landing page and documentation site.
> 
> To make contributions and see the source code, go to the repository's default branch.

The "repository's default branch" appears to be develop.

**Comment by giladgray** [comment]
fixed! thanks for the report @cnrudd 👍
