### ISSUE TITLE
<EditableText /> shows input field without styles

### ISSUE THREAD

**Issue by giftkugel** [palantir/blueprint#2425]
### Bug report

- __Package version(s)__: 
```
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "@blueprintjs/core": "2.2.0",
    "@blueprintjs/datetime": "2.0.2",
    "@blueprintjs/icons": "2.1.1",
    "@blueprintjs/select": "2.0.0"
```
- __Browser and OS versions__:  Chrome 59.0.3071.115 (OS independent)

#### Steps to reproduce

Open the BluePrint documentation and navigate to EditableText. Click.
Or use <EditableText /> in your application.

EditableText was not broken before.

#### Actual behavior

The input field and the span are visible. The input field has no styles.

![image](https://user-images.githubusercontent.com/9103924/39321355-1110854e-4987-11e8-9ad7-7841a4a61d7d.png)

![image](https://user-images.githubusercontent.com/9103924/39321389-294c61e6-4987-11e8-902b-7c26c0687606.png)

![image](https://user-images.githubusercontent.com/9103924/39321394-2eee5e56-4987-11e8-886c-adee49c14c97.png)

#### Expected behavior

Only one is visible and styled.

**Comment by giladgray** [comment]
@giftkugel already fixed. update to [`core` 2.2.1](https://github.com/palantir/blueprint/releases/tag/%40blueprintjs%2Fcore%402.2.1) for #2413

**Comment by giftkugel** [comment]
Saw that this issue was fixed with https://github.com/palantir/blueprint/pull/2413
Updated the `blueprintjs/core` to `2.2.1` and it works like a charm again. 😄

**Comment by giftkugel** [comment]
Yes, sorry. 😃 

Thank you.
