### ISSUE TITLE
Do you have any plan to make sidebar(sidemenu)?

### ISSUE THREAD

**Issue by ozluy** [palantir/blueprint#243]
If I am not wrong sidebar(sidemenu/drawer) is missing do you have plans to make sidemenu? 
Thanks You

**Comment by giladgray** [comment]
I wouldn't say it's _missing_, it's just not one single piece. Blueprint doesn't provide any layout components so "sidebar" doesn't mean a lot here. Fortunately, there are many easy ways to lay out a sidebar element that works for you. 

We've got you covered when you're ready to fill it! 
Consider [`Menu`](http://blueprintjs.com/docs/#components.menu) for lists and [`Card`](http://blueprintjs.com/docs/#components.card) for arbitrary content.

**Comment by adidahiya** [comment]
If you're looking for a floating sidebar over the entire page, you might be interested in the [`Overlay`](http://blueprintjs.com/docs/#components.overlay) component as the container

**Comment by ConneXNL** [comment]
I like the approach you guys are taking by making a lot of components composible from other components.

However I think for the non-devs of blueprint this isn't as obvious as the general user or the person which has to choose the react framework for their next project.

If this functionality can really be built easily with existing functionality and then it might be interesting to have a section in the docs with recipes (or cookbook) that show for the example how to built a Drawer component. This way you don't loose the people that require this functionality and you can promote and show off the composibility of the framework.

**Comment by adidahiya** [comment]
I totally agree @ConneXNL, a cookbook and/or demos page (#125) would go a long way. It isn't the highest priority for us right now, but we'd be open to documentation proposals / PRs.

**Comment by llorca** [comment]
Besides #125, a quick fix here can be to create another `<Overlay>` example as a side panel

**Comment by giladgray** [comment]
closing as this discussion seems resolved.

**Comment by tnrich** [comment]
If anyone feels like pasting a simple example or a link to a codesandbox here that would be greatly appreciated. Thanks!

**Comment by giladgray** [comment]
@tnrich check out `Drawer` in the docs
