### ISSUE TITLE
v2 Table editing: text shows up twice, overflows, and text field width is wrong

### ISSUE THREAD

**Issue by thom-nic** [palantir/blueprint#2436]
### Bug report

- __Package version(s)__: Table v2.1.0
- __Browser and OS versions__: MacOS High Sierra, FireFox 59, Chrome 66.  Also tested on Win10 with IE Edge.

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/v2/#table/features.editing
1. start editing text

#### Actual behavior
Text is duplicated both inside and outside the input field while editing.  Input field is too small: It should be 100% of the cell width, no?  Also the duplicated text spills over into the adjacent cell.  Screenshot:
![screen shot 2018-04-30 at 8 34 20 am](https://user-images.githubusercontent.com/95562/39427435-b2cfb2c0-4c51-11e8-9131-6604306b7fbc.png)

#### Expected behavior

Here's a screenshot from react-data-grid which more accurately mimics excel behavior:
![screen shot 2018-04-30 at 8 38 51 am](https://user-images.githubusercontent.com/95562/39427583-538a2ca4-4c52-11e8-8ea8-56038e17d432.png)

I really want to use Blueprint for its rich set of widgets (and I specifically need an Excel-like table component!) however the table editing UX is sub-optimal.  Also Blueprint's v1 table, by comparison, behaves as expected:
![screen shot 2018-04-30 at 8 52 08 am](https://user-images.githubusercontent.com/95562/39427994-d87a0960-4c53-11e8-9b46-a8daa6779c6b.png)

**Comment by thom-nic** [comment]
Given that table v1 seems to work reliably, could I use table v1 with core v2?  I would prefer to not start a new project on core v1.

**Comment by giladgray** [comment]
@thom-nic this issue has been fixed. Upgrade to latest core 2.2.1

**Comment by thom-nic** [comment]
Thanks very much. I did my best to search existing issues for any mention of behavior I was seeing.  Apologies for the dupe!
