### ISSUE TITLE
Is there a changelog for every package?

### ISSUE THREAD

**Issue by ghost** [palantir/blueprint#2447]
Is there a changelog for every package?

Also a simply changelog.md? What are the news let's say in `core@2.3.1`?

**Comment by llorca** [comment]
it's usually in the releases page: https://github.com/palantir/blueprint/releases

@giladgray looks like it's missing for recent minor releases?

**Comment by adidahiya** [comment]
we keep the changelog in the wiki now https://github.com/palantir/blueprint/wiki/3.0-Changelog
