### ISSUE TITLE
v2 docs for editable text are broken

### ISSUE THREAD

**Issue by romnempire** [palantir/blueprint#2450]
The component rendering the text of the editable text is not hidden when the editing component is made visible

### Bug report

- __Package version(s)__: whatever you build your docs with
- __Browser and OS versions__: chrome  65.0.3325.181

#### Steps to reproduce

- Go to http://blueprintjs.com/docs/v2/#core/components/editable-text and attempt to edit the title.  - The text "edit title" is rendered beside the editing component
- When editing the text, the text rendered besides continues to update.

#### Actual behavior

You see both the text editor and the text view components at the same time while editing.

#### Expected behavior

You should only see the text once when editing it

**Comment by romnempire** [comment]
also reproed in firefox 59.0.1 (64-bit).  behaviour is a bit different: in firefox, the editing pane resizes to your input while typing, in chrome it remains a fixed size.  The double vision behaviour remain the same.

**Comment by giladgray** [comment]
👍 docs deployed
