### ISSUE TITLE
Deconflict Label and FormGroup

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#2460]
They both do similar things, with a very inconsistent API.

Proposal 1: since `FormGroup` can do everything a `Label` does and more, we can potentially get rid of `Label`

Other proposal 2: `Label` and `FormGroup` both implement a common `secondaryLabel` prop (just like `Tree`s) to display a muted text near the main bold label

**Comment by giladgray** [comment]
given that `FormGroup` is better than `Label` in like every way, we could just kill `Label` entirely and only offer `FormGroup`

**Comment by llorca** [comment]
`Label` becomes a simple HTML wrapper, composed in `FormGroup`
