### ISSUE TITLE
How much RTL support is there in this library?

### ISSUE THREAD

**Issue by israelidanny** [palantir/blueprint#2468]
I just checked it out a bit, and from what I see, other than `pt-rtl`, I didn't find any RTL support. For instance, navbar buttons still have their margin to the left and not right if `direction: rtl` is applied to the `body` tag.

So, is there official RTL support for the components themselves, or just to text right now?

**Comment by israelidanny** [comment]
@giladgray I can compile a list like that.
Actually, margins are actually very important. Specifically, margin-left/right, and padding-left/right (e.g, navigation menu, where there is normally a margin-left). Also any type of float.

**Comment by giladgray** [comment]
@israelidanny looking forward to that list! then we can discuss specific margins 😄

**Comment by giladgray** [comment]
@israelidanny feel free to re-open this issue (or file a new one) if you produce such a list 👍

**Comment by israelidanny** [comment]
This list was nicely provided by another poster here:
https://github.com/palantir/blueprint/issues/3754

I'll be contributing there.
