### ISSUE TITLE
Setting style prop on <Cell/> seems to do nothing

### ISSUE THREAD

**Issue by unscene** [palantir/blueprint#247]
### Bug Report

- __Package version(s)__: @blueprintjs/core@1.0.1,

#### Describe the issue:

When setting the style prop on `<Cell/>` none of the actual styles are applied.  The only styles that are applied are measured column width/height and position.

In my case I am doing:  

```ts
renderCell () {
   const style = { textAlign: 'right' };

    return (
      <Cell style={style} tooltip="test">Test</Cell>
    )
}
```
#### Actual behavior:

Nothing happens.

#### Expected behavior:

It should merge the styles.

**Edit**: I am just now realizing that I can do 
```
<Cell><div style={style}>{value}</div></Cell>
``` 
Though the docs are not very clear why that property exists and what its intention is.

**Comment by adidahiya** [comment]
looking at [this code in `cell.tsx`](https://github.com/palantir/blueprint/blob/9ae28710616f813c4d168e40c0e299d32ceb75a2/packages/table/src/cell/cell.tsx#L35), that is surprising. can you provide any more details? do you see your inline style showing up in the DOM or in dev tools?

**Comment by unscene** [comment]
The example is in a much large project and don't want to just paste it wholesale.  I can provide a stripped down example later.  What I did notice is that I am using this in conjunction with explicit column Width on `<Table>`.  The properties that are on style are being overwritten by that I believe, but I haven't dug into the code there too much yet.

**Comment by themadcreator** [comment]
You're right, we don't handle the styles properly. This is because we use styles to absolutely position the cell elements in the viewport. See [this line](https://github.com/palantir/blueprint/blob/9ae28710616f813c4d168e40c0e299d32ceb75a2/packages/table/src/tableBody.tsx#L164) for example. But, we can just use Object.assign to merge the props, which I will do in a PR.

**Comment by unscene** [comment]
Awesome! Thanks.
