### ISSUE TITLE
allow string literals in enum props

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2476]
annoying to have to import `Position` or `Intent` every time so let's just do the thing and allow string literals in these props.

will require converting to `const/type` syntax instead of using language `enum`.

**Comment by llorca** [comment]
would be great to preserve real `enum`s. can't we add something like `typeof Position` to the type? there's a syntax that is able to generate a union of strings from an enum, but I forget which one it is. I think it's something along those lines:
```
enum E {
  A = "a",
  B = "b",
  C = "c",
}

// typeof E === "a" | "b" | "c" ??
```

**Comment by giladgray** [comment]
we unfortunately cannot do that as string enums are designed to be opaque, so you "literally" cannot reference the string literal behind `Intent.PRIMARY`. i think that's a big bummer of a feature, but what can you do 🤷‍♂️ ?

what you can do is the `const/type` hybrid, where the `type` is a union of literals and the `const` is an object providing constants for each of the literals.

**Comment by giladgray** [comment]
also that `typeof` approach simply does not work for `enum X`, but it works fine for `const X = { A, B, C }`
