### ISSUE TITLE
Button component w/ icon is misaligned 

### ISSUE THREAD

**Issue by jhlywa** [palantir/blueprint#2487]
### Bug report

- __Package version(s)__: core 2.3.1, icons 2.2.1
- __Browser and OS versions__: Firefox 60.0, Chrome 66.0.3359.170 / Linux, Mac OS 

#### Steps to reproduce

```js
<div>
  <div>
    Button Component:{' '} 
    <Button>A Button</Button>{' '}
    <Button icon="trash">Misaligned Button</Button>
  </div>
  
  <div>
    CSS Component:{' '}
    <button type="button" class="pt-button">A Button</button>{' '}
    <button type="button" class="pt-button pt-icon-trash">Correctly Aligned</button>
  </div>
</div>

```

#### Actual behavior
![alignment issue](https://i.imgur.com/enVCuHI.png)

#### Comments

I ran into this issue while upgrading from 1.x to 2.3.1.  Thanks for the great library!

**Comment by r03** [comment]
I also have the problem with an input and a button.
Bot are solved with this:

```
.pt-button {
    vertical-align: middle;
}
```
Not sure if that is the right solution?

**Comment by giladgray** [comment]
i cannot reproduce this locally with 2.x or 3.x. would need some more information about the layout properties of the parent. but this is easily solved with vertical-align or flex layouts.

**Comment by giladgray** [comment]
aaand i figured out the source: button _without_ SVG icon inline with button _with_ SVG icon.

**Comment by llorca** [comment]
@giladgray is that even worth addressing since 1) the icon font (and button without SVG) is deprecated and 2) why would you ever use buttons with different icon implementation next to each other?

**Comment by giladgray** [comment]
it's not about different impls, it's about presence or absence! the icon itself causes the misalignment cuz it has `vertical-align: top`
