### ISSUE TITLE
DatePicker docs link is dead

### ISSUE THREAD

**Issue by LittlePony** [palantir/blueprint#2496]
http://blueprintjs.com/docs/v2/#datetime/datepicker.using-modifiers

link "react-day-picker documentation." to "http://react-day-picker.js.org/Modifiers.html" return 404.

**Comment by llorca** [comment]
new docs: http://react-day-picker.js.org/docs/getting-started
what's the best page for modifiers? not that clear from glancing over

**Comment by LittlePony** [comment]
probably this
http://react-day-picker.js.org/docs/matching-days

**Comment by giladgray** [comment]
fixed in afe038c8
