### ISSUE TITLE
Layout Components

### ISSUE THREAD

**Issue by scibernix** [palantir/blueprint#250]
Hello,

Are there any layout components in the pipeline. Which Grid layout components are recommended ?

Thanks

**Comment by llorca** [comment]
@scibernix What are you looking for specifically? We don't have any layout component as we recommend using flexbox for these things

**Comment by dmackerman** [comment]
We're using https://github.com/jxnblk/reflexbox to handle the majority of our layout stuff. It's pretty powerful, and handles 99% of the layout cases we need.

**Comment by orecus** [comment]
:+1: for reflexbox, found it to be easy to use and have worked great for me too.

**Comment by llorca** [comment]
Flexbox and reflexbox are pretty great solutions. Closing as we currently have no plan to write a layout engine
