### ISSUE TITLE
Initial load of select always picks the first item

### ISSUE THREAD

**Issue by simontong** [palantir/blueprint#2500]
Hi,

How do I tell blueprint select which item to select when it first loads, it seems to pick the first item every time it re-renders?

**Comment by llorca** [comment]
That's kind of a slim issue description, @simontong -- screenshots/screencasts and more details would be welcome.

If you're talking about how the first item is selected in [this particular select instance](http://blueprintjs.com/docs/v2/#select/select-component), that's just how our example is set up. The [code is self-explanatory](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/select-examples/selectExample.tsx): we have a list of items, and we chose to feed the first item of the list to the button wrapped by `<FilmSelect>`.

Gonna close this out, but feel free to reopen with more details if needed.
