### ISSUE TITLE
undocumented changed defaults in props

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2505]
### Bug report

Some components supply values to composed components that are different from default props _without documentation_ resulting in unexpected usage.

#### Actual behavior

`DateRangeInput` sets `<Popover usePortal={false}>` when the default is `true`

#### Expected behavior

prop docs are reliable.

#### Possible solution

audit composed component usages and make sure defaults are sane and documented. this especially applies to overlay components and `usePortal`.

**Comment by llorca** [comment]
`DateRangeInput` should not change `usePortal`
