### ISSUE TITLE
Please export table/draggable on blueprint/table

### ISSUE THREAD

**Issue by toddself** [palantir/blueprint#251]
We are implementing some custom table cell editors for editing different types of data within a table (e.x. checkboxes, select widgets, etc), but we want them to react (no pun intended) the same as the EditableCell type exported by blueprintjs/table.

Right now we're reaching into the package to import Draggable so that we can achieve this, however, this is a pretty brittle abstraction (if you move it for example!), and only works if we're using TypeScript (which we happen to be here but that's not super relevant).

Ideally, the Draggable interface/behavior/component/whatever would be exported by the project for other things that might extend blueprintjs to use.

**Comment by toddself** [comment]
Although you can just grab the compiled version from `/dist/interactions/draggable.js` but it would be nice to have this exported so you could just do `const Draggable = require('blueprintjs/table).Draggable` :)

**Comment by themadcreator** [comment]
Sure, this should be no problem

**Comment by toddself** [comment]
Thank you!
