### ISSUE TITLE
Example in docs-theme not found

### ISSUE THREAD

**Issue by werayn** [palantir/blueprint#2517]
Hello blueprint :)

I was trying to test your framework with the little example you give : https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/menuExample.tsx

Everything works but one thing no.

The line import { Example, IExampleProps } from "@blueprintjs/docs-theme";
doesn't work because : "@blueprintjs/docs-theme' does not contain an export named 'Example'."

Nothing to do i don't find this module.

to reproduce create a simple app like that :
npx create-react-app my-app --scripts-version=react-scripts-ts
yarn add blueprintjs/core
yarn add blueprintjs/docs-theme

blueprint with @

and all over command that we need. I check they are in my node_modules.
Did i make something wrong or is normal ?

Thanks Blueprintjs

**Comment by giladgray** [comment]
@werayn you've got us between two releases! the `Example` component was written on Friday in #2501  and will be shipped in 3.0.0-beta.1 later this week. 

please refer to the `release/2.x` branch in the meantime: https://github.com/palantir/blueprint/blob/release/2.x/packages/docs-app/src/examples/core-examples/menuExample.tsx

**Comment by giladgray** [comment]
but there's no need for you to render the `Example` component outside of the docs site. you could simply remove that wrapper and render its children and you'd be fine.

**Comment by llorca** [comment]
closing as stale / resolved
