### ISSUE TITLE
Tabs Expansion

### ISSUE THREAD

**Issue by qcharlieshi** [palantir/blueprint#2518]
#### Context
When there are too many tabs it will overflow out of its container. It would be ideal if tabs could be expanded in one of several ways, condensing the tab titles, adding arrows to scroll or adding a dropdown selector for any overflowing tabs.

#### Examples
I can provide some screenshots if needed.

**Comment by giladgray** [comment]
@invliD sounds familiar????

**Comment by invliD** [comment]
Yes!! I'll contact you internally.

**Comment by invliD** [comment]
I will add my internal implementation to Blueprint next week.

**Comment by kudigaracoder** [comment]
Could you guys also please extend the current tab implementation to support something like this?
![tabs](https://user-images.githubusercontent.com/3305383/40216866-4478ea6e-5a87-11e8-9d66-73f2d87433bf.png)

**Comment by qcharlieshi** [comment]
I believe you could use a jsx component for the title prop to achieve that then use some of the more advanced css selectors to apply one class that reskins the entire tab section without touching the underlying components or css.

**Comment by llorca** [comment]
correct, as @qcharlieshi said, just style the tabs to whatever you'd like. there's nothing that needs to be added to Blueprint in order to achieve what's in your screenshot

**Comment by giladgray** [comment]
#2537 adds a new `OverflowList` component that lets you implement a dropdown selector to collapse extra items.

**Comment by whaty** [comment]
> #2537 adds a new `OverflowList` component that lets you implement a dropdown selector to collapse extra items.

how to do it? Any demos?
