### ISSUE TITLE
labelRenderer in single slider is not being called! 

### ISSUE THREAD

**Issue by amaatouq** [palantir/blueprint#2526]
I am trying to have custom labels for the blueprint slider using `labelRenderer`. In particular, users are shown some text, and they are asked to decide between two sentiments (i.e., the true answer is 0 or 1). However, to capture their confidence, they will have a slider that I want them to choose a value from.

Something like this
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/0yBW9.png

So the labels of the slider labels should go from "100%" on one side to "100%"

However, the blueprint slider's `labelRenderer` is not even calling the `renderLabel` function and the default labels are still shown. Note that I only want to change the labels of the slider, I still need the actual values to be between [0,1] for the backend things to work easier. Here is my code (React.js):
```javascript
 import { Slider } from "@blueprintjs/core";
import React from "react";

export default class TaskResponse extends React.Component {
  //this is to get the label between 100% & 100%
  renderLabel= val => {
    console.log("render label", val);
    if (val === 0.5) {
      return "Not sure";
    } else if (val === 1) {
      return "100% positive";
    } else if (val === 0) {
      return "100% negative";
    } else {
      return `${Math.abs(Math.round(val * 100)) - 50}%`;
    }
  };

  renderSlider(player) {
    const guess = player.round.get("guess");
    return (
      //no default value until the user inputs something (avoiding anchoring bias)
      <div className={`pt-form-content ${guess === undefined ? "empty" : ""}`}>
        <Slider
          min={0}
          max={1}
          stepSize={0.01}
          labelStepSize={0.25}
          value={guess}
          showTrackFill={false}
          disabled={false}
          labelRenderer={this.renderLabel}
        />
      </div>
    );
  }
  
  render() {
    const { player } = this.props;
    
    return (
      <div className="task-response">
        <form onSubmit={this.handleSubmit}>
          <div className="pt-form-group">
            {this.renderSlider(player)}
          </div>

        </form>
      </div>
    );
  }
}
```

**Comment by giladgray** [comment]
@amaatouq your code looks correct. not sure why this is happening, and it does not repro on the docs (beautiful formatted labels every time). are there any additional console logs?

**Comment by giladgray** [comment]
also what version of `core` are you using? i notice you did not fill out our issue template, or i wouldn't have to ask 😄

**Comment by amaatouq** [comment]
I was using `@blueprintjs/core@1.37.0` .. that's the reason. It worked once I changed it to `renderLabel`

Sorry btw, but as this is a "Request for help" it didn't show me the template that asked for the version! I guess that one only appears when you open a bug issue.

**Comment by joshua-a-becker** [comment]
had this same problem.  thanks!!

**Comment by amaatouq** [comment]
@joshua-a-becker I would recommend updating to bpjs-3 or the empirica:slider package
