### ISSUE TITLE
Need help to decide what UI framework I'm use to make a Desktop Web-Based IDE

### ISSUE THREAD

**Issue by jonatasfreitasv** [palantir/blueprint#2532]
Hi guys,

I'm started a open-source project, is a Desktop IDE Electron Based for ClickHouse Database.

But, I spend a lot of time trying to make a nice interface.

My question is, Blueprint is a good choice for make this project ? Or not ?

My project is (https://github.com/HouseOps/HouseOps).

Thx a lot guys!

**Comment by giladgray** [comment]
@jonatasfreitasv thanks for asking! Blueprint seems quite ideal for your project as it's a meticulously designed desktop-first React framework with a large set of components out of the box. I'd say give us a shot! 

We also love contributions from the community to improve the framework for everyone ❤️

**Comment by jonatasfreitasv** [comment]
Thx a lot @giladgray, I make some tests, thx again.
