### ISSUE TITLE
Are we stick to use es5 with this library?

### ISSUE THREAD

**Issue by harumando** [palantir/blueprint#2535]
#### Question

There is a little problem i ran to. For development i use typescript witch outputs as es2017. In general everything works, but i noticed that your library is compiled to es5 code where all classes are transpiled into functions. Which leads to an error with context menu decorator because the decorator tries to call a given class as a function, of course it can't so i get an error `Class constructor cannot be invoked without 'new'`. When i change tslint.json so it converts typescript to es5 everything seems to work.

**Comment by giladgray** [comment]
@harumando hmm i suppose we haven't tested the decorators against actual ES6 `class`es so this may be a real issue. can you verify this?

**Comment by giladgray** [comment]
targeting es5 is a good practice for browser apps as es6+ is inconsistently supported.

**Comment by sushain97** [comment]
> can you verify this?

FWIW, I've run into this issue using `@HotkeysTarget`.

> targeting es5 is a good practice for browser apps as es6+ is inconsistently supported.

In general, this makes sense to me. However, I would consider apps primarily intended for personal/internal use where modern browsers are implied as an exception. Here's my `tsconfig.json`:

```
{
    "compilerOptions": {
        "target": "es2017",
        "module": "esnext",
        "moduleResolution": "node",
        "sourceMap": true,
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "experimentalDecorators": true,
    },
}
```

**Comment by RvanderLaan** [comment]
The workaround I am currently using in an Electron app is to target `es5` and adding `["dom", "es2017"]` to `libs` so that you'll still be able to use its features
