### ISSUE TITLE
Documentation problem; DateRangeInput does not show required props

### ISSUE THREAD

**Issue by schicks** [palantir/blueprint#2542]
the line example for [DateRangeInput](http://blueprintjs.com/docs/v2/#datetime/daterangeinput) does not have the two required props, `formatDate` and `parseDate`. Trying to use that code will result in errors.
I'd be very happy to just fix this myself, but I'm not actually sure where in the repo the documentation lives to submit a pr.

**Comment by giladgray** [comment]
@schicks oof yes thanks for pointing this out!
