### ISSUE TITLE
Blueprint table won't scroll horizontally w/o data

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#2553]
#### Environment

- __Package version(s)__: 3.0.0-beta.0
- __Browser and OS versions__: Chrome 66 / macOS

Blueprint table decides to disable horizontal scrolling if the first cell in the rightmost column is a ghost cell:https://github.com/palantir/blueprint/blob/6b35059fd616c6a0d56919a6d6fb8813017fda03/packages/table/src/table.tsx#L1196

`Grid::isGhostIndex` sees that there are zero rows, and our `rowIndex`, `0`, is greater-than or equal to that, so it returns `true`: https://github.com/palantir/blueprint/blob/6b35059fd616c6a0d56919a6d6fb8813017fda03/packages/table/src/common/grid.ts#L280

#### Actual behavior

Unfortunately, this means it's impossible for users to be able to horizontally scroll to see all the column headers in the table.

#### Expected behavior

Table still scrolls horizontally w/o data.

#### Possible solution

Instead of using `isGhostIndex`, possibly just check column index against the known number of columns and skip the row-based condition.

**Comment by giladgray** [comment]
@JKillian you down to fix this?

**Comment by JKillian** [comment]
sure! Don't know bp-table code very well, but assuming my proposed solution is legit, shouldn't be too tricky
