### ISSUE TITLE
BP2→BP3:  <hr> styling is lost

### ISSUE THREAD

**Issue by qcz** [palantir/blueprint#2555]
#### Environment

- __Package version(s)__: 3.0.0-beta.1
- __Browser and OS versions__: all

#### Problem

While removing global styles and introducing Blueprint HTML components, the Blueprint-style HR was lost. Was it intended or was it just missed? I can make a PR if there is interest in reviving it and the team members has no time to do it.

**Comment by llorca** [comment]
mhmm, looks like pre 3.0, we had these default `<hr>` styles:
```
margin: ($pt-grid-size * 2) 0;
border: none;
border-bottom: 1px solid rgba($black, .15);
```
thoughts @giladgray?

**Comment by giladgray** [comment]
yep the removal was intentional. the plan is to build that little divider component to replace `<hr>` and those minimal button groups.
