### ISSUE TITLE
Tooltip element crash in disabled Button

### ISSUE THREAD

**Issue by jonatasfreitasv** [palantir/blueprint#2558]
#### Environment

- __Package version(s)__: 2.3.1
- __Browser and OS versions__: Electron+Linux
#### Steps to reproduce

With this structure for example:
```
<Tooltip content="Server monitoring (soon)" position={Position.BOTTOM}>
   <Button className={Classes.MINIMAL} disabled icon="doughnut-chart" text="" />
 </Tooltip>
```
On mouse over, tooltip showing, but when mouse out, tooltip not hidden and stuck.

**Comment by giladgray** [comment]
there are multiple great big callout on the docs about this. use `AnchorButton`.

![image](https://user-images.githubusercontent.com/464822/40796447-f4a6e06c-64b9-11e8-95b5-a2e2cda25112.png)

**Comment by jonatasfreitasv** [comment]
Wow! Thx a lot @giladgray. Sorry...
