### ISSUE TITLE
Make the TimePickerPrecision.MINUTE not be number 0

### ISSUE THREAD

**Issue by duolaf** [palantir/blueprint#2559]
The current value makes it easy to make some wrong. Because `TimePickerPrecision.MINUTE == false`. I hope you understand what I am talking about. Just a small suggestion.

**Comment by giladgray** [comment]
@duolaf in 3.0 we have changed all these enums to strings. https://github.com/palantir/blueprint/pull/2484/files#diff-af290363dca7a6e9dd3e197b9eb4568aR26

**Comment by duolaf** [comment]
Thank you for your answer.
