### ISSUE TITLE
FR: <EditableText> Buffer Changes

### ISSUE THREAD

**Issue by sbnon** [palantir/blueprint#2566]
#### Feature request

The `onChange` prop for `EditableText` components is fired for each change while in editing mode.

It would be useful to have a mode for EditableText where the \<input> while editing was not connected to the `onChange` or `value` props and instead the `onChange` event would only be fired when the component is blurred and the \<input> wouldn't be locked to the `value` prop during editing. 

#### Examples

An example use case of this is input validation. Let's imagine we want to only let the use enter non-blank values in the component.

Currently, you might use something like this:

```
<EditableText
  value={this.state.text}
  onChange={(v) => {
    if (v.trim()) {
      this.setState({text: v})
    }
  }}
 />
```

The issue with the approach though is that you can't make the text blank during editing. So the user wouldn't be able to do something like \<Select All> - \<Delete> - \<Enter new Value>.

If the `onChange` only fired after editing was complete, the above sequence would work.

I would suggest a new boolean prop, maybe `buffer`, that would enable this behavior.

**Comment by giladgray** [comment]
@sbnon i do believe you're looking for `onConfirm` and `onCancel`, which have always been there. they're even mentioned in the docs.
![image](https://user-images.githubusercontent.com/464822/40896033-8fdc646c-6767-11e8-8921-254b19184c20.png)
