### ISSUE TITLE
Typescript doesn't recognise showActionsBar as a valid property for DateInput

### ISSUE THREAD

**Issue by LorinWeb** [palantir/blueprint#2567]
#### Environment

- __Package version(s)__: blueprintjs/datetime@2.0.3
- __Browser and OS versions__: Any

#### Steps to reproduce

```jsx
import { DateInput } from '@blueprintjs/datetime';

<DateInput  showActionsBar />
```

#### Actual behavior

Typescript highlights `<DateInput showActionsBar />`, but the component behaves as expected.

#### Expected behavior

Typescript allows `<DateInput showActionsBar />`.

#### Possible solution

If possible, add showActionsBar to `IDatePickerBaseProps`

**Comment by giladgray** [comment]
ah yes seems like an oversight
