### ISSUE TITLE
[FR] - Decouple icon font usage

### ISSUE THREAD

**Issue by orecus** [palantir/blueprint#259]
Hi,

While playing around with Blueprint and the scss [files](https://github.com/palantir/blueprint/blob/9ae28710616f813c4d168e40c0e299d32ceb75a2/packages/core/src/blueprint.scss) I noticed a few things in regards to the `icons` and `font-imports`, as I don't want to use the supplied icons I excluded these in my main .scss file where I import blueprints files, as in my case I will be using Font-Awesome instead.

One downside to excluding this is that certain integrated icons in the UI wont work, for example in dropdown's and similar where you don't specifiy the displayed icon. It would be great if the following points could be considered.

- Decouple the usage "lockin" to the `pt-icon-XXXXX` where applicable so that any class for a icon can be provided instead of assuming it's an `pt-icon-XXXXX` icon. For example; Buttons
- For things like selects or checkboxes, where we never define the 'icon' directly (from what I can tell), perhaps a new prop could be added such as `icon/iconSelected` or similar in where I could provide `fa fa-chevron-down` or `fa fa-check` for example that would then be used instead, this would also enable greater options for which icons to use as "selected/checked" if we could specifiy which icon to use in which state or not if you would want to.

A workaround today that works is to add the custom icon class in a element as a child for example to a button, but it might not work everywhere I suspect. You can create a custom react component based on the css instead of using the supplied react component but without overriding the css classes themselves I don't think that it would work perfectly if you omit `icons` and `font-imports` in your .scss builds.

I hope all of this makes sense, granted it's only really a problem if you do custom imports instead of using [blueprint.scss](https://github.com/palantir/blueprint/blob/9ae28710616f813c4d168e40c0e299d32ceb75a2/packages/core/src/blueprint.scss) and omit `icons` and `font-imports` in your build. :)

**Comment by giladgray** [comment]
Sorry, I don't see us supporting this first-party because at Palantir we all use (and deeply love) our custom UI icon font.

However, you're on the right track with just adding your own icon elements as needed. 

You could also look into re-implementing [`Classes.iconClass()`](https://github.com/palantir/blueprint/blob/master/packages/core/src/common/classes.ts#L139-L144) to generate your own icon class names instead of ours. That said, there are a bunch of CSS rules that expect the `pt-icon` prefix so you'll still have to work around that.

**Comment by orecus** [comment]
@giladgray Thanks, that is totally understandable. I'll take a closer look once I start to refactor for icons in my application!
