### ISSUE TITLE
Radio Inner circle rendering weirdness

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2595]
Hey there,

Using the latest version of blueprint, I'm seeing some strange things with the Radio:

![image](https://user-images.githubusercontent.com/2730609/41378900-629032b2-6f15-11e8-8345-97fbb10e2a33.png)

Has anyone else seen the inner circle render with bits of it chopped off? 

Thanks!

**Comment by giladgray** [comment]
@tnrich are you zoomed in here? i've only seen awkwardness like this at high zoom levels.

**Comment by tnrich** [comment]
Nope that is normal 100% browser zoom. I'm not sure I can reproduce it. If I see it again I'll take more diagnostics.

**Comment by giladgray** [comment]
closing as stale
