### ISSUE TITLE
Note that basic select uses font icons

### ISSUE THREAD

**Issue by stramel** [palantir/blueprint#2597]
#### Environment

- __Package version(s)__: v2
- __Browser and OS versions__: all

#### Question

Can you add a note that basic selects still rely on font-icons even in v2?

**Comment by giladgray** [comment]
yeah... i should just build a React component for it.

**Comment by stramel** [comment]
I would like that, thanks!

I currently am working around it by just adding some styles to position and `Icon` and overwrite the `::after` styling.

**Comment by stramel** [comment]
Thanks you!
