### ISSUE TITLE
Weird behavior of MultiSelect

### ISSUE THREAD

**Issue by jaggernoth** [palantir/blueprint#2598]
#### Environment

- __Package version(s)__: Select 2.0.1
- __Browser and OS versions__: Chrome

#### Steps to reproduce
- Go to demo
- Open MultiSelect demo
- enable 'open popup on keydown'
- enter one letter

#### Actual behavior
Popup with suggestion shows and dissapears in split second

#### Expected behavior
Popup with suggestion shows up and stays

![error-multiselect](https://user-images.githubusercontent.com/1152824/41408179-1cab3bb2-6fd2-11e8-8821-0411f4c0c8b6.gif)

**Comment by giladgray** [comment]
i think the whole "open on keydown" feature is worthless: i propose that it should _always_ open on keydown and the option should instead be `openOnTargetFocus` (which is exactly covered by the popover prop of the same name).

**Comment by jaggernoth** [comment]
What I would use it for is like autocomplete but with multiple elements
We do have server side request for suggestions and having suggestions before user writes anything is not making any sense

**Comment by giladgray** [comment]
seems fixed by #2747
