### ISSUE TITLE
How to use the usePortal attribute on Alert component

### ISSUE THREAD

**Issue by brenopolanski** [palantir/blueprint#2599]
#### Environment

- __Package version(s)__: 2.3.1
- __Browser and OS versions__: 
    * **Browser**: Version 66.0.3359.181 (Official Build) (64-bit)
    * **OS**: Ubuntu 16.04

#### Question

How to use the portal on `<Alert />` component? I tried the `usePortal` attribute, but it not work.

```
<Alert
  canEscapeKeyCancel={true}
  canOutsideClickCancel={true}
  cancelButtonText="Cancel"
  confirmButtonText="Delete"
  icon="office"
  intent="danger"
  isOpen={isOpenAlertDelete}
  onCancel={this.handleCancelAlertDelete.bind(this)}
  onConfirm={this.handleConfirmAlertDelete.bind(this)}
>
  <p>Are you sure that you want to delete this company?</p>
</Alert>
```

![screenshot from 2018-06-14 14-47-37](https://user-images.githubusercontent.com/1894191/41429160-a0524536-6fe2-11e8-8f23-d4ca70da6d8c.png)

**Comment by giladgray** [comment]
Alerts do not support portals as they are **intended to block the entire UI until the user takes action.** this is a design choice.

**Comment by brenopolanski** [comment]
Make sense @giladgray. Thanks :+1:
