### ISSUE TITLE
Tabs component improvements

### ISSUE THREAD

**Issue by orecus** [palantir/blueprint#261]
I have a few suggestions on the <Tabs> component, mainly in regards to the layout to make slightly more customizable. In my case, I would like to add an element to be right aligned in level of the tabs within that component. 

In my use case i have several tabs with forms and settings where you can configure the application, with a single button for saving all changes once you are happy. This button I would like to have within the tabs but aligned to the right of them instead of having it as now shown at the bottom of the page.

This new component part could be a general element, so that you could also add other components than a button, for example a progress indicator or spinner perhaps.

Perhaps something like this;
```js
<Tabs>
    <TabList>
        <Tab>First tab</Tab>
        <Tab>Second tab</Tab>
        <TabElement align={Position.RIGHT}><Button iconName="refresh" text="Save Settings" onClick={this.saveConfiguration}/></TabElement >
        <TabElement align={Position.RIGHT}><Spinner intent={1} value={this.props.progressSaving}/></TabElement >
    </TabList>
    <TabPanel>
        First panel
    </TabPanel>
    <TabPanel>
        Second panel
    </TabPanel>
</Tabs>
```

It could even be a new component, a `<Toolbar>` or similar where you can componse the left side to have tabs and the right side to have an input, button or other component. 

This would mean that you would decouple the need to have equal `<Tab>` and `<TabPanel>` as you would probably only want to have the `<TabList>` within it and display the content somewhere else.

**Comment by giladgray** [comment]
@orecus see https://github.com/palantir/blueprint/issues/363#issuecomment-270200926 for a proposal of a new Tabs API that should support everything you're asking for. thoughts?

**Comment by orecus** [comment]
@giladgray That example seems to solve most of the things I would like to do. Only question is related to position of those arbitrary content or other components that i would compose into it. Could I have as in your example a search box alinged to the right with the tabs as today alinged to the left in this new API? 

If that's fully supported, then it sounds perfect as you can put anything and position it to the far right in that row without any "tab" styling.

**Comment by giladgray** [comment]
yes you'd be able to position elements on the right with a simple class name or inline styles.

non-`Tab` children do not look like `.pt-tab`s, they look like whatever they are.

**Comment by orecus** [comment]
@giladgray That sounds perfect and exactly what I'm looking for in the new Tab api then! Looking forward to it! :)
