### ISSUE TITLE
BP3 heading styles should include setting for letter-spacing

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#2610]
#### Environment

- __Package version(s)__: core@3.0.0-beta.1

#### Steps to reproduce

1. BP1 styles are on the page
2. Use BP3's `H2` component (or another one)

#### Actual behavior

The `letter-spacing` rule from BP1 still applies

#### Expected behavior

The `letter-spacing` rule from BP1 shouldn't still applies

#### Possible solution

Add a `letter-spacing` rule to the BP3 heading styles

**Comment by adidahiya** [comment]
closing as stale, will re-open if it's important
