### ISSUE TITLE
Support referenceObject in Tooltip and Popover

### ISSUE THREAD

**Issue by fnberta** [palantir/blueprint#2618]
#### Environment

- __Package version(s)__: 2.3.1
- __Browser and OS versions__: macOS High Sierra, Chrome 67.0.3396.87

#### Feature request

Popper.js (and react-popper) support passing a ```referenceObject``` instead of a real DOM node. It would be awesome if the blueprint ```Tooltip``` and ```Popover``` components could also support this. Sometimes you just don't have a proper DOM node available but still want to show a tooltip. An example use case would be things drawn on a map with WebGL.

**Comment by giladgray** [comment]
yeah this'd be cool.
