### ISSUE TITLE
React being included in output even though specified as external

### ISSUE THREAD

**Issue by jasonbarry** [palantir/blueprint#262]
I'm loading React and ReactDOM from a CDN, so I'm not including it in my bundled output. When I added blueprintjs to my project, React became included in the bundled output, even though I specify in my webpack config to not include it. Here's the relevant part of my webpack.config.js file:

```
...
externals: {
    'react': 'React', 
    'react-dom': 'ReactDOM'
},
...
```

I suspect this has something to do with `react-addons-css-transition-group`. I've tried adding that to my `externals` key too, which successfully removes React from the bundle, but then I get the JS console error `ReactCSSTransitionGroup could not be found`. 

Any help would be much appreciated!

**Comment by giladgray** [comment]
are you providing `react-addons-css-transition-group` from your CDN as well? it _is_ a dependency and must be there at runtime.

**Comment by giladgray** [comment]
adding CSSTG to externals seems like the right move, but then you have to actually externalize it.

**Comment by jasonbarry** [comment]
@giladgray yep, that's where I'm currently stuck. 

Here's what I have now: 
```JS
externals: {
    'react': 'React', 
    'react-dom': 'ReactDOM', 
    'react-addons-css-transition-group': 'ReactCSSTransitionGroup'
},
```

And on the page itself: 
```HTML
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react-with-addons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react-dom.min.js"></script>
```

Results in JS error
```
ReferenceError: Can't find variable: ReactCSSTransitionGroup
```

I believe ReactCSSTransitionGroup is in the react-with-addons.min.js file... maybe something within my externals key is incorrect?

**Comment by giladgray** [comment]
i think the issue is still that `ReactCSSTransitionGroup` is undefined... `react-with-addons` provides `React.addons.CSSTransitionGroup`, so you see the problem. I think you'll need to add something like this line of code before importing Blueprint:

```
window.ReactCSSTransitionGroup = React.addons.CSSTransitionGroup
```

https://facebook.github.io/react/docs/animation.html#high-level-api-reactcsstransitiongroup

**Comment by giladgray** [comment]
oh no wait you can probably just change the entry in `externals` map:

```js
externals: {
    'react': 'React', 
    'react-dom': 'ReactDOM', 
    'react-addons-css-transition-group': 'React.addons.CSSTransitionGroup'
}
```

**Comment by jasonbarry** [comment]
@giladgray that's the magic I was looking for! `React.addons.CSSTransitionGroup` did the trick. Thank you kindly.

**Comment by llorca** [comment]
🎉
