### ISSUE TITLE
TreeEventHandler does not inherit generic type of Tree.ofType as expected

### ISSUE THREAD

**Issue by jjhong922** [palantir/blueprint#2627]
#### Environment

- __Package version(s)__: 3.0.0-rc.1
- __Browser and OS versions__: Chrome, MacOS
#### Steps to reproduce

1. Try using Tree.ofType<>(), then try using onNodeClick with a specialized Node

#### Actual behavior

Type Errors

#### Expected behavior

No Type Errors

#### Possible solution

Give TreeEventHandler a generic type that inherits from ITreeProps

**Comment by giladgray** [comment]
fixed in #2629
