### ISSUE TITLE
Omnibar shouldn't preserve selection of item when order changes

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#2630]
#### Environment

- __Package version(s)__: select@3.0.0-rc.
- __Browser and OS versions__: Chrome 67

#### Steps to reproduce

In the gif below, I have a fuzzy matcher that is rearranging the order of the matches via `itemListPredicate`. It seems that BP keeps the previous match selected, which leads to some unintuitive UX.

#### Actual behavior

![image](https://user-images.githubusercontent.com/1400151/42042702-c5775974-7ac2-11e8-8f87-008a7c088d7d.png)

#### Expected behavior

When a second character is typed, changing the order of matches, the selection should remain with the top most item

#### Possible solution

Maintain selection based on index / position and not specific item

**Comment by giladgray** [comment]
i belive this has been addressed by other fixes.
