### ISSUE TITLE
`resetOnSelect` Omnibar prop docs are unclear

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#2631]
#### Environment

- __Package version(s)__: select@3.0.0-rc0
- __Browser and OS versions__: N/A

#### Actual behavior

The `resetOnSelect` docs say:

https://github.com/palantir/blueprint/blob/c133b0b6f7f7c1ca0ec0931b6aa6a40098faaaec/packages/select/src/components/omnibar/omnibar.tsx#L44-L50

However, the actual code seems to be written such that things are reset when the omnibar closes and is reopened (instead of when an item is selected):

https://github.com/palantir/blueprint/blob/c133b0b6f7f7c1ca0ec0931b6aa6a40098faaaec/packages/select/src/components/omnibar/omnibar.tsx#L93-L101

#### Expected behavior

I think the behavior for this prop is likely reasonable, just the docs should be clarified. Not sure if there needs to be some split of "resetWhenOpened" vs "resetWhenItemSelected" props

**Comment by giladgray** [comment]
fixed in #2917
