### ISSUE TITLE
Scrolling is broken for dialog docs

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/blueprint#2641]
#### Environment

- __Package version(s)__: v2 docs
- __Browser and OS versions__: Chrome 67 on OSX Sierra

#### Steps to reproduce

1. Go to Core/Dialog page
1. See that you can scroll on the page
1. Click the button to open the dialog
1. Close the dialog
1. Notice scrolling no longer works

This is an issue with the v1 docs too

**Comment by jaamison** [comment]
FWIW I can't repro with Chrome 67 / OSX 10.13.5

**Comment by johnwiseheart** [comment]
This seems to be fixed on my computer too. Maybe there was a small chrome bug or something else doing it. Closing.

cc @giladgray
