### ISSUE TITLE
Warning when a react element is wrapped with Cell

### ISSUE THREAD

**Issue by dineshvgp** [palantir/blueprint#2647]
#### Steps to reproduce
Link to the source code: https://codesandbox.io/s/lry7vqm73q

#### Error
![image](https://user-images.githubusercontent.com/5243459/42407893-45c8b10c-81e1-11e8-9b63-04b983a79039.png)

#### Possible solution
We might need to add a check here whether the child is string or element.
![image](https://user-images.githubusercontent.com/5243459/42407927-296b266a-81e2-11e8-9f25-c2ef45f9c398.png)

**Comment by gasolin** [comment]
dup of https://github.com/palantir/blueprint/issues/2446 ?

**Comment by giladgray** [comment]
yes
