### ISSUE TITLE
Error building: Cannot find module '@blueprintjs/icons'

### ISSUE THREAD

**Issue by RoryDungan** [palantir/blueprint#2650]
#### Environment

- __Package version(s)__: 
   - @blueprintjs/core 2.3.1
   - @blueprintjs/icons 2.2.1
   - Typescript 2.8.3
   - React 16.4.0
   - react-scripts-ts 2.16.0
- __Browser and OS versions__: Electron 2.0.0 (Chrome 61), Windows 10

#### Question

I've installed both `@blueprintjs/core` and `@blueprintjs/icons` but when I compile in watch mode I sometimes get the following error: 
```
Failed to compile.

E:/dev/app/node_modules/@blueprintjs/core/lib/esm/common/props.d.ts
(3,26): Cannot find module '@blueprintjs/icons'.
```

It only seems to happen in watch mode when I save a HTML or CSS file, not when I save a TS or TSX file. I also checked and @blueprintjs/icons is definitely present in my node_modules directory, so I'm not sure why it can't be found. 

I set the project up using Microsoft's [React Typescript Starter](https://github.com/Microsoft/TypeScript-React-Starter) and following the [instructions from the docs](http://blueprintjs.com/docs/v2/#blueprint/getting-started) with Node-style CSS module resolution.

**Comment by giladgray** [comment]
@RoryDungan this sounds like an artifact of your developer setup. can you share the repo so I can investigate live code?

**Comment by giladgray** [comment]
closing as unresponsive

**Comment by synapse** [comment]
I found out that whenever I edit a .ts or .css/.scss file it would trigger the failed compilation error

**Comment by TomFaulkner** [comment]
I am running into this as well. I am converting a project to Typescript and when I rename a js file to ts/tsx I am getting this error.

```
  "dependencies": {
    "@blueprintjs/core": "^3.2.0",
    "@blueprintjs/icons": "^3.0.0",
    "@types/react-redux": "^6.0.6",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-scripts-ts": "2.17.0",
    "redux": "^4.0.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^23.3.1",
    "@types/node": "^10.9.2",
    "@types/react": "^16.4.12",
    "@types/react-dom": "^16.0.7",
    "tslint": "^5.11.0",
    "tslint-config-airbnb": "^5.10.0",
    "tslint-eslint-rules": "^5.4.0",
    "typescript": "^3.0.1"
  }
}

```

**Comment by yash2code** [comment]
same issue

**Comment by kresli** [comment]
same issue. Experienced first time using lerna but never before
