### ISSUE TITLE
Scrolling the contents of a <Select> popover placed over a <Table> will scroll the table as well

### ISSUE THREAD

**Issue by ntamas** [palantir/blueprint#2651]
#### Environment

- __Package version(s)__: `@blueprintjs/core` 2.3.1, `@blueprintjs/select` 2.0.1, `@blueprintjs/table` 2.1.1
- __Browser and OS versions__: Firefox 60, macOS 10.13.5

#### Steps to reproduce

1. Create a Blueprint.js `<Table>` with lots of content so the table becomes scrollable.
1. Place a Blueprint.js `<Select>` component on top of it with a list of items; the list should be long enough to make the contents scrollable.
1. Open the `<Select>` component; make sure that the popover lies above the table.
1. Scroll the `<Select>` component with two-finger scrolling or with the mouse wheel.

#### Actual behavior

Both the contents of the popover and the table underneath it scroll at the same time. (Scrolling of the table is buggy on Firefox, but that's covered in #1712.

#### Expected behavior

Only the popover contents should scroll.

#### Possible solution

A workaround is to use the `popoverRef` prop of the `Select` to get a reference to the root div of the popover and then add an `onwheel` event handler (via direct DOM manipulation) that calls `event.stopPropagation()`. This could be the default for all `Select` instances.

**Comment by adidahiya** [comment]
closing in favor of newer related issue: https://github.com/palantir/blueprint/issues/5469
