### ISSUE TITLE
Certain issue with components in the new v3 documentation

### ISSUE THREAD

**Issue by NearAutomata** [palantir/blueprint#2664]
1. In the [documentation for the Menu component](http://blueprintjs.com/docs/#core/components/menu) submenus do behave wrong. The arrows are not aligned right and the submenus have weird left and right borders. Here is a comparison between v3 and v2:
![image](https://user-images.githubusercontent.com/32624319/42503211-6d4f803a-8438-11e8-914e-df2b7e7c3958.png)
![image](https://user-images.githubusercontent.com/32624319/42503222-7870d8ce-8438-11e8-92cb-238833ffe213.png)
2. In the [documentation for the Navbar component](http://blueprintjs.com/docs/#core/components/navbar) the buttons are raised and not minimal:
![image](https://user-images.githubusercontent.com/32624319/42503352-bbf369a4-8438-11e8-9595-c84cf32ac180.png)
3. Alerts, Dialogs and the Upload File Toast samples do not adhere to the dark theme when enabled in your documentation.

**Comment by giladgray** [comment]
oof 1 & 2 are definitely regressions, will fix today. thanks!

i cannot repro 3. Alert & Dialog respond just fine to the dark theme. File Toast responds on next update, as expected (because there's no event listener when dark theme is toggled)

**Comment by NearAutomata** [comment]
Issue 3 "resolved itself" - most likely some issue with the stored theme in the local storage.
