### ISSUE TITLE
Update Sketch design resources in Documentation

### ISSUE THREAD

**Issue by romanr** [palantir/blueprint#2668]
The sketch file in docs is outdated by two years

* The 2017 visual style now deviate from the current look of Blueprint
* Sketch now supports Libraries and it will be great idea to provide it as a Library
* New components and icons are missing from the Sketch file

Thank you.

**Comment by giladgray** [comment]
@pkwi will be picking this up in the next few weeks.

**Comment by mulholio** [comment]
Is this something that is in progress at the moment? I was getting a little bit frustrated at using Blueprint in Sketch so was thinking of tackling some of this myself.

Would be happy to contribute a conversion to symbols/library but don't want to duplicate any work by others.
