### ISSUE TITLE
Icon SVG-download links are broken in docs

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#268]
### Bug Report

- __Package version(s)__: v1.1.0
- __Browser and OS versions__: Chrome 54.0.2840.98, Mac OS X 10.11.6

#### Describe the issue:

These links don't work on http://blueprintjs.com/docs/#icons:

![image](https://cloud.githubusercontent.com/assets/443450/20732187/530ecbd8-b642-11e6-8ef0-0e8a243142d2.png)

They take you to a link with the following format, which shows a 404 page on github.com:
`https://github.com/palantir/blueprint/blob/develop/resources/icons/{16,20}px/pt-icon-*.svg`

#### Expected behavior:

Clicking the "Download 16px SVG" should download the 16px SVG for that icon. Same for 20px.

**Comment by giladgray** [comment]
yep should be `.../blob/master/resources/...`

**Comment by giladgray** [comment]
in the future, no need to make an issue if you're going to open the PR immediately afterwards.
