### ISSUE TITLE
Checkbox uses small tick when large={true}

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2685]
#### Environment

- __Package version(s)__: v3.0.1
- __Browser and OS versions__: Firefox/Chrome MacOS

#### Steps to reproduce

Can be seen on this sandbox: https://codesandbox.io/s/5z1z101l4x

#### Actual behavior

Small tick used on large Checkbox.

<img width="23" alt="image" src="https://user-images.githubusercontent.com/654103/42659411-170e7ff2-8620-11e8-9fb6-f3c5d015b36d.png">

#### Expected behavior

As docs:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/654103/42659430-29edf2ce-8620-11e8-8407-e51ea4027c16.png">

**Comment by will-stone** [comment]
PS congrats on the v3 release! It's looking good 😀

**Comment by giladgray** [comment]
fixed in #2709
