### ISSUE TITLE
Popover: Element type is invalid: expected a string but got Object

### ISSUE THREAD

**Issue by cmac458** [palantir/blueprint#2687]
#### Environment

- __Package version(s)__:
"@blueprintjs/core": "^3.0.0",
"react-transition-group": "^2.4.0",
"react": "^16.4.1",

- __Browser and OS versions__: 
Windows 7
Chrome Version 67.0.3396.99

#### Steps to reproduce

```
    let addMenu = (
      <Menu>
        <MenuItem icon="graph" text="Date Histogram"/>
        <MenuItem icon="chart" text="Bar Chart"/>
      </Menu>
    )

return (
        <Popover content={addMenu} minimal={true} position={Position.BOTTOM_LEFT} >
            <Button className={classes.right} icon="new-grid-item" />
          </Popover>
)
```

#### Actual behavior
The following Error appears in console, and the page doesn't load

> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of Manager

#### Expected behavior
Page loads and the popover is rendered.

#### Possible solution

n/a

**Comment by giladgray** [comment]
@cmac458 which version of blueprint are you using? have you installed `react-transition-group`?
please fill out the template as requested.

**Comment by cmac458** [comment]
@giladgray apologies, the issue has been updated with the appropriate detail

**Comment by giladgray** [comment]
@cmac458 thanks for updating. hmm this error suggests that something is returned an invalid JSX element. i've primarily seen this error when missing react-transition-group (#2511). 
do you also have `react-popper@1.0.0`?

**Comment by cmac458** [comment]
I didn't have` react-popper@1.0.0`. I have tried adding to the project along with popper.js, but I still face the same issue.

**Comment by giladgray** [comment]
🤷‍♂️
