### ISSUE TITLE
Passing 0 as text to <Button /> does not render any text

### ISSUE THREAD

**Issue by Foxhoundn** [palantir/blueprint#2703]
#### Environment

- __Package version(s)__: 3.0.1
- __Browser and OS versions__: Latest MacOS, latest Chrome

#### Steps to reproduce

1. `<Button text={0} />`

#### Actual behavior

Empty button rendered

#### Expected behavior

Button with 0 as text should be rendered

#### Possible solution

I suppose you're checking if the text prop is truthy, but 0 won't be truthy.

**Comment by giladgray** [comment]
😂 love it

**Comment by badams** [comment]
@giladgray any preference on the implementation? could attempt to convert the value to a string something like

`const textValue = text != null ? String(text) : undefined;`

This would support values like `<Button text={false} />` (not sure if this is a good thing) or do you think we just make a special case for `0`?

**Comment by giladgray** [comment]
definitely do not coerce the type, just check that it's defined. `text={false}` should render nothing, like any other JSX usage.

**Comment by giladgray** [comment]
this is the line to change: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/abstractButton.tsx#L152.

and please add a unit test.
