### ISSUE TITLE
Collapse doesn't animate on first open

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2706]
![ezgif com-optimize](https://user-images.githubusercontent.com/654103/42989994-4cd0c88c-8bf9-11e8-8959-e016f00528cf.gif)

#### Environment

- __Package version(s)__: v3.0.1
- __Browser and OS versions__: Chrome 67 / Safari 11.1.2 / Firefox 61, MacOS 10.13.6

#### Steps to reproduce

1. go to this docs page: http://blueprintjs.com/docs/#core/components/collapse
1. Click "Show build logs" demo button

#### Actual behavior

First open of the collapse object isn't animated and simply appears (also the button jumps left).
NB subsequent open and closes are animated.

#### Expected behavior

All open and close animations are animated.

#### Possible solution

Maybe use React-Spring?

**Comment by giladgray** [comment]
ugh `Collapse` needs so much love

**Comment by odusseys** [comment]
Any updates on this ? Quite annoying.

**Comment by giladgray** [comment]
nope. i've poked at it with no success. wanna take a stab?

**Comment by giladgray** [comment]
@odusseys nope sorry, please fork and push from there.
