### ISSUE TITLE
Any guidelines or recommandation on creating a custom theme?

### ISSUE THREAD

**Issue by tkrugg** [palantir/blueprint#2712]
#### Environment

- __Package version(s)__: 2.x or 3.x
- __Browser and OS versions__: N/A

#### Question

I'm wondering if there are any recommanded practices to create a custom theme on top of blueprint

**Comment by giladgray** [comment]
@tkrugg sorry we can't actually offer support for theming. but in theory you write your own `index.scss` file and overwrite all the variables you want to change (they're all marked `!default` in source so can be overwritten). then you `@import "~@blueprintjs/core/src/blueprint.scss"` to compile your own themed blueprint.css

**Comment by giladgray** [comment]
see #123 and #1619 for more discussion.
