### ISSUE TITLE
Table row and columns overlap

### ISSUE THREAD

**Issue by santosh-1987** [palantir/blueprint#2713]
Hi Team, 

  The table row and column overlap while rendering data using blueprint js table.

Code:

```
<Table
            className="results-table"
            numRows={this.state.numRows}
            selectionModes={SelectionModes.ALL}
            onSelection={this.onSelection}
            renderBodyContextMenu={this.renderBodyContextMenu}
            getCellClipboardData={this.getCellClipboardData}
            onColumnWidthChanged={this.onColumnWidthChanged}
            ref={(instance) => { this.tableInstance = instance; }}
            selectedRegions={this.state.selectedRegions.length !== 0 ? this.state.selectedRegions : null}
          >
            {this.renderColumns()}
          </Table>


```

It seems the header row for row numbers are missing.

Refer the image below:

![screenshot_2018-07-23 healtheanalytics - queries](https://user-images.githubusercontent.com/1287616/43070911-c22e3d16-8e8e-11e8-8ce4-6c95057d45c4.png)

Expexted Table:

![screenshot_2018-07-23 healtheanalytics - queries 1](https://user-images.githubusercontent.com/1287616/43070949-de631b28-8e8e-11e8-8a6a-26691bc10dca.png)

**Comment by giladgray** [comment]
@santosh-1987 weird! can you confirm which versions you are using? could be an issue with mis-measurement. you can try a `forceUpdate` after mounting.

**Comment by marcin212** [comment]
I have the same issue. My dependencies from package.json:
```
  "dependencies": {
    "@blueprintjs/core": "^3.0.1",
    "@blueprintjs/icons": "^3.0.0",
    "@blueprintjs/select": "^3.0.0",
    "@blueprintjs/table": "^3.0.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-scripts": "1.1.4",
    "recharts": "^1.1.0",
    "reflexbox": "^3.0.1"
  },
```

**Comment by giladgray** [comment]
sorry, i don't have a solution to offer. please investigate on your end some more. try the `forceUpdate()` trick to re-compute everything and try resetting `node_modules`.

the top screenshot has a much taller scrollbar (see the tiny handle) suggesting that there are way too many rows being rendered.

**Comment by santosh-1987** [comment]
forceUpdate works , closing the issue
