### ISSUE TITLE
Popover position incorrect when popover is open at first render

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#2714]
#### Environment

- __Package version(s)__: ^3.0.0",
- __Browser and OS versions__: 
ubuntu 18.04
mozilla 61.0.1
chrome 66

#### Steps to reproduce

Create a popover element which is open by default
Target tag name should be a div and popover should be position bottom.

#### Actual behavior

During the first load, the popover elements are not correctly set to the center bottom but on left center. Target element should'nt be set at the time the popover is draw which may render on a bad position.

![capture du 2018-07-23 14-20-41](https://user-images.githubusercontent.com/9548473/43076215-c394a538-8e83-11e8-8d16-4fe79972efd5.png)

after closing and reopening the popover position is correct

#### Expected behavior

![capture du 2018-07-23 14-23-11](https://user-images.githubusercontent.com/9548473/43076264-f2414044-8e83-11e8-9ed8-30c2ac743e1d.png)

**Comment by giladgray** [comment]
could be due to a flash of unstyled content, causing the popover to mis-compute element bounds. you can try issuing a `this.forceUpdate()` in `componentDidMount()` to see if that resolves the position issue

**Comment by LoiKos** [comment]
Your advice as been useful even if my context change and it seem to correct my problem ! thanks a lot !

**Comment by giladgray** [comment]
@LoiKos great! What did it? So we know when this comes up again.

**Comment by LoiKos** [comment]
In fact problems don't really come from popover ... i use it inside a Panel that use an CSSTransition to open and close. Children seems to be drawn when css transition beginning or running but before ending. So as width go from 0 to 260 the popover should see target width as null instead of the middle as it should be. 

I finally think there is nothing to correct on your side.

**Comment by giladgray** [comment]
ahhh yes transitions. perhaps don't start open and wait for `onEntered` event from `CSSTransition` before opening the popover. thanks for following up @LoiKos!
