### ISSUE TITLE
Disable built in blueprint icon titles

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2726]
![image](https://user-images.githubusercontent.com/2730609/43226279-40cb2954-9010-11e8-81aa-8b49a2041346.png)

Hey there, I'm just wondering if there is a recommended way to disable the default built in <title/> attributes that come with all blueprint icons (see above screenshot). I have yet to find a single case in my app where they are helpful and I mostly find them annoying to the user. 

Is there a good way to do that or do I manually need to override the title attribute in every single case? Ideally I could just block the default blueprint given titles, yet still be able to have my own custom titles when desired. 

Thanks!

**Comment by giladgray** [comment]
@tnrich this is fixed in 3.0.1 #2671

**Comment by tnrich** [comment]
Thanks and sorry for the duplicated question! :)
