### ISSUE TITLE
Context menu scrolls page when triggered

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#273]
### Bug Report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Firefox 48

#### Describe the issue:

![contextm](https://cloud.githubusercontent.com/assets/199754/20735115/c4fba97c-b652-11e6-9a54-0c53bfec2ae7.gif)

#### Actual behavior:

Context menu opens and the page scrolls, causing loss of context for users

#### Expected behavior:

Context menu appears without scrolling the page

**Comment by giladgray** [comment]
same issue as #183

**Comment by adidahiya** [comment]
more accurately, this is a duplicate of #231
