### ISSUE TITLE
bp3-popover-dismiss shouldn't always dismiss all popovers in the hierarchy 

### ISSUE THREAD

**Issue by badams** [palantir/blueprint#2735]
#### Environment

- __Package version(s)__: develop
- __Browser and OS versions__: Chrome 68.0.3440.75

#### Actual behavior

Current behaviour associated with the `POPOVER_DISMISS`:
Popovers catch all click events bubbling and if the target of the event has a DISMISS_POPOVER class near it, this popover will close itself.

The issue I have with this behaviour can be seen in [this example](https://codesandbox.io/embed/jz98r36z49)

#### Expected behavior
Clicking a menu item should close the menu, but not the main popover.

#### Possible solution

Currently we work around this issue by trapping the event with stopPropagation(), which can be seen [here](https://codesandbox.io/embed/0436z8068p)

As far as I can tell the main reason the behaviour is implemented like this is so clicking an item in a nested sub-menu will close all parent menus. if this is the case, wouldn't it make more sense for the Menu component to handle this internally somehow?

Would love to hear what other peoples thoughts are on this, or is simply trapping the event in user-land code good enough?

**Comment by giladgray** [comment]
@badams ah interesting, i agree this event bubbling should be handled more safely.

**Comment by giladgray** [comment]
@badams fix in progress at #2758! new `captureDismiss` prop to prevent dismissing outer popovers

**Comment by badams** [comment]
Awesome! Sounds like good solution @giladgray

**Comment by PhilTheAir** [comment]
There is similar issue when you use menu and alert / overlay / drawer. If you click the menu item to open the alert / overlay / drawer, the alert window will flash and then dissappear. If you don't use alert but use Button with this class "bp3-popover-dismiss", it will be the same issue.

**Comment by adidahiya** [comment]
@PhilTheAir your problem is most likely to be addressed if you file a new issue, ideally with a code sandbox
