### ISSUE TITLE
Slider should have an option to use a non-linear scale

### ISSUE THREAD

**Issue by jasonbarry** [palantir/blueprint#2739]
#### Environment

- __Package version(s)__: 2.0
- __Browser and OS versions__: Safari 11.1, macOS 10.12.6

#### Feature request

It would be great if with Slider you could choose between linear and logarithmic scale, or be able to pass in your own function to determine numeric distribution.

**Comment by giladgray** [comment]
@jasonbarry you can accomplish this easily with `labelRenderer` by transforming the linear value before it appears in the DOM.

**Comment by giladgray** [comment]
easily handled by rendering a linear value however you choose. will not implement in the component itself.
