### ISSUE TITLE
How can I add more className for Dialog container

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#2749]
#### Environment
    "@blueprintjs/core": "^3.0.1",
    "@blueprintjs/datetime": "^3.0.0",
    "@blueprintjs/select": "^3.0.0",
     "react": "^16.4.1",
    "react-dom": "^16.4.1",
#### Question
![image](https://user-images.githubusercontent.com/19413272/43508409-062a5498-959a-11e8-87db-f828ffe30e16.png)
How can I add more className same level of: bp3-dialog-container bp3-overlay-content bp3-overlay-enter-done.

Source code

style.scss
```
.bp3-overlay-content {
	align-items: flex-start;
	justify-content: flex-start;
}
:local(menuDialog) {
	align-items: flex-start;
	justify-content: flex-start;
}
```

popup.tsx
```
const MenuView = ({ isOpen, popUpMenu }: IMenuPropsIn) => (
	<>
		<Dialog isOpen={isOpen} className="menuPopup" backdropClassName={styles.menuDialog}>
			<MenuContent />
		</Dialog>
		<Button className={Classes.MINIMAL} icon="menu" text="Menu" onClick={popUpMenu} />
	</>
)

```

**Comment by giladgray** [comment]
@tomzaku sure that'll do it

**Comment by NearAutomata** [comment]
Correct me if I am wrong, but can't you just use the `[clasnames](https://www.npmjs.com/package/classnames)` package for multiple (and conditional) classnames?

**Comment by giladgray** [comment]
@NearAutomata the original question was about adding classes to an element that does not support adding custom classes (because it has no corresponding `*ClassName` prop).
