### ISSUE TITLE
TabList React Warning when Unmounted Right after a componentDidUpdate

### ISSUE THREAD

**Issue by brahms** [palantir/blueprint#275]
This function is causing a warning:

```
TabList.prototype.componentDidUpdate = function (prevProps) {
        var _this = this;
        if (prevProps.indicatorWrapperStyle == null) {
            setTimeout(function () { return _this.setState({ shouldAnimate: true }); });
        }
};
```

"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component."

**Comment by giladgray** [comment]
fix: track the returned `timeoutId` and clear it in `componentWillUnmount`
