### ISSUE TITLE
Dialog are closed when Date picker (DateInput on Dialog) closed

### ISSUE THREAD

**Issue by threeid** [palantir/blueprint#2753]
#### Environment

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome latest, Firefox latest, Ubuntu 16

Code:
https://codesandbox.io/s/oj6z97qk55

#### Steps to reproduce

1. Click on DateInput
2. Pick a date

#### Actual behavior

Dialog close with Date picker

#### Expected behavior

Date picker should close as normal
Dialog should stay open

**Comment by giladgray** [comment]
duplicate of #2159

**Comment by giladgray** [comment]
@threeid fix in progress at #2756!
