### ISSUE TITLE
How to I remove blue frame when clicking the button

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#2755]
#### Environment

"react": "^16.4.1",
"@blueprintjs/core": "^3.0.1",
"@blueprintjs/datetime": "^3.0.0",
"@blueprintjs/select": "^3.0.0",

#### Question

How to I remove blue frame when clicking the button like this
![image](https://user-images.githubusercontent.com/19413272/43571400-11bb68a6-9667-11e8-9ed4-26d8678040c2.png)
or this
![image](https://user-images.githubusercontent.com/19413272/43571434-28d91844-9667-11e8-8470-7fd6cb36fed9.png)
![image](https://user-images.githubusercontent.com/19413272/43571441-2ca68056-9667-11e8-9110-7d2050ff5283.png)

**Comment by amazing-space-invader** [comment]
@tomzaku Hey, check [FocusStyleManager API](http://blueprintjs.com/docs/#core/accessibility.focus-management)
