### ISSUE TITLE
Documentation version toggle does not seem to be working

### ISSUE THREAD

**Issue by rcchen** [palantir/blueprint#2763]
#### Environment

- __Package version(s)__: irrelevant
- __Browser and OS versions__: macOS 10.14, Firefox 61.0.1

#### Steps to reproduce

1. Go to the docs website and try to change the version from v3 to v1 😢 

#### Actual behavior

Doesn't do anything.

#### Expected behavior

Goes to v1 docs.

#### Possible solution

Guessing that the internal routing is mucking with "external routing" since they're part of different docs compilations.

**Comment by nickleach** [comment]
@rcchen Looks like their routing is just messed up atm. http://blueprintjs.com/docs/versions/1/ Seems to work

**Comment by arvinsim** [comment]
If you just click it, nothing happens. But if you open the link in a new tab, it works fine.
