### ISSUE TITLE
Migrating to 3.0: Autocorrecting "visual" to "icon" yields false positives 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#2764]
#### Environment

- __Package version(s)__: Migration from 2.X => 3.X

#### Steps to reproduce

1. Follow the [Blueprint 3.0 migration guide](https://github.com/palantir/blueprint/wiki/3.0-Changelog#-migration-guide).
1. Run `.$(npm bin)/upgrade-blueprint-3.0.0-rename --path=path/to/src`.

#### Actual behavior

The script changes several instances of `"visual"` to `"icon"` unnecessarily. e.g.:

```diff
- // Adjust for visual correctness
+ // Adjust for icon correctness
```

```diff
- // See https://www.website.com/blah/blah/visual-design/blah
+ // See https://www.website.com/blah/blah/icon-design/blah
```

#### Expected behavior

No false positives.

#### Possible solution

In my case, _all_ of the changes with `"visual"` were false positives. Would recommend skipping that one and requiring user intervention:

```
WARNING: Skipping visual -> icon
Can't safely change visual, you'll need to manually rename/remove this string.
It was found in these files 1 files:
```

**Comment by giladgray** [comment]
@cmslewis since it's a prop change, I wonder if changing the pattern to `visual=` would reduce the false positives?

**Comment by giladgray** [comment]
closing out as we're not going to use these bash scripts anymore.
