### ISSUE TITLE
How to set max-height CSS attributte for <Select> component?

### ISSUE THREAD

**Issue by MartyIX** [palantir/blueprint#2768]
#### Environment

- __Package version(s)__: 3.1.0
- __Browser and OS versions__: N/A

#### Question

Hi,

How can I set `max-height` for `<Select>` (http://blueprintjs.com/docs/#select/select-component) popover?

I have found http://blueprintjs.com/docs/#core/components/popover.sizing but I'm not sure if I can actually achieve that.

Thank you

Best regards,
Martin Vseticka

**Comment by giladgray** [comment]
@MartyIX use `popoverClassName` to assign a class that sets relevant CSS properties.

**Comment by MartyIX** [comment]
Thank you very much!
