### ISSUE TITLE
Migrating to 3.0: Autocorrecting "iconName" to "icon" yields false positives

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#2771]
#### Environment

- __Package version(s)__: Migration from 2.X => 3.X

#### Steps to reproduce

1. Follow the [Blueprint 3.0 migration guide](https://github.com/palantir/blueprint/wiki/3.0-Changelog#-migration-guide).
1. Run `.$(npm bin)/upgrade-blueprint-3.0.0-rename --path=path/to/src`.

#### Actual behavior

The script changes several instances of `"iconName"` to `"icon"` unnecessarily. Besides being inconvenient in those cases, it can also produce compilation errors, e.g.:

```diff
- const iconName = isTrue ? "custom-icon-1" : "custom-icon-2";
- const icon = <MyCustomIcon icon={iconName} />;
+ const icon = isTrue ? "custom-icon-1" : "custom-icon-2";
+ const icon = <MyCustomIcon icon={icon} />;
```

Note that I now have conflicting variables named `icon`.

There were quite a few other instances like this, where my custom components' icon-related props were undesirably affected by the Blueprint 3.X upgrade script.

#### Expected behavior

No false positives.

#### Possible solution

Would recommend skipping `iconName => icon` and requiring user intervention:

```
WARNING: Skipping iconName -> icon
Can't safely change iconName, you'll need to manually rename/remove this string.
It was found in these files 1 files:
```

**Comment by giladgray** [comment]
the current scripts are incapable of doing this properly (regex is not smart enough) but our internal tooling handles it with aplomb @cmslewis!
