### ISSUE TITLE
Migrating to 3.0: InputGroup has extra right padding when nested inside ControlGroup

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#2774]
#### Environment

- __Package version(s)__: `@blueprintjs/core` 3.2.0

#### Steps to reproduce

1. Render the following structure:

```tsx
<ControlGroup>
    <InputGroup value="Looooooooong text" />
    <Button />
</ControlGroup>
```

#### Actual behavior

`<InputGroup>` has non-zero padding on the right, styled inline: 
![image](https://user-images.githubusercontent.com/443450/43797090-1435b03c-9a3b-11e8-909e-d0ba62c99a95.png)

![image](https://user-images.githubusercontent.com/443450/43797140-4bd83e42-9a3b-11e8-8804-bb3b284d8564.png)

#### Expected behavior

No padding when followed by a button in a control group:

![image](https://user-images.githubusercontent.com/443450/43797151-55d49c9c-9a3b-11e8-8b7e-8142ca9430af.png)

![image](https://user-images.githubusercontent.com/443450/43797132-42280fee-9a3b-11e8-90de-c778917bf2f4.png)

**Comment by giladgray** [comment]
oops, the original "expected" behavior was the bug!
