### ISSUE TITLE
How can make left to right transition of dialog when opening? 

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#2778]
#### Environment

"react": "^16.4.1",
"@blueprintjs/core": "^3.0.1",
"@blueprintjs/datetime": "^3.0.0",
"@blueprintjs/select": "^3.0.0",

#### Question
I would like to make a specific left to right animation when dialog is opening. 
I read the document has `transitionName` prop. How can I use that or give me some example/ code?

**Comment by giladgray** [comment]
@tomzaku refer to the external [`CSSTransition`](http://reactcommunity.org/react-transition-group/css-transition/) docs to understand how transitions are implemented. Blueprint includes a [dope Sass mixin](https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/_react-transition.scss) to generate the correct styles; [see it in use on `Dialog` here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/dialog/_dialog.scss#L42-L54).

**Comment by giladgray** [comment]
@tomzaku i can't offer you a better example than Blueprint's own source code. further, `CSSTransition` is a widely used external library so google should have some advice.

**Comment by dylangrandmont** [comment]
In case anyone else encounters this, hopefully my comment on a similar issue is useful https://github.com/palantir/blueprint/issues/2449#issuecomment-1780091787
