### ISSUE TITLE
Tooltip on disabled Button can get stuck on Chrome

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#2779]
#### Environment

- __Package version(s)__: 3.2.0
- __Browser and OS versions__: Chrome 68 (affected), Firefox 59 (not affected)

#### Steps to reproduce

1. Open https://codesandbox.io/s/3xnpj1k8rq in Chrome
2. Hover the disabled button until the tooltip is shown and then quickly move the mouse out.

#### Actual behavior

The tooltip gets stuck after the mouse has left the button.

#### Expected behavior

The tooltip should hide after `hoverCloseDelay` has passed and the mouse has left.

#### Possible solution

I think the issue is that the mechanism that hides the tooltip may depend on a `mouseleave` event which may not be guaranteed to fire on disabled buttons. Interestingly, I was not able to reproduce the bug in Firefox.

**Comment by adidahiya** [comment]
see http://blueprintjs.com/docs/#core/components/button

![image](https://user-images.githubusercontent.com/723999/43847158-f646a3e2-9afd-11e8-8447-e37fe2a7d03e.png)

**Comment by silverwind** [comment]
Thanks, sorry I missed reading that. Can confirm `AnchorButton` works as expected.

**Comment by Hesam-Eskandari** [comment]
I would wrap a span around the button and put the tooltip for the span (outside of the button)

**Comment by hdavidzhu** [comment]
@Hesam-Eskandari I just tried wrapping with a span and that didn't work 🤷
