### ISSUE TITLE
Feature request: ListBox component

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#278]
I wish fantastic blueprint would also offer a simple **ListBox** to present multiple items vertically as a single continuous element. It should have
* customizable items (so I can have any React/HTML in there);
* none/single/multiple select, selection spans.

I'm asking for an API similar to but way simpler than blueprint's [Table](http://blueprintjs.com/docs/#components.table-js) or [Tree](http://blueprintjs.com/docs/#components.tree) components.

See also [List in Material UI](http://www.material-ui.com/#/components/list).

**Comment by brsanthu** [comment]
ListBox should also be virtualized so that huge number of items will not slowdown the rendering.

**Comment by adidahiya** [comment]
I think `Menu` and `QueryList` largely cover these use cases. Virtualized rendering is a separate concern; I'd rather leave that to a library like [react-virtualized](https://github.com/bvaughn/react-virtualized) (if you have specific issues using that library with Blueprint, feel free to file a new issue.
