### ISSUE TITLE
Unsafe legacy lifecycles in React 16

### ISSUE THREAD

**Issue by JakobReiter** [palantir/blueprint#2787]
#### Environment

- __Package version(s)__: 
    "@blueprintjs/core": "^3.2.0",
    "@blueprintjs/icons": "^3.0.0",
    "@blueprintjs/select": "^3.1.0",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "redux": "^3.7.2",
- __Browser and OS versions__: electron: "^1.7.11",

#### Steps to reproduce

1. Create Select Box
```js
<Select
  items={this.props.projects}
  itemRenderer={this.ProjectRenderer}
  noResults={<MenuItem disabled={true} text="No results." />}
  onItemSelect={e => {console.log(e); }}
  >
    <Button text={"-- all Projects --"} rightIcon="double-caret-vertical" />
  </Select>
```
2. Click on Button

#### Error Message on Console
```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Transition uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```
```
Warning: Received `true` for a non-boolean attribute `appear`.

If you want to write it to the DOM, pass a string instead: appear="true" or appear={value.toString()}.
    in div (created by TransitionGroup)
    in TransitionGroup (created by Blueprint3.Overlay)
    in Blueprint3.Portal (created by Blueprint3.Overlay)
    in Blueprint3.Overlay (created by Blueprint3.Popover)
    in span (created by Blueprint3.Popover)
    in Manager (created by Blueprint3.Popover)
    in Blueprint3.Popover (created by Blueprint3.QueryList)
    in Blueprint3.QueryList (created by Blueprint3.Select)
```

#### Solution
Remove `componentWillMount` and `componentWillReceiveProps` from module and place code in `getDerivedStateFromProps`.   
See https://fb.me/react-async-component-lifecycle-hooks

**Comment by giladgray** [comment]
@JakobReiter this is not coming from Blueprint but from `react-transition-group` which provides the `Transition` component mentioned in the error message. see https://github.com/reactjs/react-transition-group/issues/368
