### ISSUE TITLE
Feature request: isRowNumberColumnShown prop for Table

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#279]
Could you please add a property to [Table](http://blueprintjs.com/docs/#components.table-js) component that would allow for hiding the very first column showing the row numbers, e.g. `isRowNumberColumnShown`. 

There are many uses for table-like components where the row number isn't important for users at all. One example is using a one-column, sortable table as (poor man's) replacement for a ListBox (see my #278).

**Comment by adidahiya** [comment]
This prop already exists -- it is called `isRowHeaderShown`. We could change the prop description to enhance searchability now, and rename it to be more legible in the next major version.

**Comment by forman** [comment]
Great, that's it, I should have read more carefuly, thanks!
