### ISSUE TITLE
Nested submenu loses click event sometimes

### ISSUE THREAD

**Issue by mizchi** [palantir/blueprint#2796]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "3.2.0",

- __Browser and OS versions__: Google Chrome 68 / Mac

#### Steps to reproduce

1. Open submenu
1. Click submenu

My code

```js
    <Menu>
      <MenuItem icon="document-open" text="Open">
        {items.map((i, index) => {
          return (
            <MenuItem
              key={index}
              text={i.name}
              onClick={() => console.log('selected', i.name)}
            />
          )
        })}
      </MenuItem>
      ...
   </Menu>
```

![](https://i.gyazo.com/cc62351182eb8e87fabab4ea1b1897b0.gif)

#### Actual behavior

Emit onClick and close submenu.

#### Expected behavior

Sometimes it does not emit onClick and can not close menu popup.

#### Possible solution

I doubt lazy behavior to initialize handler, but submenu(MenuItem) does not have lazy prop. I can not find what happen yet.

**Comment by giladgray** [comment]
this is due to #2758, which I disabled in #2776. hasn't shipped yet so set `captureDismiss={false}` on `<Popover>` for now.

**Comment by mizchi** [comment]
`@blueprintjs/core@3.4.0` does not fix in my env

**Comment by giladgray** [comment]
@mizchi i don't have enough information to offer more guidance. your code looks fine and this works happily on the docs site.

**Comment by kuanb** [comment]
Update: I was able to resolve above issue based off of suggestion in this other issue: https://github.com/palantir/blueprint/issues/3010#issuecomment-443031120

**Comment by adidahiya** [comment]
closing in favor of #3010
