### ISSUE TITLE
[Datetime] Timepicker time bounds does not work correctly with AM/PM mode

### ISSUE THREAD

**Issue by jacekjagiello** [palantir/blueprint#2797]
#### Environment

- __Package version(s)__: 3.2.0
- __Browser and OS versions__: Firefox 61 Mac OS X 10.12.16

#### Steps to reproduce

1. Go to timepicker example
2. Enable "Use AM/PM", Set minimum to 6pm and maximum time to 2am
1. Increment time until you reach 2am

![timepicker-bug-2](https://user-images.githubusercontent.com/2925620/43999389-cc3de87e-9e0b-11e8-879b-53e00fbed3c9.gif)

#### Actual behavior
Timepicker overlaps between PM -> AM incorrect. When you reach AM, you can't back to PM

#### Expected behavior
Time is should overlap correctly between from PM to AM, and from AM to PM

#### Possible solution
I'll start working on fix for this

**Comment by evansjohnson** [comment]
This no longer reproduces at https://blueprintjs.com/docs/#datetime/timepicker
