### ISSUE TITLE
[DateTime] Drop dependency on Icon fonts

### ISSUE THREAD

**Issue by mrijke** [palantir/blueprint#2801]
#### Environment

- __Package version(s)__: @blueprintjs/datetime": "3.0.0"
- __Browser and OS versions__: Chromium & Ubuntu 16.04

#### Feature request
The current implementation of the Date picker relies on the icon font for the previous and next month buttons and as far as I understood, icon fonts were considered legacy within this project. It would be nice to be able have SVG icons for those, or even better, be able to provide our own (for example, FontAwesome icons).
Thanks for your consideration!

**Comment by giladgray** [comment]
@mrijke indeed it does and I actually have a fix for that open _right now_ #2792

**Comment by mrijke** [comment]
@giladgray That's great news! I'll be monitoring that PR. Thanks for your quick response.

**Comment by TranTrongKh** [comment]
ok
