### ISSUE TITLE
Slider does not slide (but does change state on click)

### ISSUE THREAD

**Issue by riley-steele-parsons** [palantir/blueprint#2803]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^3.3.0"
- __Browser and OS versions__: Chrome, macOS High Sierra

#### Steps to reproduce

1. Click slider to advance position
1. Attempt to drag slider

Actual rendered HTML (note that this is embedded within a div inside a Blueprint Menu Component):
```
<div class="bp3-slider">
    <div class="bp3-slider-track">
        <div class="bp3-slider-progress" style="left: 0%; right: 100%; top: 0px;"></div>
        <div class="bp3-slider-progress bp3-intent-primary" style="left: 0%; right: 21%; top: 0px;"></div>
        <div class="bp3-slider-progress" style="left: 79%; right: 0%; top: 0px;"></div>
    </div>
    <div class="bp3-slider-axis">
        <div class="bp3-slider-label" style="left: 0%;">0</div>
        <div class="bp3-slider-label" style="left: 10%;">10</div>
        <div class="bp3-slider-label" style="left: 20%;">20</div>
        <div class="bp3-slider-label" style="left: 30%;">30</div>
        <div class="bp3-slider-label" style="left: 40%;">40</div>
        <div class="bp3-slider-label" style="left: 50%;">50</div>
        <div class="bp3-slider-label" style="left: 60%;">60</div>
        <div class="bp3-slider-label" style="left: 70%;">70</div>
        <div class="bp3-slider-label" style="left: 80%;">80</div>
        <div class="bp3-slider-label" style="left: 90%;">90</div>
        <div class="bp3-slider-label" style="left: 100%;">100</div>
    </div><span class="bp3-slider-handle" tabindex="0" style="left: calc(79% - 8px);"><span class="bp3-slider-label">79</span></span>
</div>
```

#### Actual behavior

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31045418/44166650-c23f8180-a080-11e8-8315-f010a0af7524.gif)

Slider changes position on click but not on slide (note that this worked perfectly in version ^2.0)

#### Expected behavior

Slider should slide with a drag interaction

**Comment by riley-steele-parsons** [comment]
@giladgray, no it's not in a popover.

**Comment by riley-steele-parsons** [comment]
@giladgray, here's the the usage within my functional component:

**Comment by riley-steele-parsons** [comment]
@giladgray, I'm slightly skeptical of the partially controlled usage argument because I'm able to see state/prop changes upon clicking and this configuration and logic was working perfectly with the previous 2.0 `Slider`.

**Comment by giladgray** [comment]
@riley-steele-parsons i see a very tiny movement of the handle in the gif above, which suggests that it's trying to move but failing. perhaps try a `forceUpdate()` to recompute all the DOM measurements?

**Comment by riley-steele-parsons** [comment]
@giladgray, I'll try adding that to the `onChange` callback. The movement is seemingly from the increment/decrement of one unit, but then the sliding stop. Then, like I said, the movement is also from clicking on the bar to change the position of the slider, which works as expected.

**Comment by giladgray** [comment]
@riley-steele-parsons all this suggests there's something in your app environment interfering with the handlers. when dragging, listeners are attached to `document` to capture drags everywhere. maybe you are capturing those events somehow? 

i've never seen this happen in all my years of watching `Slider` used at Palantir,.

**Comment by riley-steele-parsons** [comment]
@giladgray: I suppose that could be possible... I'll try to track down if there is anything else capturing the drags. If there is this kind of interference taking place do you have any suggestions as to how to prevent it?

**Comment by giladgray** [comment]
@riley-steele-parsons that's gonna be on you to fix it. basically avoid `stopPropagation()` at all costs

**Comment by Sourjya-Basu** [comment]
Hello ! I am actually figuring out the problem in your code,give me a time of 2 months...-your pen friend Sourjya Bose

**Comment by riley-steele-parsons** [comment]
This issue has been resolved on my side.
