### ISSUE TITLE
Allow non-small components to be used inside a condensed table

### ISSUE THREAD

**Issue by tomshen** [palantir/blueprint#2806]
#### Environment

- __Package version(s)__: 3.0.1
- __Browser and OS versions__: Google Chrome 68.0.3440.106, MacOS 10.13.6

#### Steps to reproduce

```js
<HTMLTable small={true}>
  .
  .
  .
  <Button small={false}>Cancel</Button>
  .
  .
  .
</HTMLTable>
```

#### Actual behavior

A small button renders in a condensed table.

#### Expected behavior

A normally sized button renders in a condensed table.

#### Possible solutions

- Remove `.#{$ns}-small &` from https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/_button.scss#L76.
- Change `.#{$ns}-small` on `HTMLTable` to `.#{$ns}-condensed`

**Comment by giladgray** [comment]
> Remove `.#{$ns}-small &` 

this exists for `<ButtonGroup small>` so we cannot remove it. we could change the selector to include a `>` but then we'd also need to handle the wrapped-in-a-`Popover` case

**Comment by giladgray** [comment]
I'd be okay with bringing back `condensed` though it's gotta be done in a non-breaking way.
