### ISSUE TITLE
v3 certain css missing

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2807]
This line of css used to exist in v2: 
```
.pt-popover-wrapper {
    display: inline-block;
    position: relative;
    vertical-align: top;
}
```

but 
```
.bp3-popover-wrapper {
    display: inline-block;
    position: relative;
    vertical-align: top;
}
```

doesn't seem to be in v3 

Any reason why this might be? Definitely causing all sorts of issues for us so we'll be patching it.

I believe there might be some other css weirdness occurring related to popovers but I'll add more info to this issue as I figure more out. Thanks!

Cheers,
T 

PS We've also decided to re-apply all the <h/> stylings manually. I generally disagree with the decision to remove the default html element stylings but that's another discussion I suppose.

**Comment by tnrich** [comment]
aha! Found another difference that is causing issues for us. 

This line of css was added in v3
```
span.bp3-popover-target {
  display: inline-block;
}
```

This was not in v2 and is causing issues due to the issue I pointed out in https://github.com/palantir/blueprint/issues/2808 (v3 pt-popover-target is no longer a div (it's now a span)) 

I'll be manually patching this but again am wondering why this was added and wondering if it will be fixed by y'all. 

Thanks!

**Comment by tnrich** [comment]
@giladgray I'm not sure I understand what you're saying. The lack of the following chunk of css causes multiple issues for us. We'll go ahead and leave the patch in if you're not planning on adding it back. 

```css
.bp3-popover-wrapper {
    display: inline-block;
    position: relative;
    vertical-align: top;
}
```

**Comment by newstart346** [comment]
Hey this me I'm sorry Ben of love awhile
