### ISSUE TITLE
v3 pt-popover-target is no longer a div (it's now a span) 

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2808]
Hey there, 

For some reason it appears the pt/bp3-popover-target default element changed from a div to a span (old version on the left, new version on the right): 

![image](https://user-images.githubusercontent.com/2730609/44174337-af847700-a097-11e8-8444-15d03ae380b2.png)

This is causing issues for us where now things that were rendering with 0 height when the child element had 0 height are now rendering with a non-zero height. The names are now being blocked by that popover wrapper with a non-zero height (again old on left and new on right):

![image](https://user-images.githubusercontent.com/2730609/44174429-fd00e400-a097-11e8-92fb-df7e28bb7d24.png)

Why is this the case and how can we get the old default back?

Thanks!

**Comment by badams** [comment]
@tnrich you can use the `targetTagName` prop on the popover component like so 
```
<Popover targetTagName="div" />
```
For more details see the [docs](https://blueprintjs.com/docs/#core/components/popover.props)

**Comment by tnrich** [comment]
Hey @badams, I am aware of that prop but thank you for pointing it out. It's not an ideal solution for me because I'd like to have all instances of popover look the same as they did in bp2.

Also, while changing the span back to a div does fix this specific issue, I think the core of the problem is   being caused by a line of css that was added in bp3: 
```
span.bp3-popover-target {
  display: inline-block;
}
```

**Comment by giladgray** [comment]
@tnrich the real change there was to make _both the wrapper elements use the same element by default_. in the previous screenshot, you have `div > span`, now you have `span > span`. you can change each element with `wrapperTagName` and `targetTagName` as @badams said.

you can also modify `Popover.defaultProps` to change the defaults globally.

**Comment by giladgray** [comment]
the `inline-block` line is to prevent the default `inline` behavior where `<span>` tags have no dimensions of their own.

**Comment by giladgray** [comment]
closing as resolved. don't think there's anything to do here.
