### ISSUE TITLE
How to apply tabs into react-router-dom

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#2809]
#### Environment
```
"react": "^16.4.1",
"@blueprintjs/core": "^3.0.1",
"@blueprintjs/datetime": "^3.0.0",
"@blueprintjs/select": "^3.0.0",
```
#### Question

My purpose is only using the menu tab ( not including content) like this picture below. Because the `Route` do that for me. 
![image](https://user-images.githubusercontent.com/19413272/44186583-7eae4b80-a144-11e8-82bc-984b8be105a6.png)
My code look like this but it's absolutely not work.
```ts
const renderChildTabs = (tabs: ITabProps[] = []) => {
	return tabs.map((tab, key) => (
		<Link to={tab.path} key={key}>
			<Tab id={tab.path} title={tab.title} />
		</Link>
	))
}
const AppTabView = ({ tabs }: ICreateTabContainerPropsOut) => {
	return (
		<>
			<div>
				<Tab id={v4()}>
					{renderChildTabs(tabs)}
				</Tab>
				<Body tabs={tabs} />
			</div>
		</>
	)
}
```
I think the error here cuz the Tab query all the children but don't see `Tabs` it only show 'Link'. That why it didn't show anything

In addition: The panel in the bottom of tab get  the position by using id Jquery selector. I think it not good for react. When you resize the page it was broken like this below
Before
![image](https://user-images.githubusercontent.com/19413272/44186938-853dc280-a146-11e8-9039-5d34f456559b.png)

After
![image](https://user-images.githubusercontent.com/19413272/44186930-7c4cf100-a146-11e8-8d02-7bdf54fcf439.png)

**Comment by giladgray** [comment]
@tomzaku in `AppTabView` you render a `<Tab id={v4()}>` which I think should be a `<Tabs>`? gotta put individual `Tab` children inside a `Tabs`, not another `Tab`.

**Comment by giladgray** [comment]
also try putting the `Link` in the `Tab title` instead of around it.
`<Tab title={<Link ... />} />`

**Comment by tomzaku** [comment]
It's work
```ts
	const ListTabView = ({ tabs, match, changeId, selectedId, className }: IListTabPropsIn) => {
	const ListTab = tabs.map((tab, key) => (
		<Tab title={
			<Link to={makeUpdatePath(match.url)(tab.path)} key={key}>
				<div
					key={tab.path}
					onClick={() => changeId(tab.path)}
					className={classnames(
						'tab',
						't-color',
						'p-h-sm',
						{ 'tab--selected': selectedId === tab.path },
						className,
					)}
				>
					{tab.title}
				</div>
			</Link>
		} id={tab.path}/>
	))
	return (
		<Tabs id={v4()} selectedTabId={selectedId}>
			{ListTab}
		</Tabs>
	)
}
```
