### ISSUE TITLE
EditableCell/EditableName not truncating properly

### ISSUE THREAD

**Issue by brandonchoe** [palantir/blueprint#281]
### Bug report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit) and OS X El Capitan 10.11.6

#### Steps to reproduce

1. Render an `EditableCell`/`EditableName` with lengthy content (resizing column is not necessary).

#### Actual behavior

<img width="743" alt="screen shot 2016-11-30 at 5 10 04 pm" src="https://cloud.githubusercontent.com/assets/14318012/20773571/714f0246-b720-11e6-9309-0235b2b9c592.png">

#### Expected behavior

<img width="742" alt="screen shot 2016-11-30 at 5 13 49 pm" src="https://cloud.githubusercontent.com/assets/14318012/20773565/6cf337a8-b720-11e6-8078-d69eae6fd994.png">

**Comment by themadcreator** [comment]
Looks like a `min-width` CSS style is being applied to the content. Will investigate fix.
