### ISSUE TITLE
Non-Modal Dialogs

### ISSUE THREAD

**Issue by arvinsim** [palantir/blueprint#2810]
#### Environment

BlueprintJS 3.3.0

#### Question

Looking at the [Overlay](https://blueprintjs.com/docs/#core/components/overlay) docs, I don't see an option to set the Dialog to non-modal mode.

Does BlueprintJS support non-modal mode for its dialogs?

**Comment by giladgray** [comment]
@arvinsim Dialog deliberately does not support "non-modal" usage: it is only modal and always blocking. other Overlays allow disabling the backdrop, but Dialog explicitly does not.
