### ISSUE TITLE
Table custom setup

### ISSUE THREAD

**Issue by tmasunda** [palantir/blueprint#2811]
#### Environment

- __Package version(s)__: @blueprintjs/table": "^3.1.0"
- __Browser and OS versions__: 

#### Question

I need more information on how to order columns in a particular way and how to hide some columns given data from re-base and firestore, please assist.

I want to order columns from data passed into the table. I also want to hide some of the columns and add buttons that can open another page using row data.

**Comment by giladgray** [comment]
@tmasunda sorry we don't have such resources to offer. i'll refer you to the [table docs](https://blueprintjs.com/docs/#table) (which I trust you've already read, maybe more than once). poke at the examples source code.

**Comment by murtagha** [comment]
qqet8jvcxutgxt0rg4rkf379cnx5hc799uzaamena3
