### ISSUE TITLE
Downloading `sort` icon returns a server error, not an SVG

### ISSUE THREAD

**Issue by mulholio** [palantir/blueprint#2814]
#### Environment

- __Package version(s)__: 3.0
- __Browser and OS versions__: Chrome, Firefox

#### Steps to reproduce

1. Visit https://blueprintjs.com/docs/#icons
2. Right click to download 16px or 20px sort icon.

#### Actual behavior

The downloaded file contains an error:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 backend read error</title>
  </head>
  <body>
    <h1>Error 503 backend read error</h1>
    <p>backend read error</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-lcy19235-LCY 1534511318 1142642233</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

#### Expected behavior

A working SVG!

---

* Doesn't appear to be a problem on other icons that I have tried.
* Have tested on Chrome and Firefox and fails on both.
* Icon is working within my app so it's just the downloading off of the docs.

**Comment by giladgray** [comment]
@mulholio i cannot repro, downloads fine for me. possible you were not authenticated to github, or GH had an error blip? please try again.

**Comment by mulholio** [comment]
Yep, working fine now. Weird it was just for that one icon. How mysterious...

**Comment by TranTrongKh** [comment]
hi
