### ISSUE TITLE
EditableCell should expose 'editableTextProps'

### ISSUE THREAD

**Issue by Corey-Arneson** [palantir/blueprint#2815]
#### Environment

- __Package version(s)__: blueprint/table: 3.1.0
- __Browser and OS versions__: NA

#### Feature request

It would be very useful for our use cases (and from looking through the open issues, others as well) if the EditbleCell allowed for EditableText props to be passed down to use functionality such as placeholder, maxLength, multiline, maxLines, minLines, and default value. In complex editable grid scenarios, being able to tap into these existing behaviors of EditableText would be a massive timesaver and removes the need to create completely custom cell components in order to pass a single additional prop to the cell editor.

#### Examples
Support in a cell rendererer: 
```javascript
return (
    <EditableCell 
        key={key} 
        id={id} 
        value={value} 
        // This prop would be great to be able to pass
        editableTextProps={{ 
            maxLength: 255, 
            placeholder: 'Please enter a unique value',
        }}
    />
);
```

**Comment by giladgray** [comment]
@Corey-Arneson yeah seems legit. happy to review a PR>

**Comment by giladgray** [comment]
@Corey-Arneson (but so you're aware, this React table library is mostly dead in the water and we are working on a stupid-fast replacement)

**Comment by TranTrongKh** [comment]
hi
