### ISSUE TITLE
Change `pt-` prefix to `bp-`

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#283]
No reason to carry Palantir as a classname namespace

**Comment by cmslewis** [comment]
#breakallthethings. Makes sense though.

**Comment by adidahiya** [comment]
No, I really don't see the value in this change at this point. It provides marginal benefits at unnecessary cost. Apple's APIs are all prefixed with "NS"; the world moves on.

**Comment by llorca** [comment]
Eh, I'd rather not throw things off just because there's cost. There's always cost associated, and we can come up with solutions (upgrade scripts for instance), so let's talk about it.

Your Apple comparison is quite misleading -- when you use an `NS` prefixed API (Apple stuff), you're most certainly developing for the Apple platform. Folks using our `pt-` prefixed classes are not developing for the Palantir platform, which is why it's awkward.

_An alternative to this task could be enabling custom namespaces. This task may also become irrelevant if we move to a CSS in JS approach._

**Comment by adidahiya** [comment]
Ok, fine, the Apple example wasn't perfect -- we also don't expose "pt" in the same kind of APIs that Apple exposes "NS"; our JS APIs don't have any namespace like that, and _users should be discouraged from styling any `.pt-` classes directly anyway_[0]. So it really wouldn't show up in their applications much at all, and we're not misleading them into thinking that they're developing for any Palantir platform.

Yep, there's a cost. Before we get to that, what are the benefits, besides vanity?

[0] they should attach custom classes wherever they need global customization, and they should use `.scss` variables if they need global customization.

**Comment by brsanthu** [comment]
> our JS APIs don't have any namespace like that, and users should be discouraged from styling any .pt- classes directly anyway[0]

React component doesn't support all available CSS options. For ex., pt-control-group. There is no react component for this. In these cases, users will have to propagate the `pt-` classes.

**Comment by adidahiya** [comment]
@brsanthu that's not what I meant by styling -- _styling_ a `.pt-` class means customizing it in CSS by applying overrides on top of Blueprint.

_Applying_ a `.pt-` class is different, and yes, you sometimes have to do that. In JS you can use the `Classes` namespace we export in all our packages, and that addresses most (probably all) of our users' use cases since we're a React-based library.

**Comment by warent** [comment]
FWIW I'll chime in with my experience: it does takes a little bit of extra brainpower to remember the prefix is `pt` versus `bp` which can interrupt dev flow. In the context of Blueprint, bp is intuitive, pt is awkward

**Comment by cmslewis** [comment]
Thanks, @warent, definitely appreciate that. (Too bad we didn't call this project Pluetrint.) This isn't scoped in the short or medium term according to our current roadmap though.

**Comment by llorca** [comment]
Plueprint ha! Yeah, this issue is unlikely to be addressed, but I could see getting https://github.com/palantir/blueprint/issues/284 ready for 2.0 later this year

**Comment by bradenhs** [comment]
Another plan could be to eschew traditional css altogether and use something like [typestyle](https://github.com/typestyle/typestyle) instead. Then just have folks import class names into their components.

```javascript
import { controlGroup } from '@blueprintjs/classNames'

function MyComponent() {
  return <div className={controlGroup}>
    ...
  </div>
}
```
