### ISSUE TITLE
Sketch file uses non-standard fonts and old version of SF fonts

### ISSUE THREAD

**Issue by romanr** [palantir/blueprint#2853]
Continuing from https://github.com/palantir/blueprint/pull/2813#issuecomment-414128744

The sketch file contains non-standard fonts. The warning appears when file is opened:

![image](https://user-images.githubusercontent.com/329079/44360560-81e66600-a4bb-11e8-93de-abfad9f33a68.png)

Initially Apple did not release SF fonts officially. People copied them from the SDK and used in designs.
Later Apple officially released these fonts and when they were released they had slightly different font names as we have them now.

So it seems to me that the case is the Blueprint sketch file was started with "old" version of those fonts.

Designer needs to install official Apple SF fonts, uninstall unofficial SF fonts. Then open file and use "Missing fonts" dialog to update.

**Comment by pkwi** [comment]
Fixed https://github.com/palantir/blueprint/pull/2857
