### ISSUE TITLE
@blueprintjs/icons package on npm is incoherent with current documentation

### ISSUE THREAD

**Issue by Grmiade** [palantir/blueprint#2860]
@blueprintjs/icons package has not been published since its last modification
https://github.com/palantir/blueprint/pull/2674

So the NOTIFICATION_UPDATED icon is in the current documentation but not present in the available package on npm :/

**Comment by giladgray** [comment]
@Grmiade oops good catch! `@blueprintjs/icons 3.1.0` has been published 👍
