### ISSUE TITLE
Can't translate the actionBar in the datePicker component (blueprint 2 and 3)

### ISSUE THREAD

**Issue by mdcorriveau** [palantir/blueprint#2861]
#### Environment

- __Package version(s)__: 2 and 3
- __Browser and OS versions__: Ubuntu 18.04 Chrome  68.0.3440.106 (Official Build) (64-bit)

#### Steps to reproduce

1. Activate the showActionBar option in a datepicker
2. Give the fr-CA locale as props to the datepicker

#### Actual behavior

The buttons are in english and we have no way to translate them.

#### Expected behavior

The buttons in french or we can override the text in the datePicker.tsx in function renderOptionsBar.

`private renderOptionsBar() {
        return (
            <div className={Classes.DATEPICKER_FOOTER}>
                <Button className={CoreClasses.MINIMAL} onClick={this.handleTodayClick} text="Today" />
                <Button className={CoreClasses.MINIMAL} onClick={this.handleClearClick} text="Clear" />
            </div>
        );
    }`

#### Possible solution

Either have a locale file in french that we take this from and we can override or maybe just add two functions to the localeUtils that we can provide to the component.

**Comment by giladgray** [comment]
@mdcorriveau how about `todayButtonText` and `clearButtonText` props?

**Comment by mdcorriveau** [comment]
@giladgray this would fix my problem !

**Comment by NachoJusticia** [comment]
Hi @giladgray , would it be a good idea to pass `todayButtonText` and `clearButtonText` props to `renderOptionsBar` function? 
https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/datePicker.tsx#L131
or just access `this.props.todayButtonText` and `this.props.clearButtonText` from the function?
