### ISSUE TITLE
Does using <Provider value={{blueprintPortalClassName: "myVal"}}> work

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2869]
Hey, I saw this note: 

![image](https://user-images.githubusercontent.com/2730609/44556536-0ec53580-a6ef-11e8-83d2-0920c1d8a38c.png)

but I wasn't sure from the docs whether or not that meant that using the new Provider api won't work. I think that's what it's saying but I think it could be more clear.

Thanks!

**Comment by giladgray** [comment]
related to #2787
