### ISSUE TITLE
[OverflowList] All items are collapsed outside of 100% zoom

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#2873]
#### Environment

- __Browser and OS versions__: macOS 10.13 + Chrome 68.0.3440.106

#### Steps to reproduce

1. Navigate to `OverflowList` example
1. Increase the containers size so you can see more than one breadcrumb
1. Change your browser's zoom level to a non-100% value

#### Actual behavior

All items collapse into the overflow

#### Expected behavior

The number of visible items doesn't change

**Comment by giladgray** [comment]
@invliD oops! probably need to account for DPR, some scaling factor.

**Comment by giladgray** [comment]
huh looks like the spacer gets squashed to just below 1px at some zoom levels.

![image](https://user-images.githubusercontent.com/464822/44824533-f8215180-abba-11e8-833a-ed653d75a30c.png)

easy enough to adjust the threshold to `< 0.98` instead of the strict `< 1` check we're doing now.

**Comment by themadcreator** [comment]
consider a less strict threshold
