### ISSUE TITLE
Stop using my tools, racists

### ISSUE THREAD

**Issue by jamiebuilds** [palantir/blueprint#2876]
Apologies to any contributors who aren't employees of Palantir. But to those that are:

Please find jobs elsewhere and stop helping Palantir [do horrible things](
https://theintercept.com/2017/03/02/palantir-provides-the-engine-for-donald-trumps-deportation-machine).

Also, stop using my tools (such as Lerna), I don't support you, and I don't want my work to benefit your awful company.

**Comment by jamiebuilds** [comment]
https://news.vice.com/en_us/article/paw9ky/toddler-died-after-getting-sick-in-ice-custody

**Comment by jamiebuilds** [comment]
https://twitter.com/ACLU/status/1033084026893070338

**Comment by palantirtech** [comment]
See https://github.com/palantir/blueprint/issues/2870 .

**Comment by jamiebuilds** [comment]
See:

> Partnering with ICE at this time is in itself a violently racist and xenophobic act. Cancel your contracts or I will continue my campaign of throwing legal wrenches at you through open source.
> 
> I have an entire team of people developing software around the creation of design systems like Blueprint. I have helped start dozens of open source projects which make up a significant portion of the JavaScript/Frontend ecosystem. Palantir will explicitly, by name, be refused open source licensed access to these tools.
> 
> The open source community is better without companies like yours. You are not welcome.

**Comment by a0viedo** [comment]
> There's nothing racist or xenophobic about law enforcement.
The law by no means is an example of what is racist and what is not. Slavery and racial segregation were legal.

**Comment by nafg** [comment]
That is true. I meant this particular law enforcement.
