### ISSUE TITLE
Popover without a fixed target element

### ISSUE THREAD

**Issue by jordymeow** [palantir/blueprint#2879]
I am creating a dynamic map. When the markers are being hovered, I would like a popup to appears and display information next to them.

The popup should only be one instance, as there could be thousands of markers on the map.

I feel like it's a simple case but I can't find a way to do this nicely with Blueprint. I have looked at the Popover (and the Tooltip) and the Overlay, but I am not sure it would be the way to go. They always need to seem a target right inside it.

Is there something obvious I missed? Or maybe I should simply do it manually?

**Comment by giladgray** [comment]
@jordymeow this kind of usage is not supported out of the box--it's not idiomatic React. you can build your own wrapper component that reuses the same `<Popover>` instance.
