### ISSUE TITLE
CollapseList throws Uncaught Error: addComponentAsRefTo when clicking the dropdown ellipse

### ISSUE THREAD

**Issue by Yaojian** [palantir/blueprint#288]
When clicking the ellipse on the start of breadcrumbs, the dropdown popover shows up with the following error message in console:

react-dom.js:17870 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)

The code is here:

```ts
import * as React from "react";
import {Classes, CollapseFrom, CollapsibleList, IMenuItemProps, MenuItem} from "@blueprintjs/core";

export interface IViewProps {

}

export interface IViewState {
}

export class NavigationBar extends React.Component<IViewProps, IViewState> {
    constructor(props: IViewProps) {
        super(props);
        this.state = {};
    }

    render() {
        let target = <span className={Classes.BREADCRUMBS_COLLAPSED}/>;
        return (
            <CollapsibleList
                collapseFrom={CollapseFrom.START}
                visibleItemCount={3}
                className={Classes.BREADCRUMBS}
                dropdownTarget={target}
                renderVisibleItem={this.renderItem}
            >
                <MenuItem iconName="folder-close" text="All Files" href="#"/>
                <MenuItem iconName="folder-close" text="Users" href="#"/>
                <MenuItem iconName="folder-close" text="Jane Person" href="#"/>
                <MenuItem iconName="folder-close" text="My Documents" href="#"/>
                <MenuItem iconName="folder-close" text="Classy Dayjob" href="#"/>
                <MenuItem iconName="document" text="How to crush it"/>
            </CollapsibleList>
        );
    }

    private renderItem(p: IMenuItemProps) {
        return <span>{p.text}</span>
    };
}
```

**Comment by giladgray** [comment]
I cannot repro this on the documentation site using the exact code you provided.

@Yaojian is it possible that you have multiple copies of React loaded? say, one from your app and one from Blueprint?

**Comment by Yaojian** [comment]
It's my fault.  I marked react as externals incorrectly.

Thanks for your help.

**Comment by codebling** [comment]
I can confirm that this problem is caused by multiple copies of React. 

BEWARE! React is a peer dependency of @blueprintjs/core, and there is a [Browserify bug](https://github.com/substack/node-browserify/issues/1663) which prevents exclude/ignore/external-ing peer deps and may lead to multiple copies of React in your bundles.
