### ISSUE TITLE
customize Popover arrow position

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2882]
#### Feature request

allow the popover arrow to not always point at the middle of the target. 
this gets particularly weird if the target is > 2x the size of the popover.

<img width="393" alt="screen shot 2018-08-29 at 4 28 27 pm" src="https://user-images.githubusercontent.com/464822/44821120-b5567e00-aba8-11e8-82f1-e178df4840aa.png">

#### Proposal

`Popover arrowPosition` prop supports four values:
- `target` (default, current) - arrow points at center of target
    ![image](https://user-images.githubusercontent.com/464822/44821335-e3888d80-aba9-11e8-8e09-d980c3ba18e7.png)

- `content` - arrow originates at center of content
    ![image](https://user-images.githubusercontent.com/464822/44821313-c489fb80-aba9-11e8-945f-5ab5358f0802.png)

- `start` - arrow originates at "start" edge of content (a la `flex-start`)
    ![image](https://user-images.githubusercontent.com/464822/44821262-9a383e00-aba9-11e8-8077-ff13076d20f2.png)
- `end` - arrow originates at "end" edge of content (a la `flex-end`)
    ![image](https://user-images.githubusercontent.com/464822/44821287-afad6800-aba9-11e8-8a39-cca220141f45.png)

Perhaps a fifth `auto` value can be provided like `position` that chooses the optimal one above, but heuristics are unclear at this point.

**Comment by themadcreator** [comment]
For the `target` option, what if the target center is outside the bounds of the popover?

**Comment by giladgray** [comment]
the result of that case is the top screenshot, where the arrow is too close to the edge of the content. popper is pretty smart about this.

**Comment by mitchbeard** [comment]
I hit this too!  It's especially weird if the popover content starts with a scrollbar then loses it (i.e. you're displaying a list with a filter bar and you filter down the elements to where there is no longer overflow) because then the triangle is outside the now narrower bound of the popover content.  Yuck!

**Comment by adidahiya** [comment]
I think this is pretty much fixed with Popover2 and popper.js v2 configuration options.
