### ISSUE TITLE
[TagInput] Ability to detect input field value within custom onKeyDown/Up/Press handler 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#2897]
#### Environment

- __Package version(s)__: Core 3.4.0

#### Feature request

Use case:
- I want <kbd>Enter</kbd> to add a tag if there is text in the input field (the default behavior).
- I want <kbd>Enter</kbd> to submit a surrounding form if there is _no_ text in the input field (custom behavior).

Unfortunately, the input is cleared before custom `onKeyDown`/`onKeyUp`/`onKeyPress` callbacks are invoked, so I can't achieve the above behavior.

#### Examples

N/A

**Comment by giladgray** [comment]
@cmslewis we could add a preventDefault or stopPropagation if the default <kbd>Enter</kbd> behavior is triggered? we already do this for the arrow keys.

https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tag-input/tagInput.tsx#L377

**Comment by cmslewis** [comment]
@giladgray Oh interesting. What would the usage look like in that case? The event wouldn't propagate to a parent, say, but a custom `onKeyDown` callback that I provided to`<TagInput>` would still be explicitly invoked:

https://github.com/palantir/blueprint/blob/27e9aff0ef4aaf437e1dee34e14bdc12f70c6422/packages/core/src/components/tag-input/tagInput.tsx#L386

Sounds like I'd just need to wrap the `<TagInput>` with another `<div>` and add the `onKeyDown` prop to that container element?

```tsx
<div onKeyDown={this.submit()}>
    <TagInput {...} />
</div>
```

(For context: I'm implementing a custom form-control component of sorts, so not a literal `<form>` that listens for <kbd>Enter</kbd> to submit.)
