### ISSUE TITLE
DateInput popover does not close on tab blur

### ISSUE THREAD

**Issue by chiubaka** [palantir/blueprint#2901]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.3.0; @blueprintjs/datetime 3.1.0
- __Browser and OS versions__: Firefox 61.02 (64-bit); macOS High Sierra 10.13.6

#### Steps to reproduce

1. Create a tabbable form including a `DateInput`.
2. Attempt to tab through the form.

#### Actual behavior

When hitting tab to move from a `DateInput` to the next input, the `DateInput`'s calendar popover does not dismiss. Interestingly, if `shift-tab`ing backwards, `DateInput` _does_ dismiss the popover.

#### Expected behavior

As we are no longer focused on the `DateInput`, it seems like the `DateInput`'s calendar popover should dismiss.

#### Possible solution

Close the popover when tab is pressed in a `DateInput`.

**Comment by svilendobrev** [comment]
as a workaround: pass inputProps: {
 onKeyDown: function( e) {
   if (e.which === Keys.TAB && !e.shiftKey)
      this.refs.yourref.setState({ isOpen: false  })
 }}

inputProps:onBlur does not work correctly with opened daypicker, it seems to fire before value is ever set.
