### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by pankuleczka** [palantir/blueprint#2902]
https://blueprintjs.com/docs/#datetime/datetimepicker
this says `This component is deprecated since 3.4.0`; the core package is 3.5.0 BUT the datetime package is only 3.1.0 - I've wasted quite some time wondering why is my DatePicker not showing TimePicker. If that package is not even 3.4.0, then why is that information even there? Not cool.

**Comment by giladgray** [comment]
@pankuleczka oops! that's a double typo - wrong package _and_ we haven't shipped the `datetime` changes yet so it's not fully deprecated. waiting on #2895 to round out the feature.
