### ISSUE TITLE
Render radio as buttons

### ISSUE THREAD

**Issue by pke** [palantir/blueprint#2906]
Recently I had to render a bunch of radios in a row and really wished they would look like buttons. Maybe we could introduce a `<RadioButton` subclass that behaves as a HTML radio but renders as a button?

**Comment by giladgray** [comment]
nope. just use `<Button>` directly.

**Comment by pke** [comment]
Uhhm semantics are totally different. How is that going to work?

**Comment by giladgray** [comment]
this is why the `<Button active>` prop exists. i suppose it's not exactly the same as a checkbox, but it works damn well.

https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/common/alignmentSelect.tsx#L27

**Comment by giladgray** [comment]
we call it a "segmented control" https://www.google.com/search?q=segmented+control

**Comment by pke** [comment]
It still does not do the same as a form radio input. the markup is incompressible for screen readers.

**Comment by giladgray** [comment]
I'll bet you could make it support screen readers with the appropriate aria tags. Buttons will render extra props to HTML
