### ISSUE TITLE
table (react) eats all click events

### ISSUE THREAD

**Issue by toddself** [palantir/blueprint#291]
### Bug report

- __Package version(s)__:  1.1.0
- __Browser and OS versions__: MacOS 10.11.6 & Ubuntu 16.10 both with Chrome 54.0.2840.98. Mac 10.11.6 with Safari 10.0.1

#### Steps to reproduce

1. Create a table
1. Attach an onClick or onMouseDown/Up handler to an element rendered in that table
1. Click on that element and the handler will never fire
1. You can best demonstrate this by going to the demo (http://blueprintjs.com/docs/#components.table-js.example-editable) and trying to use your mouse to move the cursor to the beginning of the field after you activate it for editing.

![cannot-click](https://cloud.githubusercontent.com/assets/193412/20816082/76687aea-b7d5-11e6-8aab-a1490fa72adf.gif)

(All that mouse hovering is me trying to click to move the cursor around)

#### Actual behavior

Mouse click events are not propagated to children cells (even if you set the `SelectionModes` to `NONE`.)

#### Expected behavior

Children elements of the table to be able to receive and respond to click events.

**Comment by themadcreator** [comment]
Yep, there are a few event.stopPropagation() calls in dragEvents.ts. We did this to take over control of selection of cells and to prevent native text selection, which looks weird then we have our own cell selection overlays.

Furthermore, the `<EditableText>` component we use in editable cells will grab focus on a single click, but we only want to edit on double click.

We obviously need to address the issue the reporter is seeing, but some thought is required.

**Comment by adidahiya** [comment]
@toddself out of curiosity, what do you intend to use the mouse event handlers for?

**Comment by toddself** [comment]
We are building a spreadsheet type app. We need to display and react to buttons, checkboxes and the ability to place the cursor anywhere in a text field when its editable. 

I mean even if we didn't need the other things, our limited testing shows people are very angry/confused that that can't use their mouse to position the cursor. Removing expected interface paradigms is really difficult for people :)

**Comment by llorca** [comment]
Wow, I wasn't aware of this issue. I just played with it, there's no text/mouse interactions on a (non-header) cell that's being edited -- can't click to move the cursor, can't click+drag to select portions of text... yet, selection by clicking is still possible. Hopefully we can figure out a fix soon

**Comment by brandonchoe** [comment]
When will this be fixed? And about when will 1.3.0 be out?

**Comment by llorca** [comment]
@brandonchoe we were planning on fixing it this week, but the assignee needed to take care of a bunch of personal matters. 1.3.0 is coming today without this fix, and I'm hopeful 1.4.0 will address this issue
