### ISSUE TITLE
DateRangePicker not rendering TimePicker

### ISSUE THREAD

**Issue by jonlinnell** [palantir/blueprint#2919]
#### Environment

- __Package version(s)__:
    "@blueprintjs/core": "^3.3.0",
    "@blueprintjs/datetime": "^3.1.0",
- __Browser and OS versions__:
  macOS 10.12.6
  Chrome 69

#### Steps to reproduce

```js
...
import { DateRangePicker, TimePrecision } from '@blueprintjs/datetime'
...
<DateRangePicker
    timePrecision={TimePrecision.MINUTE}
    shortcuts={false}
    ...
/>
```

#### Actual behavior

Passing timePrecision prop to DateRange Picker isn't causing the component to render the TimePicker. (I even copy-pasted the identifier from the conditional in maybeRenderTimePickers() in DateRangePicker.tsx to check I wasn't misspelling it.

#### Expected behavior

Passing the timePrecision prop should render the TimePicker component.

#### Possible solution

I honestly don't know – it looks like it should work, but something seems to be stopping maybeRenderTimePickers() from rendering TimePickers.

**Comment by giladgray** [comment]
@jonlinnell this has not shipped yet.
