### ISSUE TITLE
WebpackBuildScripts - allow configurable port for webpack dev server

### ISSUE THREAD

**Issue by james2doyle** [palantir/blueprint#2921]
#### Environment

- __Package version(s)__: 3.5.1
- __Browser and OS versions__: Chrome 69.0.3497.81 OSX 10.13.6

#### Feature request

Currently, [the port for the webpack dev server is hardcoded to the file](https://github.com/palantir/blueprint/blob/develop/packages/webpack-build-scripts/webpack.config.base.js#L108). On my system, port `9000` was occupied and since the port wasn't configurable, I wasn't able to change it on the dev server.

#### Examples

All I really want to do is enable the port to be configured via `process.env` and then fallback to `9000` if its not defined. I can create a PR for this.

Thoughts?

**Comment by giladgray** [comment]
@james2doyle sure, i'd happily review a PR for this. please do it in a non-breaking way.
