### ISSUE TITLE
Add resizing options to Core Kit Sketch

### ISSUE THREAD

**Issue by thelastnode** [palantir/blueprint#2926]
#### Environment

- __Package version(s)__: 3.5.1
- __Browser and OS versions__: N/A

#### Feature request

Having the Sketch file in the repo is super helpful for developing against Blueprint!

It would be very helpful to have the `Core Kit.sketch` file have the correct resize options set, i.e., fix height/width, pin to left/right. This would make it much easier to prototype using components in the Sketch file.

#### Examples

The navigation bar currently stretches the icons and positions when resized horizontally. With appropriate resize options (pin to left/pin to right), prototyping would be simplified.

<img width="528" alt="resize_options" src="https://user-images.githubusercontent.com/250437/45394540-03767300-b5e6-11e8-912d-cf64ff7f1286.png">

**Comment by pkwi** [comment]
Yeah, will be adding it as part of the [Symbols work](https://github.com/palantir/blueprint/issues/2817). The original Blueprint sketch file was created before Resizing was added to Sketch. We have never had time to update it :(

**Comment by rachaelguay** [comment]
@pkwi do you know when this might be available? Thank you so much for your contributions.

**Comment by pkwi** [comment]
@rachaelguay Unfortunately, atm we can't allocate much time for this. So, any help would be greatly appreciated.

**Comment by vkorobov-boostlabs** [comment]
Hey guys, would you be open if I create resizing for all sketch elements? 
I will not touch symbols just tune Sketch's "Pin to Edge" properties. 
Can complete it within the March 2019

**Comment by pkwi** [comment]
@vkorobov-boostlabs that would be great! Probably worth incorporating it into [this effort](https://github.com/palantir/blueprint/issues/2817#issuecomment-472205251)

**Comment by terpimost** [comment]
mainly done in https://github.com/palantir/blueprint/pull/4007
I suggest having new issues about bugs
