### ISSUE TITLE
Refactor: rename all "renderX" props to "XRenderer"

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#293]
To be more semantically correct and consistent with other React libraries.

For example, `renderCell` &rarr; `cellRenderer`.

- [x] most table props
- [x] HeaderCell `renderGhostCell` and `renderHeaderCell`
- [x] Slider `renderLabel`
- [x] CollapsibleList `renderVisibleItem`

**Comment by cmslewis** [comment]
- I vastly prefer having a verb in all function names.
- The `render...` prefix helps me visually clump all render helper functions together, at a glance.

But if `...Renderer` is the emerging community convention, I'll capitulate.

**Comment by llorca** [comment]
No strong opinion on one or the other, but +1 for respecting conventions and best practices

**Comment by adidahiya** [comment]
@cmslewis it's not a function name, it's a prop name. Note how we currently distinguish `onEvent` vs. `handleEvent`.

**Comment by cmslewis** [comment]
Ahh gotcha. Totally down with that then.
