### ISSUE TITLE
Components wrapped in <Popover> do not respect width: 100%

### ISSUE THREAD

**Issue by mitchbeard** [palantir/blueprint#2931]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^3.2.0"
- __Browser and OS versions__: Chrome or JXBrowser

#### Steps to reproduce

1. Create a container div with width 100% and a child div with width: 100%
1. See the child fill the container properly
1. Wrap the child in a `<Popover>` (as the click target, not the popover content)
1. See the child no longer fill the horizontal space.

#### Actual behavior

See above

#### Expected behavior

The child continues to fill the parent width even when wrapped in a <Popover> as the target

#### Possible solution

Fix the popover spans to prevent this.  In my code I'm using 

```
    span.bp3-popover-wrapper, span.bp3-popover-target {
        width: 100%;
    }
```

in a bunch of places to fix :(

**Comment by badams** [comment]
@mitchbeard I think switching to div instead of span for your target element will fix this, try `targetTagName="div"` on the popover

**Comment by gjavitt** [comment]
i just ran into this issue as well - perhaps worth noting in the docs?
