### ISSUE TITLE
Table not rendering correctly in Tab

### ISSUE THREAD

**Issue by jkornblum** [palantir/blueprint#2932]
#### Environment

- __Package version(s)__: 
```
"@blueprintjs/core": "^3.2.0",
"@blueprintjs/datetime": "^3.1.0",
"@blueprintjs/icons": "^3.0.0",
"@blueprintjs/select": "^3.1.0",
"@blueprintjs/table": "^3.1.1",
```
- __Browser and OS versions__: Linux Ubuntu 18.04, FireFox 61.0.1

#### Steps to reproduce
My project has more than core + table so I'm including all css loaded for clarity.
```
import "../node_modules/normalize.css/normalize.css";

import "../node_modules/@blueprintjs/core/lib/css/blueprint.css";
import "../node_modules/@blueprintjs/datetime/lib/css/blueprint-datetime.css";
import "../node_modules/@blueprintjs/icons/lib/css/blueprint-icons.css";
import "../node_modules/@blueprintjs/select/lib/css/blueprint-select.css";
import "../node_modules/@blueprintjs/table/lib/css/table.css";

const cellRenderer = (rowIndex: number) => {
      return <Cell>{`$${(rowIndex * 10).toFixed(2)}`}</Cell>
};

public tablePanel() {
    return (
      <div style={{height: '500px'}}>
        <Table numRows={10}>
            <Column name="Dollars" cellRenderer={cellRenderer}/>
        </Table>
      </div>
    )
  }

<div>
          <Tabs>
            <Tab id="limits" title="Step 3 - Set Limits" panel={this.tablePanel()} />
          </Tabs>
          <Table numRows={10}>
              <Column name="Dollars" cellRenderer={cellRenderer}/>
          </Table>
</div>
```

#### Actual behavior

The table in the tab renders four rows incorrectly.
The table outside the tab renders correctly.

![blueprintjs-table](https://user-images.githubusercontent.com/5368903/45452600-13548c80-b6a4-11e8-95f8-659d348998af.png)

#### Expected behavior

Tables in tab and outside of tab render the same.

#### Possible solution

Not explored yet, looking for some comments.

**Comment by giladgray** [comment]
@jkornblum try a `forceUpdate` after rendering in the tab or enable `renderActiveTabPanelOnly` to re-mount it when it becomes visible.

**Comment by jkornblum** [comment]
Okay, `renderActiveTabPanelOnly` resolves this issue. I haven't tried `forceUpdate` route.
Thanks!

**Comment by giladgray** [comment]
well dope, sounds like we did it 👍

**Comment by asyncjason** [comment]
Is there a solution to this if remounting is not the best option?

**Comment by adidahiya** [comment]
@jseparovic have you tried Table2? If this is still a bug, please open a new issue, thanks.
