### ISSUE TITLE
Pass custom input element to DateInput

### ISSUE THREAD

**Issue by tobilen** [palantir/blueprint#2933]
#### Feature request

The DateInput component ships with its own input field, which can't really be accessed from the outside. We have an input element in our own pattern library, which we want to use in combination with the DatePicker. We accomplished this by basically duplicating the `DateInput` component with a render prop function passed to `children`. It would be really cool if the `DateInput` component shipped with the functionality to pass your own input. 

#### Examples

The interface could look like this:
```jsx
<DateInput>
{ ({inputProps}) => <MyInput {...inputProps} /> }
</DateInput>
```

**Comment by giladgray** [comment]
@tobilen sure this is a cool feature and I'd be happy to review a PR. just be sure not to break existing usage.

**Comment by tobilen** [comment]
i'll try to code something after my other issue has been solved +1

**Comment by tobilen** [comment]
i think i'll take a look at this next week
