### ISSUE TITLE
Datepicker uses local timezone

### ISSUE THREAD

**Issue by tobilen** [palantir/blueprint#2934]
#### Environment

- __Package version(s)__: 3.2.0
- __Browser and OS versions__: MacOS 10.13.6 , Chrome 69.0.3497.9

#### Why is this a problem
When doing snapshot testing with the Datepicker component, the snapshots will be different depending on the local timezone of the machine running the tests. This is especially problematic if a CI server is set to a different timezone than the person creating or updating the snapshots.

#### Steps to reproduce

1. Pass date object to Datepicker (`defaultValue`, `maxDate`, or `minDate`)
2. Serialize the date and store it in a file.
3. Do the same thing with a different local timezone.

A good way to do this is to check out the branch i opened ( https://github.com/palantir/blueprint/pull/2935 ) and run `UPDATE=1 yarn test`. This will update the DatePicker snapshot with your local timezone applied to the dates.

I originally recorded the snapshots with UTC+2 and modified them with `TZ=UTC UPDATE=1 yarn test`, which led to this commit: https://github.com/palantir/blueprint/pull/2935/commits/130784301b615a00a364e9038c577bd4d442b85e

#### Actual behavior

The files will have different timestamps.

#### Expected behavior

Timezone will be part of the passed date. Local timezone will not be applied.

#### Possible solution

The Datepicker should keep from applying timezone offset on the dates it receives.

**Comment by tobilen** [comment]
after investing some time in it, it is looking like a problem with the way date objects get serialized in javascript. this opens up the solution space to maybe stubbing the date object, so we can monkeypatch our own serialization method.

**Comment by giladgray** [comment]
yes this is definitely just a javascript thing and there's not a whole lot to be done about it. one option would be to always report times in UTC, but that's got its own challenges.

**Comment by tobilen** [comment]
yeah, i'd really like to avoid changing interfaces. ideally, this can be solved with some kind of date mock. i probably won't get to it until the end of the week though

**Comment by tobilen** [comment]
i am now solving this with a combination of two things:
* creation of a date serializer, so dates in components get stripped of timezones: https://www.npmjs.com/package/jest-date-serializer
* PR on `react-day-picker` to strip timezone from dates before timestamping and using them as `key` props: https://github.com/gpbl/react-day-picker/pull/810

**Comment by jayarjo** [comment]
Why is this closed? Has it been solved?
