### ISSUE TITLE
"small" option for inputs / InputGroup

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2947]
![image](https://user-images.githubusercontent.com/2730609/45593898-39e52280-b945-11e8-8e06-a9da3df80ffe.png)

Hey @giladgray, as seen in the above image, the `small=true` buttons fit nicely within the div, but the InputGroup element does not. Ideally we could have a "small" InputGroups as well. 

Any reason not to have this? Seems useful in this exact case. Also strange that there is a large option but not a small. 

Thanks!

**Comment by tnrich** [comment]
I think you won't have an InputGroup within an InputGroup ever so maybe it just ends right there?

**Comment by tnrich** [comment]
I don't see the issue with the buttons getting smaller inside a small InputGroup..? Can you explain more as to why that would be an issue @giladgray ?

**Comment by giladgray** [comment]
input group styles children buttons to be smaller ([source](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/_input-group.scss#L74-L81)) so we'd need to add another set of styles to style buttons in a small input group even smaller. small buttons are already as small as they can be given text/icon size so this quickly becomes unmaintainable.

**Comment by giladgray** [comment]
okay @tnrich here's my final take on this feature: i'm not gonna build it cuz it's not needed at palantir. but if you want to take it on and work with me to drive the PR to perfection then that'd be dope 👍
