### ISSUE TITLE
Make inputRef support React.RefObject in type definition

### ISSUE THREAD

**Issue by lukyth** [palantir/blueprint#2949]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.6.1
- __Browser and OS versions__: Google Chrome 69.0.3497.81, macOs Mojave 10.14

#### Feature request

Right now every `inputRef` will receive `(ref: T | null) => any`, where `T` is its corresponding element type. Could we consider supporting `React.RefObject<T>` (a result of `React.createRef<T>()`) as well? `React.createRef` is one of the official way to create a ref ([source](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs)). The new type would be:
```ts
inputRef?: ((ref: HTMLInputElement | null) => any) | React.RefObject<HTMLInputElement>
```
I can make a PR for this if you think this is valid.

#### Examples

```ts
// Type def
export interface IInputGroupProps extends IControlledProps, IIntentProps, IProps {
  // Other props

  /** Ref handler that receives HTML `<input>` element backing this component. */
  inputRef?: ((ref: HTMLInputElement | null) => any) | React.RefObject<HTMLInputElement>

  // Other props
}

// Usage
export default class ExampleComponent extends React.Component {
  private textInputRef = React.createRef<HTMLInputElement>()
  public render() {
    return <InputGroup inputRef={this.textInputRef} />
  }
}
```

**Comment by giladgray** [comment]
this requires upgrading react types to have access to `RefObject`. i'm working on it... #2951

**Comment by lukyth** [comment]
Sorry I didn't look at every component thoroughly. I thought this's possible because I only tried it with `InputGroup`. Perhaps we should close this issue since we can't support `RefObject` in all cases?

**Comment by giladgray** [comment]
yes i'd be okay with closing this and not supporting `RefObject` anywhere. reading through the React docs, `RefObject` seems specific to the `ref` prop and cannot be used on your own custom ref props like `inputRef`, because there's no publicly available way to set the ref.
