### ISSUE TITLE
Uneditable EditableCell with falsy value

### ISSUE THREAD

**Issue by brandonchoe** [palantir/blueprint#295]
### Bug report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit) and OS X El Capitan 10.11.6

#### Steps to reproduce

1. Double-click an `EditableCell` with a falsy `value`.

#### Actual behavior

Uneditable cell.

#### Expected behavior

Editable cell.

**Comment by themadcreator** [comment]
@brandonchoe I'm not sure we support editing of such raw values -- only strings. Could you try stringifying the value with something like `"" + value`?

**Comment by brandonchoe** [comment]
If `value` is `null` or `undefined`, I pass `''` (empty string) instead. The cell is empty, which is what I want, but the cell is also uneditable.

**Comment by brandonchoe** [comment]
I just tried on the docs page, and it worked. I'm not sure what's going on.
<img width="742" alt="screen shot 2016-12-02 at 4 05 00 pm" src="https://cloud.githubusercontent.com/assets/14318012/20850421/184ac998-b8a9-11e6-8d04-bed102876c01.png">

**Comment by brandonchoe** [comment]
My bad, this isn't a bug. I wasn't including `blueprint.css` because it messes everything up, but EditableCell works if I extract just the `.pt-editable-content` stuff. Thanks.

**Comment by adidahiya** [comment]
> I wasn't including blueprint.css because it messes everything up

curious, anything we can do to make this easier to use?

**Comment by brandonchoe** [comment]
I didn't look into it, but `blueprint.css` changed the font styles of practically everything in my project - it may have just been the font weight. It would be nice if the `Table` component was entirely standalone, but I can understand why things like `pt-editable-content` are in the core CSS file.

**Comment by adidahiya** [comment]
@brandonchoe keep an eye out for #244; we plan to remove more global styles from blueprint.css.
