### ISSUE TITLE
Spinner component gets stucked

### ISSUE THREAD

**Issue by NachoJusticia** [palantir/blueprint#2950]
#### Environment

- __Package version(s)__: 3.0.0-beta.1
- __Browser and OS versions__: Google Chrome 69.0.3497.92, macOS High Sierra 10.13.3

#### Steps to reproduce

- Use Blueprint Spinner component when js main thread needs to do some calculations.

#### Actual behavior

The Spinner gets stucked.

#### Expected behavior

The Spinner should spin.

#### Possible solution

Any idea with that? I would like to submit a PR but I don't know how to approach this issue I'm having...

**Comment by giladgray** [comment]
@NachoJusticia before you do anything, upgrade to 3.6.0. Spinner has changed, this is probably fixed.

**Comment by NachoJusticia** [comment]
I'm sorry @giladgray , I am using `v3.0.0-beta.1 `of blueprintjs, so I am using `blueprintjs/core 3.6.0` version

**Comment by giladgray** [comment]
i don't follow. what do mean "of blueprintjs?"  if you're using core 3.6.0 then you're using 3.6.0.

but also, if the JS thread itself is blocked on computation then there's simply nothing to be done on the blueprint side. can you post a video or a link to a sandbox with a reliable repro?

**Comment by NachoJusticia** [comment]
@giladgray I will try to create two little projects and try to block main javascript thread, so we can make a comparison between blueprint spinner and a spinner that does not use svg + translation but just css.

**Comment by giladgray** [comment]
It most certainly is but there's a link to a CodeSandbox in both the README and the docs homepage.

**Comment by NachoJusticia** [comment]
I have prepared the following [sandbox project](https://codesandbox.io/s/km7469147) in which I compare Blueprint's Spinner and a [Semantic-ui based Spinner](https://github.com/Semantic-Org/UI-Loader/blob/master/loader.css). You can play with the number of the `foor loop` iterations in order to block the js thread.

I post here a gif to show the result:
![spinnercomparison](https://user-images.githubusercontent.com/24293766/45801665-d0527480-bcb4-11e8-9b86-f5344b611aee.gif)

**Comment by giladgray** [comment]
I cannot reproduce the result. I see an entirely blank page while the promises run then a quick flash of spinners then the "resolved" message.

**Comment by giladgray** [comment]
Actually! Your sandbox was using a core 3.0.0-beta, but i have recently reworked spinners so they have DOM wrapper elements (#2868) and now the spinner spins happily alongside the other one.

Please upgrade to the latest version. I already suggested this above.

https://codesandbox.io/s/1rk2w99p4j

**Comment by NachoJusticia** [comment]
I had to make changes in the code (for instance update the number of iterations of the for loop) and click save in order to see the spinners instead of the blank page. I the blank page is showed because codesandbox is blocked too... 

I am already using the new version of the Spinner in my project and when the js thread is blocked the Blueprint Spinner does not spin but Semantic-ui based does spin.

I think that in your codesandbox both spiners are not working until the "All promises resolved!" message is shown (so the JS thread is unblocked), don't you think so?

**Comment by giladgray** [comment]
I'm sorry mate but all signs point to you using an older version of core. Please ensure that you are using the actual latest version. In my sandbox above, I was able to get a consistently spinning spinner exactly identical to semantic-ui because the latest versions uses CSS animations on a DOM element.

**Comment by giladgray** [comment]
the most we can hope for is a consistent experience between the two libraries. if nothing renders cuz the JS thread is blocked, that's on the browser not on the library.

**Comment by NachoJusticia** [comment]
Ok! No worries and thanks for your patience 👍

**Comment by giladgray** [comment]
for sure! this was a fun one to track down.
