### ISSUE TITLE
Proper way to handle Error in DateInput component

### ISSUE THREAD

**Issue by alexandradeas** [palantir/blueprint#2965]
#### Environment

- __Package version(s)__: 3.6.1
- __Browser and OS versions__: Mac High Sierra, Firefox 62

#### Question

It appears that based on my current implementation of `DateInput` that one of the ancestor components should implement the `componentDidCatch` lifecycle method in order to prevent an app wide error.

The Error I'm dealing with is a Date being outside the bounds of the date range. The error is thrown from `DatePicker.validateProps` on and is thrown on validation of either `value` or `defaultValue`.

**Comment by giladgray** [comment]
@alex-deas yes an error boundary is a good thing to add here. another thing you can do is be more deliberate with your dates to ensure they never exceed the min/max.

I noticed how obnoxious this error is recently but I don't have a specific plan to resolve it. definitely open to suggestions if you've got any.

**Comment by alex-deas** [comment]
I'm generally averse to throwing exceptions and hoping they'll be caught; but I understand that not everyone has the same issues with it. This one did come up from me not quite reading the documentation carefully enough, although I don't think it's documented that an error could throw an exception in this case.

Drawing on the example of how HTML handles issues in the markup, it's designed to provide the most usable version and you wouldn't expect an issue in one element to cause the page not to render.

As it's a library dependency I think it would be worth it to wrap the component in a component which will handle the exception by displaying some placeholder text in place of the DateInput component and possibly log the error.

**Comment by adidahiya** [comment]
Closing in favor of https://github.com/palantir/blueprint/issues/4251
