### ISSUE TITLE
How blueprint know language which app using to compile to JS/TS ?

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#2974]
```
@blueprintjs/core": "^3.3.0
```
When I used that version 3.3.0 I saw this package only contains files which extension ts. 
I'm wondering how this package apply to js?
Now I using new version 3.6.1 and it contains both ts and js.
Why don't you write script that compile to JS lib if app using JS or don't compile if app is TS

**Comment by giladgray** [comment]
@tomzaku Blueprint provides compiled files in several common formats: commonjs, ES modules, and a webpack bundle. see the [package.json main entries](https://github.com/palantir/blueprint/blob/develop/packages/core/package.json#L5-L9) for the full list.

these files are not tracked in git and can only be seen by building locally or installing from NPM. but I assure you the .js files have always been there -- look in `lib/cjs` or `lib/esm`.
