### ISSUE TITLE
Popover not closing

### ISSUE THREAD

**Issue by hari5004** [palantir/blueprint#2978]
#### Environment

- __Package version(s)__: 3.4.0
- __Browser and OS versions__:NA

#### Question

My requirement is to close the popover when a react-router Link component is clicked and i have added bp3-popover-dismiss class mentioned in the documentation of popover but it doesnot provide the required result
```
   <Popover  content={CustomerDropDown} position={Position.BOTTOM}>
            <Button text="Customer" rightIcon="caret-down" />
     </Popover>

const CustomerDropDown = (
    <Menu>
        <Link className="bp3-menu-item bp3-popover-dismiss" to="/nest/customer">Customer</Link>
        <Link className="bp3-menu-item bp3-popover-dismiss" to="/nest/companies">Companies</Link>
        <Link className="bp3-menu-item bp3-popover-dismiss" to="/nest/billing">Billing</Link>
        <Link className="bp3-menu-item bp3-popover-dismiss" to="/nest/tickets">Tickets</Link>
    </Menu>
)
```

**Comment by giladgray** [comment]
also @hari5004 prefer using `Classes` constants rather than hardcoding strings. much more reliable.
https://blueprintjs.com/docs/#core/classes

**Comment by Penagwin** [comment]
We're also running into this issue. I believe it has something to do with this line: https://github.com/palantir/blueprint/blob/9728e61b420eda381cedce06166a4caf6b958bc4/packages/core/src/components/popover/popover.tsx#L462
