### ISSUE TITLE
Missing micro-interactions in table

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#298]
- [ ] Keyboard shortcuts (using `<Hotkey>`)
  - [x] Copy `cmd+c`
  - [ ] ~~Paste `cmd+v`~~ (can't do because table is data agnostic, we don't know what data you're putting in there)
  - [x] Move selection `up`/`right`/`bottom`/`left`
  - [ ] Select the cell immediately to the right `tab`
  - [ ] Select the cell immediately below `return`
  - [ ] Select the cell immediately to the left `shift+tab`
  - [ ] Select the cell immediately above `shift+return`
  - [ ] Type any character to edit

<br>

- [ ] Right-click menu
  - [x] When the right-click menu is open, we should block scrolling
  - [x] Right-click menu should be dismissed when clicking outside of it
  - [ ] Right-clicking on a selection shouldn't change the selection
    - [ ] Right-clicking on a cell/column/row should select said cell/column/row

<br>

- [ ] Editable (header) cells
  - [ ] Clicking outside of an cell being edited should disable editing
  - [ ] Ability to click on the edited text to place cursor and make a text selection with the mouse
  - [ ] Make editable cells and editable header cells consistent

<br>

- [ ] Selection
  - [ ] Clicking on "..." in cell shouldn't select the cell, similarly to other "..." (header for instance)
  - [ ] Column headers and row headers should reflect the current selection
  - [ ] Clicking on a selected cell shouldn't deselect it. Cmd+clicking on a cell should deselect it. (#1073)
  - [ ] Range select rows/columns `shift+click`
  - [ ] Add rows/columns/cells to selection `cmd+click`
  - [ ] Add to selection rectangle `cmd/shift+up`/`cmd/shift+right`/`cmd/shift+bottom`/`cmd/shift+left`
  - [ ] Clicking on a cell and dragging out of the table should widen selecting the active selection region

**Comment by samdenicola** [comment]
@llorca These look great -- can't wait! 

Any thoughts on adding onCellDoubleClick/onRowDoubleClick callbacks? I'm trying to build a "library"-esque table component where rows are a single item in one's inventory with different columns being attributes of the item. Users should be able to double click to "open" up an item. My solution so far feels a bit hacky -- and is ugly without one of the above proposed fixes: "Clicking on a selected cell shouldn't deselect it. Cmd+clicking on a cell should deselect it."
```
<Cell>
  <div
    className={'clickable-cell'}
    onDoubleClick={() => {
      console.log("row " + rowIndex + " has been double clicked!");
    }}
  >
    {cellText}
  </div>
</Cell>
```
It also forces me to write some css so that the clickable div fills the whole cell instead of just the cell text (Ideally I'd be able to hook in at a higher level like the Table component and have an "onRowDoubleClick".

Thanks for the great component :)

**Comment by llorca** [comment]
@samdenicola Thanks for the kind word! Yeah double click is a common interaction for tables, I'm onboard with supporting it more first class but can't give you a time estimate yet. For now adding a custom element with your own double click handler is the way to go 👍

**Comment by samdenicola** [comment]
@llorca fair enough sounds good -- how would you recommend getting around "Clicking on a selected cell shouldn't deselect it. Cmd+clicking on a cell should deselect it" combined with double clicking?

**Comment by llorca** [comment]
@samdenicola that's something we need to fix on our end, not sure if there's a workaround for that one at the moment. @gscshoyru @cmslewis?

**Comment by cmslewis** [comment]
I don't know enough about the table

**Comment by cmslewis** [comment]
Whoop

**Comment by cmslewis** [comment]
_(Oh my gosh, distracted-Chris versus the Github editor.)_

I don't know enough about the Table off the top of my head to know if it's possible to achieve click / cmd+click / double-click behavior in that way.

**Comment by samdenicola** [comment]
@cmslewis thanks!

**Comment by llorca** [comment]
Opened more scoped issues to better track this work:
- Better selection interactions (https://github.com/palantir/blueprint/issues/1079)
- More keyboard shortcuts (https://github.com/palantir/blueprint/issues/1080)
- Better editable cells (https://github.com/palantir/blueprint/issues/1081)
- Better right click menu (https://github.com/palantir/blueprint/issues/1083)

**Comment by cmslewis** [comment]
Just checked off a bunch of these
