### ISSUE TITLE
Select tries to render stale menu items

### ISSUE THREAD

**Issue by jroitgrund** [palantir/blueprint#2980]
#### Environment

- __Package version(s)__: 3.6.1
- __Browser and OS versions__: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0" ` but really any browser we tried on

#### Steps to reproduce

1. Create a select component with a few items
1. Remove one of the items from the list

e.g.

```
export class Debuggable extends React.PureComponent<{}, {
   services: { [key: string]: { name: string; } }
}
   > {

   constructor(props: {}) {
       super(props);
       setTimeout(() => { this.setState({ services: { "b": { name: "Service b" } } }) }, 5000)
   }

   public state = {
       services: { "a": { name: "Service a" }, "b": { name: "Service b" } } as { [key: string]: { name: string } }
   };

   public render() {
       return (
           <div>
               <ServiceSelect
                   onItemSelect={noop}
                   items={Object.keys(this.state.services)}
                   itemRenderer={this.renderService}
                   filterable={false}>
                   <Button rightIcon="caret-down" text="Add service Dependency" />
               </ServiceSelect>
           </div>
       );
   }

   private renderService = (id: string, { handleClick, modifiers }: IItemRendererProps) => {
       return (
           <MenuItem
               active={modifiers.active}
               disabled={modifiers.disabled}
               text={this.state.services[id].name}
               key={id}
               onClick={handleClick}
           />
       );
   };
}
```

#### Actual behavior

The component throws an error at the line `this.state.services[id].name` when trying to render the `MenuItem`: `this.state.services[id] is undefined`.

#### Expected behavior

This works fine.

**Comment by giladgray** [comment]
@jroitgrund interesting, I can see how this might happen.

what if you refactored the code to pass around the full `services` objects to `items`? that might work better and is more inline with how the component was designed.

**Comment by fscreene** [comment]
Switching to passing around the full services object fixed this issue.
