### ISSUE TITLE
On npm, 3.X.Y should be the latest version, not 1.40.0

### ISSUE THREAD

**Issue by galdebert** [palantir/blueprint#2985]
#### Steps to reproduce

npm i @blueprintjs/core

#### Actual behavior

in package.json:
"@blueprintjs/core": "^1.40.0"

#### Expected behavior

"@blueprintjs/core": "^3.6.1"

#### Possible solution

set the latest tag to the latest 3.X.Y version

**Comment by giladgray** [comment]
aw dang oops let me fix that real quick!

**Comment by giladgray** [comment]
fixed. publishing always changes `latest` tag and i forgot to reset it.
