### ISSUE TITLE
Icons look messed up

### ISSUE THREAD

**Issue by ihsw** [palantir/blueprint#2987]
#### Environment

- __Package version(s)__: 3.6.1
- __Browser and OS versions__: Firefox 62.0 (64-bit Linux)

#### Steps to reproduce

1. Upgrade to the the latest versions of @blueprintjs/core and @blueprintjs/icons

#### Actual behavior

Icons look messed up.

#### Expected behavior

Icons don't look messed up.

![busted](https://user-images.githubusercontent.com/1086917/46265882-befd3980-c4f8-11e8-8ef9-8abeacc2d427.png)

Please advise.

**Comment by giladgray** [comment]
@ihsw please make sure you're using the latest stylesheets from both `core` and `icons`. pretty sure this has been resolved.

**Comment by ihsw** [comment]
@giladgray This is from a clean `npm install` and build, but I will double check the stylesheets from both `@blueprintjs/core` and `@blueprintjs/icons`.

**Comment by giladgray** [comment]
how are you rendering these icons? they are not inheriting the proper colors, which suggests you are not using the `icon` prop?
expected this:
![image](https://user-images.githubusercontent.com/464822/46366970-49e14f80-c631-11e8-8528-606e4e802532.png)

**Comment by giladgray** [comment]
@ihsw i did some digging through your code and was dismayed to find copies of the blueprint css files in [this vender folder](https://github.com/ihsw/sotah-client/tree/master/app/public/styles/vendor). these files have not been updated in two months so **they are definitely out of date**. this means you are **using old styles with the latest code** which of course doesn't work.

I would strongly urge you to change your build so you can import directly from `node_modules`, or include a build step to regularly update your vendor directories.

**Comment by ihsw** [comment]
@giladgray that would explain it. Thank you.
