### ISSUE TITLE
[Tag] Tag with an icon and no text has an extra right margin

### ISSUE THREAD

**Issue by eshlin** [palantir/blueprint#2991]
Filing to track, though maybe an unsupported usecase to have no text. We're using the Blueprint Tag component with an icon, but no text to use as a "badge-like" component. Everything generally looks fine, except there's extra right margin of 4px, so the icon is not centered within the tag.

#### Environment

- Blueprint 3.6.1

#### Steps to reproduce

Representative React snippet:

```
<Tag
    icon={<BranchIcon />}
    interactive={true}
    round={true}
/>
```

where `<BranchIcon />` is a component that renders a branch icon

#### Actual behavior

![uncentered-branch-icon](https://user-images.githubusercontent.com/866294/46445090-f1da4400-c729-11e8-8dab-d072ecdc7e4a.png)

#### Expected behavior

![centered-branch-icon](https://user-images.githubusercontent.com/866294/46445094-f868bb80-c729-11e8-9029-b171d4e4e428.png)

(from overriding with custom CSS)

#### Possible solution

Potential solution would be to avoid rendering the `<Text>` with empty `children` if `children` is empty in https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tag/tag.tsx#L120-L122

**Comment by giladgray** [comment]
oh dang good catch. yeah we'll need to do what buttons do.
