### ISSUE TITLE
Date Range Picker reports the timezone inconsistently

### ISSUE THREAD

**Issue by acolombi** [palantir/blueprint#300]
The Date Range Picker may, or may not report the time zone of the returned date in fromDate or toDate, depending on how the date is set. If the date is set by typing a date, or programmatically, it usually does not report a time zone. If it's set using a shortcut (e.g. Last Week) it will often report the time range with UTC as the time zone (which incidentally means the reports dates, i.e. day of the time range, may not match the displayed day, because the displayed day is in the client's local time zone).

My recommendation is to stay out of the business of working with timezones and only return dates and times without time zone. The dates and times should reflect exactly what's displayed (i.e. don't report UTC times even when the displayed times are in local time zone).

The alternative might be to always report values in the local time zone, or enable the date picker to pick a time zone. These would enable more complex interactions, but maybe aren't worth it. (Hence my recommendation that you just report everything without time zone.)

**Comment by llorca** [comment]
@acolombi this may have been fixed by #297. Look out for release 1.2.0 later today!

**Comment by llorca** [comment]
At this point I think timezone support is more of a feature request than a bug. This is issue may be relevant in the context of `date-fns` considerations: https://github.com/palantir/blueprint/issues/317

**Comment by acolombi** [comment]
I agree that timezone support would be a feature request level change. I think I'm happy if the Date Range Picker is timezone-less.

**Comment by giladgray** [comment]
@acolombi what does "timezone-less" mean? to me that suggests UTC, that all times are in the universal time zone. but that'll get awkward for display. how would you like us to handle timezones?

**Comment by acolombi** [comment]
Have you ever worked with LocalDate or LocalDateTime in Joda/Java 8? These are date/time objects without a TimeZone. The advantage of them is that no matter how you interpret them, they always represent the same year-month-day-hour-minute. But you can't get millis since epoch from one.
