### ISSUE TITLE
Customizing the slider handle in <RangeSlider />

### ISSUE THREAD

**Issue by amaatouq** [palantir/blueprint#3000]
#### Environment
- __Package version(s)__: 3.7.0

#### Question

I want to customize the Slider Handle in `<RangeSlider />` such that I can have a different handle color for the two ends of the slider (i.e., the start handle will be green and the end handle will be red `value = [start, end]`). I also would like to change the color of the `TrackFill` and the shape of the handles (e.g., to match the shape of the `<Slider>` handle). 

My apologies if this is very obvious, but I am just getting started with this whole UI stuff!

**Comment by giladgray** [comment]
@amaatouq if you want to customize `RangeSlider` then you should use `MultiSlider` and build exactly what you need. However, changing the handle color is not currently supported. That'd be a cool feature and easy to add with the button intent mixins, but it's not a use case that's ever arisen for us. Coloring the track has been more than enough.
