### ISSUE TITLE
HTMLSelect icon disappears with focus in ControlGroup

### ISSUE THREAD

**Issue by Grmiade** [palantir/blueprint#3003]
#### Environment

- __Package version(s)__: 3.7.0 and below
- __Browser and OS versions__: Chrome 71 and Safari 12.0

#### Steps to reproduce

1. Create a ControlGroup with HTMLSelect inside it
2. Click on the select
3. Click outside the select to "make icon great again" 😂 

![screen recording 2018-10-08 at 12 21 06](https://user-images.githubusercontent.com/11244106/46604177-9fb46c80-caf5-11e8-919e-e50ba5a60c27.gif)

#### Actual behavior

The HTMLSelect icon disappears with focus

#### Expected behavior

The icon should not disappear

**Comment by giladgray** [comment]
nice subtle find! definitely something to do with the z-index logic of control groups.
