### ISSUE TITLE
[DateInput] Changing month and date do not work on IE 11

### ISSUE THREAD

**Issue by knalinne** [palantir/blueprint#3009]
#### Environment

- __Package version(s)__: 3.3.0 and below
- __Browser and OS versions__: IE 11 on Windows 10

#### Steps to reproduce

1. click on the field to open the popover
2. change month with arrow or select box
3. click on a date

![2018-10-09 09 06 40](https://user-images.githubusercontent.com/5163782/46652212-b533a000-cba2-11e8-9634-0b3e04853088.gif)

#### Actual behavior

At step 2, you can see the month is correctly set in the field
At step 3, the popover is closed but the date is not correctly set

#### Expected behavior

At step 3, the date should be correctly set

**Comment by giladgray** [comment]
duplicate of #2924
