### ISSUE TITLE
Test-friendly dialog animations

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#301]
Something like `.pt-minimal` for Dialogs which disables the animation or makes it instantaneous to improve unit testability (see issues like https://github.com/palantir/blueprint/pull/221#discussion_r90475758) both for us and for our consumers (apps sometimes have to introduce ugly timeouts in their dialog-related test code).

**Comment by llorca** [comment]
Hmm, fixing a test doesn't seem like a reason for adding `.pt-minimal` support to dialogs. Isn't the proper fix to find a way to test components that are animated?

**Comment by adidahiya** [comment]
Sure, I'd be open to other solutions, such as exposing an `onTransitionEnd` callback that allows for reliable testing.

**Comment by llorca** [comment]
Yes! That sounds great

**Comment by giladgray** [comment]
CSSTG simply doesn't provide hooks for `onTransitionEnd` so not sure how we'll do that...

**Comment by llorca** [comment]
What about `componentWillLeave()` and `componentDidLeave`? https://facebook.github.io/react/docs/animation.html#componentwillleave

**Comment by adidahiya** [comment]
@llorca yep, those would work; we'd have to refactor Overlay to use that lower-level API (TransitionGroup instead of CSSTransitionGroup)

**Comment by giladgray** [comment]
we could try mocking CSSTG in tests! http://stackoverflow.com/questions/36550906/disable-reacts-csstransitiongroup-in-test#comment60708967_36550906

**Comment by bsr203** [comment]
Hi. is there a way to disable animation on popover. My usecase is to use dropdown menu (like blueprint `Releases` menu on docs page), but top level menus shouldn't pop out. It somehow feels like an addon/context menu than main navigation. Is it easy to disable animation through css alone? thank you.

**Comment by giladgray** [comment]
It is indeed, try `<Popover className="pt-minimal" ... >`.
http://blueprintjs.com/docs/#components.popover.js.minimal

**Comment by bsr203** [comment]
thanks for the super quick response, greatly appreciate. but seems it not working. I added it to `Releases`, button like
```
                        <Popover className="pt-minimal" content={this.renderReleasesMenu()} position={Position.BOTTOM_RIGHT}>

```
still has the arrow.

![screen shot 2017-02-05 at 9 59 58 pm](https://cloud.githubusercontent.com/assets/1966521/22633352/9d08781a-ebee-11e6-93d5-15e0361f417f.png)

**Comment by giladgray** [comment]
I'm sorry, my code above was wrong. Refer to the docs link for the correct
code: `popoverClassName`

**Comment by bsr203** [comment]
thank you. that did work, sorry I didn't read the doc thoroughly.

one comment though. If I use this feature for main header menus, the drop down feel so detached from the trigger. I like some kind of styling to see which menu is activated, so in this case, at least the `Release` button to be active. As far I see, I have to make a custom component, which set the active state of button based on `popoverDidOpen` callback. Just wonder is there other way?
![screen shot 2017-02-06 at 7 21 04 am](https://cloud.githubusercontent.com/assets/1966521/22647151/e8591d48-ec3d-11e6-9244-857c2f38a26f.png)

**Comment by llorca** [comment]
@bsr203 You'd have to add `.pt-active` to your `.pt-button` trigger, when the popover is open

**Comment by adidahiya** [comment]
Note: this FR also applies to tree animations. As of this writing, https://github.com/palantir/blueprint/pull/679 adds a test that uses an arbitrary `300ms` setTimeout to wait for animations 🙅

**Comment by jrweinb** [comment]
Add `style={{ transition: 'none' }}` to the Dialog component to disable the scaling animation
