### ISSUE TITLE
Documentation style bug regarding TagInput

### ISSUE THREAD

**Issue by jtheisen** [palantir/blueprint#3024]
This is a bug only in the online documentation styles.

The `TagInput` control renders wrong in the large variant:

![image](https://user-images.githubusercontent.com/1516294/46904485-1500b280-cee5-11e8-9e61-c2172e7f1b7c.png)

This is the culprit rule:

![image](https://user-images.githubusercontent.com/1516294/46904481-01554c00-cee5-11e8-9c8a-84c7f82c07ce.png)

Disabling the `line-height` property makes it look proper.

**Comment by adidahiya** [comment]
This is no longer the case, seems to be fixed in the docs: https://blueprintjs.com/docs/#core/components/tag-input
