### ISSUE TITLE
menu (with shouldDismissPopover=false items) cannot be closed with Esc-key after being clicked

### ISSUE THREAD

**Issue by svilendobrev** [palantir/blueprint#3025]
#### Environment

- __Package version(s)__: 3.7
- __Browser and OS versions__: linux,opera,firefox..

#### Steps to reproduce
in the documentation, menu section, Dropdowns, the menu there can be closed with Esc but only until that "Table" element is clicked, then Esc doesnot work anymore.

https://blueprintjs.com/docs/#core/components/menu.dropdowns

**Comment by giladgray** [comment]
@svilendobrev i cannot reproduce this in chrome or firefox. granted, i don't have access to linux or opera but we don't explicitly support those.
