### ISSUE TITLE
Support consumption via unpkg CDN

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#303]
It's really convenient: https://unpkg.com/#/

Current status: unpkg acts as a CDN for our commonJS module https://unpkg.com/@blueprintjs/core@1.1.0. Not very useful.

Basically I think we just need to support the [`browser` field in package.json](https://github.com/defunctzombie/package-browser-field-spec) and publish the UMD bundle.

**Comment by timelyportfolio** [comment]
It's already there https://unpkg.com/@blueprintjs/core@1.1.0/, but unfortunately does not also contain a standalone.  I browserified a standalone in my fork [here](https://github.com/timelyportfolio/blueprint/tree/master/docs) for `core` and `table`.  This allowed me to use in R as shown in the just posted [example](http://bl.ocks.org/timelyportfolio/f4a791ee9e1ba02fbb2cfa4aa8aa26b9).

**Comment by Ciantic** [comment]
Should this work at the moment? I'm not getting a `<script />` tag for the blueprintjs when using the unpkg webpack loader. I do get it for e.g. react.

**Comment by Ciantic** [comment]
I think it works, but it's not discoverable by whatever way the modules cdn plugin finds it, I think the right url is this:

https://unpkg.com/@blueprintjs/core@1.15.0/dist/core.bundle.js

**Comment by giladgray** [comment]
@Ciantic it would seem like that webpack plugin does not support the `unpkg` key in package.json, which we define for each of our packages and rely on for correct usage with unpkg.com (see https://unpkg.com/#query-parameters). not much to be done on this end 😭
