### ISSUE TITLE
Accept `container` prop for Portal

### ISSUE THREAD

**Issue by gnestor** [palantir/blueprint#3033]
#### Environment

- __Package version(s)__: 3.7.0
- __Browser and OS versions__: Chrome 69

#### Feature request

It would be nice if we could pass our own `container` prop to Portal vs. Portal creating a new div element as a sibling to the root element. 

ReactDOM's createPortal method does exactly this: 

```typescript
ReactDOM.createPortal(child: React.Node, container: HTMLElement)
```

Why? Well I need to put some content in a portal and I want it to scroll with the rest of my content. My root element has `absolute` position with `scroll` overflow so I would like my portal to render in an element inside the root.

#### Examples

```jsx
<Portal container={document.getElementById('my-portal-container')} />
```

**Comment by giladgray** [comment]
@gnestor yeah this seems like a reasonable request. critical to note that no components currently expose `portalProps`, so this would be unusable by users of `Overlay`, `Dialog`, `Popover` etc

**Comment by KagamiChan** [comment]
@giladgray 
#3045 is another attempt for this issue, it is ready or some refinement is needed?

**Comment by Alynva** [comment]
Is that working?
