### ISSUE TITLE
[select] update inputProps documentation

### ISSUE THREAD

**Issue by tomaszbalsys** [palantir/blueprint#3037]
Prop `inputProps` in components `Select` and `Suggest` doesn't work.

#### Environment

- @blueprintjs/select 3.2.0
- Chromium 69.0.3497.100 (Official Build) Arch Linux (64-bit)

#### Steps to reproduce

```
<Suggest
  items={Films.TOP_100_FILMS}
  itemRenderer={renderFilm}
  inputValueRenderer={film => film.title}
  onItemSelect={this.handleValueChange}
  noResults={<MenuItem disabled text="No results." />}
  inputProps={{ value: query, onChange: this.handleChange }}
>
  <Button text={buttonText} rightIcon="caret-down" />
</Suggest>
```

#### Actual behavior

Method `this.handleChange` gets never executed.

#### Expected behavior

Providing prop `inputProps` should make component controlled.

#### Possible solution

In `suggest.tsx` in method `renderQueryList`:
```
                <InputGroup
                    {...inputProps}
                    placeholder={isOpen && selectedItemText ? selectedItemText : placeholder}
                    inputRef={this.refHandlers.input}
                    onChange={listProps.handleQueryChange}
                    onFocus={this.handleInputFocus}
                    onKeyDown={this.getTargetKeyDownHandler(handleKeyDown)}
                    onKeyUp={this.getTargetKeyUpHandler(handleKeyUp)}
                    value={isOpen ? listProps.query : selectedItemText}
                />
```
`{...inputProps}` should be moved to the end, so that it overrides `value` and `onChange` props.

**Comment by giladgray** [comment]
@tomaszbalsys this is by design and mentioned in the docs:
![image](https://user-images.githubusercontent.com/464822/47055494-80a88100-d16c-11e8-9ce6-b326b664c0ba.png)

**Comment by tomaszbalsys** [comment]
@giladgray Thank you for your answer. In that case the documentation needs to be updated.

https://blueprintjs.com/docs/#select/select-component:
![screenshot from 2018-10-17 20-52-14](https://user-images.githubusercontent.com/39491246/47109467-9a21f980-d24e-11e8-89e9-b1ffdcf09c56.png)

https://blueprintjs.com/docs/#select/suggest:
![screenshot from 2018-10-17 20-50-33](https://user-images.githubusercontent.com/39491246/47109379-634be380-d24e-11e8-9904-fa95e9b72449.png)

**Comment by giladgray** [comment]
ah fair enough.

**Comment by tomaszbalsys** [comment]
Another issue is that `onQueryChange` gets executed 3 times for one keypress.

In queryList.tsx:
1. `handleQueryChange` → `setQuery` → `onQueryChange`
2. `handleQueryChange` → `onQueryChange`
3. `componentWillReceiveProps` → `setQuery` → `onQueryChange`

I created the component like this:
```jsx
        <Suggest
          items={Films.TOP_100_FILMS}
          itemRenderer={renderFilm}
          inputValueRenderer={film => film.title}
          onItemSelect={this.handleValueChange}
          query={query}
          onQueryChange={this.handleChange}
        >
          <Button text={buttonText} rightIcon="caret-down" />
        </Suggest>
```

**Comment by giladgray** [comment]
@tomaszbalsys please do not conflate this issue with others. file a separate issue for separate concerns.

**Comment by EchoZw** [comment]
Is this a bug? Are you ready to fix it?

**Comment by giladgray** [comment]
@EchoZw i'm certainly ready for it to be fixed!

**Comment by EchoZw** [comment]
@giladgray Excuse me, when are you going to fix this problem?
and  I think you should add a bug label to this issue.
