### ISSUE TITLE
<Icon />s with an intent in <Tree />s do not have the correct color

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/blueprint#3042]
#### Environment

- __Package version(s)__: 

    "@blueprintjs/core": "^3.7.0",
    "@blueprintjs/icons": "^3.2.0",

#### Steps to reproduce

1. Create a <Tree /> with one element, where the element icon is an <Icon /> with an intent

#### Actual behavior

It is not the correct color

#### Expected behavior

It should be the correct color

#### Extra info

Repro: https://codesandbox.io/s/mj6nnkkmwx

**Comment by johnwiseheart** [comment]
Not sure why the repro has two icons though 😕 

In my use case specifically, I'm seeing this css issue:
![image](https://user-images.githubusercontent.com/4270292/47091028-fddeff00-d21b-11e8-9ff7-66db962a41c6.png)

**Comment by giladgray** [comment]
two icons == old CSS file.
classic specificity + definition order.

**Comment by johnwiseheart** [comment]
Hmm, I updated the CSS and it seems fine now - maybe its a bug with having multiple versions of blueprint? https://codesandbox.io/s/9o7r6vjqlr

**Comment by giladgray** [comment]
yes multiple versions would definitely affect the ordering in unreliable ways.

**Comment by chriswiggins** [comment]
Actually, we're having the same problem and it is due to something breaking between **3.6.1** and **3.7.0**. The latest release is also broken for trees.

I'll see what I can find and will comment back

**Comment by chriswiggins** [comment]
The commit from pull #2466 that breaks intent colors on trees is the following: https://github.com/palantir/blueprint/pull/2466/commits/0df54799f9d6c7b2551c5b402e5492f57d96a73f

The documentation doesn't have intents on trees as examples so easy to miss I'd say.

How do we go about fixing this? I'm new to blueprint contributions so welcome some guidance for a pull request 👍

**Comment by jacekjagiello** [comment]
@chrisbellande I've proposed a fix for this in PR #3355, please take a look at it, and let me know if you have a better solution :)
