### ISSUE TITLE
Wrong overlay mount-point when rendering in another web page using React.createPortal

### ISSUE THREAD

**Issue by KochiyaOcean** [palantir/blueprint#3043]
#### Environment

- __Package version(s)__: 3.7.0

#### Steps to reproduce

1. open the example https://codesandbox.io/s/30kyp019vq
1. click `open a portal` button

#### Actual behavior

A tooltip is rendered in the original webpage

![image](https://user-images.githubusercontent.com/8194131/47101993-84282f00-d276-11e8-82dd-38ca5ec62876.png)

#### Expected behavior

The tooltip should be rendered on the opened window

![image](https://user-images.githubusercontent.com/8194131/47102032-9c984980-d276-11e8-880c-90843d62133a.png)

#### Possible solution

set `usePortal` to false can avoid this problem, but there are some behavior differences on enable `usePortal` or not

**Comment by giladgray** [comment]
should be solved by #3033 so let's continue discussion there.
