### ISSUE TITLE
Select + ellipsis truncate + 100% width

### ISSUE THREAD

**Issue by yshterev** [palantir/blueprint#3049]
#### Environment

- __Package version(s)__:
"@blueprintjs/core": "^3.7.0",
"@blueprintjs/docs-theme": "^3.0.1",
"@blueprintjs/select": "^3.2.0",

- __Browser and OS versions__: Win 10, Chrome 69

#### Question

I am trying to use bootstrap 4 layout and grids +blueprint.js component. I am using [Select demo](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/select-examples/selectExample.tsx).

What I have is `div.d-flex > div.flex-1` and then form group inside with the select and a button. I tried `bp3-text-overflow-ellipsis` on the button inside the select but then select does not get full width.

Is there an example of something similar working?

**Comment by giladgray** [comment]
see #2956
