### ISSUE TITLE
Add stickyToTop prop to Navbar

### ISSUE THREAD

**Issue by jtreminio** [palantir/blueprint#3055]
#### Environment

- __Package version(s)__: ^3.7.0
- __Browser and OS versions__: Chrome 69, Fedora 27

#### Feature request

Add `stickyToTop` or similar named prop to Navbar, similar to `fixedToTop` prop.

`fixedToTop` uses `position: fixed` to affix Navbar to top of screen. Per W3C this is supposed to attach to the viewport and not any other elements on the page: https://www.w3.org/TR/css-position-3/#valdef-position-fixed

This means any sidebar element will be below the Topbar, as the Topbar stretches across the full width of the screen when fixed:

![image](https://user-images.githubusercontent.com/589398/47228234-5502e200-d38a-11e8-9667-357ae697e48e.png)

The `position: sticky` property, however, can be attached to an element and not just the viewport: https://www.w3.org/TR/css-position-3/#valdef-position-sticky

This allows the stickied element to respect its first parent with `position: relative`:

![image](https://user-images.githubusercontent.com/589398/47228393-b1fe9800-d38a-11e8-830f-a644bf524ff4.png)

![image](https://user-images.githubusercontent.com/589398/47228403-baef6980-d38a-11e8-9d33-bfbbe35a4b7a.png)

`position: sticky` has been in Chrome since 2012: https://developers.google.com/web/updates/2012/08/Stick-your-landings-position-sticky-lands-in-WebKit

All non-mobile browsers have support: https://caniuse.com/#feat=css-sticky

**Comment by giladgray** [comment]
the caniuse chart here is not particularly _encouraging_--I want to see more green across the board. the total lack of IE support is a bummer (though expected) since we do support IE11.
the light green on Edge and Chrome have this note: "Supported on `th` elements, but not `thead` or `tr`" which thankfully does not apply to this proposed use case.

![image](https://user-images.githubusercontent.com/464822/47238270-87b2d780-d396-11e8-8e5b-d0f63fa15777.png)

**Comment by giladgray** [comment]
all this to say i'm pretty meh on this feature overall but since you've done the work nicely I think we can make it happen. just gotta make sure to note the IE caveat in docs.

**Comment by sormazi** [comment]
Try to leave IE on atpx trysera server for the cloud. Send link to azure workbox. Side garner the xcode compiler using Swiftx.

**Comment by giladgray** [comment]
@jtreminio after some more thought and internal discussion, we have decided that this feature is not worth supporting in Blueprint itself for two reasons: 

1. it does not match our browser support commitments (no IE11) and 
1. it is trivially implemented as needed with nothing more than a single CSS override: 
  `position: fixed -> sticky;`.

thanks for taking the time to do the work and respond to my reviews! gonna close this out now.
