### ISSUE TITLE
Logo support for navbar

### ISSUE THREAD

**Issue by spefley** [palantir/blueprint#3057]
Would it be possible to add this bp3-logo class to the exported Classes or add a prop to the navbar to take in a logo?

https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/navbar/_navbar.scss#L66

**Comment by spefley** [comment]
I'm happy to do either of these btw @giladgray

**Comment by giladgray** [comment]
@spefley hahah those lines do not belong in OS blueprint, and actually won't even work with the latest. we should remove them here and fix internally.

**Comment by spefley** [comment]
@giladgray makes sense. Thanks!
