### ISSUE TITLE
Content wrapped by Tooltip renders multiple times

### ISSUE THREAD

**Issue by apietrzak** [palantir/blueprint#3060]
#### Environment

- __Package version(s)__: 3.7.0
- __Browser and OS versions__: Windows 10, Chrome 69.0.3497.100

#### Steps to reproduce

https://codesandbox.io/s/ykr6nl6m09

#### Actual behavior

When tooltip content is showing then wrapped content is rerendered (In example <Test /> component).

#### Expected behavior

Wrapped content should be rendered only once. 

#### Possible solution

---

**Comment by giladgray** [comment]
@apietrzak i'm inclined to say this is _by design_. are the multiple renders actually hurting your app, or are you just bugged by the fact that it happens multiple times? i'm fairly certain re-renders are required for proper tooltip positioning, so there's little to be resolved here.

**Comment by giladgray** [comment]
nah we don't offer any guarantees about "only renders once." this is not worth documenting, nor is it common practice in react components. sometimes extra renders are absolutely necessary.
