### ISSUE TITLE
yarn verify is requiring access to bash even on windows.

### ISSUE THREAD

**Issue by barkermn01** [palantir/blueprint#3062]
#### Environment

- __Package version(s)__: Develop Branch
- __Browser and OS versions__: Browser N/A, OS Windows 10 with node:10.7.0 yarn:1.10.1

#### Steps to reproduce

1. install python
2. install windows-build-tools
3. download repo
4. install yarn
5. run `yarn` inside repo directory 
6.run `yarn verify` inside repo directory

#### Actual behavior

```
yarn run v1.10.1
$ npm-run-all -s compile dist:libs dist:apps -p test lint
$ lerna run compile
lerna info version 2.7.1
lerna info versioning independent
$ tsc -p ./src
$ tsc -p ./src
lerna ERR! compile Errored while running script in '@blueprintjs/icons'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run compile
lerna ERR! 'bash' is not recognized as an internal or external command,
lerna ERR! operable program or batch file.
lerna ERR! error Command failed with exit code 1.
lerna ERR! ERROR: "compile:css" exited with 1.
lerna ERR! error Command failed with exit code 1.
lerna ERR! $ npm-run-all -s "compile:pre" -p "compile:*"
lerna ERR! $ generate-icons-source
lerna ERR! $ generate-icons-source
lerna ERR! $ sass-compile ./src
lerna ERR! $ tsc -p ./src
lerna ERR! $ tsc -p ./src/tsconfig.cjs.json
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\GitRepos\Beaconsoft\blueprint\node_modules\execa\index.js:236:11)
{ Error: Command failed: yarn run compile
'bash' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
ERROR: "compile:css" exited with 1.
error Command failed with exit code 1.
$ npm-run-all -s "compile:pre" -p "compile:*"
$ generate-icons-source
$ generate-icons-source
$ sass-compile ./src
$ tsc -p ./src
$ tsc -p ./src/tsconfig.cjs.json
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (C:\GitRepos\Beaconsoft\blueprint\node_modules\execa\index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '$ npm-run-all -s "compile:pre" -p "compile:*"\n$ generate-icons-source\n$ generate-icons-source\n$ sass-compile ./src\n$ tsc -p ./src\n$ tsc -p ./src/tsconfig.cjs.json\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   '\'bash\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nerror Command failed with exit code 1.\nERROR: "compile:css" exited with 1.\nerror Command failed with exit code
1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run compile',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "compile" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Expected behaviour

Yarn verify to work. and not produce an error on windows from the initial repo download.

#### Possible solution

stop using scss-compile and use a node-sass configuration & script.

**Comment by giladgray** [comment]
oh man it must be from these `#!/usr/bin/env bash` lines at the start of our script files. we cannot simply stop using these scripts. 

@barkermn01 all palantir devs use unix machines so windows support is not a priority for the team, but we're happy to work with you to enable it. can you offer a reasonable way to support windows development short of replacing our existing tools?

**Comment by barkermn01** [comment]
Ok so these don't seem to be doing that much in terms of syntax there are 3 that are problematic 
```
packages\node-build-scripts\
	css-dist.sh 		->	css-dist.bat
	sass-compile.sh		->	sass-compile.bat

scripts\
	revert-lerna-publish	->	revert-lerna-publish.bat
```

So I'm looking at trying to port them to work on windows.

**Comment by barkermn01** [comment]
Well, I'm looking at providing alternate tools for windows, however, I'm unsure how Lerna & Yarn are actually setting up the tools to work.
now both css-dist.sh amd sass-compile.sh are simple scripts. I have ported them to node scripts

**css-dst**
```javascript
#!/usr/bin/env node
let spawn = require(`child_process`).spawnSync;
let OUTPUT = `lib/css/`;

let proc = spawn(`postcss ${OUTPUT}/*.css --use autoprefixer --use postcss-discard-comments --replace --map`);
process.exit(proc.status);
```

**sass-compile**
```javascript
#!/usr/bin/env node
let spawn = require(`child_process`).spawnSync;
let OUTPUT = `lib/css/`;
let ROOT_NM = `../../node_modules`;
let args = process.argv;
delete args[0], args[1];
let argString = args.join(' ');

let proc = spawn(`${ROOT_NM}/.bin/node-sass-chokidar
--importer ${ROOT_NM}/node-sass-package-importer/dist/cli.js
--output ${OUTPUT}
--source-map true
${argString}`);

process.exit(proc.status);
````

and updated the package.json to use the `.js` version over the `.bat` version and we seem to be running on icons and most system.

So the failed to build is @blueprint/select with `[node-build-scripts] Failed to validate package layout: expected 'lib/css/blueprint-select.css' to exist.` & @blueprintjs/labs with `[node-build-scripts] Failed to validate package layout: expected 'lib/css/blueprint-labs.css' to exist.`

So i have got somewhere with this

**Comment by giladgray** [comment]
@barkermn01 those errors suggest your sass-compile script is not putting the CSS files in the correct place, so the work is not finished! converting to node scripts is reasonable i think.

**Comment by barkermn01** [comment]
@giladgray yeah I know that's what I worked out hence I have not sent a branch your way :D

**Comment by giladgray** [comment]
you know where to focus your efforts then :)
but i must say i cannot accept the code above as it's very different from our code style. please use our tslint rules and prefer `const` variables in all cases.

**Comment by barkermn01** [comment]
Yeah that's fine it was only a starter idea it just happened to work :D

**Comment by barkermn01** [comment]
Right i have a new CSS-Dist.js and SASS-Compile.js that are working correctly generating files now I'm getting error's with:
```
@blueprintjs/docs-app: ERROR in ../docs-data/src/index.js
@blueprintjs/docs-app: Module not found: Error: Can't resolve './generated/docs.json' in 'OBSUCURED\packages\docs-data\src'
```

What's supposed to generate this` ./generated/docs.json` so I can find out what's causing that error. @giladgray do you have any pointers to what i should be looking at?

**Comment by giladgray** [comment]
@barkermn01 seems Microsoft actually provides a thing to enable bash scripts on Windows:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

This might be your best option.

**Comment by barkermn01** [comment]
Yeah, I know about WSL and i have it installed however bash does not just get added as an exe to windows,  but it's not ideal to make someone install the whole Linux subsystem and most of Ubuntu's apps into there OS just to use a bash prompt bash, especially when you are using a Cross-Platform language when I have ported the bash scripts successfully and they do work. the problem seems to be more of an async issue with the PageMap class the bug I'm looking at can't be exclusive to windows. as it's in Javascript Code.

**Comment by barkermn01** [comment]
Just to verify when using VSCode on windows with WSL bash added to the path and the build scripts the WSL bash fails

```
stdout: '$ npm-run-all -s "compile:pre" -p "compile:*"\n$ generate-icons-source\n$ generate-icons-source\n$ tsc -p ./src\n$ tsc -p ./src/tsconfig.cjs.json\n$ sass-compile ./src\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
stderr: '/bin/bash: D:\\Projects\\Bluprintjs\\packages\\icons\\node_modules\\.bin\\..\\..\\..\\node-build-scripts\\sass-compile.sh: No such file or directory\nerror Command failed with exit code 127.\nERROR: "compile:css" exited with 1.\nerror Command failed with exit code 1.\n',
```

This is because the WSL does not use the correct paths for accessing the harddrive. so just to verify that WSL is not an option.

**Comment by giladgray** [comment]
@barkermn01 looking at the build scripts, i'll definitely support migrating the bash scripts to js like you proposed. but given that my workflow is fine and my plate is full, i'm going to have to ask you to dive in and contribute 😄

**Comment by barkermn01** [comment]
Well I have ported the Compilers I can't work out why the documentor module is not working, I can port the rest of the scripts but as per https://github.com/palantir/blueprint/issues/3062#issuecomment-432789094 I Can't work out why the documentator is failing. is there anyone who you could bring in to support me with that issue? or should i open an issue on the Repo for that.

**Comment by barkermn01** [comment]
Update on this i have replaced rm with a node implementation :D
https://github.com/palantir/blueprint/commit/bc958eead85159bd7aa857824754ec469852219a

**Comment by giladgray** [comment]
@barkermn01 have you run `yarn compile` first? that should generate that json file. you can also run `yarn compile` in `packages/docs-data/` directly.

**Comment by barkermn01** [comment]
The problem is in the compile scripts it's failing to create that file due to a strange bug in documenalist this is the problem I'm having that I can't work out it's failing to create.

**Comment by barkermn01** [comment]
Just to confirm when running `yarn compile` the output i get is,
```node
$ node ./compile-docs-data.js
[docs-data] ERROR when generating JSON docs data:
' in toTree()n @page 'blueprint
    at PageMap.toTree (D:\Projects\BlueprintJS\node_modules\documentalist\dist\page.js:55:19)
    at D:\Projects\BlueprintJS\node_modules\documentalist\dist\page.js:61:46
    at Array.forEach (<anonymous>:null:null)
    at PageMap.toTree (D:\Projects\BlueprintJS\node_modules\documentalist\dist\page.js:58:23)
    at MarkdownPlugin.compile (D:\Projects\BlueprintJS\node_modules\documentalist\dist\plugins\markdown.js:42:27)
    at D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:127:69
    at step (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:38:23)
    at Object.next (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:19:53)
    at step (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:23:97)
    at Object.next (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:19:53)
    at D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:13:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:9:12)
    at Documentalist.documentFiles (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:114:16)
    at Documentalist.<anonymous> (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:102:44)
    at step (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:38:23)
    at Object.next (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:19:53)
    at D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:13:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:9:12)
    at Documentalist.documentGlobs (D:\Projects\BlueprintJS\node_modules\documentalist\dist\documentalist.js:98:16)
    at generateDocumentalistData (D:\Projects\BlueprintJS\packages\docs-data\compile-docs-data.js:62:10)
    at D:\Projects\BlueprintJS\packages\docs-data\compile-docs-data.js:32:15
    at Object.<anonymous> (D:\Projects\BlueprintJS\packages\docs-data\compile-docs-data.js:39:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

Script line causing the error before entering into a node_module,
`Object.<anonymous> (D:\Projects\BlueprintJS\packages\docs-data\compile-docs-data.js:39:3)`

```js
(async () => {
    try {
        if (!fs.existsSync(GENERATED_SRC_DIR)) {
            fs.mkdirSync(GENERATED_SRC_DIR);
        }
        await generateDocumentalistData();
    } catch (err) {
        // console.error messages get swallowed by lerna but console.log is emitted to terminal.
        console.log(`[docs-data] ERROR when generating JSON docs data:`);
        console.log(err);
        throw err;
    }
})();
function generateDocumentalistData() {
    return new dm.Documentalist({
        markdown: { renderer: docsUtils.markedRenderer },
        sourceBaseDir: ROOT_DIR,
        // must mark our @Decorator APIs as reserved so we can use them in code samples
        reservedTags: ["import", "ContextMenuTarget", "HotkeysTarget"],
    })
        .use(".md", new dm.MarkdownPlugin({ navPage: NAV_PAGE_NAME }))
        .use(
            /\.tsx?$/,
            new dm.TypescriptPlugin({
                excludeNames: [/I.+State$/],
                excludePaths: ["node_modules/", "-app/", "test-commons/"],
                tsconfigPath: path.resolve(__dirname, "../../config/tsconfig.base.json"),
            }),
        )
        .use(".scss", new dm.KssPlugin())
        .use("package.json", new dm.NpmPlugin())
        .documentGlobs("../*/src/**/*.{scss,md}", "../*/src/index.{ts,tsx}", "../*/package.json")
        .then(docs => JSON.stringify(docs, transformDocumentalistData, 2))
        .then(content => fs.writeFileSync(DOCS_DATA_PATH, content));
}
```

**Comment by justinbhopper** [comment]
@barkermn01 I believe I found a fix for the latest error you're getting.  The error output doesn't mention it, but its due to a `spawn NOENT` when the compiler tries to spawn commands.

https://github.com/palantir/documentalist/pull/106

**Comment by justinbhopper** [comment]
@giladgray I believe the documentalist is now fixed, and this issue can be closed
