### ISSUE TITLE
Label component - update documentation

### ISSUE THREAD

**Issue by mattacus** [palantir/blueprint#3064]
#### Environment

- __Package version(s)__: @blueprintjs/core v.3.7.0
- __Browser and OS versions__: Chrome Version 69.0.3497.100

#### Steps to reproduce
The docs mention that the label "supports the full range of HTML props", and gives this example:

```
<Label
    helperText="Helper text with details..."
    text="Label A"
>
    <input className="bp3-input" id="text-input" placeholder="Placeholder text" />
</Label>
```

#### Actual behavior

These attributes give me a type error when I try to set them;  I would expect we can only use ```htmlFor``` and ```form``` as specific HTML attributes for the ```<label>``` element

#### Expected behavior

Example gives valid usage for the Label component.

#### Possible solution

Update the docs to show one of the attributes above, or by putting the text inside the label tag directly maybe?   I realize that using FormGroups is preferred, but it would have saved me some confusion from trying Label.

(By the way, I've been using the library for a bit and I'm interested in contributing!  If you can give me some guidance on what you'd like the docs to show here, I'd be happy to make a PR with the updates :slightly_smiling_face: )

**Comment by giladgray** [comment]
@mattacus thanks for reporting! happy to support your contributing goals 😄
this example should at the very least be valid code. doesn't have to be fancy. got a use case from your code that would be relevant here?

worst case:
```
<Label>
    Label text
    <input ... />
</Label>

**Comment by mattacus** [comment]
This sort of thing seems to work, although I get type warnings on htmlFor (seems ILabelProps doesn't have it):

```
<Label htmlFor="text-input">Input</Label>
 <input className="bp3-input" id="text-input" placeholder="Placeholder text" />
```

It could also work for a more complicated example like this:
```
<Label htmlFor="film-select">Film Select</Label>
<FilmSelect
        items={Films.TOP_100_FILMS}
        itemPredicate={Films.filterFilm}
        itemRenderer={Films.renderFilm}
        noResults={<MenuItem disabled={true} text="No results." />}
        onItemSelect={this.handleValueChange}
>
     <Button id="film-select" text={buttonText} rightIcon="caret-down" />
</FilmSelect>
```

Gotta say though, I prefer using FormGroup for sure.  Just want to save someone some time from the head scratching I had to do 😉
