### ISSUE TITLE
Problems using dark theme

### ISSUE THREAD

**Issue by warpdesign** [palantir/blueprint#3066]
#### Environment

- __Package version(s)__: blueprint 3.6.1, react 16.4.14
- __Browser and OS versions__: Windows 10 / Chrome 66.0.3359.181 (via Electron 3.0.5)

#### Question
When adding the class "bp3-dark" to my main container, here is what I'm getting:

![image](https://user-images.githubusercontent.com/199648/47418141-cfac7280-d779-11e8-88fd-53cbdcfd7f29.png)

Most elements (eg. Tree, InputGroup) don't seem to follow the dark theme: only the button group seems to be correct.

Is there something more (eg. include some dark css file?) to have correct dark theme in every components?

**Comment by giladgray** [comment]
@warpdesign you need to set a background color behind everything so the light text will appear. use `$pt-dark-app-background-color`.

**Comment by warpdesign** [comment]
@giladgray That's Sass/Less right? Does it mean I need to build a new version of the css files?

Right now I am just including this file:

```
require("@blueprintjs/core/lib/css/blueprint.css");
require("@blueprintjs/icons/lib/css/blueprint-icons.css");
```

Adding this fixes the problem:

```
.bp3-dark{
    background-color: #293742;
}
```

but I'd like to know what's the official/recommanded way.

**Comment by giladgray** [comment]
yes you need to add that background-color line somewhere. this is the official way. strongly recommend putting it on your own class instead of on `.bp3-dark` as that will mess up _every_ blueprint component.

some components set a background color for the theme (like `Card` or `Dialog`) but if you just slap `Classes.DARK` on an arbitrary container then you need to manually set the background yourself.

**Comment by barkermn01** [comment]
The easiest way to just affect your body tag dynamically i have a footer with a switch inside it but it shows how to get dark mode to work it's because the CSS uses `body.bp3-dark`

```js
import React, { Component } from 'react';
import { Alignment, Switch } from '@blueprintjs/core';

class Footer extends Component{

    constructor(){
        super()
        if(localStorage.getItem("DarkMode") === null){
            localStorage.setItem("DarkMode", "no");
        }
        this.state = {
            darkMode:localStorage.getItem("DarkMode") === 'yes',
            displayCopyWriteName:"Test Company"
        };
    }

    switchTriggered(){
            localStorage.setItem("DarkMode", (!this.state.darkMode)?"yes":"no");
            this.setState({darkMode:!this.state.darkMode});
    }

    render(){
        document.body.className = ((this.state.darkMode)?"bp3-dark":"bp3-body");
        console.log("Darkmode:", ((this.state.darkMode)?"bp3-dark":"bp3-body"), "state is", this.state.darkMode, "from LS", localStorage.getItem("DarkMode"));
        return (
            <footer className="bcn-footer-bottom ">
                &copy; {new Date().getFullYear()} {this.state.displayCopyWriteName}
                <Switch checked={this.state.darkMode} label="Dark Mode" onChange={this.switchTriggered.bind(this)} />
            </footer>
        );
    }
}

export default Footer;
```

**Comment by giladgray** [comment]
yeah nice, the docs site [does a similar thing](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/components/blueprintDocs.tsx#L27-L28) @barkermn01 👍 

@warpdesign see the docs styles: https://github.com/palantir/blueprint/blob/develop/packages/docs-theme/src/styles/_layout.scss#L72-L75, https://github.com/palantir/blueprint/blob/develop/packages/docs-theme/src/styles/_layout.scss#L89-L91

**Comment by MalikBagwala** [comment]
@barkermn01 instead of using a string "yes" or "no" it's better to use a boolean and just check if it is true or false
eg. `darkMode == true`

**Comment by barkermn01** [comment]
@MalikBagwala no because [`localStorage.getItem()`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem) and [`localStorage.setItem()`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem) only support a DOMString,

And it's more confusing to see "true" than it is to see "yes"

**Comment by UpsideDownRide** [comment]
@barkermn01 Minor nitpick - It's ternary not turnary - you have an expression that takes three arguments - hence the name.

**Comment by jgresham** [comment]
I'd really like to use the dark theme, but I am confused on how to get it done. I think this works. Could there be straightforward steps added to the docs https://blueprintjs.com/docs/#core/typography.dark-theme ? Something like:

App.js
```
import { Classes } from "@blueprintjs/core";
...
<div className={"App "+ Classes.DARK}>
    <child-elements-given-dark-theme></child-elements-given-dark-theme>
</div>
```

index.scss
```
...
@import "~@blueprintjs/core/src/common/variables";

$dark-content-background-color: $dark-gray4;

.App {
	&.#{$ns}-dark {
		background-color: $dark-content-background-color;
	}
}
...
```

**Comment by adidahiya** [comment]
@jgresham yes, we ought to improve the documentation around dark theme. This is already filed as an FR here https://github.com/palantir/blueprint/issues/4436
