### ISSUE TITLE
Set Focus on MenuItem in Select

### ISSUE THREAD

**Issue by ishiland** [palantir/blueprint#3069]
#### Environment
- __Package version(s)__: "@blueprintjs/select": "^3.2.0", "@blueprintjs/core": "^3.7.0",
- __Browser and OS versions__: Chome / Win 7

#### Question
I am unclear on how to set the focus to the selected `MenuItem` for a `Select` component. My use case is for accessibility. Is this possible? Are there any examples of this being done? Thanks.

**Comment by giladgray** [comment]
@ishiland use `activeItem` prop

**Comment by ishiland** [comment]
Oops looks like i missed that in the docs, its exactly what I needed. thanks
