### ISSUE TITLE
Suggest: Retain entered value on unfocus

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#3071]
#### Environment

- __Package version(s)__: `@blueprintjs/select 3.2.0`
- __Browser and OS versions__: any

#### Feature request

I'm trying to make`Suggest` work for search suggestions where users can enter any value and be provided with search suggestions, very similar to Google's search box.

My issue is that `Suggest` discards any non-matching user-entered value on unfocus. If no value is selected, it clears the entered value on unfocus. If a value has been previously selected, the entered  value is replaced with the previously selected value.

#### Examples

I'd suggest a new option `keepEnteredValues` option to retain non-matching values or alternatively, make it the default behaviour, like it is for `MultiSelect`.

**Comment by giladgray** [comment]
@silverwind could you perhaps make a gif demonstrating the issue?

**Comment by silverwind** [comment]
Sure,

Let me show you `MultiSelect` first. It behaves as I would expect by retaining the value after entry and clicking outside:

![multiselect](https://user-images.githubusercontent.com/115237/47524116-0aa5c780-d89a-11e8-83da-22a2ab50b155.gif)

Next the same for `Suggest`. You notice that the displayed value is seemingly lost when clicking outside, but it reappears magically when clicking the element again. Also, I think the content should not be selectable with a single click.

![suggest](https://user-images.githubusercontent.com/115237/47524162-27da9600-d89a-11e8-994b-957ce66d6edd.gif)

I think this is more like a bug than a feature request really. `MultiSelect` does it right in my opinion.

**Comment by giladgray** [comment]
nice. yeah i feel the `MultiSelect` behavior too, happy to support changing `Suggest` to match. @silverwind are you interested in making the PR?

**Comment by silverwind** [comment]
I'll look into it.

**Comment by silverwind** [comment]
Not sure I can actually contribute as I'm failing to get a development environment up.

`yarn run compile` errors with `TS2694: Namespace 'ts' has no exported member 'ImportTypeNode'`
`yarn dev:select` spews a lot of errors like `TS2307: Cannot find module './generated/iconNames'`

(This is using node 10.12, yarn 1.10.1, macOS 10.14)

My basic idea was to drop [this line](https://github.com/palantir/blueprint/blob/15f8a82ebaa3afff52f14ea2ae09d433b2d9bedf/packages/select/src/components/select/suggest.tsx#L177) and debug what's happening to [this value](https://github.com/palantir/blueprint/blob/15f8a82ebaa3afff52f14ea2ae09d433b2d9bedf/packages/select/src/components/select/suggest.tsx#L156).

**Comment by giladgray** [comment]
yeah i'm working on resolving this locally...

**Comment by giladgray** [comment]
@silverwind i just merged #3078 so please merge latest `develop` and try building again.

i have never seen this `ts` error locally but seems quite common from contributors. not really sure what it's about.
definitely need to have a successful `yarn compile` before you can `yarn dev` anything.

**Comment by JIAQIA** [comment]
> @silverwind i just merged #3078 so please merge latest `develop` and try building again.
> 
> i have never seen this `ts` error locally but seems quite common from contributors. not really sure what it's about.
> definitely need to have a successful `yarn compile` before you can `yarn dev` anything.

tset

**Comment by bsr203** [comment]
@giladgray I too in need of this otherwise it behave just like `Select` as the user cannot input any value other than options. If it is a small change, can the core team look into this. thank you.

**Comment by giladgray** [comment]
@silverwind i just opened https://github.com/palantir/blueprint/pull/3289 to address this issue. does it seem reasonable?

**Comment by silverwind** [comment]
Looking good to me based on your gif. My only remaining concern is now the full-text selection on focus in `Suggest` which does not match the `MultiSelect` behaviour. I think it'd be as simple as removing `this.selectText()` in `handleInputFocus`. Would you mind trying that? I would send you a PR, but I had a lot of trouble getting the dev environment up.
