### ISSUE TITLE
z-index does not work with Alert component

### ISSUE THREAD

**Issue by jbadilla** [palantir/blueprint#3074]
#### Environment

- __Package version(s)__: latest blueprint.js
- __Browser and OS versions__: OSX (El Capitan) // Google Chrome – Version 70.0.3538.77 (Official Build) (64-bit)

#### Feature request

I would like to be able to set the z-index for the Alert Component. I am running into an issue where I have a modal that is supposed to trigger an alarm, but the modal supersedes the alarm, even when I set the alarm's z-index higher than that of the modal; so the alarm gets triggered, but is still behind the modal.

#### Examples

Be able to trigger an alarm that supersedes a modal by simply setting its z-index.

**Comment by giladgray** [comment]
@jbadilla can you share a gif demonstrating the issue? hard to understand from language alone. 

Overlay components will stack themselves in DOM order, so if you want an overlay to appear above another one, you should ensure it uses a portal (`usePortal` defaults to true) and open them in the desired order.

**Comment by giladgray** [comment]
closing as stale. needs more info.
