### ISSUE TITLE
Add .bp3-button.bp3-xlarge to Classes? 

### ISSUE THREAD

**Issue by spefley** [palantir/blueprint#3076]
@giladgray here's another bp3 class that isn't exported on Classes. Should it be? If not, why not?

**Comment by giladgray** [comment]
@spefley this class does not exist in blueprint itself. must be a custom thing.
https://github.com/palantir/blueprint/search?q=xlarge&unscoped_q=xlarge

**Comment by spefley** [comment]
yikes. I will have to track that down...
