### ISSUE TITLE
Publish ES2015 modules in addition to CommonJS modules

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#309]
Following up from a discussion here: https://github.com/palantir/blueprint/issues/245#issuecomment-263065706

> For consumers to utilize tree shaking, we'll have to publish ES6 modules in addition to CommonJS modules (static analysis tools work much better with the former). Shouldn't be too hard; we can use tsconfig.json inheritance and create multiple folders in dist/, dist/es6/ and dist/cjs/

**Comment by adidahiya** [comment]
Here's an example of a library that pulishes UMD, CJS, and ES6 modules in its NPM package: https://github.com/mjackson/history

**Comment by adidahiya** [comment]
Based on [this post about the state of JS modules](https://medium.com/webpack/the-state-of-javascript-modules-4636d1774358), we should be compiling to `.mjs` files and point package.json's `"module"` to the ESM entry point.

**Comment by adidahiya** [comment]
I can pick up this task this week.

**Comment by giladgray** [comment]
👍  go for it!

**Comment by giladgray** [comment]
@adidahiya however... https://medium.com/webpack/the-state-of-javascript-modules-4636d1774358#4cb9

> **Should I use .mjs for ESMs now?**
> **No.** There’s currently no benefit of it and tooling support is still weak. I recommend to start the transition as soon as native ESM support lands in Node.js. Remember that browsers do only care about MIME types, not file extension.
