### ISSUE TITLE
Multilevel menu as dropdown has strange click behaviour 

### ISSUE THREAD

**Issue by SaravananM21** [palantir/blueprint#3095]
#### Environment

- __Package version(s)__: 3.7.0
- __Browser and OS versions__: Chrome 70, Mac OS X 10.13.4

#### Steps to reproduce

1. Create a menu with submenu in a navbar - as per this example in the docs - https://blueprintjs.com/docs/#core/components/menu.dropdowns
1. Click on the Open In to show the popover
1. Hover over Settings
1. Click on Remove application
1. Click on the Open In again to show the popover
1. _Click_ on Settings
1. Click on Remove application

#### Actual behavior

In the first case, the onClick functionality for Remove application is called, causing the whole popover to disappear.

In the second case, the onClick functionality for Remove application is not called. Instead the submenu disappears, but the popover remains. This appears to be because when you click on Settings, it becomes focused (though it doesn't show because the docs' css has bp3-focus-disabled so you don't see the usual blue focus outline), and being focused causes different behaviour.

#### Expected behavior

In both cases, the onClick functionality for Remove application is called, causing the whole popover to disappear. When you click on the Settings button, it shouldn't become focused, as is the case when you have a multi level menu that's not a dropdown.

#### Possible solution

Disable the settings button becoming focused when you click it? Not sure why the different behaviour when in a dropdown popover vs not.

**Comment by adidahiya** [comment]
This is no longer a problem, I cannot repro in the docs example. Fixed by MenuItem2.
