### ISSUE TITLE
@bluprintjs/core bundle includes react-popper

### ISSUE THREAD

**Issue by betalb** [palantir/blueprint#3097]
#### Environment

- `@bluprintjs/core` - 3.7.0
- browser version is irrelevant

#### Steps to reproduce

1. `yarn add @blueprintjs/core`
1. check contents of `node_modules/@blueprintjs/core/dist/coire.bundle.js`

#### Actual behavior

Bundle includes sources of `popper.js` and `react-popper`

#### Expected behavior

Bundle should just `require('react-popper')` in UMD header (`popper.js` is dependency of react-popper)

#### Possible solution

Update `https://github.com/palantir/blueprint/blob/develop/packages/webpack-build-scripts/externals.js` and mark `react-popper` as external dependency

**Comment by mintyzhu** [comment]
emm...

**Comment by giladgray** [comment]
yeah oops gotta update list of externals.

**Comment by adidahiya** [comment]
fixed by https://github.com/palantir/blueprint/pull/3276
