### ISSUE TITLE
Toast update with key should also update timeout option

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#3107]
#### Environment

- __Package version(s)__: core@3.7.0
- __Browser and OS versions__: chrome@70.0.3538.77

#### Steps to reproduce
```
import { Toaster, Position } from "@blueprintjs/core";

const toastr = Toaster.create({
  position: Position.TOP
});

let timesShown = 1;
    const key = toastr.show({
      message: `shown ${timesShown}`,
      timeout: 100000
    });

    const interval = setInterval(() => {
      timesShown++;
      toastr.show(
        {
          message: `shown ${timesShown}`,
          timeout: timesShown === 10 ? 3000 : 100000
        },
        key
      );
      if (timesShown === 10) {
        clearInterval(interval);
      }
    }, 1000);
```

#### Actual behavior

The toastr keeps the original timeout of 100 seconds meaning that after finishing it still won't dismiss automatically

#### Expected behavior

That updating the timeout will make the toastr dismiss when the new timeout triggers

#### Possible solution

in the toastr code
```
 public componentDidUpdate(prevProps: IToastProps) {
        if (prevProps.timeout <= 0 && this.props.timeout > 0) {
            this.startTimeout();
        } else if (prevProps.timeout > 0 && this.props.timeout <= 0) {
            this.clearTimeouts();
        }
    }
```
that first check for ```prevProps.timeout <= 0``` seems wrong. It should start the timeout regardless so that the newly passed timeout prop will be used.

**Comment by giladgray** [comment]
@tgreen7 yep seems a legit bug!
