### ISSUE TITLE
HTMLSelect styling

### ISSUE THREAD

**Issue by alex-deas** [palantir/blueprint#3109]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: Firefox - MacOS Mojave

#### Steps to reproduce

Create a component with the style props such as:
```jsx
<HTMLSelect
  options={["foo", "bar"]}
  onChange={() => undefined}
  value="foo"
  minimal={true}
  disabled={false}
  style={{ top: 31, left: 62 }}
/>
```

#### Actual behavior

Inline styles are applied to html `select` element

#### Expected behavior

Inline styles are applied to the HTMLSelect surrounding `div` with class `bp3-html-select`

#### Possible solution

Use the CSS class to target the element instead

**Comment by giladgray** [comment]
@alex-deas use `className` to apply these styles.
