### ISSUE TITLE
Is there a way to pass an inline style to the <FormGroup/> component?

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#3116]
@giladgray 
```js
<FormGroup
        style={formGroupStyle}
      >
...stuff here
      </FormGroup>
```

Passing style above does not seem to do anything. Is there a way to pass an inline style to the `<FormGroup/>` component?

Thanks!

**Comment by giladgray** [comment]
@tnrich nope just `className` but i don't mind adding this as i'm actually about to add a few other useful props to `FormGroup`
