### ISSUE TITLE
Change "Filter ..." text on Select component

### ISSUE THREAD

**Issue by llermaly** [palantir/blueprint#3124]
Hello, 

How can I change the "Filter ..." text that appears when select list is clicked before typing?

I could change noResults text but no Filter text.

Another question is how to add scrollbar to long lists. In examples a scrollbar appears but not in my code.

Thanks!

**Comment by giladgray** [comment]
@llermaly `<Select inputProps={{ placeholder: "My placeholder text" }} />`
https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/select/select.tsx#L115-L117

**Comment by giladgray** [comment]
you should see a scrollbar automatically, there is a max-height in CSS. https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/select/_select.scss#L22
