### ISSUE TITLE
Missing polyfill for Element.closest on IE11?

### ISSUE THREAD

**Issue by mrijke** [palantir/blueprint#3128]
#### Environment

- __Package version(s)__: `"@blueprintjs/core": "3.7.0"`
- __Browser and OS versions__: Windows 10 / IE11

#### Question
When using the Popover component, I'm getting an error on IE11 about "Object doesn't support property or method 'closest'".
According to MDN, this method is not supported on IE11 (https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)

I've added the polyfill from MDN and it started working again. I can also not reproduce it on the blueprint docs website, so either I'm doing something wrong on my side or the docs application already includes some polyfills.

My question, is this known behavior? Is this supposed to work out of the box on IE11? Or do I have to keep my own polyfill around?

**Comment by giladgray** [comment]
@mrijke  please ensure you are loading `dom4` onto the page. this is one of our dependencies and provides a polyfill for this method. 
https://github.com/palantir/blueprint/blob/develop/packages/core/package.json#L44
https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/index.ts#L8-L13

**Comment by mrijke** [comment]
@giladgray thanks! Looks like I was missing that indeed.
However, looking at the docs (https://blueprintjs.com/docs/#blueprint/getting-started.dom4) it states that it should be loaded automatically. Any clue why that didn't happen in my case? I think I'm importing things in the right way...
```tsx
import { Popover } from "@blueprintjs/core";
```

**Comment by giladgray** [comment]
@mrijke i can't possibly answer that question without understanding your environment! but the require statement is _dynamic_, meaning it happens at runtime (if DOM APIs exist) instead of bundle time. so your environment must support dynamic imports.

**Comment by mrijke** [comment]
@giladgray Understandable. In any case, adding an explicit import seemed to have solved the issue - so I'm fine with that :)
Thanks for your help!
