### ISSUE TITLE
<Breadcrumb> does not exist (error in docs)

### ISSUE THREAD

**Issue by shahzeb1** [palantir/blueprint#3131]
#### Environment

- __Package version(s)__: 3.7
- __Browser and OS versions__:  Chrome / Mac

#### Steps to reproduce

Refer to this link in the docs: https://blueprintjs.com/docs/#core/components/breadcrumbs.breadcrumbs

```js
private renderCurrentBreadcrumb = ({ text, ...restProps }: IBreadcrumbProps) => {
        // customize rendering of last breadcrumb
        return <Breadcrumb {...restProps}>{text} <Icon icon="star" /></Breadcrumb>;
    };
```

There is no such thing as `<Breadcrumb>` and therefore, there is an error thrown.

#### Actual behavior

Error is thrown if the sample code is run. I'm not sure if the user is suppose to understand / define their own `<Breadcrumb/>` component.

#### Expected behavior

Unsure what should go there, but replacing `<Breadcrumb>...</Breadcrumb>` with `<div>...</div>` seems to fix things.

#### Possible solution

Please let me know what the correct fix to this will be and I'll go ahead and make a PR.

Thank you.

**Comment by giladgray** [comment]
@shahzeb1 add the import to the first line. this is an error in the docs code.

```diff
- const { Breadcrumbs, IBreadcrumbProps, Icon } = "@blueprintjs/core";
+ import { Breadcrumb, Breadcrumbs, IBreadcrumbProps, Icon } from "@blueprintjs/core";

**Comment by petersobolev** [comment]
Still not fixed (lack if import { Breadcrumb, .. } )
https://blueprintjs.com/docs/#core/components/breadcrumbs
