### ISSUE TITLE
Allow to show Single Month Only in DateRangePicker

### ISSUE THREAD

**Issue by nileshr** [palantir/blueprint#3133]
#### Environment

- __Package version(s)__: Datetime 3.3.1
- __Browser and OS versions__: All

#### Feature request

Allow to pass `singleMonthOnly` props to show only a single month in the DateRangePicker and DateRangeInput. Alternatively, can avoid overriding React Day Picker's `numberOfMonths` to allow the user to specify the numberOfMonths to be rendered.

#### Examples

```jsx
<DateRangePicker
    value={[this.state.startDate, this.state.endDate]}
    onChange={this.handleDateChange}
    singleMonthOnly={true}
/>
```
OR 
```jsx
<DateRangePicker
    value={[this.state.startDate, this.state.endDate]}
    onChange={this.handleDateChange}
    numberOfMonths={1}
/>
```

**Comment by giladgray** [comment]
@nileshr we already expose `dayPickerProps` but the [docs explicitly note that `numberOfMonths` cannot be configured](https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/dateRangePicker.tsx#L67-L69). i'd be happy to allow configuration of that prop, if you're willing to push up a PR 👍

**Comment by nileshr** [comment]
@giladgray Yes, I noted that. Would it be useful to just allow for `singleMonthOnly` prop to make the DateRangePicker look consistent with the usual DatePicker? Will be willing to push a PR for that.

**Comment by nileshr** [comment]
@giladgray I've raised a PR for this. This is my first time contributing in this repository, so please let me know if there's anything that I might have missed.
