### ISSUE TITLE
How to get the example code?

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3138]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question

How to get the example code that showed in the doc, such as the Table component ?

**Comment by giladgray** [comment]
Click the "View source" link below the example.

**Comment by giladgray** [comment]
<img width="840" alt="view-source" src="https://user-images.githubusercontent.com/464822/48306410-1df59b80-e506-11e8-9634-e6e889474827.png">
