### ISSUE TITLE
Interactions on docs page scroll page to bottom

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#314]
### Bug report

- __Package version(s)__: 1.2.0
- __Browser and OS versions__: Chrome 55.0.2883.75

#### Steps to reproduce

1. Click on the popover target here: http://blueprintjs.com/docs/#components.popover

#### Actual behavior

Page scroll position jumps to the bottom. This only seems to happen on Chrome 55. Safari appears to behave properly. Perhaps this is an issue introduced by some changes in Chrome?

#### Expected behavior

Page scroll position should not change when interacting with elements.

**Comment by michael-yx-wu** [comment]
Follow up: this also seems to happen when interacting with custom context menus on Blueprint Table examples, so this might is probably not due to something specific to a single component.

**Comment by llorca** [comment]
Tried Chrome 54, no problem. Can repro on Chrome 55. Damn it.

**Comment by adidahiya** [comment]
Probably the same as #231.

**Comment by michael-yx-wu** [comment]
Okay, closing in favor of #231!
