### ISSUE TITLE
Why blueprint do not supply the example code with javascript ?

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3143]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question
Why blueprint do not supply the example code with javascript ?

**Comment by giladgray** [comment]
> Blueprint is written in TypeScript, a statically typed superset of JavaScript that compiles to plain JavaScript. All the code samples throughout this site and all interactive examples are also written in TypeScript. TypeScript code looks exactly like ES2015+ code with the addition of type signatures, which typically appear after colons and are italicized in our syntax theme.


https://blueprintjs.com/docs/#blueprint/reading-the-docs
