### ISSUE TITLE
How to catch a keyDown on an EditableText component 

### ISSUE THREAD

**Issue by TeaBough** [palantir/blueprint#315]
I'd like to do the same thing than in the blueprint doc, having the popover autocomplete in the search area in the header. But instead of using a `InputGroup` I'd like to use an `EditableText` component. Everything works fine except for the fact that when I press `ARROW_DOWN` I'd like to navigate through the menu items ... But with `EditableText` I can't catch `keyDown` events. Does somebody know a workaround ?

**Comment by giladgray** [comment]
`EditableText` does not expose key event listeners, but it easily could if we wanted it to. Perhaps it should accept all `React.HTMLProps<HTMLInputElement>` so you can do what you like.

In the meantime, you could put a wrapper element around the ET that handles key events?

**Comment by TeaBough** [comment]
Thanks @giladgray with the wrapper it's working perfectly !
