### ISSUE TITLE
It always show a strange border style after clicked a button.

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3151]
Hi guys, I got a strange issue as follow screen shot. It would show the strange borer that I couldn't find reason after clicked the button or select component. So what's wrong?

#### Steps to reproduce
Just use the component as follow code.
```
<Button intent="primary" onClick={() => { this.onSearch(detail); }}>Search</Button>
```

#### Actual behavior

![image](https://user-images.githubusercontent.com/3346188/48536955-05f98f80-e8eb-11e8-988b-9783e31ebb90.png)

![image](https://user-images.githubusercontent.com/3346188/48537129-89b37c00-e8eb-11e8-9029-51d80db2b299.png)

**Comment by giladgray** [comment]
@fachilles this the focus state. see https://blueprintjs.com/docs/#core/accessibility.focus-management for details.
