### ISSUE TITLE
blueprint-html-components lint rule should not work when there is no blueprint dependency

### ISSUE THREAD

**Issue by styu** [palantir/blueprint#3154]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Steps to reproduce

1. Have a package in monorepo that uses blueprint
1. Have another package in monorepo that doesn't use blueprint
1. Have the latter package use native HTML elements like `<h2>`

#### Actual behavior

1. The lint rule complains about not using blueprint html components

#### Expected behavior

1. The lint rule doesn't complain in the package that doesn't use blueprint

**Comment by styu** [comment]
For that matter, this rule also is only relevant for consumers on blueprint 3.x, since blueprint 1.x has no remediation for the rule

**Comment by adidahiya** [comment]
lint rule implementations typically don't know this kind of information, so this is probably best solved at the level of tooling which runs tslint. in theory we might be able to use the `ts.Program` to see if the module `"@blueprintjs/core"` resolves to something to indicate the presence of the dependency, but (1) I'm not sure if that's possible and (2) it won't be reliable for monorepos

**Comment by giladgray** [comment]
yep if you're not using blueprint then disable the rule. that's the expected usage here.
