### ISSUE TITLE
Utils.measureTextWidth should add span to relevant container not body - measurements are off

### ISSUE THREAD

**Issue by paulpooch** [palantir/blueprint#316]
My root has font-size of 100px.

My div holding the `<Blueprint.DatePicker>` has `font-size: 16px`.

DatePicker tries to measure the width of the month labels by adding <span>'s to the body - as a result the measurements are wrong.  I'd suggest the <span>'s get appended to the component container and NOT document.body.

This would stop differing font-sizes from screwing things up.

**Comment by adidahiya** [comment]
yeah, that makes sense @paulpooch. we could change the function signature to

```ts
export function measureTextWidth(text: string, className = "", containerElement = document.body) {
    ...
}
```

**Comment by paulpooch** [comment]
Sounds good.  My issue was in datePickerCaption.positionArrows()

It was measuring totally wrong and my arrows were like halfway across the page : )

Could you slap a ref on on the root div of datePickerCaption and measure relative to that element?  I can make a PR if you want I don't know TS yet.

**Comment by giladgray** [comment]
@paulpooch if you're interested in learning some TS then go ahead and make a PR! we'll help you through any tricky bits. otherwise the team will pick this up early next year.

**Comment by cmslewis** [comment]
@paulpooch I had some time to open a PR for this today. Feel free to peruse #320 and see if it makes sense and addresses things correctly. Would appreciate your thoughts here. 👍

**Comment by paulpooch** [comment]
Thanks I'll check this out tomorrow.
