### ISSUE TITLE
[select/suggest] prop inputProps in component Suggest doesn't work

### ISSUE THREAD

**Issue by EchoZw** [palantir/blueprint#3163]
#### Environment

- @blueprintjs/select : 3.3.0
- chrome:  70.0.3538.102 (Official Build) (64-bit)

#### Question

Prop inputProps in components Suggest doesn't work

#### Description of the prop of the inputProp of the component

![image](https://user-images.githubusercontent.com/23427655/48657600-3ae21f80-ea6e-11e8-8638-b952abc197d2.png)

#### Steps to reproduce

```javascript
const inputProps = {
  value: "unknown",
  onChange: e => {
    console.log(e.target.value);
  }
};
<Suggest
      inputProps={inputProps}
      itemRenderer={renderItem}
      items={list}
      inputValueRenderer={inputValueRenderer}
      noResults={
        <MenuItem className="empty-result" disabled={true} text="No Results" />
      }
      onItemSelect={() => {
        console.log("select");
      }}
    />
```

#### Actual behavior

- Method `onChange` gets never executed.
- Property `value` doesn't work

#### Expected behavior

Providing prop `inputProps` should make component controlled.

Links to [codesandbox](https://codesandbox.io/s/5wx7j72rmn)

**Comment by giladgray** [comment]
ahh a follow up from #3037. the prop docs are wrong.

**Comment by giladgray** [comment]
@EchoZw i have deployed the fix above to the docs site.
