### ISSUE TITLE
Allow MenuItem to customize icon size

### ISSUE THREAD

**Issue by lukyth** [palantir/blueprint#3165]
#### Environment

- __Package version(s)__: `@blueprintjs/core@3.9.0`
- __Browser and OS versions__: Google Chrome Version 70.0.3538.102 (Official Build) (64-bit) and macOS Mojave 10.14.2 Beta (18C48a)

#### Feature request

Would it be a good idea to make `MenuItem` allow `iconSize` prop to adjust icon size? Right now it renders `Icon` with `<Icon icon={icon} />` ([source](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/menu/menuItem.tsx#L125)), hence making the icon size fixed to `16` with no way to modify it.

#### Examples

```ts
<MenuItem text="Project" icon="folder-close" iconSize={20} />
```

**Comment by giladgray** [comment]
this is already possible using the `Icon` component directly: 
`<MenuItem text="Project" icon={<Icon icon="folder-close" iconSize={20} />} />`

**Comment by lukyth** [comment]
Oh, sorry I totally missed that. Thank you for answering this. 🙇
