### ISSUE TITLE
Tree - node hover callback

### ISSUE THREAD

**Issue by oliverox** [palantir/blueprint#3168]
#### Environment

- __Package version(s)__: 3.0.0
- __Browser and OS versions__:  n/a

#### Question

I am in need of a callback whenever the user hovers on a tree node (e.g: `onNodeHover()`). Is this possible as of today? If not, may I request this as a feature?

**Comment by giladgray** [comment]
@oliverox this is not currently possible but could easily be added as `onMouseEnter` etc handlers on [ITreeNodeProps](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tree/treeNode.tsx#L71-L75). happy to review a PR if you push it up 👍
