### ISSUE TITLE
DateInput does not support tabIndex property

### ISSUE THREAD

**Issue by kittle31** [palantir/blueprint#3169]
#### Environment

- __Package version(s)__: Core 3.9.0. datetime 3.4.0
- __Browser and OS versions__:  Chrome 70.0, Windows 10

#### Steps to reproduce
    Use the following
      <DateInput value={date } placeholder={"pick a date"}
               large={true}
               onChange={ change handler }
               **inputProps={{tabIndex: 1}}**
      {...getMomentFormatter()} />
      <InputGroup value={"whatever"} 
              onChange={ change handler }
              tabIndex={2}
              />
Click in the text field, and press the tab key

#### Actual behavior
Cursor moves to some seemingly random control on the page

#### Expected behavior
Cursor moves to the date input

#### Possible solution
Allow inputProps to pass all property values to the <input> tag in DateInput
-or-
update examples to show how inputProps should be used

**Comment by giladgray** [comment]
@kittle31 can you please construct a code sandbox to demonstrate the bug? use https://codesandbox.io/s/rypm429574 as a starting point.

**Comment by giladgray** [comment]
as far as i can tell, [we've done our part in the code](https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/dateInput.tsx#L219). `inputProps` is passed to the `InputGroup` as expected, and `zIndex` is not overridden.

need more information to make any progress here.

**Comment by kittle31** [comment]
try this link: https://codesandbox.io/s/ov6v8rr05

If you look at the code, I pass 'tabIndex' to 3 input fields, 2 InputGroup and 1 DateInput
the tab order should be:
1) first name  (tabIndex = 1)
2) DOB (date picker)  (tabIndex  = 2)
3) last name  (tabIndex = 3)
instead the tab order is:  First, Last, DOB.   It seems like the tab index for date picker is being ignored.

**Comment by giladgray** [comment]
oh snap it is definitely not emitting the `tabIndex` in the DateInput. nice find.
