### ISSUE TITLE
Feature request: resizer component

### ISSUE THREAD

**Issue by dandv** [palantir/blueprint#3171]
I'm looking for an ExtJS and Webix alternative, and have just discovered Blueprint today. It looks very promising, and I've added it to the [list of UI component toolkits / ExtJS alternatives](https://stackoverflow.com/questions/200284/what-are-alternatives-to-extjs) I maintain on StackOverflow. Thanks!

One component that I haven't found yet is a resizer - making components draggable by a specific border. Here's [sample code](https://snippet.webix.com/basic) and a more [complex demo from Webix](https://docs.webix.com/samples/01_layout/06_header_resize.html).

Would it be useful to offer a general resizer component?

**Comment by cmslewis** [comment]
Hi @dandv, the resizer you describe looks a lot like another Palantir open-source project, React Mosaic:

![image](https://user-images.githubusercontent.com/443450/49060867-1bf93100-f1c4-11e8-9849-34e6c63a4bf9.png)


See a demo [here](https://palantir.github.io/react-mosaic/) and the GitHub repo [here](https://github.com/palantir/react-mosaic/). Would this suit your needs?

**Comment by giladgray** [comment]
such things exist in outside of blueprint and could easily be composed into it. we have not had a need for such a thing at Palantir yet.
