### ISSUE TITLE
QueryList activeItem does not change when query and items change on props

### ISSUE THREAD

**Issue by rhysbrettbowen** [palantir/blueprint#3179]
#### Environment

- __Package version(s)__: @blueprintjs/select:3.3.0
- __Browser and OS versions__: 

#### Steps to reproduce

1. have a QueryList and set the props for "query" and "items"
2. select an activeItem
3. change "query" and "items" props
4. use Enter key

#### Actual behavior

an item from the old items props will be chosen with the new query

#### Expected behavior

the new list of items will be used with the query

#### Possible solution

Issue is that `setQuery` is called here: https://github.com/rhysbrettbowen/blueprint/blob/develop/packages/select/src/components/query-list/queryList.tsx#L139

and the `setQuery` method looks at the current props - not the next props.

**Comment by giladgray** [comment]
@rhysbrettbowen hmm nice find! any bandwidth to submit a fix? 🙏

**Comment by rhysbrettbowen** [comment]
yep - working on a PR and test now.

**Comment by giladgray** [comment]
amazing!! 💯
