### ISSUE TITLE
About toast happened time in react life schedule?

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3181]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question
In the blueprint toaster examples, it can pop a toast after click the button. But, if in the redux flow, how to use it? Such as , I remove one item from a table list with async fetch api, there will be toast message for action success or fail depend on the async fetch result.

**Comment by giladgray** [comment]
@fachilles if you look at the example code you'll that the `onClick` simply triggers a `toaster.show()`, the imperative API for showing toasts. you can easily do the same thing in your async logic:

```ts
const toaster = Toaster.create(...)
// pseudocode ahead
asyncOperation().then(result => toaster.show(...))
```

**Comment by fachilles** [comment]
@giladgray Thanks
Yes, this is one way if the react app used the redux middleware like thunk. It could be called in callback function. But , if the react app used the saga middleware. I don't think it's right.  So, I resolved the scenario by passing a callback function to action, then do callback in the saga async function as follow code. Is it the appropriate or suggestion way?
Action code:
```
export function doDeleteMetricAction(params, callback) {
    return {
        type: DO_DELETE_METRIC,
        params,
        callback
    }
}
```

Saga code:
```
export function* doDeleteMetric(action) {
  let result = {}
  try {
    const response = yield call(deleteMetric, action.params);
    if (response) {
      result = response;
    }

    if (result === true) {
      yield put(doRequestMetricsAction({ pageNo: 1 }));
    }
  } catch (ex) {
    result.msg = ex;
  }

  //// Do callback function that passed by action.
  action.callback && typeof action.callback === "function" && action.callback(result);
  yield put(doneDeleteMetricAction(result));
}
```
