### ISSUE TITLE
The `%code-block` font-size prevents using anything but pixels

### ISSUE THREAD

**Issue by joelschou** [palantir/blueprint#3183]
#### Steps to reproduce

1. Set `$pt-font-size` to `1rem`
1. Compile
1. Get error.

#### Actual behavior

```
{ Error: Incompatible units: 'px' and 'rem'.
    at options.error (/.../node_modules/node-sass/lib/index.js:291:26)
  status: 1,
  file:
   '/.../node_modules/@blueprintjs/core/src/_typography.scss',
  line: 296,
  column: 14,
  message: 'Incompatible units: \'px\' and \'rem\'.',
  formatted:
   'Error: Incompatible units: \'px\' and \'rem\'.\n        on line 296 of node_modules/@blueprintjs/core/src/_typography.scss\n        from line 13 of node_modules/@blueprintjs/core/src/blueprint.scss\n        from line 6 of src/styles/_setup.scss\n        from line 1 of src/styles/index.paper.scss\n>>   font-size: $pt-font-size - 1px;\n\n   -------------^\n' }
```

#### Expected behavior

Font-size values shouldn't be limited to pixel measurements. I should be able to use rems or ems or pts or anything I want.

#### Possible solution

`font-size: $pt-font-size-small` or `font-size: calc( #{$pt-font-size} - 1px )` or something else altogether.

#### Add'l thoughts

Similar errors arise when the `$pt-grid-size` is set to non-pixel values. I haven't yet dug in to see if this can be overcome by setting other variables to the same measurement type as the grid size.

**Comment by giladgray** [comment]
@joelschou Blueprint was never designed to support non-px font sizes so i'm going to decline this request. it's just not a priority for us.
