### ISSUE TITLE
[DateRangePicker] Time input loses focus on keypress

### ISSUE THREAD

**Issue by yixunx** [palantir/blueprint#3185]
#### Environment

- __Package version(s)__: `@blueprintjs/core 3.9.0`, `@blueprintjs/datetime 3.4.0`
- __Browser and OS versions__: Chrome Version `70.0.3538.110 (Official Build) (64-bit)`, macOS High Sierra 10.13.6

#### Steps to reproduce

1. Open https://codesandbox.io/s/105080ojo3.
1. Focus on one of the time inputs at the bottom of the popup menu and press up/down

#### Actual behavior

1. The time input loses focus to one of the date inputs on the top.

#### Expected behavior

1. The focus should stay in the time input, allowing the time to be changed by pressing up/down consecutively.

**Comment by giladgray** [comment]
@yixunx ooh yeah that's a bug. the `DRI` focus behavior on date change is interfering with `TP`'s own desires. perhaps you've got some time to work on a fix?

**Comment by yixunx** [comment]
I can submit a patch this week or next.
