### ISSUE TITLE
Example for combining Tree and ContextMenu

### ISSUE THREAD

**Issue by volkandkaya** [palantir/blueprint#3187]
#### Question

It would be great to have an example of Tree and ContextMenu working together in the docs. Can't seem to get it working.

**Comment by giladgray** [comment]
sorry, we do not have bandwidth to build examples like this. i'd suggest sharing a codesandbox.

**Comment by giladgray** [comment]
also see #1725 which is also relevant to `ContextMenuTarget`: must be wrapped around a DOM node.

**Comment by clarson0** [comment]
@volkandkaya 

import * as React from "react";
import {
  Classes,
  ContextMenu,
  Icon,
  Menu,
  MenuDivider,
  MenuItem,
  Tree
} from "@blueprintjs/core";

export interface ExampleProps {
  header: string;
}

export class NewTree extends React.PureComponent<ExampleProps> {
  public showContextMenu(nodeData, path, e) {
    e.preventDefault();
    // invoke static API, getting coordinates from mouse event
    ContextMenu.show(
      <Menu>
        <MenuItem icon="search-around" text="Search around..." />
        <MenuItem icon="search" text="Object viewer" />
        <MenuItem icon="graph-remove" text="Remove" />
        <MenuItem icon="group-objects" text="Group" />
        <MenuDivider />
        <MenuItem disabled={true} text="Clicked on node" />
      </Menu>,
      { left: e.clientX, top: e.clientY }
    );
  };

  public render() {
    return (
      <Tree
        onNodeContextMenu={this.showContextMenu}
        contents={[
          {
            id: 0,
            hasCaret: true,
            icon: "folder-close",
            label: "Folder 0",
          }]}
      />
    );
  }
}

**Comment by SoulKa** [comment]
Is there any static ContextMenu2.show() in the new Popover2 library?

**Comment by adidahiya** [comment]
@SoulKa no, but I'm tracking that request here https://github.com/palantir/blueprint/issues/5527
