### ISSUE TITLE
inputRef is not set for NumericInput control.

### ISSUE THREAD

**Issue by erenbaydemir** [palantir/blueprint#3192]
#### Environment

- __Package version(s)__: 3.8.0
- __Browser and OS versions__: Chrome 70.0.3538.102, macOS 10.14.1

#### Steps to reproduce

1. Create a ref
2. Set the inputRef property of a NumericInput control with this ref
3. Check the current property of the ref on the page

#### Actual behavior

When you set the inputRef of a NumericInput control, the ref never gets set with the reference to the inner input element and stays null. When you change the control with an InputGroup and keep everything the same, inputRef is successfully set. 

#### Expected behavior

current property of the inputRef should reference the inner input element of the NumericInput control

**Comment by giladgray** [comment]
@erenbaydemir hah i actually just noticed something fishy with the relevant code and refactored it locally. will push that up!

**Comment by giladgray** [comment]
@erenbaydemir actually wait, i don't understand your repro. 

what do you mean when you say "Set the inputRef property of a NumericInput control with this ref?"
if you mean `inputRef="name"` then that usage is simply unsupported. we only support the callback usage.

**Comment by giladgray** [comment]
oh no i see you're using `React.createRef()`. this also doesn't work -- it is only supported on React's own `ref` props. you must use the simple callback syntax instead. if you were using typescript then this would have been an obvious compile error.

**Comment by giladgray** [comment]
see https://github.com/palantir/blueprint/issues/2949#issuecomment-422158461
