### ISSUE TITLE
HotKeys: using preventDefault prop never calls the keyUp handler

### ISSUE THREAD

**Issue by warpdesign** [palantir/blueprint#3196]
#### Environment

- __Package version(s)__: 3.6.1
- __Browser and OS versions__: macOS Mojave, Chrome 66.0.3359.181 (Electron)

#### Steps to reproduce

1. Add an hotkey with both onKeyDown and onKeyUp handlers and preventDefault prop set to true.

#### Actual behavior

Only the keyDown handler is called: the keyUp handler is never called.

#### Expected behavior

The keyUp handler should be called as well.

**Comment by giladgray** [comment]
i'm not sure this is solvable because it's built-in browser behavior--there's actually nothing a library can do. if you need both events then don't use `preventDefault`.
