### ISSUE TITLE
[Popover] Change default boundary to viewport?

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#3205]
I find myself adding the following popper modifiers to every single popover:
`<Popover modifiers={{ preventOverflow: { boundariesElement: "viewport" } }} />`

This allows the popover to escape the closest ancestor that is a scroll container. I have not yet seen a case where it's actually desired to stay within those containers.

Discuss!

**Comment by badams** [comment]
Also a fan of this, as I was initially confused by the behaviour of the popover when a containing element had `overflow:auto`

**Comment by adidahiya** [comment]
I believe `rootBoundary: "viewport"` is the default in popper.js v2, so this should be solved in v4 when Popover2 becomes Popover. See https://popper.js.org/docs/v2/utils/detect-overflow/#rootboundary
