### ISSUE TITLE
custom Intent

### ISSUE THREAD

**Issue by dixitk13** [palantir/blueprint#3221]
#### Environment

- __Package version(s)__: 3.9.0
- __Browser and OS versions__: Version 71.0.3578.80 (Official Build) (64-bit), MacOS 10.14.1

#### Feature request

Custom Intent: 
Currently blueprint offers 5 Intents, viz {DANGER, NONE, PRIMARY, SUCCESS, WARNING}

Requesting custom Intent variation where we can write colors in SCSS to define new Intent.  Technically this would be implemented outside the blueprint repository, inheritance stays within blueprint.  

##### Consider the below code changes

Assuming, there's only the above three files which determine the Custom Intent. Offer some Inheritance magic to the below helper functions making it easier for defining custom intents. 

Hypothetically: 

- CustomIntent/CustomIntent.ts
```
...
export const CustomIntent = {
    BLACK: "black" as "black",
    GRAY: "gray" as "gray"
};
export type CustomIntent = typeof CustomIntent[keyof typeof CustomIntent];
...
```

- CustomIntent/_custom-color-aliases.scss
```
...
$custom-intent-black: #182026 !default;
$custom-intent-gray: #ced9e0 !default;
...
```

- CustomIntent/classes.ts

```

...
const CNS = "custom";

...
export const INTENT_BLACK = intentClass(CustomIntent.BLACK);
export const INTENT_GRAY = intentClass(CustomIntent.GRAY);
...
export function customIntentClass(intent?: Intent) {
    if (intent == null || intent === Intent.NONE) {
        return undefined;
    }
    return `${CNS}-intent-${intent.toLowerCase()}`;
}
...
```
and an index.js ofcourse for the exports

#### Examples
Usage be like 
```
import { EditableText } from "@blueprintjs/core";
import { CustomIntent } from "./customIntent";
...
...
  <EditableText
     intent={CustomIntent.BLACK}
  />
...
...
```

**Comment by giladgray** [comment]
@dixitk13 use `className` to apply custom scss to an element, which is supported on every component. Custom intents make type safety much more difficult, but this is already solved with the CSS class you've already written.

**Comment by giladgray** [comment]
you can use our sass mixins in your own sass code by `@import`ing their src files. that'll give you a classname that will work much better. (this is why we ship the `/src` directory in the npm packages.)
