### ISSUE TITLE
Popover on position fixed element in wrong place

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#3224]
Hey there,

I have the following code: 
```js
                              <Tooltip
                                  // usePortal={false}

                                    position="left"
                                    content="Minimize Tab"
                                  >
                                    <Button
                                      style={{
                                        zIndex: 15002,
                                        position: "fixed",
                                        top: 15,
                                        right: 25
                                      }}
                                      minimal
                                      icon="minimize"
                                      onClick={() => {
                                        togglePanelFullScreen(activePanelId);
                                      }}
                                    />
                                  </Tooltip>
```

that is producing this strange looking behavoir: 
![image](https://user-images.githubusercontent.com/2730609/49781930-56d18d80-fcc9-11e8-941c-44f440dff462.png)

I'm hovering the button in the top right but the popover is coming up in the middle of the screen. I tried using `usePortal=false` but that doesn't seem to help. 

Any ideas? 

Thanks!

**Comment by giladgray** [comment]
@tnrich play with the `boundary` prop, specifically `boundary="viewport"`. usually solves all problems.

**Comment by tnrich** [comment]
Thanks I'll try that out. I found that wrapping the popover-wrapped element
in a div that is fixed position fixed the problem.

**Comment by giladgray** [comment]
Yes sure. That would work for the reason as boundary prop: it affects
Popper's logic for determining scroll parent.

**Comment by giladgray** [comment]
@tnrich any luck?

**Comment by leif-freshx** [comment]
> @tnrich play with the `boundary` prop, specifically `boundary="viewport"`. usually solves all problems.

Thank you very much! I have been trying things for days without effect and when using the boundary={ "viewport" } it solved it perfectly. Thanks for the tip!

**Comment by colinmegill** [comment]
I hit this on an element with `Position.RIGHT` that was rendering on the left side. Adding this property solved it even though overflow was set:

```
            modifiers={{
              preventOverflow: { enabled: false },
              hide: { enabled: false },
            }}
```

**Comment by giladgray** [comment]
@colinmegill that sounds like a case for `boundary="viewport"`. if your popover flips unexpectedly, try changing the boundary before you disable modifiers 🤷‍♂️
