### ISSUE TITLE
Is there any way to copy the cell inside value directly?

### ISSUE THREAD

**Issue by fachilles** [palantir/blueprint#3226]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question
In Table component, is there a way to copy the cell inside value directly? The example code show how to copy the cell inside value by add the bodyContextMenuRenderer to Table component. It's terrible interactive. It should show a right-click menu in every cell. So there is a simple way to get the cell inside value?
![image](https://user-images.githubusercontent.com/3346188/49851058-d4f17980-fe1a-11e8-8f7a-7098cd8b253c.png)

**Comment by giladgray** [comment]
Pretty sure there's a whole copy interface to support cmd-c. I'm not at a
computer so can't point you to the docs, but go read them again.

**Comment by giladgray** [comment]
Ah it's called `getCellClipboardData` on Table itself
