### ISSUE TITLE
Not possible to use dark theme with ContextMenu

### ISSUE THREAD

**Issue by lyptt** [palantir/blueprint#3229]
#### Environment

- __Package version(s)__: 
"@blueprintjs/core": "^3.10.0"
"react": "^16.6.3"
- __Browser and OS versions__: 
Any, any

#### Steps to reproduce

Display a ContextMenu like so:

```jsx
    const menu = (
      <Menu className='bp3-dark'>
        <MenuItem  ...  />
        <MenuDivider />
      </Menu>
    )
    ContextMenu.show(menu, { left: e.clientX, top: e.clientY })
```

#### Actual behavior

The displayed Menu remains light

#### Expected behavior

The displayed Menu is dark, as a result of applying the bp3-dark theme

#### Possible solution

It looks like the CSS class is one level too deep, it should be applied to the generated div one level higher with the class `bp3-popover-content`, but I have no access to this via the ContextMenu. Potentially you could support supplying className to the generated popover via ContextMenu itself.

**Comment by TomFaulkner** [comment]
This seems to be the case for the Tabs component as well.

**Comment by adidahiya** [comment]
there is actually an additional parameter on `ContextMenu.show`, `isDarkTheme?: boolean`: https://github.com/palantir/blueprint/blob/d8b247a72f25335e70151fbfaf638e5825f29856/packages/core/src/components/context-menu/contextMenu.tsx#L124

so you can manually make it a dark menu. the popover will also try to detect if it is in a dark theme DOM subtree, as shown in the context menu example in the docs.

**Comment by giladgray** [comment]
@TomFaulkner for `Tabs` you can simply slap `Classes.DARK` on it. this works for all non-overlay components. overlays require special attention as they typically use portals which breaks the CSS cascade.
