### ISSUE TITLE
I can't move slider

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#3231]
Hi.

Please checkout below code. Why i can't move slider?

```
import * as React from "react";
import { Slider} from "@blueprintjs/core";

import "@blueprintjs/core/lib/css/blueprint.css"
import "@blueprintjs/icons/lib/css/blueprint-icons.css"

export default class SliderExample extends React.PureComponent {
    render() {

        return (
                <Slider
                    min={0}
                    max={10}
                    stepSize={0.1}
                    labelStepSize={10}
                    value={0.5}
                />
                
        );
    }

}

```

Thanks.

**Comment by giladgray** [comment]
@spider58 this is expected. you are controlling the `value` but not providing `onChange` to update that value. this slider will never move. 

this is a basic react concept: https://reactjs.org/docs/forms.html#controlled-components

**Comment by giladgray** [comment]
Slider does not support "uncontrolled" usage so you must provide `onChange` for it to be useful.

**Comment by spider58** [comment]
Thanks for answer. I tried with a state it's worked.

But i'm not using state for value, I have a datagrid which has many rows and each rows has a slider column. i must define slider values from datagrid data.

i tried below code in array.map

```
 <Slider
                    min={0}
                    max={10}
                    stepSize={0.1}
                    labelStepSize={10}
                    value={row.sliderValue}
  		    onChange={(value) =>row.sliderValue = value}
                />
```
Still can't move. 

I can't define static slider and state for each row. Data count is dynamic.

**Comment by giladgray** [comment]
sorry, this is how the component works. you should refactor your code to make better use of state.
