### ISSUE TITLE
Nested Tables

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#3238]
Hi

Can we create a nested datatable ? Please look at below image

https://www.codeproject.com/KB/webforms/EditNestedDataGrid/EditNestedGridView.JPG

**Comment by jaamison** [comment]
This can easily be accomplished with the HTMLTable component (or with vanilla HTML tables for that matter)

**Comment by giladgray** [comment]
@spider58 the `@blueprintjs/table` package does not support this. @jaamison is right to point you to `HTMLTable` for simple table support, where this can definitely be achieved. you could nest a table in another table's `tr`.

**Comment by havesomeleeway** [comment]
Popping in on this, would I be able to use the `<Collapse/>` component with the nested table's `tr`?
