### ISSUE TITLE
Sample code for PanelStack using wrong variant of setState 

### ISSUE THREAD

**Issue by ChristianIvicevic** [palantir/blueprint#3242]
While reading through the new sample code for the PanelStack component I noticed multiple calls to `setState` which seem to be wrong:

https://github.com/palantir/blueprint/blob/f29ca793ed533ac7a98cf25b9559685782ab8022/packages/docs-app/src/examples/core-examples/panelStackExample.tsx#L49

https://github.com/palantir/blueprint/blob/f29ca793ed533ac7a98cf25b9559685782ab8022/packages/docs-app/src/examples/core-examples/panelStackExample.tsx#L55

If you need the current value of `state` while processing `setState` you should use the overload `setState(previousState => ({/* ... */}))` since the actual change of the state is not immediate.

**Comment by giladgray** [comment]
@ChristianIvicevic ah good catch. I suppose the current impl doesn't explode because these handlers are only called in response to user events, which happen rarely (not more than once per frame), but your proposal is the best practice. 

mind submitting a PR? ⭐️

**Comment by ChristianIvicevic** [comment]
@giladgray Will do it later this weekend ⭐️
