### ISSUE TITLE
Selection gets set to first after filtering

### ISSUE THREAD

**Issue by Sktank** [palantir/blueprint#3243]
#### Environment

- __Package version(s)__: 3.3.0
- __Browser and OS versions__: Chrome

#### Steps to reproduce

Make a selection, type anything in the filter box.

![2018-12-14 15 16 40](https://user-images.githubusercontent.com/1815469/50025508-cee2d080-ffb3-11e8-9e0a-7982464c2601.gif)

#### Actual behavior

Active list entry as denoted by the blue highlight will get set to the first element in list.

#### Expected behavior

Active list entry should remain the currently selected item

**Comment by giladgray** [comment]
@Sktank this is expected. see the various `resestOn*` props, especially `resetOnSelect`.

**Comment by Sktank** [comment]
@giladgray - What I would prefer is that the active selection is always pt-active in the dropdown menu, regardless of query string.  Do you know if this is possible with the current props? I'm not able to get this functionality even when playing with the props on https://blueprintjs.com/docs/#select/select-component

**Comment by giladgray** [comment]
@Sktank use `activeItem` prop to control the blue one.

**Comment by Sktank** [comment]
@giladgray - thanks for the help
