### ISSUE TITLE
Dialog close button is not properly styled

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#3245]
#### Environment

- __Package version(s)__: 3.9.0
- __Browser and OS versions__: Chrome, OS X

#### Steps to reproduce

1. Navigate to the Dialog example on the Blueprint documentation site ([link](https://blueprintjs.com/docs/#core/components/dialog.css)).

#### Actual behavior

Dialog close button is not properly styled.

![image](https://user-images.githubusercontent.com/443450/50036364-4a954b00-ffbd-11e8-8b18-0f88ceacea3b.png)

#### Expected behavior

Dialog close button looks like a minimal `Button`.

![2018-12-14 16 28 44](https://user-images.githubusercontent.com/443450/50036373-58e36700-ffbd-11e8-9305-0dd45944f1bb.gif)

#### Possible solution

Looks like adding `bp3-button` and `bp3-minimal` does the trick.

**Comment by giladgray** [comment]
@cmslewis oof that's old code running against newer styles. upgrade blueprint in the package that renders the original dialog. this was changed in #2964.
