### ISSUE TITLE
Can I forbid hotkey "shift + ?" to show dialog

### ISSUE THREAD

**Issue by MrMengJ** [palantir/blueprint#3246]
I doesn't need the feature. Can I forbid it?Thank you!

**Comment by giladgray** [comment]
nope sorry it's always on.

**Comment by giladgray** [comment]
for clarity: there's currently no way to customize or disable this feature. see #1028, #3135, #1590

**Comment by warpdesign** [comment]
I think it can be forbidden by adding a listener for the keydown even in capture mode, and stopping the event from propagating.

**Comment by tnrich** [comment]
@warpdesign where should that listener be? Can you post some example code?

**Comment by warpdesign** [comment]
I'm doing something like that:

```jsx
const onKeyDown = (e) => {
  if (e.which === 191 && e.shiftKey) {
    e.stopPropagation();
    e.stopImmediatePropagation();
    e.preventDefault();
  }
}
addEventListener('keydown', onKeyDown, true)
```

see: https://github.com/warpdesign/react-explorer/blob/master/src/components/App.tsx
