### ISSUE TITLE
Popover throws TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by VincentNewkirk** [palantir/blueprint#3254]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "^3.7.0",
- __Browser and OS versions__:
Chrome Version 71.0.3578.98 (Official Build) (64-bit).
Mac OS X El Capitan Version 10.11.6

#### Question
After migrating to Blueprint version 3, we experience this error everywhere we render a popper on click. Meaning this fires only on the click event which opens the Popover.

![image](https://user-images.githubusercontent.com/18303749/50323551-84b29f80-051d-11e9-8581-4a61e538d012.png)

I see that this errors inside of the ```popover``` component itself. Checking the source code, ```popover``` is using ```react-popper```. I have checked their Github issues thread and found nothing there.

Here is a simplified version of a common way we implement Popover:
```
<div className='common-filters__filters show-if-mid'>
  <Popover
     autoFocus={false}
     popoverClassName='common-filters__sub-filters-popover'
     position={Position.BOTTOM_RIGHT}
  >
    <div className='common-filters__collapsed-filters-opener'>
      <i className='icon icon-cross2' />
      <i className='icon icon-three-bars' />
    </div>
    <div className='common-filters__filters common-filters__sub-filters'>
       { ...more components }
     </div>
  </Popover>
</div>
```

**Comment by giladgray** [comment]
@VincentNewkirk what version of React are you using?

**Comment by giladgray** [comment]
@VincentNewkirk can you also share versions of popper.js and react-popper?

**Comment by VincentNewkirk** [comment]
React: 16.3.1
react-popper: 1.3.2
popper.js: 1.14.6

**Comment by VincentNewkirk** [comment]
You're absolutely right. After investigation it seems we had a conflicting instance of React.
I'm not completely sure, but it seems it might be related to this known issue with Yarn:
https://github.com/yarnpkg/yarn/issues/3967

If anyone runs into this problem, I solved it by deleted my node_modules and running ```npm install```. Not ```yarn install```.
