### ISSUE TITLE
Unexpected Character '' on import using NextJs

### ISSUE THREAD

**Issue by blujedis** [palantir/blueprint#3257]
#### Environment

- __Package version(s)__: 3.10.0
- __Browser and OS versions__: Mojave (10.14.2) Chrome (71.0.3578.98)
-__Node 8.11.4
-__NPM 6.5.0
-__Next 7.0.2

#### Question

Having issue with import. I'm already importing normalize.css using "~" so I'm confident webpack is unwinding that to the full node_modules path. 

However mini-css-extract-plugin complains about -->  Unexpected Character ''

I'm building this using NextJs but as I said all other modules are building fine so I suspect there's something up with the blueprint in that perhaps there's some build process it's expecting in Webpack's loaders.

For good measure I tried importing the .scss directly which failed as well in that it wasn't able to find "../../resources" among other packages. I could probably monkey with tsconfig and babel's module-resolver to make that all work but seems like too much cost.

What am I missing here? Thanks :)

**Comment by adidahiya** [comment]
@blujedis can you post the full console output?
