### ISSUE TITLE
Menu scrolling in the documentation is janky/jittery/slow

### ISSUE THREAD

**Issue by balupton** [palantir/blueprint#3261]
#### Environment

- __Package version(s)__: whatever is on the documentation site
- __Browser and OS versions__: Safari Version 12.0.2 (14606.3.4),  MacOS 10.14.2 (18C54)

#### Steps to reproduce

https://blueprintjs.com/docs/#blueprint

scroll the menu on the left via safari on macos, or safari on ios

#### Actual behavior

- mac: https://youtu.be/NjOkVz4aAvM
- ios: https://twitter.com/balupton/status/1078444496231194625

#### Expected behavior

be smooth as butter

#### Possible solution

no idea

**Comment by adidahiya** [comment]
it's pretty smooth on my machine. do you have any performance profiles to share? that might help debug the issue.

**Comment by balupton** [comment]
No I do not. Only those videos. However I find this is very common among react apps and components.

**Comment by adidahiya** [comment]
ok, unfortunately that doesn't leave much for me to go forward with this issue. I'll reopen if other Blueprint users have similar complaints or more specific performance problems.
