### ISSUE TITLE
Blueprint Starter Kit: Cannot read property '__extends' of undefined

### ISSUE THREAD

**Issue by dylanswartz** [palantir/blueprint#3262]
#### Environment

- __Package version(s)__: 
```
    classnames@^2.2
    dom4@^1.8
    react@^16.2.0/umd/react.production.min.js
    react-dom@^16.2.0/umd/react-dom.production.min.js
    react-transition-group@^2.2.1/dist/react-transition-group.min.js
    popper.js@^1.14.1/dist/umd/popper.js
    react-popper@^1.0.0/dist/index.umd.min.js
    @blueprintjs/core@^3.0.0
    @blueprintjs/icons@^3.0.0
```
- __Browser and OS versions__: 
Chrome Browser: Version 71.0.3578.98 (Official Build) (64-bit)
Mac OS 10.13.1

#### Steps to reproduce

1. Head to blueprint getting started docs: 
https://blueprintjs.com/docs/#blueprint/getting-started
2. Copy paste the example under CDN consumption into an index.html file
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Blueprint Starter Kit</title>
    <link href="https://unpkg.com/normalize.css@^7.0.0" rel="stylesheet" />
    <link href="https://unpkg.com/@blueprintjs/core@^3.0.0/lib/css/blueprint.css" rel="stylesheet" />
    <link href="https://unpkg.com/@blueprintjs/icons@^3.0.0/lib/css/blueprint-icons.css" rel="stylesheet" />
  </head>
  <body>
    <script src="https://unpkg.com/classnames@^2.2"></script> 
    <script src="https://unpkg.com/dom4@^1.8"></script> 
    <script src="https://unpkg.com/react@^16.2.0/umd/react.production.min.js"></script> 
    <script src="https://unpkg.com/react-dom@^16.2.0/umd/react-dom.production.min.js"></script> 
    <script src="https://unpkg.com/react-transition-group@^2.2.1/dist/react-transition-group.min.js"></script> 
    <script src="https://unpkg.com/popper.js@^1.14.1/dist/umd/popper.js"></script> 
    <script src="https://unpkg.com/react-popper@^1.0.0/dist/index.umd.min.js"></script> 
    <script src="https://unpkg.com/@blueprintjs/core@^3.0.0"></script> 
    <script src="https://unpkg.com/@blueprintjs/icons@^3.0.0"></script> 
 
    <div id="btn"></div>
    <script>
      const button = React.createElement(Blueprint.Core.Button, {
        icon: "cloud",
        text: "CDN Blueprint is go!",
      });
      ReactDOM.render(button, document.querySelector("#btn"));
    </script> 
  </body>
</html>
```
3. Open index.html file in chrome or run in a local server like `serve` 
4. Observe the following exception in the console:
```
core.bundle.js:1 Uncaught TypeError: Cannot read property '__extends' of undefined
    at core.bundle.js:1
    at Object.<anonymous> (core.bundle.js:1)
    at n (core.bundle.js:1)
    at Object.<anonymous> (core.bundle.js:1)
    at n (core.bundle.js:1)
    at core.bundle.js:1
    at core.bundle.js:1
    at core.bundle.js:1
    at core.bundle.js:1
```

#### Actual behavior

The example Blueprint Quick Start for CDN consumption does not work. An exception is thrown in the console and no button renders on the screen. 

#### Expected behavior

Running the Example Blueprint Quick Start in the browser should render a button and not throw exceptions.

#### Possible solution

I'm not sure. Seems like perhaps some dependency is missing 🤷‍♂️

**Comment by giladgray** [comment]
@dylanswartz you are likely missing `tslib`, one of the declared dependencies.

**Comment by giladgray** [comment]
can you confirm this ⬆️? may need to add another script tag to that example.

**Comment by dylanswartz** [comment]
Tried adding: 
`<script src="https://unpkg.com/tslib@^1.9.3"></script>`

Seem to still get the same error.

**Comment by giladgray** [comment]
ah hmm yup this is real! the example file does not work. just opened #3276 to fix.

**Comment by dylanswartz** [comment]
Thanks @giladgray! Sorry for not replying seem to miss github notifications

**Comment by llchan** [comment]
Are we sure this is fixed? I copied the example and I'm still seeing the same `__extends` error. Also the  `react-transition-group.min.js` filename might need to be updated to `react-transition-group.js`.

**Comment by giladgray** [comment]
Hasn't been deployed yet. Code just merged.

**Comment by llchan** [comment]
Oh, maybe you mean that a new blueprint bundle needs to be built and propagated to unpkg for it to work via CDN, not just that the docs/examples need to be updated. If that's the case I'll wait for the next release.

**Comment by giladgray** [comment]
@llchan release was published late last week. check again!

**Comment by llchan** [comment]
Blueprint stuff looks good now, thanks! Btw I think react-transition-group.min.js still needs to be pointed to the unminified versions, but that's a diffferent issue.
