### ISSUE TITLE
The Style of DateTimeInput is Incorrect 

### ISSUE THREAD

**Issue by longxiutmm** [palantir/blueprint#3263]
#### Environment

    "@blueprintjs/core": "^3.10.0",
    "@blueprintjs/datetime": "^3.5.0",
    "@blueprintjs/select": "^3.4.0",

#### Actual behavior

 
![123](https://user-images.githubusercontent.com/19338062/50532959-1e9ccc80-0b5c-11e9-8149-e011af808080.jpg)

**Comment by giladgray** [comment]
this looks correct to me, except for the arrows in the year/month. is that what you're talking about @longxiutmm?

**Comment by longxiutmm** [comment]
yes . 
the arrow's position  is Incorrect when I use 'moment/locale/zh-cn'.
If i  use default language . this position is correct.

**Comment by longxiutmm** [comment]
There is my code.
`
import React from 'react';
import { DateInput, IDateFormatProps, } from "@blueprintjs/datetime";
import moment from "moment";
import 'moment/locale/zh-cn';
import 'moment/locale/de';
import MomentLocaleUtils from 'react-day-picker/moment';

const dateTimeFormat = "YYYY-MM-DD hh:mm";

const dateTimeProps={
    formatDate: (date) => moment(date).format(dateTimeFormat),
    parseDate: (str) => moment(str, dateTimeFormat).toDate(),
    locale:'zh-cn',
    //locale:'en',
    localeUtils:MomentLocaleUtils,
    reverseMonthAndYearMenus:true,
    showActionsBar:true,
    timePrecision:'minute',
    todayButtonText:'此时',
    clearButtonText:'清除'
};




export default class DateTimeInput extends React.Component{
    render(){
        let {value,onChange,maxValue,minValue} = this.props;

        if(!maxValue){
            maxValue = new Date();
        }
        if(!minValue){
            minValue = new Date(0);
        }

       return( <DateInput {...dateTimeProps} maxDate={new Date()} value={value} onChange={onChange} minDate={minValue} maxDate={maxValue}/>);
    }
}
`

**Comment by longxiutmm** [comment]
there is my code.
`
import React from 'react';
import { DateInput, IDateFormatProps, } from "@blueprintjs/datetime";
import moment from "moment";
import 'moment/locale/zh-cn';
import 'moment/locale/de';
import MomentLocaleUtils from 'react-day-picker/moment';

const dateTimeFormat = "YYYY-MM-DD hh:mm";

const dateTimeProps={
    formatDate: (date) => moment(date).format(dateTimeFormat),
    parseDate: (str) => moment(str, dateTimeFormat).toDate(),
    locale:'zh-cn',
    //locale:'en',
    localeUtils:MomentLocaleUtils,
    reverseMonthAndYearMenus:true,
    showActionsBar:true,
    timePrecision:'minute',
    todayButtonText:'此时',
    clearButtonText:'清除'
};




export default class DateTimeInput extends React.Component{
    render(){
        let {value,onChange,maxValue,minValue} = this.props;

        if(!maxValue){
            maxValue = new Date();
        }
        if(!minValue){
            minValue = new Date(0);
        }

       return( <DateInput {...dateTimeProps} maxDate={new Date()} value={value} onChange={onChange} minDate={minValue} maxDate={maxValue}/>);
    }
}

`

**Comment by longxiutmm** [comment]
there is my code.
`import React from 'react';
import { DateInput, IDateFormatProps, } from "@blueprintjs/datetime";
import moment from "moment";
import 'moment/locale/zh-cn';
import 'moment/locale/de';
import MomentLocaleUtils from 'react-day-picker/moment';

const dateTimeFormat = "YYYY-MM-DD hh:mm";

const dateTimeProps={
    formatDate: (date) => moment(date).format(dateTimeFormat),
    parseDate: (str) => moment(str, dateTimeFormat).toDate(),
    locale:'zh-cn',
    //locale:'en',
    localeUtils:MomentLocaleUtils,
    reverseMonthAndYearMenus:true,
    showActionsBar:true,
    timePrecision:'minute',
    todayButtonText:'此时',
    clearButtonText:'清除'
};




export default class DateTimeInput extends React.Component{
    render(){
        let {value,onChange,maxValue,minValue} = this.props;

        if(!maxValue){
            maxValue = new Date();
        }
        if(!minValue){
            minValue = new Date(0);
        }

       return( <DateInput {...dateTimeProps} maxDate={new Date()} value={value} onChange={onChange} minDate={minValue} maxDate={maxValue}/>);
    }
}`

**Comment by longxiutmm** [comment]
there is my code.

import React from 'react';
import { DateInput, IDateFormatProps, } from "@blueprintjs/datetime";
import moment from "moment";
import 'moment/locale/zh-cn';
import 'moment/locale/de';
import MomentLocaleUtils from 'react-day-picker/moment';

const dateTimeFormat = "YYYY-MM-DD hh:mm";

const dateTimeProps={
    formatDate: (date) => moment(date).format(dateTimeFormat),
    parseDate: (str) => moment(str, dateTimeFormat).toDate(),
    locale:'zh-cn',
    //locale:'en',
    localeUtils:MomentLocaleUtils,
    reverseMonthAndYearMenus:true,
    showActionsBar:true,
    timePrecision:'minute',
    todayButtonText:'此时',
    clearButtonText:'清除'
};




export default class DateTimeInput extends React.Component{
    render(){
        let {value,onChange,maxValue,minValue} = this.props;

        if(!maxValue){
            maxValue = new Date();
        }
        if(!minValue){
            minValue = new Date(0);
        }

       return( <DateInput {...dateTimeProps} maxDate={new Date()} value={value} onChange={onChange} minDate={minValue} maxDate={maxValue}/>);
    }
}

**Comment by longxiutmm** [comment]
@giladgray please recheck this problem.

**Comment by jez321** [comment]
Just leaving a note that we are seeing a similar thing when reverseMonthAndYearMenus is true, I might see if I can have a look into it further but for now we are using the following CSS as a workaround
`.bp3-datepicker-month-select .bp3-icon-double-caret-vertical {
          right: 0 !important;
      }`
