### ISSUE TITLE
Disable a `suggest`

### ISSUE THREAD

**Issue by colinmegill** [palantir/blueprint#3270]
#### Environment

- __Package version(s)__: 

React 16.6.0
Blueprint 3.8.0
Blueprint select 3.2.1

- __Browser and OS versions__: 

MacOS Mojave, Chrome 70

#### Question

Probably missing something, but I'm not sure of the best way to disable a `suggest`. 

Looking here: https://blueprintjs.com/docs/#select/suggest 

Happy path? Or, if not, this is a feature request.

**Comment by colinmegill** [comment]
Fwiw, this does work: 

`itemDisabled={condition ? () => true : () => false}` 

But I wouldn't describe it as the least surprising thing from either the programmer or user perspective, so inquiring :)

**Comment by giladgray** [comment]
related to #2467. not trivially supported. you can use `itemDisabled` for disabling items or play with `inputProps.disabled`.

**Comment by colinmegill** [comment]
Thanks for prioritizing & working on this one
