### ISSUE TITLE
Update FAQ?

### ISSUE THREAD

**Issue by joehillen** [palantir/blueprint#3272]
I was just evaluating blueprint for use in a project as an alternative to Material UI. It looks like some parts of the FAQ haven't been updated since 2016.

Has any of this changed in the last 2 years? https://github.com/palantir/blueprint/wiki/Frequently-Asked-Questions

**Comment by giladgray** [comment]
@joehillen hey thanks for reading that, i guess! the content actually seems accurate to this day. sure, there are some 2016-era references (css-in-js tooling is much better), but it's all still basically correct.

i would rather delete that page than update it. faqs are rarely helpful, and all that info lives separately on the docs site where it belongs.
