### ISSUE TITLE
Can one preserve row selection across data updates in Blueprint Table?

### ISSUE THREAD

**Issue by mdanka** [palantir/blueprint#328]
Column headers have both keys and selection properties, making it easy to preserve column selection when data gets updated. However, I don't see such properties for rows or for general selection.

For example, let's say I have a table representing a histogram, with two columns, Value and Count:

    Selected? Value Count
    --------- ----- -----
    x         A     1
    x         B     3
              C     2

Now my data updates, and row B disappears, and C and A swap order. I would like to preserve selection as the following:

    Selected? Value Count
    --------- ----- -----
              C     2
    x         A     1

Is this possible to do?

**Comment by adidahiya** [comment]
You should be able to do this with fully controllable table selection added in v1.2 (#253). Let us know if this API isn't sufficient to meet your use case.
