### ISSUE TITLE
Dialogs:Esc key closed the two dialog

### ISSUE THREAD

**Issue by meiguanxiHXX** [palantir/blueprint#3280]
I had try put a new dialog in the dialog,I wish only close the new dialog  when I fisrt press ESC key,maybe next press will close the old dialog. In fact, I did this it closed all dialog. 
any help? thank you!

**Comment by tgreen7** [comment]
@meiguanxiHXX You can add ```e.stopPropagation()``` to the inner dialog close so that the close event will not hit the outer dialog.

Check out this fiddle for an example: https://codesandbox.io/s/xll8q8v7mp

**Comment by tnrich** [comment]
@tgreen7 what about if the inner dialog has canEscapeKeyClose={false} but the first dialog does not.. How do we stop propagation in that case? 

Thanks in advance!

https://codesandbox.io/s/blueprintjs-playground-forked-pqqd74

**Comment by tnrich** [comment]
@tgreen7 answering my own question - I think to do that means manually catching the esc key event and preventing dialog close:

https://codesandbox.io/s/blueprintjs-playground-forked-5onri8?file=/App.js

**Comment by adidahiya** [comment]
I think you may be able to implement a "stop propagation" boundary for the inner Dialog with the new feature we just added to Portal & overlayable components: https://github.com/palantir/blueprint/pull/6093 (to be released this week).

```tsx
<Dialog stopPropagationEvents={["keyDown", "keyUp"]}>
```

(it's unlikely to be backported to Blueprint v3.x, though, as I see that's being used in @tnrich's code sandbox link)
