### ISSUE TITLE
Is there a way to download all of your icons at one time?

### ISSUE THREAD

**Issue by edelstone** [palantir/blueprint#3284]
#### Environment

- __Package version(s)__: N/A
- __Browser and OS versions__: N/A

#### Question

I'm trying to download your icon set for use in Sketch/IconJar.

I see PR's like this in the recent past (https://github.com/palantir/blueprint/pull/2614) but I still don't see any way to download the SVGs in bulk from the documentation website, via right-click menu or any other method.

Is it possible to download them all at one time?

**Comment by adidahiya** [comment]
they're right here in this repo: https://github.com/palantir/blueprint/tree/develop/resources/icons

**Comment by edelstone** [comment]
OK, no problem, just go to the home page and download the whole repo. Not sure why I didn't think of that. Thanks again @adidahiya!
