### ISSUE TITLE
Is there anyway to support scrollable for tab

### ISSUE THREAD

**Issue by tomzaku** [palantir/blueprint#3298]
#### Environment

"@blueprintjs/core": "^3.10.0",

#### Question

![image](https://user-images.githubusercontent.com/19413272/51451172-9d091a80-1d66-11e9-8f30-8297e391c324.png)

or 
![image](https://user-images.githubusercontent.com/19413272/51451276-27ea1500-1d67-11e9-813d-4e175ba59744.png)
My tabs contains a lot of children, so I would like to scroll the tab or dropdown menu like Chrome Debug

**Comment by havesomeleeway** [comment]
@tomzaku Wanted to raise this here instead of creating another issue. Do you by any chance know how to route from the tab?

I have tried wrapping my tab with a `<NavLink><Tab/><NavLink/>`but it doesnt work.

**Comment by giladgray** [comment]
@havesomeleeway try `<Tab title={<NavLink ... />} />`
