### ISSUE TITLE
How to overwrite css of Components

### ISSUE THREAD

**Issue by havesomeleeway** [palantir/blueprint#3302]
#### Environment

Package version(s): 
"@blueprintjs/core": "^3.11.0",
Browser and OS versions: 
Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
OS: Mojave 10.14.2

#### Question

I currently have a `<NavigationMenu />` component that goes something like this:

```js
import React from "react";
import {Menu } from "@blueprintjs/core";

const NavigationMenu = () => {
    return (
        <Menu>
            <Menu.Item/>
           <Menu.Item/>
           <Menu.Item/>
           <Menu.Item/>
        </Menu>
    )
};

export default NavigationMenu
```

This component is passed into a bigger component that renders my Dashboard's content:

```js
const DashboardContent = () => {
    return (
        <div className="layout__wrapper">
        <div className="layout__body">
        <div className="layout__body--inner">
            <div className="layout__aside">
                <div className="layout__body-logo">
                    <img src={companyLogo} alt="logo"/>
                </div>
                <Divider/>
        <NavigationMenu />
            </div>
            <div className="layout__main">
                <div className="layout__main-navbar">
                <NavBar/>
                </div>
                <div className="layout__main-content">
                    <div>
                        Hello welcome!
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    )
};

export default DashboardContent
```

It would look something like this when <DashboardContent /> renders
![screenshot 2019-01-21 at 7 37 56 pm](https://user-images.githubusercontent.com/25948209/51472322-1418d000-1db4-11e9-90e4-08e6fae26417.png)

What im trying to achieve is to change the background of `<Menu>` so that it matches the sidebar i.e. `<div className="layout__aside">`

How can I do this? 
___

What i've tried so far unsuccessfully was to add a `className` to my  `<Menu>`,  
Eg: `<Menu className="Sidebar__menu">`
Needless to say, it failed. 

I looked at the documentations and it suggested that `Classes` can be used. However, im not sure how it works.

```
// use Classes constants for forward-compatible custom elements.
import { Classes } from "@blueprintjs/core"
<a className={Classes.MENU_ITEM}>custom menu item</a>
```

**Comment by giladgray** [comment]
@havesomeleeway a custom class applied via `className` is the correct approach here.

in this case the background color comes from `MenuItem`, not from `Menu`. so you've gotta be sure you're applying a class to the _correct component_.

**Comment by havesomeleeway** [comment]
@giladgray Thanks. I'll give it a shot in specifying the order that which my css is loaded. I must have it setup wrong because a `className` on my `Menu` failed to change the CSS.

**Comment by havesomeleeway** [comment]
@giladgray the other question I have is, under what circumstances would it be logical to use `Classes`? 

```js
// use Classes constants for forward-compatible custom elements.
import { Classes } from "@blueprintjs/core"
<a className={Classes.MENU_ITEM}>custom menu item</a>
```

**Comment by giladgray** [comment]
@havesomeleeway use `Classes` when you need to render your own markup but want our styles, or for some css-only APIs like `Classes.SKELETON / MONOSPACE_TEXT / TEXT_LARGE` etc. 

use props for everything else: `<Button minimal>` not `<Button className={Classes.MINIMAL} >`.
