### ISSUE TITLE
Error: Can't resolve './generated/docs.json'

### ISSUE THREAD

**Issue by EndiM** [palantir/blueprint#3307]
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.11.0
- __Browser and OS versions__: 
Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
OS: macOS Mojave 10.14.2
Node version: 10.13.0

#### Steps to reproduce

running `yarn verify` or `yarn dev` command in the project root or just `yarn compile` in packages/docs-data folder,
any command that includes compiling ./packages/docs-data/compile-docs-data.js script fails with error:
```
Module not found: Error: Can't resolve './generated/docs.json' in '/Users/endimodric/Desktop/blueprint.nosync/packages/docs-data/src
```
`yarn dev` output

![yarn dev output](https://duaw26jehqd4r.cloudfront.net/items/1B2R3q3T3s3b222h1m1x/Image%202019-01-21%20at%2011.47.47%20PM.png?v=77e4fbdf)

`yarn compile` output (run inside ./packages/docs-data)

![yarn compile inside /packages/docs-data output](https://duaw26jehqd4r.cloudfront.net/items/293t2c1V0E092Z250t2F/Image%202019-01-21%20at%2011.49.51%20PM.png?v=681897b5)

#### Actual behavior

Doesn't create  docs.json file at ./packages/docs-data/src/generated

#### Expected behavior

Should create docs.json file at ./packages/docs-data/src/generated

**Comment by giladgray** [comment]
@EndiM 🤷‍♂️ `yarn compile` at the root or in docs-data _should_ make this file every time. perhaps an error is being thrown by that script? have you edited any docs?

**Comment by giladgray** [comment]
do you perhaps have a `.npmrc` or `.yarnrc` file in the directory tree that points to a private NPM? this could cause the package lookups to fail.

that second screenshot sure looks like an error when generating docs.json, so i wonder what files you've touched and how? the script does not report helpful errors.

**Comment by EndiM** [comment]
@giladgray There is one `.yarnrc` with `workspace-experimental true` file but that was already in the root of the project. I haven't touched any of the files, I just forked the repository and was trying to setup the project when the error occurred. It definitely breaks in `compile-docs-data.js` script. I tried to debug but I still can't figure out.
It passes all until last `then` when the file is written and then breaks.

 ![debug screenshot](https://duaw26jehqd4r.cloudfront.net/items/3r421l1D0A401k33121M/%5B80947fce065ec2ca5ee88a197d72fd59%5D_Image+2019-01-22+at+3.47.01+PM.png?v=6da4ce07)

**Comment by giladgray** [comment]
@EndiM the stack trace you posted above clearly shows an error in the npm plugin: `JSON.parse in NpmPlugin`, which confirms my earlier suspicion that it's failing to parse package.json files correctly. did you edit any of those? 

do you have a `.*rc` file in an _outer directory_? npm/yarn work their way up the file tree to find all config files and merge them, so one outside of blueprint will still apply.

**Comment by EndiM** [comment]
@giladgray It works now, I isolated the repository and run `yarn verify`. I had few `.*rc` files in the outer directory so it must have picked them up. Sorry for wasting your time!

**Comment by giladgray** [comment]
yep there you go. thanks for confirming @EndiM 🌴
