### ISSUE TITLE
Tooltip default hoverOpenDelay

### ISSUE THREAD

**Issue by pavex** [palantir/blueprint#3316]
#### Environment

- __Package version(s)__: 3.11
- __Browser and OS versions__: Google Chrome 71.0.3578.98

#### Question

Hi, it's possible to setup hoverOpenDelay on Tooltip component to another value (1000ms) as default globaly?
Thanks
Pavel

**Comment by giladgray** [comment]
@pavex sure, you can change the global default with `Tooltip.defaultProps.hoverOpenDelay = 1000`.

https://reactjs.org/docs/react-component.html#defaultprops
