### ISSUE TITLE
Switch with nested text

### ISSUE THREAD

**Issue by kvngco** [palantir/blueprint#3320]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Feature request

Working on a settings modal that uses a prominent switch. Feature request to be able to:
- add nested text that changes based on on/off
- customizable colour based on on/off

#### Examples

UI/Animation: creating a new channel on Slack

Personal mock:
<img width="800" alt="screen shot 2019-01-28 at 9 03 09 pm" src="https://user-images.githubusercontent.com/3757807/51879112-25c41f80-2340-11e9-94e2-762a0e7bc4ae.png">

**Comment by giladgray** [comment]
yes this is cool! the implementation should gracefully handle a/b texts of different length. I propose doing it a la `<Button loading>` by maintaining the same width for both states.
