### ISSUE TITLE
Avoid font-styles

### ISSUE THREAD

**Issue by Neskews** [palantir/blueprint#3331]
#### Environment

```"@blueprintjs/core": "^3.5.1",```
#### Question

I have an existing react app and I want to use blueprints```Collapse```. I have an encapsulated Component that imports its own styles.scss. In that styles file I have following line:

```
@import '@blueprintjs/core/lib/css/blueprint.css';
```

**Expected**
The styles, especially font-related styles like ```font-size``` and ```letter-spacing```, are not applied to the rest of the react app.

**Actual**
The styles are applied, thus are interfering with the rest of the apps styles. 

**Potentially related issues**
https://github.com/palantir/blueprint/issues/2878#issue-354898289

**Updated**
The styles I don't want come from the ```_reset.scss```. To overwrite them, I needed to overwrite them in the styles.scss:

```
@import '@blueprintjs/core/lib/css/blueprint.css';

body {
  font-family: 'Roboto', sans-serif;
  letter-spacing: 0;
  line-height: 1;

  a {
    color: rgb(22, 65, 81);
    text-decoration: underline;
  }
}

```

![bildschirmfoto 2019-02-04 um 11 46 20](https://user-images.githubusercontent.com/29442471/52203792-84bef280-2872-11e9-8a23-4514a4ae4990.png)

**Comment by giladgray** [comment]
@Neskews sorry, this is not currently possible. see #2366 for context.

if you're _only_ using collapse then you could import and compile its `_collapse.scss` file, but honestly that's no fun and unsupported by us.

**Comment by Neskews** [comment]
@giladgray thanks for the quick reply - very commendable. I'm gonna work around it then.
