### ISSUE TITLE
EmberJS fork of Blueprint Components

### ISSUE THREAD

**Issue by jugaadi** [palantir/blueprint#3332]
We love BlueprintJS design and therefore, we are starting an open source EmberJS(addon) fork of Blueprint components. Would love to know your feedback/concerns if any.

**Comment by giladgray** [comment]
@jugaadi ooh interesting! can you please provide a link to the repository so I can follow along?

**Comment by jugaadi** [comment]
We are yet to publish it. Would keep you posted. Please share your email.

**Comment by giladgray** [comment]
@jugaadi cool. please post a link to the repo on this issue when you are ready. and please be sure to use our same license, for fun legal reasons.

**Comment by jugaadi** [comment]
Initial work is available here: https://dunkinbase.github.io/ember-elements . Still working out the rough edges. 

PS: Thanks for the update to Apache 2.0 License.
