### ISSUE TITLE
Webpack 4 production build is missing dom4 polyfill

### ISSUE THREAD

**Issue by TheHolyWaffle** [palantir/blueprint#3333]
#### Environment

- @blueprintjs/core 3.12.0
- Windows 10 / Chrome 71

#### Steps to reproduce

1. Do the following import:
`import { Position, Toaster, Intent } from "@blueprintjs/core";`
2. Make a production build using webpack 4
3. Load and execute the page on IE11

#### Actual behavior

IE11 console errors: Object doesn't support property or method 'remove'

#### Expected behavior

No error should appear

#### Possible solution

It appears that the dom4 polyfill that includes the .remove() functionality is not included during the production build. This is because @blueprintjs/core is marked as sideEffect: false in package.json. Which means that webpack will cut away any unused imports/exports. Including the following lines which are responsible for loading in dom4: https://github.com/palantir/blueprint/blob/b40b5a1766c4af55426cd2e82a1d23139c00ebd9/packages/core/src/components/index.ts#L8-L13

Solution is to mark this file as a sideEffect, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by TheHolyWaffle** [comment]
@TheHolyWaffle I'll leave that up to the maintainers :)

**Comment by tom-s-powell** [comment]
This is fixed in https://github.com/palantir/blueprint/pull/3868 right?

**Comment by adidahiya** [comment]
@tom-s-powell yes, I believe so, thanks. fixed by #3868 & #3876
