### ISSUE TITLE
DateRangePicker shortcuts incorrectly dismiss popovers

### ISSUE THREAD

**Issue by mjbcopland** [palantir/blueprint#3338]
#### Environment

- __Package__: Datetime 3.7.0
- __Browser__: Chrome 71.0.3578.98
- __OS__: macOS 10.14

#### Steps to reproduce

1. Put a DateRangePicker with shortcuts inside a Popover
2. Click one of the shortcuts

#### Example

https://blueprintjs.com/docs/#datetime/daterangeinput

#### Actual behaviour

Popover is dismissed

#### Expected behaviour

Popover should not be dismissed

#### Possible solution

Use `shouldDismissPopover` instead of `Classes.POPOVER_DISMISS_OVERRIDE`.

**Comment by adidahiya** [comment]
I don't fully understand, can you post a video / gif of the problem and some example code? In the example you linked, the popover does not get dismissed unless you enable the "close on selection" switch.

**Comment by apbarratt** [comment]
Hi people! I've thrown together a sandbox to demonstrate how the date range picker closes any enclosing popover when a shortcut date is selected.  Hope this helps towards finding a fix :)
https://codesandbox.io/embed/blueprint-sandbox-zmnow

**Comment by SaenkoM** [comment]
As a quick workaround:
```
const removePopoverDismiss= () => {
  const shortcuts = document.querySelectorAll('.bp3-daterangepicker-shortcuts li .bp3-menu-item')

  shortcuts.forEach((shortcut) => {
    shortcut.classList.remove('bp3-popover-dismiss')
  })
}

popoverProps={{
  ...
  onOpened: removePopoverDismiss,
}}
```
