### ISSUE TITLE
Date Picker: date doesn't update the first time the month is changed

### ISSUE THREAD

**Issue by krozett** [palantir/blueprint#3340]
#### Environment

- __Package version(s)__: datetime 3.7.0 (latest)
- __Browser and OS versions__: Chrome 72.0.3626.81, Firefox 65.0

#### Steps to reproduce

1. Refresh whatever page you are working on.
1. Select a date. It doesn't matter if you already navigated between months/years.
1. Use the month/year menus or left/right arrows to go to a different month or year.
1. Note that the `onChange` event has not fired.
1. Now use month/year menus or left/right arrows again.
1. Note that the `onChange` event does fire, supplying the new selected date and setting `isUserChange` to `false`.

You can reproduce it with the example on https://blueprintjs.com/docs/#datetime/datepicker . Note how the blue display below the calendar does not change after step 3, but does after step 5.

#### Actual behavior

The `onChange` event only fires the second time a month/year navigation happens, not the first.

#### Expected behavior

`onChange` should fire both times.

#### Possible solution

Using the component in a controlled manner may be a workaround. It's significantly more complex and I want to ignore non-user-initiated date changes anyway, so I have no personal interest in going down that road.

Edit because it turns out controlled usage actually works better for my use case: controlled usage doesn't have this bug, only uncontrolled.

**Comment by giladgray** [comment]
![datetime-change-repro](https://user-images.githubusercontent.com/464822/52307481-9de9a100-294f-11e9-936a-41ce2900fd8a.gif)

ah yep definitely got a repro here.

**Comment by krozett** [comment]
I edited my initial report, but just reiterating it here: controlled usage is a good workaround.
