### ISSUE TITLE
Remove the dependency between core and icons

### ISSUE THREAD

**Issue by mdestagnol** [palantir/blueprint#3345]
In the current version, importing the core imports also the 400kb of icons with it, which makes for a huge bundle. I know there has been some solution involving webpack to strip out the icons assets and replace them by an empty file. But I was wondering if there was any plan to make the core package completely independent of the icons? By the way, thanks to the contributors for this super high quality library!

**Comment by giladgray** [comment]
@mdestagnol sorry, this is not possible because of the string `IconName` syntax which only works if all the icons are available.

**Comment by mdestagnol** [comment]
Maybe I'm missing something. Let's say we want to add an icon to a `<Button>`. We set the property `<Button icon={iconComponent}>`. In this case, `iconComponent` can be either an `<Icon>` or a `MaybeElement`. Why do we need the Button to be aware that this is an "Icon", vs simply an HTML element. Wouldn't it make more sense to have the <Icon> component as part of the @blueprintjs/icons package instead of being in the core?

**Comment by adidahiya** [comment]
We like the convenience of `<Button icon={iconName}>` where `iconName` is just a string, that was a conscious API design decision. This requires core to depend on icons. I think you might be interested in #2193

**Comment by mdestagnol** [comment]
Understood. Always complicated to find the right balance between simplicity and "customizability". Appreciate taking the time to answer @adidahiya
