### ISSUE TITLE
Issues with Docs Navigator (Search box)

### ISSUE THREAD

**Issue by dieseldeesh** [palantir/blueprint#335]
#### Description
Nav div does not scroll as you press down arrow so user does not see which item is selected. This forces them to get more specific with their query or use mouse to scroll down. Is there another way to scroll down?

#### Example
![hot_key_issue](https://cloud.githubusercontent.com/assets/4008117/21016489/afa3c5c2-bd33-11e6-9bca-febb55841287.gif)

#### Description
While hovering over an element in the search drop down (such as the 3rd), the first item automatically also gets selected when the query changes. This causes confusion as to which element is actually selected.

#### Example
![style_bug](https://cloud.githubusercontent.com/assets/4008117/21016493/b3620822-bd33-11e6-8c34-e92f5592383c.gif)

**Comment by adidahiya** [comment]
Thanks for filing these issues. These are not urgent, but ultimately important to fix because they'll be necessary considerations for any kind of typeahead component we build (#118).

**Comment by giladgray** [comment]
i am not able to repro the Style Bug above (multiple blue items), i think we fixed that one a while back. got a fix for the hotkeys incoming 🚀
