### ISSUE TITLE
Nested menus in dropdown menu setup don't propagate onClicks

### ISSUE THREAD

**Issue by rgbkrk** [palantir/blueprint#3352]
#### Environment

- __Package version(s)__: 3.12.0
- __Browser and OS versions__: Chrome, macOS

#### Steps to reproduce

1. Use this code ([codesandbox](https://codesandbox.io/s/q9jw6q6y8q))

```js
import React, { useState } from "react";
import ReactDOM from "react-dom";

import "@blueprintjs/core/lib/css/blueprint.css";

import {
  Popover,
  Button,
  Menu,
  MenuItem,
  MenuDivider,
  ButtonGroup,
  Position
} from "@blueprintjs/core";

function App() {
  const [theme, setTheme] = useState("light");

  return (
    <div className="App">
      <ButtonGroup minimal>
        <Popover position={Position.BOTTOM_LEFT} minimal>
          <Button minimal text={"file"} />
          <Menu>
            <MenuItem text="New" icon="document" />
            <MenuItem text="Open" icon="folder-shared" />
            <MenuItem text="Close" icon="add-to-folder" />
            <MenuDivider />
            <MenuItem text="Save" icon="floppy-disk" />
            <MenuItem text="Save as..." icon="floppy-disk" />
            <MenuDivider />
            <MenuItem text="Exit" icon="cross" />
          </Menu>
        </Popover>
        <Popover position={Position.BOTTOM_LEFT} minimal>
          <Button minimal text={"edit"} />
          <Menu>
            <MenuItem text="Cut" icon="cut" />
          </Menu>
        </Popover>
        <Popover position={Position.BOTTOM_LEFT} minimal>
          <Button minimal text={"view"} />
          <Menu>
            <MenuItem text="Settings" icon="cog" />
            <MenuItem text="Theme" icon="folder-shared">
              <MenuItem
                text="Dark"
                icon="moon"
                onClick={() => setTheme("dark")}
              />
              <MenuItem
                text="Light"
                icon="flash"
                onClick={() => setTheme("light")}
              />
            </MenuItem>
          </Menu>
        </Popover>
      </ButtonGroup>
      <h1>Theme</h1>
      <h2>{theme}</h2>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

2. Click View -> Theme -> Dark

(note that theme doesn't change below)

3. Click View -> Theme -> Dark (again, and possibly again)

Watch how theme now changes to dark

NOTE: The above also occurs without React's new hooks. It just made this example smaller.

#### Actual behavior

First (?) click on a nested menu item does not fire onClick, only close the surrounding portal.

Additionally, it seems like opening the menu automatically opens that submenu.

#### Expected behavior

`onClick` gets triggered and menu is closed

#### Possible solution

???

#### Related issues

This is likely related to #3095, though I've got the codesandbox for checking out, as well as the above snippet.

**Comment by rgbkrk** [comment]
Some extra notes -- 

View is clicked here, yet the full submenu comes up.

<img width="479" alt="screen shot 2019-02-13 at 8 45 53 am" src="https://user-images.githubusercontent.com/836375/52728269-cf73f500-2f6b-11e9-838f-575035a3bc4d.png">

I tried to make a workaround for this in https://codesandbox.io/s/wymn319465 by putting a `ButtonGroup` inside a `Menu`, then just using `MenuItem` to build the submenus. Same bug occurs.

Is there another pattern I should be using @giladgray?

**Comment by BenRussert** [comment]
@rgbkrk I found a workaround, and a hint at where the bug is. 

In the nested menu item props use `tagName={ "button" }` 

 https://codesandbox.io/s/w6yyomoy1w

**Comment by AlexGodard** [comment]
I have the same problem. @BenRussert's solution works but the font gets changed to something else. To change it back to the default, add to your CSS file:

```css
button.bp3-menu-item > div {
  font-family: apple-system, "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Open Sans", "Helvetica Neue", "Icons16", sans-serif;
}
```

**Comment by domhaas** [comment]
> @rgbkrk I found a workaround, and a hint at where the bug is.
> 
> In the nested menu item props use `tagName={ "button" }`
> 
> https://codesandbox.io/s/w6yyomoy1w

Can confirm that this workaround works.

**Comment by aniov** [comment]
Try to add on Popover "autoFocus={false}"
`<Popover position={Position.BOTTOM_LEFT} minimal autoFocus={false}>
          <Button minimal text={"view"} />
          <Menu>
            <MenuItem text="Settings" icon="cog" />
            <MenuItem text="Theme" icon="folder-shared">
              <MenuItem
                text="Dark"
                icon="moon"
                onClick={() => setTheme("dark")}          
              />
              <MenuItem
                text="Light"
                icon="flash"
                onClick={() => setTheme("light")}                
              />
            </MenuItem>
          </Menu>
        </Popover>`

**Comment by adidahiya** [comment]
I am not seeing the bug from the OP in the code sandbox. Clicking the submenu items does change the "theme":

![2021-03-22 19 22 08](https://user-images.githubusercontent.com/723999/112070430-02721500-8b44-11eb-9c4b-5f4e06704934.gif)

Submenu opening up on its own is likely #2863
