### ISSUE TITLE
Add nameRenderer prop to RowHeaderCell

### ISSUE THREAD

**Issue by DannyDelott** [palantir/blueprint#3362]
#### Feature request

Hi Blueprint team,

I'm currently working on a Blueprint Table and need to add a Tooltip to the `RowHeaderCell` text. 

There is precedent for this in `ColumnHeaderCell` via the [`nameRenderer`](https://github.com/palantir/blueprint/blob/2b8300b8ce24ad4f17d3e7ef0b3ee0d700e4ae82/packages/table/src/headers/columnHeaderCell.tsx#L31-L44) prop, however this functionality does not exist yet for the `RowHeaderCell`.

If the approach from `ColumnHeaderCell` can be repurposed here, I'm happy to submit a PR. This is a great UI library with a very thoughtful API.

#### Examples

```tsx
<RowHeaderCell
  name="Population"
  nameRenderer={
    (name, index) =>
      <Tooltip content="The population as determined by the 2016 US Census">
        {name}
      </Tooltip>
  } />
```

**Comment by adidahiya** [comment]
What kind of information are you showing in this tooltip? Can you share an example? We're likely open to PRs here, just want to understand the context a bit more first.

**Comment by adidahiya** [comment]
Sorry, to elaborate: what are the columns in your example above? Why is population a row instead of a column?

**Comment by DannyDelott** [comment]
Thanks for the response! Our columns describe different urban planning scenarios, and the rows correspond to parameters in those scenario.

Here's a screenshot of the UI mock we're working from:

![image](https://user-images.githubusercontent.com/4524175/53840750-c74a1c80-3f4f-11e9-80cf-87f031cdae2f.png)

**Comment by adidahiya** [comment]
It looks like the data there is transposed in a way that doesn't really match how the table was designed to be used. `@blueprintjs/table` is more like a spreadsheet, where we expect the columns to be different parameters / attributes for a given entry, like a database. I think you're better off using the HTML table in `@blueprintjs/core` to implement that UI mock. Unfortunately we don't have an in-between component (there have been requests for things like #3368).

**Comment by DannyDelott** [comment]
I think that's a great testimony for the flexibility of this table component then! We've been able to get very close to our design, save for this tooltipped row header. 😄 

Since we still use the interactive features like right-click menus and multi-select, etc, using the HTML table doesn't quite fit our needs.

Our data model aside, this still seems like a useful feature for row headers and I'm happy to make a PR for it if it's an acceptable change.

**Comment by adidahiya** [comment]
Ok, go for it 👍
