### ISSUE TITLE
How can MultiSelect support scrollable popover

### ISSUE THREAD

**Issue by cloudysail** [palantir/blueprint#3363]
#### Environment

- blueprintjs/select@^3.3.0: 
- __Browser and OS versions__: 

#### Question

I'm using `MultiSelect` and would like to know how to make the `popover` scrollable?

`MultiSelect` has `popoverProps` which is `props to spread to Popover. Note that content cannot be changed.`, then I cannot change the popover content using the solution in
https://blueprintjs.com/docs/#core/components/popover.sizing

**Comment by cloudysail** [comment]
I think I found a solution by setting some global CSS like
```
.bp3-multi-select-popover .bp3-menu{max-height:300px;overflow:auto}
```
If so, we can close this issue.

**Comment by adidahiya** [comment]
same as https://github.com/palantir/blueprint/issues/2768#issuecomment-411152300, you should use `popoverClassName` and apply the relevant CSS to set a max-height for the relevant popovers. I would recommend avoiding global styles which apply to all MultiSelects like that.

**Comment by Foxhoundn** [comment]
It seems that the `popoverClassName` prop was removed from `Select` component.

How should we approach now to tackle this issue?
