### ISSUE TITLE
[Select] custom itemListRenderer breaks scrollToActiveItem

### ISSUE THREAD

**Issue by jbach** [palantir/blueprint#3369]
#### Environment

- __Package version(s)__: core@3.13.0, select@3.6.1
- __Browser and OS versions__: Chrome/Mac

#### Steps to reproduce

[![Edit w0wmq7p76k](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0wmq7p76k)

1. Open [Sandbox](https://codesandbox.io/s/w0wmq7p76k)
2. Select `Fight Club`
3. Reopen Select

#### Actual behavior

QueryList does not scroll to `Fight Club`, but to `Schindler’s List`.

#### Expected behavior

Should scroll to `Fight Club`

#### Possible solution

As mentioned in the [docs](https://blueprintjs.com/docs/#select/select-component.custom-menu), `itemListRenderer`can be used to `group items under a common heading`. But additional `MenuItem` shift the scroll behaviour. It seems, the problem lies within [QueryList#getActiveElement](https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/query-list/queryList.tsx#L262), which uses the lists children by index. This does not account for additional items.

**Comment by jbach** [comment]
So I have managed to solve my use case by overwriting `QueryList.prototype.getActiveElement`, but it would be nice to have a clean way. Either by allowing to overwrite `getActiveElement` via a prop or by using refs that establish the relations between item <-> HTMLElement? Otherwise, the docs should specify that no additional items within `itemsParentRef` are allowed.

**Comment by adidahiya** [comment]
fixed code link (pinned to a commit): https://github.com/palantir/blueprint/blob/a9197188d73058f850c01355b23197a53df5299f/packages/select/src/components/query-list/queryList.tsx#L299

yeah I think the only way to really solve this is with a new `getActiveElement` prop on `QueryList`, would be open to PRs exploring this approach

**Comment by shim-flounce** [comment]
> https://github.com/palantir/blueprint/blob/a9197188d73058f850c01355b23197a53df5299f/packages/select/src/components/query-list/queryList.tsx#L299
> 
> yeah I think the only way to really solve this is with a new `getActiveElement` prop on `QueryList`, would be open to PRs exploring this approach

@adidahiya Let me know your thoughts on the proposed approach in #5815.
