### ISSUE TITLE
<Drawer /> shows warning with default props

### ISSUE THREAD

**Issue by Ackos95** [palantir/blueprint#3380]
#### Environment

- __Package version(s)__: **"@blueprintjs/core": "3.13.0"**
- __Browser and OS versions__: Google Chrome Version 72.0.3626.109 (Official Build) (64-bit), Ubuntu 16.04.5 LTS

#### Steps to reproduce

1. Render `Drawer` component with default props (only fill required ones)
2. You can even try to modify other props (without adding `title`), even setting `isCloseButtonShown` to `false`, same result

#### Actual behavior

Throws out warning on each re-render (I assume):

`[Blueprint] <Dialog> isCloseButtonShown prop is ignored if title is omitted.`

#### Expected behavior

No warnings..

#### Possible solution

Only valid solution I found was to add empty `title` prop (`title=""`), but that causes empty header to draw within (which I don't want)

**Comment by Ackos95** [comment]
@adidahiya I can fix it it is really small fix

**Comment by Nancy-Wang0721** [comment]
Hi, just wondering is this issue fixed yet? I'm using package version **@blueprintjs/core@npm:3.28.1** and are still experiencing the issue.

**Comment by adidahiya** [comment]
@Nancy-Wang0721 that version is fairly old. if the issue still persists, can you please post a code sandbox demonstrating the problem?

**Comment by Nancy-Wang0721** [comment]
> @Nancy-Wang0721 that version is fairly old. if the issue still persists, can you please post a code sandbox demonstrating the problem?

It's now fixed. Thank you!
