### ISSUE TITLE
Turn off autocomplete for InputGroup

### ISSUE THREAD

**Issue by nmquaan** [palantir/blueprint#3383]
#### Environment

- __Package version(s)__: 3.12.0
- __Browser and OS versions__: Chrome Version 72.0.3626.119 (Official Build) (64-bit) - Window 10 Build 1803

#### Question
How to turn off `autocomplete` on `InputGroup`?

Please help me resolve this question.
Thanks for the support!

**Comment by nmquaan** [comment]
Hi there,
This problem resolved.
Sorry because raise this issue.

**Comment by furkanbezci** [comment]
How??

**Comment by clinVaricent** [comment]
How?

**Comment by VincentFP** [comment]
Like this:

`<InputGroup autoComplete="off"></InputGroup>`
