### ISSUE TITLE
Non-Standard License

### ISSUE THREAD

**Issue by hen** [palantir/blueprint#3384]
Over at Apache our criteria for license use begins with a license needing to be Open Source Definition compliant. Blueprint's license has been raised there as questionable ( https://issues.apache.org/jira/browse/LEGAL-436 ). 

Have you discussed your license with the OSI?

For my part, I see two concerns with section 10 that stop Blueprint from being an Open Source project:

Firstly, section 1 is a field of use restriction. It is accepted that it's not a field of use restriction to state that a derived work cannot infringe on trademarks, but this seems to go beyond that (otherwise, why have this text given section 6 exists).

Secondly, section 2 is a pig to comprehend. I think it's a trademark concern again. My rough interpretation is that "No derivative work should imply it's Palantir's work, or the work of a Contributor". It appears to be blocking simple factual statements - "This product is derived from/includes/depends-on Palantir's Blueprint" is an example of one that would seem to conflict with this section. The phrase 'sourced from' also made me wince, given that source has another meaning in an Open Source license, and 'sourced from' is very different in meaning to sponsored/endorsed/promoted.

Another factual statement that is blocked is that a Contributor to Blueprint cannot state that their derived work is sourced from/sponsored/endorsed/promoted by themselves.

**Comment by adidahiya** [comment]
Thanks for the feedback; I've reached out to our legal team to see what they think about this.

**Comment by hen** [comment]
Any word?

Assuming no word, I'll leave the Apache JIRA issue open another week, then resolve it as unsuccessful.

**Comment by adidahiya** [comment]
@hen I've just gotten approval from legal to change the license to a standard Apache-2.0 one. The original modification to Apache-2.0 was made in an effort to prevent potential competitors from copying the design of Palantir's products in a manner similar to the original BSD+Patents license (#1751). After re-weighing the risks around this while Blueprint has been available, we've decided that the benefits of using a standard license are greater than the associated risks. I'll make a PR to switch the license soon.

**Comment by hen** [comment]
That's brilliant - thank you Adi and Palantir Legal :)
