### ISSUE TITLE
[Select] Keyboard navigation on select with no enabled items causes infinite loop

### ISSUE THREAD

**Issue by Goddak** [palantir/blueprint#3388]
#### Environment

- __Package version(s)__:  3.7.0 
- __Browser and OS versions__:  Chrome 72 (Ubuntu 18.04)

#### Steps to reproduce

1. Navigate to: https://blueprintjs.com/docs/#select/select-component
2. Turn on "Disable films before 2000" prop
3. Open drop-down and filter with 'the god'
4. Press down arrow

#### Actual behaviour

Crashes.

#### Expected behaviour

Same as when no results (filter by "thegod" to test) - nothing should happen when I press an arrow key.

#### Possible solution

Not investigated

**Comment by adidahiya** [comment]
Good catch, thanks for the clear repro steps

**Comment by Goddak** [comment]
@adidahiya - Hey bud, any update on this bug?

**Comment by vedadeepta** [comment]
@adidahiya -  seems like this bug is caused due to an infinite loop in `getFirstEnabledItem()` in `select/src/components/query-list/` component when `startIndex = -1` and all items are disabled the index variable is stuck in the range of 0 - maxIndex.
