### ISSUE TITLE
Large lists of 'Text' elements force reflows, leading to poor performance

### ISSUE THREAD

**Issue by MGHawes** [palantir/blueprint#3393]
I can't post all the reproduction steps here without referring to palantir internal applications (Will ping code owners on the side for more details)

Essentially [this line](https://github.com/palantir/blueprint/blob/e97ef2cd9ff130544275a0044e1cd5fc205b1621/packages/core/src/components/text/text.tsx#L75) is causing _a lot_ or reflows in a long list of items:
![image](https://user-images.githubusercontent.com/26897711/53822220-367f3b00-3f67-11e9-9765-0e40e0437f0b.png)

The `.scrollWidth` is the culprit, used for showing the ellipsis. Perhaps we can instead the the css `overflow: ellipsis` style for this?

**Comment by MGHawes** [comment]
@adidahiya for triage

**Comment by adidahiya** [comment]
This is hard to debug without a more clear repro case... on the internal ticket you mentioned this regression correlated to a change to use `<Select>` but that package doesn't use `<Text>` anywhere... so this probably has more to do with your application layout containers and how they interact with each other rather than Blueprint's own usage of `<Text>`

**Comment by noah79** [comment]
I am running into the same issue with the new ContextMenu2 component with standard menus.  The text measurement for MenuItems is killing performance opening the menu.

**Comment by noah79** [comment]
Doing this made a huge difference for me:
`const ContextMenuItem = (props: IMenuItemProps) => {
  return <MenuItem multiline={true}  {...props} />
}`

**Comment by adidahiya** [comment]
@noah79 do you have a code sandbox where you could demonstrate the performance issue? I understand why Text's overflow checking behavior may cause unexpected DOM work, but it's necessary for the feature you get out of the box for MenuItems (and some other Blueprint components) which shows a native browser tooltip on hover for text which is hidden behind a "...". 

I have an attempt to refactor the Text component into a function component here, it should in theory improve performance by running the `update()` function less often (now it's a layout effect hook) but I haven't been able to verify the performance improvement through the DevTools profiler... https://github.com/palantir/blueprint/pull/4666
