### ISSUE TITLE
Toggle Checkbox on keyboard interaction

### ISSUE THREAD

**Issue by Neskews** [palantir/blueprint#3397]
#### Environment

- __Package version(s)__: 3.5.1

#### Feature request

Enable keyboard action for `Checkbox` as already done for `NumericInput`. For example, toggle checked status on keyboard enter.

**Comment by adidahiya** [comment]
You can already do this with the space bar, which is the standard keyboard interaction for checkboxes. Enter is often reserved for submitting forms.
