### ISSUE TITLE
Table doesnt render properly.

### ISSUE THREAD

**Issue by ABruel** [palantir/blueprint#3399]
#### Environment

- __Package version(s)__: 
@blueprintjs/core: ^3.14.1
@blueprintjs/datetime: ^3.7.2
@blueprintjs/icons: ^3.6.0
@blueprintjs/select: ^3.7.0
@blueprintjs/table: ^3.4.1
@blueprintjs/timezone: "^3.3.0"
- __Browser and OS versions__: 
Firefox Quantum 65.0 and chrome 72.0.3626.96. both on linux Mint 19

#### Question
The table doesn't render properly. resizing any of the rows fixes the problem until the component unmounts.
I'm using the docs example for simplicity.

Current:
![selecao_018](https://user-images.githubusercontent.com/30672118/54031346-424c4680-418d-11e9-9a96-2da389ea7e4a.png)

Expected
![selecao_019](https://user-images.githubusercontent.com/30672118/54031406-6740b980-418d-11e9-8462-a05da655e938.png)

The code, just in case:
```tsx
import 'normalize.css';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import '@blueprintjs/table/lib/css/table.css';
import '@blueprintjs/datetime/lib/css/blueprint-datetime.css';
import '@blueprintjs/select/lib/css/blueprint-select.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

import React from 'react';
import ReactDOM from 'react-dom';
import * as serviceWorker from './serviceWorker';
import {Table, Column, Cell} from '@blueprintjs/table';
const cellRenderer = (rowIndex: number) => <Cell>{`$${(rowIndex * 10).toFixed(2)}`}</Cell>;
ReactDOM.render(
  <Table numRows={10}>
    <Column name="Dollars" cellRenderer={cellRenderer} />
  </Table>
  , document.getElementById('root'));
```

**Comment by killerspaz** [comment]
Running into this as well, have you found a workaround?

I tried the `forceUpdate` and semaphore hack, but no-go. As you demonstrated, even the sample in the documentation isn't working.

**Comment by S0urcemaster** [comment]
You've changed the font.

**Comment by ABruel** [comment]
> You've changed the font.

What font? The example is from the docs, the exact same code.
