### ISSUE TITLE
Regression in DateInput

### ISSUE THREAD

**Issue by ggregoire** [palantir/blueprint#340]
Hi guys!

I got a regression in updating from 1.1.0 to 1.2.0 (latest).

The bug comes from [this PR](https://github.com/palantir/blueprint/pull/297).

The component crashes during its instantiation because of [this change](https://github.com/palantir/blueprint/pull/297/files#diff-2899fd9fc14d599c6e4062f791d99120L135).

Some screenshots:

![screen shot 2016-12-09 at 00 47 57](https://cloud.githubusercontent.com/assets/591804/21040618/b87be8aa-bdab-11e6-9766-0734501da2a1.png)

![screen shot 2016-12-09 at 00 47 24](https://cloud.githubusercontent.com/assets/591804/21040620/bbc5d106-bdab-11e6-9b19-c6de34328d76.png)

It worked before to pass a `string` to the component because of the `moment(date)`.

Now it doesn't work anymore because of the `moment([date.getFullYear(), ...])`.

To be honest, your doc says that `value` should be a `Date` and not a `string`, so...

We could indicate in the changelog the potential breaking change and a possible solution, e.g.

> replacing `value={value}` by `value={new Date(value)}`

Or maybe a workaround in the code to keep the previous behaviour?

**Comment by cmslewis** [comment]
Thanks for filing, @ggregoire! This is helpful context, but I'm going to close this as a duplicate so that we can track the issue in a single place in #280.

**Comment by adidahiya** [comment]
Actually the correct duplicate is #322. Fixed for today's upcoming release.

**Comment by ggregoire** [comment]
> Thanks for filing, @ggregoire! This is helpful context

> Fixed for today's upcoming release.

Guys, did you read my bug description beyond the first 3 lines?

How [this fix](https://github.com/mfedderly/blueprint/commit/76a1ee7b29f71b30b8c60ae371c5283950ea7fbd) could fix this?

![screen shot 2016-12-09 at 00 47 24](https://cloud.githubusercontent.com/assets/591804/21040620/bbc5d106-bdab-11e6-9b19-c6de34328d76.png)

Could you change this

```
if (null == date) {
    return moment(null);
}
```

in

```
if (null == date || typeof date === "string") {
    return moment(date);
}
```

for today's upcoming release?

Or do you prefer me to submit a PR?

Thanks.

**Comment by ggregoire** [comment]
Some tests to avoid future regressions:

```javascript
it("renders without crashing", () => {
  const DATE_NULL = null;
  ReactDOM.render(<DateInput value={DATE_NULL} />, document.createElement("div"))

  const DATE_STRING = "1988-08-07 11:01:12";
  ReactDOM.render(<DateInput value={DATE_STRING} />, document.createElement("div"))
})
```

**Comment by adidahiya** [comment]
Hey, you're right @ggregoire, sorry I overlooked that. Opened a new PR #342 which we will try to merge for today's upcoming release.

**Comment by ggregoire** [comment]
@adidahiya Thanks for looking into it! :)

**Comment by cmslewis** [comment]
Whoops, sorry about that @ggregoire. Thanks for staying vigilant.
