### ISSUE TITLE
is it possible to add Icon in DateInput ? 

### ISSUE THREAD

**Issue by squarewave24** [palantir/blueprint#3401]
I want Date Input to look like InputGroup with a left icon. 

pretty standard look for date pickers to have a little calendar icon on the left. 

i tried wrapping different elements but can't seem to get this to work 

i want date-input to look like text-input:

https://blueprintjs.com/docs/#datetime/dateinput
https://blueprintjs.com/docs/#core/components/text-inputs.input-group

**Comment by adidahiya** [comment]
yes, use `inputProps`, which allows you to set props on the underlying `InputGroup`

**Comment by squarewave24** [comment]
> yes, use `inputProps`, which allows you to set props on the underlying `InputGroup`

could you elaborate or point to an example?

**Comment by adidahiya** [comment]
`<DateInput inputProps={{ leftIcon: "calendar" }} />`

**Comment by squarewave24** [comment]
> `<DateInput inputProps={{ leftIcon: "calendar" }} />`

interesting thanks! didn't realize you can do this.. essentially you figure out which control DateInput is using and then you know which InputProps are supported?

**Comment by adidahiya** [comment]
it's listed in the props documentation. you can click through all the types & interfaces in the docs to see their members
