### ISSUE TITLE
Select with ajax / remote data source

### ISSUE THREAD

**Issue by squarewave24** [palantir/blueprint#3402]
I've been stuck with this for hours. 

I saw the omnibar question and suggestion to use inputProps onChange but so far i can't get it to work.. my code so far: 

     render() { 

               let CompanySelect = Select.ofType<ICompany>();
               ...
               <CompanySelect
                    items={companies}
                    onItemSelect={this.handleItemSelect}
                    itemPredicate={this.filterCompany}
                    itemRenderer={this.renderCompany}
                    {...this.state}

                    itemsEqual={this.areItemsEqual}
                    noResults={<MenuItem disabled={true} text="No results." />}
                    inputProps={{ onchange: this.handleChange }}

```
    handleChange = (e: any) => {
        console.log('change! ', e);
        this.userInput$.next(e.target.value);
    }
```

this was a breeze with regular react components, but for some reason can't figure out with BP. my select shows, but so far handleChange does not fire when typing into the select... 

i am not sure if this is the best approach to implement xhr type data source with latest version? 

i have a development branch of https://github.com/palantir/blueprint.git which has a few examples but it looks like they're all based on static data..

**Comment by squarewave24** [comment]
hmm just kind of got it to work using onQueryChange event 

    onQueryChange={this.handleQueryChange}


     handleQueryChange = (e: any) => {
        console.log('handleQueryChange', e)
        this.userInput$.next(e);

    }

**Comment by adidahiya** [comment]
Blueprint components are generally data-agnostic and require you to do your own data loading / manipulation. See https://github.com/palantir/blueprint/issues/2528 and https://github.com/palantir/blueprint/issues/3253
