### ISSUE TITLE
Tab is wrapped by HOC and Tab not display

### ISSUE THREAD

**Issue by MrMengJ** [palantir/blueprint#3421]
#### Environment

- __Package version(s)__: ^3.12.0
- __Browser and OS versions__: Chrome V72

#### Steps to reproduce

1. Tab is wrapped by HOC AuthControl
2. 
``` javascript
const AuthControlTab = AuthControl(Tab)
 <Tabs id="systems">
      <AuthControlTab id={Systems.HOME}  />
</Tabs>
 ``` 

#### Actual behavior
Tab don't  display

#### Expected behavior

Tab display normally

**Comment by MrMengJ** [comment]
This is HOC AuthControl
```javascript
const AuthControl = WrappedComponent => {
  class Item extends Component {
    render() {
         return <WrappedComponent {...this.props} />;
      }
   }
  return Item
};

export default AuthControl;
````

**Comment by adidahiya** [comment]
This is a limitation of the `Tabs` API. Children of `Tabs` need to be `Tab` components. Maybe it needs to be highlighted more clearly in the documentation. For now you can put your `AuthControl` functionality inside the `Tab` child of `Tabs`.

**Comment by MrMengJ** [comment]
Thank you !!! @adidahiya
