### ISSUE TITLE
How to not autofocus the popover created by ContextMenu.show() ?

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#3424]
I can't find a way to stop the popover created by ContextMenu.show() from stealing focus. Is there any way around this?

Thanks!

**Comment by tnrich** [comment]
Looking at the code it doesn't seem like there is any way set up to pass additional props to the <Popover/> element being created: 

https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/context-menu/contextMenu.tsx#L63

**Comment by adidahiya** [comment]
Can you share more of the UI / UX context here? Why do you not want it to autofocus?

**Comment by tnrich** [comment]
Sorry @adidahiya sometimes I don't want the context menu to steal the focus from the layer that was just right clicked to bring it up. I'd basically just like to be able to override the `autoFocus=true` on a case by case basis. In my case if there is a selection 

![image](https://user-images.githubusercontent.com/2730609/61907536-8644ab80-aee2-11e9-9c3a-4a64093c40df.png)

![image](https://user-images.githubusercontent.com/2730609/61907553-8e9ce680-aee2-11e9-8f85-c5f4783b01ea.png)

Right clicking the selection makes it lose focus unnecessarily... Maybe..? 

Thinking more about this though, I think that is actually an unfriendly UX for people who need to use the keyboard to navigate. I'll close this.
