### ISSUE TITLE
Uncontrolled MultiSelect example?

### ISSUE THREAD

**Issue by zachkirsch** [palantir/blueprint#3429]
#### Environment

- __Package version(s)__:
    - "@blueprintjs/core": "^3.8.0",
    - "@blueprintjs/icons": "^3.6.0",
    - "@blueprintjs/select": "^3.7.0",
- __Browser and OS versions__: OSX 10.14.3, Chrome 73.0.3683.75

#### Question

Hi!

I'm trying to get an uncontrolled MultiSelect working, but haven't had much luck. Is there an example of one somewhere?

Here's what I've got. Am I missing something obvious? Is specifying the `onClick` and `active` in the `MenuItem` even necessary?

```jsx
<MultiSelect
    items={["A", "B", "C"]}
    itemRenderer={(item, { modifiers, handleClick }) =>
        <MenuItem
            key={item}
            text={item}
            onClick={handleClick}
            active={modifiers.active}
        />
    }
    onItemSelect={() => {}}
    tagRenderer={item => item}
/>
```

This is what renders:

![multiselect](https://user-images.githubusercontent.com/8902272/54582572-a241b900-49e7-11e9-9a1f-e736fe43aa4c.gif)

Thanks!

**Comment by adidahiya** [comment]
The [example in the docs](https://github.com/palantir/blueprint/blob/78b8f6536aa99fac524cfcdec5250b98ad379b53/packages/docs-app/src/examples/select-examples/multiSelectExample.tsx) is actually uncontrolled but it might be a little hard to understand because it does much more than the most basic example usage of the component. Your code looks fine; you do need to set `onClick` and `active` on the MenuItem like you are doing. Can you try posting a minimal bug repro using the codesandbox link in the README?

**Comment by zachkirsch** [comment]
Thanks for the quick reply!

I thought that the `films` array in the `MultiSelectExample`'s state was controlling the `MultiSelect`.

Here's a link to a repro on the sandbox: https://codesandbox.io/s/1vv1l03j2j

**Comment by richwandell** [comment]
I am running into this same issue today. Was there a resolution?

**Comment by adidahiya** [comment]
@richwandell this is a pretty old issue, can you please create a new one and share a code sandbox of your problem?

**Comment by rrramani1230** [comment]
Did anyone get this to work. I wonder why the MultiSelect looks like a singleselect. Are there certain props that are not required but needed for the mutliselect to work @zachkirsch @adidahiya

**Comment by rrramani1230** [comment]
The answer to this is that you need the selectedItems prop along with the tagRender prop for it to Render. Please don't spent as much time on this as I did finding this out :(
