### ISSUE TITLE
Remove moment dependency from published typings for datetime package

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#343]
Not sure if this is possible, but we should look into it. See https://github.com/palantir/blueprint/pull/339#discussion_r91782919

**Comment by giladgray** [comment]
could mark that one property `@internal`?

**Comment by giladgray** [comment]
so `@internal` does remove the import from `dateInput.d.ts` as well as the field from `this.state`. but that's probably fine for the typings, yeah?

**Comment by giladgray** [comment]
@adidahiya thoughts on my proposal above?

**Comment by adidahiya** [comment]
@giladgray yes, I like that idea, but it sounds susceptible to regressions. Let's see if we can add tests that prevent us from leaking typedefs like this..

**Comment by giladgray** [comment]
hmm any suggestions for how to go about testing that? regular expression on the `.d.ts` files? is it really worth the extra complexity?

**Comment by leebyp** [comment]
the typings that gets pulled in is from the moment module itself, so there no harm in using it anyway, right?

**Comment by giladgray** [comment]
yeah i think @leebyp is right... `moment.d.ts` comes from the NPM `moment` package itself so consumers will always have it available. there shouldn't be any harm in leaving the reference around.

**Comment by giladgray** [comment]
we've been doing exactly that lately... see `@types/dom4` and `@types/tether`. but there is no `@types/moment` cuz the typings are in the NPM package itself. 

i don't understand what you're asking to do? it seems like there's no work here.

**Comment by adidahiya** [comment]
we also depend on types that are pulled in via our root package.json, as you documented for users here: https://github.com/palantir/blueprint/pull/404/files#diff-3e1057b57224ba16b7b9ab4aaabd6037R108

**Comment by giladgray** [comment]
but those are peer dependencies so it's not weird.

**Comment by llorca** [comment]
@adidahiya should we take care of this for this week? Looks like you're the only person that understands how to move forward ⏩

**Comment by adidahiya** [comment]
Did some reading in the [TypeScript Handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md#dependencies) and looked for relevant issues in the TS repo. I think we should declare all the react typings + `@types/pure-render-decorator` as `"dependencies"` in package.json.

**Comment by giladgray** [comment]
closing this issue as the `moment` discussion is resolved. `@types` as `dependencies` will continue in #485.
