### ISSUE TITLE
Tooltip triangle shows 1px gap in some cases

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#3430]
#### Environment

- __Package version(s)__: `@blueprintjs/core 3.14.0`
- __Browser and OS versions__: Firefox 66, macOS

#### Steps to reproduce

1. Open https://blueprintjs.com/docs/#core/components/tooltip in Firefox
2. Set browser zoom level to something greater than 100%, like 150%.

#### Actual behavior

Due to [CSS rounding errors](https://johnresig.com/blog/sub-pixel-problems-in-css/) (which may or may not be browser bugs), the triangle that points to the tooltipped element shows a 1px border on left and top-aligned tooltips:

<img width="177" alt="Screenshot 2019-03-19 at 19 08 04" src="https://user-images.githubusercontent.com/115237/54630692-b5ea2f80-4a7a-11e9-897f-b0d52e33b60a.png"> <img width="305" alt="Screenshot 2019-03-19 at 19 08 14" src="https://user-images.githubusercontent.com/115237/54630694-b5ea2f80-4a7a-11e9-98af-07f4029909ea.png">

#### Expected behavior

There should not be a visible border between tooltip and the triangle, like in right and bottom-aligned tooltips:

<img width="173" alt="Screenshot 2019-03-19 at 19 08 24" src="https://user-images.githubusercontent.com/115237/54630697-b682c600-4a7a-11e9-927e-18529491289d.png"><img width="181" alt="Screenshot 2019-03-19 at 19 08 37" src="https://user-images.githubusercontent.com/115237/54630698-b682c600-4a7a-11e9-87b4-a3f8311adfd6.png">

#### Possible solution

When positioning the triangle, position it so it goes 1px into the tooltip element to prevent CSS rounding errors from having significance. Note that this will not work with semi-transparent tooltips, but as Blueprint's tooltips are opaque, it may be an option.

A better solution might be to use a SVG path for the tooltip background.

**Comment by adidahiya** [comment]
> A better solution might be to use a SVG path for the tooltip background.

This could potentially be a good approach... I believe the original tooltip design was created when SVG styling support was not so widespread, but now that Blueprint uses SVGs for icons, I think it is worth reconsidering this design choice. I'm not sure how well this would play with popper.js and how it would do responsive resizing based on tooltip contents...

I don't have bandwidth to work on this right now, but would be happy to look at proposals and work through PRs with interested contributors.

**Comment by silverwind** [comment]
A SVG solution might be ideal, but hard too given that we can not simply stretch a SVG background with the triangle as the triangle itself needs to maintain aspect ration. I imagine a workaround those rounding errors (maybe via `getComputedStyle`) might be easier to pull off.

**Comment by silverwind** [comment]
Found a hacky workaround that moves the arrow by half a pixel in the direction of the popover which seems to reliably eliminate those rounding errors:

````css
.bp3-popover[style*="transform-origin"][style*="bottom"] .bp3-popover-arrow { transform: translate(0, -.5px); }
.bp3-popover[style*="transform-origin"][style*="left"] .bp3-popover-arrow { transform: translate(-.5px, 0); }
.bp3-popover[style*="transform-origin"][style*="top"] .bp3-popover-arrow { transform: translate(0, .5px); }
.bp3-popover[style*="transform-origin"][style*="right"] .bp3-popover-arrow { transform: translate(.5px, 0); }

**Comment by adidahiya** [comment]
I can still reproduce this at some zoom levels in Firefox 74.0, but I'm closing this stale issue for now due to low priority.
