### ISSUE TITLE
Opt out of showing a hotkey label in the hotkey dialog

### ISSUE THREAD

**Issue by mattrussell36** [palantir/blueprint#3431]
It would be useful if you could choose **not** to display a hotkey in the hotkeys dialog.

Our use case is that we have hotkeys for `cmd + 1...9` and we would like to display only one hotkey label for all of these.

I'd be happy to help out and make a PR.

thanks!

**Comment by adidahiya** [comment]
There are no APIs to customize display of the dialog right now... have you looked at #3228 and #1590 ?

**Comment by mattrussell36** [comment]
Yup looked into those. _I don't think_ those issues would cover this functionality as they are about customizing the text and controlling its display state.

What would be nice is if we could remove Hotkeys from the dialog, but still have the hotkey registered so that it calls the method passed to it when the triggered.

It could be done with an additional property for the `<Hotkey />` component, `showInDialog` which would default to `true`
