### ISSUE TITLE
DateRangePicker with singleMonthOnly and maxDate renders last month

### ISSUE THREAD

**Issue by jaxgeller** [palantir/blueprint#3432]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "3.14.1", "@blueprintjs/datetime": "3.7.2",
- __Browser and OS versions__: All

Demo: https://codesandbox.io/s/lxlq58lm4q

#### Steps to reproduce

1. Add DateRangePicker with 

```js
<DateRangePicker
  singleMonthOnly
  allowSingleDayRange
  shortcuts={false}
  maxDate={new Date()}
/>
```

#### Actual behavior

By default renders last month

#### Expected behavior

Render the current month as the default

**Comment by adidahiya** [comment]
Thanks for the code repro, looks like a bug

**Comment by dqlobo** [comment]
I think this could be to blame: https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/dateRangePicker.tsx#L198
Don't have time this minute to jump in further
