### ISSUE TITLE
Adjust size of DateInput input box

### ISSUE THREAD

**Issue by CodeMaven** [palantir/blueprint#3444]
Hi,

I am trying to change the size of a DateInput. I need all of my input fields to line up on the app but it seems that the interface is inconsistent across components. For example, I am able to use small={true} on regular inputs to use a more compact theme but for numeric or date that does not work. For the length of the box I've got it to work on all of my other controls but with DateInput, no matter what I do  it does not make a difference.  I cannot hard-code this in css because it needs to dynamically change programatically. Here's what I've tried:

```ts
        <DateInput style={{width: props.width}}
                   inputProps={{
                    leftIcon:"calendar",
                    width: props.width
            }}
                   width={props.width}
                   showActionsBar={true}
                   small={true}
                   closeOnSelection={true}
                   value={props.data[props.field]}
                   popoverProps={{ position: Position.BOTTOM }}
                   formatDate={ date => moment(date).format("YYYY-MM-DD")}
                   parseDate={str => moment(str, "YYYY-MM-DD").toDate()}
                   minDate = {new Date('1901-01-01T00:00:00')}
        />
```

I've put width={props.width} as an attribute on the tag, and I've put it in the style on the component, and also in the inputProps tag. No matter what, the width of the actual input box stays the same.... How can I resize it so that it matches my other fields? See the attached screenshot. The date boxes should be 200px wide,  the same as the other inputs.
![Screenshot from 2019-03-25 12-55-56](https://user-images.githubusercontent.com/8939073/54921514-dcd2b680-4efd-11e9-8f42-1ae1f6a5d7ef.png)

Thankyou,
Troy

**Comment by Cody0913** [comment]
If it is for consistent styling and you have access to the stylesheets I would possibly make a class defining your desired input width. This will also give you access to make the inputs more responsive.
Then just set up a style for it.

I did so by creating the below style.
```
.test-width, .test-width input {
  width: 200px !important;
}
```
Then using the dateInput as such
`<DateInput className={'test-width'}/>`

This might be more of a hack, but also allows to only set the style once and not have to pass a prop.

**Comment by CodeMaven** [comment]
Hi, 
Unfortunately this is not just for consistent styling.  I actually generate customizable screens dynamically. It's a business app with many, many screens (200+) and a built-in editor for creating new data entry screens. The layouts are saved in Json format in the database and and supplied by a webservice. A rendering engine written in React renders the controls from the JSON on demand. There are also some screens that are created on-demand by the Java back-end from external data sources. So, the width has to be set programmatically. See this SO link for a more detailed description of what I'm doing:
https://stackoverflow.com/questions/53521729/dynamic-layout-of-react-component-from-json

Cheers,
Troy.

**Comment by adidahiya** [comment]
@CodeMaven this should do the trick:

```ts
<DateInput inputProps={{ style: { width: props.width }}} />
```

what you were setting in your example was the `width` attribute on the `<input>` element, which is not the same thing ([see docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input))
