### ISSUE TITLE
Small button design difference in Sketch/Figma and CSS

### ISSUE THREAD

**Issue by vkorobov-boostlabs** [palantir/blueprint#3448]
.sketch design file has different font-size for 3 types of buttons:
![image](https://user-images.githubusercontent.com/47153854/55053240-f2e19380-5031-11e9-83eb-f25fba39c09a.png)
- Normal - 14px
- Large - 16px
- Minimal - 12px

But css style for minimal button does not change font-size from 14px to 12px. I am working on symbolizing everything in .sketch file and wonder should I fix that bug or not?

**Comment by adidahiya** [comment]
@pkwi

**Comment by pkwi** [comment]
Looks like small font size was removed here https://github.com/palantir/blueprint/pull/1421

Small buttons in Sketch should then use default font size - [small buttons.sketch.zip](https://github.com/palantir/blueprint/files/3016224/small.buttons.sketch.zip)

**Comment by terpimost** [comment]
@adidahiya and @pkwi that should be fixed in https://github.com/palantir/blueprint/pull/4007

**Comment by adidahiya** [comment]
Revisiting this, @aycai and I think that small buttons should use 12px. It seems like the only justification for removing the 12px font size from small buttons was that small input groups also used 14px. But that does not seem to be the case anymore; they use 12px:

![image](https://user-images.githubusercontent.com/723999/130528474-cfd44903-6a8c-4ef8-b517-6d12e4f9dd93.png)

So, we should change small buttons to also use 12px font. This would make them match our Figma design:

![image](https://user-images.githubusercontent.com/723999/130528533-fb9ff45c-6c04-4bce-aada-47e0ec6efb6f.png)
