### ISSUE TITLE
Date range picker and Date range input incorrect end time

### ISSUE THREAD

**Issue by ppiscuc** [palantir/blueprint#3449]
#### Environment

node v10.15.3
yarn 1.12.3
@blueprintjs/core 3.14.1
@blueprintjs/datetime 3.7.1
Chrome 73.0.3683.86 
Ubuntu 18.10 x64

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#datetime/daterangepicker
2. select `allow single day range` and `time precision = minutes`
3. click `Yesterday`

It can be reproduces by selecting any time filter on the left of the date range picker.
It can be reproduces also with the daterangeinput

#### Actual behavior
My computer reports that today is 27.03.2019.
The output is:
`Tuesday, March 26, 2019 12:00 AM -> Tuesday, March 26, 2019 12:00 AM`

#### Expected behavior
`Tuesday, March 26, 2019 12:00 AM -> Wednesday, March 27, 2019 12:00 AM`

#### Possible solution

Consider today: 27.03.2019 00:00 -> now or 27.03.2019 00:00 -> 28.03.2019 00:00
yesterday: 26.03.2019 00:00 -> 27.03.2019 00:00
past week: 21.03.2019 00:00 -> 28.03.2019 00:00

**Comment by Neskews** [comment]
Since it is a date RANGE picker, I understand why you expect it to actual select a range. On the other hand, ```yesterday``` isn't a range. So I guess it's expected behavior.

**Comment by adidahiya** [comment]
Single day ranges are allowed in the range picker. That's why we have the prop.

I can't repro this @ppiscuc. Which time zone are you in?

Today:

![image](https://user-images.githubusercontent.com/723999/55191029-78229080-5177-11e9-9725-d1c8aa1e86ca.png)

Yesterday:

![image](https://user-images.githubusercontent.com/723999/55191041-7fe23500-5177-11e9-9c8f-50cd31e28b24.png)

**Comment by ppiscuc** [comment]
@adidahiya in your first example, the difference between end time and start time = 0
in the second example, the difference between endtime and start time = 0 

I fail to understand how today = a 0 range, and yesterday = a 0 range

The same for a week with minutes selected: the difference between endtime and starttime is 6 days (for example: Sunday, March 24, 2019 12:00 AM -> Saturday, March 30, 2019 12:00 AM ), not 7 days. 

The issue is not the single date range picker, although there the issue is the most visible. The issue is that the range picker with minutes makes every period with 24h less (today range: 0 minutes, yesterday:0 minutes, a week ago: 6 days etc.)

**Comment by adidahiya** [comment]
Ah, sorry, you're right, I see the problem. I wasn't paying close enough attention to the minutes. Yes, I think this is a bug, the range should be 24h, not 0h
