### ISSUE TITLE
Cannot spread IButtonProps with react 16.8.5

### ISSUE THREAD

**Issue by explosivose** [palantir/blueprint#3450]
#### Environment

- __Package version(s)__: blueprint/core@2.1.1, React 16.8.5 (just upgraded from 16.3), typescript 3.3

#### Steps to reproduce

1. 
```
render() {
  const {buttonProps} = this.props; // type is IButtonProps
  <Button // compile error
    {...buttonProps} 
  />
}
```

#### Actual behavior
It looks like `React.ButtonHTMLAttributes<T>` has narrowed the button type from `string | undefined` to `'button' | 'submit' | 'reset' | undefined`

```
Type '{} | { active?: boolean | undefined; alignText?: Alignment | undefined; elementRef?: ((ref: HTMLElement | null) => any) | undefined; fill?: boolean | undefined; large?: boolean | undefined; ... 10 more ...; className?: string | undefined; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<IButtonProps & ButtonHTMLAttributes<HTMLButtonElement>> & Readonly<{ children?: ReactNode; }>'.
  Type '{ active?: boolean | undefined; alignText?: Alignment | undefined; elementRef?: ((ref: HTMLElement | null) => any) | undefined; fill?: boolean | undefined; large?: boolean | undefined; ... 10 more ...; className?: string | undefined; }' is not assignable to type 'Readonly<IButtonProps & ButtonHTMLAttributes<HTMLButtonElement>>'.
    Types of property 'type' are incompatible.
      Type 'string | undefined' is not assignable to type '"button" | "submit" | "reset" | undefined'.
        Type 'string' is not assignable to type '"button" | "submit" | "reset" | undefined'.
```

#### Expected behavior

No typescript compilation error

#### Possible solution

Use the same type as React for the `type` attribute in `IButtonProps`?

**Comment by adidahiya** [comment]
Which version of `@types/react` do you have installed? That's the one that matters, the `react` version doesn't really matter

**Comment by adidahiya** [comment]
Also if you could find the commit in DefinitelyTyped which caused this break, that'd be super helpful

**Comment by explosivose** [comment]
`"@types/react": "^16.8.10",`

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4d371be185ddd77264a8d7f30a7f7f8912738ed8#diff-96b72df8b13a8a590e4f160cbc51f40c

**Comment by adidahiya** [comment]
This is a tricky one... I don't think we can fix this without upgrading `@types/react` in this project, since expose some of those types directly on the `Button` API. But that upgrade would then force Blueprint consumers to also upgrade their react types, which will be breaking (I tried doing this recently, it wasn't pretty)...

**Comment by explosivose** [comment]
okay thanks. In the meantime my workaround is:
```
// workaround for this issue
// https://github.com/palantir/blueprint/issues/3450
interface FixButtonProps extends IButtonProps {
  type?: 'button' | 'submit' | 'reset';
}
interface Props {
  buttonProps: FixButtonProps;
}
export const MyComponent = (props: Props) => {
  return (
    <Button
      {...props.buttonProps}
    />
  );
}
```

**Comment by adidahiya** [comment]
Fixed by https://github.com/palantir/blueprint/pull/3608
