### ISSUE TITLE
Swipeable drawer feature for mobile websites

### ISSUE THREAD

**Issue by Darkness126** [palantir/blueprint#3456]
#### React 16

- __Package version(s)__: blueprint 3.14.1
- __Browser and OS versions__: chrome, android

#### Question

Is there a way to show drawer on swipe from any side of the screen on mobile devices? I have implemented a side navigation bar using the drawer and this swipe feature would be a great addition.

**Comment by adidahiya** [comment]
No, this isn't currently possible and it's a low priority for blueprint because we focus on desktop interactions. But if you had a proposal for a PR to contribute this, we might consider it.
