### ISSUE TITLE
Regex Icon Suggestion

### ISSUE THREAD

**Issue by kwojcicki** [palantir/blueprint#3459]
#### Feature request

It would be helpful to have a regex icon such as in vscode to indicate a user can switch a text field/input to allow regex. Apologies if one already exists but I couldnt find a decent one.

#### Examples

![image](https://user-images.githubusercontent.com/2487946/55413595-9e5d7d00-5537-11e9-834a-e8246d00d7d6.png)

**Comment by adidahiya** [comment]
Unfortunately we don't take icon requests from outside Palantir (plenty of icons to maintain already), so I'll have to close this for now. Tagging @pkwi in case he was planning on adding this one to the icon set anyway...
