### ISSUE TITLE
The doc suggests a way to pass <Icon ...> to a button (instead of just an icon name) that does not work as expected

### ISSUE THREAD

**Issue by galdebert** [palantir/blueprint#3462]
#### Environment

- __Package version(s)__: @blueprintjs.core 3.14.1
- __Browser and OS versions__: chrome 73.0.3683.86 Windows 10 OS Build 17134.648

minimal repro: https://codesandbox.io/s/myr2qw6pyy

#### Steps to reproduce

1. write
```
        <Button text="the button text">
          <Icon icon={IconNames.ADD} iconSize={10} />
        </Button>
```
 
#### Actual behavior

The button is not positioned properly as if we wrote
```
        <Button icon={<Icon icon={IconNames.ADD} iconSize={10} />}>
          the button text
        </Button>
```

#### Expected behavior

Well the current behavior is fine, but the doc says "Icons can also be supplied as children using the Icon component" which suggests we can pass icon as a child with the same result as passing it as a icon prop.

#### Possible solution

In the doc, say something like
- if you want to pass a custom Icon, use `<Button icon={<Icon icon={IconNames.ADD} iconSize={10} />}>`
- passing multiple children to Button will place them inline with the passed text

**Comment by adidahiya** [comment]
I can confirm this is still an issue in Blueprint v5.x, I made this sandbox to demonstrate: https://codesandbox.io/p/sandbox/condescending-sun-mwmsrm

In particular, the padding looks quite bad if there is just an icon and text (no icon on the right or any other HTML element):

![image](https://github.com/palantir/blueprint/assets/723999/dd46e952-24cb-451e-bed3-5e5e0c10f9b0)

I think the docs should be updated to remove the line "Icons can also be supplied as child elements using the [Icon](https://blueprintjs.com/docs/#core/components/icon) component."
