### ISSUE TITLE
Documentation site not working on IE11

### ISSUE THREAD

**Issue by Keats** [palantir/blueprint#3463]
#### Environment

- __Package version(s)__: master + whatever is deployed on the docs site
- __Browser and OS versions__: Windows 10/IE 11

If possible, ink to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/nko3k41y60)): https://blueprintjs.com/docs/

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/ with IE11

#### Actual behavior

White screen

#### Expected behavior

See the documentation site

#### Possible solution

Ensure that arrow functions for the doc app are properly transpiled. I am getting some ugly lists after fixing that manually (only 2 places where it happens: documentalist and linkify) but could be the results of some other issues.

**Comment by adidahiya** [comment]
Should be fixed in the latest release.

**Comment by adidahiya** [comment]
Oops, meant to link this to https://github.com/palantir/blueprint/pull/3482
