### ISSUE TITLE
DateInput -- Getting parseDate is not a function error at onChange event

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#3465]
Hi!

As i said i'm getting an error message at onChange event of DateInput

"**parseDate is not a function (dateinput.js:264)**"

I think that i need to upgrade blueprint components and i updated today (core, datetime... etc..)

But still getting same error message

**Comment by raiju** [comment]
This might be the same issue as https://github.com/palantir/blueprint/issues/2196

**Comment by adidahiya** [comment]
If this is still an issue, please provide a code sandbox repro and I will re-open.
