### ISSUE TITLE
DateRangeInput onChange's signature inaccurate

### ISSUE THREAD

**Issue by matthieu-beteille** [palantir/blueprint#3470]
The `DateRangeInput` can call its `onChange` handler will `null` values in the range (as mentioned in the following comment):
https://github.com/palantir/blueprint/blob/44043fd6bd195cd08b3399ba242031d8bd260405/packages/datetime/src/dateRangeInput.tsx#L95-L104

But the `DateRange` type doesn't include `null` in its signature:
https://github.com/palantir/blueprint/blob/44043fd6bd195cd08b3399ba242031d8bd260405/packages/datetime/src/common/dateUtils.ts#L19

It seems like throughout your codebase you use double equals to check for `null`/`undefined` values (```value == null```) so you wouldn't run into this issue. 

But on stricter codebases which want to be more explicit, if we follow the types we would only check for ```=== undefined``` when the value could also potentially be ```null```.

**Comment by adidahiya** [comment]
This is true across virtually all of blueprint's type definitions because we don't use the `strictNullChecks` compiler option. Everything is potentially null. We'd like to enable this option, but it's a large change to make across the codebase.
