### ISSUE TITLE
Why new size of library increased for 128KB?

### ISSUE THREAD

**Issue by HZ-labs** [palantir/blueprint#3472]
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.15.1
- __Browser and OS versions__: 

#### Question

Why new size of library increased for 128KB? I think it is very expensive. 
My old Environment:
__@blueprintjs/core__: 3.14.1

**Comment by adidahiya** [comment]
how did you get that file size? when we switched to the Apache-2.0 license in #3457, the copyright header comments increased in size. if you strip comments from JS in your builds then the library size change should not be significant.

**Comment by HZ-labs** [comment]
My apologies, I think after install new version I started using two version of the lib, but I don't know how it happened.
