### ISSUE TITLE
Dialog closes on  submenu selection

### ISSUE THREAD

**Issue by coolgrl8** [palantir/blueprint#3473]
I am trying to open a dialog from a menu.. but whenever the menu is clicked  - the dialog opens for a very brief  and closes . I think it closes when the menu closes.   I tried to use the `popoverProps={{ usePortal: false  }}` but that didnt work either.  any other ideas?

```ts
                return (
                    <MenuItem
                        text="Main menu"
                    >
                        <MenuItem
                            text="Sub menu 1"
                            onClick={() => {
                                this.openmydialog();
                            } }
                        />
                        <MenuItem
                            disabled
                            text="submenu 2(Coming Soon)"
                        />
                    </MenuItem>
                );
```

**Comment by swist** [comment]
Give your menu item `shouldDismissPopover={false}`

**Comment by adidahiya** [comment]
@coolgrl8 what does `this.openmydialog()` do exactly? it would be helpful if you had a full code sandbox to demonstrate the issue

**Comment by coolgrl8** [comment]
sorry for the delay in replying --thanks @swist -- yes shouldDismissPopover={false} worked. but The menu  was still open although transparent.  Any idea how to close the menu but open the dialog ? 
@adidahiya  its a simple dialog which  has some text boxes and selects.. -- will try to add some code ..

**Comment by nrathi** [comment]
@coolgrl8 did you figure out a solution? I'm having the same problem.

**Comment by rdugi** [comment]
shouldDismissPopover={false} worked for me .. I  know there were some refinements that had to be done..  but never fixed it.. :-) .
So were you able to fix it ? what do you mean `controlling the popover and dialog state, and closing them together`

**Comment by nrathi** [comment]
This is simplified pseudo-code so forgive any errors:
```
const handleTargetClick = () => this.setState({isPopoverOpen: !this.state.isPopoverOpen});
const handleContentClick = () => this.setState({isDialogOpen: true });
const handleDialogClose = () => this.setState({isPopoverOpen: false, isDialogOpen: false});

const target = <Button onClick={handleTargetClick} .../>
const content = <Menu><MenuItem onClick={handleContentClick} .../></Menu>;

return (
  <>
    <Popover isOpen={this.state.isPopoverOpen} target={target} content={content} .../>
    <Dialog isOpen={this.state.isDialogOpen} onClose={handleDialogClose} .../>
  </>
);
```
