### ISSUE TITLE
DateInput popover closes when clicking TimePicker arrow after changing month

### ISSUE THREAD

**Issue by gjvoosten** [palantir/blueprint#3474]
#### Environment

- __Package version(s)__: @blueprintjs/datetime 3.19.0, @blueprintjs/datetime 3.14.0
- __Browser and OS versions__: FF, Chrome, IE11

#### Steps to reproduce

Make the following change to the DateInput example:
```diff
diff --git a/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx b/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
index ada2350..ffc6ddb 100644
--- a/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
+++ b/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
@@ -59,6 +59,7 @@ export class DateInputExample extends React.PureComponent<IExampleProps, IDateIn
                     defaultValue={new Date()}
                     onChange={this.handleDateChange}
                     popoverProps={{ position: Position.BOTTOM }}
+                    timePickerProps={this.state.timePrecision ? {showArrowButtons: true} : undefined}
                 />
                 <MomentDate date={date} />
             </Example>
```
then:
1. set the **Date format** to _YYYY-MM-DD HH:mm:ss (moment)_
1. set the **Time precision** to e.g. _Minute_
1. click in the date input field
1. go to the previous (or next) month
1. click one of the time picker arrows (up or down)

#### Actual behavior

The DateInput popover is closed, time in the input field is unchanged.

#### Expected behavior

The DateInput popover stays open, time in the input field is updated.

#### Possible solution

The whole thing appears to balance on how `registerPopoverBlurHandler()` in `dateInput.tsx` works: when clicking next/previous month, this registers a blur handler. When clicking on a time picker arrow (an svg), `e.relatedTarget` inside `handlePopoverBlur(e)` is `null`/`undefined` and `document.activeElement` is `<body>` (that is, since `3.9.0` i.e. my own PR https://github.com/palantir/blueprint/pull/3471 — not that it is functionally any different for `3.8.0`). So the code assumes there was a click somewhere else and closes the popover.

I've looked into various approaches to tackle this, but haven't found anything that would fit. I'm willing to help make this work, let me know!

**Comment by maullerz** [comment]
Happens to me also. DateInput's Popover with `showArrowButtons` doesn't catch clicks on arrow buttons and closes.

```
    "@blueprintjs/core": "^3.29.0",
    "@blueprintjs/datetime": "^3.18.3",
```

**Comment by IzaGz** [comment]
Same problem , all latest versoins installed, please help!
