### ISSUE TITLE
Cannot type TagInput onChange as string[]

### ISSUE THREAD

**Issue by thelastnode** [palantir/blueprint#3477]
#### Environment

- __Package version(s)__: `"@blueprintjs/core": 3.15.1`
- __Browser and OS versions__: N/A

Minimal repro: https://codesandbox.io/s/2pz12p278r?fontsize=14

#### Steps to reproduce

1. Use `<TagInput />` with `strict: true` and `onChange: (newValues: string[]) => ...`

#### Actual behavior

```
Type '(newValues: string[]) => void' is not assignable to type '(values: ReactNode[]) => boolean | void'.
  Types of parameters 'newValues' and 'values' are incompatible.
    Type 'ReactNode[]' is not assignable to type 'string[]'.
      Type 'ReactNode' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.ts(2322)
```

#### Expected behavior

A way of typing the `onChange` callback without getting type errors.

#### Possible solution

Maybe `<TagInput<string[]> />`? Or maybe this is fixable in the current typings.

**Comment by adidahiya** [comment]
Hmm yeah that's annoying... I think we could solve this by making `TagInput` generic like `Select`, but it would be a breaking change...

a quick test also tells me that the following does not work:

```
interface ITagInputPropsGeneric<T> {
    values: T[];
    onChange: (values: T[]) => boolean | void;
}

type ITagInputProps = ITagInputProps<string | React.ReactChild>
```

so I guess we could introduce a generic version of the type now, to fix your issue, and replace the current `TagInput` with that generic one at the next major version

**Comment by thelastnode** [comment]
Could a generic component with `React.ReactNode[]` default work?

```tsx

interface ITagInputProps<T> {
    values: T[];
    onChange: (values: T[]) => boolean | void;
}

class TagInput<T = React.ReactNode[]> extends React.Component<ITagInputProps<T>> {
}
```

**Comment by adidahiya** [comment]
ah yes, that would work. `Tree` works like this

**Comment by tanmoyopenroot** [comment]
```javascript
interface ITagInputProps<T = React.ReactNode> {
    values: T[];
    onChange: (values: Array<string | T>) => boolean | void;
}
```

onChange will have the above signature because of the following line
`onChange([...values, ...newValues])` where `values` is of type T[] and `newValues` is of type string[]
we get `newValues` from  the `<Input />`
[check TagInput.tsx file for Line 289](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tag-input/tagInput.tsx#L289)

Eg:
For example in the code below `newValues` will be of type `React.ReactText[]`
```javascript
   <TagInput
      values={[1, 2]}
     onChange={(newValues: React.ReactText[]) => console.log(newValues)}
   />;
```

But for code below `newValues` will be of type `string[]`
```javascript
   <TagInput
      values={["ABC", "DEF"]}
     onChange={(newValues: string[]) => console.log(newValues)}
   />;
```

Any thoughts?

**Comment by adidahiya** [comment]
There have been some recent changes to the TagInput API... closing this issue in favor of https://github.com/palantir/blueprint/issues/4390
