### ISSUE TITLE
TextArea growing on every onChange when growVertically set to true

### ISSUE THREAD

**Issue by himselfego** [palantir/blueprint#3478]
#### Environment

- __Package version(s)__:  3.15.1
- __Browser and OS versions__: Windows 10, Chrome 73.0.3683.86 (Official Build) (64-bit)

#### Steps to reproduce

1. Add <TextArea> to any page
1. Set growVertically attribute
1. Start typing or pasting any text

#### Actual behavior

TextArea is growing on every onChange event.

#### Expected behavior

Growing only when you need to accommodate text.

**Comment by adidahiya** [comment]
I can't reproduce this in the code sandbox on macOS on Chrome. Does the issue show up for you here? https://codesandbox.io/embed/qzl1rm2994

**Comment by himselfego** [comment]
Nope. My project was written in JavaScript, maybe thats the problem? 
This issue show up here: https://codesandbox.io/s/rlm6w95kko

**Comment by adidahiya** [comment]
You haven't imported blueprint CSS.

**Comment by himselfego** [comment]
Oh. My bad. Sorry for your time
