### ISSUE TITLE
NumericInput throws type error when value=null

### ISSUE THREAD

**Issue by westrickc** [palantir/blueprint#3479]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.15.1
- __Browser and OS versions__: Chrome 73.0.3683.103, Windows 7

__Minimal repro__: https://codesandbox.io/s/j7r4p4kpy3

#### Steps to reproduce

1. Set the value of a NumericInput to null

#### Actual behavior

Component throws "TypeError Cannot read property 'toString' of null"

#### Expected behavior

Display an empty NumericInput box.

I was using blueprintjs/core 3.7.0, and null values would result in an empty numeric input box just as I expected. When I updated to blueprintjs/core 3.15.1, I started seeing the type error.

The [Controlled Mode](https://blueprintjs.com/docs/#core/components/numeric-input.controlled-mode) example initializes the NumericInput value to null. So I expected it to work. But now I see that the documentation for the `value `prop clearly states it's type is `number|string` which excludes null values. So this is arguably a usage error on my part.

#### Possible solution

Maybe update the example in the documentation to initialize the value to "" instead of null. The example also has some syntax errors (missing => in the handleValueChange function definition).

**Comment by adidahiya** [comment]
Yes I think it's a documentation issue, thanks for filing it. Looks like the best value might actually be `NumericInput.VALUE_EMPTY`
