### ISSUE TITLE
Date range picker inconsistent Date

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#3480]
- __Package version(s)__: 3.6.0 +
- __Browser and OS versions__: Linux, Firefox 67.0b10 

I post this here but i'm not sure if it's an issue with Blueprint itself or with React day picker.

When i try to pick a date with DateRangePicker (without Time only days) for example 30/01/2019 i received the following Date object `2019-01-29T23:00:00.000Z`.  
I think you should received something like that : `2019-01-30T00:00:00.000Z`

date picker configuration :      
```ts
      <DateRangePicker
        contiguousCalendarMonths={false}
        dayPickerProps={{
          containerProps: {
            id: 'compliance-dates-rangepicker',
          },
        }}
        onChange={handleRangeChange}
        value={range}
        maxDate={dayjs(`${dayjs().year() + 20}-12-31`).toDate()}
        shortcuts={false}
      />
```

**Comment by adidahiya** [comment]
This might be related to https://github.com/palantir/blueprint/issues/3449. Can you reproduce this in a code sandbox?

**Comment by LoiKos** [comment]
I finally got it ... After some tests, it seems that there is no bug. The thing is when you pick date and you try to log them in the console they are parse to ISO string which show a wrong day but the date is correct. 

https://codesandbox.io/s/wkz1lwq29k?fontsize=14
