### ISSUE TITLE
<Suggest resetOnClose="false" unexpected behavior

### ISSUE THREAD

**Issue by colinmegill** [palantir/blueprint#3483]
#### Environment

    "@blueprintjs/core": "^3.8.0",
    "@blueprintjs/icons": "^3.3.0",
    "@blueprintjs/select": "^3.2.1",

Chrome 73.0.3683.103 (Official Build) (64-bit)
MacOS Mojave 10.14.4

#### Question

Expected behavior: 

```
<Suggest
   resetOnClose={false}
```

would preserve the input on loss of focus. The flag seems to have no effect, and the behavior is: 

![resetonclose](https://user-images.githubusercontent.com/1770265/56252175-7e67a680-606b-11e9-87df-16b7e2e8e1e1.gif)

Are there any other props which would override the input state and interfere with `resetOnClose`? My instance looks like this:
```
            <ControlGroup>
              <Suggest
                resetOnSelect
                closeOnSelect
                resetOnClose={false}
                itemDisabled={
                  foo ? () => true : () => false
                }
                noResults={<MenuItem disabled text="No matches." />}
                onItemSelect={g => { this.handleClick(g); }}
                inputProps={{ "foo1": "bar1" }}
                inputValueRenderer={g => {
                  return "";
                }}
                itemListPredicate={baz}
                itemRenderer={renderFoo.bind(this)}
                items={
                  foo ? 
                    ? bat.asArray()
                    : ["Nothing"]
                }
                popoverProps={{ minimal: true }}
              />
              <Button
                className="bp3-button bp3-intent-primary"
                data-testid={"foo-button"}
                loading={fooLoading}
              >
                Add
              </Button>
            </ControlGroup>
```

**Comment by adidahiya** [comment]
1. `resetOnClose` was not added until v3.6.0: https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjsselect-360 (using typescript would help you identify this issue)
2. Please try to include a code sandbox repro link for bugs (it's in the issue template)

**Comment by colinmegill** [comment]
Thanks! I filed this under support since I didn't know if it was my bug, will try a repro if I hit another one.
