### ISSUE TITLE
RadioGroup selectedValue doesn't affected by state on program startup

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#3488]
Hi, I added a Dialog which has a RadioGroup

```
state : {
  myValue : "0"
}

<RadioGroup selectedValue = {this.state.myValue}>
     <Radio label="test0" value = "0" />
     <Radio label="test1" value = "1" />
     <Radio label="test2" value = "2" />
</RadioGroup>
```

and a button which is changing state

```
      this.setState ( state => 
         {
        myValue = "2"
        return state
}         
)
```

state is changed when i clicked button, but i can't see "test0" radio is being not selected (no radio selected) on program startup.

Why? state.myValue has "0" default value

**Comment by adidahiya** [comment]
Please create a code sandbox repro (see the link in README or issue template)
