### ISSUE TITLE
TimePrecision inconsistent in DatePickerRangeExample

### ISSUE THREAD

**Issue by ibk6** [palantir/blueprint#3490]
#### Environment

node v10.15.3
yarn 1.12.3
@blueprintjs/core 3.15.1
@blueprintjs/datetime 3.9.0
Chrome 73
Ubuntu 18.04 x64

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#datetime/daterangepicker
2. select time precision as 'Minute'
3. select a range from shortcut
4. select time precision as 'None'

#### Actual behavior

Time inputs as well as time in final datetime labels doesn't hide

![image](https://user-images.githubusercontent.com/23393182/56426144-c76e6380-62d4-11e9-9bfc-e83578505c4f.png)

#### Expected behavior

Time inputs as well as time in final datetime labels should disappear

#### Possible solution

`TimePrecision` enum doesn't have a value as None

`<MomentDateRange withTime={props.timePrecision !== undefined} range={this.state.dateRange} />`

props.timePrecision !== TimePrecision.NONE condition can be added

**Comment by adidahiya** [comment]
This doesn't seem to be an issue in the latest docs with [DateRangePicker3](https://blueprintjs.com/docs/#datetime2/date-range-picker3)
