### ISSUE TITLE
Breadcrumb chevrons not aligned with text

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#3492]
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: Chrome 73

#### Steps to reproduce

1. Go to the [doc page](https://blueprintjs.com/docs/#core/components/breadcrumbs).

#### Actual behavior

![image](https://user-images.githubusercontent.com/4096676/56487215-14eafc00-64a0-11e9-9c2d-3345a594b665.png)

As you can see, the arrows aren't aligned with the text.

#### Expected behavior

Arrows are aligned.

**Comment by adidahiya** [comment]
@pkwi any thoughts on this?

**Comment by pkwi** [comment]
I guess this might be related to the specific typeface?

**Comment by shravan2x** [comment]
The screenshot is taken from the typeface on the docs page. I know it happens on at least 2 other fonts as well.

**Comment by adidahiya** [comment]
Looks like a Windows-specific issue. Are you using Windows @shravan2x?

**Comment by pkwi** [comment]
Good catch @adidahiya! This looks like an issue with Segoe UI font family.
