### ISSUE TITLE
Button/Form Border missing when Zoomed out

### ISSUE THREAD

**Issue by kujohn** [palantir/blueprint#3498]
#### Environment

- __Package version(s)__: 3.10.0
- __Browser and OS versions__: OS X - Safari, Firefox

#### Steps to reproduce

1. Zoom out a few times

#### Actual behavior

 Borders missing from form fields, selects, and buttons

#### Expected behavior

Border to be at a 1px minimum

#### Possible solution

Perhaps a change of px unit to rem

![Screen Shot 2019-04-25 at 5 52 50 PM](https://user-images.githubusercontent.com/1356936/56776781-f4ae8c00-6782-11e9-8f00-35bad96610f6.png)
![Screen Shot 2019-04-25 at 5 48 47 PM](https://user-images.githubusercontent.com/1356936/56776761-db0d4480-6782-11e9-9f23-efe07cf0609e.png)

**Comment by adidahiya** [comment]
Can you clarify "high resolution"? I can't repro this on my monitors. We use box shadow for borders.

**Comment by kujohn** [comment]
Omitting the 'high resolution' comment, doesn't look like it's happening.
