### ISSUE TITLE
Incorrect paths for @blueprintjs source maps that produce multiple warnings on project compilation

### ISSUE THREAD

**Issue by newtriks** [palantir/blueprint#3500]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.15.1
- __Browser and OS versions__: Chrome 73.0.3683.86, OS X 10.14.4 

If possible, link to a minimal repro: https://github.com/newtriks/bp_example

#### Steps to reproduce

1. `npm install --save @blueprintjs/core @blueprintjs/datetime`
1. `cd node_modules/@blueprintjs/datetime/lib/css/`
1. Check path in `blueprint-datetime.css.map` for `_variables.scss`
1. Using path list dir for `_variables.scss` e.g. `ls ../../../../node_modules/@blueprintjs/core/src/common/`

#### Actual behavior

Output: `ls: ../../../../node_modules/@blueprintjs/core/src/common/: No such file or directory`

This was discovered by all the warnings on compilation of the project:

![Screenshot 2019-04-26 at 14 07 43](https://user-images.githubusercontent.com/31971/56810175-88d52d80-682d-11e9-8aec-93598c0f6971.png)

#### Expected behavior

Outputs files in the common directory e.g. the source map points to the correct file

#### Possible solution

Step up another directory e.g. `ls ../../../../../node_modules/@blueprintjs/core/src/common/`

Output:

```
_color-aliases.scss             alignment.ts                    intent.ts
_colors.scss                    boundary.ts                     interactionMode.ts
_flex.scss                      classes.ts                      keys.ts
_mixins.scss                    colors.ts                       position.ts
_react-transition.scss          constructor.ts                  props.ts
_variables.scss                 elevation.ts                    utils
abstractComponent.ts            errors.ts                       utils.ts
abstractPureComponent.ts        index.ts
```

Seems the same as this closed issue: https://github.com/palantir/blueprint/issues/2728

**Comment by jonasws** [comment]
I did some research on this, and this behavior is caused by the monorepo structure of the blueprint repository. 

I was unable to find a straightforward solution to fix this. One solution is to "patch" the `blueprintjs.css.map` file to replace the entries referencing the wrong `node_modules` location, but this may be "hacky", if another solution exists.

One could create a `pre-release`-script f. eks that would transform (showing only the entries at fault):
```json
{
  "version": 3,
  "sources": [

    "../../../../node_modules/@blueprintjs/icons/src/_icons.scss",

    "../../../../node_modules/@blueprintjs/icons/src/generated/_icon-variables.scss",

    "../../../../node_modules/@blueprintjs/core/src/common/_react-transition.scss",
  ],
  "names": [],
  "file": "blueprint.css"
}
```
into
```json
{
  "version": 3,
  "sources": [

    "../../node_modules/@blueprintjs/icons/src/_icons.scss",

    "../../node_modules/@blueprintjs/icons/src/generated/_icon-variables.scss",

    "../../node_modules/@blueprintjs/core/src/common/_react-transition.scss",
  ],
  "names": [],
  "file": "blueprint.css"
}
```

If this would be an acceptable solution, I would be happy to put in the time to implement it.

**Comment by MaximeBernard** [comment]
I just encountered the same issue using Parcel.

Any update on this? Any workaround?

**Comment by 0xhjohnson** [comment]
Experiencing same issue using parcel@1.12.4

**Comment by Dilks44** [comment]
I am still experiencing this issue, could we get an update here?

**Comment by Friedoo** [comment]
Still experiencing this issue :(

"@blueprintjs/core": "^3.51.3"
"webpack": "^5.67.0",
