### ISSUE TITLE
Style title which shows on hoverering over buttons

### ISSUE THREAD

**Issue by schroef** [palantir/blueprint#3505]
#### Environment
Version 1.33.1 (1.33.1)
Osx 10.11.6

#### Question
Im wondering how we can style the title which shows when hovering over buttons. The style is very basic and does not fit with the app. The title it shows is either the title given to a button or it automatically shows the name of an svg icon used.

I tried simple things like title, .title, but that didnt work of course.

**Comment by adidahiya** [comment]
Can you provide a screenshot? I think you are referring to an OS-specific title UI element, which we can't control from the browser. If you want a Blueprint-style tooltip, use a Tooltip component.

**Comment by schroef** [comment]
I had some issue getting on screen grab but i managed it now. Im thinking this is a browser related thing. I did some more research yesterday and believe this cant be changed.
This is how it looks when hovering over a button or icon which has title. Looks like standard browser styling
![auto-generated-tooltip](https://user-images.githubusercontent.com/6923008/56937186-64957d00-6ac9-11e9-94f5-0ef4f5f29819.jpg)


Title in SVG show as tooltip automatically
<img width="528" alt="Screen Shot 2019-04-29 at 21 24 07" src="https://user-images.githubusercontent.com/6923008/56937167-4cbdf900-6ac9-11e9-8719-851cc311cf25.png">


However i noticed that this tooltip also shows on all buttons when i use custom icons. These are export from illustrator and this adds title to them. After some more checking i noticed the Blueprintjs icons dont have this, they use <desc> instead of title. 
<img width="545" alt="Screen Shot 2019-04-29 at 21 50 34" src="https://user-images.githubusercontent.com/6923008/56937164-46c81800-6ac9-11e9-888c-b555367dda8c.png">


Ive now added a sort of custom tootltip by adding a data attribute and i deleted all titles in the svg files. I also changed all titles in buttons i had to a data attribute. I had some issue with this though that the tooltip on the right side of the app would go off screen. So i made a second attribute class for those, than the tooltip will show on the left side instead of right side.
<img width="320" alt="Screen Shot 2019-04-29 at 21 53 23" src="https://user-images.githubusercontent.com/6923008/56937161-4039a080-6ac9-11e9-81b4-910c9b3b15e7.png">

**Comment by adidahiya** [comment]
Nice, thanks for the screenshots. Yes, you may need to do some editing of SVG files exported from other programs for them to display nicely in the browser. Closing because it looks like you've managed to get the desired visual output... but I would still encourage you to try wrapping your `<Button>` with a `<Tooltip>` for "easy" Blueprint consistency

**Comment by schroef** [comment]
> Nice, thanks for the screenshots. Yes, you may need to do some editing of SVG files exported from other programs for them to display nicely in the browser. Closing because it looks like you've managed to get the desired visual output... but I would still encourage you to try wrapping your `<Button>` with a `<Tooltip>` for "easy" Blueprint consistency

THanks i did try that, but i find it adding way to much hustle and code. Using the data attribute is nice i think and cleaner. 

After checking more info about SVG, its seems they need to be almost stripped out of everything. I guess its a standard browser thing to show the title. But the button from blueprintjs does the same if you add title. I guess every component will do it when you add title. Some use title though the show info.

For now my data attribute fixes this. I add a section where i add all tooltips below each other and than add it to a button

<img width="499" alt="Screen Shot 2019-05-01 at 20 23 08" src="https://user-images.githubusercontent.com/6923008/57051329-0692a200-6c4f-11e9-8f7b-893ec3e31095.png">
![Uploading Screen Shot 2019-05-01 at 20.22.46.png…]()
