### ISSUE TITLE
@blueprintjs/select not using latest @blueprintjs/core version produces TS compile error 

### ISSUE THREAD

**Issue by louisbyrne89** [palantir/blueprint#3506]
#### Environment

- __Package version(s)__: @blueprintjs/select 3.8.0

#### Steps to reproduce

1. npm upgrade to latest @blueprintjs/core (3.15.1) and @blueprintjs/select versions
2. Create a Blueprint suggest component with inputProps prop provided

#### Actual behavior

This produces a TS compile error (see below)

> **Types of property 'leftIcon' are incompatible**.
>       Type 'false | "search" | Element | "error" | "add" | "add-column-left" | "add-column-right" | "add-row-bottom" | "add-row-top" | "add-to-artifact" | "add-to-folder" | "airplane" | ... 454 more ... | undefined' is not assignable to type 'false | "search" | Element | "error" | "add" | "add-column-left" | "add-column-right" | "add-row-bottom" | "add-row-top" | "add-to-artifact" | "add-to-folder" | "airplane" | ... 453 more ... | undefined'.
>         **Type '"inheritance"' is not assignable to type** 'false | "search" | Element | "error" | "add" | "add-column-left" | "add-column-right" | "add-row-bottom" | "add-row-top" | "add-to-artifact" | "add-to-folder" | "airplane" | ... 453 more ... | undefined'
> 

#### Expected behavior

No Compile error.

#### Possible solution

Upgrade blueprintjs/core dependency of blueprint/select to 3.15.1

**Comment by adidahiya** [comment]
Can you reproduce this in a code sandbox?
