### ISSUE TITLE
Docs: "what's new" link is broken in the docs homepage

### ISSUE THREAD

**Issue by warpdesign** [palantir/blueprint#3511]
![Capture d’écran 2019-05-01 à 17 44 19](https://user-images.githubusercontent.com/199648/57025957-e22bcb00-6c38-11e9-8695-c2ef5836c19a.png)

Not sure where it's supposed to point.

See: https://blueprintjs.com/docs/

**Comment by adidahiya** [comment]
duplicate of #3487
