### ISSUE TITLE
Doc side panel prop definitions not scrolling 

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#3512]
The only way to see more content here:
![image](https://user-images.githubusercontent.com/2730609/57093020-aee14e80-6cc1-11e9-8d1a-bb9b8afe28e1.png)

is to make the window zoom smaller:

![image](https://user-images.githubusercontent.com/2730609/57093035-b6a0f300-6cc1-11e9-8bcc-be8b1ead6ddd.png)

The scrollbar doesn't seem to be showing up.

**Comment by giladgray** [comment]
@tnrich I cannot reproduce this. it scrolls just fine for me on the latest docs site.

**Comment by tnrich** [comment]
Hmmm I think this might be related to the nasty new chrome bug that blocks scrolling seemingly at random on certain machines..

**Comment by adidahiya** [comment]
Yeah I can repro this on Chrome 74.0.3729.131 on macOS

**Comment by adidahiya** [comment]
Fixed by #3576
