### ISSUE TITLE
Time Picker only triggers onChange on "change" event and not "input" event

### ISSUE THREAD

**Issue by Khrall** [palantir/blueprint#3513]
#### Environment

- __Package version(s)__:  3.15.1
- __Browser and OS versions__: Chrome 73.0.3683.103, Mac OS High Sierra

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#datetime/datepicker
1. Set Time Precision = `minute`
1. Click a date (selected value is instantly registered below the date picker)
1. Click the time and update it, changes are not registered until you hit enter or click outside the input element.

#### Actual behavior

Changes to the time is not registered before un-focusing the input element (triggering the `change` event).

#### Expected behavior

Changes to the time is registered as soon as a new time is input (triggered by the `input` event). Calling this a bug might be a stretch, but I'm not the only one that thinks that this behaviour should be expected.

#### Possible solution

Changing the Time Picker to listen for `input` events rather than `change` events. I can imagine there being good reasons for not listening to `input` event, but I'm not aware of them.

**Comment by adidahiya** [comment]
I think #3502 just fixed this
