### ISSUE TITLE
Feature Request: Drawer option to not render overlay

### ISSUE THREAD

**Issue by domehead100** [palantir/blueprint#3515]
#### Environment

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome, Windows

#### Feature request

It would be nice to have an option on the Drawer to not render an overlay so that the Drawer does not block access to other visible parts of the UI when it is open.

Kind of the opposiste of https://github.com/mui-org/material-ui/issues/10993 and would behave like the MUI "Persistent Drawer" in that it does not render an overlay and thus allows access to the not-covered-up content on the page.

#### Examples

https://material-ui.com/demos/drawers/#persistent-drawer

**Comment by giladgray** [comment]
@domehead100 this exists: `<Drawer hasBackdrop={false}>`

**Comment by adidahiya** [comment]
Yeah, I think you can achieve this with `hasBackdrop={false}` and custom behavior in your `onClose` handler. Let us know if that doesn't work for your use case.

**Comment by jdpaterson** [comment]
I have this issue, I don't think hasBackdrop solves it. Here is a sandbox: https://codesandbox.io/s/confident-boyd-8mg7s . I would like to be able to edit inputs while a drawer is open.

**Comment by zdzarsky** [comment]
Is it supposed to be done? I would love to have this feature in my new project.

**Comment by zdzarsky** [comment]
Hi! You can easilly cheat it by overriding `pointer-events` selector in the top-level CSS file:
```
.bp3-overlay{
  pointer-events: none;
}

.bp3-overlay-content {
  pointer-events: all;
}
```

**Comment by zdzarsky** [comment]
All in all, I think you can easilly add this feature by adding one more CSS class.

**Comment by domehead100** [comment]
This is a bit old due to the repo having been locked down to committers only a while back.

Problem was that hasBackdrop did not solve it because even when that was false a backdrop was still being rendered and covering all of the other content on the page.

Pointer events didn't solve it either, since it would allow clicking on, for example, inputs beneath the backdrop, but then the user was unable to interact with the inputs via the keyboard.

Our solution was to add a class name and then style the backdrop to just have the same position and dimensions as the drawer, so even though it was there it was totally behind the drawer.

Hope this helps...

**Comment by ucg8j** [comment]
I also have this issue. My setup:
```json
"@blueprintjs/core": "^3.50.2",
"react": "^17.0.2",
```

What I've tried:
- `hasBackdrop={false}` doesn't work, an overlay component still renders covering the entirety of the page, preventing pointer events on other elements of the UI.
- have also edited the CSS to include @zdzarsky 's suggested inclusions. This does work. However (for me) it introduces bugs on other components that have pointer events e.g. a select dropdown on a navbar component.


Comment: A collapsible sidebar component is a pretty common need. I've seen on other Blueprint issues the `Drawer` component being recommended by the core contributors. However having a working and recommend way of creating such a component with Blueprint would be really helpful to users.

**Comment by el-j** [comment]
For the latest version of the MUI Drawer, i found this working solution for me:
```jsx
<Drawer
      PaperProps={{
        style: {
            //menu styles      
          },
      }}
      variant={'temporary'} // standard
      ModalProps={{
        slots: { backdrop: "div" }, // override backdrop component standart
        slotProps: {
          root: {
            // override backdrop position+size
            style: {
              position: "absolute",
              top: "unset",
              bottom: "unset",
              left: "unset",
              right: "unset",
            },
          },
        },
      }}
    >
```
https://stackoverflow.com/questions/58020202/mui-remove-overlay-in-drawer/74992716#74992716

**Comment by htelferAptiv** [comment]
Very late but another possible quick fix:

Setting the portal class name to something like:  `portalClassName={"bp4-portal map_settings_drawer"}` 
then allows you to use a css selector like: `.map_settings_drawer>div:first-child`
which then forces the overlay for that specific Overlay using UI component to get out of the way.

In my issue of a Blueprint Drawer getting in the way of interacting with a embedded Leaflet map, this worked well without upsetting other parts of my application
