### ISSUE TITLE
Horizontal bar chart y-axis (categorical) pans in opposite direction

### ISSUE THREAD

**Issue by Sktank** [palantir/blueprint#3517]
#### Environment

"@elements/blueprint-chart": "7.5.0",
"@blueprintjs/core": "3.15.1",

#### Steps to reproduce

1. Create a horizontal bar chart
2. Zoom in a couple times
3. Pan up/down using the toolbar arrows

#### Actual behavior

Panning on the up-arrow icon pans down the categorical axis.
Panning on the down-arrow icon pans up the categorical axis.

#### Expected behavior

The opposite.

#### Possible solution

Switch the pan direction

**Comment by adidahiya** [comment]
blueprint-chart is not open source; please file in the internal github
