### ISSUE TITLE
Alert: ability to invert cancel/confirm buttons position

### ISSUE THREAD

**Issue by warpdesign** [palantir/blueprint#3518]
Use case: native applications may have different position for confirm/cancel buttons.

For example:
- Windows: OK Cancel
- macOS: Cancel OK

It would be great to have a new prop in the Alert component that allows changing the position of cancel/confirm buttons.

As a workaround, the `order` CSS property can be used to invert the buttons' position.

**Comment by adidahiya** [comment]
If you want a custom Alert, you should make your own Dialog. The Alert component is opinionated by design and we'd like to add avoiding much configuration to it.
