### ISSUE TITLE
Unable to dismiss context menu for Table component

### ISSUE THREAD

**Issue by johnwquarles** [palantir/blueprint#353]
### Bug report

- __Package version(s)__: Core: 1.3.0, 1.3.1; working in 1.2.0. Table: 1.2.0
- __Browser and OS versions__: Chrome 54.0.2840.98 (64-bit), OSX El Capitan

#### Steps to reproduce

1. Create a (blueprintjs) `<Table>` and provide a `renderBodyContextMenu` function via that prop that will return a simple `<Menu>`, a la the example provided in the documentation. In my case, right now there are just two `<MenuItem>`s that don't do anything yet.

2. Open said context menu with a right-click on the table, then try to dismiss it by left-clicking elsewhere on the table

#### Actual behavior

The context menu cannot be dismissed. The console displays the following error:
![screen shot 2016-12-12 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/8734556/21114861/3c36af48-c074-11e6-9791-5b49ca2bd1b6.png)

#### Expected behavior

The context menu to be dismissed, no errors in console.

**Comment by llorca** [comment]
Thanks for filing @johnwquarles, we're tracking as part of our micro-interaction work on the `Table` component: https://github.com/palantir/blueprint/issues/298

**Comment by llorca** [comment]
This was actually fixed by #427 which shipped last week in `@blueprintjs/table` 1.3.0! See how it's working beautifully in the examples: http://blueprintjs.com/docs/#components.table-js
