### ISSUE TITLE
Mention of "version 3.0" in docs

### ISSUE THREAD

**Issue by billyjanitsch** [palantir/blueprint#354]
(lil' nit :v:)

I noticed a mention of "version 3.0" in the [Dialog docs](https://github.com/palantir/blueprint/blob/a90bf1a4e5c20d7b379001c3f2de788271aaedf6/packages/core/src/components/dialog/dialog.tsx#L53). Given that Blueprint is currently at 1.3.1, I assume this is leftover from internal versioning?

**Comment by llorca** [comment]
@billyjanitsch great catch! 🌟
