### ISSUE TITLE
Style directly injected into div in tab indicator wrapper

### ISSUE THREAD

**Issue by lloydho** [palantir/blueprint#3567]
#### Environment

- "@blueprintjs/core": "^3.13.0",
- Mac OSX High Sierra

If possible, link to a minimal repro: https://codesandbox.io/embed/blueprint-sandbox-406il

#### Steps to reproduce

1. Create Tabs
1. Check the style of bp3-tab-indicator-wrapper

#### Actual behavior

Style is directly injected into style attribute

#### Expected behavior

Style should be included as class.

#### Possible solution

We should move as many of the styles that are not dynamic to classes.

**Comment by adidahiya** [comment]
Those are dynamic styles. Check out [the source](https://github.com/palantir/blueprint/blob/332ccb386df354b616fd2689053667e1e40e3b1e/packages/core/src/components/tabs/tabs.tsx#L274).

It would help if you tried to describe what you were trying to do, in addition to just suggesting a code change.

**Comment by dqunbp** [comment]
Hello! When I dynamically change the width of a tab element, `bp3-tab-Indicator-wrapper` does not change the width accordingly.
Possible solution - set the width to 100%? Or use resize detector?

**Comment by dqunbp** [comment]
I also have one more style remark - `margin-right` is not necessary  for vertical tabs
```scss
  // this is fine.
  // stylelint-disable-next-line selector-no-universal
  > *:not(:last-child) {
    margin-right: $pt-grid-size * 2;
  }
```

**Comment by adidahiya** [comment]
@dqunbp this is an old issue, please open a new one and fill out the issue template if you'd like further support
