### ISSUE TITLE
Input width on MultiSelect

### ISSUE THREAD

**Issue by CodeMaven** [palantir/blueprint#3573]
#### Environment

- __Package version(s)__: 
   "@blueprintjs/core": "^3.15.1",
    "@blueprintjs/select": "^3.8.0",
- __Browser and OS versions__:  Linux Mint 16, Firefox 66.03

#### Question

How can I make a MultiSelect component fill the width of the container? using 
tagInputProps={{fill:true }} 
doesn't seem to have any effect. I've also tried styling the component with CSS but the tag input box always remains at 150px and grows only as I add tags.

Additionally, I have an issue where the tags wrap but the box doesn't expand to accommodate. I.e. If I add more tags than can fit in the width of the container the  tags wrap to the next line but the box doesn't expand and the components below do not move so the new tags are superposed under the control below.
![MultiSelects](https://user-images.githubusercontent.com/8939073/58494793-d23ad480-816d-11e9-8294-48ac36c771f1.png)
![TagsWrapping](https://user-images.githubusercontent.com/8939073/58494813-dbc43c80-816d-11e9-9e63-6da2760fbd56.png)

**Comment by jpk0727** [comment]
I have the exact some questions

**Comment by adidahiya** [comment]
I think this is essentially the same as https://github.com/palantir/blueprint/issues/2931

Setting `popoverProps={ targetTagName: 'div' }` should allow you to use `fill: true`. I'll update the docs to mention this.
