### ISSUE TITLE
Support passing Popover props in ContextMenu.show (imperative usage)

### ISSUE THREAD

**Issue by GabiAxel** [palantir/blueprint#3577]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.15.1
- __Browser and OS versions__: any

#### Feature request

Add popoverProps parameter to ContextMenu.show method that would be passed to the created Popover to allow overriding the popover defaults (in my case I need to change the z-index)

#### Examples

```javascript
ContextMenu.show(menu, { left: 0, top: 0 }, undefined, false, { popoverClassName: 'my-popover-class' })
```

**Comment by adidahiya** [comment]
Hmm, I don't know if adding this API is the best approach... we'd also need to expose `popoverProps` in `ContextMenu`'s props. Why do you need to change the z-index? Can you achieve the same result by reordering your DOM layout or timing the opening of the ContextMenu differently? My advice is usually to avoid setting z indices whenever possible.

**Comment by GabiAxel** [comment]
In my case I am trying to use `ContextMenu` on a Leaflet map, which contains layers with higher z-index then the popover, so the context menu appears under some of them. Maybe I could change these layers' z-index but it wouldn't be any prettier than changing it for the popover, or my current workaround of adding this global css rule `.bp3-overlay-open .bp3-transition-container { z-index: 10000; }` , and I would always have to ensure that new layers have lower z-index than the popover instead of just setting a very high z-index for the popover. Do you have any recommendation how to deal with such case?

**Comment by adidahiya** [comment]
Instead of fighting a z-index battle with the library, can you isolate your context menu from Leaflet by putting the latter in its own [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context)?

**Comment by ericgla** [comment]
See [this gist](https://gist.github.com/ericgla/89576e6c01b7c6f1a77a5561f98c97c8) for an implementation of ContextMenu that allows you pass in all of the props for Popover...

**Comment by adidahiya** [comment]
Closing this as outdated and likely fixed by ContextMenu2 / showContextMenu (see [migration guide](https://github.com/palantir/blueprint/wiki/ContextMenu2-migration)). I'll re-open this issue if there are further requests for popover customization with the new APIs.
