### ISSUE TITLE
Allow the slider tooltip render to be separated from the label renderer

### ISSUE THREAD

**Issue by gerrod** [palantir/blueprint#3578]
#### Environment

Package version: @blueprintjs/core 3.15.1
Browser: Chrome 74+

#### Feature request

Allow a separate tooltip renderer on the slider, instead of just using the label renderer. The label renderer is a great fallback but sometimes the tooltip needs to be different.

#### Examples

We use a slider for stepping through data over a range of date/times - anything from the last hour to the last 30 days.

When the date range spans over multiple days, we render labels on the hour; but for midnight, we render the new date instead. Something like this -

![image](https://user-images.githubusercontent.com/865932/58680331-b708d880-83aa-11e9-9565-b8777013cb71.png)

The problem though, is that when the current value passes the date boundary, the tooltip shows the date instead of the time (due to the way that labels for the slider are generated):

![image](https://user-images.githubusercontent.com/865932/58680463-2c74a900-83ab-11e9-8f98-2ab894d92987.png)

We could get around this if either we had a separate renderer for the tooltips, OR if the renderer knew the "context" about where the label was being applied (that is, if we knew that the label was going to be attached as a tooltip instead of as a label on the slider itself, we would calculate the label's value differently.)

**Comment by adidahiya** [comment]
Seems like a reasonable request, accepting PRs
