### ISSUE TITLE
documentation bug for icon search

### ISSUE THREAD

**Issue by dixitk13** [palantir/blueprint#3579]
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: macOS 10.14.5, Chrome: 74.0.3729.169

<strike>
If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/nko3k41y60)): 
</strike>

#### Steps to reproduce

1. visit https://blueprintjs.com/docs/#icons
1. try selecting the icon dropdown. 
1. now try typing something in the dropdown

#### Actual behavior
the results just show calendar as the search result without any search query but the results show up if you type the query in 

screenshots attached 
![Screen Shot 2019-05-31 at 1 32 46 PM](https://user-images.githubusercontent.com/8632659/58733427-5f1da200-83a9-11e9-8da6-b638435bbaa6.png)
![Screen Shot 2019-05-31 at 1 32 54 PM](https://user-images.githubusercontent.com/8632659/58733429-5f1da200-83a9-11e9-956e-c22269ef0585.png)

#### Expected behavior
the search show allow seeing all the results when the search query is empty

**Comment by adidahiya** [comment]
why?

you can look at all the icons right below that example. there's a big search bar to search through their names and keywords.
