### ISSUE TITLE
Datetime controls: possibility to highlight "today" in the calendar

### ISSUE THREAD

**Issue by marcoponticelli** [palantir/blueprint#3583]
#### Environment

- __Package version(s)__: v3
- __Browser and OS versions__: Chrome 74.0.3729.169

#### Feature request

possibility to show "today" highlighted in the various date pickers.
Even when the date field is not yet evaluated. 
The image below shows how I would like to see the date selector if today was June 7th 2019 and the "HighlightToday" property was active:
![wanted](https://user-images.githubusercontent.com/14297307/58861437-a5774780-86ae-11e9-93b2-bba852475509.png)
the image below shows how I would like to see the date picker if the "HighlightToday" property is not active:
![actual](https://user-images.githubusercontent.com/14297307/58861439-a60fde00-86ae-11e9-8e65-df49396179e8.png)

thanks!

**Comment by adidahiya** [comment]
Seems like a reasonable request. I think it could easily be achieved by adding some styles to the class which react-day-picker is already adding (as a "modifier") to the current date in the calendar. I would call the new prop `highlightCurrentDay`.

Any thoughts from a design perspective @pkwi?

**Comment by pkwi** [comment]
+1 here. style wise this could be a simple outline using `divider-black` and `dark-divider-white`

<img width="282" alt="Screen Shot 2019-06-07 at 11 12 13" src="https://user-images.githubusercontent.com/23030180/59097447-79113480-8915-11e9-95d4-6dcf25ee2e40.png">
<img width="282" alt="Screen Shot 2019-06-07 at 11 18 03" src="https://user-images.githubusercontent.com/23030180/59097638-f8066d00-8915-11e9-9d3c-ca7366a708a5.png">

**Comment by marcoponticelli** [comment]
Nice, I like it
