### ISSUE TITLE
Overlay/Omnibar not centering

### ISSUE THREAD

**Issue by jchirik** [palantir/blueprint#3587]
By default Overlay and Omnibar components appear on the top left corner, whereas Alerts are properly centered. There are no props I can pass to Omnibar for positioning, so it remains stuck in the corner as shown below.

<img width="531" alt="Screen Shot 2019-06-07 at 12 59 09 PM" src="https://user-images.githubusercontent.com/5505304/59099675-14a9a180-8924-11e9-9518-b578f388e139.png">

**Comment by adidahiya** [comment]
what are the props you're sending to `Omnibar`? does it happen with an `Overlay` with custom content as well? it would help if you could provide a minimal bug repro using the code sandbox

**Comment by hnolCol** [comment]
Same problem here. 
Example without any select function:
https://codesandbox.io/s/react-native-odsgf?fontsize=14

Same behaviour when using custom overlay for me.

**Comment by adidahiya** [comment]
You need to import `blueprint-select.css` since Omnibar is in the `@blueprintjs/select` package.

**Comment by abdelhafid-mahmoudi-env** [comment]
**You need to add those lines to your style css** 
`@import "~@blueprintjs/popover2/lib/css/blueprint-popover2.css";`
`@import "~@blueprintjs/select/lib/css/blueprint-select.css";`
