### ISSUE TITLE
Need to pass extra arguments to Column

### ISSUE THREAD

**Issue by nagylzs** [palantir/blueprint#3588]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^3.15.1", "@blueprintjs/table": "^3.5.0",
- __Browser and OS versions__: All

#### Feature request

Childrens of the `Table` component must be `Column` components. If I try to use a different child (e.g. a pure component that encapsulates a Column) then I get this error:
`
Error: [Blueprint Table] <Table> Children of Table must be Columns"`

If I can't encapsulate a Column into another component, then a problem will arise. Consider a general cell renderer method that needs to know the name of the column for rendering. It will be hard to do this without using anonymous functions in the celRenderer property. But using anonymous/lambda functions for a cellRenderer is very inefficient.

#### Examples

This was taken (and simplified) from an existing component that renders a table that has dynamic structure. It receives the structure of the data in a property. The number of columns is not known in advance, so it is not easy to pre-create a separate cell renderer for each column.

```

        const rows = this.state.rows;
        let columns: JSX.Element[] = [];
            const viewStruct = api.meta.get_view_struct(this.getFullViewName());
            viewStruct.column_order.forEach((columnName) => {
                const colStruct: IColumnStruct = viewStruct.columns[columnName];
                columns.push(<Column name={colStruct.displaylabel} key={"column-" + colStruct.name}
                        cellRenderer={(rowIndex: number) => this.cellRenderer(rowIndex, colStruct, columnName)}
                    />);
            }
            );
        return <Table numRows={rows.length}>{columns}</Table>;

```
The viewStruct object describes the columns for the table, including the name, the data type and the label for the column. The cellRenderer method is also general - it will get the column structure and name as a parameter, and renders the cell accordingly.

The problem with this code is that the cellRenderer property is an anonymous function. This is VERY inefficient. This might be avoided using partially bound functions:

`const column1Renderer = this.cellRenderer.bind(this, null, col1Struct, column1Name);`

However, this will only work if we pre-create all column renderer functions for all columns, and reuse them in the render method. But in this example, the number, the order and the name of the columns changes dynamically. It is possible to pre-create cell renderer functions for all of the columns, but that results in an ugly and fragile code.

The obvious solution is to encapsulate `Column` to another pure functional component that has extra properties (e.g. column name and structure). Then we would be able to write this:

```
interface IMyColumnProps extends IColumnProps {
   columName: string;
   colStruct : IColumnStruct;
}

class MyColumn extends React.PureCompontent<IMyColumnProps> {
   private cellRenderer = (rowIndex: number) => {  /* use this.props.columnName here... */ }
   ....
   public render() {
      let props = { ...this.props };
      delete props["columnName"];
      delete props["colStruct"];
      return <Column {...props} cellRenderer={this.cellRenderer} />;
   }
}
```

```
        const rows = this.state.rows;
        let columns: JSX.Element[] = [];
            const viewStruct = api.meta.get_view_struct(this.getFullViewName());
            viewStruct.column_order.forEach((columnName) => {
                const colStruct: IColumnStruct = viewStruct.columns[columnName];
                columns.push(<MyColumn name={colStruct.displaylabel} key={"column-" + colStruct.name} columnName={columnName} colStruct={colStruct}
                    />);
            }
            );
        return <Table numRows={rows.length}>{columns}</Table>;

```
This would prevent using anonymous functions for the cellRenderer property, and also result in a clean code that is easy to maintain. This is currently not possible, because only a `Column` child can be placed inside a `Table`.  In theory, and component that looks like and renders like a `Column` should work.

**Comment by adidahiya** [comment]
> The problem with this code is that the cellRenderer property is an anonymous function. This is VERY inefficient.

Have you profiled your application to verify that this is actually a problem?

**Comment by nagylzs** [comment]
I didn't. I was just trying to follow React guidelines:

https://reactjs.org/docs/handling-events.html

> The problem with this syntax is that a different callback is created each time the LoggingButton renders. In most cases, this is fine. However, if this callback is passed as a prop to lower components, those components might do an extra re-rendering. We generally recommend binding in the constructor or using the class fields syntax, to avoid this sort of performance problem.

I just guessed that the number of cells can be very high, and rendering them multiple times would be inefficient. I wonder if I put a huge table into a scroll view, then will this only render the visible cells, or all of them?

**Comment by nagylzs** [comment]
By the way, my table is rendering slowly, but this might not be the reason.

**Comment by adidahiya** [comment]
Yeah, I'm aware of those guidelines. In practice, though, using lambdas like this in props does not usually have a big performance impact. Your table is probably slow for other reasons... 

Closing this because I think you can manage the extra arguments using lambdas
