### ISSUE TITLE
Hotkey dialog does not close

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#359]
### Bug report

![image](https://cloud.githubusercontent.com/assets/24398123/21124109/b9be9b66-c091-11e6-929e-c31e1e15da75.png)
Chrome, Mac

#### Steps to reproduce

1.  Open hotkey dialog via `?`
2. Attempt to close dialog by clicking away
Expected: Closes
Actual: Does not close
3. Attempt to close via ESC - does not work

You can close via ESC if you haven't click elsewhere.

**Comment by llorca** [comment]
@cmslewis any thoughts?

**Comment by giladgray** [comment]
I am seeing the opposite problem on latests docs, where the `HotkeyDialog` doesn't even appear because it has `.pt-overlay-inline` which overrides all the fixed positioning.

**Comment by giladgray** [comment]
@tgreenwatts is the screenshot relevant to this issue in some way?

**Comment by tgreenwatts** [comment]
I always see the dialog, but it's locked at the top of the screen, so I have to scroll to find it. Not sure if this gif helps, but I press `?`, have to scroll up, then can't exit without refreshing. 
![hotkeys](https://cloud.githubusercontent.com/assets/24398123/21153036/aff081ee-c11d-11e6-962b-5731dd20bd5c.gif)

**Comment by giladgray** [comment]
ah yes same issue i'm seeing. it's cuz the Dialog is marked inline, but it shouldn't be anymore.

**Comment by cmslewis** [comment]
Back from my trip. Opened a PR and added a unit test so this won't happen again.
