### ISSUE TITLE
Switch component hover interaction in dark mode 

### ISSUE THREAD

**Issue by queeniwu** [palantir/blueprint#3599]
The hover interaction for switch is inconsistent with buttons in dark mode, but is consistent in light mode. This makes switches less visible than buttons when in dark mode.

**Dark Mode**
Buttons in dark mode become darker when hovered
Unhovered:
![image](https://user-images.githubusercontent.com/32552540/59469568-065afa00-8dea-11e9-88bf-65b29ed68e11.png)
Hovered (becomes lighter):
![image](https://user-images.githubusercontent.com/32552540/59469548-f4795700-8de9-11e9-9298-c24a08355729.png)

**Light Mode**
Unhovered:
![image](https://user-images.githubusercontent.com/32552540/59469615-34403e80-8dea-11e9-8711-7668448de641.png)
Hovered:
![image](https://user-images.githubusercontent.com/32552540/59469642-47530e80-8dea-11e9-9183-eecd50ddded5.png)

**Comment by adidahiya** [comment]
Fair point, I agree with you that the default and hovered states in dark mode may need to be swapped. Can you confirm @pkwi?

**Comment by pkwi** [comment]
@queeniwu good catch, it should follow intent style buttons and get darker on hover.
