### ISSUE TITLE
HTML table throws error `blueprint-html-components`.

### ISSUE THREAD

**Issue by KonradKlimczak** [palantir/blueprint#3609]
#### Steps to reproduce

1. Use `@blueprintjs/tslint-config` in your tslint configuration
2. Use html table tag like this `<table className{Classes.HTML_TABLE} />
3. You get an error

```
blueprint-html-components: use Blueprint <Table> component instead of JSX intrinsic element.
```

But Table component is totally different then this html table - different functionality and look.

#### Actual behavior

You got unexpected error.

#### Expected behavior

No error.

#### Possible solution

Exclude table tag from this tslint rule.

**Comment by adidahiya** [comment]
I think the error message is wrong. it should say `<HTMLTable>`

use `import { HTMLTable } from "@blueprintjs/core"`

**Comment by tanmoyopenroot** [comment]
@adidahiya 'blueprint' has two components for table `<Table>` and `<HTMLTable>`.
I think the error should say 
`use Blueprint <Table> or <HTMLTable> component instead of JSX intrinsic element.`

**Comment by adidahiya** [comment]
@tanmoyopenroot no, `Table` is very different and would be confusing to offer in replacement of the intrinsic element. If someone wanted a Blueprint data grid, it's better to go find it in the documentation first. Also `<Table>` requires installing another package. Open to PRs to change the error message as I suggested above.
