### ISSUE TITLE
3.16.0 does not include scss or less variables

### ISSUE THREAD

**Issue by maclockard** [palantir/blueprint#3611]
The published lib directory does not include any less or scss variables. 

See here for example: https://unpkg.com/@blueprintjs/core@3.16.0/lib/

**Comment by JulianJason** [comment]
Same issue here.

**Comment by barisozanguler** [comment]
Same here. I just return "3.15.0" for now.

**Comment by adidahiya** [comment]
Sorry about that, it should be fixed now in 3.16.2
