### ISSUE TITLE
Alert: Configurable Button props

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#3614]
#### Feature request

I'd like to add the `large` prop to the buttons of a `Alert`. To achieve this, I would suggest `Alert` to expose two new props: `confirmButtonProps` and `cancelButtonProps` (same naming scheme as for existing text props).

#### Examples

```` jsx
<Alert confirmButtonProps={{large: true}} cancelButtonProps={{large: true}}/>
````

**Comment by adidahiya** [comment]
Alerts are opinionated by design. You can create your own Alert-like dialog with a `Dialog` component.
