### ISSUE TITLE
Using Blueprint React components with Microsoft DotNet Core 2.2 (Reactjs Template)

### ISSUE THREAD

**Issue by arifsuleman** [palantir/blueprint#3618]
#### Environment

- __Package version(s)__: Blueprint V 3.16.0
- __Browser and OS versions__:  ChromeVersion 75.0.3770.100 (64-bit) , Windows 2012 Server 

#### Question

I want to incorporate Blueprint react components into my dotnet core 2.2 Reactjs application. On the way of testing, I see couple of errors. I am using Microsoft Visual Studio 2017 , Reactjs Template on dotnet core 2.2 that does not support typescript out of the box. All of my existing files are (.js) extensions and we have a lot of existing code that is being written in ES6 jsx standard. Do I need to enable Typescript support in my MS React Template to use with Blueprint react components. It would be great if you can provide the right steps to incorporate Bluepting components to specifically with MS .NET 2.2 Reactjs template. The default template is based on NPM.

**Comment by adidahiya** [comment]
Hi @arifsuleman, it is certainly possible to use Blueprint components without using TypeScript, but we do not have a separate documentation guide for purely JS syntax. You may want to look at this page about [reading the Blueprint documentation](https://blueprintjs.com/docs/#blueprint/reading-the-docs) for info about the additional type annotations you see in the code samples.

As for integrating Blueprint into the MS React Template, I'm not familiar with it, is it [this one](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)? If so, it looks like it uses Create React App under the hood. I would suggest checking out [CRA's documentation](https://facebook.github.io/create-react-app/docs/getting-started). You should be able to `import { ... } from "@blueprintjs/core"` and other Blueprint packages after you've installed them via `npm`. Make sure to import the relevant stylesheets as described in [Blueprint's getting started docs](https://blueprintjs.com/docs/#blueprint/getting-started).

**Comment by arifsuleman** [comment]
Hi @adidahiya ,
Thanks for your response. Converting any of existing Blueprint typescript samples to JSX is time consuming. Would that possible , the support team can provide few of samples translated in JSX so it gives good direction where to start if someone does not want to move typescript way of doing in Blueprint and specially since our existing app is based on JSX only. appreciate your input on this and I confirm we use CRA template from Microsoft dotnet core 2.2 that does not support typescript out of the box and I do not want to convert it to typescript since our app is being written in JSX only.
Please advise
