### ISSUE TITLE
Varibales import in sass V3.16.0

### ISSUE THREAD

**Issue by Darkness126** [palantir/blueprint#3619]
I was importing variables in SASS and using its color values. It was working all fine for me until today. Today when I tried to deploy the application with a fresh install I'm getting an error stating that 

```
@import "~@blueprintjs/core/lib/scss/variables";
^
      File to import not found or unreadable: ~@blueprintjs/core/lib/scss/variables.
```

I'm using the below SCSS code

```
@import "~@blueprintjs/core/lib/scss/variables";

.item {
    font-size: 20px;
    color: $blue3;
  }
```
React Version: 16.8.6
Blueprint Core: 3.16.0

Please let me if any more details is needed

**Comment by adidahiya** [comment]
Fixed in 3.16.2
