### ISSUE TITLE
With dark theme, text of button links have wrong color

### ISSUE THREAD

**Issue by nmoreaud** [palantir/blueprint#3623]
#### Environment

- "@blueprintjs/core": "^3.16.2"
- Firefox 67
- Chrome 75
- Windows 10
[Sample here](https://codesandbox.io/s/blueprint-sandbox-wgo52)

#### Steps to reproduce

Put a "minimal" button within a Link.

#### Actual behavior

1. Under light theme it is ok (the text is black)
2. Under dark theme, the text is blue instead of white
3. Under Chrome, the button text has an undesired underline when hovered (no matter the theme)

#### Expected behavior

Dark theme : white text
Thext should not be underlined

#### Possible solution

Add a link example in the docs ? (button & navbar)

Thanks for your great work !

**Comment by adidahiya** [comment]
`<AnchorButton>` is a component designed for buttons with links. Use that and the styling should look fine.

**Comment by nmoreaud** [comment]
Nice. However, AnchorButton doesn't seem to be compatible with react-router, because I cannot pass it a Link tag with "to" prop so it doesn't fix my use case...

**Comment by aurevec** [comment]
I have the same issue and also when you hover the button the text is underlined, it's not the case without link.
