### ISSUE TITLE
Add an option to DateRangeInput to make its popover a fixed height

### ISSUE THREAD

**Issue by gblaketx** [palantir/blueprint#3631]
#### Environment
Package version: @blueprintjs/datetime 3.10.0
Browser: Chrome 75+

#### Feature Request
Add an option to DateRangeInput to make its popover a fixed height rather than resizing when the number of weeks changes.

#### Examples
Currently, the DateRangeInput will resize to fit the number of weeks in the calendar, shrinking and growing as the number of rows changes. This can cause the location of the buttons to change, especially when the popover is positioned above the input.

![dateRangeInputResize](https://user-images.githubusercontent.com/18133832/60287667-6ff60080-98e0-11e9-9620-bfc06cc23641.gif)

Fixing the popover's height would prevent this resizing.

**Comment by tanmoyopenroot** [comment]
Hi @gblaketx ,
I think `dayPickerProps={{ fixedWeeks: true }}` might fix your problem

**Comment by gblaketx** [comment]
Thanks! That looks like it fixes the issue.
