### ISSUE TITLE
Typescript Compiler Doesn't Require Function as Per Docs

### ISSUE THREAD

**Issue by jdpaterson** [palantir/blueprint#3632]
#### Environment

- __Package version(s)__: @blueprintjs/datetime 3.10.0
- __Browser and OS versions__: - 

If possible, link to a minimal repo (fork [this code sandbox](https://codesandbox.io/s/nko3k41y60)):

https://codesandbox.io/s/blueprint-sandbox-wfnbn

#### Steps to reproduce

Go into this sandbox: https://codesandbox.io/s/blueprint-sandbox-wfnbn
The typescript compiler should throw an error because no required props have been passed to the DateInput (according to the docs).
If you un-comment the DateRangeInput an error is thrown, correctly.

#### Actual behavior
Compiler runs without error

#### Expected behavior
Compiler should throw an error because as per the docs a formatDate prop is required: https://blueprintjs.com/docs/#datetime/dateinput 

#### Possible solution

Fix the typescript, or amend the docs.
---
If this passes as an issue I would like to do it as a "good first issue"

**Comment by adidahiya** [comment]
It is a required prop. Not sure why it's passing type checking in the code sandbox... I get an error in my local vscode:

![image](https://user-images.githubusercontent.com/723999/60344763-493dd580-9985-11e9-88ca-54d376ce8a46.png)

Does this happen for you in vscode as well? Which version of typescript are you using?

**Comment by jdpaterson** [comment]
I do not get any error warnings in vscode, or in my console. Tried typescript versions 3.5.2, 3.4.5, and 3.4.1
