### ISSUE TITLE
PanelStack Conflict with @blueprintjs/core/lib/css/blueprint.css

### ISSUE THREAD

**Issue by leonyjiang** [palantir/blueprint#3633]
https://codesandbox.io/embed/panelstack-issue-zer5f

#### Environment

- __Package version(s)__: @blueprintjs/core -- Version 3.16.2
- __Browser and OS versions__: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

#### Actual behavior
When I include "import "@blueprintjs/core/lib/css/blueprint.css" in my index.tsx file, the PanelStack component fails to appear. Removing it allows the PanelStack to render, but it's not styled correctly. To see this issue in action, use the CodeSandbox link above and try toggling commenting for line 5 of index.tsx.

Any possible fixes to get the PanelStack rendering correctly?

**Comment by adidahiya** [comment]
Looks like you just need to tell the PanelStack to take up a certain height with CSS:

![image](https://user-images.githubusercontent.com/723999/60444752-ce2a2880-9beb-11e9-989d-7dd6f5631e2b.png)

You can debug issues like this by inspecting elements and seeing if their bounding boxes take up the right width / height you expect.

**Comment by leonyjiang** [comment]
Thank you!
