### ISSUE TITLE
FileInput : alternative "Browse" text

### ISSUE THREAD

**Issue by nmoreaud** [palantir/blueprint#3639]
#### Environment

"@blueprintjs/core": "^3.16.2"

#### Feature request

When using a FileInput component, I can choose its placeholder but not the text on the embedded button (bad for internationalization). Could you add a prop to do this ?

#### Examples

https://blueprintjs.com/docs/#core/components/file-input.css

**Comment by adidahiya** [comment]
This is in progress: #3560
