### ISSUE TITLE
Better support for icons in SVGs

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#364]
From Ryan M:

> It's pretty hard to put icons in svgs (involves rendering the icon outside the svg, grabbing the "content" to get the unicode character representing the icon in the icon font, adding the icon font to the svg element you want to render the icon in and putting the unicode char in the element)
> This could be supported more first class and would be really nice!

**Comment by giladgray** [comment]
How about `IconContents.STYLE`?
`IconContents` is a map of icon name to unicode content string.
https://github.com/palantir/blueprint/blob/master/gulp/icons.js#L53

**Comment by adidahiya** [comment]
fixed with SVG icons in 2.0
