### ISSUE TITLE
[Table] onKeyUp and onKeyDown does not work in EditableCell

### ISSUE THREAD

**Issue by HZ-labs** [palantir/blueprint#3643]
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.17.1, @blueprintjs/table: 3.6.0
- __Browser and OS versions__: 

Link to a minimal repro: https://codesandbox.io/s/blueprintjs-rerender-editablecell-enablefocusedcell-t7uf8

#### Steps to reproduce

1. Create Table with EditableCell
1. Set focus to Cell and press some Keys

#### Actual behavior

Callback functions does not work

#### Expected behavior

Callback functions is working and is containing `event` params

**Comment by adidahiya** [comment]
I think this is a bug in `@HotkeysTarget` which is used as a class decorator on `EditableCell`... this line seems to have a typo

https://github.com/palantir/blueprint/blob/02b74da0b628430623a28a7f23005aa0b1b9c339/packages/core/src/components/hotkeys/hotkeysTarget.tsx#L100

it should be taking `onKeyDown` and `onKeyUp` from the "existing props", not `keyDown` and `keyUp`

open to PRs with a unit test
