### ISSUE TITLE
handle <TextArea growVertically={true}/> with initial contents

### ISSUE THREAD

**Issue by li-yifei** [palantir/blueprint#3646]
#### Environment

- __Package version(s)__: 3.17.1
- __Browser and OS versions__: Chrome 75, macOS

#### Feature request
The current <TextArea/> component with growVertically property only resizes after inputting.  It can be a new feature that make TextArea fit initial content like the example below.

#### Examples
With a normal one and an expected one.
https://codesandbox.io/s/blueprint-sandbox-dfjbv

**Comment by adidahiya** [comment]
Agreed, we're open to PRs which make it so `growVertically={true}` sizes the component appropriately to the initial contents on render. Doesn't need to be a new feature / option, this feels like a bug fix.
