### ISSUE TITLE
Help enabling autoComplete

### ISSUE THREAD

**Issue by Jtaks** [palantir/blueprint#3662]
#### Environment

- __Package version(s)__:
  - "@blueprintjs/core": "^3.14.1"
  - "@blueprintjs/icons": "^3.6.0"
- __Browser and OS versions__:
  - Firefox 68.0 (64-bit)
  - Ubuntu Budgie 18.04.2 LTS (Bionic Beaver)

#### Question

Is there any way to enable the [`autoComplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute on [InputGroups](https://blueprintjs.com/docs/#core/components/text-inputs.input-group)? I can't seem to get it to work in my react project.

This would be where previously entered form values are made available to the user. Very useful for addresses during a signup process.

#593 and #118 mention it but it is unclear to me which component implements it.

Example of feature in question:

![image](https://user-images.githubusercontent.com/6249932/61244088-9ef4da80-a706-11e9-9bd6-45cc40c425b3.png)

My jsx snippet in question:

```jsx
<form>
    <FormGroup label='Address 1'>
        <InputGroup 
            autoComplete='on'
            placeholder='123 Sunset blvd sw'
            value={addressLine1}
            onChange={(event) => setAddressLine1(event.currentTarget.value)} />
    </FormGroup>
    // ...
</form>
```

Let me know if more information is needed.

**Comment by adidahiya** [comment]
Yes, that's the right syntax for using this attribute with `InputGroup`. Maybe one of these is the issue?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/723999/61360835-878d2d00-a87f-11e9-88e3-506251b6dd3a.png">

**Comment by Jtaks** [comment]
@adidahiya Wow I totally missed that :see_no_evil:. Thank you for your help.
