### ISSUE TITLE
Changing Blueprint Dialog close button style

### ISSUE THREAD

**Issue by arifsuleman** [palantir/blueprint#3666]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question

Dear Support,
I am using Blueprint Dialog component to my reactjs app. I need to change the close button style of Dialog i.e default close button that shows on right corner of dialog window, Could you plz advise how to do that.
thanks

**Comment by adidahiya** [comment]
It depends on which part you want to customize, but generally you should open up the DOM inspector and find the relevant CSS classes which you want to override:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/723999/61436376-f1b6d800-a93a-11e9-893c-496c3cfa6236.png">

Then add custom CSS to your application which applies additional custom styles to those CSS selectors.

**Comment by arifsuleman** [comment]
Hello,
I did use the same class name "bp3-button bp3-minimal bp3-dialog-close-button" and they have the two attributes  box-shadow: none; and  -webkit-box-shadow: none; . I noticed removing them in inspect element gives me the border but what should be the correct approach/style attribute value to override them. I would appreciate if you plz provide some sample style to apply.
thanks

**Comment by igor-volk-red-deer** [comment]
Is there a way to override the svg the button uses?

**Comment by adidahiya** [comment]
@igor-volk-red-deer no. If you need to customize the dialog appearance that much, I would suggest building your own using `<Overlay>` (you can use the `<Dialog>` implementation as a template).

**Comment by igor-volk-red-deer** [comment]
Thank you for clarifying @adidahiya
