### ISSUE TITLE
MultiSelect adds first element from list again if when item removed using "Enter Key"

### ISSUE THREAD

**Issue by mahatosourav91** [palantir/blueprint#3674]
#### Environment

- __Package version(s)__: 3.16.2
- __Browser and OS versions__: Chrome and MacOS

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/nko3k41y60)): 
![delete](https://user-images.githubusercontent.com/25343161/61859277-72e70f80-aee5-11e9-81b0-ec1aabb412ed.gif)

#### Steps to reproduce

1. Add multiple tags in the multi-select field. (Except the first element on the list)
2. Use the keyboard Tab to navigate to any tag close icon.
3. Press enter

#### Actual behavior

The selected tag gets removed but the first element from the dropdown list gets inserted as a new tag.

#### Expected behavior

Only the selected tag should be removed

#### Possible solution

I think this is happening because if the enter key is pressed on a blank multiselect field, the first element of the dropdown is selected.

**Comment by mahatosourav91** [comment]
@adidahiya  Could you please verify if this is the right approach to fix this issue.
https://github.com/palantir/blueprint/pull/3680

**Comment by adidahiya** [comment]
I haven't dug deep into the code yet but `stopPropagation()` is almost never the solution -- we try to avoid it as much as possible in Blueprint because it often has unintended side effects for other components / libraries on the page and I consider it an anti-pattern.
