### ISSUE TITLE
'tsconfig.base' not found

### ISSUE THREAD

**Issue by renjiza** [palantir/blueprint#3684]
after get using "yarn add @blueprintjs/core"

i got some problem message like File `'../../../config/tsconfig.base' not found` 
from `@blueprintjs/core/src`

**Comment by adidahiya** [comment]
It sounds like you're trying to compile blueprint from source in your node_modules. Don't do that. What command did you run?

**Comment by doumart** [comment]
I have the same probleme when using ViteJs. Seems to be with the commonjs plugin of vite
