### ISSUE TITLE
Multiselect reset query on focusOut

### ISSUE THREAD

**Issue by Rashe** [palantir/blueprint#3686]
- __Package version(s)__: core-3.15.1, select-3.8.1
- __Browser and OS versions__: Chrome, Ubuntu

#### Question
For now the query stays as is if I don't select any value from results. Any way to reset the query string on focus out?

Thx

**Comment by adidahiya** [comment]
I think you might be able to do this yourself by reacting to input blur:

```ts
<MultiSelect
  query={...}
  tagInputProps={{
    inputProps: {
      onBlur: () => { ... }
    }
  }}
/>
```

**Comment by Rashe** [comment]
@adidahiya yea, I made something similar, but there will be an issue with selecting item in results list with mouse.

**Comment by adidahiya** [comment]
@Rashe what issue exactly? Can you reproduce it using a code sandbox?
