### ISSUE TITLE
Make spinner colors consistent

### ISSUE THREAD

**Issue by pkwi** [palantir/blueprint#369]
### Bug report

- __Package version(s)__: 1.3.1
- __Browser and OS versions__: all

#### Actual behavior

dark spinners use the following colors:

Track: gray1 (20%)
Head: gray1 (100%)

![screen shot 2016-12-14 at 5 06 18 pm](https://cloud.githubusercontent.com/assets/23030180/21192210/adfedb62-c21f-11e6-87ab-97d89abe64af.png)

#### Expected behavior

Track: black (30%)
Head: gray1 (100%)

![screen shot 2016-12-14 at 5 02 45 pm](https://cloud.githubusercontent.com/assets/23030180/21192120/606ba61e-c21f-11e6-98be-02f3191a175c.png)

**Comment by leebyp** [comment]
@pkwi the contrast with the proposed colors are coming out different to your screenshot, do we want to tweak some more?

<img width="245" alt="screen shot 2017-01-05 at 11 50 58" src="https://cloud.githubusercontent.com/assets/6375593/21695152/67d14434-d33d-11e6-8e2d-89754e7d285f.png">

**Comment by pkwi** [comment]
@leebyp ha! my fault. The head should be using @gray3 (#8A9BA8) not @gray 1.

**Comment by giladgray** [comment]
@pkwi the contrast between the track and background in your proposal is very low, almost too low... 
though in the current incarnation the contrast between track and head are too low...

**Comment by pkwi** [comment]
Valid point @giladgray! We could increase the track's opacity to 50% (same colour/opacity as dark sliders)

<img width="286" alt="screen shot 2017-01-05 at 10 34 06 pm" src="https://cloud.githubusercontent.com/assets/23030180/21700240/5f0b00b0-d397-11e6-838d-e240cb8abe9a.png">

**Comment by leebyp** [comment]
like the 50% a lot more (though from looking at the docs page, maybe we can go even higher)
