### ISSUE TITLE
prevent close

### ISSUE THREAD

**Issue by pmiranda-geo** [palantir/blueprint#3690]
#### Environment

- __Package version(s)__: @blueprintjs/core@^2.3.1":
- __Browser and OS versions__: Chrome

#### Question
Is there a way to prevent dismiss? in other words, to not show the close button, and to change the "title" of that button. it says "cross"

**Comment by adidahiya** [comment]
@pmiranda-geo are you referring to the Alert component? No, it is opinionated by design. See #3417, #3614, #3518, ...
