### ISSUE TITLE
Cannot implment Omnibar Hotkeys without TypeScript

### ISSUE THREAD

**Issue by MalikBagwala** [palantir/blueprint#3695]
#### Environment

- __Package version(s)__: 3.12.0
- __Browser and OS versions__: Chrome 76 and Window 10 Home 

#### Feature request

Hey I am unable to use Omnibar (or HotKeys in general) in ES6 syntax since class Decorators only work in TypeScript is there any existing way of doing this. if not I would like this feature to be added

**Comment by adidahiya** [comment]
> Decorators only work in TypeScript

They are an ES feature, you should be able to use them with Babel too: https://babeljs.io/docs/en/babel-plugin-proposal-decorators

**Comment by MalikBagwala** [comment]
I have used create-react-app (3.1.1) to setup my project and this is the error I get

![OmniBar Error](https://user-images.githubusercontent.com/23068029/63485873-b0c65c00-c4c2-11e9-90fb-d76c0dac6f5e.jpg)

Also, this code crashes on the server

![OmniBar crash](https://user-images.githubusercontent.com/23068029/63485893-ccc9fd80-c4c2-11e9-8824-27635ac2d877.jpg)

**Comment by adidahiya** [comment]
Please see the create-react-app documentation about this: https://create-react-app.dev/docs/can-i-use-decorators

You can rewrite your code to use `Hotkeys` as a function without the decorator syntax.

```ts
class MyComponent extends Component {
  renderHotkeys() {
    // ...
  }
}

export const MyComponentWithHotkeys = HotkeysTarget(MyComponent)
```

**Comment by MalikBagwala** [comment]
I tried this and still this does not work

I  get this warning
`hotkeysTarget.js:23 [Blueprint] @HotkeysTarget-decorated class should implement renderHotkeys.`

this is my code

![Code - 23-08-2019-397](https://user-images.githubusercontent.com/23068029/63573353-bc894f80-c5a2-11e9-8de6-675b8dafbc84.png)

**Comment by MalikBagwala** [comment]
@giladgray thanks a lot...that is silly on my point 😄 ...You guys rock 👍
