### ISSUE TITLE
Setting button icon intent does not change icon color in dark mode

### ISSUE THREAD

**Issue by tomshen** [palantir/blueprint#3696]
#### Environment

- __Package version(s)__: 3.15.1 (but can repro in 3.18.0)
- __Browser and OS versions__: macOS 10.14.6, Chrome 76

Repro: https://codesandbox.io/embed/blueprint-sandbox-0egjl

#### Steps to reproduce

1. Create a container with Classes.DARK.
1. Create a button inside that container.
1. Set the button's icon to `<Icon icon="tick-circle" intent="success" />`.

#### Actual behavior

<img width="79" alt="Screen Shot 2019-08-12 at 1 40 00 PM" src="https://user-images.githubusercontent.com/2065456/62885395-c4c1cf00-bd06-11e9-8b51-02f058147598.png">

#### Expected behavior

<img width="90" alt="Screen Shot 2019-08-12 at 1 40 14 PM" src="https://user-images.githubusercontent.com/2065456/62885384-bd9ac100-bd06-11e9-8745-272d7669e1db.png">

#### Possible solution

Change selector specificity:

<img width="318" alt="Screen Shot 2019-08-12 at 1 40 57 PM" src="https://user-images.githubusercontent.com/2065456/62885505-10747880-bd07-11e9-86f4-619801f07975.png">

**Comment by adidahiya** [comment]
I think it depends on the context of the icon. See https://github.com/palantir/blueprint/pull/3597, https://github.com/palantir/blueprint/pull/3598, https://github.com/palantir/blueprint/pull/3355

Adjusting title to reflect that the problem is with icons inside buttons (which rarely need custom colors...)

**Comment by DeepakSinghKapKoti** [comment]
Yea its a bug I think the intents are not reflecting but I found a way to reflect intents to icon now


<Button     id={...}    text={...}   icon = {<Icon icon={this.props.icon}  style={{color:"red"}}></Icon>}   />

the intent will not work but we can have our own css, which will work on icon only.
