### ISSUE TITLE
Impossible to add a tooltip to a tab

### ISSUE THREAD

**Issue by guigui64** [palantir/blueprint#3699]
#### Environment

- __Package version(s)__: 3.18.0
- __Browser and OS versions__: Chrome 76.0.3809.100

Code sandbox: https://codesandbox.io/embed/bp-tooltip-on-tab-b6h5p

#### Steps to reproduce

Try wrapping a Tab with a Tooltip

#### Actual behavior

The Tab won't show.

#### Expected behavior

The Tab should show and the Tooltip as well on hover.

**Comment by pettyron** [comment]
A Blueprint Tooltip's title supports ReactNodes so why not just wrap its title in a tooltip instead of trying to wrap the whole tab?

`function App() {
  return (
    <Tabs large id="TabsExample" selectedTabId="one">
      <Tab id="one" title="One" />
      <Tab id="two" title="Two" panelClassName="ember-panel" />
      <Tab id="three" title={<Tooltip content="I have content">Three</Tooltip>} />
      <Tab id="four" disabled title="Four" />
    </Tabs>
  );
}`

**Comment by guigui64** [comment]
Thanks, you made my day ! Cheers.
