### ISSUE TITLE
Icon submission: archive/unarchive

### ISSUE THREAD

**Issue by kvngco** [palantir/blueprint#3705]
#### Environment

- __Package version(s)__: 3.18
- __Browser and OS versions__: Safari desktop 12.1.1

#### Feature request

I have a pair of icons to submit. While working on some file components, we've noticed that there was a need to have more explicit icons to convey archiving/unarchiving.

#### Examples

![Screen Shot 2019-08-16 at 15 46 18](https://user-images.githubusercontent.com/3757807/63194051-0327f880-c03d-11e9-87a4-770297097e4d.png)

**Comment by adidahiya** [comment]
closed by #3816
