### ISSUE TITLE
Prevent a futur bug with Blueprint3.Drawer, Blueprint3.OverflowList, Blueprint3.Overlay

### ISSUE THREAD

**Issue by benjaminbours** [palantir/blueprint#3707]
<img width="515" alt="Screenshot 2019-08-19 at 18 02 00" src="https://user-images.githubusercontent.com/8804297/63280816-c9a8f480-c2ab-11e9-8ce2-820d2f58426c.png">

It will be really important to be up to date before the next big react release, that's all :)

Thank you for this lib, keep evolving it 👍

**Comment by adidahiya** [comment]
Thanks for point it it out, going to merge this issue with #2384
