### ISSUE TITLE
How do I get an input value from a popover?

### ISSUE THREAD

**Issue by guydijugnu** [palantir/blueprint#3709]
I have a popover with a text input that I want to obtain data from. I am looking at the documentation but I am confused at how I can access the value from the input. Could anyone help me?

                <Popover
                    popoverClassName={Classes.POPOVER_CONTENT_SIZING}
                >
                    <AnchorButton
                        text="Join"
                        target="_blank"
                        minimal
                        rightIcon="key"
                    />
               <div key="input">
                    <label className={Classes.LABEL} style={{margin: 5}}>
                        <InputGroup
                            type="text"
                            placeholder="Enter your key."
                        />
                    </label>
                </div>
            </Popover>

**Comment by pettyron** [comment]
Let me start by saying that this is a question that belongs somewhere like StackOverflow and not an issue with Blueprint itself. With that said you need an onChange event-handler on the input to get its value and that's not a Blueprint thing that's a JavaScript thing.

    <InputGroup
        type="text"
        placeholder="Enter your key"
        onChange={(e: React.FormEvent<HTMLInputElement>) => {
        console.log(e.currentTarget.value);
        // enter your logic here and pass the value you're needing from e.currentTarget.value
        }}
     />
