### ISSUE TITLE
Update @blueprintjs/datetime on npmjs to 3.12.0?

### ISSUE THREAD

**Issue by jayarjo** [palantir/blueprint#3712]
Version of `@blueprintjs/datetime` on npm is 3.9.2 and it lacks for example such a highly appreciated options as `highlightCurrentDay`. Could you publish the latest one please?

**Comment by adidahiya** [comment]
datetime 3.12.0 is on NPM, it's just not the "latest" version because I published a patch release 3.9.2 afterwards. you can still install 3.12.0: https://unpkg.com/browse/@blueprintjs/datetime@3.12.0/
