### ISSUE TITLE
Enable blueprint-bot comments for forks

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#372]
Also would be neat if contributors didn't have to manually trigger CI. With all the great external contributions we're getting, it's starting to create quite a bit of friction in the review process.

Two instances of CI enabled where blueprint-bot didn't post a comment: https://github.com/palantir/blueprint/pull/371 https://github.com/palantir/blueprint/pull/349

According to @adidahiya, it has to do with this line in the Circle config: https://github.com/palantir/blueprint/blob/497a03eab4420e48db0865407995895aa25726fa/circle.yml#L31

**Comment by giladgray** [comment]
I removed that line in circle.yml in #347. note it's no longer there: https://github.com/palantir/blueprint/blob/master/circle.yml#L38

So really not sure why we're not getting comments from forks. Perhaps the forks were created before this commit so they have the old circle.yml?

**Comment by giladgray** [comment]
don't think there's much to be done about contributors having to enable their own CI. remember that scary "permissive building of forks" setting? 

fortunately CircleCI is absurdly easy to use.

**Comment by adidahiya** [comment]
@giladgray we add a note about enabling Circle to the contributing docs

**Comment by giladgray** [comment]
assigning to @llorca to follow up 🌈

**Comment by adidahiya** [comment]
in TSLint we just added a checkbox to the PR template. https://github.com/palantir/tslint/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by llorca** [comment]
Oh, so it's a manual step required by every external contributor? If so, the checklist item makes sense 👍

**Comment by adidahiya** [comment]
Oops, sorry, my comment doesn't address the overall problem in this issue -- @blueprint-bot is still not posting previews on PRs from forks and I don't know how to fix that :(

**Comment by giladgray** [comment]
I don't think this is technically possible to automate for forks. We have a Circle environment variable `GH_AUTH_TOKEN` that gives @blueprint-bot permission to post comments on our repo. This token is used in the API request from the preview script.

Can't think of a sustainable way for forkers to do the same thing (given that we have control of the bot and its tokens and they have control of their fork & circle env).

**Comment by giladgray** [comment]
take a look at @greglo's loading button Circle build: https://circleci.com/gh/greglo/blueprint/21. expand the `./scripts/preview.sh` block and you'll see this at the end:
![image](https://cloud.githubusercontent.com/assets/464822/21945944/fc54f078-d992-11e6-90f1-583672f95d8a.png)

**the github API request fails because the token is missing.**

actually, if forkers were to set a `GH_AUTH_TOKEN` env var then the preivew script should pass. they wouldn't be able to use @blueprint-bot but they could generate a token as themselves (ugh gender-non-specific pronouns).
