### ISSUE TITLE
Can I render data on EditableCell components?

### ISSUE THREAD

**Issue by whyjay17** [palantir/blueprint#3721]
#### Environment

- __Package version(s)__:  `Blueprint V3`
- __Browser and OS versions__: `Chrome, Windows`

#### Question

Hello, I tried to render data my `Table`-`Column`-`Cell` components by doing:

```
<Table numRows={this.state.sample_table1_data.length}>
    <Column name="Profile" cellRenderer={this.profileRenderer} />
    <Column name="Features" cellRenderer={this.platformRenderer} />
    <Column name="Platform" cellRenderer={this.featureRenderer} />
</Table>
```
and my Renderer looks like
```

    profileRenderer = (rowIndex) => {
        return <Cell>{`${this.state.sample_table1_data[rowIndex].profile_name}`}</Cell>
    }
```

However, when I try to use `EditableCell` instead of `Cell`, the cell becomes editable, but my data do not show up (not get rendered). 

Is the `EditableCell` meant to be like this (initially empty)?

If not, how can I fix this issue?

Thank you.

**Comment by adidahiya** [comment]
`EditableCell` works a little differently -- it uses the `value` prop to render contents. Check out the [docs](https://blueprintjs.com/docs/#table/features.editing) and [`tableEditableExample.tsx`](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/table-examples/tableEditableExample.tsx)
