### ISSUE TITLE
Toaster - How to set container without calling Toaster.create in React 16

### ISSUE THREAD

**Issue by rasika-sinha** [palantir/blueprint#3726]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.13.0; React 16.7.0
- __Browser and OS versions__: Chrome latest version, Windows 10

#### Question

I have recently upgraded React and BlueprintJS to latest versions and after that I am having issues with the Toaster component of BlueprintJS.

Initially we used to create a Toaster via the first method described in documentation i.e. Toaster.create(props, container) and with that we can supply the container element therefore I was able to show toasts in body (page level toast) and also inside a particular div(regional toast). With React 16 as mentioned in the Blueprint documentation we cannot use Toaster.create anymore

"React 16 usage Toaster.create() will throw an error if invoked inside a component lifecycle method in React 16, as ReactDOM.render() will return null resulting in an inaccessible toaster instance. See the second bullet point on the React 16 release notes for more information."

So now I am unable to assign a container to the toast. As per React 16 documentation, alternate to ReactDOM.render is ReactDOM.createPortal but looks like Blueprint is not yet using it.

Do we have any alternatives to show toast in different containers on runtime?

**Comment by adidahiya** [comment]
Have you tried using the following API ([#2 in the docs](https://blueprintjs.com/docs/#core/components/toast.toaster))? It should allow you to make global and local (inline) toasters:

```tsx
<Toaster usePortal={false}>
  <Toast />
</Toaster>
```
