### ISSUE TITLE
Tabs - wrong resize calculation

### ISSUE THREAD

**Issue by Kupstas** [palantir/blueprint#3727]
#### Environment

"@blueprintjs/core": "^3.18.0"
"electron": "6.0.7",

Tab indicator does not recalculating when window has changed size. Also reproduces at fullscreen toggle.

<img width="480" alt="Screenshot 2019-09-06 at 15 32 07" src="https://user-images.githubusercontent.com/10007851/64428137-a5c31c80-d0bb-11e9-9a07-e1f08fc7f669.png">
<img width="195" alt="Screenshot 2019-09-06 at 15 32 20" src="https://user-images.githubusercontent.com/10007851/64428138-a5c31c80-d0bb-11e9-9601-0ed14ee23e52.png">

**Comment by adidahiya** [comment]
Related to #1035, and it will have the same solution
