### ISSUE TITLE
Is there a way to pass in an additional parameter to `cellRenderer`?

### ISSUE THREAD

**Issue by whyjay17** [palantir/blueprint#3728]
#### Environment

- __Package version(s)__: The recent version
- __Browser and OS versions__: Chrome, Windows
#### Question

I am using Blueprint with React.
When rendering a table, is there a way to pass in an additional parameter to the `cellRenderer` props other than the `rowIndex` and `columnIndex`? 

Right now, I am doing:
```
<Table numRows={profile.releases.length}>
    <Column name="Release" cellRenderer={this.releaseRenderer} />
    <Column name="Owner" cellRenderer={this.ownerRenderer} />
</Table>
```
to render columns in a table, but I also need to pass in another variable.
I tried this:
 ```<Column name="Owner" cellRenderer={() => this.ownerRenderer(rowIndex, columnIndex, something} />```
but it did not recognize `rowIndex` and `columnIndex` which is pretty obvious.

I can rephrase the question differently if it's complicated to solve the issue above: 
```
<div className="table-box">
    {
        this.state.table1_data.map((profile, idx) => {
            console.log('idx', idx)
            return (
                <div>
                    <p className="profile-title">{profile.title}</p>
                    <Table numRows={profile.releases.length}>
                        <Column name="Release" cellRenderer={this.releaseRenderer} />
                        <Column name="Owner" cellRenderer={this.ownerRenderer} />
                    </Table>
                </div>
            )
        })
    }
</div>
```

How can I pass that `idx` into the `releaseRenderer`?

In my `releaseRenderer`, 

    releaseRenderer = (rowIndex, columnIndex) => {
        return <EditableCell
            value={``} <----------- I need `idx` here
            onChange={this.onEditCell(rowIndex, columnIndex)}
        />
    }

I need `idx` to render the value inside the array inside the state. 
My state looks something like:

`state = [ { 'title': 'aa', releases: [ '1', '2', '3'], owner: 'John' }, { 'title': 'bb', releases: [ '1', '2', '3'], owner: 'Doe' } ]`

So, I have a table for each object inside the `state` and trying to render the values in the `releases` on the first column, but I need to be able to pass in the `idx` to the `releaseRenderer` to access the right object in the `state`

Thanks again

**Comment by qcz** [comment]
try
```
<Column name="Owner" cellRenderer={(rowIndex, columnIndex) => this.ownerRenderer(rowIndex, columnIndex, something)} />
```

**Comment by qcz** [comment]
try
```
<Column name="Owner" cellRenderer={(rowIndex, columnIndex) => this.ownerRenderer(rowIndex, columnIndex, something)} />
```

**Comment by whyjay17** [comment]
@qcz Works perfectly. Thanks!
