### ISSUE TITLE
Updating Breadcrumbs content

### ISSUE THREAD

**Issue by ljgago** [palantir/blueprint#3734]
#### Environment

- __Package version(s)__: 3.18.0
- __Browser and OS versions__: 
  - Chrome: Version 76.0.3809.100 (Official Build) (64-bit)
  - OS Debian Testing

#### Question

Hello, I am using the Breadcrumbs component for render a path file and need that this Breadcrumbs change if I change this path, but if I change the content of items props the component not updated and it continue show the old items.

What is the better way for update the Breadcrumbs view and to show the currents items?

**Comment by adidahiya** [comment]
Are you updating the same `items` array every time? Breadcrumbs is a [pure component](https://github.com/palantir/blueprint/blob/1aa7160518376ead77706c049a1b1b6655ce58e1/packages/core/src/components/breadcrumbs/breadcrumbs.tsx#L79), so if you send a prop value which is a reference to the same array, it will not re-render. You will have to create a new array.

**Comment by ljgago** [comment]
Thanks! sending an array copy to Breadcrumbs component work fine.
