### ISSUE TITLE
Popover/Tooltip dynamical content

### ISSUE THREAD

**Issue by aniov** [palantir/blueprint#3740]
#### Question
Because I use a Tree and have many elements I have to get Popover 'content' individually on hover for each one as a server request.
How can I render content of a Popover component dynamically on hover without re-rendering whole Tree?

Thank you.

**Comment by adidahiya** [comment]
The Tree example in the docs shows how to add a tooltip (or popover in your case) to both the label and secondary label in a tree node: https://github.com/palantir/blueprint/blob/a37f79c95c5b377a9793b222a142df7f5bff2ce7/packages/docs-app/src/examples/core-examples/treeExample.tsx#L89
