### ISSUE TITLE
Unexpected Popover behavior after update to 3.18.1

### ISSUE THREAD

**Issue by tim-lukacik** [palantir/blueprint#3741]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^3.18.1",
    "@blueprintjs/select": "^3.10.0", "react": "^16.9.0"
- __Browser and OS versions__: Version 77.0.3865.75 (Official Build) (64-bit)

#### Question

I have a strange issue with Popover with the 3.18.1 update. This code has been in place unchanged for perhaps 6 months with no issues until this update. The behavior goes way if I revert back to 3.18.0. I have attempted to reproduce this behavior in the sandbox but have not been able to do so so posting this as a support question instead of a bug.

I have a sidenav which has a read only input, which when clicked creates a popover, which contains 2 tabs, which contain selects, multiselects, and HTMLSelects. I have roughly recreated basics in this [sandbox](https://codesandbox.io/s/blueprint-sandbox-phrz7). The issue occurs only with the select and multiselect.

The problem is when a user clicks the select it appears focus is stolen to some other element. Clicking on an item or in the "Filter..." input closes the parent popover and then the multiselect popover. Expected behavior is that the multiselect popover closes and the parent popover remains open. This makes it impossible to use the filter input and annoying to use the selects as the user has to re-open the parent popover. The same thing happens when selecting an item in the multiselect although interestingly it does not happen when removing an item in the multiselect.

Checking document.activeElement when focus is lost shows the active tab label element with a suspect class name "bp3-tab-panel_undefined_input". Removing the selects from the tab and placing as direct children seems to solve the problem.

Any idea what's going on here? I looked at the changelog for 3.18.1 and it doesn't seem like much changed...

**Comment by tim-lukacik** [comment]
[Video](https://timlukacik-gmail.tinytake.com/tt/Mzc3MDAzMV8xMTQ5NTA1Ng) of the behavior

**Comment by adidahiya** [comment]
I haven't looked closely at your issue yet but this was likely the commit which changed your popover behavior in 3.18.1: https://github.com/palantir/blueprint/pull/3716

**Comment by tim-lukacik** [comment]
Closing since I can't reproduce this outside of my own project.

**Comment by balgamat** [comment]
I have experienced the exact same issue as well. There is a filterable Select in a Modal and I am unable to type into the Filter due to the lack of focus. When rendered elsewhere (not in a modal, it works just fine)

**Comment by adidahiya** [comment]
@balgamat if it's still a problem can you please file a new issue and fill out the template?
