### ISSUE TITLE
Breadcrumbs overflow menu causes React error if "current" property is set

### ISSUE THREAD

**Issue by mdanka** [palantir/blueprint#3744]
#### Environment

- __Package version(s)__: 3.18.1
- __Browser and OS versions__: Chrome 76, Mac 10.14.6

Repro: https://codesandbox.io/s/blueprint-sandbox-4qrku

![Screenshot 2019-09-19 at 20 09 18](https://user-images.githubusercontent.com/8069999/65269504-9612f180-db19-11e9-96c2-590b22a2a340.png)

#### Steps to reproduce

1. Provide breadcrumbs with the current property set on the first one
1. Click on the overflow menu
1. Check the console log

#### Actual behavior

Console log shows a React error

#### Expected behavior

No errors in the console log

**Comment by anresti256** [comment]
> #### Environment
> * **Package version(s)**: 3.18.1
> * **Browser and OS versions**: Chrome 76, Mac 10.14.6
> 
> Repro: https://codesandbox.io/s/blueprint-sandbox-4qrku
> 
> ![Screenshot 2019-09-19 at 20 09 18](https://user-images.githubusercontent.com/8069999/65269504-9612f180-db19-11e9-96c2-590b22a2a340.png)
> 
> #### Steps to reproduce
> 1. Provide breadcrumbs with the current property set on the first one
> 2. Click on the overflow menu
> 3. Check the console log
> 
> #### Actual behavior
> Console log shows a React error
> 
> #### Expected behavior
> No errors in the console log
> 
> #### Possible solution
