### ISSUE TITLE
How do you use your local blueprint repository in other projects for testing purposes?

### ISSUE THREAD

**Issue by m-manseer** [palantir/blueprint#3747]
#### Environment

- __Package version(s)__:

core 3.18.1
datetime 3.13.0
icons 3.10.0
select 3.10.0
table 3.7.0
timezone 3.5.0

- __Browser and OS versions__: 

No browser.
OS: macOS Mojave 10.14.6

#### Question

I am trying to use my forked, local blueprint repository in another project so that I can test my changes to blueprint. To do this, I'm following [this guide](https://medium.com/@chrisdmasters/how-to-fork-a-dependency-and-use-it-locally-in-a-project-707c80d3449c), which basically suggests to use `yarn link`.

When using this command however, it says:

```
yarn link
yarn link v1.15.2
success Registered "blueprintjs-monorepo".
info You can now run `yarn link "blueprintjs-monorepo"` in the projects where you want to use this package and it will be used instead.
✨  Done in 0.06s.
```

I was expecting the registered project to be called `@blueprintjs`, not `blueprintjs-monorepo`. If I now use `yarn link "blueprintjs-monorepo"` in my other project, it will not use it instead of `blueprintjs` but be a separate linked project altogether (I assume, since the names don't match and none of my changes are applied).

I would like the [contribution guide](https://github.com/palantir/blueprint/blob/develop/CONTRIBUTING.md) to include clear steps on how to be able to test/use one's own changes to blueprint before submitting a pull request.

**Comment by adidahiya** [comment]
@m-manseer you need to run `yarn link` inside each package directory, e.g. packages/core, packages/datetime, etc.
