### ISSUE TITLE
Menu Item is undefined when package build (create-react-app)

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#3753]
#### Environment
- __Package version(s)__: 3.18.1
- __Create React App versions__: v3.1.2

#### Steps to reproduce

1. Build a react app with a Menu and Menu.Item inside
2. Access the page 
3. Should have blank screen

#### Actual behavior

When trying to render a Menu.item inside a build create react app i got a blank screen. To find more information I had some log and found something akward : 

![image](https://user-images.githubusercontent.com/9548473/65775757-14d2e480-e141-11e9-96f9-bfe11dd3f1f8.png)

![image](https://user-images.githubusercontent.com/9548473/65775648-e2c18280-e140-11e9-9050-0a7ef05b370b.png)

` Menu.item ` is `undefined`
#### Expected behavior

Render correctly a Menu Item

#### Workaround

use `Menu Item` directly instead of `Menu.item`

**Comment by amalo95** [comment]
Using `MenuItem` directly instead of `Menu.Item` gets rid of the error. It must get evaluated to `undefined` during minification.

**Comment by LoiKos** [comment]
Yep maybe due to last update on CRA. By the way it's working for `Menu.Divider`

**Comment by zachkirsch** [comment]
+1 we just got this bug too. Maybe the docs should be updated? Took us a while to debug since it only occurs after the JS is minified

**Comment by LoiKos** [comment]
It seems that Menu Aliases as been removed so i close this issue. If someone still getting the problem feel free to re-open.
