### ISSUE TITLE
Tab - render once on change

### ISSUE THREAD

**Issue by gurpal2000** [palantir/blueprint#3756]
#### Environment

blueprintjs/core v3.18.0
Chrome
Windows

#### Feature request

Provide a prop that does not re-render tabs onChange. I think the terminology is "to keep it mounted" similar to the Collapse component which has a keepChildrenMounted flag.

#### Examples

Say I have 2 tabs with various components on them. I find that the tab switch forces a re-render each time. Currently the workaround (I assume) is to control the state change manually in the onChange handler?

**Comment by adidahiya** [comment]
Tabs will re-render when switched to, but they should not unmount. Unmounting inactive tabs is controlled by the `renderActiveTabPanelOnly` prop.

**Comment by gurpal2000** [comment]
Is there an example? I never did get this working. I have some sample code I was trying on from last year.

**Comment by adidahiya** [comment]
@gurpal2000 can you demonstrate the issue in a code sandbox (linked in the issue template)?
