### ISSUE TITLE
Table cell copy in IE 11

### ISSUE THREAD

**Issue by chuyachia** [palantir/blueprint#3758]
#### Environment

- __Package version(s)__: blueprintjs/table v.3.7.0
- __Browser and OS versions__: IE 11 Win7

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/#table/features.sorting

#### Steps to reproduce

Follow the table documentation page instruction to select cell and copy in IE11

#### Actual behavior

No data was copied. Got an `Unexpected call to method or property access.` error.
![Screenshot from 2019-09-30 14-24-22](https://user-images.githubusercontent.com/25123789/65905266-4096da00-e38e-11e9-92f8-fcac2a0725b2.png)

#### Expected behavior

IE 11 is among the browsers that Blueprint supports. The data should be copied.

#### Possible solution

It seems that DataTransfer.setData only accepts "text" format in IE11 but "text/html" and "text/plain" are used in https://github.com/palantir/blueprint/blob/develop/packages/table/src/common/clipboard.ts#L107 One solution might be just using "text" as format?

**Comment by chuyachia** [comment]
@adidahiya  Do you think using just "text" instead of "text/html" and "text/plain" can be a solution?

**Comment by adidahiya** [comment]
@chuyachia you're welcome to test it out -- just make sure the behavior for other browsers continues to work.
