### ISSUE TITLE
Upgrade to TypeScript 2.1

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#376]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

- [x] switch from Object.assign to ES2017 object spread
  - also fixes #11 
- [ ] configuration inheritance (likely useful for the `examples/` TS project)
  - :sob: not supported yet https://github.com/ivogabe/gulp-typescript/issues/459
- [ ] `Partial<T>` (haven't looked into this much yet for this codebase)

these should all be non-breaking changes.

**Comment by jumpinjackie** [comment]
You might also want to leverage the new `--importHelpers` compiler flag in TS 2.1 along with the `tslib` external helper library so that the various TypeScript helper boilerplate functions aren't emitted for every TS source file in the project (reducing overall bundle size)

**Comment by giladgray** [comment]
regrettably gulp-typescript does not currently support `extends`: https://github.com/ivogabe/gulp-typescript/issues/459
