### ISSUE TITLE
Upgrade icons package

### ISSUE THREAD

**Issue by vsrinivasdsd** [palantir/blueprint#3760]
#### Environment

- __Package version(s)__: 2.2.0
- __Browser and OS versions__: Chrome 77 & Win 10

#### Question

Thanks for the great library :)

We are using blueprintjs ver.2.2.0 in our project and separately added [select] feature (ver. 3.8.0) and [table] (2.1.0), which are working fine.
One of our recent tasks requires the new "flow" set of icons that are present in version 3.1.0.
I tried adding @blueprintjs/icons package separately and though it shows version 3.10.0 in the package.json file, the icons folder in [node_modules] still uses the version 2.2.0 (that is part of the blueprintjs/core version)
Due to client restrictions, we are unable to upgrade the whole blueprintjs package version.

Is there a way\workaround to upgrade the icons package alone or have it installed like the [select] and [table] and get the required icons ?

Thanks for any help!

**Comment by adidahiya** [comment]
`@blueprintjs/core` 2.2.0 is very old. Unfortunately, we will not be backporting new icons to v2.x. Please upgrade to v3.x.
