### ISSUE TITLE
Leading spaces in free text input in dropdowns are not displayed

### ISSUE THREAD

**Issue by tgemal** [palantir/blueprint#3765]
Users can accidentally create entries in dropdowns that have leading spaces (e.g. “ SMITH” instead of “SMITH”), but the leading space is not shown in the dropdown thus creating confusion about what the created value is, and 

<img width="361" alt="dropdown" src="https://user-images.githubusercontent.com/4023382/66162970-a05fe000-e62f-11e9-9bce-c1f93dd34a7b.png">

#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: Chrome 77.0.3865.90, Windows 10

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1.	Create a form
2.	Put a dropdown property
3.	Allow users to create new values
4.	Type 'Maxime' and ' Maxime' (with a leading space).

#### Actual behavior
The two values (incorrectly) look the same in the dropdown. See screenshot

#### Expected behavior
Either trim the value or at least show any leading spaces when displaying.

**Comment by adidahiya** [comment]
Good catch! I think we should trim leading and trailing whitespace.
