### ISSUE TITLE
[select] not clearing state when items list changes

### ISSUE THREAD

**Issue by alecf** [palantir/blueprint#3775]
#### Environment

- @blueprint/core 3.19.0, @blueprint/select 3.11.0: 
- Chrome 77, MacOS: 

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. Use `<Select>`
1. change the items= prop
1. Note that the list you select from does not change

#### Actual behavior

The list of items does not change.

#### Expected behavior

The list of items should change

#### Possible solution

I suspect this is related to #3702

**Comment by adidahiya** [comment]
I'm able to repro this bug. Working on a fix

**Comment by adidahiya** [comment]
Here's a sandbox with the bug repro: https://codesandbox.io/embed/blueprint-sandbox-28x3m
