### ISSUE TITLE
Toaster: First bottom-anchored Toast has wrong animation direction

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#3778]
#### Steps to reproduce

1. Open Toaster demo https://blueprintjs.com/docs/#core/components/toast
1. Set position to either bottom, bottom-left or bottom right
1. Click "Procure Toast"

#### Actual behavior

The very first toast shown animates wrongly  as top-to-bottom

#### Expected behavior

It should animate bottom-to-top like subsequently procured toasts 

#### Possible solution

Top-anchored toasts do not appear to be affected by this direction bug.

**Comment by j0b0sapi3n** [comment]
I'm seeing this problem too
