### ISSUE TITLE
Collapse doesn't animate on first open

### ISSUE THREAD

**Issue by pdesoyres** [palantir/blueprint#3788]
#### Environment

- __Package version(s)__: 3.19.1
- __Browser and OS versions__: Google Chrome 77.0.3865.120, Linux Mint 19

#### Steps to reproduce

1. clone git blueprint repository
2. run `yarn`
3. run `yarn verify`
4. run `yarn dev`
5. navigate to http://localhost:9000/#core/components/collapse
6. click on the "Show build logs" button

#### Actual behavior
The first Collapse opening is not animated. All other successive close and open plays animation properly.

#### Expected behavior

An animation should be played at first opening 

#### Possible solution

Exact same issue (#2911) has been fixed but the commit 8ce4d592a3d34b47ccfc14d387870c072bf11075 introduced the regression.

**Comment by alxmiron** [comment]
Same for me. Animation regression

**Comment by RenzHoly** [comment]
Same for me

**Comment by mytototo** [comment]
I have the same issue and want to add a little detail about it: after upgrading to latest version, the closing animation doesn't work at all regardless if it's the first opening or not.

**Comment by adidahiya** [comment]
Fixed by #3831. Note that this also fixes Tree animations as well
