### ISSUE TITLE
[Table] Rows reordering not update immediately

### ISSUE THREAD

**Issue by PeacePan** [palantir/blueprint#3789]
#### Environment

- __Package version(s)__: @blueprintjs/table: 3.7.1
- __Browser and OS versions__: Chrome 76.0.3809.100, MacOS 10.14.6

#### Steps to reproduce

1. go to https://blueprintjs.com/docs/#table/features.reordering
1. scroll to `Example`
1. Drag and drop the rows

#### Actual behavior

Rows not updated after reordering.

#### Expected behavior

Rows update immediately after reordering

**Comment by ramirs** [comment]
Was able to repro, and currently facing a related issue with rendering

**Comment by adidahiya** [comment]
Seems to work fine in the current version. If it persists, leave a comment and I can re-open the issue.

![2021-06-11 15 11 01](https://user-images.githubusercontent.com/723999/121737792-5519f800-cac7-11eb-9897-9332c2d3ce74.gif)
