### ISSUE TITLE
Toaster: other toasts fill gap in the wrong direction when bottom toast closed

### ISSUE THREAD

**Issue by sidsethupathi** [palantir/blueprint#3791]
#### Environment

- __Package version(s)__: 3.19.1
- __Browser and OS versions__: Chrome Mac OSX

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#core/components/toast
1. Select any of the bottom toasts
1. Open 2 or 3 toasts, then close out the bottom or middle toast

#### Actual behavior

The "fill" animation goes up

![toast](https://user-images.githubusercontent.com/2329283/67355725-fab0da00-f525-11e9-9ba7-f901c2ecea35.gif)

#### Expected behavior

The fill animation goes down

#### Possible solution
Not sure, but maybe related to https://github.com/palantir/blueprint/issues/3778 and https://github.com/palantir/blueprint/pull/3784

**Comment by algomaster99** [comment]
@adidahiya Can I try this issue? :)

**Comment by algomaster99** [comment]
@adidahiya Hi! Shall I give this issue a try? :)

**Comment by adidahiya** [comment]
@algomaster99 you're always welcome to submit PRs for issues marked "help wanted", but someone beat you to it in #3911
