### ISSUE TITLE
Table: only four columns are rendered after updating numRows

### ISSUE THREAD

**Issue by mtrivolli** [palantir/blueprint#3796]
#### Environment

- core: 3.19.1
- table: 3.8.1
- Browser: 77.0.3865.90 (64 bits)
- OS: linux

[Code sandbox example](https://codesandbox.io/s/blueprint-table-column-refresh-issue-26ht5)

#### Steps to reproduce

1. Create a table with a certain number of rows and a large number of columns (enough to activate the horizontal scrollbar)
1. Update the number of rows in the table

#### Actual behavior

The table only renders the first four columns

#### Expected behavior

The table should render all visible columns

#### Possible solution

Not identified

**Comment by PeacePan** [comment]
same here #3779

**Comment by mtrivolli** [comment]
My bad... closing this as duplicate of #3779
