### ISSUE TITLE
Breadcrumbs, OverflowList: Support React Strict Mode

### ISSUE THREAD

**Issue by tony** [palantir/blueprint#3797]
Originally references in #3361.

(I am new to blueprint, sorry if I missed anything!)

#### Environment

- __Package version(s)__: 3.19.1
- __Browser and OS versions__: Ubuntu 19.10, Chrome Version 78.0.3904.70 (Official Build) (64-bit)

No fork, but the life example on docs give this warning (as of Oct 27th, 2019): https://blueprintjs.com/docs/#core/components/breadcrumbs

#### Steps to reproduce

1. Use example in breadcrumb docs: https://blueprintjs.com/docs/#core/components/breadcrumbs
1. Load breadcrumbs

#### Actual behavior

```
react-dom.development.js:530 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Blueprint3.ResizeSensor which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in ul (created by Blueprint3.OverflowList)
    in Blueprint3.ResizeSensor (created by Blueprint3.OverflowList)
    in Blueprint3.OverflowList (created by Breadcrumbs)
    in Breadcrumbs (at Layout.tsx:29)
    in BreadcrumbBar (at Layout.tsx:63)
    in main (at Layout.tsx:62)
    in Layout (at HSK.tsx:55)
    in HashScroll (created by NaviProvider)
    in NaviProvider (created by Router)
    in Router (at HSK.tsx:54)
    in HelmetProvider (created by NaviHelmetProvider)
    in NaviHelmetProvider (at HSK.tsx:53)
    in StrictMode (at HSK.tsx:52)
    in RelayEnvironmentProvider (at HSK.tsx:51)
    in App (at HSK.tsx:65)
```

#### Expected behavior

No warning when wrapped in `React.StrictMode`

#### Possible solution

Not sure yet, docs mention something about passing in a reference https://fb.me/react-strict-mode-find-node

**Comment by adidahiya** [comment]
closing in favor of #3979, which has more information and some concrete proposals
