### ISSUE TITLE
"Maximum update depth exceeded" error when using blueprint with mobx

### ISSUE THREAD

**Issue by Buroni** [palantir/blueprint#3803]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.19.1, react 16.11.0, mobx 5.14.2, mobx-react 6.1.4
- __Browser and OS versions__: Chrome 72.0.3626.121, Fedora 29

Minimal example, click the input field to trigger react crash: https://stackblitz.com/edit/react-njhvds 

#### Steps to reproduce

1. Wrap a blueprint `TagInput` or `InputGroup` component in a mobx `observer`.
1. Bring the input field into focus (i.e. click the field).

#### Actual behavior

The react app crashes with the following error:

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

#### Expected behavior

The input field should focus as normal.

#### Possible solution

It looks like this error was introduced since blueprint was updated to remove deprecated lifecycle component such as `componentWillReceiveProps`. For example in the updated `TagInput` component, `setState` is being called unconditionally inside `componentDidUpdate` which seems to be causing the infinite re-render.

**Comment by adidahiya** [comment]
I can see the problem with TagInput, but what's the issue with InputGroup?

**Comment by Buroni** [comment]
> I can see the problem with TagInput, but what's the issue with InputGroup?

If you replace `TagInput` with `InputGroup` (i.e. `const OInputGroup = observer(InputGroup);`) then you should see that the react error should trigger immediately.
