### ISSUE TITLE
DateInput should allow shortcuts

### ISSUE THREAD

**Issue by rherms** [palantir/blueprint#3804]
When using the DateInput component, you have no control over what is rendered in the popover. It would be nice if you could add your own custom shortcuts to the side of the calendar, much like the DateRangePicker.

**Comment by adidahiya** [comment]
Do you have a design proposal of what the default shortcuts should look like?

**Comment by rherms** [comment]
I think the default would be no shortcuts. Or we could move the today and clear shortcuts there. I just need some control over the date picker popover that is rendered and this would provide a nice plugin point.
