### ISSUE TITLE
Button does not preserve `disabled` prop value when set to false

### ISSUE THREAD

**Issue by DannyDelott** [palantir/blueprint#3819]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Assert in a test that a Blueprint `<Button>` is disabled when set to `false`.

Example (using Enzyme apis):

```js
it('should be disabled', () => {
  const wrapper = mount(
    <Button disabled={false} onClick={...} />
  );

  expect(
    wrapper.find('button').props().disabled
  ).to.equal(false);
});
```

#### Actual behavior

`expected undefined to equal false`

#### Expected behavior

Blueprint should preserve the boolean literal `false`, instead of converting to `undefined`.

#### Possible solution

Looks like this line should explicitly check if `disabled === false` instead of doing a simple falsy check.
 https://github.com/palantir/blueprint/blob/1aa7160518376ead77706c049a1b1b6655ce58e1/packages/core/src/components/button/abstractButton.tsx#L104

**Comment by adidahiya** [comment]
I don't think this is explicitly part of our API contract, nor am I convinced that it needs to be. We don't spread all props as attributes to HTML elements like `<button>`.

**Comment by jrafidi** [comment]
The change made to fix this issue caused a regression in behavior. Previously, `loading` would always disable a button. Now, `loading` will not disable if `disable` is set to `false`.

If we intend to make this change, I think it should be done in a major version since this behavior change will require a migration to fix.

**Comment by adidahiya** [comment]
@jrafidi is right, and after realizing the downstream impact of the change I made in #5360, I think we should revert it. My statement in the comment above https://github.com/palantir/blueprint/issues/3819#issuecomment-550151460 is still true, and Blueprint doesn't need to guarantee that `<button disabled={false}>` will get rendered by `<Button disabled={false}>` as suggested in the test case in the OP here.

The previous behavior where `loading={true}` overrides `disabled={false}` is more useful to users, so I'm going to revert back to that.
