### ISSUE TITLE
is it possible to open calendar by clicking the Icon in DateInput ?

### ISSUE THREAD

**Issue by irecognizedyou** [palantir/blueprint#3827]
#### Environment

 Blueprint v2.3.1
 DateTime v2.0.3

#### Question

How can I trigger open calendar popover by clicking the passed in icon inside the input field?
```
<DateInput
       rightElement={this.calendarIcon()}/>
```

**Comment by irecognizedyou** [comment]
``

**Comment by adidahiya** [comment]
I think you would have to override the component's internal Popover control by supplying `popoverProps={ isOpen }` on the DateInput. In addition you could use `onInteraction` to help with controlling the popover (see the docs on controlled Popover usage http://localhost:9000/#core/components/popover.controlled-mode)

**Comment by irecognizedyou** [comment]
Thanks for the answer. I have tried to use `popoverProps={ isOpen}` and it allowed to open the popover by clicking the icon, but in another hand it overwrote ability to open popover on input click, to solve this problem I added in addition `inputProps` 
```
 popoverProps={{
            isOpen: this.state.isCalendarOpen,
            onInteraction: this.handleCalendarInteraction
}}
 inputProps={{
            onClick: this.handleCalendarInteraction
 }}                         
```
