### ISSUE TITLE
How to make select all time in TimePicker when it clicked/focused. 

### ISSUE THREAD

**Issue by lida-skakun** [palantir/blueprint#383]
Time Picker should select all text when clicked/focused. 
By default to enter any time you need first to erase text with backspace or double-click to select all.
expected: click on field, start typing.Any Ideas? 

```ts
const renderTime = ({ input, meta: { touched, error } }) => (
	<div className={classes.timeField}>
		<TimePicker
			onChange={value => input.onChange(value)}
			value={input.value}
		/>
		{touched && error && <div className={classes.error}>{error}</div>}
	</div>
);
```

**Comment by cmslewis** [comment]
Hi @lida-skakun, thanks for the issue, and sorry for the delay getting back to you; the Blueprint team is taking some time off for the holidays. Your proposal makes sense to me at first glance. We implemented this functionality in the `<EditableText>` component by adding a boolean `selectAllOnFocus` prop—should be straightforward enough to add a similar prop to our other input-fieldy components as well. We'll take a look when we're back in the new year.
