### ISSUE TITLE
Input search field in Select component always loses focus if I use these component inside Drawer

### ISSUE THREAD

**Issue by Bielykh-Artem** [palantir/blueprint#3845]

**Comment by adidahiya** [comment]
please help me triage the issue by filling out the issue template

**Comment by Bielykh-Artem** [comment]
I created video for you: https://drive.google.com/file/d/1T4fTUdhqWGTKNxQ9fiuZvZA6qIzyJ5I2/view?usp=sharing

**Comment by giuliano-december** [comment]
@adidahiya putting `enforceFocus={false}` on the drawer solved that issue for me

**Comment by adidahiya** [comment]
duplicate of #3854 (which has more info)
