### ISSUE TITLE
Blueprint Table sorting not update immediately

### ISSUE THREAD

**Issue by chuyachia** [palantir/blueprint#3846]
#### Environment

- __Package version(s)__: 3.8.2
- __Browser and OS versions__: Firefox  70.0.1 Ubuntu 18.04.3 LTS

#### Steps to reproduce

1. Go to doc page https://blueprintjs.com/docs/#table/features.sorting
2. Sort Asc the first column
3. Focus on one cell in that column
4. Sort Asc again
5. Sort Desc

#### Actual behavior
View is not updated after the Sort Desc. It will update only after you do something else that triggers an update, for example, focus on another cell or scroll.

This is a little bit difficult to reproduce with the small table on the doc page. But in my application with 10000 rows, sorting is not updating immediately every time.

Same behavior of not updating immediately also happens with setting column width with `onColumnWidthChanged`  and `columnWidths`. 

It's probably linked to #3833

#### Expected behavior
View should update

**Comment by oliver-ni** [comment]
I'm having this issue as well, any update?

**Comment by adidahiya** [comment]
should be fixed by table v4.0.0-rc.1
