### ISSUE TITLE
[core] TagInput has wrong focus styling when intent is specified

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#3847]
#### Environment

- __Package version(s)__: core: 3.20.0, select: 3.11.2
- __Browser and OS versions__: Chrome 78.0.3904.97, MacOS 10.14.6

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-ljjq5
#### Steps to reproduce

1. Open codesandbox, focus the select input. Highlight changes to blue. Focus the InputGroup. Highlight stays red.

#### Actual behavior

Highlight changed to blue on intent: "danger" select.

#### Expected behavior

Highlight should stay red exactly like the InputGroup does

#### Possible solution

the .bp3-tag-input has the class .bp3-active which sets the box-shadow to blue. It probably needs some .bp3-intent-danger .bp3-active tweaks to keep it red.

**Comment by adidahiya** [comment]
it seems to be an issue with TagInput in general... updating issue accordingly.

![2019-11-14 11 42 33](https://user-images.githubusercontent.com/723999/68877357-e9e22700-06d3-11ea-916f-96e042b6617e.gif)
