### ISSUE TITLE
DIALOG_FOOTER_ACTIONS missing margin

### ISSUE THREAD

**Issue by IvanBaranov** [palantir/blueprint#3848]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.20.0
- __Browser and OS versions__: Chrome 78.0.3904.97, MacOS 10.14.6

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-5nfn7

#### Steps to reproduce

1. Add div with class DIALOG_FOOTER_ACTIONS inside Dialog component

#### Actual behavior

Margin of footer actions content should be aligned with dialog

#### Expected behavior

There are no margins in DIALOG_FOOTER_ACTIONS

#### Possible solution

Set common dialog margin on DIALOG_FOOTER_ACTIONS

**Comment by adidahiya** [comment]
This is not a bug: you can see the CSS API here requires nesting footer actions inside a dialog footer div: https://blueprintjs.com/docs/#core/components/dialog.css
