### ISSUE TITLE
MultiSelect support limit

### ISSUE THREAD

**Issue by YuK1Game** [palantir/blueprint#3850]
Hi.

I have an idea to make MultiSelect better
It is to set an upper limit on the selection.

There is no upper limit now, and there is no function to forcibly hide the pop bar even if the upper limit is exceeded.

wishing for a better tomorrow
Thanks

**Comment by adidahiya** [comment]
sure, I could see this being added as an option. we would need to think through the UX around what happens when the limit is reached
