### ISSUE TITLE
DatePicker not rendering properly at all :(

### ISSUE THREAD

**Issue by bobbyconnolly** [palantir/blueprint#3852]
#### Environment

- __Package version(s)__: 3.17.2
- __Browser and OS versions__: Chrome 78.0.3904.70

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. create-react-app
2. Followed steps https://blueprintjs.com/docs/#blueprint/getting-started

#### Actual behavior

![image](https://user-images.githubusercontent.com/29126769/68986629-3e2df980-07ef-11ea-9f7c-778d6cff90a3.png)

#### Expected behavior

I expected to see a calender

#### Possible solution

I have no idea what is going on... spent an hour trying to solve. Can't see anything wrong :/

**Comment by johanwilson** [comment]
Looks like you forgot to add the datetime css file.
`@import '~@blueprintjs/datetime/lib/css/blueprint-datetime.css';`

If you use select or table package they have a separate css file to.
`@import '~@blueprintjs/select/lib/css/blueprint-select.css';`
`@import '~@blueprintjs/table/lib/css/table.css';`

**Comment by bobbyconnolly** [comment]
Oh damn.. I knew it was something simple 👍 
thx very much!
