### ISSUE TITLE
Wrong version for latest tag on npm?

### ISSUE THREAD

**Issue by mrxdst** [palantir/blueprint#3853]
From https://www.npmjs.com/package/@blueprintjs/core

    Current Tags
    3.17.2              latest
    3.0.0-rc.1          next
    Version History
    3.17.2              2 days ago
    3.20.0              5 days ago
    3.19.1              a month ago
    3.19.0              a month ago
    3.18.1              2 months ago
    3.18.0              4 months ago
    3.17.1              4 months ago
    3.17.0              4 months ago

**Comment by vladeck** [comment]
Is **3.17.2** supposed to be **3.20.2** as far as features go or... ?

**Comment by adidahiya** [comment]
3.17.2 is a patch on the 3.17.x release branch. 3.20.0 is the latest release.

I'm curious why people install using the `latest` tag? This can easily cause a break if blueprint was to release a new major version. It's better to use a semver range like `^3.20.0`.

**Comment by vladeck** [comment]
@adidahiya Actually, I just run `npm i @blueprintjs/core` and `npm` installed **3.17.2** - did not use `@latest`.

**Comment by mrxdst** [comment]
https://docs.npmjs.com/cli/dist-tag

> By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.

**Comment by silverwind** [comment]
package managers default to install the `latest` dist-tag which is automatically set when unspecified. When publishing older versions, one could set a different tag, e.g. `npm publish --tag stable`.

**Comment by adidahiya** [comment]
it's been fixed with new releases
