### ISSUE TITLE
Fill width html table

### ISSUE THREAD

**Issue by SungJinWoo-SL** [palantir/blueprint#3859]
#### Environment

- __Package version(s)__: 3.20
- __Browser and OS versions__: Firefox 71.0b10 & Windows 10

#### Question

Is it possible to make a [HTML table](https://blueprintjs.com/docs/#core/components/html-table) fill the width of the screen? I'm pretty new to React and Blueprint, sorry if this is a dumb question.

**Comment by pdiazdumont** [comment]
I wanted that too but couldn't find a setting in blueprint, my solution was to use raw CSS.

**Comment by SungJinWoo-SL** [comment]
> 
> 
> I wanted that too but couldn't find a setting in blueprint, my solution was to use raw CSS.

Dang it sucks it's not built in. Thanks!
