### ISSUE TITLE
DateInput: focusing input element when value falls outside minDate or maxDate constraints causes a crash.

### ISSUE THREAD

**Issue by Anveio** [palantir/blueprint#3861]
#### Environment

- __Package version(s)__: blueprintjs/core: 3.20.0, blueprintjs/datetime: 3.15.1
- __Browser and OS versions__: Chrome Version 78.0.3904.97 (Official Build) (64-bit) MacOS Catalina

https://codesandbox.io/s/romantic-dream-8s09x?fontsize=14&hidenavigation=1&theme=dark

#### Steps to reproduce

1.  Go to https://codesandbox.io/s/romantic-dream-8s09x?fontsize=14&hidenavigation=1&theme=dark
2. Click on either "Constrain max date" or "Constrain min date" buttons
3. Bring the `<input />` element into focus (with a click, for example).
4. Observe the application crashing.

#### Actual behavior

The application crashes when the HTML Input element is focused.

#### Expected behavior

The input should have some error state instead of crashing.

#### Possible solution

Haven't dug in to the code quite yet.

**Comment by Anveio** [comment]
Related other issues: https://github.com/palantir/blueprint/issues/3407 and https://github.com/palantir/blueprint/issues/980 but they don't have a CodeSandbox repro

**Comment by patrickk** [comment]
I work with @Anveio. 

Workaround we ended up going with was to update the value of the date picker if its value is less than the minDate to minDate, and same with maxDate if value is greater than maxDate. 

This suits our use case, but it'd still be great if the app didn't crash each time a user tried to pick a date on `Out of range`.

**Comment by adidahiya** [comment]
Given your code sandbox, I don't see how this could actually work out in practice. You have set a max date before your min date... so even if the application _didn't_ crash and the user was able to open the date picker, they wouldn't be able to pick a date and recover from the error:

![2020-02-04 16 56 14](https://user-images.githubusercontent.com/723999/73790922-561e7500-476f-11ea-8add-1c3312ef24e3.gif)

same goes for min date... so even if we did change `DateInput` / `DatePicker` to be more friendly to invalid props... what is your proposal?
