### ISSUE TITLE
Add tractor icon

### ISSUE THREAD

**Issue by sonovawolf** [palantir/blueprint#3865]
![image](https://user-images.githubusercontent.com/3002490/69382757-b885d000-0c6c-11ea-882a-3f6bd60a33c3.png)
Tracking feedback internally, but dropping files here to be ready when we reach a conclusion.
[tractor icons.zip](https://github.com/palantir/blueprint/files/3877096/tractor.icons.zip)

**Comment by sonovawolf** [comment]
Well, option 2 clearly won @adamstorr

**Comment by adamstorr** [comment]
Added here: https://github.com/palantir/blueprint/pull/3878

**Comment by asashour** [comment]
This should be closed.
