### ISSUE TITLE
FileInput doesn't support multiple file uploads

### ISSUE THREAD

**Issue by Bielykh-Artem** [palantir/blueprint#3869]
```ts
<FormGroup>
            <FileInput
              className="form__file"
              inputProps={{ name: 'file' }}
              onInputChange={this.onSelectFile}
              id="file"
              multiple <----!!!!!!!
              buttonText="Browse"
            />
</FormGroup>
```

But this one is ok: `<input type="file" onChange={this.onSelectFile} multiple />`

**Comment by adidahiya** [comment]
@Bielykh-Artem I know it's a little unintuitive, but you need to use `inputProps={{ multiple: true }}` in this case. The top-level `FileInput` props are for the `<label>` element wrapper rendered by the component.

**Comment by Bielykh-Artem** [comment]
Yes, thanks. I already guessed about it.
