### ISSUE TITLE
Unable to pass props to input in DateInput

### ISSUE THREAD

**Issue by jagregory** [palantir/blueprint#387]
### Bug report

Unable to pass props to the input element inside of a DateInput. e.g. can't use the HTML5 validation attributes. Related to: #361 

- __Package version(s)__: @blueprintjs/datetime 1.4.0
- __Browser and OS versions__: All.

#### Steps to reproduce

```jsx
<DateInput required={true} />
```

#### Actual behavior

```html
<input type="text" class="pt-input">
```

#### Expected behavior

```html
<input type="text" class="pt-input" required>
```

**Comment by leebyp** [comment]
To proxy the props down to the input in a sane way, I think we need a new API
```jsx
<DateInput
    datePickerProps={...}
    inputGroupProps={...}
    className, closeOnSelection, defaultValue, format, value...
/>
```
Things to note:
- `datePickerProps` and `inputGroupProps` just proxies the props down to the sub-component
- The exceptions are overlapping props (`defaultValue`, `onChange`, `value`) which are on the `<DateInput />` itself
- Should some props be ignored? In particular for `inputGroupProps`: `rightElement` and `type`. Although, I can foresee a customization with the calendar icon *in addition* to a rightElement (or even substituting it)
- I want to set this up in a way where a `<DateRangeInput />` would also have a decent / similar API if we ever do it.

**Comment by llorca** [comment]
@cmslewis is looking at `DateRangeInput`, so would be neat to have the same API for both indeed

**Comment by cmslewis** [comment]
Ack.

**Comment by valentinvoilean** [comment]
Hi guys ! Any news about this ? I want to add the "name" attribute to serialize the form afterwards.

**Comment by giladgray** [comment]
@valentinvoilean progress here is slow at best because solving this issue correctly will likely be a breaking change (as proposed in https://github.com/palantir/blueprint/issues/387#issuecomment-271671709 above) which will require a new major version. We are in the process of planning Blueprint 2.0 but I can't even begin to offer a time estimate.

**Comment by orecus** [comment]
This would be great, as I would like to pass `pt-fill` to the input within `<DateInput/>` so that the size of the input aligns with the rest of the inputs within my form. 

From my testing this is currently not possible to achive.

**Comment by hmaurer** [comment]
I would also be interested in being able to pass `pt-fill` to a DateInput. Any idea how i can achieve this? Thank you!

**Comment by giladgray** [comment]
@hmaurer this has been possible since #1011 added the `inputProps` prop! a quick glance through the docs should have revealed this.

**Comment by hmaurer** [comment]
@giladgray Thanks! I tried this but it doesn't seem to do the job. The DateInput is wrapped in an inline `pt-popover-wrapper` which doesn't fill the whole container. Am I missing something?

**Comment by sheenm** [comment]
> @giladgray Thanks! I tried this but it doesn't seem to do the job. The DateInput is wrapped in an inline `pt-popover-wrapper` which doesn't fill the whole container. Am I missing something?

I know that's an old question, but for anyone who is interested:
```
<DateInput
            popoverProps={{
                targetTagName: 'div',
                wrapperTagName: 'div'
            }}
 // ... other props
/>
```
that will do the trick
