### ISSUE TITLE
[EditableText] Bugs when @blueprintjs/datetime is not installed

### ISSUE THREAD

**Issue by mormahr** [palantir/blueprint#3870]
#### Environment

- __Package version(s)__: 3.17.2 (core)
- __Browser and OS versions__: macOS 10.14.6, Firefox 70.0.1, Chrome 78.0.3904.108

If possible, link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-np86c

#### Steps to reproduce

1. Click on EditableText field (the one without `alwaysRenderInput`)
2. Click a second time(!)

#### Actual behavior

In Chrome and Firefox i had to click two times to get the input to focus. On the first click the styling changed appropriately, but the input wasn't actually given focus. Only on the second click the input receives focus. Maybe related: The other field with `alwaysRenderInput` is cut off early and only fixes itself after focusing it the first time.

#### Expected behavior

The input should receive focus after the first click.

#### Possible solution

It works in as expected in Safari, but fails in Chrome and Firefox.

Now the wild part: While creating the repro case i discovered that it worked with your "fork this" sandbox and not with the case i made earlier, so i started digging for differences and the result is this: As soon as i install `@blueprintjs/datetime` it works, i don't have to include it / it's css. I just have to install the package and both bugs go away (the double click focus and the early cut off). I'm just gonna assume this is not intentional, as i didn't see anything telling me to install the `datetime` package, when i want to use a component from `core`. If this doesn't happen on your machine i made a [screenrecording](https://drive.google.com/open?id=1ep-fI1aXTDemGURJ_BNQa0pZ2h-_DOjV).

I don't know if i'm missing something as this feels a little too weird to be true, but here we are.

**Edit:** I tried adding `datatime` in a real-world project and it didn't change anything.

**Comment by adidahiya** [comment]
looks like your linked sandbox is using version core v3.18.0, I can't repro the issue there. but I've forked it and can see the issue occur with latest core v3.22.0: https://codesandbox.io/s/blueprint-sandbox-for-3870-6uu3n. most likely caused by #3842 

![2019-11-28 15 55 56](https://user-images.githubusercontent.com/723999/69831483-9dc8d380-11f7-11ea-9772-3e5d97c58d8b.gif)

**Comment by mormahr** [comment]
The _first_ problem (requiring two clicks to focus) seems to be [fixed](https://codesandbox.io/s/blueprint-sandbox-for-3870-oig4w) with v3.22.2

The second problem (clipped input) persists.

**Comment by adidahiya** [comment]
Made a new (forked) sandbox and filed a new issue for the remaining bug: https://github.com/palantir/blueprint/issues/4423
