### ISSUE TITLE
PanelStack totally broken after 3.17.2

### ISSUE THREAD

**Issue by sgarnotel** [palantir/blueprint#3875]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.22.0 - npm 6.13.1 - node 13.2.0
- __Browser and OS versions__: Chromium Version 78.0.3904.108 (Build officiel) Arch Linux (64 bits)

#### Steps to reproduce

1. Build a component with PanelStack
```jsx
<div className="Panel">
     <PanelStack
        className="Panel-stack"
        stack={this.state.panels}
        onOpen={(panel) => this.handleOpen(panel)}
        onClose={this.handleClose}
     />
 </div>
```
The state element `this.state.panels` contains only one element
2. Update `this.state.panels` keeping the same `title`, `component` (update just `props`)

The PanelStack is not updated

#### Actual behavior

With @blueprintjs/core@3.22.0, there is no update

#### Expected behavior

Same behavior of @blueprintjs/core@3.17.2

#### Possible solution

I thing [PR #3787](https://github.com/palantir/blueprint/pull/3787) is part of the problem, but reverse this commit is not enough

**Comment by sgarnotel** [comment]
After tests, the problem is the PR #3787 

Doing that and recompile with the version 3.22.0 works as expected
```jsx
public componentDidUpdate(prevProps: IPanelStackProps, _prevState: IPanelStackState, _snapshot: {}) {
        super.componentDidUpdate(prevProps, _prevState, _snapshot);
        // const stackLength = this.props.stack != null ? this.props.stack.length : 0;
        // const prevStackLength = prevProps.stack != null ? prevProps.stack.length : 0;
        //
        // if (stackLength !== prevStackLength && prevProps.stack != null) {
        //     this.setState({
        //         direction: prevProps.stack.length - this.props.stack.length < 0 ? "push" : "pop",
        //         stack: this.props.stack.slice().reverse(),
        //     });
        // }
        if (this.props.stack !== prevProps.stack && prevProps.stack != null) {
            this.setState({
                direction: prevProps.stack.length - this.props.stack.length < 0 ? "push" : "pop",
                stack: this.props.stack.slice().reverse(),
            });
        }
    }
```

**Comment by marvinsum** [comment]
I see the issue now. I guess the fix would be to always update the local stack whenever `this.props.stack` changes, but only update the animate direction when the stack length changes.
