### ISSUE TITLE
Convert @blueprintjs/tslint-config to eslint

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/blueprint#3877]
`tslint` is deprecated. 

I propose adding a new package `@blueprintjs/eslint-config` which is a duplicate of `@blueprintjs/tslint-config` but converted to eslint. We can keep both for the time being (its rare that they are touched) and when blueprint next major versions, we can remove the tslint ones.

Probably at the same time, we'd want to migrate the linting of blueprint itself to use eslint.

Thoughts?

**Comment by adidahiya** [comment]
Done
