### ISSUE TITLE
Support ArrowKey navigation on contextMenu

### ISSUE THREAD

**Issue by cnrudd** [palantir/blueprint#3881]
#### Environment

- __Package version(s)__: 3.x
- __Browser and OS versions__:  all browsers currently supported

#### Feature request

I couldn't find this feature already requested, so here goes:
Would it be possible to support arrow key navigation on the Context Menu component?
A user could:

- navigate up/down the menu with ArrowUp/Down keys
- move into and open sub menus with the ArrowRight key
- move back to a parent menu and close the sub menu with the ArrowLeft key or Escape key
- close current menu with Escape key
- open menu with Windows menu key (optional, via prop)
- trigger menu button action with Enter key (and then close entire menu)

Thx!

**Comment by adidahiya** [comment]
ContextMenu renders a Menu, so I think your request is essentially the same as this one for Menu: https://github.com/palantir/blueprint/issues/3079
