### ISSUE TITLE
Need an `is-active` class for menu-item

### ISSUE THREAD

**Issue by djyde** [palantir/blueprint#389]
When I click a menu item, I want to keep the item looks focused (actived) 

![image](https://cloud.githubusercontent.com/assets/914329/21477836/add032fc-cb80-11e6-894e-4c3c40e8f774.png)

**Comment by JKillian** [comment]
I believe the docs site actually uses something like this, agreed that it would be useful to promote this to the core library

**Comment by llorca** [comment]
Let's agree on one naming for all these things: `.pt-active` or `.pt-selected`?

**Comment by adidahiya** [comment]
I think we should go with `.pt-active` to be consistent with how button groups work: http://blueprintjs.com/docs/#components.button-group.css.fill

**Comment by leebyp** [comment]
Currently the default for `.pt-menu-item` on hover sets `background: @blue3`. This means that when using `.pt-active` on one item and hover over another, it'll look pretty awkward (attached). How about we add something like a `.pt-selectable` to `.pt-menu` to change the hover and active state colors to what the docs show right now? (I don't like that name, so open to suggestions) @llorca 

<img width="224" alt="screen shot 2017-01-16 at 14 13 20" src="https://cloud.githubusercontent.com/assets/6375593/22001004/3cdaff82-dbf7-11e6-8f67-e807f31b8429.png">

**Comment by llorca** [comment]
Hmm, `.pt-selectable` doesn't seem necessary. Items are always selectable (unless they're disabled).

Maybe we can simply update the hover state of menus to be gray? @pkwi what do you think?

**Comment by leebyp** [comment]
I was initially worried about it being troublesome to have force the consumer to set the `:hover` state in the cases where it shouldn't be selectable (eg. in the screenshot). I just realised that's the intention of `.pt-intent-primary`, so I'm down for the defaults to be like the docs - it also keeps consistency with the default button being grey.
