### ISSUE TITLE
MultiSelect onAdd prop does not fire

### ISSUE THREAD

**Issue by Sktank** [palantir/blueprint#3893]
As per the documentation
1) `onAdd` is a callback invoked when new tags are added by the user pressing `enter` on the input.
2) Pasting `"hello\nworld"` will invoke `onAdd` with `["hello", "world"]`

Recently I've noticed the `onAdd` command is not firing, breaking the above two situations.

**Comment by adidahiya** [comment]
@Sktank there's no top-level `onAdd` prop for MultiSelect. Do you mean `tagInputProps={ onAdd }`? When did this last work for you? Did you recently upgrade your version of the select package? It looks like this PR changed the behavior and could have caused `onAdd` to no longer fire as you expect: https://github.com/palantir/blueprint/pull/3428

**Comment by adidahiya** [comment]
I'm not sure that `tagInputProps.onAdd` is the best for your use case... can you explain a bit more what you're trying to do? Maybe it makes more sense to add an `onCreateItem` callback which gets a list of items when they get created.

**Comment by adidahiya** [comment]
Resolved offline, the features added by #3429 (pasting values) and #3381 (allow creating new items in select components) should cover @Sktank's use case.

Do you think the docs need to be more clear about these features?
