### ISSUE TITLE
Set active suggest item on tab

### ISSUE THREAD

**Issue by jdpaterson** [palantir/blueprint#3895]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question

Is there a way to set the active item of a Suggest component when the user tabs out of the component? I have a few suggests set up in a row and would like to be able to tab back and forth between them. The user would be selecting the values using keyboard up and down

**Comment by adidahiya** [comment]
@jdpaterson yes, [see "Controlled usage" here](https://blueprintjs.com/docs/#select/select-component.controlled-usage) -- you can use the `activeItem` and `onActiveItemChange` props.
