### ISSUE TITLE
Icon : Type script error when using an unkown string in icon property

### ISSUE THREAD

**Issue by etcarrupt** [palantir/blueprint#3897]
#### Environment

- __Package version(s)__: Core 3.22.0, Icons 3.12.0
- __Browser and OS versions__: Chrome 77, Windows 7 Enterprise

#### Steps to reproduce

1. In Visual Studio Code, in a React app, add an `<Icon icon="nothing">`

#### Actual behavior

Typescript show error: Type '\"nothing\"' is not assignable to type 'false | \"add\" | \"add-column-left\" | \"add-column-right\" | \"add-row-bottom\" | \"add-row-top\" | \"add-to-artifact\" | \"add-to-folder\" | \"airplane\" | \"align-center\" | \"align-justify\" | ... 473 more ... | undefined'.

#### Expected behavior

Typescript don't show an error. The documentation say that "Unknown strings will render a blank icon to occupy space.", so Typescript should accept any string as value.

#### Possible solution

This declaration seems to do the trick:
`export declare type IconName = (typeof IconNames)[keyof typeof IconNames] | string;` in iconName.d.ts

**Comment by adidahiya** [comment]
> Unknown strings will render a blank icon to occupy space.

This is the runtime behavior, yes, but we still do compile-type checks to ensure you are using icons as intended. If you need a blank icon, use `"blank"`. We don't plan to expand the type def to allow all strings like you suggested.

**Comment by etcarrupt** [comment]
Oh, I didn't see the "blank" icon. Works for me. Thanks for the feedback

**Comment by oinuma** [comment]
I get the same error when I try to pass iconName as a variable.

```
export default function NavLinkButton({ label = '', path = '', iconName = 'Blank' }): JSX.Element {
  return (
    <NavLink exact to={path} activeClassName={styles.active}>
      <div>
        <Icon className={styles.icon} icon={iconName} iconSize={20} />
        <div className={styles.label}>{label}</div>
      </div>
    </NavLink>
  )
}
```

**Comment by oinuma** [comment]
Type 'string' is not assignable to type 'false | "add" | "add-column-left" | "add-column-right" | "add-row-bottom" | "add-row-top" | "add-to-artifact" | "add-to-folder" | "airplane" | "align-center" | "align-justify" | ... 473 more ... | undefined'.

**Comment by adidahiya** [comment]
@oinuma that's more of a TypeScript problem (not specific to Blueprint)... you have to narrow the type to something like:

```ts
import { IconName } from "@blueprintjs/icons";

export default function NavLinkButton({ label = '', path = '', iconName: IconName = 'blank' }): JSX.Element {
  ...
}
```

(also note the difference in the string literals `'"Blank"` vs `"blank"`, it's case-sensitive.
