### ISSUE TITLE
Filterable feature for MultiSelect and disabling inline search

### ISSUE THREAD

**Issue by arifsuleman** [palantir/blueprint#3899]
I am using blueprint Multiselect component where my use case requires to have filter search input within popover like blueprint Select component has filterable:true option, but MultiSelect component lacks this feature and provides alternate way to search items as inline to input field. The existing input field that is being used for search/filter items that I need to move under popover as first element with rendering other menu items. Appreciate if someone can help to provide example or any guidelines using jsx

**Comment by adidahiya** [comment]
If you're moving the input field inside the popover, then what is shown as the popover target? Do you have a drawing or mockup of what you want the UI to look like? It sounds like you're trying to implement something outside the Blueprint design system, so you may be on your own... it is possible to build your own select / multi-select components using the lower-level QueryList component: https://blueprintjs.com/docs/#select/query-list

**Comment by arifsuleman** [comment]
Hi Adidahiya,
Viewing your response and my requirement, I have given it a shot and it works in my requirement. It may not be ideal for others but it did work for me. The option for filterable: true is not added rather I added the search filter input to MultiSelect as like select component via lower-level QueryList component. 
Working demo with code is here:  https://codesandbox.io/s/blueprintjs-multiselect-with-filter-under-popover-krf3w
My customized version of blueprint MultiSelect has:
1-Input search filter under popover with supporting exact match search feature
2-Custom checkboxes are added as menu items
3-The selected items are shown as list of comma separated items in placeholder as it was needed in my use case. Another part of use case requires to show comma separated values as tooltip once the length of selected items is bigger than the display area. 

![CustomMultiSelect](https://user-images.githubusercontent.com/52038443/88088882-8da99e00-cba4-11ea-9d41-22cbf3bd097f.jpg)
