### ISSUE TITLE
NumericInput sub-unit support at initialization - displayed value is wrong

### ISSUE THREAD

**Issue by iongion** [palantir/blueprint#3902]
#### Environment

- __Package version(s)__:  @blueprintjs/core at 3.22.3
- __Browser and OS versions__: All / any

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 
- https://codesandbox.io/s/react-typescript-ej3b8

#### Steps to reproduce

1. Start with a sub-unit **state** value , the examples starts at **0.5**

#### Actual behavior

Displayed value is wrong, showing **1**

#### Expected behavior

Displayed value should be showing **0.5**

#### Possible solution

- No ideas, implement custom **NumericInput** :(
- It seems it has this issue only with sub-unit values.

![image](https://user-images.githubusercontent.com/867609/71245121-56c09080-2314-11ea-933d-d92b42eb5d85.png)

**Note** - all works correctly with sub-unit, but only after the user performs changes using the up/down arrows, it is just at init that it is wrong.

**Comment by iongion** [comment]
As a workaround, very ugly, but should do the job:

```

**Comment by adidahiya** [comment]
This looks pretty similar to #3889, and I think should be fixed by #3894. Closing for now, but feel free to comment and I'll reopen if it isn't fixed in the next release (coming this week).
