### ISSUE TITLE
Collapse doesnt animate when closing.

### ISSUE THREAD

**Issue by 0xorial** [palantir/blueprint#3903]
#### Environment

- __Package version(s)__:  3.22.3. seems broken since 3.19.1
- __Browser and OS versions__: Chrome 79/Windows 10

 [code sandbox](https://codesandbox.io/s/blueprint-sandbox-4lk4g) 

#### Steps to reproduce

click collapse twice

#### Actual behavior

animated when expanding,
not animated when collapsing

#### Expected behavior

animated when expanding,
animated when collapsing

**Comment by adidahiya** [comment]
weird, I thought I fixed it in https://github.com/palantir/blueprint/pull/3831 but it's still a bug. thanks for pointing it out
