### ISSUE TITLE
Toggle value is always 'on' never 'off;

### ISSUE THREAD

**Issue by stoplion** [palantir/blueprint#3907]
Latest Blueprint
Chrome

https://codesandbox.io/s/blueprint-sandbox-f6ekm

The toggle value is always 'on' never 'off;

**Comment by KRONOS-11** [comment]
Hey @stoplion , if you want to check the checkbox state you should use the checked attribute, the value attribute is by default 'on' which is used when submitting forms, for further explanation please checkout the mdn resource on [checkbox's value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#value).
