### ISSUE TITLE
Add the info line "@import '~@blueprintjs/datetime/lib/css/blueprint-datetime.css'"; in the official DateTime documentation(v3)

### ISSUE THREAD

**Issue by hadnet** [palantir/blueprint#3918]
When using the DateTime component, the official documentation doesn't tell you that you need to add the @import "~@blueprintjs/datetime/lib/css/blueprint-datetime.css"; to works properly after npm install --save @blueprintjs/datetime.

**Comment by adidahiya** [comment]
[This docs page](https://blueprintjs.com/docs/#datetime) ([source](https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/index.md)) mentions reading the getting started docs, which have in bold, in step 3:

> __Don't forget to include the main CSS file from each Blueprint package!__

**Comment by hadnet** [comment]
Yeah, but it would be BETTER just putting the line and make life easy for everyone. If there is a chance for confusing, why not do it?
