### ISSUE TITLE
Dividers in Control Groups have incorrect margins

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#3919]
#### Environment

- __Package version(s)__: `@blueprintjs/core ^3.22.3`
- __Browser and OS versions__: Mac OS X Chrome 79.0.3945.88

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Spotted this while building a `<ControlGroup>` that contained buttons, selects, and some dividers.

```tsx
<ControlGroup>
    // ...Other controls...
    <Button />
    <Divider />
    <Button />
    // ...Other controls...
</ControlGroup>
```

#### Actual behavior

The divider doesn't have its usual `5px` padding. Instead, `<ControlGroup>` overrides with a default `-1px` padding for all controls.

#### Expected behavior

The divider should have a `5px` padding when inside a `<ControlGroup>`.

#### Possible solution

```scss
// Special case for dividers
.bp3-control-group .bp3-divider {
    margin: 5px;
}
```

Labeling P3 because it's an easy 1-line fix of custom CSS for application authors. Filing quickly for tracking, but may be able to open a PR soon.

**Comment by lidyho0708** [comment]
Hi

**Comment by lidyho0708** [comment]
Im Clueless

**Comment by aug-mx** [comment]
hi!how are you

**Comment by adidahiya** [comment]
Actually, I'm not so sure about this. Why put a divider inside a control group instead of separating multiple control groups by dividers? From the existing documentation it feels like a control group is supposed to be one cohesive unit. Can you demonstrate a strong use case for this proposed change?

**Comment by cmslewis** [comment]
This is relevant only if all controls in the control group are minimal - in that case, you might want to chunk controls into sub-groups using vertical dividers, without introducing a bunch of extra padding or rounded border radii (on hover) between sub-groups. Consider this example of a floating text-formatting toolbar, which includes buttons and native select menus:

![image](https://user-images.githubusercontent.com/443450/87968117-c3e80000-ca74-11ea-8c66-0fec9842c0a5.png)

I'll send you a PR link internally. Let me know if I'm missing an obvious workaround though.

**Comment by adidahiya** [comment]
@cmslewis ok that makes sense. There is still some visual weirdness with border radii in this setup, but #4215 looks like a good step in the right direction.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/723999/88190871-cc713f80-cc08-11ea-92b2-c9d81d8d962b.png">
