### ISSUE TITLE
Mixed-type Buttons in ButtonGroup don't render well in Safari

### ISSUE THREAD

**Issue by isTravis** [palantir/blueprint#393]
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Safari 9 and Safari 10

#### Steps to reproduce

Mixed-type button-group do not render harmoniously in Safari (though they do in Chrome and Firefox). By mixed-type, I mean button groups that have both `<a>` and  `<button>`. For example:

```html
<div class="pt-button-group">
  <a class="pt-button" role="button">Hello</a>
  <button type="button" class="pt-button">Goodbye</button>
</div>
```

#### Actual behavior

On Safari, this renders non-grouped and out-of-line buttons:
![screen shot 2016-12-28 at 6 04 36 pm](https://cloud.githubusercontent.com/assets/1000455/21533412/2055abf6-cd28-11e6-90bc-1f8ea8922bc2.png)

#### Expected behavior
On Chrome and Firefox, this renders properly:
![screen shot 2016-12-28 at 6 04 30 pm](https://cloud.githubusercontent.com/assets/1000455/21533416/2820acbe-cd28-11e6-9b63-77c268b1296e.png)

#### Note

I tried this on the BlueprintJS docs site in Safari - copying and pasting the html from above into the inspector - and it works fine:
![screen shot 2016-12-28 at 6 15 15 pm](https://cloud.githubusercontent.com/assets/1000455/21533554/ba135710-cd29-11e6-94c6-53c0bd3c86d9.png)

So - there is either something funky with my setup (scouring over the inspector, I don't see any place I'm overwriting anything though), or there is something in the BlueprintJS docs site that is preventing this bug, that I can't find. If noone is able to reproduce this in their own environments, I'm happy to chock it up to my own setup and feel free to close this, but since I couldn't find the cause, figured I'd post.

**Comment by giladgray** [comment]
@isTravis are you including `normalize.css` on your page? it's an NPM dependency and must be included for optimal browser compatibility.

**Comment by isTravis** [comment]
Thanks for the fast response!

I did not have `normalize.css` and that indeed fixed the issue. I wound up npm installing it and then simply including it `@import "~normalize.css";` in my scss file before the blueprint CSS imports. 

I was going to say I didn't see this anywhere in the docs, but then found #190 and it seems that's already on your radar. 

Thanks again for the help!
