### ISSUE TITLE
Dialog automatically closes when clicking on the scrollbar.

### ISSUE THREAD

**Issue by rostero1** [palantir/blueprint#3930]
Steps: 
1) Navigate to https://blueprintjs.com/docs/#core/components/dialog
2) Click open dialog
3) Resize the window so the scrollbars appears
4) Click on the scrollbar to view the bottom of the modal.
5) You'll see the dialog disappear and the user may not be able to get back to the contents of the dialog.

**Comment by yshterev** [comment]
For some reason `bp3-overlay-backdrop` click seems to be triggered when clicking on scroll...

If you add `pointer-events: none;` to `bp3-overlay-backdrop` you can scroll, but dialog won't close on overlay click.

**Comment by adidahiya** [comment]
Can you please fill out the issue template? Which OS and browser(s) are you using? Thanks

**Comment by rostero1** [comment]
#### Environment

- __Package version(s)__: 3.23.0
- __Browser and OS versions__: Mac Chrome 79.0

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/#core/components/dialog

#### Steps to reproduce

1. Navigate to https://blueprintjs.com/docs/#core/components/dialog
2. Click open dialog
3. Resize the window so the scrollbars appears
4. Click on the scrollbar to view the bottom of the modal.
5. You'll see the dialog disappear and the user may not be able to get back to the contents of the dialog.

#### Actual behavior

The dialog closed when I tried to view more of the dialog contents by clicking on the scrollbar.

#### Expected behavior

The dialog not to close and to view the bottom half of the contents of the dialog.

#### Possible solution

No, but found a few similar issues on other GitHub projects, such as https://github.com/reactstrap/reactstrap/issues/1097.

I did find that Reach Modal does not have this problem:  https://github.com/reach/reach-ui/blob/master/packages/dialog/src/index.tsx#L111 and uses https://www.npmjs.com/package/react-remove-scroll

**Comment by adidahiya** [comment]
This doesn't seem to be an issue with the latest dialog & overlay components.
