### ISSUE TITLE
wrapText support does not work in table

### ISSUE THREAD

**Issue by mvshvets** [palantir/blueprint#3937]
#### Environment

- __Package version(s)__: Table 3.8.2
- __Browser and OS versions__: Chromium 78.0.3904.108, Linux Mint 19.3

#### Actual behavior

When adding a wrapText support to a cell, the text in the cell does not wrap

https://codesandbox.io/s/blueprint-sandbox-ghiiw

#### Expected behavior

Text should wrap while increasing cell height

**Comment by adidahiya** [comment]
It does wrap the text, but you need to further resize the rows to see the wrapped text. This can be done manually by a user:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/723999/72919969-5ef65c00-3d16-11ea-9db0-03398c9798e4.png">

... or programmatically by the [table instance method](https://blueprintjs.com/docs/#table/api.instance-methods) `resizeRowsByApproximateHeight`, as shown in the table-dev-app demo page:

![2020-01-22 12 56 15](https://user-images.githubusercontent.com/723999/72920106-a41a8e00-3d16-11ea-99f6-d310322ec20e.gif)
