### ISSUE TITLE
The layout of the table crash when working with tabs

### ISSUE THREAD

**Issue by mvshvets** [palantir/blueprint#3944]
#### Environment

- __Package version(s)__: Table 3.8.2, Core 3.22.0
- __Browser and OS versions__: Chromium 78.0.3904.108, Linux Mint 19.3

If possible, link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-xi09m

#### Actual behavior

The layout of the table crashes when working with tabs. On the first tab, everything works well, on the second and further - it breaks

#### Expected behavior

The table should look the same on any tab

**Comment by adidahiya** [comment]
I think this is due to lingering issues we have with the table lifecycle methods after refactoring them in 3.8.0... for now I would recommend downgrading to 3.7 until these are addressed https://github.com/palantir/blueprint/milestone/41

**Comment by MonkeyAndres** [comment]
I solved that by forcing a `scrollToRegion(lastColumnRegion)` after `onCompleteRender`. Hope it helps. Let me know if you need more info.
```jsx
const tableRef = useRef()

const onCompleteRender = useCallback(() => {
  const lastColumnRegion = Regions.column(10) // Your table last column
  tableRef.current.scrollToRegion(lastColumnRegion)
}, [])

<Table
  {...tableProps}
  ref={tableRef}
  onCompleteRender={onCompleteRender}
>
  {tableContent}
</Table
```

**Comment by mvshvets** [comment]
> I solved that by forcing a `scrollToRegion(lastColumnRegion)` after `onCompleteRender`. Hope it helps. Let me know if you need more info.
> 
> ```js-jsx
> const tableRef = useRef()
> 
> const onCompleteRender = useCallback(() => {
>   const lastColumnRegion = Regions.column(10) // Your table last column
>   tableRef.current.scrollToRegion(lastColumnRegion)
> }, [])
> 
> <Table
>   {...tableProps}
>   ref={tableRef}
>   onCompleteRender={onCompleteRender}
> >
>   {tableContent}
> </Table
> ```
> 
> Another solution is by adding `renderActiveTabPanelOnly` to the tabs component.

Thanks. It helps me
