### ISSUE TITLE
Migrate away from deprecated React methods

### ISSUE THREAD

**Issue by asashour** [palantir/blueprint#3946]
#### Environment

- __Package version(s)__: 3.23.1
- __Browser and OS versions__: Chrome, Windows 10

#### Steps to reproduce

1. Use `@blueprint/core` 3.23.1 with React `16.12.0`

#### Actual behavior

There are warnings in the browser console, that some lifecycle methods has been renamed. Namely, `componentWillMount`, `componentWillReceiveProps` and  `componentWillUpdate`

#### Expected behavior

No warnings should be shown.

#### Possible solution

The easiest way is to prefix them with `UNSAFE_`, or move the code to some other lifecycle methods, as hinted in this [guide](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by adidahiya** [comment]
Can you please be more specific? None of the published components are using these methods, you can search the source code. There are deprecated components which uses these methods: `AbstractComponent` and `AbstractPureComponent`

**Comment by asashour** [comment]
Thanks for hinting, mostly that is the reason.
