### ISSUE TITLE
Multiple highlighted menu items in the navigator search bar on documentation page

### ISSUE THREAD

**Issue by pavelkang** [palantir/blueprint#395]
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Chrome 55.0.2883.95 (64-bit) macOS Sierra

#### Steps to reproduce

1. type a query in the navigator search bar on blueprint documentation page
2. Hover cursor over an item A, A is highlighted
3. press down/up arrow key. 

#### Actual behavior

Two items are highlighted

#### Expected behavior

I believe we want to remove the highlight effect from the item under the cursor

**Comment by giladgray** [comment]
duplicate of #335

**Comment by JKillian** [comment]
Closing as a duplicate
