### ISSUE TITLE
Breadcrumbs: Support custom renderOverflowBreadcrumb

### ISSUE THREAD

**Issue by yshterev** [palantir/blueprint#3954]
#### Environment

- __Package version(s)__: latest
- __Browser and OS versions__: any

#### Feature request
Support custom renderOverflowBreadcrumb.

#### Examples

This will give more control for overflow menu and it is already done for other cases.
I am using custom renders to pass custom onClick on breadcrumbs that returns the props instead of click event. I extend the props and add more things there for custom logic, but onClick cannot be a prop of breadcrumbs object for this to work. 

I can't do this on overflow menu, because it expects onClick to be part of the breadcrumb props and it always returns the click event.

Something like this will do [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/breadcrumbs/breadcrumbs.tsx#L114 )

```
{orderedItems.map(
  this.props.renderOverflowBreadcrumb || this.renderOverflowBreadcrumb
)}
```

I can PR

**Comment by adidahiya** [comment]
If you are rendering custom breadcrumbs and want a custom overflow menu, then why not make your own breadcrumbs component using the lower-level `OverflowList`? Then you have full control over the rendering. You can see the implementation in `breadcrumbs.tsx` is not a lot of code.

**Comment by yshterev** [comment]
Of course I can do my own component, but there is already support for `breadcrumbRenderer` and `currentBreadcrumbRenderer`. It does not seem like a big change and other people can probably use it too.

@adidahiya If you don't like the idea feel free to close the issue.
