### ISSUE TITLE
Form Controls JS API does not document disable parameter

### ISSUE THREAD

**Issue by isTravis** [palantir/blueprint#396]
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: All

#### Actual behavior

Disabling Form controls (e.g. Checkbox) is possible using the CSS API. It's a bit cumbersome though. A className modifier has to be applied to the label and a a parameter modifier has to be applied to the input tag itself. I wanted to use the JS Component (e.g. `<Checkbox>`) hoping that it would have a simple `disabled` or `isDisabled` parameter, but it does not seem to exist.  Most input form controls seem to allow disabling them through the CSS API, but not through the JS API

Apologies if I'm missing something in the [documentation](http://blueprintjs.com/docs/#components.forms).

#### Expected behavior

I would expect a simple `disabled` parameter to exist on most Form Control components.

**Comment by giladgray** [comment]
@isTravis did you try `<Checkbox disabled />`?

Checkbox (and Radio and Switch) support the full range of HTML props, they're just not all listed in the props table: 
![image](https://cloud.githubusercontent.com/assets/464822/21571424/30b48ad2-ce84-11e6-80aa-1e7193a9de19.png)

**Comment by giladgray** [comment]
reopening to track making the documentation more obvious. 
we could add `disabled` to the table, it's common enough.

**Comment by isTravis** [comment]
Doh - I could've sworn I tried every combination of `className="pt-disabled"` and others, but maybe I kept doing `isDisabled={true}` by accident. Anyways - thanks for pointing out the callout in the docs, don't know how I missed it.

That said though, for Checkboxes, there seem to be a couple inconsistencies in the disabled styling (here I'm talking about the component `<Checkbox disabled />`). 

1. The label text is not greyed out as it is for labels that are explicitly given `'pt-label pt-disabled'`. In the following image, the top (expected) checkbox has been given `'pt-label pt-disabled'`: 
![screen shot 2016-12-30 at 3 07 39 pm](https://cloud.githubusercontent.com/assets/1000455/21571905/ce1b1ddc-cea1-11e6-9c39-314c329c927f.png)

2. The pointer events on a disabled label and input still trigger hover events. Also true regardless of manually adding `'pt-label pt-disabled'`:
![wvrlbqy3gk](https://cloud.githubusercontent.com/assets/1000455/21571940/2be46838-cea2-11e6-9210-44f12a1c884b.gif)

My screencap tool doesn't seem to grab the right cursor icon, but on the labels, it has a `cursor: pointer` and on the checkbox it properly shows `cursor: disabled`.

I could see these 'bugs' being a matter of preference or design decision though, so feel free to categorize them as you wish, or dismiss them if this is proper behavior.

Thanks again for the quick and helpful replies!

**Comment by giladgray** [comment]
@isTravis those don't look like Blueprint checkboxes in your screencaps... [Our checkboxes](http://blueprintjs.com/docs/#components.forms.checkbox) do not have such color or hover problems, so I'll bet you're missing a case in your custom CSS.

**Comment by isTravis** [comment]
Hmm yea - you're right. I still stand by point 1 - that the label color is not greyed out like they are for [disabled labels](http://blueprintjs.com/docs/#components.forms.label.disabled), but you're right that I'm missing a CSS case, causing the hover problems in point 2. 

I (as you can see) am using a slightly different color palette, so had to manually overwrite some of the hover events. I'm really excited for #337 as overriding default colors themselves would mean I no longer have to ensure I've caught all the CSS cases.

Thanks again and apologies for the misstated bug!

**Comment by giladgray** [comment]
@isTravis you should be able to theme checkboxes without #377: all the relevant colors are [already variable-ized](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/_controls.scss#L10-L22) and we don't use color names (like `$blue2`) in the code directly (only in variable aliases with `!default`).

**Comment by isTravis** [comment]
Great - thank you! I assumed that because I went on a 'migrate all the colors' spree when I did the customization, and for [button intents, direct colors are used](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/button/_common.scss#L54). I think I assumed all of the 'intents' that dictate hover state worked like the button ones do and didn't look directly at the checkbox code.  

So, I'm still excited for #377 for the button intents (unless those also get variable-ized).

Many thanks for the quick responses and patience as I continually misstate things :)

**Comment by giladgray** [comment]
aw snap that variable needs a `!default`! i think that would fix your issue and we can keep the "constant colors."

**Comment by giladgray** [comment]
@isTravis see #399, just fixed `$button-intents`.

**Comment by isTravis** [comment]
❤️  🎉  Awesome - thank you! 

That does indeed solve all the manual-color-setting issues I had. Thank you!

Still want to show support in favor of #377 though, because as it stands now, I'm overriding 20-30 variables (and checking to make sure I got the opacities correct, etc), rather than just changing two of the $blue values.

Thanks so much for the quick responses and PRs!

**Comment by giladgray** [comment]
thing is, it feels super weird to me to change the two blue values and leave the other three unchanged. what's worse, given your screencaps i'm assuming you want to change those _blue_ variables to be _grays_. 

seems to me that even though it's more awkward, tweaking more variables gives more control and better results.

**Comment by giladgray** [comment]
i'm trying to treat our color palette as immutable constants. if you don't like `$blue3` then change the usages to `$my-custom-gray`.

**Comment by isTravis** [comment]
Ya, I hear ya. And you of course have a much better overview of the project and how it's structured, so I defer to your insight. 

I agree it's odd to change just the two blues, in my specific case I want to merge the blues and grays, so ideally I'd do something like this:

```
$blue1: $gray1;
$blue2: $gray2;
$blue3: $gray3;
$blue4: $gray4;
$blue5: $gray5;
$blue6: $gray6;
```

Even though this is a bit heretical, because now I have something called blue that isn't blue, it 

1. Prevents me from having to search though all the instances of $blue and overwrite them. (I agree, there's more control by doing so, but in this case, I don't want more control).
2. Future-proofs my code so that if a new component or SCSS class is added, I don't have to go searching through the library to compare what has changed.

Adding the `!default`s also doesn't prohibit anyone from treating the colors as Immutable or having the fine-grain control of overwriting other variables. It could simply be stated that the best practice is to not mutate the colors, but if for some reason I want to rotate the reds, I could. 

Anyways - I'm sure you've given this lots of thought already, so this is just my two cents. I'm also fairly off topic from the original Issue I had posted, so I'm happy to move this discussion to #377 or just finish it there. 

Thanks again, I really appreciate all your work and effort on this!

**Comment by giladgray** [comment]
@isTravis I hear you on the color mapping. I'm inclined to just ship `!default` colors because it'll make life easier for everyone...

would you mind filing a new issue for the disabled label coloring? i'm going to close this issue when i fix the original documentation issue.

**Comment by isTravis** [comment]
Yep - absolutely. New issue is here: #402. Thanks again for all the support!

**Comment by giladgray** [comment]
our pleasure! thank _you_ for the detailed bug reports 🐞
