### ISSUE TITLE
Buttons do not center-align vertically in IE

### ISSUE THREAD

**Issue by saeidN** [palantir/blueprint#3961]
#### Environment

- __Package version(s)__: 3.23.1
- __Browser and OS versions__: IE 11 Windows 10

Test page: https://blueprintjs.com/docs/#core/components/button

#### Actual behavior

![image](https://user-images.githubusercontent.com/2012679/74247671-6c1ebf00-4cb4-11ea-9366-239faec2e124.png)

#### Expected behavior

Button text and icon should be in the middle.

This problem is more visible in small and large buttons. Seem to be fine in regular size buttons.

**Comment by jotasolano** [comment]
May be related to #3927

**Comment by muntact** [comment]
What worked for me was setting the `height` style to `40px`. Though it doesn't appear to fix #3927. I suspect it's a tracked [flexbug](https://github.com/philipwalton/flexbugs). 
 
![Button with centered text IE11](https://user-images.githubusercontent.com/13400754/82625788-2ae66580-9c3a-11ea-838b-30cbad10ef1a.png)

**Comment by adidahiya** [comment]
Closing because we are no longer supporting IE11 in Blueprint v5.0.
