### ISSUE TITLE
Not possible to scroll dialogs in firefox

### ISSUE THREAD

**Issue by alexanderchr** [palantir/blueprint#3962]
## Environment

- __Package version(s)__: @blueprintjs/core 3.23.1
- __Browser and OS versions__: MacOS 10.14.6, Firefox 72.0.2

https://codesandbox.io/s/blueprint-sandbox-rz8or
https://rz8or.csb.app/ (the bug only appears here, not in the small window in the sandbox)

#### Steps to reproduce

Create a dialog with overflowing content. Open in Firefox and try to scroll the dialog.

#### Actual behavior
Is is not possible to scroll the dialog using the scrollbar or mousewheel. However if you scroll by tabbing to the button at the bottom (in the example above) scrolling by mousewheel starts working again. If you scroll all the way to the top it becomes stuck there again.

Works without issue in Chrome and Safari.

#### Expected behavior
It should always be possible to scroll.

#### Possible solution
I think this is an issue with Firefox.

Not using portals (`usePortal={false}`) makes things work.

Moving the backdrop `bp3-overlay-backdrop` to above (as a sibling) `bp3-overlay`, instead of having it as a child of `bp3-overlay` fixes the issue. Not sure if this is a feasible solution.

**Comment by alexanderchr** [comment]
I think #3930 is related to this.

**Comment by adidahiya** [comment]
This doesn't seem to be an issue with the latest dialog & overlay components.
