### ISSUE TITLE
ButtonGroup can get into a state where multiple buttons are pressed

### ISSUE THREAD

**Issue by peterjcoffman** [palantir/blueprint#3971]
#### Environment

- __Package version(s)__:   3.23
- __Browser and OS versions__:  Google Chrome v80.0 on MacOS Catalina v10.15.3

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-q1rn2

#### Steps to reproduce

1. Click on the first button in the ButtonGroup. Ensure that pressing Tab will focus the next button in the group.

2. Press Tab and Enter at the same time.

#### Actual behavior

Multiple buttons are shown as pressed at the same time.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/48924151/74774115-22f4df00-5261-11ea-919f-9efcd1bd5d47.png">

#### Expected behavior

Only one button at a time should be shown as pressed, namely the one that was pressed most recently.

#### Other notes

This is also reproducible 'in the wild' on the Blueprint documentation page [here](https://blueprintjs.com/docs/#core/components/button-group)

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/48924151/74773953-dc9f8000-5260-11ea-9bd0-fa9bca6a50b2.png">

**Comment by adidahiya** [comment]
> Only one button at a time should be shown as pressed, namely the one that was pressed most recently.

Not necessarily... it is not a _radio_ button group, it is simply a button group. There are some use cases where (for example) a button group may be used as a toolbar and multiple buttons should be selected.

If you wish to enforce that only one item in the group is selected, you may want to create a wrapper component, e.g. `<RadioButtonGroup>`.

**Comment by peterjcoffman** [comment]
> Not necessarily... it is not a _radio_ button group, it is simply a button group. There are some use cases where (for example) a button group may be used as a toolbar and multiple buttons should be selected.

That makes sense, but in my example and in the examples on [the Blueprint documentation page](https://blueprintjs.com/docs/#core/components/button-group) it is being used for radio buttons. In my example, 'bgValue' is always one of "Primary", "Warning", "Danger", or "Success", and on the Blueprint docs page it's always one of "Left", "Center", or "Right".

My example works as expected most of the time, but when very quickly changing buttons by simultaneously hitting Tab + Enter the ButtonGroup can enter a state where buttons which should not be pressed are displayed as pressed. Given that this behavior only shows up in that edge case, I doubt very much it is desired.

**Comment by adidahiya** [comment]
> Given that this behavior only shows up in that edge case, I doubt very much it is desired.

I agree that it is usually undesirable behavior... but the ButtonGroup component is intentionally very simple by design. It has no logic in it, it simply renders markup which applies the right styling. At this point I'm not convinced that we need to extend its functionality to give it knowledge of its Button children components.

**Comment by peterjcoffman** [comment]
I have found the cause of this issue. It is a problem with the Button component, not with the ButtonGroup. The relevant code can be found here:

https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/abstractButton.tsx

The problem is in the `onKeyUp` and `onKeyDown` handlers. `onKeyDown` sets the Button's `isActive` flag to true if the user hit Enter. This flag is reset in `onKeyUp`. The button is displayed as active if _either_ it gets `active = true` as a prop _or_ its `isActive` flag is set:

```                [Classes.ACTIVE]: this.state.isActive || this.props.active,```

The issue occurs when the Button does not handle both events, i.e. it gets the `onKeyDown` event but not the `keyUp` event. I can trigger this reliably by holding Enter on a button, tabbing to another button, and then releasing Enter. Since the first Button never gets the `keyUp` event, it will never reset its `isActive` flag and will never become inactive.

My workaround is passing each button a prop of `key: `${active} ${value}`, where `active` is the Button component's `active` prop and `value` is the text contained in the button. This will force a remount whenever `active` changes, which will reset the `isActive` flag.
