### ISSUE TITLE
Scrolling at the bottom of a Table with ghost cells triggers a "bounce"

### ISSUE THREAD

**Issue by nadia26** [palantir/blueprint#3975]
#### Environment

- __Package version(s)__: core 3.22.3, table 3.8.3

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprintjs-3-playground-4v9h0?fontsize=14&hidenavigation=1&theme=dark

#### Steps to reproduce

1. Make a `Table` with `enableGhostCells={true}`
2. Set the table to have more rows than are visible in the table's height. i.e. scrolling is necessary to reach the final row.
3. Scroll all the way to the bottom of the table.

#### Actual behavior

A "bounce" effect. When you scroll past the bottom of the table, the scroll bar on the right moves upwards momentarily and then back down to the bottom. This gives the effect that more data is being loaded (and then potentially hidden) when it's not. It looks as if ghost cells are being inserted on scroll, and then removed upon realizing they're not necessary.

#### Expected behavior

Vertical scrolling looks as it would on the same tables with `enableGhostCells={false}`

#### Possible solution

Short of a full solution, the ability to enable ghost cells just horizontally would accomplish what we're looking for.

**Comment by adidahiya** [comment]
This seems similar to https://github.com/palantir/blueprint/issues/5027, which has been fixed in recent versions of `@blueprintjs/table` in the Table2 component. I can't repro it anymore, see this sandbox: https://codesandbox.io/s/great-greider-8mtmkg?file=/src/index.tsx
