### ISSUE TITLE
MenuItem's don't disable interaction on hover & click when disabled

### ISSUE THREAD

**Issue by dmackerman** [palantir/blueprint#398]
### Bug report

- __Package version(s)__:  1.4.0
- __Browser and OS versions__:  Chrome, OSX

#### Steps to reproduce

1. Add `disabled={true}` to a `MenuItem` that contains subitems.
```js
        <MenuItem
          disabled={isDisabled}
          text="Create New View"
          intent={Intent.SUCCESS}
          iconName="add"
        >
           <MenuItem text="From scratch" />
          <MenuItem text="Clone existing" />
...

```
2. Submenu is still shown on hover.

My impression was that disabled was supposed to disable all interactivity. This also can be seen if you attach an `href` to a `MenuItem`, the href still fires on click.

**Comment by giladgray** [comment]
wow great catch! got a fix in PR already :)

**Comment by dmackerman** [comment]
Some more details about click - it appears that `onClick` isn't called when `disabled` is present, but maybe a call to `e.preventDefault` to stop the `href` from firing on click.

**Comment by giladgray** [comment]
[i fixed the `href` issue too](https://github.com/palantir/blueprint/pull/400/files#diff-24db1b93aa0f0d687cf8dfb451e77512R109); now it won't be set at all when `disabled`. i tested locally, works beautifully.
