### ISSUE TITLE
"Invalid bin entry" warnings on 'yarn add'

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#3984]
#### Environment

- __Package version(s)__: `@blueprintjs/core@3.24.0`
- __Browser and OS versions__: Linux

#### Steps to reproduce

1. `yarn add @blueprintjs/core@3.24.0`

#### Actual behavior

````
warning @blueprintjs/core@3.24.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.24.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
````

#### Expected behavior

No warnings

#### Possible solution

Fix bin scripts

**Comment by silverwind** [comment]
Related to https://github.com/yarnpkg/yarn/pull/7755. Yarn does not seem to allow dots in the bin script names:

````
  "bin": {
    "upgrade-blueprint-2.0.0-rename": "./scripts/upgrade-blueprint-2.0.0-rename.sh",
    "upgrade-blueprint-3.0.0-rename": "./scripts/upgrade-blueprint-3.0.0-rename.sh"
  },
````

**Comment by silverwind** [comment]
Actually, it was fixed in https://github.com/yarnpkg/yarn/pull/7811. Upgrading to yarn 1.22 solves it.

**Comment by adidahiya** [comment]
nice, thanks for the update!
