### ISSUE TITLE
In a Table of EditableCells, when using Tab/Enter to navigate and update cells, every other cell is updated.

### ISSUE THREAD

**Issue by roberthahn** [palantir/blueprint#3988]
#### Environment

`@blueprintjs/core 3.24.0` and `@blueprintjs/table 3.8.3`

#### Steps to reproduce

1. I created a component that renders a table of `EditableCell`s. You must have a minimum number of cells (Discussion below)
1. Please load https://codesandbox.io/s/elastic-payne-iu8mt
1.  Starting from the top left cell, using only the keyboard, type a letter, then Tab (or enter), then a letter, then Tab (or Enter). You may need to click on the first cell with a mouse to bring focus to the table.

#### Actual behavior

When tabbing, every other cell gets updated with 2 letters ('ab', no change, 'cd', etc)
When using 'Enter', every other row gets an update.

#### Expected behavior

Each cell should be updated with one letter

##### Minimum Table Size
In an effort to chase down the repro steps, I discovered the table had to be a certain minimum size:

* 5x5 (25 cells)
* 6x4 (24 cells)
* 7x3 (21 cells)

Trying 10x2 or 6x3 or 5x4 fails to repro the bug.  I do not know if the number of cells is significant.

##### Indications of a regression

I noticed that the behaviour didn't happen when trying to repro using codepens that relied on 3.18.0/3.7.0 of core/table. I'm planning on using those older versions in the meantime. I also did not experiment with different combinations of versions of core and table, because I assume that each release date corresponds to a particular tested combination of components.

Finally, I noticed between these two releases a variation on the behaviour where doubled up input only happened in the top-left cell, but every other cell behaved as expected.

##### Possible areas to focus on

Without looking at the source code, and basing this only on observation, it feels like the logic around ensuring that the focus is applied to the correct cell is less robust than it ought to be.

**Comment by roberthahn** [comment]
Addendum: no code sandbox because the one that's linked uses 3.18.0/3.7.0 and I haven't used this tool before.

**Comment by roberthahn** [comment]
I was able to get CodePen running here with the latest: https://codesandbox.io/s/elastic-payne-iu8mt and could not repro the issue. I'll continue to refine my local code to attempt reliable repro.

**Comment by roberthahn** [comment]
I traced a bit through the code in the Chrome debugger.

When reproducing the bug by tabbing across columns, I observed that `renderNewCell()` in `src/tableBodyCells.tsx` was only being called on every other cell.

Tracing back a bit further, I was finding that `renderNewCell()` was being called in the context of `renderBatchedCells()`, which appeared to be called after every Tab. So it seems that there's something happening within `renderBatchedCells()` or the batching library that's causing `renderNewCell()`to NOT be called on every Tab/Enter.

**Comment by roberthahn** [comment]
Please let me know if anything's not clear or if you can't repro. This was driving me out of my mind for the longest time until I worked out reliable repro (for myself at least)

**Comment by adidahiya** [comment]
thanks for the repro steps. I would recommend downgrading to table v3.7.x for now (it should work with a newer version of core just fine), as the 3.8.x range has a number of React lifecycle related issues (see the milestone I just linked this issue to)

**Comment by roberthahn** [comment]
Thanks for the response. I appreciate the package versioning guidance and the background, too.  It seemed weird to me that no one had reported anything like this before, so the context was very useful.

**Comment by davidko604** [comment]
Thanks for this!  I was having the same issue when I use the latest table version (3.8.22) even using the following example table:
https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/table-examples/tableEditableExample.tsx

I downgraded to v3.7.1 as recommended and it fixes the issue.

**Comment by adidahiya** [comment]
might be fixed in table v4.0.0-rc.1, but if it's not, please let me know and I'll re-open.
