### ISSUE TITLE
Cannot re-export a type when the '--isolatedModules' flag is provided.  TS1205

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#3990]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.24.0, @blueprintjs/icons@3.14.0
- __Browser and OS versions__: All browsers, all OSes

#### Steps to reproduce

1. git clone https://github.com/CCI-Tools/cate-webui.git
1. cd cate-webui
1. yarn install
1. yarn start

#### Actual behavior

When running my project bootstrapped with [create-react-app](https://create-react-app.dev/), I get the following TypeScript compiler error:

```
D:/Projects/cate-webui/node_modules/@blueprintjs/core/src/components/icon/icon.tsx
TypeScript error in D:/Projects/cate-webui/node_modules/@blueprintjs/core/src/components/icon/icon.tsx(24,10):
Cannot re-export a type when the '--isolatedModules' flag is provided.  TS1205

    22 | import { AbstractPureComponent2, Classes, DISPLAYNAME_PREFIX, IIntentProps, IProps, MaybeElement } from "../../common";
    23 | 
  > 24 | export { IconName };
       |          ^
    25 | 
    26 | export interface IIconProps extends IIntentProps, IProps {
    27 |     /** This component does not support custom children. Use the `icon` prop. */
``` 

#### Expected behavior

BlueprintJS should be usable with `tsconfig.json` where 

```json
{
    "compilerOptions": {
        "isolatedModules": true,
        ...
    },
    ...
}
```

#### Possible solution

Change lines 21 - 24 in [src/components/icon/icon.tsx](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/icon/icon.tsx#L21-L24) to become:

```javascript
import { IconName as _IconName, IconSvgPaths16, IconSvgPaths20 } from "@blueprintjs/icons";
import { AbstractPureComponent2, Classes, DISPLAYNAME_PREFIX, IIntentProps, IProps, MaybeElement } from "../../common";

export type IconName = _IconName;
```

**Comment by forman** [comment]
I should mention that [create-react-app](https://create-react-app.dev/) requires `"isolatedModules": true`. See also

* https://github.com/facebook/create-react-app/issues/5738#issuecomment-443487322

**Comment by forman** [comment]
Oops, sorry! Found the root cause. WebStorm automatically placed an import into one of our source files:

```typescript
import { IconName } from '@blueprintjs/core/src/components/icon/icon';
```

Closing this...

**Comment by switz** [comment]
This just started popping up for me today, I tried clearing node_modules and my yarn cache, but it persists.

Edit: this must be related to Next.js 9.5. 9.4 still works.
