### ISSUE TITLE
Icon htmlTitle not working

### ISSUE THREAD

**Issue by Redirts** [palantir/blueprint#3994]
#### Environment

- __Package version(s)__: 3.15.0
- __Browser and OS versions__: Firefox Quantum 68.5.0esr (64-bit)/Chrome 79.0.3945.130

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-igfrk

#### Steps to reproduce

1. Add htmlTitle attribute to an Icon
2. Add title attribute to an Icon

#### Actual behavior

1. Adding htmlTitle attribute renders console error:
Warning: React does not recognize the `htmlTitle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `htmltitle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

and no tooltip is shown on hover

2. Adding title works fine.

#### Expected behavior

1. Either there is an implementation error or the documentation is wrong.

**Comment by adidahiya** [comment]
Can you link to a code sandbox repro?

**Comment by Redirts** [comment]
I already did above: https://codesandbox.io/s/blueprint-sandbox-igfrk :-)
Thanks

**Comment by adidahiya** [comment]
I don't see the `Icon` component used anywhere in that sandbox.

I see you added an `htmlTitle` to a Button in CoreExample.tsx, is that what you mean? If so, that does not type check because it is not a valid prop for that component.

```ts
<Button intent={Intent.WARNING} text="Warning" htmlTitle="test2" />
```

**Comment by Redirts** [comment]
Sorry my bad.
