### ISSUE TITLE
renderDay method of DatePicker library is not being called

### ISSUE THREAD

**Issue by MalikBagwala** [palantir/blueprint#3996]
#### Environment

Package version  - `@blueprintjs/datetime` - 3.15.2
Browser and OS - Chrome 80.0.3987.122 with Ubuntu 19.10

#### Steps to reproduce

1. call out `renderDay` method of the DatePicker component 
2. the function is just not called

So, this is my code

```
import React from "react";
import { DatePicker } from "@blueprintjs/datetime";
const Dashboard = () => {
  return (
    <>
      <DatePicker
        dayPickerProps={{
          renderDay(props, date) {
            console.log("DATE CALLED");
            return <td>3</td>;
          }
        }}
      />
    </>
  );
};

export default Dashboard;
```

Hover it is clearly seen that the `renderDay` function is not called

![Screenshot from 2020-03-02 11-49-28](https://user-images.githubusercontent.com/23068029/75650522-19657100-5c7c-11ea-8055-1425a360fc18.png)

**Comment by adidahiya** [comment]
It looks like the documentation should be updated here. `renderDay` is managed by the component and cannot be customized. https://github.com/palantir/blueprint/blob/dd8b43c4198a50b33d2bfc0448215eec370ed60d/packages/datetime/src/datePicker.tsx#L43-L45

What are you hoping to achieve by customizing `renderDay`? Can you share more info about your use case?

**Comment by MalikBagwala** [comment]
@adidahiya I want to show a small red coloured dot (like a notification badge) on particular dates. and when the user hovers over it i want to show an alert( a tooltip)

**Comment by MalikBagwala** [comment]
@adidahiya  is there any way I can implement this functionallity in the current version?

**Comment by giladgray** [comment]
@MalikBagwala of course it's _possible_ to implement this. send a PR, if you will :+1

**Comment by adidahiya** [comment]
I think it would have to be a little more nuanced than that; Blueprint would have to take the result of `dayPickerProps.renderDay` _in place of_ its current implementation... something like:

https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/datePicker.tsx#L179

```
                        renderDay={dayPickerProps?.renderDay ?? this.renderDay}
```

and there should be a mention in the docs that the Blueprint user is expected to apply the wrapping class `Classes.DATEPICKER_DAY_WRAPPER` on the element rendered by `dayPickerProps.renderDay` to get the default Blueprint styling

**Comment by MalikBagwala** [comment]
@adidahiya 

I have added the change in a pull request(as you suggested)
Please check this out

https://github.com/palantir/blueprint/pull/4012

I am getting a lint check fail..do let me know what that means

**Comment by MalikBagwala** [comment]
Merged all the changes successfully
