### ISSUE TITLE
Outlined props: Button component

### ISSUE THREAD

**Issue by s-solyanik** [palantir/blueprint#3997]
Hello.

First of all I should l say thx for cool toolkit)
I've got a console warning when update to a new version. 

#### Environment

- __Package version(s)__: "^3.24.0",
- __Browser and OS versions__: doesn't matter 

I haven't checked it on prod env, but it seems that it happens in dev mode. 

#### Steps to reproduce

1. Add Button component
2. Add outline props to that component according to doc (eg outline={true}) 
3. Open app in browser

#### Actual behavior

React-dom warning in console.
react-dom.development.js:530 Warning: Received `true` for a non-boolean attribute `outlined`.

If you want to write it to the DOM, pass a string instead: outlined="true" or outlined={value.toString()}.
    in button (created by Blueprint3.Button)

#### Expected behavior

console without warning 

#### Possible solution
Are you sure that you do not forget to add "outlined" attr to INVALID_PROPS variable that is used by removeNonHTMLProps?
node_modules/@blueprintjs/core/src/common/props.ts

**Comment by adidahiya** [comment]
you're right, thanks for the heads up
