### ISSUE TITLE
Icon Notifications not seen  

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#3999]
#### Feature request

New icon to handle notifications not read yet : 

You already have something similar for inbox :
![image](https://user-images.githubusercontent.com/9548473/75862935-f9f75100-5dff-11ea-9e05-2e476348c318.png)

But not for notifications :

![image](https://user-images.githubusercontent.com/9548473/75863060-2ca14980-5e00-11ea-89f0-f9e925004ec8.png)

#### Examples

![image](https://user-images.githubusercontent.com/9548473/75863281-80ac2e00-5e00-11ea-9b05-1146317b759c.png)

**Comment by adidahiya** [comment]
Hi @LoiKos we generally don't accept public icon requests; new ones are added as needed in Palantir applications. You might be able to get away with creating such an icon yourself with CSS. Try adding a `::before` or `::after` pseudo element to `.bp3-icon-notifications` and styling it like a circle.
