### ISSUE TITLE
How to detect MenuItem's onMouseHover

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#4000]
Hi,

I need to detect a menuItem's mousehover (onClick doesn't meet my need) and i will do some actions that depends on hoveredMenuItem

is there anyway to do this ?

Thanks.

**Comment by adidahiya** [comment]
MenuItem spreads all HTML props to its rendered DOM, so you can attach event handlers like `onMouseEnter`, `onMouseLeave`, etc

https://github.com/palantir/blueprint/blob/803cf2c036c0f58cf5696b571cd21ce769facc72/packages/core/src/components/menu/menuItem.tsx#L149
