### ISSUE TITLE
Date range input docs give no mention of styling

### ISSUE THREAD

**Issue by dubwub** [palantir/blueprint#4002]
### Versions
Blueprint v3
Browser/OS agnostic I'd imagine, but Chrome/MacOS

### Bug
I imported and used https://blueprintjs.com/docs/#datetime/daterangeinput and out of the box it looks like the following:
<img width="338" alt="Screen Shot 2020-03-06 at 4 04 32 PM" src="https://user-images.githubusercontent.com/9725102/76122593-6de25680-5fc4-11ea-86f4-f28b78fe882d.png">

Tried to do some debugging on my end, was surprised to see this behavior because most BlueprintJS components work amazingly out of the box, eventually came across https://github.com/gpbl/react-day-picker/issues/265, and realized that I was missing this scss line: `@import "../node_modules/react-day-picker/lib/style";`

And now it looks like:
<img width="565" alt="Screen Shot 2020-03-06 at 4 04 42 PM" src="https://user-images.githubusercontent.com/9725102/76122739-c9acdf80-5fc4-11ea-878d-97e2169831ae.png">

Would love for the docs to mention styling on this page: https://blueprintjs.com/docs/#datetime/daterangeinput so that people in the future won't be confused coming across this.

Thanks!
Darwin

**Comment by adidahiya** [comment]
Did you import the "main" CSS file from the `@blueprintjs/datetime` package?

```
@import "~@blueprintjs/datetime/lib/css/blueprint-datetime.css";
```

You shouldn't need to reference react-day-picker directly.

The [index page](https://blueprintjs.com/docs/#datetime) of the datetime package documentation links you to the "getting started" page, which has installation info relevant to all Blueprint packages:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/723999/76150355-a4c57480-6077-11ea-96a1-dd9cdd7d35bf.png">

**Comment by dubwub** [comment]
Ah didn't see that. Cheers, thanks!
