### ISSUE TITLE
Display a React component as MenuItem

### ISSUE THREAD

**Issue by spider58** [palantir/blueprint#4009]
Hi,

I want to display a React component in a menu as MenuItem

I tried

```
<Menu>
                    <MenuItem text={ <MyComponent /> } />
</Menu>
```
and

```
<Menu>
                    <MenuItem labelElement={ <MyComponent /> } />
</Menu>
```

But getting "**type is invalid**" error on both codes because

Is there ay posibility for this?

**Comment by giladgray** [comment]
@spider58 that is valid code. perhaps your component definition is wrong.

**Comment by adidahiya** [comment]
@spider58 please use the issue template and link a code sandbox to help with debugging

**Comment by spider58** [comment]
sorry for inconvenience. This is my fault.

changed this 
`import { MyComponent } from "./bla"
`
into this
`import MyComponent from "./bla"
`
and it's worked
