### ISSUE TITLE
Table loading states docs example doesn't respect Cells toggle

### ISSUE THREAD

**Issue by rootulp** [palantir/blueprint#4013]
#### Steps to reproduce

1. Navigate to https://blueprintjs.com/docs/#table/features.table-loading-states
1. Toggle everything off
1. Try toggling cells on

#### Actual behavior

![2020-03-17 14 19 12](https://user-images.githubusercontent.com/3699047/76888534-75262180-685a-11ea-8c38-9a5f171b71bb.gif)

#### Expected behavior

The cells to display as loading

**Comment by adidahiya** [comment]
I think this is related to #3774, part of a group of issues in table v3.8.x: https://github.com/palantir/blueprint/milestone/41

for now, please downgrade to table v3.7.x, it should work fine with the latest core package.

**Comment by adidahiya** [comment]
fixed in table v4.0.0-rc.1
