### ISSUE TITLE
Table loading states docs does not respect loading column

### ISSUE THREAD

**Issue by rootulp** [palantir/blueprint#4014]
#### Steps to reproduce

1. Navigate to https://blueprintjs.com/docs/#table/features.table-loading-states
1. Change the column in the select

#### Actual behavior

![2020-03-17 14 22 03](https://user-images.githubusercontent.com/3699047/76888705-c6ceac00-685a-11ea-9c0c-9b13b99b7586.gif)

#### Expected behavior
I would expect the Number column to show loading cells, not the Name column.

**Comment by adidahiya** [comment]
I think this is related to #3774, part of a group of issues in table v3.8.x: https://github.com/palantir/blueprint/milestone/41

for now, please downgrade to table v3.7.x, it should work fine with the latest core package.

**Comment by adidahiya** [comment]
fixed in table v4.0.0-rc.1
