### ISSUE TITLE
Support for intents on HTMLSelect

### ISSUE THREAD

**Issue by damianrusak** [palantir/blueprint#4016]
It would be helpful to have `HTMLSelect` (and other html elements) support Blueprint intents wrt styling (especially `DANGER`). Would it make sense or is it ruled out in order to be more in parity with native `select` element?

**Comment by adidahiya** [comment]
Yeah, I think this makes sense, it could take on intents the same way Buttons do.

**Comment by adidahiya** [comment]
Merging this issue into #5022, which is more comprehensive
