### ISSUE TITLE
Expose isConfirmButtonLoading for Alert

### ISSUE THREAD

**Issue by rootulp** [palantir/blueprint#4017]
#### Feature request

I have a use case where I would like the Alert button's confirm button to display a spinner (while executing a network request) prior to the Alert dialog closing. Is it possible to expose an `isConfirmButtonLoading : boolean` prop to enable this feature?

**Comment by adidahiya** [comment]
I don't want to add new props to Alert, it's basically a thin layer of syntactic sugar for Dialog. I think your customization needs are best met by using Dialog directly and rendering a bit of extra markup to match Alert.
