### ISSUE TITLE
[Tooltip] Flickering with parent that has overflow: auto.

### ISSUE THREAD

**Issue by ellisio** [palantir/blueprint#4019]
#### Environment

- __Package version(s)__: `core@3.24.0`
- __Browser and OS versions__: Chrome 80.0.3987.132

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/stoic-meitner-ymv8s

#### Steps to reproduce

1. Hover the "Home" icon.
2. Observe the Tooltip flickers, and doesn't position itself to the right.

#### Expected behavior

1. Expect the Tooltip to display to the right, just like the "Expand" icon at the bottom of the sidebar.

#### Details

The `.primary-items` div contains `overflow: auto`. This is so the top group will scroll if a user shrinks their browser to a small enough view port. If I remove this div, the tooltips behave fine, as can be seen with the expand icon at the bottom.

**Comment by adidahiya** [comment]
Can you try messing around with the [popper.js modifiers](https://blueprintjs.com/docs/#core/components/popover.modifiers)? There are a few layout things going on in your example with `position: fixed` on sidebar and `overflow: hidden` on body... which might be preventing the positioning algorithm from working

**Comment by ellisio** [comment]
@adidahiya You rock! Adding the following solves it:

```
modifiers={{
  preventOverflow: { enabled: false },
  flip: { enabled: false }
}}
```
