### ISSUE TITLE
How do I set focus on a Select component without triggering the popup?

### ISSUE THREAD

**Issue by roberthahn** [palantir/blueprint#4028]
#### Environment

- __Package version(s)__: Core: 3.24.0; Select 3.12.0
- __Browser and OS versions__: Chrome 80.0.3987.132, macOS 10.15.3

#### Question

I've created a `ControlGroup` comprising a `Select` component, and an `InputGroup`. The way this works is that you select a value from the dropdown, add some text to the  text field, then when I press 'Enter', add the pair of values to a list.

Since it's possible a user may want to add many such pairs of values, I'd like to bring the focus halo back to the `Select` component. I accomplish this by doing a couple of things:

```
<Select items={...} itemRenderer={...} itemPredicate={...} onItemSelect={...}>
   <Button text={...} rightIcon="caret-down" elementRef={this.setButtonRef} />
</Select>
```

`this.setButtonRef()` sets a state variable, `this.state.buttonRef`,  holding a reference to the element

Finally, whenever a pair of values is added, I run this line of code to bring the focus halo back to the dropdown.

` this.state.buttonRef.focus()`

What I discover is that calling this does bring the focus halo to the `Select` component, but it _also_ causes the popup to display.  I was expecting to see the outline move to the button, and the user to either click on it or press 'Enter' to bring up the popup.

What do I need to do to set the focus halo on the `Select` button such that no popup is automatically triggered, and subsequently pressing 'Enter' _does_ trigger the popup?

**Comment by adidahiya** [comment]
Apologies for the delayed response here. I attempted to repro this in the latest Blueprint v5.x versions and was not able to; focusing on a Button inside a Select does not seem to open the popover: https://codesandbox.io/p/sandbox/romantic-brahmagupta-f67p6d?file=%2Fsrc%2FSelectExample.tsx%3A30%2C11

If you are able to repro this somehow, though, I would suggest trying `popoverProps={{{ openOnTargetFocus: false }}` to disable the behavior where focusing on a Popover's target opens it.
