### ISSUE TITLE
Build error due to AbstractComponent

### ISSUE THREAD

**Issue by lukasbach** [palantir/blueprint#4035]
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: Chrome 80.0.3987.149, Windows 10 v1903, Typescript 3.7.2, React 16.13.1, @types/react 16.9.31

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Occurs when I've attempted to build a project that uses BlueprintJs as dependency.

#### Actual behavior

I got the following error:

```
.../node_modules/@blueprintjs/core/src/common/abstractComponent.ts
TypeScript error in .../node_modules/@blueprintjs/core/src/common/abstractComponent.ts(33,15):
Argument of type 'P | undefined' is not assignable to parameter of type 'P'.
  Type 'undefined' is not assignable to type 'P'.  TS2345

    31 | 
    32 |     constructor(props?: P, context?: any) {
  > 33 |         super(props, context);
       |               ^
    34 |         if (!isNodeEnv("production")) {
    35 |             this.validateProps(this.props);
    36 |         }
```

#### Expected behavior

The project should build.

#### Possible solution

The constructor of ``React.Component`` in fact requires props as parameter, so calling ``super`` in the constructor of ``AbstractComponent`` needs props that may not be undefined. Maybe not allowing the props of ``AbstractComponent`` to be undefined already solves it.

**Comment by adidahiya** [comment]
We don't compile with `scrictNullChecks`, so this doesn't show up as a build error in our tooling. Why are you importing Blueprint `.ts` files directly? You shouldn't be recompiling Blueprint; you should only reference the `.js` and `.d.ts` files. The `.ts` files are provided in the package for source mapping purposes.

**Comment by lukasbach** [comment]
Ah you're right, I was importing the wrong file, my bad. I was confused due to the typing and assumed it should build nonetheless, but the compiler setting explains that. Sorry!
