### ISSUE TITLE
custom leftIcon in InputGroup is renderer outside of element

### ISSUE THREAD

**Issue by albemala** [palantir/blueprint#4039]
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: Firefox 75 / macOS 10.14

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/mutable-wave-nuvm8

#### Steps to reproduce

1. Create an InputGroup element
2. Use a custom React element as leftIcon attribute

#### Actual behavior

The leftIcon element is rendered outside of the InputGroup

#### Expected behavior

The leftIcon element should be displayed inside the InputGroup. When using a Blueprintjs icon as a leftIcon element, the icon is correctly displayed inside the InputGroup.

**Comment by giladgray** [comment]
@albemala easy, albeit awkward, fix: 
```diff
 <svg
+  className={Classes.ICON}
```

`InputGroup` relies on absolute positioning for the icon and it's tied to the class constant:
![image](https://user-images.githubusercontent.com/464822/78384834-c1c66800-758f-11ea-8dcb-641aab3d62d6.png)

sorry!

**Comment by albemala** [comment]
Fantastic, thanks @giladgray ! 
The workaround works perfectly 👍

**Comment by justinbhopper** [comment]
@giladgray Perhaps one long-term fix to consider is to use a wrapper element for the left content, much like is already done for the rightElement (the wrapper for the rightElement being `bp3-input-action`).  

Before:
```
.bp3-input-group > .bp3-icon { top: 0; }

<div class="bp3-input-group">
  <span icon="filter" class="bp3-icon bp3-icon-filter"><svg></span>
  <input type="text" class="bp3-input" />
</div>
```

After:
```
.bp3-input-group > .bp3-left-element { top: 0; }

<div class="bp3-input-group">
  <span class="bp3-left-element">
    <span icon="filter" class="bp3-icon bp3-icon-filter"><svg></span>
  </span>
  <input type="text" class="bp3-input" />
</div>
```

This would be a breaking change for anyone currently targeting `.bp3-input-group > .bp3-icon` in their specific code.  If this is undesirable, another option would be to add a new `leftElement` prop to achieve the same effect, and deprecate using `leftIcon` for elements.

**Comment by adidahiya** [comment]
@justinbhopper I think that's a good approach, we should add a new `leftElement` prop to achieve this effect. We can keep `leftIcon` around but mark it as "deprecated" _for custom elements_. Then, in the next major version, just keep the `leftIcon` prop but use the wrapper element for it (for both `string` and `JSX.Element` content).
