### ISSUE TITLE
Can you set min/max Length on inputs?

### ISSUE THREAD

**Issue by Calibrah** [palantir/blueprint#4042]
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: No idea

#### Question

Can you set mix and max Length on an input? for example a password should not be shorter than 8 and thus a pop-up shall appear.

**Comment by adidahiya** [comment]
Not out of the box with Blueprint's `InputGroup`... but you can control the input `value` yourself and enforce any constraints you want that way. Just like any other React `<input>`.
