### ISSUE TITLE
Card component ignores background-color via custom class in conjunction with dark mode

### ISSUE THREAD

**Issue by ChristianIvicevic** [palantir/blueprint#4053]
#### Environment

- __Package version(s)__: 3.24.0

#### Steps to reproduce

Create the following component and corresponding CSS:

```typescript
const Component = () => (
    <div className={Classes.DARK}>
        <Card className="custom-class">
        </Card>
    </div>
);
```

```scss
.custom-class {
    background-color: magenta;
}
```

#### Actual behavior

The background color defined for Card components nested in `bp3-dark` containers takes precedence over custom colors thus the card appears with `background-color: #30404d`.

![image](https://user-images.githubusercontent.com/45569997/78930452-71c23680-7aa4-11ea-8042-5a8a083a73fc.png)

#### Expected behavior

I expected that custom classes take precedence over the dark theme thus `background-color: magenta` being true.

#### Possible solution

It is currently necessary to add `!important` to the `background-color`. However I am not aware whether there is any proper solution to fix the SCSS file to give custom colors precedence.

**Comment by adidahiya** [comment]
> I expected that custom classes take precedence over the dark theme thus background-color: magenta being true.

This is not necessarily true. You are dealing with plain CSS here, so selector specificity rules apply. You must make your CSS __selector__ more specific if you wish to override the styles without using `!important`. For example:

```
.some-other-class .custom-class {
  background-color: magenta;
}
```

This is not unique or specific to Blueprint.

**Comment by ChristianIvicevic** [comment]
Thank you for the quick reply, you were correct and I could resolve this issue with a better selector.
