### ISSUE TITLE
Table column resize too slow

### ISSUE THREAD

**Issue by mvakulich** [palantir/blueprint#4055]
At least in that line the result will be always true, as soon as 
`React.Children.toArray` will produce a new array, and array even with same content will not be equal to the old saved one
https://github.com/palantir/blueprint/blob/2c76d09052a9784691aec43b09c9405a86ec83bd/packages/table/src/table.tsx#L932

**Comment by adidahiya** [comment]
You're right, good catch. In hindsight, that looks like a glaring error in this commit https://github.com/palantir/blueprint/commit/69882d36d1f1c8a0eb83859d714fc80a5ed98a53

This is part of a handful of other table lifecycle problems in `@blueprintjs/table` 3.8.x: https://github.com/palantir/blueprint/milestone/41

For now, I would recommend you downgrade to table 3.7.x

**Comment by DrewDennison** [comment]
Also seeing this super slow column resize for a 39 row x 3 column table of strings. Downgraded to `3.7.1` and that fixed.

**Comment by adidahiya** [comment]
Fixed in table v4.0.0-rc.1
