### ISSUE TITLE
TypeError: props.formatDate is not a function

### ISSUE THREAD

**Issue by abbyghosh** [palantir/blueprint#4059]
#### Environment

- __Package version(s)__: 
"@blueprintjs/core": "^3.24.0",
"@blueprintjs/datetime": "^3.15.2",
- __Browser and OS versions__:
Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Windows 10

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. Use DateInput
1. 
1. 

#### Actual behavior

TypeError: props.formatDate is not a function
getFormattedDateString
C:/Users/newUser/Desktop/src/dateFormat.tsx:70
DateInput.render
C:/Users/newUser/Desktop/src/dateInput.tsx:194

  191 |         _this.lastElementInPopover.addEventListener("blur", _this.handlePopoverBlur);
  192 |     }
  193 | };
> 194 | _this.unregisterPopoverBlurHandler = function () {
      | ^  195 |     if (_this.lastElementInPopover != null) {
  196 |         _this.lastElementInPopover.removeEventListener("blur", _this.handlePopoverBlur);
  197 |     }
#### Expected behavior

No error

**Comment by adidahiya** [comment]
The `DateInput` component requires `formatDate` and `parseDate` props, see [the documentation](https://blueprintjs.com/docs/#datetime/dateinput.date-formatting).

In the future please try to include a code sandbox (linked in the issue template) to demonstrate your issue
