### ISSUE TITLE
[core] Button and InputGroup ref prop types not assignable with React hooks

### ISSUE THREAD

**Issue by tdehollain** [palantir/blueprint#4064]
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: Google Chrome 80.0.3987.149, MacOS 10.14.6

#### Question

What is the correct way of using ElementRef for a Button component?
When I do the following, the `normalButtonRef` is set but the `bpButtonRef` is not.

```javascript
import { Button } from '@blueprintjs/core';

const MyComponent = (props) => {
  const normalButtonRef = React.useRef(null);
  const bpButtonRef = React.useRef(null);
  
React.useEffect(() => {
    console.log(normalButtonRef); // {current: HTMLButtonElement}
    console.log(bpButtonRef); // {current: null}
  }, []);

return (
  <div>
    <button ref={normalButtonRef} />
    <Button elementRef={bpButtonRef} />
  <div>
);
```

<ins>Edit</ins>: typos in example code

**Comment by adidahiya** [comment]
ref handlers sometimes get `null` in React; it's part of the type definition. if you have some behavior you believe is buggy, can you demonstrate it in a code sandbox (linked in the issue template)?

**Comment by tdehollain** [comment]
Thanks. [Here is the code sandbox](https://codesandbox.io/s/blueprint-sandbox-lbs3z).
There is actually a lint message on the elementRef prop that probably points to the issue:
> Type 'MutableRefObject<null>' is not assignable to type '(ref: HTMLElement | null) => any'.

**Comment by johnwiseheart** [comment]
FYI this is an issue with the `inputRef` in `InputGroup`'s as well.

**Comment by adidahiya** [comment]
@johnwiseheart is that with react hooks as well?

**Comment by johnwiseheart** [comment]
Yeah its the same situation where `inputRef` is `(ref: HTMLInputElement | null) => any'` but using `useRef` wants it to take a `MutableRefObject` instead
