### ISSUE TITLE
HTML Table questions

### ISSUE THREAD

**Issue by jibberishclient** [palantir/blueprint#4065]
Is there a way to add pagination, table title, and global filter to the HTML table component? Is there also a way to make it more responsive by adding cell truncation, action overflow menus, and horizontal scrolling?

**Comment by adidahiya** [comment]
No. If you want advanced features like that I would suggest the `@blueprintjs/table` components.

**Comment by jibberishclient** [comment]
@adidahiya Yes but the problem is the table package is more of an excel sheet. I want something like segment's table component with popovers for sorting and overflow menus and icon buttons per row. I don't want row headers either.
