### ISSUE TITLE
Weird separated box shadow on dark theme dialogs

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#4071]
#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#core/components/dialog and open the dialog with dark theme turned on.
2. Look at the weird separated outline of the dialog.

<img width="160" alt="Screen Shot 2020-04-19 at 11 25 56 PM" src="https://user-images.githubusercontent.com/10415101/79720381-4f46cf00-8295-11ea-8d41-658ea49681cd.png">

**Comment by adidahiya** [comment]
I don't see the problem... I think what you're referring to is the docs sidebar, which is visible underneath the dialog backdrop because the backdrop is semi-transparent.

**Comment by tgreen7** [comment]
@adidahiya I was using the docs for a test screenshot because it was easy to access. However, this happens in every dialog throughout our app. It is kinda hard to see but there is a noticeable halo of blurriness around the entire dialog that looks bad.

<img width="631" alt="Screen Shot 2020-04-20 at 10 37 59 PM" src="https://user-images.githubusercontent.com/10415101/79829338-a1502900-8357-11ea-8deb-678e53b99504.png">

<img width="672" alt="Screen Shot 2020-04-20 at 10 38 43 PM" src="https://user-images.githubusercontent.com/10415101/79829362-b4fb8f80-8357-11ea-8fe0-24676d94eada.png">

**Comment by adidahiya** [comment]
That's the CSS box shadow styling on the dialog.
