### ISSUE TITLE
Blueprint HTML Table

### ISSUE THREAD

**Issue by ghost** [palantir/blueprint#4073]
To be clear from the start, I do not want to use @blueprintjs/table because of it's Excel like appearance and features. I want a regular HTML table without row labels or cell selection. However, I was wondering if there was a way to make the HTML table flex based such that it consumes 100% of the available width but the cells divide the space proportionally based on the max width of cells in each column. 

For example:

| Name | Age |
|-------|-------|
| aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa | 32 |
| short | 30|

Because the name column is really long it, more space is allocated for it. However, should the users resize to a smaller screen I would like the text to truncate on a single line. Is there a way to achieve this?

**Comment by adidahiya** [comment]
No, this isn't currently built into Blueprint. I would consider adding a table component based on flex box (perhaps `FlexboxTable`) to the core package as a contribution. Open to proposals

**Comment by jibberishclient** [comment]
In that case, I would suggest more customization with the @blueprintjs/table package. Ideally, it should allow the ability to remove row labels, cell selection, and overflow menus.

**Comment by adidahiya** [comment]
You can remove row labels and overflow menus already. Use `enableRowHeader={false}` and don't use `TruncatedFormat`/`JSONFormat` (these components add the cell overflow menus).

**Comment by jibberishclient** [comment]
Hmmmm I'm not seeing the overflow menus in tables in the docs. Also is there a way to consume the entire horizontal space?

**Comment by jibberishclient** [comment]
![image](https://user-images.githubusercontent.com/11995299/79795626-39cbb680-8322-11ea-8b2f-afe2c5666b56.png)

So do I add a per row menu like so with enough padding to accommodate? Styling with padding only seems to break it. I'd also like just this column to not be resizable.

**Comment by adidahiya** [comment]
I don't understand the request clearly -- do you want overflow menus? Or do you want to remove them? What does an "overflow menu" mean to you?

**Comment by jibberishclient** [comment]
Basically I want to have a popover with actions like update and delete which will redirect the user to some custom forms. However, it doesn't appear that you can do so without cutting off the button as seen in the image. I was hoping there was some built in functionality but I'm not seeing it in the docs.

**Comment by adidahiya** [comment]
You can provide a custom cell renderer to `<Column>` where you render your custom Popover with cell actions.

**Comment by jibberishclient** [comment]
That's exactly what I did in the image. However, as you saw it cuts off the button. Furthermore, any attempt to add padding to the cell only screws things up.

**Comment by adidahiya** [comment]
> any attempt to add padding to the cell only screws things up.

I think you can work around this with custom CSS which overrides blueprint's `table.css`. If you're running into problems with this, the best way to get support would be by posting a code sandbox repro'ing your issue.

**Comment by jibberishclient** [comment]
Is there a way to actually get this truncation to work, also is there a way to vertically center the cell content?

https://codesandbox.io/s/tender-mountain-grfmv?file=/src/App.js
