### ISSUE TITLE
add `wrap` property to `Collapse`

### ISSUE THREAD

**Issue by zafarella** [palantir/blueprint#4076]
#### Environment

- __Package version(s)__: 3.25.0 
- __Browser and OS versions__: 

#### Feature request

Would be nice to have the collapse element the wrap option so that the long text could be wrapped to fit width of the component. Demo of component https://blueprintjs.com/docs/#core/components/collapse

#### Examples

wrapContent | boolean Whether the component should wrap the text.
-- | --

**Comment by adidahiya** [comment]
Not sure what you mean; this sounds like something you could easily achieve with CSS? It depends on what's inside the Collapse...

**Comment by zafarella** [comment]
thanks for response. Solved with this snip:
```javascipt
<Collapse isOpen={!this.state.showLambdaPayload}>
                            <Pre wrap={"true"}>
                                {this.state.userLambdaPayload}
                            </Pre>
</Collapse>
