### ISSUE TITLE
Popover Inline Smart Arrow Positioning Places Wrong Position

### ISSUE THREAD

**Issue by jchomicki** [palantir/blueprint#408]
### Bug report

- __Package version(s)__: 1.4.0
- __Browser and OS versions__: Firefox 50.0.2, Chrome  55.0.2883.95 (64-bit), OSX El Capitan 10.11.6

#### Steps to reproduce

1. Go to: http://blueprintjs.com/docs/#components.popover
1. Make Popover Inline, with Smart Arrow Positioning, and a Position of Bottom-Right (or Top-Right)
1. Change the width of the element to 30px (can be seen in anything <70px)
1. Click button to open popover

#### Actual behavior

Popover position does not correctly center on the button until the element is >=70px when Popover is inline, using smart arrow positioning, with a bottom-right (or top-right) location

![2017-01-04_10-50-50](https://cloud.githubusercontent.com/assets/5685907/21654967/b6bfc0e2-d26c-11e6-8218-45a54751fb60.png)

#### Expected behavior

Smart arrow positioning correctly centers the arrow when inline is set and the position is bottom-right or top-right

**Comment by jchomicki** [comment]
Ah yes, I mistyped, my bad.

**Comment by llorca** [comment]
Hmm, is this a bug? If your target gets really small, the arrow may not have enough room to center properly. The smart popover positioning solves this by offsetting the popover as necessary, instead of always trying to align the edge of the popover with the target
