### ISSUE TITLE
Overlay with portal not taking any vertical space

### ISSUE THREAD

**Issue by JuanIrache** [palantir/blueprint#4086]
#### Environment

- __Package version(s)__: 3.25.0
- __Browser and OS versions__: Electron 8.2.3 (Chromium), Windows 10

#### Question

Hi, I'm new to this toolkit. It looks great.

If this is not the right place to ask, my apologies. Could someone point me to the right place? I am having some problems sizing/positioning an overlay.

```
<Overlay isOpen={isOpen}>
    My content
</Overlay>
```

If I leave it like that, the portal is attached to the body and takes 0 pixels vertically, so I have worked around this by assigning it a classname and forcing it to take the full screen:

```
<Overlay isOpen={isOpen} portalClassName="force-bottom">
    My content
</Overlay>
```
and

```
.force-bottom {
  bottom: 0;
}
```
Also, the contents appear behind the backdrop, so I had to bring them forward by giving them a high z-index in CSS. I also applied a backdropClassName to change the backdrop color to white.

This gets my problems solved, but it seems too hacky. What would be the official way of solving these problems?

Thanks

**Comment by adidahiya** [comment]
With layout/positioning issues like this it's best to provide a code sandbox (linked in the issue template) showing a minimal repro of your setup. What are you trying to do with Overlay? Are you sure you don't want a Dialog instead? What's the larger context here?

**Comment by JuanIrache** [comment]
Thanks @adidahiya . I've been trying to reproduce the issue in a minimal setup, but it only shows up in my more complex project, so it must be somewhere in my own CSS.

Regarding Overlay vs Dialog, the description in the documentation of Overlay fits better what I'm trying to achieve. I just experimented with Dialog and it creates additional elements I don't need, like a solid background.

I will close this.

**Comment by adidahiya** [comment]
It looks like Overlay clones its child element and applies a class to it, so if you supply a custom component, you will have to support the `className` prop accordingly and render out `props.className` to the DOM. This was a tradeoff made in https://github.com/palantir/blueprint/pull/2205 to reduce the amount of DOM nesting in the component. I can see it being a little confusing, but at this point it is something you can work around and is probably not worth the breaking change in DOM layout.

**Comment by adidahiya** [comment]
The relevant code is here: https://github.com/palantir/blueprint/blob/2bee55fb38204ccd0e51e21fe881f7294ad8a0f6/packages/core/src/components/overlay/overlay.tsx#L312

**Comment by JuanIrache** [comment]
All good. Just reopened in case this was not under control. Thank you
