### ISSUE TITLE
Add new group inheritance icons

### ISSUE THREAD

**Issue by sonovawolf** [palantir/blueprint#4089]
![image](https://user-images.githubusercontent.com/3002490/80154004-89ed8780-8573-11ea-861b-102a713b56c8.png)
[pt-icon-inherited-group.zip](https://github.com/palantir/blueprint/files/4525562/pt-icon-inherited-group.zip)

**Comment by adidahiya** [comment]
would you mind sending a PR? you don't have to update the icon font, just add the files and edit `icons.json`, for example: https://github.com/palantir/blueprint/pull/4050/commits/13351e021bcdb94a1d34cbdebe86f6e6543185df

**Comment by kaatherine** [comment]
I will open a PR! :)

**Comment by kaatherine** [comment]
PR is up [here](https://github.com/palantir/blueprint/pull/4097)

**Comment by adidahiya** [comment]
fixed by #4097
