### ISSUE TITLE
The input area of InputGroup component is transparent when it's a dark theme

### ISSUE THREAD

**Issue by wisdomG** [palantir/blueprint#4090]
#### Environment

The version of @blueprintjs/core I'm using is 3.23.1. I repeat this problem in official document.

#### Steps to reproduce

Just change the theme to 'bp3-dark', compare with the light theme, someone will see it.

#### Actual behavior

As shown in pictures. The color of input area is white in 'bp3-light' theme even if I change the background color to red. However, when I change to theme to dark, the input area becomes transparnet.

![image](https://user-images.githubusercontent.com/11959301/80179722-b79a0580-8633-11ea-9f6a-8833ed33f0a7.png)

![image](https://user-images.githubusercontent.com/11959301/80179726-ba94f600-8633-11ea-9787-53a71c9ad9f3.png)

#### Expected behavior

The expected behavior I think is that the color of input area shoule be similar to the theme color.

**Comment by adidahiya** [comment]
This is by design so that the input can sit on top of different shades of dark backgrounds in the dark theme. A red background like that is not expected in our design system, do you have a more representative use cases or a non-contrived design example of what you're trying to achieve?

**Comment by wisdomG** [comment]
My case is look like this. I have a map as the background. Users may be disturbed by the elements on map if the input area is transparent in dark theme, but it seems OK in light theme. I just think this phenomenon my confuse users.

Anyway, I could still change the css manually to meet my requirement even if it's by design. 

![image](https://user-images.githubusercontent.com/11959301/80295510-bee12080-87a5-11ea-944d-c483d821086c.png)

![image](https://user-images.githubusercontent.com/11959301/80295508-bbe63000-87a5-11ea-9b84-acb41619bc35.png)

**Comment by adidahiya** [comment]
In your case I would suggest adding a solid or semi-solid background container element behind the input elements. This will also help reduce visual noise.
