### ISSUE TITLE
Add a ref handler for the Card component returning the div element backing this component

### ISSUE THREAD

**Issue by ChristianIvicevic** [palantir/blueprint#4091]
#### Environment

- __Package version(s)__: 3.25.0

#### Feature request

In our application we have the use-case that we wanted to use an interactive card with an injected `onClick` that has further buttons as its children (with their own `onClick` handlers) that cause something else to happen when clicked. Therefore we wanted to hook into the `onClick` event and figure out whether the button itself was clicked rather than the card. In order to do so we attempted to pass a ref to the `Card` component which doesn't pass it further to the backing div container.

Therefore we propose adding a `divRef` prop similar to the `ulRef` prop for the `Menu` component so that we actually get access to the underlying div container.

#### Examples

```tsx
const CardWithButtons = ({ buttons, onClick }: /* ... */) => {
    const ref = useRef(null);
    return (
        <Card interactive elevation={2} ref={ref} onClick={(e) => {
            if (e.target === ref.current) {
                onClick();
            }
        }}>
            {/* render some content and buttons */}
            {buttons}
        </Card>
    );
};
```

**Comment by adidahiya** [comment]
> Therefore we wanted to hook into the onClick event and figure out whether the button itself was clicked rather than the card.

Can you accomplish the same thing using `event.target`, `event.target`, and checking against the `Classes.CARD` selector instead?

**Comment by ChristianIvicevic** [comment]
If I remember correctly, `event.target` was set to the button component but maybe we could check for the absence of the `Classes.CARD` selector to deduce it's actually something other than the card that invoked the click event. We'll be able to try that out on Monday.
