### ISSUE TITLE
16px inherited-group icon SVG is broken

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4102]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/723999/80562363-81eb7880-89b5-11ea-98d5-186d99e279a0.png">

@sonovawolf @kaatherine

**Comment by kaatherine** [comment]
filed a fix [here](https://github.com/palantir/blueprint/pull/4104)

**Comment by adidahiya** [comment]
fixed by #4104
