### ISSUE TITLE
Tri-state: checkboxes

### ISSUE THREAD

**Issue by rasgo-cc** [palantir/blueprint#4106]
Any chance we can get tri-state checkboxes with state rotating between: unselected, indeterminate, true, false?

**Comment by adidahiya** [comment]
This is supported... just like `<input type="checkbox">`:

<img width="226" alt="image" src="https://user-images.githubusercontent.com/723999/80735430-ab53f380-8ade-11ea-8068-d3c5c476de41.png">

[docs here](https://blueprintjs.com/docs/#core/components/checkbox)
