### ISSUE TITLE
Remove custom configuration of scss stylelint rules

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#411]
In particular, `max-line-length` and `at-extend-no-missing-placeholder`. This project isn't really special enough to skip those rules. We should either fix the violations or update `stylelint-config-palantir` to reflect how we really write code.

https://github.com/palantir/blueprint/blob/31476f995399b76d5216ed63ec5c172dd3b6bce7/.stylelintrc#L9

**Comment by giladgray** [comment]
what's wrong with max line length?

**Comment by adidahiya** [comment]
Why do we need a custom line length limit? We should just use whatever is prescribed in stylelint-config-palantir.

**Comment by giladgray** [comment]
the line length affects _every single scss file_

**Comment by giladgray** [comment]
ok so 100-character lines are pretty reasonable even for the docs comments, but there are a few cases where longer lines are unavoidable (such as extremely long URLs) and it's cumbersome to disable stylelint for a block comment.

we could leverage the new `ignore: ["comments"]` option to allow our comments to be longer? http://stylelint.io/user-guide/rules/max-line-length/
