### ISSUE TITLE
Theme option/tools already exists?

### ISSUE THREAD

**Issue by thierryc** [palantir/blueprint#4111]
#### Question

Theme option/tools already exists?
Do you have a theme example?

If it is not, I would like to create one.

- design tokens driven.
- easy to test. 
- cli tool
- online tools

TIA for your help

**Comment by adidahiya** [comment]
Blueprint does not support custom themes out of the box; it ships with a light and dark theme for all its components. If you wish to customize blueprint you can do that by compiling its Sass source files: https://github.com/palantir/blueprint/issues/123
