### ISSUE TITLE
Feature Request: Allow custom CSS background before and after handles on MultiSlider

### ISSUE THREAD

**Issue by bergkvist** [palantir/blueprint#4116]
### Environment
@blueprintjs/core: 3.26.1

## Feature request

![image](https://user-images.githubusercontent.com/410028/81594045-9cafeb00-93c0-11ea-8313-404220b837fb.png)
---
![image](https://user-images.githubusercontent.com/410028/81594089-aafe0700-93c0-11ea-8d46-c2bd61b54524.png)
---

Right now, there are only a few options for background color on the MultiSlider component (between handles). It would be nice to have more control over this through `backgroundBefore` and `backgroundAfter` props on the handles. This could allow for gradients or even custom images as backgrounds. See the images above.

Personally, my motivation for wanting this is to use sliders for adjusting thresholds/color scales dynamically. And for this to be as intuitive as possible - the background of the slider could be used to visualize the color scale.

#### Examples
```tsx
import React, { useState } from 'react'
import { MultiSlider } from '@blueprintjs/core'
import '@blueprintjs/core/lib/css/blueprint.css'

export function App() {
  const [start, setStart] = useState(25)
  const [end, setEnd] = useState(75)

  return (
    <MultiSlider min={0} max={100} stepSize={1} labelStepSize={20}>
      <MultiSlider.Handle
        value={start}
        onChange={setStart}
        type="start"
        backgroundBefore='rgb(0,255,0)'
        // A gradient background that changes from green, to yellow, to red.
        backgroundAfter='linear-gradient(to left, rgb(0,255,0),rgb(255,255,0),rgb(255,0,0))'
      />
      <MultiSlider.Handle
        value={end}
        onChange={setEnd}
        type="end"
        backgroundAfter='rgb(255,0,0)'
      />
    </MultiSlider>
  )
}
```

#### Userland implementation (warning: very hacky)
```tsx
// MultiSlider.tsx
import { SFC } from 'react'
import { MultiSlider as BlueprintMultiSlider } from '@blueprintjs/core/lib/esm/components/slider/multiSlider'
import { IHandleProps } from '@blueprintjs/core/lib/esm/components/slider/handleProps'
import { DISPLAYNAME_PREFIX } from '@blueprintjs/core/lib/esm/common/props'
import '@blueprintjs/core/lib/css/blueprint.css'

type ICustomHandleProps = IHandleProps & {
  backgroundBefore?: string
  backgroundAfter?: string
}
const MultiSliderHandle: SFC<ICustomHandleProps> = () => null
MultiSliderHandle.displayName = `${DISPLAYNAME_PREFIX}.MultiSliderHandle`

//@ts-ignore - Overriding a private method (renderTrackFill) to allow a custom background
export class MultiSlider extends BlueprintMultiSlider {
  public static Handle = MultiSliderHandle

  private renderTrackFill(
    index: number,
    start: ICustomHandleProps,
    end: ICustomHandleProps
  ) {
    //@ts-ignore - Accessing a private method
    const trackFill = super.renderTrackFill(index, start, end)
    if (start.backgroundAfter !== undefined) {
      trackFill.props.style.background = start.backgroundAfter
    } else if (end.backgroundBefore !== undefined) {
      trackFill.props.style.background = end.backgroundBefore
    }
    return trackFill
  }
}

```

**Comment by adidahiya** [comment]
I think this request makes sense, but I would implement it slightly differently... we don't suggest supplying CSS directly as props in any other part of the public API, instead we use CSS class names. So I think this should work the same, with a new prop on Handle:

```
trackClassAfter?: string;
```

do you strictly need the "before" prop? I think you could make do with just "after", like the current `intentAfter` prop

**Comment by bergkvist** [comment]
There is both `intentBefore` as well as `intentAfter` as props to the handle, so I kind of modeled this after that.

The advantage of inlining the css like this is that it allows for making the style reactive. I can create the background dynamically. Doing this with class names creates a level of indirection, and sort of limits the background to be defined in a categorical way. (since class names are categorical)

Of course most of the time, people would probably want static backgrounds - in which case class names might be more comfortable to work with.

**Comment by bergkvist** [comment]
What about providing `trackClass(Before|After)`, as well as `trackStyle(Before|After)`?

**Comment by adidahiya** [comment]
Ok I see your point about dynamic styling. I would accept a PR for `trackStyleBefore` and `trackStyleAfter` props. They would have to merge with the dynamic style object we are already rendering in `multiSlider.tsx`.
