### ISSUE TITLE
Mobile App Example

### ISSUE THREAD

**Issue by fredfortier** [palantir/blueprint#4125]
I'm working on a mobile web version of my app built with Blueprint. Most of the pieces seem to be there, including the panel stack. Is there a sample mobile app anywhere that I could use as a starting point?

**Comment by adidahiya** [comment]
No, we don't have an official example of this kind. Reminder that Blueprint is desktop focused UI toolkit: https://github.com/palantir/blueprint/blob/a98ac28dc5079a728fa40d8c4d31faa98b569001/README.md#L7

**Comment by fredfortier** [comment]
Any recommendation for a mobile-first React toolkit with a TypeScript code base?

**Comment by dmackerman** [comment]
@fredfortier Check out Ionic?
