### ISSUE TITLE
Suggest dropdown does not open when inputRef is set to ref hook

### ISSUE THREAD

**Issue by tdehollain** [palantir/blueprint#4138]
#### Environment

- __Package version(s)__: ~Core@3.27.0, Suggest@3.13.0~ core@3.28.0, select 3.13.1
- __Browser and OS versions__: Google Chrome 81.0.4044.129, MacOS 10.14.6

[Repro code sandbox](https://codesandbox.io/s/blueprint-sandbox-9qvk3?file=/src/SuggestExample.tsx)

#### Steps to reproduce

1. Click on the Suggest --> App crashes with error `core_1.Utils.getRef is not a function`
1. Change @blueprintjs/core version from 3.27.0 to 3.26.1 --> works

**Comment by adidahiya** [comment]
Your code sandbox works for me if I upgrade the other packages, datetime and icons:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/723999/82465878-c1295880-9a8d-11ea-9704-8c29fa29d0df.png">

Can you check if you have multiple versions of core getting installed?

**Comment by tdehollain** [comment]
Indeed. I came to this while trying to reproduce a separate issue: when adding an inputRef prop to the Suggest component, the popover no longer shows when clicking on the input.
Should I edit the original post or create a new issue?

**Comment by adidahiya** [comment]
Maybe code sandbox is doing something weird where it doesn't respect dependency version ranges? select 3.13.0 explicitly depends on core 3.27.0, where `Utils.getRef` was introduced:

https://github.com/palantir/blueprint/blob/d08244b8b89b5acc1e4844230fbe01434ec39e8d/packages/select/package.json#L38

any chance you could share a more realistic repro of the issue outside of the sandbox?

**Comment by adidahiya** [comment]
> when adding an inputRef prop to the Suggest component, the popover no longer shows when clicking on the input.

I'll look into this right now; I just made some changes to that code so I'll make sure it works before I release today.

**Comment by adidahiya** [comment]
Adding an inputRef to Suggest works fine for me on the latest develop branch. keep an eye out for a release today

**Comment by tdehollain** [comment]
Thanks. Seems like the bug is still present though, both on my local env and on codesandbox (updated the packages to yesterday's release).
I noticed that on Firefox the popover doesn't show at all but on Chrome it appears and disappears within like 0.1s.

**Comment by adidahiya** [comment]
Ok, I can repro the new problem in code sandbox with the latest packages: https://codesandbox.io/s/blueprint-sandbox-9w34k

The bug occurs with `React.useRef`, not with a callback ref. Latest [docs site](https://blueprintjs.com/docs/#select/suggest) works fine.

**Comment by adidahiya** [comment]
I'm not sure what's happening here, but I can definitely repro the issue with the new feature added in [select 3.13.0](https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjsselect-3130). Callback refs still work, so it's not a regression. Maybe @tanmoyopenroot (who submitted #4093) can take a look?

**Comment by tanmoyopenroot** [comment]
> I'm not sure what's happening here, but I can definitely repro the issue with the new feature added in [select 3.13.0](https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjsselect-3130). Callback refs still work, so it's not a regression. Maybe @tanmoyopenroot (who submitted #4093) can take a look?
> 

I am looking into it.
