### ISSUE TITLE
Blueprint Cells Table does not correctly refresh

### ISSUE THREAD

**Issue by eleveurdechevres** [palantir/blueprint#4139]
#### Environment

- __Package version(s)__: table 3.8.6
- __Browser and OS versions__: Linux RedHat 7.8

https://blueprintjs.com/docs/#table/features.table-loading-states

#### Steps to reproduce

1. Check "cells"
2. Uncheck "cells"
3. Check "cells"
...

#### Actual behavior

Cells do not refresh at each time. If you scroll down with mouse, the cells will refresh

#### Expected behavior

CellRenderer should do its job each time a props is modified inside the renderer

#### Possible solution

Don't know but i think it can be the same cause as issue 3846

**Comment by adidahiya** [comment]
Essentially the same as #3774 and other issues in that milestone. For now I recommend downgrading to table 3.7

**Comment by Dessix** [comment]
Downgrading to 3.7 now produces lifecycle warnings on stable react. Is this still the recommended solution?
