### ISSUE TITLE
How can I use Suggest / QueryList on a TextArea to emulate a "Mention" like system

### ISSUE THREAD

**Issue by LouizFC** [palantir/blueprint#4144]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "3.27.0" and "@blueprintjs/select": "3.13.0",

#### Question

I found Blueprint recently and I am quite astonished how I haven't found it earlier. It is quite complete and very robust.

I am about to use Blueprint for a new project.

For my use case, I need a "Mention" system, like https://ant.design/components/mentions/ does with textarea.

I found the [QueryList](https://blueprintjs.com/docs/#select/query-list) component, but I found no example of how to use it.

My question is: **is there any example available? I could not find something similar in previous issues. To the library authors: the components can be used for my use case? if yes, could you please give me some hints?**

I have looked at MultiSelect implementation and I found quite smart that it uses a invisible input at the end of the tag list, I tried an earlier prototype using a content-editable with a similar concept but had no luck.

Maybe I could potentially contribute the resulting component to the library, but since it is just a side project I don't know if I can make it "robust" enough for the library standards

**Comment by adidahiya** [comment]
Yes, it should be possible to use QueryList to build a "mention" input component. In addition to MultiSelect you might want to look at the [Suggest](https://github.com/palantir/blueprint/blob/ac0658a385c74faad95b19c889d03bbd17ef8048/packages/select/src/components/select/suggest.tsx) component implementation. All the "examples" we have for QueryList are the other components in the `@blueprintjs/select` package.

Alternatively, it should also be possible to use a library like [react-mentions](https://github.com/signavio/react-mentions) and add Blueprint input and menu styling to it.

**Comment by LouizFC** [comment]
Right. I got a prototype working. If it gets more mature, I will try to contribute it to the project. Thank you very much.

**Comment by tgreen7** [comment]
@LouizFC I know this has been a while but I am curious if you continued down this path. We are using react-mentions and it has many issues playing with redux-form.
