### ISSUE TITLE
[core] button, form control, search input focus styling changed in Chrome 83

### ISSUE THREAD

**Issue by wisdomG** [palantir/blueprint#4156]
#### Environment

- __Package version(s)__: 3.28.0
- __Operating System__: Ubuntu 16.04
- __Browser name and version__: Chrome 83.0.4103.61

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-uk6kk?file=/src/index.tsx

#### Actual behavior

This just happened after I upgrade Chrome from version 81 to version 83.

As you will see in the sandbox, there is a white border shown after you click on it. 

![image](https://user-images.githubusercontent.com/11959301/82986960-5fd32d80-a029-11ea-8f54-cb5daad28e5e.png)

#### Possible solution

I have no idea.

I am wondering if you have the same issue on Chrome with version 83.

**Comment by adidahiya** [comment]
it looks like Chrome updated default form element styling in v83:

- https://developers.google.com/web/updates/2020/05/nic83#forms
- https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

and the new user agent styling can be overridden with the `:focus-visible` pseudo element: https://web.dev/style-focus/#use-:focus-visible-to-selectively-show-a-focus-indicator

**Comment by adidahiya** [comment]
relatedly, styling of the "clear" button on search inputs has changed with Chrome 83:

![image](https://user-images.githubusercontent.com/723999/83430563-df834280-a403-11ea-9952-83865be14d68.png)

(h/t @moorerc, thanks for reporting)

**Comment by adidahiya** [comment]
I downloaded an old version of Chromium to take a closer look at this. The change affects a few components:

- Button
- Form controls (Checkbox, Switch, HTMLSelect)
- Search inputs

Screenshots below, design analysis forthcoming

## Chrome 83

<img width="184" alt="image" src="https://user-images.githubusercontent.com/723999/83645427-796ffa00-a580-11ea-9df0-e2caf3bf1a4e.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/723999/83645441-7f65db00-a580-11ea-983d-b3faa7fa2149.png">

<img width="111" alt="image" src="https://user-images.githubusercontent.com/723999/83645573-a45a4e00-a580-11ea-9c8c-115dfbd69722.png"> <img width="105" alt="image" src="https://user-images.githubusercontent.com/723999/83646445-a40e8280-a581-11ea-93ea-db363476c0b7.png">

<img width="121" alt="image" src="https://user-images.githubusercontent.com/723999/83645601-aae8c580-a580-11ea-8c7e-3a5621655bc0.png"> <img width="109" alt="image" src="https://user-images.githubusercontent.com/723999/83646472-acff5400-a581-11ea-9277-0f6a3762f108.png">

![2020-06-03 10 07 21](https://user-images.githubusercontent.com/723999/83646827-3020aa00-a582-11ea-87ee-6d7dd6724975.gif)
![2020-06-03 10 07 32](https://user-images.githubusercontent.com/723999/83646837-31ea6d80-a582-11ea-8526-3e4ef5d37491.gif)


![2020-06-03 09 59 57](https://user-images.githubusercontent.com/723999/83645938-0a46d580-a581-11ea-954b-ae026d6cc77e.gif)
![2020-06-03 10 00 08](https://user-images.githubusercontent.com/723999/83645943-0c109900-a581-11ea-90a3-cdff18ad57cc.gif)

<img width="401" alt="image" src="https://user-images.githubusercontent.com/723999/83646254-69a4e580-a581-11ea-97b3-307c17f6f406.png">



## Chrome 81

<img width="187" alt="image" src="https://user-images.githubusercontent.com/723999/83645709-cb188480-a580-11ea-914d-284c5e111f68.png">
<img width="178" alt="image" src="https://user-images.githubusercontent.com/723999/83645728-cf44a200-a580-11ea-871f-f11368fb2876.png">

<img width="109" alt="image" src="https://user-images.githubusercontent.com/723999/83645757-d8ce0a00-a580-11ea-943a-9ecc22a56fcd.png"> <img width="101" alt="image" src="https://user-images.githubusercontent.com/723999/83646602-dcae5c00-a581-11ea-9232-389208982067.png">
<img width="103" alt="image" src="https://user-images.githubusercontent.com/723999/83645787-de2b5480-a580-11ea-85a8-bd799a70afe7.png"> <img width="109" alt="image" src="https://user-images.githubusercontent.com/723999/83646622-e46e0080-a581-11ea-94f9-009f7b80f1b4.png">

![2020-06-03 10 07 50](https://user-images.githubusercontent.com/723999/83646882-3e6ec600-a582-11ea-9284-338e043ee268.gif)
![2020-06-03 10 08 00](https://user-images.githubusercontent.com/723999/83646889-40388980-a582-11ea-84a4-cdc82e03a532.gif)


![2020-06-03 10 01 12](https://user-images.githubusercontent.com/723999/83646084-35c9c000-a581-11ea-8968-8d8e07a30568.gif)
![2020-06-03 10 01 25](https://user-images.githubusercontent.com/723999/83646091-37938380-a581-11ea-8e5f-3d92ff0309bd.gif)

<img width="405" alt="image" src="https://user-images.githubusercontent.com/723999/83646265-6dd10300-a581-11ea-9a50-39b5759f6429.png">

**Comment by adidahiya** [comment]
There doesn't seem to be a lot I can do about this visual change, as my efforts to style `:focus-visible haven't worked. If anyone has a working example of custom `:focus-visible` styling for the focus ring please share it.

I actually think the new focus rings look better, especially in the dark theme, where there is much better (accessible) contrast with the background. I'm sure the old focus rings wouldn't pass WCAG 2.0 standards. So I'm inclined to keep the new styling. The one thing we might want to reconsider is the style for checkboxes in light theme, it's pretty subtle:

![2020-06-03 10 07 21](https://user-images.githubusercontent.com/723999/83646827-3020aa00-a582-11ea-87ee-6d7dd6724975.gif)

Regarding the search input "clear" icon change. I also don't see a way to add custom styles there, but I don't think the new visuals are a regression. The cross works just as well as the old icon. Note that Firefox doesn't even have a "clear" button / icon in that location.

**Comment by jay-jlm** [comment]
For someone looking for a quick hack to fix this, the following code seems to work for me, for mouse clicks as well as tab navigation.
Note: I did not try to make the style 100% like the original, just close enough:

`
.App button:focus { 
  outline: none;
  border: 2px solid #137CBD;
}
`

**Comment by wisdomG** [comment]
@adidahiya Sorry to ask again. Are you plan to solve this problem ? We still think these rings looks wired especially in the dark theme.
![image](https://user-images.githubusercontent.com/11959301/94100795-0527d200-fe61-11ea-9071-e02171dcc738.png)

**Comment by adidahiya** [comment]
@wisdomG how did you create that example? Note that this is not a regression; the old focus styles did sometimes have issues of z-index ordering of the focus rings too:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/723999/94462263-3f5ae180-0189-11eb-81b4-d14ed3fc8545.png">

And, like I said:

> I actually think the new focus rings look better, especially in the dark theme, where there is much better (accessible) contrast with the background. I'm sure the old focus rings wouldn't pass WCAG 2.0 standards.

**Comment by wisdomG** [comment]
@adidahiya The example is here.
https://codesandbox.io/s/blueprint-sandbox-forked-8dx9o?file=/src/CoreExample.tsx
The example is runing on Chrome 85
![image](https://user-images.githubusercontent.com/11959301/94537788-cc7b6480-0275-11eb-90fd-3eac09735a19.png)

**Comment by dlech** [comment]
I solved this issue with the following:

```scss
.#{$ns}-control input:focus:not(:focus-visible) ~ .#{$ns}-control-indicator,
.#{$ns}-button:focus:not(:focus-visible) {
    outline: none;
}
```
