### ISSUE TITLE
DateRangeInput behaves strangely

### ISSUE THREAD

**Issue by jiripudil** [palantir/blueprint#4169]
Hi there, first of all, I am sorry for opening a single issue for multiple bugs — originally this was going to be about `DateRangeInput` giving us false positive "Overlapping dates" warnings, but while trying to reproduce the bug, I've stumbled upon a few more. Feel free to split the issue.

#### Environment

- __Package version(s)__:
    @blueprintjs/core 3.28.0
    @blueprintjs/datetime 3.18.0
- __Operating System__: macOS 10.13.6
- __Browser name and version__: Chrome 83.0.4103.61

#### Code Sandbox

https://blueprintjs.com/docs/#datetime/daterangeinput

#### Steps to reproduce & actual behavior

![daterangeinput-bugs](https://user-images.githubusercontent.com/1042159/84015333-f84ba500-a97b-11ea-82ec-b397af62a3e6.gif)

As you can see, I've encountered several issues:

1. The popover jumps forward by an increasing number of months when opened and changed repeatedly.
1. I admit I've done some frantic <kbd>Tab</kbd>bing and <kbd>Shift</kbd>+<kbd>Tab</kbd>bing there, but eventually in some constellation, the input gave me a false positive "Overlapping dates" warning for what seems to be the same date, judging by the badges below the input.
1. By the end I've even managed to break the input to the point it gave me an "Invalid date" warning for a date I've selected from the calendar.

#### Expected behavior

No jumping back and forth through the calendar, no false positive "overlapping dates", and no false positive "invalid date"s.

**Comment by adidahiya** [comment]
Can you please split the issue into multiple issues, with more specific repro steps? In addition to a gif I would appreciate a list of steps. Also it helps to have a code sandbox with your exact configured settings so that I can jump into it and debug quickly.
