### ISSUE TITLE
Sketch files

### ISSUE THREAD

**Issue by NickyYo** [palantir/blueprint#417]
Hi, do we have available Sketch files for the components please?

**Comment by giladgray** [comment]
Hi @NickyYo,

@llorca maintains our Sketch file for the components (where it all began, of course) so I'll defer to him when he's back in the office next week on if/when/how we'll publish it.

**Comment by nativerez** [comment]
Hello, I'd also really appreciate this for a project I'm working on. Would help ensure the mockups are not deviating from the components available to the devs.
Thanks

**Comment by llorca** [comment]
Yeah I definitely want to publish the files. I was actually blocked on a few items. Does anybody know how to use the San Francisco font in Sketch?

**Comment by sadokx** [comment]
I created this Sketch kit with every major component and style used in BlueprintJS for a project that I'm working on. It's not nearly as polished as it can be, but hopefully it's useful to someone. It uses San Francisco. (SF UI Text/Display).

[BlueprintJS-Kit.sketch.zip](https://github.com/palantir/blueprint/files/694261/BlueprintJS-Kit.sketch.zip)

**Comment by llorca** [comment]
@sadokx very cool! How did you SF UI Text/Display with Sketch? It doesn't appear in the "Typeface" dropdown:
![image](https://cloud.githubusercontent.com/assets/199754/21777484/ed082c58-d653-11e6-882d-fc374ce15dee.png)

**Comment by sadokx** [comment]
@llorca Thanks! So, even if macOS uses SF UI Text/Display through out the entire system, you can't really 'use' it for anything. You need to download the font pack from the Apple Developer website.
Attached here for your convenience.
[SFUI-1.zip](https://github.com/palantir/blueprint/files/694376/SFUI-1.zip)

**Comment by llorca** [comment]
Oh, that's good to know. Thanks for the fonts! I'm looking forward to sharing the master Sketch file in the next week or so. FYI, it matches the code almost 1:1 and includes dark theme! 🎉

**Comment by sandys** [comment]
@llorca  any hope you could attach the first version in the bug here ?

**Comment by llorca** [comment]
@sandys It'll most likely be hosted on GitHub pages with a section in the [docs](http://blueprintjs.com/docs/) linking to it. It's almost ready, I'll ping this thread once it's released

**Comment by andrictham** [comment]
@llorca Any word on this yet? We’re starting a project with Blueprint and the Sketch file would be a massive help

**Comment by llorca** [comment]
@andrictham Putting the final touches on the Sketch file, also building the page it will be hosted at. Should ship this week!

**Comment by llorca** [comment]
@NickyYo @nativerez @sadokx @andrictham @sandys Sketch assets are now in the repo, and the page will be live tomorrow when we ship 1.7.0. Enjoy 🎉

**Comment by nativerez** [comment]
So awesome, thanks so much! Keep up the good work.

**Comment by andrictham** [comment]
@llorca Thank you! 🙌  Got a question, every time I open the Sketch file, it asks for DIN and Blender fonts, not sure why that’s the case

**Comment by llorca** [comment]
@andrictham I probably left a text layer with DIN or Blender, are you able to locate which one?

**Comment by andrictham** [comment]
@llorca Wasn’t able to, unfortunately.

**Comment by visioncan** [comment]
I use this plugin [FontFinder](https://github.com/ukn530/FontFinder) to find out the missing font:

Blender font using in Dialog Header (Light theme) and day's text in Calendar(Dark theme).
DIN font using in many many layers...

**Comment by llorca** [comment]
Thanks, I used the plugin to find old hidden layers with older fonts. Today's update will fix it 👍
