### ISSUE TITLE
Button onClick is triggered twice from the keyboard

### ISSUE THREAD

**Issue by amin3141** [palantir/blueprint#4170]
#### Environment

- __Package version(s)__: 
- __Operating System__: Ubuntu 20.04 LTS
- __Browser name and version__: 77.0.1+build1-0ubuntu0.20.04.1 and 77.0.1 (64-bit) (windows)

#### Code Sandbox

[Link to a minimal repro](https://codesandbox.io/s/blueprint-sandbox-f968c?file=/src/index.tsx)

#### Steps to reproduce

1. Tab onto the button and hit the spacebar.

#### Actual behavior

The word 'hello' prints to the console twice.

#### Expected behavior

The word 'hello' should only print once. This is the correct behavior, which happens on chromium based browsers, and also when mouse clicking on Firefox.

**Comment by adidahiya** [comment]
I can repro this on Firefox, but not Chrome or Safari. Which browser are you using @amin3141?

**Comment by amin3141** [comment]
That's correct @adidahiya . The issue only occurs on Firefox browsers. Sorry, I notice now that under "Browser name and version" I mentioned the version of Firefox, but not the actual browser itself.

**Comment by ejose19** [comment]
I've stumbled on this as well, and seems to be an [unresolved bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1487102) with firefox where `preventDefault` is not actually preventing anything. Only "workaround" I see is throwing another hack on: https://github.com/palantir/blueprint/blob/2968e3720d06861ee7eab804307b82c64f3d751c/packages/core/src/components/button/abstractButton.tsx#L168-L177

to avoid calling `this.buttonRef?.click();` if the browser is firefox (at least until upstream bug is resolved).

**Comment by adidahiya** [comment]
I ported the original repro to a fork of the latest Blueprint v5.x sandbox and can no longer repro the issue 🎉 

https://codesandbox.io/p/sandbox/fancy-cdn-625zxl?file=%2Fsrc%2FDatetimeExample.tsx%3A1%2C1
