### ISSUE TITLE
Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.

### ISSUE THREAD

**Issue by luciancaetano** [palantir/blueprint#4174]
#### Environment

- __Package version(s)__: 
    "@blueprintjs/core": "^3.28.2"
    "@blueprintjs/icons": "^3.18.1"
    "react": "^16.13.1"
- __Operating System__:  Linux
- __Browser name and version__: Google Chrome 83.0

#### Actual behavior

Outdated types

ERROR in [at-loader] ./node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts:258:28 
    TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.

ERROR in [at-loader] ./node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts:259:35 
    TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.

**Comment by adidahiya** [comment]
@luciancaetano what version of `typescript` and `@types/react` do you have installed?

**Comment by luciancaetano** [comment]
I used interna reat types installed when i ran npm install

**Comment by adidahiya** [comment]
And which version of typescript?

If you can demonstrate the issue with a code sandbox (as linked in the issue template), it helps me debug issues much faster.

**Comment by Seiyial** [comment]
Hi @adidahiya,

I'm facing this issue after bumping my `react` and `react-dom` `@types` versions, as well as `typescript` version.

Here's a codesandbox showing the dependencies list, but I'm not sure if it shows typescript  type errors that we're experiencing...
https://codesandbox.io/s/focused-resonance-147bg?file=/package.json

**Environment**

- **Package version(s):**
  "react": "16.13.1",
  "react-dom": "16.13.1",
  "react-scripts": "3.0.1",
  "@blueprintjs/core": "3.28.2",
  "@blueprintjs/datetime": "3.18.2",
  "@blueprintjs/icons": "3.18.1",
  "@blueprintjs/select": "3.13.3"

  "typescript": "3.9.5",
  "@types/react": "16.9.19",
  "@types/react-dom": "16.9.8"

- **Operating System**: Linux
- **Browser name and version**: Google Chrome 83.0

Upon building, typescript returns the same errors as mentioned above:

```
ERROR in /redacted/MyProject/node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts(258,28):
TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.
ERROR in /redacted/MyProject/node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts(259,35):
TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.
Version: typescript 3.9.5
Time: 19426 ms
```

**Possible solution(s)**

The error seems to occur here:

![image](https://user-images.githubusercontent.com/25403498/84580715-fcf4db00-ae0b-11ea-93e4-1f5c2d7cf283.png)

It seems to me that in `@types/react` `16.9.19`, `UIEvent` only needs the `HTMLElement` as the type parameter, and repeating `UIEvent` as above is not needed anymore.

![image](https://user-images.githubusercontent.com/25403498/84580767-6f65bb00-ae0c-11ea-87ca-de447ff0266d.png)

By changing the typing of `onScroll` and `onScrollCapture` to remove the additional `UIEvent` the type error is fixed.

![image](https://user-images.githubusercontent.com/25403498/84580779-97edb500-ae0c-11ea-85ef-dea17fa21810.png)

Sorry if I should have been following a certain template or if it's possible to have provided a more extensive demo in `codesandbox`.

**Comment by benritteraptiv** [comment]
I've started seeing this exact issue as well. Did a clean reinstall recently and it started popping up.

"@blueprintjs/core": "3.17.1",
"@blueprintjs/datetime": "3.11.0",
"@blueprintjs/docs-theme": "^3.4.0",
"@blueprintjs/icons": "3.9.1",
"@blueprintjs/select": "3.8.0",

"react": "16.8.6",
"react-dom": "16.8.6",
"@types/react": "16.8.23",
"@types/react-dom": "16.8.5",
"typescript": "3.8.3",

**Comment by adidahiya** [comment]
Can you all try upgrading to the latest `@types/react`, or at a minimum the version which is installed in this repo (`16.9.35`)? There may have been a breaking change in the types. If so, that's an unfortunate unintended break in our API, but a little hard to avoid and I think these kinds of breaks will continue happening every now and then. My best advice is to stay up to date on the latest `@types/react` version.

**Comment by jimmylarkin** [comment]
I'm now having this issue as well. It happens after a few seconds once the page loads. 
    "@blueprintjs/core": "^3.31.0",
    "@blueprintjs/icons": "^3.20.1",
    "@types/react": "^16.9.9",
    "@types/react-dom": "16.9.2",
    "typescript": "3.9.7"
