### ISSUE TITLE
[MultiSelect] onAdd handler is not invoked

### ISSUE THREAD

**Issue by xobotyi** [palantir/blueprint#4185]
#### Environment

- __Package version(s)__:
  - "@blueprintjs/core": "^3.28.2"
  - "@blueprintjs/select": "^3.13.3"
  - "react": "^16.13.1"
- __Operating System__: Windows 10 x64
- __Browser name and version__: Chrome 81

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-281ie

#### Steps to reproduce

1. Specify `onAdd` property of `tagInputProps`
1. Enter smth to tag input

#### Actual behavior

Nothing happens (provided callback is not invoked)

#### Expected behavior

Provided `onAdd` callback should be invoked

**Comment by adidahiya** [comment]
If you are looking to update your `selectedItems` state, then you ought to use the `onItemSelect` prop instead. This will give you a callback with newly selected items, and is a little more convenient when you have a more complex type of MultiSelect where the items are not simple `string` types. You can see how it is done in the docs example code: https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/select-examples/multiSelectExample.tsx

If there is significant interest in supporting `tagInputProps.onAdd`, I might consider adding it (we'd have to call the user-supplied function in MultiSelect). In the meantime, I guess the docs could use an update to mention that this is unsupported.

**Comment by xobotyi** [comment]
@adidahiya i have a case when user should be able to select from the list AND input on his own.

Also in my case tags are not plain text - they're react objects with some nesting level thus use of `tagInputProps` `onChange` kind of PITA because i have a mixed array of strings and objects and have to dig down to determine what the actual value is with excessive array mapping
```js
newSelected = newSelected.map((i) => {
  if (typeof i === 'string') return i;

  return i.props.children.props.category;
});
onChange(newSelected);
```
IMO it is woth to notice in docs that `onChance` receive not values itself but mix of existing tags contents and newely added strings. I was frustrated when received objects but docs told that it is values🙃

**Comment by adidahiya** [comment]
> i have a case when user should be able to select from the list AND input on his own

The [MultiSelect example in the docs](https://blueprintjs.com/docs/#select/multi-select) shows this kind of use case. Have you checked out its source code? It uses `onItemSelect` and `tagInputProps.onRemove`. It doesn't use `tagInputProps.onAdd` or `tagInputProps.onChange`. You should be able to set up your usage in a similar way.
