### ISSUE TITLE
Any way to access the openPanel property of a PanelStack outside of the PanelStack itself?

### ISSUE THREAD

**Issue by krozett** [palantir/blueprint#4189]
`openPanel` gets injected as a prop into the components that get rendered in the stack. I can call `this.props.openPanel` just fine, but what if I want to manipulate the stack outside of the component? There doesn't seem to be a way to do this. I poked around into a ref to the PanelStack, but could not find any way to get to `openPanel`.

**Comment by adidahiya** [comment]
It sounds like you want "controlled" behavior of the `<PanelStack>` component. You can use the `stacks` prop to explicitly control which panel is open in a declarative manner (the last panel in the stack will be displayed). [docs here](https://blueprintjs.com/docs/#core/components/panel-stack.props)

**Comment by krozett** [comment]
Thanks, I'll check it out.
