### ISSUE TITLE
Navbar with Menu dosnt work

### ISSUE THREAD

**Issue by jim-alexander** [palantir/blueprint#4193]
- __Package version(s)__: 3.29.0
- __Operating System__: MACOS
- __Browser name and version__: Firefox 75

#### Code Sandbox

Link to a minimal repro (fork [this stackBlitz](https://stackblitz.com/edit/blueprint-dev?file=Navigation.js))

#### Actual behavior

The menu component isn't working with a Navbar

#### Expected behavior

I want to use the navbar and have items with children like how a menu would work. (I would have assumed this to be pretty standard functionality.. but cant seem to find anyone else with the problem.)

**Comment by jim-alexander** [comment]
Didnt change anything and then it started to work.. then a few seconds later it wasnt working again, This could be a problem with stackBlitz..

**Comment by adidahiya** [comment]
The "Registers" and "Statistics" dropdowns work fine for me in your stackblitz !
