### ISSUE TITLE
missing documentation 

### ISSUE THREAD

**Issue by bsdis** [palantir/blueprint#4199]
Hi - I am trying to use the blueprintjs table, but I find the documentation for it quite non-existing.
Are there any examples of how to use the getCellClipboardData prop and are there any example on how to set the width of the entire table? I was not able to find any information about that anywhere.

**Comment by adidahiya** [comment]
You can see documentation of `getCellClipboardData` here: https://blueprintjs.com/docs/#table/api.table

Also a [search for that symbol in this repo](https://github.com/palantir/blueprint/search?q=getCellClipboardData&unscoped_q=getCellClipboardData) shows some usage examples

Re: setting width of the entire table... you should be able to do that with CSS on the table's container element. You might also need a `width: 100%` rule applied to the table root element.
