### ISSUE TITLE
NumericInput events run incorrectly when using min or max props

### ISSUE THREAD

**Issue by ejose19** [palantir/blueprint#4200]
#### Environment

- __Package version(s)__: 3.28 / 3.29
- __Operating System__: Linux
- __Browser name and version__:  Firefox 77 / Chromium 81

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-numericinput-vxkuu

#### Steps to reproduce

1. Hold arrow button until limit is reached, then do the same with opposite button, repeating a couple of times will
   make all events to not work properly (button clicks set more than 1 step at once, and keyboard up and down arrow don't stop until limit is reached, even if tapped once)

#### Actual behavior

Button & keyboard events don't work properly

#### Expected behavior

Behaviour shouldn't not change when usin min/max

Edit: Seems I found the cause of the issue, this bug doesn't happen if you release the mouse before reaching the limit, or upon reaching the limit, outside of the disabled button. I've checked the source and it seems stopContinuousChange is not firing when releasing the mouse on the disabled button

**Comment by adidahiya** [comment]
Yeah, I can confirm this bug.

> I've checked the source and it seems stopContinuousChange is not firing when releasing the mouse on the disabled button

Sounds about right. Related to other bugs about disabled buttons not receiving events like https://github.com/palantir/blueprint/issues/967.
