### ISSUE TITLE
Maximum update depth exceeded in EditableName / EditableText (on Chrome)

### ISSUE THREAD

**Issue by pcdv** [palantir/blueprint#4212]
#### Environment

    "@blueprintjs/core": "3.29.0",
    "@blueprintjs/table": "^3.8.5",
   Win10
   Chrome 83.0.4.4103.116 (KO) and Firefox (OK)
#### Code Sandbox

https://codesandbox.io/s/xenodochial-greider-bp3jr

#### Steps to reproduce

1. Edit "name" a couple of times, it should crash pretty quickly

#### Actual behavior

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```
```
 258 | export { EditableText };
 259 | function getFontSize(element) {
 260 |     var fontSize = getComputedStyle(element).fontSize;
 261 |     return fontSize === "" ? 0 : parseInt(fontSize.slice(0, -2), 10);
```

Looks like this happens also when removing the EditableText

#### Expected behavior

Being able to edit with EditableName

#### Possible solution

Don't know :/

**Comment by adidahiya** [comment]
It looks like you are styling the component with `text-align: center`. This is explicitly called out in [the docs](https://blueprintjs.com/docs/#core/components/editable-text) as unsupported usage which will cause a crash.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/723999/86817478-17108a80-c053-11ea-8480-00e4ee7ba7c4.png">

**Comment by pcdv** [comment]
It's a surprise. As you can see in the codesandbox, I'm not styling anything at all. I checked the inspector and did not find any mention of the `text-align` property either.

**Comment by pcdv** [comment]
Maybe the problem is that EditableName is part of @blueprintjs/table and not @blueprintjs/core (I did not realize that at first, found it with autocomplete) and should not be used outside of a table context.

**Comment by adidahiya** [comment]
In styles.css:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/723999/86840108-54374580-c070-11ea-8ade-538d202ec268.png">

And yes, EditableName should only be used inside the table component. But EditableText works on its own.

**Comment by pcdv** [comment]
Indeed I had missed this default styling in codesandbox. Removing it does not fix the problem but I guess I will use EditableText then.

Thanks
