### ISSUE TITLE
Unable to start the development server on a freshly cloned repo

### ISSUE THREAD

**Issue by rayanht** [palantir/blueprint#4217]
#### Environment

- __Package version(s)__: develop & yarn 1.22.4
- __Operating System__: macOS Mojave
- __Browser name and version__: N/A

#### Steps to reproduce

1. Fork and clone the repo
2. `yarn && yarn dev`

#### Observed behavior

```
$ lerna run dev --parallel --scope "!@blueprintjs/{landing-app,table-dev-app}"
lerna notice cli v3.22.0
lerna info versioning independent
lerna notice filter including "!@blueprintjs/{landing-app,table-dev-app}"
lerna info filter [ '!@blueprintjs/{landing-app,table-dev-app}' ]
lerna ERR! EFILTER No packages remain after filtering [ '!@blueprintjs/{landing-app,table-dev-app}' ]
error Command failed with exit code 1.
```

**Comment by adidahiya** [comment]
Looks like this broke with the lerna 3 upgrade (https://github.com/palantir/blueprint/commit/83fd97f5da8ea0235a56340818b7251830f34a8b). I just pushed a fix. The other `dev:` tasks should work too, if you don't want to build the whole repo.
