### ISSUE TITLE
Styles for use in isolated components

### ISSUE THREAD

**Issue by ViggoV** [palantir/blueprint#4224]
#### Environment

- __Package version(s)__: 3.29.0
- __Browser and OS versions__: Chrome 83.0.4103.116 on MacOS 10.15.5

#### Feature request

Currently it is nescessary to insert the stylesheets globally to use Blueprint. However, as far as I can tell it should be possible to apply most of the styles, exept of course those for `body` and `html`, to an element forther down the DOM.

At my work we are currently slowly moving from a monolithic Rails application to a more modularised architecture. I am extracting the functionality component by component and would really like to use Blueprint, however I can't override the global styles for the time being.

Would it be possible to build a stripped version of the css-file(s) which could be used with something like `styled-components` to apply the styles to a standalone component.

#### Examples

The component I am currently working on is a cookie consent form, for use across our products. It is built as a standalone webpack module and served over private CDN. I would like to use Blueprint for checkboxes and buttons, but again I can't inject global styles into the existing site without jeopardizing the current layout.

**Comment by adidahiya** [comment]
Yes, I believe this would be valuable, but it is a large undertaking and has not been a high priority for our use cases. I believe it's essentially the same as this issue so I'm going to mark it as a duplicate: https://github.com/palantir/blueprint/issues/248
