### ISSUE TITLE
Focus border on an InputGroup partially hidden when inside div with overflow: auto

### ISSUE THREAD

**Issue by marenaud** [palantir/blueprint#4233]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "^3.30.0",
- __Operating System__: Ubuntu 18.04
- __Browser name and version__: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)):https://codesandbox.io/s/blueprint-sandbox-5wqrw

#### Steps to reproduce

1. Make a Card with a scrollable form (overflow: auto on the form)
2. Put an InputGroup inside the form
3. Focus on the input
4. Notice that the border glow is partly hidden even when nothing is overflowing.

#### Actual behavior

When the input is focused, the focus glow is partly hidden.

#### Expected behavior

The border should not be hidden.

#### Possible solution

Only seems happens when overflow is set on the form.

**Comment by adidahiya** [comment]
This is expected CSS behavior. The box shadow of the input is outside the component, and you haven't provided any padding on your container element with a `overflow` CSS rule, so it will clip:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/723999/88132953-d5352780-cbae-11ea-9e35-7bde325aae94.png">
