### ISSUE TITLE
very poor performance on table sort

### ISSUE THREAD

**Issue by bsdis** [palantir/blueprint#4241]
Hi. I am using react+redux+blueprinjs table to make a table where user can sort columns asc/desc by clicking on the column header. It works great on this example: https://codesandbox.io/s/cocky-bell-43eqh however when adapting that implementation the performance is so bad that tables cannot even sort. 
Are there any places in this component where i am doing something obviously bad to destroy the performance/functionality? (https://dpaste.org/d1bH#L14)  I have been staring at this for so long now and I cannot figure out why the component is rerendering all the time when sorting. I hope someone can help me with some advice on what I am doing wrong here. Thanks so much!

**Comment by vileen** [comment]
@bsdis did you solve the problem or was it just your mistake? Why did you just close the issue without any information?
