### ISSUE TITLE
New eslint-plugin rule suggestion: @blueprintjs/intent-constants

### ISSUE THREAD

**Issue by cihati** [palantir/blueprint#4242]
#### Feature request

The existing eslint-plugin already has a useful `@blueprintjs/classes-constants` rule. I propose a similar one for `Intent`. 

#### Examples

If the linter sees such usage:
```
        <Button
          onClick={onButtonClick}
          intent="primary"
          text="Test"
        />
```

It should warn and suggest using `Intent.PRIMARY`.

I have never written an eslint rule, but if this is seen useful, I might give it a shot. Also, if you have similar `Elevation`, `Position`, `Alignment`, etc too

**Comment by adidahiya** [comment]
the `intent` prop is type checked for the correct string literals. so I don't really see the need for this rule. prefer to use type checking as much as possible rather than lint rules

**Comment by cihati** [comment]
@adidahiya sounds good.
