### ISSUE TITLE
DateInput does not work as expected on a Dialog

### ISSUE THREAD

**Issue by anupbhatt** [palantir/blueprint#4246]
#### Environment

- __Package version(s)__: 
- __Operating System__: Mac OS High Siera 10.13.6 
- __Browser name and version__:  Chrome 84.0.4147.89, Safari 13.1.2, Firefox 68.10.0

#### Code Sandbox

Minimal code to see these DateInput issues :

    <Dialog isOpen={props.isOpen} title="Sample">
      <DateInput
        timePickerProps={{
          disabled: false,
        }}
      />
    </Dialog>

#### Steps to reproduce

Click on DateInput field. 
Click on the button which displays the month name.
Click on the button which displays the year. 
Click on time field. 

#### Actual behavior

The list of months flashes but does not remain open for selection when a month name is clicked. 
The list of years flashes but does not remain open for selection when a year is clicked. 
The time field remains disabled. 

#### Expected behavior

The list of months should remain open for selection when a month name is clicked. 
The list of years should remain open for selection when a year is clicked. 
The time field should be editable. 

#### Possible solution

Don't have any solution. Note that above problems occur on Dialog only. It works on a page.

**Comment by adidahiya** [comment]
If you link to a working code sandbox which reproduces the issue that will make debugging a lot quicker! Thanks

**Comment by mapes911** [comment]
I'm having the exact same issue and I tried to recreate the problem here:

https://codesandbox.io/s/javascript-forked-y3tzx

However, the problem doesn't occur in this sandbox when setting up the form/overlay in the same way as my main project, which makes me think that maybe this is some sort of conflict with another library? or some weird click handler or css issue?

I'm not sure... just wanted to post this in case someone else has the same issues.
Attaching my package.json here.. @anupbhatt are you using similar libraries? 

Maybe we can work together to figure this out.

PS. I'm also only experiencing this when in a Dialog (Overlay) or in a Drawer.  Both use an overlay I believe.

```json
  "dependencies": {
    "@apollo/client": "^3.1.1",
    "@blueprintjs/core": "^3.30.0",
    "@blueprintjs/datetime": "^3.18.5",
    "@blueprintjs/select": "^3.13.6",
    "apollo-cache-persist": "^0.1.1",
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "graphql": "^15.0.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.15",
    "moment": "^2.27.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hook-form": "^5.7.2",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.1.1",
    "url-loader": "^4.1.0"
  },
```

**Comment by iRayan7** [comment]
Same issue here

**Comment by WadhahEssam** [comment]
@mapes911 Have you found a workaround for this ?

**Comment by anupbhatt** [comment]
> I'm having the exact same issue and I tried to recreate the problem here:
> 
> https://codesandbox.io/s/javascript-forked-y3tzx
> 
> However, the problem doesn't occur in this sandbox when setting up the form/overlay in the same way as my main project, which makes me think that maybe this is some sort of conflict with another library? or some weird click handler or css issue?
> 
> I'm not sure... just wanted to post this in case someone else has the same issues.
> Attaching my package.json here.. @anupbhatt are you using similar libraries?
> 
> Maybe we can work together to figure this out.
> 
> PS. I'm also only experiencing this when in a Dialog (Overlay) or in a Drawer. Both use an overlay I believe.
> 
> ```json
>   "dependencies": {
>     "@apollo/client": "^3.1.1",
>     "@blueprintjs/core": "^3.30.0",
>     "@blueprintjs/datetime": "^3.18.5",
>     "@blueprintjs/select": "^3.13.6",
>     "apollo-cache-persist": "^0.1.1",
>     "axios": "^0.19.2",
>     "core-js": "^3.6.5",
>     "graphql": "^15.0.0",
>     "jwt-decode": "^2.2.0",
>     "lodash": "^4.17.15",
>     "moment": "^2.27.0",
>     "react": "^16.13.1",
>     "react-dom": "^16.13.1",
>     "react-hook-form": "^5.7.2",
>     "react-router-dom": "^5.2.0",
>     "styled-components": "^5.1.1",
>     "url-loader": "^4.1.0"
>   },
> ```

**Comment by anupbhatt** [comment]
I accidentally closed this issue. Re-opening it.

**Comment by anupbhatt** [comment]
@mapes911 I am using different libraries, but blueprints and react versions in my package.json are:
"@blueprintjs/core": "^3.23.1",
"react": "^16.9.0"

**Comment by anupbhatt** [comment]
@mapes911 I  I could reproduce all the problems which I mentioned by changing the blueprints/core version to 3.23.1 in your sample https://codesandbox.io/s/javascript-forked-y3tzx. Also, I verified that these problems do not occur if change blueprints/core version to 3.31.0. 

![image](https://user-images.githubusercontent.com/68756508/91193515-69197800-e6b4-11ea-9645-7f4c5c2fcf0c.png)

**Comment by mapes911** [comment]
@anupbhatt  that's great information. have you tried it in your main project? I just tried quickly with 3.31.0 and it doesn't seem to solve the problem for me :(

but... hopefully this can help @adidahiya  debug... can you try 3.23.1 in my sample so you can see the issue first hand?

**Comment by adidahiya** [comment]
I need to know the version of the datetime package as well. blueprint core 3.23.1 is very old, and if the issue doesn't persist in the latest version, then it's unlikely to get backported as a fix.

**Comment by adidahiya** [comment]
@anupbhatt I forked your sandbox to use core 3.23.1 and datetime 3.15.2. I can't repro your issue: https://codesandbox.io/s/dateinput-in-dialog-old-blueprint-version-hxrtt

**Comment by mapes911** [comment]
@adidahiya this sandbox reproduces it, using core 3.23.1 and datetime 3.18.6

https://codesandbox.io/s/javascript-forked-y3tzx

**Comment by adidahiya** [comment]
@mapes911 ok, I see the issue there. But those versions are incompatible. Look at datetime's package.json: https://unpkg.com/browse/@blueprintjs/datetime@3.18.6/package.json

**Comment by mapes911** [comment]
@adidahiya thank you so much! that was the problem.
my project had
```
    "@blueprintjs/core": "^3.31.0",
    "@blueprintjs/datetime": "^3.18.5",
```

bumped the datetime version to 3.18.6 and the issue has gone away. 🥳

**Comment by anupbhatt** [comment]
Thanks for this fix in newer version. It works on my project now.
