### ISSUE TITLE
Tabs component changes height when changing Tab

### ISSUE THREAD

**Issue by JuanIrache** [palantir/blueprint#4257]
#### Environment

- __Package version(s)__: 3.26.0
- __Browser and OS versions__: Electron JS 8.2.3 and Windows 10

#### Feature request

When changing Tab, the height of the Tabs component changes, moving the rest of the content around, even if you leave the _renderActiveTabPanelOnly_ option as true. 

Is there a way to have the component mantain a fix height? (based on the tallest of components)

Thank you

#### Examples

Demonstration video https://youtu.be/2pm6ZCYgYpc
Minimal example https://github.com/JuanIrache/blueprint-tabs-test

**Comment by adidahiya** [comment]
This doesn't happen in the docs example page. The tabs stay in the same position. Maybe you have some other CSS interfering.

![2020-08-04 11 11 49](https://user-images.githubusercontent.com/723999/89310925-54ad0700-d643-11ea-891d-1b62cdba827c.gif)

If you want a consistent height, I recommend setting it explicitly with CSS on the `<Tabs>` element with a custom `className`. Perhaps a `min-height` rule.

**Comment by JuanIrache** [comment]
The tabs (labels) themselves changing height is my own thing indeed (and that's fine for me), but I was referring to the whole Tabs element. Using the min-height rule would involve knowing the height of the content inside the tabs, or otherwise I would be creating blank spaces or overflowing the available space. Wouldn't I?

Note that the gif you posted has the same problem: the section under the Tabs element (where it says "View source on GitHub") jumps up and down as you change tabs.

Thank you

**Comment by adidahiya** [comment]
> Using the min-height rule would involve knowing the height of the content inside the tabs

The current behavior, where the component container has a height responsive to its contents is the simplest, default CSS layout scheme. It keeps the component relatively simple. If we "fixed" the height inside the Tabs component, it would have to measure height of its contents. I don't think any other Blueprint component does this, and this doesn't feel like a strongly justified place to start adding that behavior.

I think this situation is best solved by improving your app layout surrounding the Tabs. If you want something with responsive height, then perhaps use a flex rows layout and set `height: 100%` on your Tabs container.

**Comment by JuanIrache** [comment]
Thanks for your reply
