### ISSUE TITLE
Replace node api 'isSameNode'

### ISSUE THREAD

**Issue by MrMengJ** [palantir/blueprint#4260]
![image](https://user-images.githubusercontent.com/26325346/89265676-6b655500-d667-11ea-9354-3856128bf928.png)

This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.
Could you repalce item?

https://github.com/palantir/blueprint/blob/a8b08f54124422432fa9b9ac1b67144f255e85b8/packages/core/src/components/overlay/overlay.tsx#L437

**Comment by adidahiya** [comment]
> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

Can you point me to documentation which states this? The ["Can I use..."](https://caniuse.com/#search=issamenode) page which you screenshotted doesn't say that.

**Comment by MrMengJ** [comment]
@adidahiya "[https://developer.mozilla.org/zh-CN/docs/Web/API/Node/isSameNode](url)" this one in MDN

**Comment by adidahiya** [comment]
Interesting... the English version of that page doesn't have the same callout warning: https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode

It does mention "Obsolete" status lower down the page in a very brief mention... but when I click through to the DOM level 3 specification, I don't actually see an equivalent API which can replace `.isSameNode()`.

Unless you are experiencing actual issues at runtime with this API used by Blueprint, I don't think this is a problem.

**Comment by MrMengJ** [comment]
@adidahiya 
![image](https://user-images.githubusercontent.com/26325346/89480984-50aaf180-d7c9-11ea-915a-e19c55f5f2e2.png)

In firefox 40, click Breadcrumb in overflow list, the page will broken.
But it is OK in IE11 and any version Chrome, so  strange!

**Comment by adidahiya** [comment]
@MrMengJ how is it broken? can you describe the exact repro steps? If you are experiencing a bug, please fill out the bug report issue template. Firefox 40 is _extremely_ old (2015), we do not support browsers that old.
