### ISSUE TITLE
Datepicker time component failing to lose focus when clicking away from component

### ISSUE THREAD

**Issue by bondsgame101** [palantir/blueprint#4265]
#### Environment

- __Package version(s)__: 
"@blueprintjs/core": "^3.22.1",
"@blueprintjs/datetime": "^3.15.1",
"@blueprintjs/icons": "^3.12.0",
"@blueprintjs/select": "^3.11.2",
"@blueprintjs/table": "^3.8.2"

- __Operating System__: OSX Catalina
- __Browser name and version__: Chrome latest

#### Steps to reproduce

1. Use DateTimePicker in component with clickAway to close enabled
2. Edit timeHour
3. Leave cursor in time component and click away

#### Actual behavior

The datePicker will close and reopen because focus is not being lost by the timeHour input

#### Expected behavior

The datePicket to close upon click away and not refocus

#### Possible solution

None, currently.

**Comment by adidahiya** [comment]
> Use DateTimePicker in component with clickAway to close enabled

What does this mean? Can you build a code sandbox to demonstrate the issue? A sandbox template is linked in the issue template, it greatly speeds up debugging.
