### ISSUE TITLE
Card onclick still activates despite another card on top of it

### ISSUE THREAD

**Issue by afandrew** [palantir/blueprint#4269]
I'm dealing with an issue regarding nested cards. The structure of items are as follows:

```
<Card onClick={changes collapse state}>
    <Collapse>
       <Card>
           <Button>
           </Button>
       </Card>
    </Collapse>
</Card>
```

When I try to click something on the inside card, such as the button, the outside card's onclick function triggers, collapsing the inside card. Is there a way to make the outside card's onclick not activate while interacting with the inside card?

**Comment by adidahiya** [comment]
This is standard DOM event behavior, not specific to Blueprint. You should inspect the `target` and `currentTarget` properties of the events inside your Card and add logic to selectively ignore the types of clicks which should not collapse the inside card.
