### ISSUE TITLE
NumericInput can cause selection when clicking the up or down buttons quickly

### ISSUE THREAD

**Issue by mfedderly** [palantir/blueprint#4270]
#### Environment

- __Package version(s)__: 3.30.1
- __Operating System__: OSX
- __Browser name and version__: Chrome 84

#### Code Sandbox

https://blueprintjs.com/docs/#core/components/numeric-input

#### Steps to reproduce

1. Click the up or down button rapidly

#### Actual behavior

The word 'Props' in the right column becomes selected

#### Expected behavior

Selection is prevented

#### Possible solution

I think you can event.preventDefault() to avoid the selection from happening? I'd have to test it though.

**Comment by Gatix** [comment]
I have the same issue, it still triggers text selection even if you click slowly

**Comment by adidahiya** [comment]
If you have a specific part of your UI which you really don't want a user to be able to select, consider using the [`user-select` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select). Otherwise, I'm not sure we should be interfering with event propagation & default browser behavior in this case... it can cause unintended side effects.

**Comment by mfedderly** [comment]
I guess that works for me, really strange that you'd need to remember to put `user-select: none` on a completely unrelated element to avoid the selection behavior from using the input.

**Comment by cybae0804** [comment]
> I guess that works for me, really strange that you'd need to remember to put `user-select: none` on a completely unrelated element to avoid the selection behavior from using the input.

Agreed. I've also fixed it by putting `user-select: none` for the time being, putting that property on sibling elements to all the wrappers seem a bit hacky.

EDIT: So I've actually noticed a few things. 

1. This doesn't happen on Firefox at all. 

2. You can fix this by changing the buttons to be `button` elements in stead of `a` elements. I don't know why these buttons need to be `a` elements, but changing them fixes the issue. To be specific, `<a role="button" class="bp3-button" tabindex="0"></a>`

**Comment by adidahiya** [comment]
The buttons were recently changed from `<button>` to `<a>` to improve some event handling behavior in this PR: https://github.com/palantir/blueprint/pull/4201. I would consider changing them back if this issue turns out to be a widespread annoyance.

**Comment by yarl** [comment]
It kinda is, depends on implemented code it causes selection of some parts of application which is pretty noticeable.

**Comment by darkopetrovic** [comment]
Actually, putting `user-select: none;` directly on the button itself is working as well:

```css
.bp3-numeric-input > .bp3-button-group {
  user-select: none;
}
```
