### ISSUE TITLE
Tag Input doesn't change when props change

### ISSUE THREAD

**Issue by KippWade** [palantir/blueprint#4277]
#### Environment

- __Package version(s)__: Blueprint Core @ 3.30.1
- __Browser and OS versions__:  Chrome / Windows 10

#### Question

We have the tags input on our form, but if the props data changes, the tags do not update.  
We have verified that the actual props data has changed.
Is there an additional step we need to have the Tags Input update, or is there possible an issue with this not recognizing that the component updated?

**Comment by adidahiya** [comment]
Can you please create a code sandbox to demonstrate the issue (linked in the issue template)? That greatly speeds up debugging.

**Comment by KippWade** [comment]
Of course, right after posting my issue, we find the solution.  The sub-component where the tag input was, wasn't being updated properly.
