### ISSUE TITLE
Toggle appear column in table

### ISSUE THREAD

**Issue by belal-mazlom** [palantir/blueprint#4279]
#### Environment
Package version: latest version
#### Question
For table package, is there a way to show/hide specific column using property?

I want toggle columns depend on user preferences for listed data.

**Comment by DanNicolau** [comment]
It would be nice to have this added in the API, for now you can put your columns in an array and put the array in your table.
See: https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx

**Comment by adidahiya** [comment]
Deciding which columns to render at any time is all up to you. Just change the `<Column>` children list rendered inside `<Table>`.
