### ISSUE TITLE
Core & Select ITagProps out of sync

### ISSUE THREAD

**Issue by mattydono** [palantir/blueprint#4281]
#### Environment

- __Package version(s)__: core 3.31.0 & select 3.13.5
- __Operating System__: windows
- __Browser name and version__: chrome latest

#### Steps to reproduce

Using multi-select with ITagProps

#### Actual behavior

Type Error

![image](https://user-images.githubusercontent.com/42358242/90121808-5ddd5880-dd54-11ea-8410-4bef3faec3ed.png)

#### Expected behavior

able to modify props

#### Possible solution

Publish select with updated ITagProps

**Comment by adidahiya** [comment]
There is a more up to date version of select, the latest is 3.13.7
