### ISSUE TITLE
Render bp3-table-menu

### ISSUE THREAD

**Issue by hadrienl** [palantir/blueprint#4282]
Hi,

I'd like to render the first row in the table (the empty corner with the class "bp3-table-menu". I can't find any render prop to change its content.

**Comment by adidahiya** [comment]
I think you're looking for [`IColumnProps.columnHeaderCellRenderer`](https://blueprintjs.com/docs/#table/api.column)

**Comment by adidahiya** [comment]
Actually, if you're looking to replace the top-left corner, it looks like there is no API to do this. I doubt we'd add one... you should consider just rendering your own floating element above the table in that location.
