### ISSUE TITLE
[table] The tooltip prop for a Cell does not do anything 

### ISSUE THREAD

**Issue by alekseyig** [palantir/blueprint#4283]
#### Environment

- __Package version(s)__: 
"@blueprintjs/table": "^3.8.13",
- __Operating System__: 
Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
- __Browser name and version__: 
Chrome Version 81.0.4044.113 (Official Build) (64-bit)

#### Steps to reproduce

\<Cell tooltip="test_tooltip"> test</Cell\>

#### Actual behavior

does not show "test_tooltip" when I hover over the cell

#### Expected behavior

should see "test_tooltip" when I hover over the cell

#### Possible solution

css is broken ?

**Comment by adidahiya** [comment]
Note that this prop enables a [browser native tooltip](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title), not a Blueprint tooltip. It doesn't use CSS.

Can you link to a bug repro using the code sandbox linked in the issue template?

**Comment by alekseyig** [comment]
@adidahiya, thanks for clarifying.
