### ISSUE TITLE
How add colors to my code on Pre tag?

### ISSUE THREAD

**Issue by arthursoas** [palantir/blueprint#4289]
I'm doing the following:

```js
import React, { Component } from 'react';
import { Pre } from "@blueprintjs/core";

export class MyClass extends Component {
  render() {
    return (
      <Pre lang="json">
          {JSON.stringify(MessageJSON, null, 2)}
     </Pre>
  )
}
```

But my code block is all with black color. I want to color it, like the blueprint docs do on its own website, like:

![image](https://user-images.githubusercontent.com/22826013/90966736-84b23200-e4ac-11ea-9712-29e429bf5124.png)

Is that possible?

**Comment by adidahiya** [comment]
Blueprint doesn't do any syntax highlighting. That can be accomplished using libraries like `highlights`. The docs site does that [here](https://github.com/palantir/blueprint/blob/a0c244165da17800bd7cd04d413b1644d300aea2/packages/docs-data/docsUtils.js#L39) in its markdown rendering pipeline.
