### ISSUE TITLE
Multiselect refocus on select

### ISSUE THREAD

**Issue by bofa** [palantir/blueprint#4292]
#### Environment

- __Package version(s)__:  "@blueprintjs/select": "^3.13.7",
- __Operating System__:  Windows 10
- __Browser name and version__:  Chrome 85

#### Code Sandbox

Link to a minimal repro https://blueprintjs.com/docs/#select/multi-select: 

#### Steps to reproduce

1. Scroll down list
2. Select Item

#### Actual behavior

Focus is lost and list re-renderer from the top 

#### Expected behavior

Stay with the select item so user can keep selecting items in the list

#### Possible solution

This seams to be working as expected in version 2, https://blueprintjs.com/docs/versions/2/#select/multi-select

**Comment by adidahiya** [comment]
duplicate of https://github.com/palantir/blueprint/issues/3596
