### ISSUE TITLE
InputRef is not a function error for TextArea

### ISSUE THREAD

**Issue by weilandia** [palantir/blueprint#4294]
#### Environment

- __Package version(s)__:  3.26.1
- __Operating System__: MacOS
- __Browser name and version__: Chrome latest

#### Code Sandbox
https://codesandbox.io/s/blueprint-sandbox-forked-qj8xe

#### Steps to reproduce
Pass inputRef to TextArea using useRef()

#### Actual behavior
_this.props.inputRef is not a function

#### Expected behavior
No error.

#### Possible solution
Look into this commit:
https://github.com/palantir/blueprint/commit/35aa3538f6b83d31ba6eac705639e52b45d7d3fb

**Comment by adidahiya** [comment]
#4198 was later updated by https://github.com/palantir/blueprint/pull/4206, but yes this is a bug we should fix ASAP
