### ISSUE TITLE
Allow slider's `labelStepSize` to accept an array/function to specify which values should get a label.

### ISSUE THREAD

**Issue by cybae0804** [palantir/blueprint#4297]
#### Environment

- __Package version(s)__: 3.25.0
- __Browser and OS versions__: Ubuntu 18.04, Chrome 84

#### Feature request

Allow slider's `labelStepSize` to accept a array/function to specify which values should get a label.

#### Examples

If the min/max of the slider does not divide up nicely, the labels become very awkward. Say min/max is 1/200, step size of 10 would show 1, 11, 21, 31... and so on, whereas you might want a label like 1, 10, 20, 30... 200, in which case the initial step size would be 9, and then 10 afterwards. 

I think a possible implementation could be that the prop can still receive a numeric value to behave as it does currently, but also allow it to receive an array of numeric values where the labels will render.

**Comment by J-Vin** [comment]
Are you suggesting adding a registry key?

**Comment by cybae0804** [comment]
> 
> 
> Are you suggesting adding a registry key?

Not sure what you mean by that.
