### ISSUE TITLE
Memory leak in multiSelect and tagInput causing error in react due to using setState on unmounted component.

### ISSUE THREAD

**Issue by jareqpl** [palantir/blueprint#4299]
#### Environment

- __Package version(s)__:
    "@blueprintjs/core": "3.31.0",
    "@blueprintjs/icons": "3.20.1",
    "@blueprintjs/select": "3.13.7",
- __Operating System__: Windows 10
- __Browser name and version__: jest js-dom 26.4.2 (also happening in chrome 84.0.4147.135)

#### Code Sandbox

Please fork [https://github.com/jareqpl/bpjs-memory-leak-reproduction](https://github.com/jareqpl/bpjs-memory-leak-reproduction))

#### Steps to reproduce

1. npm run install
2. npm run test

#### Actual behavior
Getting error:
Warning: Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application.
To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount
method.
#### Expected behavior
Error should not appear. 
#### Possible solution
You need to cancel all invocations of requestAnimationFrame before component is unmunted.

Thank you very much for the fix! :)

**Comment by adidahiya** [comment]
not a "memory leak" in the traditional sense of the term, but yes this is a bug. I recently fixed it in https://github.com/palantir/blueprint/pull/4290, which will be in the next release, likely next week.
