### ISSUE TITLE
Escape key cannot escape Popover element

### ISSUE THREAD

**Issue by Nantris** [palantir/blueprint#4300]
#### Environment

- __Package version(s)__: 3.31.0
- __Operating System__: Windows 7
- __Browser name and version__: Firefox 80 (Also seems to affect Webkit browsers)

#### Code Sandbox

https://blueprintjs.com/docs/#core/components/popover

#### Steps to reproduce

Open popover and then press `ESC`

#### Actual behavior
Nothing

#### Expected behavior

Popover closes upon `ESC`

**Comment by adidahiya** [comment]
Looks like Overlay's `autoFocus` prop isn't working as intended. This is a regression.
