### ISSUE TITLE
Try to pick date in "Datepicker" with Formik

### ISSUE THREAD

**Issue by MichalPorag** [palantir/blueprint#4304]
#### Environment

- __Package version(s)__: 3.18.6
- __Browser and OS versions__: Chrome and Windows

#### Question

I try to change the date in the "Datepicker" will running text with Formik. 
if I use this code:

`     const selector = document.querySelector(".bp3-datepicker-caption > .bp3-datepicker-month-select > select");
      selector.dispatchEvent(new Event("change"));
      selector.value = "0";`

With this code, I succeeded to change the month to January but the "DayPicker-Body" does not update.

**Comment by adidahiya** [comment]
If you create a clear repro using the linked code sandbox that will greatly help in debugging, thanks
