### ISSUE TITLE
Reset Select component

### ISSUE THREAD

**Issue by rickysullivan** [palantir/blueprint#4317]
#### Environment

- __Package version(s)__: "@blueprintjs/select": "^3.13.7"
- __Browser and OS versions__: n/a

#### Question

I have two select components. If a user chooses an option from select component A, I'd like to reset select component B. 

How can I reset a component back to an un-selected state.

![image](https://user-images.githubusercontent.com/437480/92366835-c4824600-f149-11ea-85f0-453e7d0a9532.png)

**Comment by rickysullivan** [comment]
Ok, so I figured out that I can reset the text on the Button. I have also kept a reference to the `activeItem` in a context that's shared between both selectors. Selecting an item in select component A now removes the activeItem from select component B and the button text is also reset.

**Comment by adidahiya** [comment]
Closing as this seems to be a generic question about React application logic and not really Blueprint-specific.
