### ISSUE TITLE
Formula for generating variants of a color

### ISSUE THREAD

**Issue by alberto-f** [palantir/blueprint#4318]
Hello, Thank you very much for the work done on BlueprintJS component library.

Here, using blueprintjs version 3.31.

I have noticed that all the colors have their variants defined in `@blueprintjs/core/lib/scss/variables.scss`.

Have you hand pick the variants for every color ? Did you use any "logic" to come with those variants ? If so, could you share it ?

Thanks.

**Comment by adidahiya** [comment]
> Have you hand pick the variants for every color

Yes, our designers created these color palettes balancing various concerns including accessibility, aesthetics, functionality, and brand identity. For more info see the [Colors docs page](https://blueprintjs.com/docs/#core/colors). If you have a specific question about the colors maybe we could try to answer it.

**Comment by alberto-f** [comment]
Thanks.
