### ISSUE TITLE
Rename z-indices vars to elevation

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#434]
For consistency with our generic "elevation" concept. Thoughts?

`$pt-z-index-base` -> `$pt-elevation-0`
`$pt-z-index-content` -> `$pt-elevation-1`
`$pt-z-index-overlay` -> `$pt-elevation-2`

**Comment by giladgray** [comment]
this change does not seem valuable. having `-z-index-` in the name is analogous to `-color` and `-shadow` elsewhere: hints at the variable type and where it should be used.
