### ISSUE TITLE
v3.32.0 - build failed - No exported member 'IResizeEntry'

### ISSUE THREAD

**Issue by ptgamr** [palantir/blueprint#4340]
After upgrading to 3.32.0, wepack is nolonger be able to build due to some missing types:

```
TS2305: Module '"../../../../node_modules/@blueprintjs/core/lib/esm"' has no exported member 'IResizeEntry'.
    20 |   Hotkey,
    21 |   ResizeSensor,
  > 22 |   IResizeEntry,
       |   ^^^^^^^^^^^^
    23 |   Tag,
    24 | } from '@blueprintjs/core'
```

Perhaps something is missing after the TS 4.0 upgrade?

**Comment by adidahiya** [comment]
Actually that was a regression introduced by https://github.com/palantir/blueprint/commit/bd3efea2a757be823677efbaeab9075d9602a5d4, thanks for reporting

**Comment by ptgamr** [comment]
Thanks for the quick fix! @adidahiya
