### ISSUE TITLE
Tabs should have a fallback option

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#4344]
#### Environment

- __Package version(s)__: 3.32.1

#### Feature request

I am using the tabs component controlled through the url with react-router-dom. However, if the user tries to go to a route for a tab that does not exist then the tabs component does not render anything. It would be nice to have it fallback to a not found page.

https://codesandbox.io/s/blueprint-tab-fallback-6ubo2?file=/src/index.tsx

try clicking the link to tab 3 in the codesandbox.

Maybe there is a different or better way to achieve what I am trying to do.

**Comment by adidahiya** [comment]
This is something you need to implement in your application logic; a data-agnostic UI component like `<Tabs>` will not handle this for you. In your specific code sandbox, you should be validating `section` before sending it to `selectedTabId` (choose a static "fallback" tab id if the section does not match any of the known tabs).
