### ISSUE TITLE
Incorrect references to browser global `name`

### ISSUE THREAD

**Issue by RyanCavanaugh** [palantir/blueprint#4348]
https://github.com/palantir/blueprint/blob/ea31b1caa73a0f66417f94203073ac50748d0eaf/packages/docs-theme/src/components/typescript/interfaceTable.tsx#L124

https://github.com/palantir/blueprint/blob/ea31b1caa73a0f66417f94203073ac50748d0eaf/packages/docs-theme/src/components/typescript/methodTable.tsx#L119

These appear to be copy-paste errors from other similar methods where `name` was brought in from a destructuring of the method parameter, but that didn't happen here and the `key` is just the `name` property of the global window

**Comment by adidahiya** [comment]
good catch, thanks for the heads up
