### ISSUE TITLE
[Tab] `style` prop is unsupported.

### ISSUE THREAD

**Issue by arsenush** [palantir/blueprint#4355]
#### Context

I am trying to make all tabs same width. So I've calculated width depending on tabs count and passed it to Tab in `style` but for some reasons it is unsupported.

#### Steps to reproduce

```javascript
<Tab style={{width, height...}}/>
```

#### Actual behavior

`Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Tab> & Pick<Readonly<ITabProps> & Readonly<{ children?: ReactNode; }>, never> & Partial<Pick<Readonly<ITabProps> & Readonly<{ ...; }>, "className" | ... 5 more ... | "panelClassName">> & Partial<...>'.`

#### Expected behavior

`Tab` should support `style` prop.

Please let me know if there is some specific reason why `Tab` does't support it.

**Comment by adidahiya** [comment]
Which version are you on? Can you demonstrate using a code sandbox linked from the issue template? It works fine for me in the Blueprint docs application.

**Comment by arsenush** [comment]
Couldn't repro this in your sandbox. Also after doing some environment magic - it works.
Sorry for disturbing.

Closing this issue...
