### ISSUE TITLE
Dialog with lots of content - scroll WITHIN the dialog?

### ISSUE THREAD

**Issue by boazrymland** [palantir/blueprint#4361]
#### Environment

- __Package version(s)__: 3.18.1
- __Browser and OS versions__: Chrome / OS X

#### Question

Hi,

In case we have lots of content going into the dialog body area, we want to have a non elongated dialogs, as we currently have, but rather a scroll to appear **inside** the dialog modal window. 
I know its achievable relatively easy with some CSS but I wanted to check if that is possible today?
See attached screenshot.

Thanks,
Boaz

![Screen Shot 2020-10-07 at 13 45 18](https://user-images.githubusercontent.com/1311936/95321711-1bdc1900-08a4-11eb-9f49-4fb7f7be08ff.png)

**Comment by adidahiya** [comment]
> I know its achievable relatively easy with some CSS

Yes, just set a `max-height` and `overflow-y` on the dialog body:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/723999/95351362-26d87e80-088f-11eb-9786-c6f5d7c3f46a.png">

**Comment by boazrymland** [comment]
> > I know its achievable relatively easy with some CSS
> 
> Yes, just set a `max-height` and `overflow-y` on the dialog body:
> 

that's exactly what we did, which BTW led to a strange bug in which the date picker wouldn't close when a range was selected, thus killing some of our automated tests. I have to admit that haven't checked **exactly** why this is happening. Specifically, if its an issue on the date picker when its put inside a Dialog component, or is it some other styling CSS we have on the datepicker, or the Dialog itself. But, its worth mentioning this so here I am :) 

But anyhow, I think having scrollbars inside the Dialog is better than on the page, UX wise, so please consider this a suggestion/feedback.
