### ISSUE TITLE
Exposing MultiSelect Ref

### ISSUE THREAD

**Issue by mkrkelj1** [palantir/blueprint#4366]
#### Environment

- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome / MacOS Catalina

#### Question

Hi, I'm attempting to use the `MultiSelect` component with `react-hook-form`, but am unable to integrate without access to the ref handler (components like `InputGroup` + others have been easy to integrate as they expose the ref directly w/ the `inputRef`, `elementRef`, etc..). 

I've tried a few different approaches, and there's a `inputRef` prop accessible via the `tagInputProps`, but I haven't been able to grab the ref. Am I missing something obvious? Is there a straightforward way to access the MultiSelect ref handler?

**Comment by ejose19** [comment]
You can use ```react-hook-form``` [controller](https://react-hook-form.com/api/#Controller) for cases where the ref is not exposed.

**Comment by adidahiya** [comment]
Try `<MultiSelect tagInputProps={ inputRef: ... }>`
