### ISSUE TITLE
Using React Hooks

### ISSUE THREAD

**Issue by kewp** [palantir/blueprint#4369]
## Environment

- __Package version(s)__: N/A
- __Browser and OS versions__: N/A

#### Question

Just starting my first big React project and I think this is the best interface library available. My question is if you can use React Hooks with Blueprint, since hooks were introduced in React 16.8? The example code uses classes - is that a limitation?

Thank you.

**Comment by adidahiya** [comment]
You can freely mix component types in React, using class and function components interchangeably. Some Blueprint components have not been completely updated to support all the new paradigms introduced in React 16.8 (like ref objects in some props, for example #4370), but that will not prevent you from using those components in an application which uses functional React components & hooks.

**Comment by kewp** [comment]
That's good to hear. Thank you for your reply
