### ISSUE TITLE
FR: TagInput inputRef support for React ref objects

### ISSUE THREAD

**Issue by kennyjsa** [palantir/blueprint#4370]
#### Environment

- __Package version(s)__: 3.32.0 and later
- __Operating System__: Windows
- __Browser name and version__: Chrome 86.0.4240.75

#### Code Sandbox

https://codesandbox.io/s/priceless-ishizaka-yiykz

#### Steps to reproduce

error on render

#### Actual behavior

Crashes with error
```
TypeError
_b.call is not a function
```

#### Expected behavior

render without crashing

**Comment by adidahiya** [comment]
You are sending the wrong type of value to `inputRef`. This would be checked at compile time if you were using TypeScript. From the props documentation:

```ts
    /** Ref handler for the `<input>` element. */
    inputRef?: (input: HTMLInputElement | null) => void;
```

Adding support for a React 16 style ref _object_ is an open FR.

**Comment by adidahiya** [comment]
fixed by https://github.com/palantir/blueprint/pull/4438
