### ISSUE TITLE
Date Range Picker with Time Input

### ISSUE THREAD

**Issue by RaghulXander** [palantir/blueprint#4380]
#### Environment

- __Package version(s)__: 3.30.1
- __Operating System__: Mac OS
- __Browser name and version__: Chrome, Firefox

#### Steps to reproduce

1. Add a Date Range Picker in a page
2. Add props `timePrecision` as minutes, `usePortal` props as false and required props.
2. Select the Date Range and you can see the date picker closes and doesn't wait for time input

#### Expected behavior

It should actually wait for the time input to be filled or manually closed by user

#### Possible solution

Date Picker open and close should wait for time input if time precision is mentioned

**Comment by adidahiya** [comment]
Do you mean DateRangeInput? It helps if you can demonstrate your exact situation using a fork of the code sandbox linked in the issue template.

**Comment by RaghulXander** [comment]
Sorry i sorted it out we had props to control it `closeOnSelection`
