### ISSUE TITLE
Support for ref objects in NumericInput inputRef prop

### ISSUE THREAD

**Issue by appleneil** [palantir/blueprint#4382]
#### Environment

- __Package version(s)__: 3.31.0

#### Question

I'm trying the following but get a typescript error

```javascript
const inputEl = useRef<HTMLInputElement>(null)

<NumericInput
// other props
            inputRef={inputEl}
          />
```

`TS2322: Type 'RefObject<HTMLInputElement>' is not assignable to type '(ref: HTMLInputElement | null) => any'.`

I've looked at other components (InputGroup) and passing a ref this way works. I've seen the type expected of the `inputRef` prop, but I don't understand how to use it correctly.

Can anyone help please?

**Comment by adidahiya** [comment]
ref objects returned by `useRef` are not yet supported on this component prop. that's clear from the type definition: https://github.com/palantir/blueprint/blob/57b3ad93822f2516c761be24ceb543a585ccb6f5/packages/core/src/components/forms/numericInput.tsx#L93

I'm open to adding support for that, similar to other components (#4354, #4338)

**Comment by appleneil** [comment]
Thanks for the quick reply. Is there a way around this (whilst waiting for fix)?

**Comment by adidahiya** [comment]
Use a function ref, the old pattern for React refs.

**Comment by appleneil** [comment]
Hi @adidahiya I've found a similar problem with the `HTMLSelect`. I updated my core package after this https://github.com/palantir/blueprint/pull/4093 was merged but the problem persists.

**Comment by adidahiya** [comment]
as of https://github.com/palantir/blueprint/pull/4438, all components support both ref objects and callbacks.
