### ISSUE TITLE
Menu inside a Tag Input or alternate way to display grouped multi-select items

### ISSUE THREAD

**Issue by arunmmanoharan** [palantir/blueprint#4385]
#### Environment

- __Package version(s)__:    
    "@blueprintjs/core": "^3.10.0",
    "@blueprintjs/datetime": "^3.19.3",
    "@blueprintjs/select": "^3.6.0",
- __Browser and OS versions__:  Chrome 86.0.4240.75, Windows 10

#### Feature request

Hi, I have a multi-select with groups and looking for a better way to display the selected ones on the screen. I was thinking about having a menu, and each menu-item is a tag-input but unable to find an API which does that. I am also open to other feedback on ideas to display this in a more concise manner.

#### Examples

If you select Orange in Fruit and in color, I prepend the type to the item. But I am looking to display it in the same way as I do in the dropdown.

https://codesandbox.io/embed/react-typescript-forked-dkrb3?file=/src/data.json&codemirror=1

**Comment by adidahiya** [comment]
It looks like you've accomplished what you want in that sandbox:

![image](https://user-images.githubusercontent.com/723999/97326339-49d0cf80-184a-11eb-96f5-594d2b9b155b.png)

By "better way to display the selected ones on the screen", do you mean inside the TagInput? Is `tagRenderer` not sufficient?

**Comment by arunmmanoharan** [comment]
Yeah. I was hoping if I can have a menu inside the tagInput and render the tags as MenuItem's with an X.

**Comment by adidahiya** [comment]
> I was hoping if I can have a menu inside the tagInput and render the tags as MenuItem's with an X.

But... that doesn't make sense in a modular component-based design system. What is the visual/functional difference here? Why render `MenuItem` instead of `Tag`? Is there a design mockup you can share which illustrates what you're trying to achieve?

**Comment by arunmmanoharan** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/4927454/97333370-e185ec00-1851-11eb-9314-f90a830930c9.png)


Lets say I select around 25 items, I want it to be categorised as how the Menu does. I am open to different creative options as well, but the one I showed initially is too cumbersome for me. Clicking on the X in the above image should remove the element. Adding new elements should be added only to this list and not create another Menu.

**Comment by arunmmanoharan** [comment]
Achieved it using QueryList, thanks
