### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by karudo** [palantir/blueprint#4391]
React 17 released already, but peerDependencies contains `"react": "^15.3.0 || 16"`, so there are npm warnings after React is updated

**Comment by adidahiya** [comment]
It's on the 4.0 roadmap. We first need to drop support for 15.x, which is still used in some of our code bases. ETA is roughly EOY.

**Comment by david-raine** [comment]
My project needs React 17 as it has multiple app root elements, so I updated `./node_modules/@blueprintjs/core.package.json` directly with `"react": "^15.3.0 || 16 || 17"` and everything seems to be working well so far.

**Comment by dapetcu21** [comment]
It doesn't need to wait for 4.0. React 17's only breaking change is the moving of event handlers from document root to React root element, which is unlikely to cause problems. It's a stepping stone release for future compatibility.
