### ISSUE TITLE
Show selected items count in Multiselect

### ISSUE THREAD

**Issue by arunmmanoharan** [palantir/blueprint#4392]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Feature request

When I select more than three items in multiselect, I want to display "4 items selected" instead of tags.

#### Examples

https://projects.skratchdot.com/react-bootstrap-multiselect/

Check how optgroups dropdown works.

**Comment by arunmmanoharan** [comment]
@adidahiya @giladgray Any advices?

**Comment by arunmmanoharan** [comment]
Fixed it using QueryList. Thank you.

**Comment by adidahiya** [comment]
Yeah I think QueryList is the way to go if you're trying to achieve some kind of selection UI which is outside our design system.
