### ISSUE TITLE
Timezone "Poland" should not be in the timezone picker

### ISSUE THREAD

**Issue by alfredvaa** [palantir/blueprint#4394]
According to [this](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) list of timezones the timezone "Poland" is deprecated. If using this library in combination with [Luxon](https://moment.github.io/luxon/), Luxon is not recognizing it as a valid timezone. It should be "Europe/Warsaw".

**Comment by adidahiya** [comment]
We get our timezones directly from [moment-timezone](https://momentjs.com/timezone/), so you might want to bring this up there.

**Comment by alfredvaa** [comment]
Ok I'll look into that, thanks!
