### ISSUE TITLE
[Table] v3.8.17 Fails To Build Fresh Install

### ISSUE THREAD

**Issue by tbertrand7** [palantir/blueprint#4395]
#### Environment

- __Package version(s)__: @blueprintjs/table: 3.8.17
- __Operating System__: mac 10.15.7
- __Browser name and version__: Chrome latest

#### Steps to reproduce

1. Install @blueprintjs/table v3.8.17 in a new project.

#### Actual behavior

SassError: no mixin named force-hardware-acceleration
        on line 34 of node_modules/@blueprintjs/table/src/quadrants/_quadrants.scss
        from line 17 of node_modules/@blueprintjs/table/src/table.scss
        from line 2 of main.scss
>>   @include force-hardware-acceleration();

When I download the .zip of v3.8.17 ` @include force-hardware-acceleration();` is still present in `_@blueprintjs/table/src/quadrants/_quadrants.scss`

#### Expected behavior

The project should build.

#### Possible solution

It looks like the latest code has these references removed, but the current release of @blueprintjs/table does not have these changes. Releasing a new patch should fix.

**Comment by adidahiya** [comment]
How / why are you building the table styles yourself? Yes, this change has been committed to `develop`, and no, it has not been released yet.

**Comment by tbertrand7** [comment]
Ah, thank you. That was the problem.

I replaced: '\~@blueprintjs/table/src/table.scss';
With: @import '\~@blueprintjs/table/lib/css/table.css';

That fixed the build issue.
