### ISSUE TITLE
Large tags have unusually large padding

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#4397]
#### Environment

- __Package version(s)__: 3.31.0
- __Operating System__: irrelevant
- __Browser name and version__: same

#### Code Sandbox

https://blueprintjs.com/docs/#core/components/tag (enable the "Large" switch)

#### Steps to reproduce

1. Render a `<Tag large={true} />`

#### Actual behavior

The tag has a height of 36px.

#### Expected behavior

The tag has a height of 30px.

Most inline UI components have a height divisible by `$pt-grid-size` (10px). Regular tags are 20px high, buttons and menu items are and large tags used to be 30px, large buttons are 40px, etc.
Large tags used to have a very similar layout to regular buttons, allowing trivial side-by-side use.
With the changes in #4099 the added vertical padding makes large tags 36px high, which (1) looks odd, there's an unusual amount of vertical padding, and (2) removes the large tag from the divisible-by-10px sizes of most comparable components, making them largely unusable alongside those components.

#### Possible solution

Revert #4099, or make that padding explicitly opt-in.

cc @kmblake

**Comment by invliD** [comment]
@adidahiya Any chance we can prioritize this?

**Comment by adidahiya** [comment]
Looks like the problem is with removable tags, which get a 36px height. Large tags without a remove button are still 30px:

![image](https://user-images.githubusercontent.com/723999/98868698-8bfb3300-243e-11eb-878b-d52dc6355ac4.png)
