### ISSUE TITLE
Adding year-to-date and previous-year-to-previous-year-to-date option to date range filter

### ISSUE THREAD

**Issue by jan00s** [palantir/blueprint#4398]
#### Environment

- __Package version(s)__:  Latest Blueprint version
- __Browser and OS versions__:  Latest Chrome version

#### Feature request

Hi,

one of your clients at Palantir would like to have a predefined year-to-date and previous-year-to-previous-year-to-date option in the date range filter.

#### Examples

Let's say today is November 4th 2020. The year-to-date option would set the boundaries of the filter to 01-01-2020 to 04-11-2020. The previous-year-to-previous-year-to-date option would set the boundaries of the filter to 01-01-2019 to 04-11-2019.

**Comment by adidahiya** [comment]
This is already possible with the `shortcuts` prop on `DateRangeInput`: https://blueprintjs.com/docs/#datetime/daterangeinput

**Comment by jan00s** [comment]
@adidahiya: Thanks for your response! Is it possible to extend the default shortcuts to include those options? The reason being that we are using this dateRangeFilter in Hubble.
