### ISSUE TITLE
ContextMenu imperative usage does not scroll

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#4406]
#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-menu-scroll-rxz1m?file=/src/index.tsx

#### Expected behavior

The window should scroll so that the full menu can be viewed. Should behave like the popover.

**Comment by adidahiya** [comment]
Hmm I'm not sure ContextMenu is really designed for this... usually those menus are pretty short and fit within the vertical viewport. Can you instead try to limit the height of the context menu popover and add `overflow-y: scroll`?
