### ISSUE TITLE
Click on MenuItem closes both Popover and any Alert/Dialog inside it

### ISSUE THREAD

**Issue by kmeshavkin** [palantir/blueprint#4407]
#### Environment

- __Package version(s)__: v3.35.0
- __Browser and OS versions__: 86.0.4240.111

#### Question

Not sure if this is a bug, but currently if you use Menu+MenuItem in Popover and also add Alert/Dialog somewhere inside this Popover, then click on MenuItem, Alert/Dialog that should open after MenuItem click will open and then immediately close. I believe this was also addressed in https://github.com/palantir/blueprint/issues/2735#issuecomment-657389794, but I don't think it was ever solved. At first I though class "Classes.POPOVER_DISMISS_OVERRIDE" could solve this issue, but it doesn't work in that case.

I think one of the solutions here is to make whole Popover controlled, but that would require binding close event to everything (and also handling logic of clicking outside of Popover) except MenuItem, which is not desirable.

I believe this happens because Popover completely unmounts on close, in that case one solution would be not to unmount Popover on close, but hide it, but it looks hacky.

I should note that it's possible to bring Dialogs/Alerts to up so it's not Popover child, but I would really like to find a solution where Dialogs/Alerts can be housed inside Popover.

Here's sample component code:
```javascript
const ContextMenuButton = () => {
  const [isAlertOpen, setAlertOpen] = React.useState(false);

  const content = (
    <>
      <MenuItem text="OpenAlert" onClick={() => setAlertOpen(true)} />
      <Alert isOpen={isAlertOpen}>
        Alert!
      </Alert>
    </>
  );

  return (
    <Popover content={<Menu>{content}</Menu>}>
      <Button text="Open Popover" />
    </Popover>
  );
};
```

Is there any solution to this apart from making Popover controlled or am I missing something?

**Comment by arunmmanoharan** [comment]
You need to pass         shouldDismissPopover={false} to MenuItem

**Comment by adidahiya** [comment]
@kmeshavkin if the `shouldDismissPopover` suggestion by @a2441918 doesn't work, can you please try to demonstrate the issue in a code sandbox (linked in the issue template)?

**Comment by kmeshavkin** [comment]
@a2441918, @adidahiya, thanks, that works well. I need to set it on every menu with popovers, but looks like it's most convenient option when Alert/Dialog located inside Popover.

**Comment by arunmmanoharan** [comment]
@kmeshavkin Or you can just extend MenuItem as a new component and make this prop always false and use this as your MenuItem
