### ISSUE TITLE
table has duplicate row headers and column headers

### ISSUE THREAD

**Issue by likang** [palantir/blueprint#4420]
#### Environment

- __Package version(s)__: 3.8.17
- __Operating System__: macOS 11.0.1
- __Browser name and version__: Chrome 86.0.4240.193 

#### Code Sandbox

Link to a minimal repro : https://blueprintjs.com/docs/#table.basic-usage

#### Steps to reproduce

1. Open developer tools
1. Expand node tree of  `.bp3-table-quadrant-main` `.bp3-table-quadrant-top` `.bp3-table-quadrant-left`

#### Actual behavior

1. MAIN quadrant has body / column headers (duplicate) / table menu (duplicate) / row headers (duplicate)
2. LEFT quadrant has body / column headers (duplicate) / table menu (duplicate)
3. TOP quadrant has body / table menu (duplicate) / row headers (duplicate)

#### Expected behavior

1. MAIN quadrant only shows body
2. TOP quadrant only shows column headers ( and body if it has frozen rows)
3. LEFT quadrant only shows row headers ( and body if it has frozen columns)

#### Possible solution

remove unexpected props of TableQuadrant such as `columnHeaderCellRenderer` `menuRenderer` `rowHeaderCellRenderer` in tableQuadrantStack.tsx, and add css top / left  to quadrant if needed.

**Comment by adidahiya** [comment]
Before we go ahead with a potentially dangerous refactor in #4421, can you describe what problems this duplication is causing for you?
