### ISSUE TITLE
Rename isDisabled to disabled

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#443]
There's still a few instances of `isDisabled` here and there

**Comment by cmslewis** [comment]
Remnants of a golden era. I'm going to miss those helping-verb prefixes.

**Comment by adidahiya** [comment]
+1 to @cmslewis; I also like the helping-verb prefixes. I guess the idea here is that we are mimicking the behavior of the HTML `disabled` attribute so we're trying to be consistent? I could see this going either way, but would get a little worried if we removed _all_ such prefixes from prop names ("should", "use", etc.)

**Comment by llorca** [comment]
What's important is staying consistent. This task is about choosing between `isDisabled` or `disabled` and sticking with it, but if you think there's a larger "do we use verb prefixes" task to look at, happy to file.

**Comment by leebyp** [comment]
Slightly tangential but I wonder if we should just remove `disabled` altogether in some of these components in question; I'm thinking `<Button />`, `<InputGroup />` and explicity say that we're proxying HTML props through to the underlying HTML.

**Comment by giladgray** [comment]
we _do_ do that, but `disabled` exists in the interface so it appears in the documentation. this came up recently in #396 where someone didn't realize that it was supported.

**Comment by llorca** [comment]
I just saw references to `isActive`, does this issue also apply to it?

**Comment by cmslewis** [comment]
@llorca take a look. Are we done with the `isDisabled` => `disabled` transition? Only a few search results left, none of them props:

https://github.com/palantir/blueprint/search?utf8=%E2%9C%93&q=isDisabled&type=

**Comment by llorca** [comment]
looks done indeed
