### ISSUE TITLE
Navigation drawers (Sidebar)

### ISSUE THREAD

**Issue by alfawal** [palantir/blueprint#4437]
#### Feature request

Navigation drawers on the sidebar left/right supportive

#### Examples

Example of Navigation drawers [here](https://vuetifyjs.com/en/components/navigation-drawers/).
A good example of lists styling inside them [here](https://vuetifyjs.com/en/components/lists/#nav).

**Comment by adidahiya** [comment]
Navigation via drawers isn't really part of our design system, but we may consider it in the future. For now we have these two components you may use:

https://blueprintjs.com/docs/#core/components/drawer
https://blueprintjs.com/docs/#core/components/navbar
