### ISSUE TITLE
Rename pt-align-* to pt-position-*

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#444]
Reducing API surface, bringing consistency with current JS positioning APIs

**Comment by adidahiya** [comment]
This might be a little confusing because

1. one could imagine subtle semantic differences between the intention of "alignment" and "position"
2. the JS Position APIs wouldn't actually generate `pt-position-*` classes

Overall this change seems like it provides few benefits.

**Comment by llorca** [comment]
Things using `.pt-align-*`:
- buttons
- button groups
- control groups
- controls
- submenus
- navbar
- `Classes.ts`: `ALIGN_LEFT` and `ALIGN_RIGHT`

Then we have the `Position` enum in `position.ts`.

Separately, in `tetherUtils.ts` we have things like this:
```
export function getTargetAttachment(position: Position) {
    const attachments: {[p: number]: string} = {
        [Position.TOP_LEFT]:     "top left",
        [Position.TOP]:          "top center",
        [Position.TOP_RIGHT]:    "top right",
        [Position.RIGHT_TOP]:    "top right",
        [Position.RIGHT]:        "middle right",
        [Position.RIGHT_BOTTOM]: "bottom right",
        [Position.BOTTOM_RIGHT]: "bottom right",
        [Position.BOTTOM]:       "bottom center",
        [Position.BOTTOM_LEFT]:  "bottom left",
        [Position.LEFT_BOTTOM]:  "bottom left",
        [Position.LEFT]:         "middle left",
        [Position.LEFT_TOP]:     "top left",
    };
    return attachments[position];
}
```

Is there some kind of refactor/reorganization worth doing here?
