### ISSUE TITLE
MultiSlider.Handle className prop doesn't seem to be getting propagated to the rendered element.

### ISSUE THREAD

**Issue by cybae0804** [palantir/blueprint#4440]
#### Environment

- __Package version(s)__: 3.25.0
- __Operating System__: Ubuntu 18
- __Browser name and version__: Brave Version 1.17.73 Chromium: 87.0.4280.67

#### Code Sandbox

Link to a minimal repro: [Here](https://codesandbox.io/s/blueprint-sandbox-forked-hs3fb?file=/src/CoreExample.tsx)

#### Steps to reproduce

1. Provide a classname to a MultiSlider.Handle

#### Actual behavior

The rendered span element does not receive the user provided className.

#### Expected behavior

The rendered span element does receive the user provided className.

#### Possible solution

If you look at the [code for the handle](https://github.com/palantir/blueprint/blob/28d5bcab7daedeabded0004dfb843d8359de9468/packages/core/src/components/slider/handle.tsx#L74), it does indeed receive a className prop and puts it on the span element.

```
className={classNames(Classes.SLIDER_HANDLE, { [Classes.ACTIVE]: isMoving }, className)}
```

However, if you look at the [MultiSlider code, specifically the `renderHandles` function](https://github.com/palantir/blueprint/blob/28d5bcab7daedeabded0004dfb843d8359de9468/packages/core/src/components/slider/multiSlider.tsx#L289), it only passes the preset classNames.

```
className={classNames({
    [Classes.START]: type === HandleType.START,
    [Classes.END]: type === HandleType.END,
})}
```

I may be reading the code wrong, so please feel free to correct me.

**Comment by adidahiya** [comment]
Your assessment is correct, this looks like a bug.
