### ISSUE TITLE
Cannot install demo app on Windows 10

### ISSUE THREAD

**Issue by sgreinert** [palantir/blueprint#4444]
#### Environment

- __Package version(s)__: 
blueprint 3.17.x / develop
node v12.18.3
npm 6.14.6
python 3.9 / 3.8.5

- __Browser and OS versions__: 
Firefox 83.0 (64 bit), Win 10 Pro X64

#### Question

After having downloaded the repo (tried different versions), I started "yarn" at repo base and got:

yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "typedoc@0.14.2" is incompatible with requested version "typedoc@^0.15.0-0"
warning Resolution field "js-yaml@3.13.1" is incompatible with requested version "js-yaml@~3.6.0"
[3/5] Fetching packages...
warning better-handlebars@0.1.1: The engine "atom" appears to be invalid.
warning language-less@0.34.3: The engine "atom" appears to be invalid.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > stylelint-config-palantir@3.1.1" has unmet peer dependency "stylelint@^^8.0.0 || ^9.0.0".
warning "stylelint-config-palantir > stylelint-config-standard@18.3.0" has unmet peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
warning "stylelint-config-palantir > stylelint-order@0.8.1" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0".
warning "stylelint-config-palantir > stylelint-scss@2.5.0" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0".
warning "stylelint-config-palantir > stylelint-config-standard > stylelint-config-recommended@2.2.0" has unmet peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
warning " > stylelint-scss@3.8.0" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0 || ^10.0.0".
warning " > @blueprintjs/core@3.17.2" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/core@3.17.2" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/test-commons@0.9.0" has unmet peer dependency "react@>=15.3.0".
warning " > @blueprintjs/tslint-config@1.8.1" has unmet peer dependency "tslint@^5.12.1".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/core > sass-inline-svg@1.2.0" has unmet peer dependency "node-sass@^4.5.3".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/core > webpack-cli@3.3.2" has unmet peer dependency "webpack@4.x.x".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/docs-app > webpack-dev-server@3.4.1" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/karma-build-scripts > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/karma-build-scripts > karma-webpack@4.0.2" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has incorrect peer dependency "react@^15.5.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has unmet peer dependency "react-dom@^15.5.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.0" has unmet peer dependency "react-test-renderer@^15.5.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/test-commons > enzyme-adapter-react-16@1.13.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/tslint-config > tslint-plugin-prettier@2.0.1" has unmet peer dependency "tslint@^5.0.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/tslint-config > tslint-react@3.6.0" has unmet peer dependency "tslint@^5.1.0".
warning "workspace-aggregator-e1dcc804-aac6-4684-b053-659dc5dcbcb7 > @blueprintjs/docs-app > webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
[5/5] Building fresh packages...
[1/7] ⠈ command-join
[2/7] ⠈ node-sass
[6/7] ⠈ oniguruma
[7/7] ⠈ tree-sitter-typescript
error C:\...BLUEPRINT\blueprint-release-3.17.x\node_modules\oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\....BLUEPRINT\blueprint-release-3.17.x\node_modules\oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\....python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\...node.exe" "C:\\...BLUEPRINT\\blueprint-release-3.17.x\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...BLUEPRINT\blueprint-release-3.17.x\node_modules\oniguruma
What have I done wrong?

Please help!
Kind regards
Sigurd

**Comment by adidahiya** [comment]
Looks like you might be using the wrong version of python? I would suggest searching the web for oniguruma installation errors.
