### ISSUE TITLE
Datepicker throws error 'Uncaught TypeError: Cannot read property 'querySelectorAll' of null'

### ISSUE THREAD

**Issue by basslagter** [palantir/blueprint#4446]
I can reproduce every time by clicking on the first of the month. Issue is in dateInput.tsx in 'getLastTabbableElement' where it does not check this.popoverContentEl for null. In the source is already a comment stating "Beware: this.popoverContentEl is sometimes null under Chrome", so I guess this should be fixed here also.

**Comment by adidahiya** [comment]
Please fill out the issue template. This is a duplicate of https://github.com/palantir/blueprint/issues/4399.
