### ISSUE TITLE
Tooltip does not disappear if it contains another tooltip with a button

### ISSUE THREAD

**Issue by derekzx** [palantir/blueprint#4450]
#### Environment

- __Package version(s)__: 3.18.0
- __Operating System__: 10.14.6
- __Browser name and version__: Google Chrome: 86.0.4240.198

#### Code Sandbox

https://codesandbox.io/s/hardcore-wilbur-7pywf?file=/src/index.tsx

#### Steps to reproduce

1. Hover over the disabled button
2. Move mouse away from the button

#### Actual behavior

The tooltip taunts you and refuses to disappear

#### Expected behavior

The tooltip should disappear once I stop hovering over the buttono

**Comment by adidahiya** [comment]
Use an `AnchorButton` instead. This is called out in the docs:

https://blueprintjs.com/docs/#core/components/tooltip.props

<img width="814" alt="image" src="https://user-images.githubusercontent.com/723999/101715548-a76f5300-3a69-11eb-8b3b-708fddd8fe98.png">

https://blueprintjs.com/docs/#core/components/button

<img width="813" alt="image" src="https://user-images.githubusercontent.com/723999/101715564-b0602480-3a69-11eb-9f83-6a7dc4b59f9d.png">
