### ISSUE TITLE
Popover for Select goes fullscreen

### ISSUE THREAD

**Issue by fakabbir** [palantir/blueprint#4467]
#### Environment

- __Package version(s)__: v3
- __Operating System__: Windows 10
- __Browser name and version__: Chrome (87.0.4280.88)

#### Code Sandbox
https://codesandbox.io/s/blueprint-issue-select-c6qm9

#### Steps to reproduce
Click in Select Button

#### Actual behavior
Select option takes the whole screen to show the available options

#### Expected behavior
Only about 10 items should be visible in on the screen with scrollable small container

#### Possible solution
Issues with CSS could be checked

**Comment by adidahiya** [comment]
You forgot to include `blueprint-select.css`. You can see it's imported in the code sandbox linked from the issue template and README.
