### ISSUE TITLE
Navbar.Group Alignment.CENTER is not working

### ISSUE THREAD

**Issue by MohammedSalameh** [palantir/blueprint#4468]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.36.0
- __Browser and OS versions__: Firefox 84.0.1 (64-bit) | Windows 10 build 19041

#### Question
Navbar Alignment functionality doesnt work as intended. 

Navbar Group in the center is being aligned left and filled out to the right, pushing the RIGHT navbar group out of bounds. 

Imgur link to issue: [pic](https://imgur.com/a/61fMNkN)

Codesandbox: https://codesandbox.io/s/blueprint-reactjs-9n6bz

`
<Navbar fixedToTop={true}>

      <Navbar.Group align={Alignment.LEFT}>
          <Button className="bp3-minimal" icon="home" text="Home" />
          <Button className="bp3-minimal" icon="document" text="Files" />
          <Navbar.Divider/>
      </Navbar.Group>

      <Navbar.Group align={Alignment.CENTER}>
          <Navbar.Heading>
              Center
          </Navbar.Heading>
      </Navbar.Group>

      <Navbar.Group align={Alignment.RIGHT}>
          <Navbar.Divider/>
          <Button className="bp3-minimal" icon="user" text="User" />
          <Button className="bp3-minimal" icon="cog" text="Settings" />
      </Navbar.Group>
      
</Navbar>
`

**Comment by adidahiya** [comment]
Can you please demonstrate the issue with a code sandbox (linked from the issue template)? That will make debugging much faster.

**Comment by MohammedSalameh** [comment]
Absolutely: 
https://codesandbox.io/s/blueprint-reactjs-9n6bz

**Comment by adidahiya** [comment]
I just realized that `Alignment.CENTER` is not supported for NavbarGroup. There's no styling for it yet. Open to PRs to fix this.

**Comment by kefd** [comment]
I have the same problem.. want to code this feature how i do it?

**Comment by adidahiya** [comment]
@kefd this will be addressed by #4474 in v4.0

**Comment by kefd** [comment]
@adidahiya when release v4.0?
