### ISSUE TITLE
Need help for Simple Icons integration

### ISSUE THREAD

**Issue by miZyind** [palantir/blueprint#4470]
#### Question

I really like this package so I suggested [Simple Icons](https://github.com/simple-icons/simple-icons) add an icon for BlueprintJS.
This is the corresponding [issue](https://github.com/simple-icons/simple-icons/issues/3510) I opened before.
However, as the member of Simple Icons said, it's hard to determine BlueprintJS's primary color.
Would you like to provide me the primary color hex code so that I can contribute to that package? Thanks!

**Comment by adidahiya** [comment]
We don't have a project logo which is easily suitable for monochrome usage like the ones I see in the [simple icons gallery](https://simpleicons.org/). Not sure how you would adapt ours for that. But if I had to pick a primary color I'd go with [`@blue3`](https://blueprintjs.com/docs/#core/colors), #137cbd.

**Comment by adidahiya** [comment]
Strike that -- I realized we have a monochrome logo right here, use this one: https://github.com/palantir/blueprint/blob/493f27bdaf6fd26ded7e07e607bc3df01211080a/packages/docs-app/src/components/logo.tsx#L20

**Comment by miZyind** [comment]
I've created a [Corresponding PR](https://github.com/simple-icons/simple-icons/pull/4729) based on your suggestion. Thanks for your support adidahiya!
