### ISSUE TITLE
Date range selector resets year

### ISSUE THREAD

**Issue by youssefarizk** [palantir/blueprint#4477]
Hi,

I have a date range selector in my application, where the workflow involves selecting dates in the future.
To repro the bug, you can do the following:
1. select a start date that is in the past (let's say 1/12/2020)
2. select an end date that is in the future (let's say 31/3/2021), but using the Year dropdown to select 2021, followed by the Month dropdown to select March.
3. When I selects March, the year dropdown reverts to 2020, when it should stay to 2021.

AFAICT this is a bug and should probably be fixed at some point.

Thanks

**Comment by adidahiya** [comment]
Can you please demonstrate the issue with a code sandbox? It's linked from the issue template and makes debugging a lot faster.

It sounds like you have this option enabled which will constrain the picker to show contiguous months:
![image](https://user-images.githubusercontent.com/723999/104347463-a4370f00-54ce-11eb-9ae2-701069f8b22e.png)
