### ISSUE TITLE
Crashing when using Popover popoverRef props

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#4485]
#### Environment

- __Package version(s)__: 3.36.0
- __Operating System__: Mac OS Big sur
- __Browser name and version__: Chrome 87

#### Code Sandbox

https://codesandbox.io/s/modest-tree-hww7h?file=/src/App.js

#### Actual behavior

Trying to add ref to popover via `popoverRef` property that should allow us to use a ref with `Popover`. But when setting this property the add crash with the following error `_b.call is not a function`. You can see in live the error throwing when setting popoverRef via CodeSandbox link above

#### Expected behavior

Not crashing when this props is set with a valid ref.

**Comment by adidahiya** [comment]
A `React.Ref` is not allowed for that prop. The type must be a ref callback, this is documented in the props table: https://blueprintjs.com/docs/#core/components/popover.props

However, this prop was changed recently in https://github.com/palantir/blueprint/pull/4438, so you should be able to use `React.Ref` in the next Blueprint release (expected this week).
