### ISSUE TITLE
Reposition popover if target moves

### ISSUE THREAD

**Issue by synapse** [palantir/blueprint#4493]
#### Environment

- __Package version(s)__: @blueprintjs/core 3.38.0
- __Browser and OS versions__: Electron 8.0.0

#### Question
Is there a way to make the popover stick to its target element? Seams to be working when scrolling but not when dynamically the target is pushed or pulled (check GIF below).

![](https://i.imgur.com/6wXs0cn.gif)

**Comment by adidahiya** [comment]
@synapse this may be fixed with the newly released Popover2, can you test it out? see the release notes [here](https://github.com/palantir/blueprint/wiki/3.x-Changelog#january-21-2021). I'm updating the docs site now to reflect the new package.

**Comment by synapse** [comment]
Hey, @adidahiya I've just installed and using Popover2. It seems that it's still not moving along with its target element. Do I need to set any prop in particular. I'm using it like so:

```
<Popover2
    content={<TagsPicker {...this.props} />}
    placement={Position.TOP}
>
    {children}
</Popover2>
```

PS: there's a small stagger when closing
![](https://i.imgur.com/WlwBlQj.gif)

**Comment by olegshilov** [comment]
@synapse hi. seems like in the next release of Popover2 this behavior would be fixed.
BTW it seems to me that the user experience would be better if the add tag button was at the beginning. it seems that cognitive load increases when you start to follow the popover moving on the screen with your eyes

**Comment by synapse** [comment]
hey @olegshilov, thanks for the idea of placing the button at the beginning! 👍
