### ISSUE TITLE
Popover did not close by escape key

### ISSUE THREAD

**Issue by olegshilov** [palantir/blueprint#4496]
#### Environment

- __Package version(s)__: 3.38.1
- __Operating System__: macOS Big Sur 11.1
- __Browser name and version__: Google Chrome 88.0.4324.96

#### Code Sandbox

You can see this behavior at your docs site https://blueprintjs.com/docs/#core/components/popover

#### Steps to reproduce

1. Choose `Text` at example content select
2. Enable `Can escape key close` switcher
3. Open popover by clicking to `Popover target` button
4. Press the `Escape` button

#### Actual behavior

Popover did not close

#### Expected behavior

Popover dismissed

**Comment by adidahiya** [comment]
duplicate of #4300

**Comment by tjmcdonough** [comment]
This still happens even on your documentation https://mantine.dev/core/popover.

Name | Type | Description
-- | -- | --
`closeOnEscape` | `boolean` | `Determines whether dropdown should be closed when Escape key is pressed, true by default`
