### ISSUE TITLE
Dialog goes over sticky header in documentation

### ISSUE THREAD

**Issue by leebyp** [palantir/blueprint#450]
As shown:

<img width="789" alt="screen shot 2017-01-10 at 17 36 50" src="https://cloud.githubusercontent.com/assets/6375593/21831820/8fb48624-d75b-11e6-8939-2f749492725a.png">

**Comment by llorca** [comment]
Not a problem, dialogs have a higher z-index than anything else on purpose. I do wonder if it's that useful to show a static dialog without its backdrop

**Comment by leebyp** [comment]
It's useful to see what the CSS API produces inline as a quick reference without needing to click the button in the JS API. The dialog should have a high z-index in general, but I don't think it should specifically for this purpose in the documentation, and we should override it. It just looks bad when you're scrolling through the docs.

**Comment by giladgray** [comment]
_fix it ben_ https://github.com/palantir/blueprint/blob/master/packages/docs/src/styles/_sections.scss#L254-L264
