### ISSUE TITLE
Icon component cannot accept ARIA `role` prop

### ISSUE THREAD

**Issue by markerikson** [palantir/blueprint#4500]
#### Environment

- __Package version(s)__: 3.38
- __Operating System__: RHEL7 (not relevant)
- __Browser name and version__: Firefox 78 (not relevant)

#### Code Sandbox

N/A

#### Steps to reproduce

1. Try to render `<Icon icon="cross" role="image" />`

#### Actual behavior

TypeScript fails to compile because the `Icon` component does not accept a `role` prop.

#### Expected behavior

The `Icon` component would pass through `role` to the underlying `<svg>` or `<span>`

#### Possible solution

`Icon` is currently defined as using `React.DOMAttributes<HTMLElement>>`:

https://github.com/palantir/blueprint/blob/26351ca79595ebaf633c57b1beadc37a9f2d62b6/packages/core/src/components/icon/icon.tsx#L90

Per the React TS types, `role` is part of the `HTMLAttributes` interface, which extends `DOMAttributes`:

```ts
    interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
        // React-specific Attributes
        defaultChecked?: boolean;
        defaultValue?: string | number | ReadonlyArray<string>;
        suppressContentEditableWarning?: boolean;
        suppressHydrationWarning?: boolean;

        // Standard HTML Attributes
        accessKey?: string;
        // omit

        // WAI-ARIA
        role?: string;

        // omit
    }
```

Perhaps it should be switched over to use `HTMLAttributes` instead?

**Comment by adidahiya** [comment]
@markerikson that looks like a fair assessment. open to PRs, this should be a trivial change. thanks for filing the issue.

**Comment by ChristianIvicevic** [comment]
I'll look into this in the coming days since we need this for our own project right now.
