### ISSUE TITLE
Popover2 tabindex

### ISSUE THREAD

**Issue by dlech** [palantir/blueprint#4502]
#### Environment

- __Package version(s)__: "@blueprintjs/popover2": "^0.1.1",
- __Operating System__: Ubuntu 20.04
- __Browser name and version__: Chromium Version 88.0.4324.96 (Official Build) snap (64-bit)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-146cf?file=/src/CoreExample.tsx

The example has been modified to add `Tooltip2` around the *Core Sandbox* buttons.

#### Steps to reproduce

1. click on a blank part of the browser
1. press tab on the keyboard to focus the buttons
1. notice that each button is focused twice

#### Actual behavior

Each button is focused twice, once for the button element and once for the tooltip element.

#### Expected behavior

The buttons should only be focused once.

#### Possible solution

Don't apply tabindex to the tooltip element if child already has tabindex or make it configurable.

**Comment by adidahiya** [comment]
Thanks for taking the new package for a spin. Good catch, I'll fix this ASAP.

**Comment by adidahiya** [comment]
Fix open in PR #4512

**Comment by dlech** [comment]
https://user-images.githubusercontent.com/963645/107266587-58af4c80-6a0b-11eb-9922-7811682fdac8.mp4
