### ISSUE TITLE
Tooltip does not close if focus is triggered by keyboard but removed mouse

### ISSUE THREAD

**Issue by dlech** [palantir/blueprint#4503]
#### Environment

- __Package version(s)__:  @blueprintjs/core@3.38.2, @blueprintjs/popover2@0.2.0
- __Operating System__: Ubuntu 20.04
- __Browser name and version__: Chromium Version 88.0.4324.96 (Official Build) snap (64-bit), Firefox 85.0

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-146cf?file=/src/CoreExample.tsx

The example has been modified to add `Tooltip2` around the *Core Sandbox* buttons.

FWIW, the same happens with the deprecated `Tooltip`.

#### Steps to reproduce

1. click on a blank part of the browser
1. press tab on the keyboard to focus the buttons
1. wait for one second for the tooltip to appear
2. click on a blank area of the browser to remove the focus from the button

#### Actual behavior

The tooltip stays open

#### Expected behavior

The tooltip should close since the focus is lost

#### Possible solution

?

**Comment by dlech** [comment]
Once you get the hang of it, you can end up with this:

![image](https://user-images.githubusercontent.com/963645/105908059-63211d80-5feb-11eb-96a9-6ed7f3f7ce03.png)

**Comment by adidahiya** [comment]
Fix open in PR #4512

**Comment by dlech** [comment]
This issue still exists. I have updated the sandbox to popover2@0.2.0 and the problem is still reproducible.

**Comment by dlech** [comment]
https://user-images.githubusercontent.com/963645/107265649-20f3d500-6a0a-11eb-9bec-16f6600b68b8.mp4

**Comment by dlech** [comment]
https://user-images.githubusercontent.com/963645/107266628-66fd6880-6a0b-11eb-9ddb-4225f8a2c927.mp4

**Comment by adidahiya** [comment]
@dlech did you also upgrade the core package? there was a change made there targeting this issue.

**Comment by dlech** [comment]
yes, I upgraded all packages in the sandbox

**Comment by dlech** [comment]
> #### Possible solution
> 
> ?

Would it work to use onfocusout instead of onblur?

**Comment by adidahiya** [comment]
I made an updated sandbox to verify that it is still a bug: https://codesandbox.io/s/blueprint-sandbox-forked-eiv42?file=/src/CoreExample.tsx

In fact you can repro it on the Tooltip2 docs page, as I mentioned in https://github.com/palantir/blueprint/pull/5080#issuecomment-1006904602
