### ISSUE TITLE
Context menu cannot use any context provider. 

### ISSUE THREAD

**Issue by abouolia** [palantir/blueprint#4517]
Why context menu cannot use any context providers or react hooks that application depend on, e.g. useIntl or redux dispatches to open some alerts or dialogs, actually context menu just a component that returns JSX then rendering on body, any solutions or suggestions to this issue?

**Comment by adidahiya** [comment]
I just merged `ContextMenu2`, which is simpler than its predecessor and should "just work" with hooks & React context. Will be available in a release this week: https://github.com/palantir/blueprint/pull/4524
