### ISSUE TITLE
 MultiStepDialog does not allow customization of back button

### ISSUE THREAD

**Issue by vilmosioo** [palantir/blueprint#4518]
#### Environment

 Package version(s): 3.38.0
 Operating System: macOS 10.15
 Browser name and version: All browsers

#### Link to a minimal repro: 

https://blueprintjs.com/docs/#core/components/dialog.multistep-dialog
 
#### Steps to reproduce

 MutliStepDialog provides a nextButtonProps prop for controlling props passed to the next button, but not the back button. This would be useful in processes that have a step that you can't go back from, such as a confirmation screen.
 
#### Actual behavior
 Can't control disabled behaviour of 'back' button in MultiStepDialog.
 
 #### Expected behavior
 MultiStepDialog has a backButtonProps prop for controlling props passed to the back button.
 
 #### Possible solution
 Add a backButtonProps prop that controls props passed to the back button.

**Comment by yuchristina** [comment]
This would be very helpful. I am encountering the same problem -- would like disable and style back button.

**Comment by adidahiya** [comment]
@yuchristina what kind of styling are you hoping to do? Is button `intent` sufficient?

**Comment by yuchristina** [comment]
@adidahiya  In terms of styling, I want to be able to use the small button. Most importantly, however, I would like to conditionally disable the button so exposing props as you have done for the final and next button would be great.
