### ISSUE TITLE
portalClassName breaks with empty string

### ISSUE THREAD

**Issue by jmuzsik** [palantir/blueprint#4519]
#### Environment

- __Package version(s)__:  Most recent
- __Operating System__:  Mac
- __Browser name and version__:  Google beta

#### Code Sandbox

``` js
// Some portal component (Dialog, Popover, etc.):
...
portalClassName={theme}
...
// Update theme somewhere in the app:
setSettings({
    ...settings,
    theme: theme === '' ? 'bp3-dark' : '',
});
```

#### Steps to reproduce

Shown above, global state for theme with two values ('') and ('bp3-dark')

#### Actual behavior

``` js
// Line 112 - 117 in blueprint/packages/core/src/components/portal/portal.tsx

        if (this.portalElement != null && prevProps.className !== this.props.className) {
            if (prevProps.className !== undefined) {
                this.portalElement.classList.remove(prevProps.className);
            }
            maybeAddClass(this.portalElement.classList, this.props.className);
        }

```

Here, the app breaks at line 114. Why? Because prevProps.className === '' rather than undefined and '' classList.remove breaks on ''.

Proof:

<img width="1440" alt="Screenshot 2021-02-05 at 12 03 42 AM" src="https://user-images.githubusercontent.com/29470576/106992103-af840000-6745-11eb-8fbe-369f56fb1571.png">

#### Expected behavior

Either it handles the empty string or a better error message... something like you cannot input an empty string into the portalClassName (especially when you are utilising a button that switches the theme). I fixed it by using 'bp3-dark' and 'light' but this is not ideal as i'm adding a useless class.

#### Possible solution

Mentioned above. I'd do it myself but the build process is quite time-consuming. Just want to put this out there as I wasted quite a bit of time confused about this and the solution is very simple.

Thanks, jerry

**Comment by adidahiya** [comment]
Ok... I agree the code could be a little more resilient... but why not use `undefined` instead of `""`? I can't imagine why empty strings would feel better semantically or more "correct" than `undefined` in this kind of use case.

**Comment by jmuzsik** [comment]
Well, the thought stems from the simplest use case of modifying className's through react - like in some form of component in which a drawer opens and you change the className based on if it is open or not

something like this:
```js
className={`${isOpen ? "drawer-open" : ""}`}
```

where you would use an empty string as if you do, for example, this:
```js
className={`${isOpen && "drawer-open" }`}
```

you get undefined as a class, which i think is something you intuitively want to avoid.

That's, I suppose, the reason of my initial thinking, but tbh i used code from the [docs site](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/components/blueprintDocs.tsx#L27-L28) where theme is set to bp3-dark or an empty string and then set in the proper location (i suppose either at the top level of the app or within a portal).

Though looking at some of the examples, it is done different than i did, in that it is set [in className rather than portalClassName](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/dialogExample.tsx#L57-L58).

I did it in portalClassName as it was at a higher level (which I don't think is exactly unreasonable?). Though, this does show that className in a component handles passing an empty string while portalClassName does not, which is likely not ideal.

**Comment by adidahiya** [comment]
```
className={`${isOpen && "drawer-open" }`}
```

I've never really seen this syntax before. I would write it as `className={classNames({ "drawer-open": isOpen })}`.

This could be a bit of a subjective preference, but I don't think of `undefined` as something "you intuitively want to avoid". It's a useful feature of the language. Empty strings are much less intuitive IMO.

Still open to PRs to make `portalClassName` more resilient. Or I may get around to fixing it eventually.

**Comment by jmuzsik** [comment]
Suppose I never exactly worked with the classNames utility - i should start using it, and i meant you'd want to avoid undefined being a class name.

Also, it doesn't break with an empty string, but rather breaks if it is first set as an empty string and then changed to another className (if you want to make the title a bit more exact). Thanks
