### ISSUE TITLE
Tooltip not closing on disabled button

### ISSUE THREAD

**Issue by synapse** [palantir/blueprint#4520]
#### Environment

- __Package version(s)__: 3.38.2
- __Operating System__: macOS Catalina 10.15.6
- __Browser name and version__: Electron 8+

#### Code Sandbox
[this code sandbox](https://codesandbox.io/s/blueprint-sandbox-forked-08tf9)

#### Steps to reproduce
1. Create a disabled button
2. Add a Tooltip component

#### Actual behavior
Tooltip not closing when blurring a disabled button. Same issue with Tooltip2

![](https://i.imgur.com/cT4jgks.gif)

#### Expected behavior
The tooltip should close.

**Comment by adidahiya** [comment]
[see docs](https://blueprintjs.com/docs/#core/components/button)

![image](https://user-images.githubusercontent.com/723999/107247027-de78cb00-69fe-11eb-9c11-5ef2520518ea.png)

**Comment by papscript** [comment]
So why it works at the first place? Shouldn't it also prevents initial tooltip opening?
