### ISSUE TITLE
Tooltip2+Button selection tabindex issue

### ISSUE THREAD

**Issue by dlech** [palantir/blueprint#4521]
Follow up to #4502

#### Environment

- __Package version(s)__: @blueprintjs/popover2@0.2.0
- __Operating System__: Ubuntu 20.04
- __Browser name and version__:  Firefox 85.0

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-146cf?file=/src/CoreExample.tsx

#### Steps to reproduce

1. click on a blank part of the browser
1. press tab on the keyboard to focus the buttons
1. notice that the selection indicator is rendered behind the buttons instead of in front
2. try pressing spacebar to activate the button

#### Actual behavior

The selection indicator is behind the neighboring buttons. Also, the highlight looks different from the normal button highlight like it is selecting the tooltip rather than the button. And more importantly, the button can't be activated with the keyboard by pressing space.

![image](https://user-images.githubusercontent.com/963645/107263845-dd986700-6a07-11eb-9e6b-1176ecebfd17.png)

#### Expected behavior

The UI should show the normal button selection highlight instead and should respond to keyboard activation.

![image](https://user-images.githubusercontent.com/963645/107264237-5c8d9f80-6a08-11eb-940f-66b8f6b78715.png)

**Comment by seve** [comment]
Comparing the DOM between Popover1 and 2, it looks like the tabindex is attributed to the wrong element:

![image (2)](https://user-images.githubusercontent.com/8716829/111192004-db30ac00-8575-11eb-9e74-e00ffa83a177.png)
![image (3)](https://user-images.githubusercontent.com/8716829/111192017-de2b9c80-8575-11eb-9d6e-30022a44b5db.png)
