### ISSUE TITLE
Popover2 large arrow in FireFox

### ISSUE THREAD

**Issue by ghost** [palantir/blueprint#4529]
#### Environment

- __Package version(s)__: `"@blueprintjs/popover2": "^0.2.0",`
- __Operating System__: `Ubuntu`
- __Browser name and version__: `Firefox 85.0.1 (64-bit)`

#### Code Sandbox

```
<Popover2
        interactionKind="click"
        popoverClassName={Classes.POPOVER2_CONTENT_SIZING}
        placement={"right-end"}
        content={
          <Menu className={....}>
            <Button  ... className={Classes.POPOVER2_DISMISS}>...</Button>
            <Button  ... className={Classes.POPOVER2_DISMISS}>...</Button>
          </Menu>
        }
      >
        <Button icon={"list"} />
      </Popover2>
```

#### Steps to reproduce

1. Open popover by clicking hamburger menu 
2. Observe broken arrow

#### Actual behavior

![image](https://user-images.githubusercontent.com/383295/108206948-5fcf0c80-7127-11eb-8a05-2dcf5f0c75b7.png)

I assume it is an arrow, meant to connect popover visually with clicked element. 

#### Expected behavior
- In Firefox it should be visible and not this big
- In Chrome it should be visible

it "works" in Chromium (arrow not visible at all):
![image](https://user-images.githubusercontent.com/383295/108207858-95c0c080-7128-11eb-986a-fa42a92eb61e.png)

**Comment by adidahiya** [comment]
Please follow the issue template and post a code sandbox link. Did you include the popover2 CSS file?

**Comment by ghost** [comment]
Sorry for late response. Yep, it was missing CSS file. Sorry and thanks a lot for the hint.
