### ISSUE TITLE
Ability to disable onHoverChange event for DateRangeInput

### ISSUE THREAD

**Issue by olegshilov** [palantir/blueprint#4531]
#### Environment

- __Package version(s)__: latest
- __Browser and OS versions__: all

#### Feature request

Hi, I have a small suggestion about date inputs.
I can’t find any way to disable changing input value on date range hover right now. 
Maybe it would be better if `onHoverChange` behavior can be optional for `DataRangeInput`.
As well as maybe it would be cool to add `onHoverChange` effect to `DateInput` where is not working for now

#### Examples
I think it should be something like this

```ts
import { DateRangeInput } from "@blueprintjs/datetime";
 
<DateRangeInput
  {...}
  shouldChangeOnHover={false}
/>
```

**Comment by adidahiya** [comment]
I think this is an intentional choice in the design system and we don't necessarily want to add a prop to customize this behavior without a strong need for it. The hover interaction helps preview what the input will look like once you click on a date.

**Comment by olegshilov** [comment]
@adidahiya ok, I understood. But what about adding `onHoverChange` to `DateInput`?

**Comment by adidahiya** [comment]
@olegshilov what will you use that for? Can you explain your use case in more detail?

**Comment by olegshilov** [comment]
As you mentioned above, for example for this (=
> The hover interaction helps preview what the input will look like once you click on a date.

**Comment by adidahiya** [comment]
@olegshilov yes, that "preview" is built into the component behavior already. So I'm asking what would you use the prop for outside the component? It helps to share more context about your use case.
