### ISSUE TITLE
leftElement inside InputGroup inside ControlGroup is invisible

### ISSUE THREAD

**Issue by awsp** [palantir/blueprint#4535]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "^3.39.0"
- __Operating System__: macOS Big Sur 11.1
- __Browser name and version__: Brave Browser v1.20.103, Firefox: 85.0.2

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-3cr0u

#### Steps to reproduce

1. Create a `ControlGroup` 
2. Create a `InputGroup` with `leftElement`
3. Insert `<Icon icon="tag" />` (Any icon is reproducible)

OR  - 
Just click the forked codesandbox

#### Actual behavior

Following the example from [here](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/inputGroupExample.tsx).
Tag icon should be shown on left element but instead invisible

#### Expected behavior

Icon on left element should be visible. 

#### Possible solution

~~`z-index` needs to be greater than or equal to 3 in order for it to show.~~
When input is in focus state, it has a `z-index` at 14, and therefore icon's `z-index` needs to be greater than or equal to 15 in order for it to show.

![image](https://user-images.githubusercontent.com/2015218/108611447-c9575100-739b-11eb-81cc-adb8a43b3420.png)

![image](https://user-images.githubusercontent.com/2015218/108611420-a5940b00-739b-11eb-89ff-5e42bd3fba9c.png)

**Comment by adidahiya** [comment]
Yeah, looks like a bug, we need to fix some CSS rules and update the [ControlGroup CSS example](https://blueprintjs.com/docs/#core/components/control-group.css) to match what actually gets rendered by the React component.

**Comment by adidahiya** [comment]
@awsp actually, looking at this more closely... why are you using `leftElement` and not `leftIcon`? The docs tell you to use `leftIcon` for icons. You can use either `leftIcon="tag"` or `leftIcon={<Icon icon="tag" />}`.

![image](https://user-images.githubusercontent.com/723999/122967312-55808180-d358-11eb-9ca0-36b245b68902.png)

Despite that, though, I can see that anything put into `leftElement` gets hidden. #4768 is not the right fix, though. I have an alternative fix I will put up for PR soon.

**Comment by awsp** [comment]
@adidahiya 
No particular reason why I had to use leftElement instead of leftIcon. 
I was only following what this example was doing. 
https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/inputGroupExample.tsx#L128

In fact, I was using a different element other than icon in my actual code.
