### ISSUE TITLE
Popover2: Classes

### ISSUE THREAD

**Issue by rully-saputra15** [palantir/blueprint#4539]
#### Environment

- __Package version(s)__:    
"@blueprintjs/core": "3.39.0",
"@blueprintjs/popover2": "0.3.0",
"react": "^17.0.1",
- __Operating System__: Windows 10
- __Browser name and version__: Mozilla Firefox 85.0.2 (64-bit)

#### Actual behavior

This is my first time install popover2 of blueprintjs. When i import the library in my react project 
import {Classes, Popover2} from "@blueprintjs/popover2";

My compiler show error like image below
![image](https://user-images.githubusercontent.com/54345394/108807595-65b96780-75d7-11eb-891e-0e7d3bdfd902.png)

Do my imported path is wrong?

Thank you

**Comment by rully-saputra15** [comment]
![image](https://user-images.githubusercontent.com/54345394/108808079-61417e80-75d8-11eb-9d19-be6f9fa26797.png)
This is the another image

**Comment by adidahiya** [comment]
Hmm, not sure how you got that error, what does your build system look like? Can you repro the issue in a code sandbox or is it just in your local build system? Looking at the published package file structure on unpkg, everything seems to be in order: https://unpkg.com/browse/@blueprintjs/popover2@0.3.0/lib/esm/

**Comment by rully-saputra15** [comment]
There are no missing files in folder blueprintjs popover2 and I'm using yarn to install any package. 

I think the problem just in my local build system and I can't find any sandbox project that implements popover2 for now

is it correct to import the library into my files like the syntax below?
import {Classes, Popover2} from "@blueprintjs/popover2";

thank you @adidahiya

**Comment by adidahiya** [comment]
@rully-saputra15 yes, that's the correct syntax for the import statement

**Comment by rully-saputra15** [comment]
is there any advice to solve this problem?

@adidahiya

**Comment by adidahiya** [comment]
Nope, since I don't know what your build system looks like. It is a bit strange to be importing from `lib/esnext/`, that's generally for advanced users who know what they're doing with their build system. `lib/esm/` is the standard import usage pattern.

**Comment by pcclickbit** [comment]
Hi,

**Comment by pcclickbit** [comment]
Hi,

I just installed Popover2 and I get the same error.
![image](https://user-images.githubusercontent.com/11739293/111818942-5b704d80-88a5-11eb-8351-b859fcbe4f1a.png)

### Changes:
Package:
![image](https://user-images.githubusercontent.com/11739293/111819101-93779080-88a5-11eb-948f-663fc1d16071.png)

Component: Added the Popover2 import, still not using it:
![image](https://user-images.githubusercontent.com/11739293/111819356-d9345900-88a5-11eb-8f24-4423972ebb39.png)

**Comment by pcclickbit** [comment]
In my case the error was in package.json
changed  "typescript": "~3.7.2"
to "typescript": "^3.9.9"
now works fine.
