### ISSUE TITLE
Attach Menu to Button

### ISSUE THREAD

**Issue by Orbyt** [palantir/blueprint#454]
I'm looking for a way to toggle a `Menu` Component with a `Button`. Currently, I can conditionally render the `Menu` by toggling state, but the positioning is off and it does not provide a smooth look. Is there a built in way not mentioned in the documentation to "attach" a `Menu` component to a `Button` to toggle the menu and have it positioned according to the component its attached to?

I am essentially looking for a drop down menu toggled by a button.

**Comment by llorca** [comment]
It sounds like you'd like what you want is a `Menu` inside a `Popover` wrapped around a `Button`, see this example: http://blueprintjs.com/docs/#components.menu.js.dropdown

**Comment by Orbyt** [comment]
Yes, excellent, thank you.
