### ISSUE TITLE
useHotkeys not rebinding global hotkeys

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4551]
@adidahiya thanks for your work on the useHotkeys functionality! Much appreciated. However, as far as I can tell I can't get global hotkey handlers to ever update based on props coming in. I see in the example you have an empty array being passed to useMemo: 
![image](https://user-images.githubusercontent.com/2730609/109366083-60faea80-7847-11eb-8dcc-1194f978c1d2.png)

Is it ever ok to pass a few changing props to that function? 

Here is the use case I'm trying to support but am not quite sure how to do it: 
```js
const [inAssignDefaultsMode, setAssignDefaultsMode] = useState(false);
    const hotkeys = useMemo(
      () => [
        
        {
          global: true,
          combo: "shift+d",
          label: "Toggle Assign Defaults Mode",
          onKeyDown: () => {
            setAssignDefaultsMode(!inAssignDefaultsMode);
          }
        }
      ],
      [inAssignDefaultsMode]
    );

    useHotkeys(hotkeys);
```

Note in the above example I am able to setAssignDefaultsMode to true, but I am never able to toggle it back to false because the onKeyDown handler is never rebound as the global handler. 

When I modified the source code here: 
https://github.com/palantir/blueprint/blob/develop/packages/core/src/hooks/hotkeys/useHotkeys.ts#L133

to pass globalKeys like so: 
```js
useEffect(function () {
        document.addEventListener("keydown", handleGlobalKeyDown);
        document.addEventListener("keyup", handleGlobalKeyUp);
        return function () {
            document.removeEventListener("keydown", handleGlobalKeyDown);
            document.removeEventListener("keyup", handleGlobalKeyUp);
        };
    }, [globalKeys]);
```

then the hotkeys correctly update and my functionality works. 

Did you mean to pass globalKeys there and just mistakenly forget to? Or is there a better pattern for having hotkey handlers that can respond to changes in state/props? 

Thanks! Hope this all makes sense to you.

**Comment by adidahiya** [comment]
@tnrich thanks for taking the new hook for a spin. Pretty sure that's an oversight on my part and the line you linked ([permalink here](https://github.com/palantir/blueprint/blob/88638ffdd908fa59e4c9a01ff2c265c69b91186a/packages/core/src/hooks/hotkeys/useHotkeys.ts#L133)) needs to be changed to add `globalKeys` as a dependency. Will fix this week.

**Comment by tnrich** [comment]
Cool great to hear! I thought that was probably the case but definitely wasn't certain.
