### ISSUE TITLE
Select component has wrong position when wrap it in `overflow: auto`

### ISSUE THREAD

**Issue by lmk123** [palantir/blueprint#4552]
#### Environment

- __Package version(s)__: 3.39.0
- __Operating System__: win10
- __Browser name and version__: Chrome 88

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-nvpx6

#### Steps to reproduce

Click film select.

#### Actual behavior

The position of the popover will always be upward, even if there is enough space below.

![image](https://user-images.githubusercontent.com/5035625/109407039-be627900-79b8-11eb-97d3-1894f3285038.png)

#### Expected behavior

The popover should display downwards.

#### Possible solution

Related issues https://github.com/popperjs/popper-core/issues/648

i tried set `boundariesElement` to `viewport` but it didn't work.

**Comment by lmk123** [comment]
This seems to be a bug in popper.js v1.16.1 https://codesandbox.io/s/misty-worker-30iq0

Is there any way to replace `Poppover` with `Poppover2` in the `Select` component?

**Comment by adidahiya** [comment]
> Is there any way to replace `Poppover` with `Poppover2` in the `Select` component?

@lmk123 this is done in https://github.com/palantir/blueprint/pull/4589. you will get that change in 4.0, which I expect to release an alpha/beta for in the next week.
