### ISSUE TITLE
Large bundle size after importing single component

### ISSUE THREAD

**Issue by mmz15** [palantir/blueprint#4557]
#### Environment

- __Package version(s)__: ^3.39.0

#### Question

I'm trying to import a Button component into my React project. The import cost of that component is ~135kb. Since I assume that the button itself doesn't take 135kb to implement, is there any way to modularize the imports?

<img width="522" alt="Screen Shot 2021-03-03 at 08 49" src="https://user-images.githubusercontent.com/69217396/109815424-9e6fc700-7bfd-11eb-9d7e-c134950c7613.png">

Blueprint's Brotli-compressed size is ~130kb, which is a little too large. Are there any recommendations for decreasing the size? Here's the Bundle Analyzer output, for context:

<img width="819" alt="Screen Shot 2021-03-03 at 08 54" src="https://user-images.githubusercontent.com/69217396/109815887-25bd3a80-7bfe-11eb-8b25-99e97d653378.png">

**Comment by adidahiya** [comment]
Are you using a module bundler which supports tree shaking? That's the first thing to verify. your "index.js + 54 modules" seems to be obfuscating / hiding a lot of information about what's in the bundle.

Currently blueprint bundles all its icon SVG paths together, which can result in a larger than expected bundle size if you're just using one component. This is changing in blueprint v4, see #2193

**Comment by mmz15** [comment]
Thanks for getting back to me. Made a fresh CRA and confirmed that it's the icons:

![image](https://user-images.githubusercontent.com/69217396/110032720-7a4bdd00-7d06-11eb-8b15-f3637beadf5d.png)

Really glad to see v4 coming out. Is there an alpha release? Happy to test if needed.

**Comment by adidahiya** [comment]
@mmz15 no alpha yet, I expect to release one in ~1 week

**Comment by mmz15** [comment]
Sounds good! Very much looking forward.

**Comment by odusseys** [comment]
this seems to still be an issue even after upgrading to 4.x - is this actually fixed ? using create-react-app

**Comment by adidahiya** [comment]
No, unfortunately icon modularity got pushed to v5: https://github.com/palantir/blueprint/wiki/Blueprint-5.0
