### ISSUE TITLE
Table FR: default implementation for copy cells via getCellClipboardData

### ISSUE THREAD

**Issue by bergkvist** [palantir/blueprint#4566]
#### Environment

- __Package version(s)__: "@blueprintjs/table@3.8.24"
- __Browser and OS versions__: Chrome 88.0.4324.150

[The rendered table examples](https://blueprintjs.com/docs/#table.basic-usage) in the documentation does not seem to allow copying the contents to your clipboard (either by Ctrl+C or right-clicking).

#### Feature request

Ability to copy contents from table component so that I can paste them in Google Spreadsheets or Microsoft Excel etc.

#### Example
After highlighting some cells, I want to be able to copy theses contents to my clipboard by pressing Ctrl+C or right-clicking to copy.

![image](https://user-images.githubusercontent.com/410028/110377345-95935100-8054-11eb-8be1-37d09a648110.png)

Then I want to be able to paste them into Google Spreadsheets like this:

![image](https://user-images.githubusercontent.com/410028/110377708-05a1d700-8055-11eb-9464-20738054c8b8.png)

**Comment by adidahiya** [comment]
The docs for this feature are not very discoverable but you can enable the clipboard with the `getCellClipboardData` prop: https://blueprintjs.com/docs/#table/api.table

**Comment by bergkvist** [comment]
Could it make sense to have a default implementation of `getCellClipboardData` that is used if you don't specify anything? Or maybe this would be too "magical"?

**Comment by jgresham** [comment]
I agree that this should be enabled by default.
By default, `<Cell>` child should be returned. If Child is an object, try to convert it to a string?

**Comment by adidahiya** [comment]
> Could it make sense to have a default implementation of `getCellClipboardData` that is used if you don't specify anything? Or maybe this would be too "magical"?

I guess this is theoretically possible, but I don't see a very clean or elegant way to do this right now. Yes we could try to add a default implementation which looks up the cell renderer for each row/col in the selected region and runs the renderer... we'd then have to take that virtual DOM `ReactElement` and render it to a real DOM element to get its `.textContent`. This would probably work but is a bit clunky. On the other hand, it's usually pretty easy for a user to implement a more performant `getCellClipboardData` function.

I'm open to seeing PRs for the kind of implementation I just described, though... maybe it's not as bad as I imagine it to be.

**Comment by bergkvist** [comment]
An idea might be to use something like this to convert React elements into text: 
https://www.npmjs.com/package/react-innertext

**Comment by adidahiya** [comment]
@bergkvist that looks promising! I personally can't prioritize this FR for a little while, but open to PRs in the meantime.
