### ISSUE TITLE
Tooltip not hiding itself when focus is shifted away in IE 11

### ISSUE THREAD

**Issue by rafiazman** [palantir/blueprint#4569]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.40.0
- __Operating System__: Windows 10 Version 1809
- __Browser name and version__: Internet Explorer 11.1577.17763.0

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/#core/components/tooltip

#### Steps to reproduce

1. Open the documentation page for Tooltip
2. Cycle focus through the example tooltip-enabled links with the Tab key

#### Actual behavior

Previous tooltips remain open even though focus has shifted towards the next element.

![image](https://user-images.githubusercontent.com/7603038/111556031-80ee5000-87ee-11eb-88b7-67d3e029f103.png)

#### Expected behavior

Only the currently focused element's tooltip should be visible.

**Comment by rafiazman** [comment]
@adidahiya Would just like to add that this seems to be present with `Tooltip2` as well.

**Comment by adidahiya** [comment]
We're dropping IE11 support in Blueprint v5, so this will not be fixed.
