### ISSUE TITLE
add different nextButtonProps for each Dialog in MultistepDialog

### ISSUE THREAD

**Issue by Kaby-Lake** [palantir/blueprint#4579]
#### Question

I have a MultistepDialog with several sub-dialogs in it, and I want to custom each dialog with different code to define if the nextButton should be `disabled` or not. For now, the only API `nextButtonProps` can just set the global Props for all nextButtons. 

something like this
<img width="629" alt="Screen Shot 2021-03-11 at 10 52 47 PM" src="https://user-images.githubusercontent.com/49022571/110805912-8282ba00-82bc-11eb-82be-0896431e0674.png">

**Comment by adidahiya** [comment]
I think we should have an API that accepts a callback for each step:

```ts
type AllowedButtonProps = Pick<IButtonProps, "disabled" | "text">;

export interface IMultistepDialogProps extends IDialogProps {
    /**
     * Props for the back button.
     */
    backButtonProps?: Partial<AllowedButtonProps> | (step: DialogStepId) => Partial<AllowedButtonProps>;

    /**
     * Props for the next button.
     */
    nextButtonProps?: Partial<AllowedButtonProps> | (step: DialogStepId) => Partial<AllowedButtonProps>;

    // ...
}
```

open to PRs for the above change... or I will get to it some time in April
