### ISSUE TITLE
Table. Copy the contents of Cell to the clipboard.

### ISSUE THREAD

**Issue by ivanmem** [palantir/blueprint#4585]
#### Environment

 "@blueprintjs/core": "^3.41.0",
 "@blueprintjs/table": "^3.8.26",

#### Question

How do I allow the user to select text for copy to clipboard? or maybe there is some other way to make a copy of what's inside the Cell?
I know about the getCellClipboardData property, but it seems too complicated to me. There, only indices go into the input, but the content itself is not. In my implementation, it is impossible to find out by indices which property in the object needs to be copied.

Maybe there is some example of a table wrapper that implements copying to the content buffer?

**Comment by lanzhenw** [comment]
check bodyContextMenuRenderer, it is the right click menu. There is a copy component, click that will copy the actual data to clipboard.

**Comment by xeleoss** [comment]
and how to get data from this current column in this component? I'm interested in textContent.
`<CopyCellsMenuItem context={context} text={'Copy'} getCellData={() => 'what should I write here?'}/>`

**Comment by ivanmem** [comment]
Okay I realized that I would have to get the data by indexes. Thanks.
