### ISSUE TITLE
Popover2 does not get closed on mouseout (hover interaction)

### ISSUE THREAD

**Issue by BaharDev** [palantir/blueprint#4586]
#### Environment

- __Package version(s)__:     "@blueprintjs/core": "^3.38.2",    "@blueprintjs/popover2": "^0.3.0",
- __Operating System__: macOS Catalina
- __Browser name and version__: Chrome Version 89.0.4389

#### Steps to reproduce

1. Creating multiple elements ( in my case 10) as target of popover
2. Fast hovering on them (like a streak)

#### Actual behaviour

Ending up having ghost popovers; I'm using portal and I see in the DOM the popovers have bp3-enter-done and of course not exit-done. I suspected this might be because of the transition timing so I even tried to set the hoverCloseDelay to 0, no dice; tried to set isOpen and make it controlled by setting state on mouseEnter to true and mouseLeave to false; still no dice

#### Expected behaviour
When mouseleave happens on the target; the popover should be closed; also would be nice to be able to call a method to trigger closing popovers.

#### Possible solution

I went through the documentation and noticed the combination of captureDismiss and classes.POPOVER2.DISMISS; however seems that works for the click; would be nice to have for the hover as well

**Comment by adidahiya** [comment]
Please post a link to a code sandbox, this makes debugging much faster.

**Comment by bhajiakbar-varicent** [comment]
@adidahiya Thanks adidhiya sorry that it took so long; so I could solve the issue but it was quite bizarre; the problem was I was passing the content jsx as function const someContent = () => {...
Instead I switched to someContent = (... and it got resolved! honestly I don't understand why one would lead to that issue since both produce jsx, but as long as issue is fixed Im happy, would be nice if you can elaborate on that

**Comment by BaharDev** [comment]
Thanks adidhiya sorry that it took so long; so I could solve the issue but it was quite bizarre; the problem was I was passing the content jsx as function const someContent = () => {...
Instead I switched to someContent = (... and it got resolved! honestly I don't understand why one would lead to that issue since both produce jsx, but as long as issue is fixed Im happy, would be nice if you can elaborate on that

**Comment by adidahiya** [comment]
two different values of type `JSX.Element` and `() => JSX.Element` are not equivalent, and they cannot be used interchangeably unless explicitly specified otherwise in a Blueprint API. in TypeScript, this would be a compile error.
