### ISSUE TITLE
Tooltip2 documentation page not working in IE 11

### ISSUE THREAD

**Issue by rafiazman** [palantir/blueprint#4593]
#### Environment

- __Package version(s)__: @blueprintjs/popover2@0.3.3
- __Operating System__: Windows 10 Version 1809
- __Browser name and version__: Internet Explorer 11.1577.17763.0

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/#popover2-package/tooltip2

#### Steps to reproduce

1. Open the documentation page for Tooltip2
2. Cycle focus through the example tooltip-enabled links with the Tab key

#### Actual behavior

Page turns into a blank white screen.

#### Expected behavior

Underlined text to have a dotted border outline indicating browser focus and a tooltip to appear containing example message.

**Comment by adidahiya** [comment]
I can repro this bug. The fix is pretty simple, we need to add polyfills for IE11 as documented here: https://popper.js.org/docs/v2/browser-support/#ie11
