### ISSUE TITLE
Broken transitions from table loading state to content

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#460]
### Bug report

- blueprintjs 1.5.0
- Chrome 55, Safari 10.0.2, FF 50.1.0

#### Steps to reproduce

- Go to Components > Table (React) > Loading States > Cell 
- Click on `All cells`
- Click on `First Column`

#### Actual Behavior

Chrome:
The ColumnHeaderCells that transition from loading > not loading will have their `div` recreated, resulting in ColumnHeaderCells being unable to fade-in text.

Safari:
Fade in effect doesn't work at all.

Firefox:
Fade-in works as expected on all types of cells.

It's possible that whether or not the `div` that represents a cell is recreated is up to the browser, and not React.

#### Expected Behavior
As cells transition out of the loading state, the text should fade-in.

**Comment by llorca** [comment]
@michael-yx-wu are you addressing this as part of the loading work?

**Comment by michael-yx-wu** [comment]
I'm not really sure how to resolve this issue. It will probably not be a part of https://github.com/palantir/blueprint/pull/452 but instead a follow up PR at a later point.

**Comment by llorca** [comment]
Ok, then should we have transitions at all for right now? Maybe just tackle it properly at a later time? @giladgray thoughts?

**Comment by michael-yx-wu** [comment]
The lack of fade in for header text is fairly unnoticeable and it feels really good to see that table body fade in, so I'd say it's worth it to leave them in.

**Comment by llorca** [comment]
Sure, but it seems that according to the bug report, it works for regular cells but not header cells on Chrome, which doesn't sounds great. Let's look at it together some time and see how it feels 👍

**Comment by tgreenwatts** [comment]
@cmslewis is this still an issue?

**Comment by cmslewis** [comment]
Seems like no.

**Comment by michael-yx-wu** [comment]
Cool, glad to see this is resolved!
