### ISSUE TITLE
[popover2] onClose is triggered twice in controlled mode

### ISSUE THREAD

**Issue by glentakahashi** [palantir/blueprint#4607]
#### Environment

- __Package version(s)__: popover2@0.3.2
- __Operating System__: Big sur 11.2.3
- __Browser name and version__: Chrome 89.0.4389.90

#### Code Sandbox

Minimal repro: https://codesandbox.io/s/onclose-duplicate-bug-lwvrh

#### Steps to reproduce

1. Use Popover2 in controlled state
2. Add `onClose` function
3. Open popover
4. Click outside of popover

#### Actual behavior

onClose is called twice: once for the mouse event, once without an evt (when isOpen is flagged to false)

#### Expected behavior

onClose is only called for the mouseEvent, and no onClose is called for when `isOpen` is changed

**Comment by adidahiya** [comment]
What are you using `onClose` for in controlled mode? Is `onInteraction` not sufficient? Note that this is also a "bug" for `Popover`, so it's not a regression: https://codesandbox.io/s/onclose-duplicate-bug-forked-rgyd9

**Comment by glentakahashi** [comment]
Ah good call, I didn't realized onInteraction would be the better hook to use here. This is fine to close out then
