### ISSUE TITLE
Dialog popup is not centrally aligned in IE 11

### ISSUE THREAD

**Issue by ShaneBarboza** [palantir/blueprint#4608]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.40.0
- __Operating System__: Windows 10 Pro Version 1909
- __Browser name and version__: Internet Explorer Version 11.1139.18362.0

#### Code Sandbox

The behaviour can be seen on the Blueprint docs itself: https://blueprintjs.com/docs/#core/components/dialog.multistep-dialog

#### Steps to reproduce

1. Click on any button that opens a dialog popup box

#### Actual behavior

On IE 11, the box appears horizontally aligned (in the middle),but not vertically aligned (it appears at the top of the page):
![image](https://user-images.githubusercontent.com/31976726/114961293-dc2e6380-9ebc-11eb-94b2-e7cbd338b5f2.png)

#### Expected behavior

The box should appear in the centre of the page.

**Comment by adidahiya** [comment]
Closing because we are no longer supporting IE11 in Blueprint v5.0.
