### ISSUE TITLE
Expandable vertical menu similar to Blueprint docs site

### ISSUE THREAD

**Issue by czetsuya** [palantir/blueprint#4609]
#### Environment

- __Package version(s)__: 3.36
- __Browser and OS versions__: Edge on Windows 10

#### Question

I would like to create an expandable vertical menu similar to your website:
![image](https://user-images.githubusercontent.com/804528/112566242-903a5280-8e19-11eb-803c-b606dab9fa13.png)

Is it doable using the current menu component set? I'm referring to this document https://blueprintjs.com/docs/#core/components/menu but can't seem to figure it out aside from custom CSS.

**Comment by adidahiya** [comment]
It's not a traditional "menu" in the Blueprint design system; it's really just a list of links. We don't have a component for it. You can inspect the docs-theme package to see how the docs navigation menus are built.
