### ISSUE TITLE
Suggestions for making long list of tabs work well on mobile

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4628]
Hey there @adidahiya and others,

We have a settings page in our app that looks like so: 
![image](https://user-images.githubusercontent.com/2730609/114278038-abdd5580-99e2-11eb-9ac6-1deb7869ceab.png)

As you can see it is made up of a vertical tabs component. 

On mobile this set up doesn't look too great: 
![image](https://user-images.githubusercontent.com/2730609/114278149-46d62f80-99e3-11eb-9b94-bf4b481e5ba1.png)

I think I'd like to have it set up in such a way that the tabs could pop in using a Drawer component when a mobile device is detected but it's unclear to me whether this functionality would be possible using the Tabs component. Any thoughts on this or other suggestions? Thanks!

Hope that all makes sense. Thanks!

**Comment by tnrich** [comment]
I was able to hack this together just using css and a button that I'd hide/show based on the screen size. Here's the main media query I used for the CSS hiding/showing of the different elements: 

```css
@media only screen and (max-width: 600px) {
}
```

Closing. Thanks!

**Comment by adidahiya** [comment]
> I'd like to have it set up in such a way that the tabs could pop in using a Drawer component when a mobile device is detected

I think this should be possible, but you'd have to do browser detection in JS and render a different kind of React tree. An approach for this is briefly mentioned in the [documentation](https://blueprintjs.com/docs/#core/components/tabs.tab):

> Omitting `panel` is supported and can be useful when you want the associated panel to appear elsewhere in the DOM (by rendering it yourself as needed).

If you omit the `<Tab panel={...}>` prop, you can conditionally render the panel outside the tabs list. In your case it sounds like the tabs list would be a in Drawer and your panels somewhere else in the app.
