### ISSUE TITLE
Using the Toast component

### ISSUE THREAD

**Issue by Orbyt** [palantir/blueprint#463]
I'm trying to use the `Toast` Component.  I was able to get a Toast to show using the code recommended in the docs:

```javascript
import { Position, Toaster } from "@blueprintjs/core";
 
export const OurToaster = Toaster.create({
    className: "my-toaster",
    position: Position.BOTTOM_RIGHT,
});
```
```javascript
// application.ts
import { OurToaster } from "./toaster";
 
OurToaster.show({ message: "Toasted!" });
```

This does show a basic Toast. However, I'd like to customize the toast further, using various intents (like Intent.WARNING) and other props that are available on `<Toast />` Components. The examples in the documentation seem to focus on the `<Toaster />` component but do not go into detail on how to simply show a `<Toast/>` component.

I did take a look at the [source](https://github.com/palantir/blueprint/blob/master/packages/core/examples/toastExample.tsx) linked on the documentation page, but am not familiar enough with Typscript to answer my question.

I am writing my components in ES6. How can I simply show a `<Toast />` component?

I am aware this issue tracker is probably not the best place for questions, but I was unable to find an available tag on StackOverflow, a gitter chat, or any better place. If there exists a better place to ask these questions, please let me know.

**Comment by imawuman** [comment]
Once you have a `Toast` object, just include the intent as a property similar to the message:
```
OurToaster.show({
  message: "Toasted!",
  intent: Intent.WARNING,
  onDismiss: () => console.log("Dismissed!"
});
```
Docs: http://blueprintjs.com/docs/#components.toaster.js.instance

**Comment by giladgray** [comment]
Thanks @imawuman! That is indeed the correct answer. 

@Orbyt re TypeScript example source: it's just JavaScript. you can literally ignore the type annotations (basically anything after the colons) and it'll read exactly like ES6. cuz that's what it is. see #464 for some more discussion o this.
