### ISSUE TITLE
Is it possible to prevent a blueprint global hotkey from being triggered using stopPropagation?

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4646]
Hey @adidahiya 

It seems like this functionality should be supported but I don't think it is. Here is an example codesandbox where this is illustrated: 

https://codesandbox.io/s/blueprint-sandbox-forked-8y9g4?file=/src/CoreExample.tsx

I would expect when "R" is pressed outside of the input for the global hotkey to be triggered. However, because inside the input I'm calling e.stopPropagation(), I would expect the global hotkey NOT to be triggered (as the global hotkey is being attached to the window.document). Is there a way to have this work as I would expect? It seems counterintuitive right now. 

Thanks!

**Comment by tnrich** [comment]
I don't really understand how this functionality is occurring. It appears to me that the global hotkeys are being bound to the document on this line https://github.com/palantir/blueprint/blob/develop/packages/core/src/hooks/hotkeys/useHotkeys.ts#L127: 
```js
document.addEventListener("keydown", handleGlobalKeyDown);
``` 

As the document is higher in the DOM tree than the input node it would stand to reason that stopping propagation on the keydown on the input node would prevent the document from getting the event. That doesn't seem to be the case however. Not sure why.. Any explanation of what's going on would also be appreciated. 

tHanKs!

**Comment by adidahiya** [comment]
Simplified your example and got it working by using `event.nativeEvent.stopImmediatePropagation()`. Apparently this is required because React synthetic events are registered on the `document`: https://stackoverflow.com/a/24421834/7406866

Forked sandbox: https://codesandbox.io/s/blueprint-sandbox-forked-c3wdg?file=/src/CoreExample.tsx

**Comment by tnrich** [comment]
Thanks @adidahiya that should do it! Closing
