### ISSUE TITLE
4.0.0 Popover2 arrow rendering seems broken

### ISSUE THREAD

**Issue by switz** [palantir/blueprint#4649]
#### Environment

- __Package version(s)__: 4.0.0-alpha.0
- __Operating System__: Mac OS X
- __Browser name and version__: Firefox 88.0b4
- 
#### Steps to reproduce

```
    "@blueprintjs/core": "^4.0.0-alpha.0",                                                            
    "@blueprintjs/icons": "^4.0.0-alpha.0",                                                           
    "@blueprintjs/popover2": "^0.5.0",
```

```
      <Popover2
        content={
          <Menu>
            <Link href="/user/[id]" as={`/user/${me.id}`} passHref>
              <StyledA>
                <MenuItem icon="user" text="Profile" tagName="a" />
              </StyledA>
            </Link>
            <MenuItem icon="log-out" text="Logout" href="/api/logout" onClick={logout} />
          </Menu>
        }
        placement="bottom"
      >
        <div>content</div>
      </Popover2>
```

#### Actual behavior

<img width="217" alt="image" src="https://user-images.githubusercontent.com/990166/115083432-57037880-9ed5-11eb-98ab-1652cf3477fa.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/990166/115083460-6256a400-9ed5-11eb-8cfb-0ad4c04b2e28.png">

#### Expected behavior

Should render an arrow normally.

#### Possible solution

Will follow up if I figure out the root cause; I think the arrow svg might just be broken.

**Comment by tianyu94** [comment]
remove `"@blueprintjs/popover2": "^0.5.0",`

and use `Popover` from `@blueprintjs/core`
