### ISSUE TITLE
[Checkbox] using non-callback inputRef fails with "Cannot add property indeterminate, object is not extensible" at runtime

### ISSUE THREAD

**Issue by vladimir-djokic** [palantir/blueprint#4651]
#### Environment
- __Package version(s)__:
  - @blueprintjs/core 3.42.0
  - react 17.0.2
- __Operating System__: Windows 10 x64
- __Browser name and version__: Microsoft Edge Version 91.0.852.0 (Official build) dev (64-bit)

#### Code Sandbox
https://codesandbox.io/s/blueprint-sandbox-forked-qhg7b

#### Actual behavior
If non-callback ref is used for `inputRef`, **"Cannot add property indeterminate, object is not extensible"** is thrown.

#### Possible solution (workaround)
Use callback ref.

**Comment by adidahiya** [comment]
Your sandbox seems to work fine with the latest version of Blueprint core v3.43.0: https://codesandbox.io/s/blueprint-sandbox-forked-es5qi?file=/src/index.tsx

**Comment by vladimir-djokic** [comment]
Yes, I can confirm that the issue is **not** present in **3.43.0** and **3.44.0**, but present in earlier versions.

**Comment by adidahiya** [comment]
Indeed, I believe it was fixed by https://github.com/palantir/blueprint/pull/4612, released in 3.43.0
