### ISSUE TITLE
Broken link to v3 docs in v4 preview

### ISSUE THREAD

**Issue by JB1905** [palantir/blueprint#4653]
#### Steps to reproduce

1. go to https://blueprintjs.com/docs/versions/4/
2. click on button to change version
3. click on v3 button

#### Actual behavior
I get https://blueprintjs.com/docs/versions/3 - 404 page

#### Expected behavior

I get https://blueprintjs.com/docs/ - latest version

![Zrzut ekranu 2021-04-18 o 16 55 34](https://user-images.githubusercontent.com/28870390/115150035-e8eebb00-a066-11eb-8971-b5502099bdcb.png)
![Zrzut ekranu 2021-04-18 o 16 48 14](https://user-images.githubusercontent.com/28870390/115150037-ea1fe800-a066-11eb-987a-c85ef8cc0704.png)

**Comment by adidahiya** [comment]
Fixed by 0d7ae0f
