### ISSUE TITLE
Incorrect title on version button in docs

### ISSUE THREAD

**Issue by JB1905** [palantir/blueprint#4654]
#### Actual behavior

Visible text `v/versions/4`

#### Expected behavior

Visible `v4`

![Zrzut ekranu 2021-04-18 o 16 47 55](https://user-images.githubusercontent.com/28870390/115150075-20f5fe00-a067-11eb-89b5-59fac39713f9.png)

**Comment by adidahiya** [comment]
Fixed by https://github.com/palantir/blueprint/commit/0d7ae0fbc4cd16161ae09fc56c54aabb92a0701e
