### ISSUE TITLE
Cannot clear selected Date in DateTimePicker

### ISSUE THREAD

**Issue by c-h-** [palantir/blueprint#466]
### Bug report

- __Package version(s)__: dateTime 1.4.0
- __Browser and OS versions__: Chrome 55.0.2883.87

#### Steps to reproduce

1. Add DateTimePicker with the ability to clear selection
```jsx
<DateTimePicker
  datePickerProps={{
    canClearSelection: true,
    showActionsBar: true,
  }}
/>
```
2. Click Clear

#### Actual behavior

`Uncaught TypeError: Cannot read property 'getFullYear' of null`
`getDateTime` in common/DateUtils immediately calls `date.getFullYear()` on its `date` argument, however the value passed to it by `DateTimePicker.handleDateChange` is `null` when the user clicks the clear button.

#### Expected behavior

The plugin clears the selected date and passes the change (value `null`) to the `onChange` DateTimePicker prop.

**Comment by c-h-** [comment]
What I would change is one line of DateUtils, but I'm not sure of side effects from this change.
Old:
```typescript
return new Date(date.getFullYear(), date.getMonth(), date.getDate(),
           time.getHours(), time.getMinutes(), time.getSeconds(), time.getMilliseconds());
```
Recommended:
```typescript
return date === null ? date : new Date(date.getFullYear(), date.getMonth(), date.getDate(),
           time.getHours(), time.getMinutes(), time.getSeconds(), time.getMilliseconds());
```

https://github.com/palantir/blueprint/blob/master/packages/datetime/src/common/dateUtils.ts#L101-L102

**Comment by leebyp** [comment]
@c-h- Good catch! You're on the right track, the problem's a bit deeper which I've addressed in the PR
