### ISSUE TITLE
4.0.0 consider exporting `Hotkeys` again

### ISSUE THREAD

**Issue by bensalilijames** [palantir/blueprint#4668]
We use the `Hotkeys` component in our custom hotkeys dialog (it's basically the same as the default, except with some additional info at the bottom) so we don't need to write a render method to turn the hotkey configs into nice-looking renderable components. However, in 4.0.0-alpha.0 it's not exported from `@blueprintjs/core` anymore.

It would be great if this could be exported again so we don't have to copy-paste the `Hotkeys.tsx` file into our app!

#### Environment

- __Package version(s)__: 4.0.0-alpha.0
- __Operating System__: MacOS 11.2.3
- __Browser name and version__: n/a

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

https://codesandbox.io/s/blueprint-sandbox-forked-yow5w?file=/src/HotkeyExample.tsx

You can see here how we basically use the normal hotkeys dialog, except at the bottom we add some helpful text and a link.

#### Steps to reproduce

1. `import { Hotkeys } from "@blueprintjs/core"`
2. `'"@blueprintjs/core"' has no exported member named 'Hotkeys'. Did you mean 'Hotkey'?ts(2724)`

#### Actual behavior

Cannot import `Hotkeys`.

#### Expected behavior

Import `Hotkeys` is successful.

#### Possible solution

Ideally, `Hotkeys` would be exported, but failing that, we could always remove the custom info in the dialog, or copy-paste the `Hotkeys` component into our app.

**Comment by adidahiya** [comment]
Sure, that sounds pretty reasonable. I can add the export. Until then you can `import { Hotkeys } from "@blueprintjs/core/lib/esm/components/hotkeys/hotkeys"`

**Comment by bensalilijames** [comment]
Thanks! ❤️
