### ISSUE TITLE
PanelStack controlled mode transitions

### ISSUE THREAD

**Issue by ryanyue123** [palantir/blueprint#4686]
#### Environment

- __Package version(s)__: 3.43.0
- __Browser and OS versions__: Google Chrome, macOS Big Sur 11.3

#### Question

In controlled mode, the panel stack doesnt seem like its animating correctly. It currently on has the push animation (pushing a new panel onto the stack); however if I remove a panel from the stack array, it "pushes" the older panel on rather than animating it in from the lefthand side.

**Comment by adidahiya** [comment]
Do you have a link / gif / video demonstrating the issue? That would make debugging much faster.

**Comment by ryanyue123** [comment]
hope this is helpful - when i click the back button, which just pops the latest element off the stack, it animates forward rather than backwards

![Screen Recording 2021-04-29 at 11 14 02 AM](https://user-images.githubusercontent.com/12056123/116598863-34615e80-a8dc-11eb-9d15-81bd883a0363.gif)

**Comment by ryanyue123** [comment]
@adidahiya did you have a chance to look at the video

**Comment by ike-ko** [comment]
@ryanyue123 Were you able to find a solution/workaround to this? Running into the same issue with PanelStack2..

**Comment by invliD** [comment]
@ryanyue123 Are you using PanelStack2 or the old PanelStack? I can confirm this bug on the former, but not the latter.
