### ISSUE TITLE
Can't expand last column in blueprint-table

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#470]
If my table extends to the end of my browser, I can't grab the last column and expand it

**Comment by michael-yx-wu** [comment]
@tgreenwatts is this because the scroll bar is preventing you from clicking the resize component?

**Comment by tgreenwatts** [comment]
Nope, you just can't resize the last column I thought

**Comment by llorca** [comment]
It's because click and drag doesn't scroll the table

**Comment by michael-yx-wu** [comment]
@tgreen you can resize the last column. Try it out on the docs page. But not drag not scrolling the table makes expanding the last column impossible when you're full screen and the last column is at the right edge of your screen

**Comment by tgreenwatts** [comment]
So is there something more we can do here?

**Comment by michael-yx-wu** [comment]
This will probably take a good amount of time but the right thing to do is to enable drag-induced scrolling. That would make this interaction possible. Until then there's nothing we can really do. Let's keep this ticket open though.

**Comment by tgreenwatts** [comment]
I'd successfully resized columns at the end of tables, so I think this is just dependent on where apps put tables
