### ISSUE TITLE
[Popover2] Offset modifier is ignored if arrow is disabled

### ISSUE THREAD

**Issue by vladimir-djokic** [palantir/blueprint#4720]
I tried using modifiers to disable the arrow and make popper offset from the element, however offset is ignored if arrow is disabled:

```jsx
modifiers={{
    arrow: {enabled: false}, // <-- If present, offset bellow is ignored
    offset: {options: {offset: [0, 48]}}
}}
```

```jsx
minimal={true} // <-- If present, offset bellow is ignored
modifiers={{
    offset: {options: {offset: [0, 48]}}
}}
```

Note: Using @blueprintjs/popover2 **0.7.3**

**Comment by adidahiya** [comment]
You're right, this seems to be a behavior change in Popover2 caused by this line:

https://github.com/palantir/blueprint/blob/ccef710bc8c0f729ab86918e9c26c2a348d61735/packages/popover2/src/popover2.tsx#L460

It's likely that we can simply change that line to something like `enabled: this.isArrowEnabled() || modifiers?.offset?.options !== undefined` to support your use case.

Can you explain a bit more what your desired use case looks ? Do you have any screenshot or example of what you're looking to do?

**Comment by vladimir-djokic** [comment]
This is my use case:

![Screenshot 2021-05-20 132905](https://user-images.githubusercontent.com/16443718/118971580-e508ce00-b96f-11eb-8ad3-831370b57761.png)

Clicking on `Folder`, `File` or `Document` directly (as they are `MenuItem`s) results in **Wizard** for creating those objects. 

However, there is also a concept of "classification" where clicking on a button next to them will display a submenu of "classifications" for those object types (API for fetching available "classifications" for that particular object type is being called). Clicking on "classification" results in **Wizard** with that "classification" applied and some data pre-filled for the user (among other things). I wanted to make this "classification" sub-menu a little more like "regular" Blueprint's submenu.

If I remove the arrow, I get this:

![Screenshot 2021-05-20 133012](https://user-images.githubusercontent.com/16443718/118972470-dff84e80-b970-11eb-8bad-fb34fd7565a1.png)

But it looks funky like this. That is why I wanted to remove the arrow and apply additional offset at the same time.

**Comment by adidahiya** [comment]
Interesting, thanks for sharing @vladeck. I will make the change I suggested in my comment above, and also consider supporting your style of menu item w/ submenu in a more first-class way, as it looks like it could be useful for other Blueprint users.

**Comment by adidahiya** [comment]
@vladeck actually, you should be able to enable the offset yourself simply by adding `enabled: true` to the modifier. with your initial code example, you should change it to:

```ts
modifiers={{
    offset: {
        enabled: true,
        options: { offset: [0, 48] },
    },
}}
```

you can do this with any of the modifiers. I'll update the prop documentation to make this more clear.

**Comment by vladimir-djokic** [comment]
@adidahiya Thank you, that works!
