### ISSUE TITLE
How do I make a button rounded? 

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4724]
I'm pretty sure this was possible but I don't see how to do it in your docs. 

Thanks!

keywords: button round circular rounded icon

**Comment by adidahiya** [comment]
I don't think this was ever possible, and it probably won't be supported. You can make [tags](https://blueprintjs.com/docs/#core/components/tag) rounded, though.

**Comment by tnrich** [comment]
@adidahiya good to know. Thanks!
