### ISSUE TITLE
Hovering over a tooltip even with HOVER is almost impossible

### ISSUE THREAD

**Issue by maclockard** [palantir/blueprint#4727]
#### Environment

- __Package version(s)__:
  - `@blueprintjs/core`: 3.40.0
  - `@blueprintjs/popover`: 0.3.1
- __Operating System__: macOS
- __Browser name and version__: Firefox 88.0.1

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-pyqub?file=/src/index.tsx:984-989

#### Steps to reproduce

1. Hover over the button that says "Normal tool tip"
2. Try to hover over the tooltip and click then link

#### Actual behavior

The tooltip closes as soon as you leave the target even though `interactionKind` is set to `HOVER`. It's possible if you move your mouse _exactly_ over the tooltip arrow, but its a pretty tight tolerance so its difficult to do even if you know thats the only way to do it.

Note a workaround right now is to set `minimal` to `true`. This makes it much easier to mouse over, but requires changing the style of the tooltip.

#### Expected behavior

I'm able to easily hover over the tooltip when `interactionKind` is set to `HOVER`

#### Possible solution

I think rendering an invisible div in the area between the tooltip and the target would allow for the interaction kind to work with the tiny arrow.

**Comment by adidahiya** [comment]
try `hoverCloseDelay={200}` (or some suitable ms value)?

**Comment by maclockard** [comment]
ah, that definitely helps a lot. No longer need `minimal` with that.
