### ISSUE TITLE
useHotkeys from within an iframe

### ISSUE THREAD

**Issue by pringshia** [palantir/blueprint#4731]
#### Environment

Testing on Chrome Version 90.0.4430.212 (x86_64) / macOS Big Sur

**Repro: https://codesandbox.io/s/blueprintjs-hotkeys-iframe-xwcpw?file=/src/App.js**

<a href="https://codesandbox.io/s/blueprintjs-hotkeys-iframe-xwcpw?file=/src/App.js"><img width="516" alt="Screen Shot 2021-05-21 at 4 01 43 PM" src="https://user-images.githubusercontent.com/425059/119192284-dc86c500-ba4d-11eb-9a3c-ae6c65a5d70d.png"></a>

#### Question

This is definitely a unique use-case.

I am trying to get hotkeys working with a BlueprintJS app residing within an iframe (via `react-frame-component`).

In the code sandbox above, you can toggle the boolean `WRAP_WITH_IFRAME` to toggle wrapping the blueprint app within and without an iframe.

The hotkey works as expected without the iframe. However, once within the iframe, the hotkey doesn't seem to trigger. It does trigger however when the iframe is not in focus, and the parent window is in focus.

*Additional thoughts*: `react-frame-component` does provide through a context provider a reference to the child iframe's window and document objects. I think having the global event listeners for `useHotkey` register off of that window/document object may fix the problem, though I'm not sure how configurable this is. Again, this is definitely a unique case, I understand.

**Comment by adidahiya** [comment]
Thanks for bringing this up. It is a unique use case but it's definitely within the realm of things we should support. Making assumptions about `document` and `window` is always limiting, and I'd like to make Blueprint APIs configurable in that regard wherever possible (related: #3972, #4159).

I think this can be solved by accepting a custom `document` in `useHotkeys` and `HotkeysTarget2` via `UseHotkeysOptions`.

**Comment by adidahiya** [comment]
@pringshia please let me know if my changes in #4773 work in the next release. I can make tweaks if necessary.

**Comment by pringshia** [comment]
seems to be working at a quick initial glance, thanks @adidahiya!
