### ISSUE TITLE
Overwritting Card css with css className

### ISSUE THREAD

**Issue by marcoamonteiro** [palantir/blueprint#4733]
#### Environment

- __Package version(s)__: 3.44.3
- __Browser and OS versions__: Chrome

#### Question

I have a Card component. I would like to overwrite the padding of the Card. I defined the following css class:
`
.Login-screen-card {
    margin: auto;
    width: 450px;
    padding-left: 100px;
    padding-right: 100px;
}`
This is the html:
`
<Card className="Login-screen-card" elevation={2}>
`
My padding styling is overwritten by the Card styling. How can I give my styling priority?

**Comment by adidahiya** [comment]
can you please post a code sandbox demonstrating the issue? the problem may reveal itself more clearly if you do.
