### ISSUE TITLE
Incorrect context-menu position when using ContextMenu2 in react-tiny-virtual-list. 

### ISSUE THREAD

**Issue by wisdomG** [palantir/blueprint#4747]
#### Environment

- __Package version(s)__: `"@blueprintjs/core": "3.44.3"` and ` "@blueprintjs/popover2": "0.9.0"`,
- __Operating System__: Ubuntu 16.04
- __Browser name and version__: Version 91.0.4472.77 (Official Build) (64-bit)

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-36jpx

#### Steps to reproduce

I wanted to add `ContextMenu2` on each element in a virtual list (`VirtualList` component from `react-tiny-virtual-list` package ), but the position of popover content-menu was always incorrect. 

I tried the render props apis to solve this issue but failed.

#### Actual behavior

When I click the button, the position of the context-menu is far away the targar button. Sometimes, the popover contenx-menu disappears after I scroll the button list and click any button again. 

#### Expected behavior

The popover context-menu shoule be alwarys near the button I clicked on. 

BTW, the position is as expected when I use the `ContextMenu.show` api, so I would like to know there are any similar apis in `ContextMenu2` ?

**Comment by adidahiya** [comment]
@wisdomG can you please try again with the latest popover2 version (v0.10.1)? I made some positioning changes in the v0.10 releases

**Comment by wisdomG** [comment]
@adidahiya Yeah, it works with the latest version. Thank you
