### ISSUE TITLE
Sass: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by ejose19** [palantir/blueprint#4751]
#### Environment

- __Package version(s)__: 3.45.0
- __Operating System__: Linux
- __Browser name and version__: N/A

#### Code Sandbox

N/A (Build warnings)

#### Steps to reproduce

1. Use latest version of `sass` (1.34.1)
2. Run a code build
3. Notice many warnings in the output

#### Actual behavior

Output receives a lot of deprecation warnings, e.g:
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
180 │ $pt-border-radius: floor($pt-grid-size / 3);
    │                          ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@blueprintjs/core/lib/scss/variables.scss 180:26  @import
    root stylesheet
```

#### Expected behavior

No warnings during build

#### Possible solution

Running migrator as stated in the output

**Comment by adidahiya** [comment]
related to #4032, we'll need to address this when moving to dart sass (currently we use node-sass)
