### ISSUE TITLE
Font issue on systems without many fonts installed

### ISSUE THREAD

**Issue by ejose19** [palantir/blueprint#4758]
#### Environment

- __Package version(s)__: 3.45.0
- __Operating System__: Linux / Android
- __Browser name and version__: Linux: Chromium 90 | Android: Bromite / Brave

#### Code Sandbox

Even the main site can be used to reproduce the bug: https://blueprintjs.com/docs/

#### Steps to reproduce

1. Install chromium on vanilla debian
2. Go to https://blueprintjs.com/docs/
3. Click on Search (or shift + s)
4. Type the character `?`

#### Actual behavior

`?` are rendered as an "icon" instead of an actual `?`

![search](https://user-images.githubusercontent.com/8742215/121774478-f8671d80-cb58-11eb-8eb8-8014d9970640.png)

#### Expected behavior

`?` should be rendered normally

#### Possible solution

If I go to developers tools and manually remove `Icons16` from the font-family, the issue goes away.

#### Note

This doesn't just affect the `Search` component, editing the HTML manually to randomly add `?` in the text will also make it display like that:

![general](https://user-images.githubusercontent.com/8742215/121774535-35cbab00-cb59-11eb-8a30-b3bd6ca58b6e.png)

**Comment by ejose19** [comment]
Upon inspecting the file that loads that font-family:

https://github.com/palantir/blueprint/blob/d0b444bbf85a85491fcaf1135aed26e90cc76c3a/packages/core/src/common/_variables.scss#L17-L28

Do really we need it? After removing the font-family I couldn't notice any issue with the site, the icons still renders as usual (and actually the words/paragraph are better spaced).

EDIT: I found https://github.com/palantir/blueprint/issues/1060 that mentions not loading icons could lead to `HTMLSelect` not rendering correctly

EDIT2: Swapping `"Icons16"` & `sans-serif` order seems to solve the issue without breaking `HTMLSelect` icons. However, I checked `v4` alpha site and the issue is not present, while diffing it seems it's using another font (v4 one doesn't include lowercase letters and there are empty rows between letters and numbers)

**Comment by adidahiya** [comment]
In v4 I changed the icons build infrastructure to use [fantasticon](https://github.com/tancredi/fantasticon), which generates the icon font files. If your issue is not present there then I am inclined to close it as "fixed", as I don't really want to make more changes to icons tooling in the 3.x range. 4.0 alpha/beta releases will be coming in the next few weeks, and a stable version is expected in a month or two.

**Comment by ejose19** [comment]
I'd argue that since the fix is very small (just swapping the order on the last 2 font-families) it should be done for 3.x branch, if you agree I can make a PR.

**Comment by adidahiya** [comment]
@ejose19 as you can see that swap was done explicitly in PR https://github.com/palantir/blueprint/pull/1150. are you sure it's safe to revert?

**Comment by ejose19** [comment]
After reading that linked PR, I see that the "solution" shouldn't have be merged in first place, specially when it should have been solved at the dependency level `css-nano` (like whitelisting certain families from the rule). The issue here is that when the system doesn't have any of the previous fonts:
`-apple-system,"BlinkMacSystemFont","Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Open Sans","Helvetica Neue"`

and reach `Icons16` first, it will use it as text font instead of icon font, which was probably the reason why they put it last in first place (as mentioned in https://github.com/palantir/blueprint/issues/1107): https://github.com/palantir/blueprint/issues/1107#issuecomment-302196313

I've swapped them manually with `patch-package` and it's not being removed even after placing after `sans-serif` (both in dev and built), and I'm using webpack (through CRA), so probably webpack is no longer using `css-nano` or the issue is no longer present.

Anyways, I did some more tests and `Icons16` is not even needed at body level since it's [legacy](https://blueprintjs.com/docs/#core/components/icon) and the only component that stills depends on it `HTMLSelect` already does import the font by itself in https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/html-select/_html-select.scss, as seen when inspecting the [docs](https://blueprintjs.com/docs/#core/components/html-select.css):

```
.bp3-select:after {
    font-family: Icons16,sans-serif;
    font-size: 16px;
    font-style: normal;
    font-weight: 400;
    line-height: 1;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    content: "";
}
```

One couldn't assume a system without any of the previous fonts is rare, but since I managed to reproduce the issue both in vanilla debian and android, I'd say it's not so low after all.

**Comment by ejose19** [comment]
Some more reports on this issue, v4 is not having any conflicts due to their icons being in a different "range" than v3 icons:

v3:
![v3](https://user-images.githubusercontent.com/8742215/122457722-534bab00-cf85-11eb-89bf-ec982c53a1e1.png)

v4:
![v4](https://user-images.githubusercontent.com/8742215/122459118-e9cc9c00-cf86-11eb-9909-05888b5396e2.png)

As you can see in the unicode value, v3 is conflicting with ascii which makes the browser use icon font as text font (see below)

search text: `abcd?$*+`

![search](https://user-images.githubusercontent.com/8742215/122459550-6fe8e280-cf87-11eb-9fc6-1cea97e56072.png)

![rendered-fonts](https://user-images.githubusercontent.com/8742215/122459542-6cedf200-cf87-11eb-9acb-7ec5545a29a3.png)

So as long blueprint icons doesn't conflict with common characters, I guess it's fine to place `Icons16` before `sans-serif`, but for v3 it's not the case and I still don't see much utility by using `Icons16` in `body` (unless users want to map unicode characters to icons, but that is a very odd case)

**Comment by adidahiya** [comment]
I thought about this some more and I think you're right that we can remove the Icons16 font from the font-family stack. However, it would be a small breaking change. Unfortunately I have no way of knowing if people are using that font as suggested in https://github.com/palantir/blueprint/issues/1107#issuecomment-302267688:

> Icons16 is in there so you can use icon unicode strings in your text

So, as much as I'd like to remove it, it will have to wait until 4.0.

**Comment by adidahiya** [comment]
Btw, the docs about icon font being "legacy" is a little outdated. I've fixed that here: https://github.com/palantir/blueprint/pull/4772

**Comment by ejose19** [comment]
Sure, let's remove it for v4 then and let users explicitly use the `Icons16` as `font-family` instead of applying it implicitly. I'll keep using the patch until v4 is released as my site was having many reports about `?` characters being mapped to an icon (and honestly I'm surprised nobody reported this issue before).

**Comment by sushain97** [comment]
Interestingly enough, I ran into this issue since it breaks word-spacing on e.g. Android where the spaces between words are rendered using `pt-iconosaurus` rather than `Roboto`:

![image](https://user-images.githubusercontent.com/4211838/148718129-5631c628-4cee-47fd-86a9-86038d984c2b.png)


Here's how it looks if I use remote debugging to remove `Icons16` from the `font-family`:

![image](https://user-images.githubusercontent.com/4211838/148718134-9db9d3bb-ee62-4f32-ba2f-561692e52d11.png)


Once you notice it, it's quite glaring.

**Comment by adidahiya** [comment]
@ejose19 @sushain97 is this still an issue with the current 4.x release?

**Comment by sushain97** [comment]
Nope. LGTM on an Android device now. Thanks!
