### ISSUE TITLE
Misplaced Popover arrow when Popover content changes size

### ISSUE THREAD

**Issue by acolombi** [palantir/blueprint#476]
Rather than try to explain it, I'll let this video do the talking:

https://videos.palantir.com/media/popover+and+daterangepicker/0_jy1i0owk

Understood that this is only available to Palantir employees, but it's a complex issue that's easily described in video form.

**Comment by leebyp** [comment]
Problem in question arises when the contents in a Popover changes size without the state changing (as shown here with the DateRangePicker):

![daterangepicker in popover](https://cloud.githubusercontent.com/assets/6375593/22089174/2db9f780-dd9e-11e6-9b6e-57a03a8999bc.gif)

The problem resolves when the Popover `inline` prop is set to `true`. I experimented with
- having the Popover passing down an `updatePopover` handler to it's contents
- the Popover uses a `setInterval` to check the size of it's contents and `forceUpdates` accordingly

Neither feels satisfactory to me. Thoughts? @palantir/blueprint

**Comment by leebyp** [comment]
Closing as won't fix.
If the `inline` solution doesn't work, another way to solve would be to control both the Popover and the Contents from the parent element and use `ref` in React accordingly.
