### ISSUE TITLE
Add ability to pass `autoComplete` as a prop to `DateInput`

### ISSUE THREAD

**Issue by epx-nathan** [palantir/blueprint#4762]
Hello!

At the moment it's possible to pass an `autoComplete` prop to the `<InputGroup/>` component, which is great! We use this with a number of our text input fields to be more accessible for our users.

I'm creating this issue because I would like to be able to pass `autoComplete` as a prop to the `<DateInput/>` component. I did a search in your codebase and saw where it was set to `"off"`, but without any ability to override that setting. Also in looking through the Blueprint codebase I see where the `<Suggest/>` component has it as an option.

We'd like this added because right now our web app is getting a lower accessibility score with one of our partners and this is one of the contributing factors (i.e. not being able to set an `autoComplete` value of `bday` for a date of birth field, which is using the `<DateInput/>` component under the hood).

Thank you for your consideration and let me know if you'd like any additional information from me!

**Comment by adidahiya** [comment]
Did you try `<DateInput inputProps={{ autoComplete: "on" }} />`? It seems to work when I try it in the Blueprint docs via React devtools.

**Comment by epx-nathan** [comment]
@adidahiya You are a lifesaver! That did the trick, thank you. Will close this issue!
