### ISSUE TITLE
Icon request: "Open in new tab"

### ISSUE THREAD

**Issue by DanielDanielDanielDanielDaniel** [palantir/blueprint#4764]

**Comment by adidahiya** [comment]
We generally get by using the "share" or "arrow-top-right" icons for actions like this, so I'm not sure we need a new icon here. @aycai any thoughts on this?

Example in the docs app:

![image](https://user-images.githubusercontent.com/723999/122089605-ec878f80-cdd4-11eb-9be6-81acca0d5e46.png)

**Comment by DanielDanielDanielDanielDaniel** [comment]
You’re totally right. I found the icon later that day and wasn’t able to delete that post. Thanks for mentioning.

**Comment by aycai** [comment]
+1 to what Adi's points, glad you found it!
