### ISSUE TITLE
Tooltips display issue with overflow: hidden

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#478]
### Bug report

- __Package version(s)__: @blueprintjs/core@1.5.0
- __Browser and OS versions__: Chromium (Electron) on Windows 10

#### Steps to reproduce

1. Use Tooltip (with dark theme, if this is important, I guess not)
2. Check its appearance
3. Agree that it could look better

#### Actual behavior

Top left and right edges of tooltip are not rounded, while bottom ones are. Bottom padding seems way to much:

![tooltip-2](https://cloud.githubusercontent.com/assets/206773/21932071/f1b714f0-d99e-11e6-87c4-7fe5ebf067b8.png)

#### Expected behavior

All edges rounded, or none. Text centered.

**Comment by forman** [comment]
The first CSS rule in my single-page app is the following

      /* Gets rid of any extra scrollbars added by the browser */

      * {
        overflow: hidden;
      }

If I comment that out, tooltips look as they should, i.e. as in the [docs](http://blueprintjs.com/docs/#components.tooltip).

**Comment by adidahiya** [comment]
> The first CSS rule in my single-page app is the following

... that is an overly general global rule. It doesn't seem worth it to write Blueprint component CSS in a way that is defensive against such global styling. Surely there are more specific selectors for your `overflow: hidden` rule which would solve your scrollbar issues?

**Comment by llorca** [comment]
A non-inline tooltip may solve your problem, but generally agree that `* { overflow: hidden; }` is gonna cause you some weird behavior eventually

**Comment by giladgray** [comment]
yeah that's a terrifying way to start your stylesheet and is guaranteed to cause problems with anything that relies on non-static positioning.

**Comment by forman** [comment]
Thanks guys for the hints! 

Yepp, it's easy to see that I am a CSS beginner (and I'm not sure whether I will ever like it).
