### ISSUE TITLE
Long MenuItem submenus are not fitting on the page properly. Need scrolling support

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4791]
Hey there @adidahiya and others. I've long admired how well your Menu's work. In general they're great! 

However, I've noticed that long submenus seem to fall off the page: 
![image](https://user-images.githubusercontent.com/2730609/124176873-5c984580-da64-11eb-8f18-b4e7756a0623.png)

Here's a link to a repro: https://codesandbox.io/s/blueprint-sandbox-forked-emhkz

Click the Primary button to see the menu in question. 

Possible Solution: 

I think that long submenus should automatically be bounded to the view height of the window and scroll within that contraint. 

Thoughts?

Thanks!

Note this is similar but slightly different than: https://github.com/palantir/blueprint/issues/4406

**Comment by adidahiya** [comment]
Is it possible to target those submenus with a custom class and apply a `max-height`? That's generally the approach we've taken for long menus.

**Comment by tnrich** [comment]
@adidahiya ok I think I have a CSS solution that is decent: 

```
.bp3-submenu > * > .bp3-menu {
  max-height: 96vh;
  overflow: auto;
}
```
![image](https://user-images.githubusercontent.com/2730609/124196124-9e36e980-da80-11eb-988f-fb571446137f.png)

Here's the sandbox link: https://codesandbox.io/s/blueprint-sandbox-forked-5f1si?file=/src/CoreExample.tsx


I'll close this and re-open it if I hit any snags implementing it. 

Thanks!
