### ISSUE TITLE
numFrozenColumns causes column header to be disjointed on first load

### ISSUE THREAD

**Issue by donnalmh** [palantir/blueprint#4797]
#### Environment

- __Package version(s)__: blueprint table 3.5
- __Operating System__: Windows
- __Browser name and version__:  Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1.  Create table. create 3 columns with long list of names. Set numFrozenCol=1

#### Actual behavior

The first column becomes disjointed from the rest. The start height of the data portion is higher at first.
![TESTIN](https://user-images.githubusercontent.com/31563018/124431380-92913e80-dd70-11eb-9a67-6258c0ccc273.png)

Only upon scroll, the table seems to re-render and the height adjusts. But then there seems to be an empty space below the first column header.
![testing](https://user-images.githubusercontent.com/31563018/124431545-c704fa80-dd70-11eb-88a8-cc9dab678894.png)

#### Expected behavior

The start height of data should be aligned with subsequent columns.

**Comment by adidahiya** [comment]
fixed in table v4.0.0-rc.1
