### ISSUE TITLE
Running on localhost

### ISSUE THREAD

**Issue by tinopetros** [palantir/blueprint#4804]
#### Environment

- __Package version(s)__: 3.23.5
- __Browser and OS versions__: Chrome 91.0.4472.114/MAC OC Catalina 10.15.7

#### Question

I need help with how to check my changes on localhost as I change components. Should I expect the components I edit to be the ones that display in the example?

**Comment by tinopetros** [comment]
For example, when I make the render method in 'packages/datetime/src/datePicker.tsx' return null, the date picker example still shows up correctly after I save my edits and reload my browser page. Yet when I edit the example itself here: 'packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx' the example page is atered as expected.

**Comment by adidahiya** [comment]
are you running `yarn dev` in both the packages/core and packages/docs-app folders?

**Comment by tinopetros** [comment]
I am running it in the root i.e blueprint folder like #2 here: https://github.com/palantir/blueprint/blob/develop/CONTRIBUTING.md

I tried running in the packages folder but that does not seem to help, are you suggesting I run yarn dev in separate terminals in each of packages/core and packages/docs-app folders?

**Comment by tinopetros** [comment]
Re-did this on a new branch and it is looking good now. I'll close this for now.

**Comment by adidahiya** [comment]
> are you suggesting I run yarn dev in separate terminals in each of packages/core and packages/docs-app folders?

yes, that is how I typically develop Blueprint, using separate terminal windows/sessions to run `yarn dev` in each package I need. usually it's just two packages, like core and docs-app.
