### ISSUE TITLE
Editable focused state is of different size than hover state

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#482]
### Bug report

- __Package version(s)__: 1.5.0
- __Browser and OS versions__:  macOS, Chrome 55

#### Steps to reproduce

1. http://blueprintjs.com/docs/#components.editable
1. Hover editable header
1. Click editable header

#### Actual behavior

Hover has a nice border right around the text, while focus state adds extra 30px padding on the right.

![screen recording google chrome](https://cloud.githubusercontent.com/assets/199754/21941015/ab652c9e-d97b-11e6-8354-446aba55abfc.gif)

#### Expected behavior

Focused input is the same size as the hover border.

**Comment by giladgray** [comment]
@cyu06 added that space for IE, I think. perhaps he can weigh in on why (if) it's necessary?

**Comment by cyu06** [comment]
https://github.com/palantir/blueprint/blob/c3ca211c073350cda8c1983c76a4446e9a85a869/packages/core/src/components/editable-text/editableText.tsx#L281

Github is not letting me upload the animated gif, but internally the issue was 1378.

**Comment by llorca** [comment]
Before IE fix:
![image](https://cloud.githubusercontent.com/assets/199754/21947289/4899d31c-d999-11e6-8cfb-095275bfedc3.png)

After IE fix:
![image](https://cloud.githubusercontent.com/assets/199754/21947283/41f54fb4-d999-11e6-90b2-9e048e51e228.png)

**Comment by llorca** [comment]
Is the buffer thing something we can do for IE only?
