### ISSUE TITLE
core.js: Uncaught (in promise) SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by rafaellichen** [palantir/blueprint#4823]
Please help; thanks in advance :)

#### Environment

- __Package version(s)__: @blueprintjs/core@3.47.0
- __Operating System__: macOS Big Sur Version 11.4
- __Browser name and version__: Google Chrome, Version 92.0.4515.107 (Official Build) (x86_64)

#### Code Sandbox

Link to a minimal repro: [https://mybinder.org/v2/gh/idom-team/idom-jupyter/main?filepath=notebooks%2Fintroduction.ipynb](https://mybinder.org/v2/gh/idom-team/idom-jupyter/main?filepath=notebooks%2Fintroduction.ipynb)

#### Steps to reproduce

Visit the link above, wait for jupyter notebook env. to build. After that, paste the following on a new cell and run.
If not seeing the error, do a browser cache clear to force the javascript file refetch.
```python
import idom
import idom_jupyter

victory = idom.web.module_from_template("react", "ipyreact@1.0.12", fallback="...")
VictoryBar = idom.web.export(victory, "Annotator")

@idom.component
def VictoryBarElement():
    return VictoryBar()

VictoryBarElement()
```

#### Actual behavior

In the browser console, error: `Uncaught (in promise) SyntaxError: Invalid or unexpected token`
The error originates from the linked file `core.js` on: [https://cdn.esm.sh/v43/@blueprintjs/core@3.47.0/es2020/core.js](https://cdn.esm.sh/v43/@blueprintjs/core@3.47.0/es2020/core.js)
Use text search to find the only code starting with `1.tolocal` or `t=1`; this is where the error starts.

#### Expected behavior

Probably should not have error here?

#### Possible solution

N/A

**Comment by adidahiya** [comment]
This looks like a problem with binder or jupyter notebook, not with Blueprint.

**Comment by rafaellichen** [comment]
@adidahiya I am really confused, am I miss something?
This is the error I get if I paste the https://cdn.esm.sh/v43/@blueprintjs/core@3.47.0/es2020/core.js inside vscode:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number.
When I run `1.toLocaleString('ar-EG');` in browser console, it still gives the same error: Uncaught SyntaxError: Invalid or unexpected token (which is expected because I got the same error when importing it in the test environment above).

**Comment by adidahiya** [comment]
I'm not familiar with esm.sh; that file you linked is not something published in the `@blueprintjs/core` package. Can you explain a bit more how that core.js file was generated?

**Comment by rafaellichen** [comment]
@adidahiya
I am not familiar with esm.sh either, but I think it's very similar to https://unpkg.com/. Both are CDN services to delivery the es modules faster. So based on the explanation in "workflow", the process is somewhat automatic. When I published my package for testing using `microbundle-crl --no-compress --format modern,cjs` to build, it becomes available on esm.sh too. Let me know if this is helpful.
Misc. links:
https://github.com/idom-team/idom/issues/455
https://github.com/idom-team/idom/discussions/452

**Comment by rafaellichen** [comment]
@adidahiya resolved by changing package build method. Thanks for the helps.
