### ISSUE TITLE
Support disabling the native cancel button for search inputs

### ISSUE THREAD

**Issue by eshlin** [palantir/blueprint#4827]
#### Environment

- __Package version(s)__: 3.47.0
- __Browser and OS versions__: Tested across several browsers

#### Feature request

This issue proposes adding a way to disable the native cancel button for search inputs. The motivation is that browsers are inconsistent with displaying the native cancel button (Chrome displays it, but not Firefox), which makes it hard to ensure good UX across browsers. For example, if we add our own remove/cancel button to the right of the search input to improve the workflow to clear the search input for Firefox users, Chrome users would end up seeing two remove/cancel buttons.

There's some discussion of the native cancel button in #4156 but figured this might be worth specifically tracking. 

We were previously relying on `normalize.css` to remove the native cancel button, but it looks like normalize stopped doing so in the 8.x release (see https://github.com/necolas/normalize.css/issues/685 and https://github.com/necolas/normalize.css/commit/f7c98c4c859c15363763f10a439b63d85b9afba0 ). While it's possible to apply custom CSS to remove this button, this potentially seems like something reasonable to support on the blueprint library level.

**Comment by adidahiya** [comment]
Agreed, this sounds like something we should fix through the `@blueprintjs/core` package.

**Comment by adidahiya** [comment]
This problem seems to have gone away, maybe it was fixed in Chrome.
