### ISSUE TITLE
Maximum update errors when combining Table2 with useHotkeys hook

### ISSUE THREAD

**Issue by ghost** [palantir/blueprint#4830]
#### Environment

- __Package version(s)__:
    "@blueprintjs/core": "^3.47.0",
    "@blueprintjs/table": "^3.9.0",
    "classnames": "^2.3.1",
    "dayjs": "^1.10.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-scripts": "4.0.3",
    "redux": "^4.1.0",
    "web-vitals": "^1.0.1"

- __Operating System__: macOS 11.5
- __Browser name and version__: Safari 14.1.2, Firefox 90.0.2

#### Steps to reproduce

1. Add a HotkeysProvider
1. Add a Table2
1. Call useHotkeys from App component

#### Actual behavior

Tons of error logs in the console, many per-second:

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
HotkeysTarget2@http://localhost:3000/static/js/vendors~main.chunk.js:9272:18
Table2@http://localhost:3000/static/js/vendors~main.chunk.js:32071:24
```

#### Expected behavior

No errors

**Comment by adidahiya** [comment]
@lyptt please provide a code sandbox repro as linked in the issue template, it will greatly speed up debugging

**Comment by HZ-labs** [comment]
@adidahiya look at this example.

https://codesandbox.io/s/determined-zeh-z29fwd?file=/src/index.js
and loom - https://www.loom.com/share/f6ad7a40cdd94bc08a2f36f7ac23a5db

**Comment by adidahiya** [comment]
@HZ-labs that looks like a different issue, can you please file a new issue for that one? There's no table component involved in your code sandbox. I'm going to close this old issue and we can discuss your problem in a new thread. Also I would recommend trying the latest v4.0.0-rc and seeing if that happens to resolve your issue.

**Comment by HZ-labs** [comment]
I create a new issue - https://github.com/palantir/blueprint/issues/5178
But I think is a similar, because @blueprintjs/table like react-virtualized, and if I use setState on re-rendering component I will get this error.
