### ISSUE TITLE
Time picker arrows do not line up inputs in date time picker with AM/PM enabled

### ISSUE THREAD

**Issue by dummycode** [palantir/blueprint#4846]
#### Environment

- __Package version(s)__: 3.23.6
- __Operating System__: macOS 10.15.7
- __Browser name and version__: Chrome 92.0.4515.131

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-lmps3

#### Steps to reproduce

1. Create a `DateTimePicker` with AM/PM buttons and arrow buttons.

#### Actual behavior

![image](https://user-images.githubusercontent.com/5015365/128553274-2e95fb02-48eb-4212-90aa-dd5316f790d6.png)

#### Expected behavior

I expect the arrows to line up with the inputs.

#### Possible solution

It's most likely the centering on the `DateTimePicker` messing this up. Even the repro as a whole looks pretty ugly.

**Comment by adidahiya** [comment]
Good call! Should be an easy fix.

**Comment by adidahiya** [comment]
Actually this seems to only be a problem with the DateTimePicker (which is deprecated). No issues when I add AM/PM to the DatePicker:

![2021-08-18 17 33 11](https://user-images.githubusercontent.com/723999/129975214-df3b114d-60a4-45e2-aca8-023f37bd932e.gif)
