### ISSUE TITLE
Radio Value Cannot be Number

### ISSUE THREAD

**Issue by JamesTann** [palantir/blueprint#4855]
#### Environment

- __Package version(s)__: ^3.45.0
- __Operating System__: Mac OS Big Sur
- __Browser name and version__: Google Chrome Version 92.0.4515.131 (Official Build) (x86_64)

#### Steps to reproduce

1. Using React, create a RadioGroup with at least one Radio button where value is set to a number and not a string. See code example:

```
<RadioGroup
    onChange={(event) => {
       setSelected(event.target.value);
    }}
    selectedValue={selected}
>
{{["one", "two", "three"].map((message, index) => {
    return (
        <Radio
            value={index}
            label={message}
            key={index}
        ></Radio>
    );
})}
</RadioGroup>
```

2. The Radio button will render, but will not be able to be checked, even though [the documentation](https://blueprintjs.com/docs/#:~:text=Radio%3E%20children%20elements.-,selectedValue,-string%20%7C%20number) for the Blueprint RadioGroup states selected value can be a number.

3. Changing `value={index}` to `value={index.toString()}` fixes the issue.

#### Actual behavior

The Radio button cannot be selected.

#### Expected behavior

The Radio button should be working according to the [documentation for the RadioGroup.
](https://blueprintjs.com/docs/#:~:text=Radio%3E%20children%20elements.-,selectedValue,-string%20%7C%20number)

#### Possible solution

Update the docs to state that selected value cannot be a number when using React.

**Comment by adidahiya** [comment]
In the future, please try to include a code sandbox to debug issues like this (it's linked in the issue template). It greatly speeds up debugging.

I've gone ahead and created a sandbox to try and repro your issue. Your code doesn't type check correctly as-is. The input value in the event is always a `string` (that's just how the DOM API works). So you need to parse the `event.currentTarget.value` from string to number. If you do this, you _can_ use a `number` for `selectedValue`.

Sandbox: https://codesandbox.io/s/blueprint-sandbox-forked-9w0t0?file=/src/CoreExample.tsx
