### ISSUE TITLE
Context Menus appear at the slightly wrong offset

### ISSUE THREAD

**Issue by oddcoder** [palantir/blueprint#4873]
#### Environment

Browser: Firefox or webview2
blueprintjs/core: 4.0.0-alpha.0
react-grid-layout: 1.2.5

#### Code Sandbox

https://codesandbox.io/s/failing-contest-menu-position-xb9d2

#### Steps to reproduce

1. Right click on the text in the `Callout` to the left.
#### Actual behavior

The context menu appeared far away from where I clicked (observe the picture bellow)
![image](https://user-images.githubusercontent.com/10424605/130483787-f158c418-8928-4a84-bcc6-97db7d8a4e5e.png)

I clicked on the word `right` and this is there the menu appeared

#### Expected behavior

The menu should appear very close to where I click as in the the example below

https://blueprintjs.com/docs/versions/4/#core/components/context-menu

#### Possible solution
I honestly don't know, I use react for fun.

**Comment by adidahiya** [comment]
I believe this was fixed in the 3.x branch in ContextMenu2, and will get fixed in the next 4.0.0 pre-release (it's been a while since I made a 4.x release).

**Comment by oddcoder** [comment]
That is cool, Looking forward for the next 4.0 release!
