### ISSUE TITLE
Provide positioning for spinners inside InputGroups

### ISSUE THREAD

**Issue by thomas-mcdonald** [palantir/blueprint#488]
We're building an app with a central search bar. I'd like to put a Spinner as the right element for an InputGroup when the network request is in progress - it seems like it would be useful to provide correct positioning/sizing (or a utility class that does so) when using a Spinner as the right element here.

The current output with `pt-large` element/`pt-small` spinner is this:
<img width="631" alt="screen shot 2017-01-15 at 19 33 13" src="https://cloud.githubusercontent.com/assets/197928/21965523/bb3ab62c-db59-11e6-81fc-fade16e95492.png">

**Comment by giladgray** [comment]
makes sense! this is a great use of an input group.
