### ISSUE TITLE
InputGroup & react-hook-form

### ISSUE THREAD

**Issue by ippsav** [palantir/blueprint#4887]
#### Environment

- __Package version(s)__: 3.49.0
- __Operating System__: Arch-Linux
- __Browser name and version__: Chrome latest

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1- The new version doesn t  support react hook form now with the {...register("fieldName")}.

**Comment by adidahiya** [comment]
Please fill out the issue template with a code sandbox demonstrating your issue, it's going to be hard to debug without that.

**Comment by ippsav** [comment]
Here is a sandbox, default html input compared to input group

https://codesandbox.io/s/sweet-aryabhata-sbz8c?file=/src/App.js

This happens only in the latest version of blueprintjs works fine with 3.48.0

**Comment by adidahiya** [comment]
Doesn't look like your example works with 3.48.0 either: https://codesandbox.io/s/magical-kirch-n7s41?file=/src/App.js

Can you please describe the issue in more detail... what is the actual behavior, expected behavior, and exact steps to repro?

**Comment by ippsav** [comment]
The actual behavior is that the input group doesn t register as an input by react hook form with the latest version.The expected behavior is just like the codesandbox it should register the value i am typing in the input group before submiting which works fine and an html input.


I downgraded it and it s working fine for me i can link you the repo:https://github.com/ippsav/chat-app-typescript

In the Login Form try to watch the values it will work as it should
