### ISSUE TITLE
Add an optional Date Picker param to disable changing the selected date on month change

### ISSUE THREAD

**Issue by emmalangfitt** [palantir/blueprint#4889]
#### Environment

- __Package version(s)__: 3.48.0
- __Browser__: Chrome 

#### Feature request

- Add an optional parameter to the Date Picker component so the selected date doesn't automatically change when the month is changed
- This behavior is baked into Blueprint [here](https://github.com/palantir/blueprint/blob/519228df03c6cb6edf076c797ca182cd4e89d9c6/packages/datetime/src/datePicker.tsx#L398)
- If an application loads data based on a selected date, it ends up calling the data load an extra time when the user selects a date in a different month (once when the month changes and once when the target date is actually selected)

#### Examples

![monthChange](https://user-images.githubusercontent.com/44270286/131914394-eab76dba-cf88-4e66-a26a-3ca1a4bdc9f4.gif)

**Comment by adidahiya** [comment]
@emmalangfitt looks like this was brought up before in https://github.com/palantir/blueprint/issues/2418 -- have you tried using the second parameter in the `onChange` callback to distinguish between selection and month navigation? Maybe that would be sufficient for your use case.

**Comment by emmalangfitt** [comment]
@adidahiya that works 🤦‍♀️  I'd tried using that parameter before but wasn't having any luck, I must have done something wrong. Thank you!
