### ISSUE TITLE
Suggest Component does not close after setting to active. only happening on BLUEPRINT/CORE 3.50^

### ISSUE THREAD

**Issue by anthonybalmeo** [palantir/blueprint#4913]
#### Environment

- __Package version(s)__: 3.50.0
- __Operating System__: Mac OSX
- __Browser name and version__: Chrome: Version 93.0.4577.63 (Official Build) (x86_64)

#### Code Sandbox
```
            <Suggest
              items={driverTags}
              onQueryChange={q => setQuery(q)}
              itemPredicate={isResult}
              query={query}
              inputValueRenderer={i => `${i}`}
              onItemSelect={async i => {
                const newTags = [...tags]
                newTags.push(i)
                setTags(newTags)
                await refetch()
              }}
              inputProps={{ placeholder: 'Add tag...' }}
              itemRenderer={(i, data) => (
                <Menu.Item
                  onClick={async () => {
                    const newTags = [...tags]
                    newTags.push(i)
                    setTags(newTags)
                    await refetch()
                  }}
                  text={`${i}`}
                  key={`${i}`}
                  active={data.modifiers.active}
                />
              )}
            />
```

#### Steps to reproduce
Video to show it
Suggest Component does not close after setting to active. only happening on BLUEPRINT/CORE 3.50^. 3.49.1 and below works.

https://user-images.githubusercontent.com/967897/133662302-c8c2092f-4590-4641-b569-bea2681baa6b.mov

#### Actual behavior

Opening the `Suggest` component doesn't ever close after clicking away.

#### Expected behavior

Should close after clicking an option or clicking out the select input.

#### Possible solution

I switched back to `3.49.1`

**Comment by kenjinz** [comment]
I got the similar problem in Date Input components too.

**Comment by kenjinz** [comment]
@anthonybalmeo I think you can try it:  
popoverProps={{
   shouldReturnFocusOnClose: false,
 }}
                        
add this props in. It worked for me.

**Comment by anthonybalmeo** [comment]
@anhvu-1706-dnvn didn't seem to work for us :\

**Comment by SNY7** [comment]
@anhvu-1706-dnvn Works like a charm, thanks for sharing :D
