### ISSUE TITLE
Removing focus from tooltip inside of a popover closes popover

### ISSUE THREAD

**Issue by styu** [palantir/blueprint#4921]
#### Environment

- __Package version(s)__: popover2 0.12.2
- __Operating System__: OSX
- __Browser name and version__: Chrome

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-5j1fz?file=/src/Popover2Example.tsx

#### Actual behavior
When you hover over the tooltip and move off the tooltip target but stay within the popover contents, the entire popover closes

#### Expected behavior

The tooltip should close, but the popover should remain open

**Comment by michaeledryan** [comment]
Just wanted to note that we hit this because the focus on the example's `textarea` is what controls the popover. Moving off the tooltip changes the `activeElement` to something with `bp3-popover-dismiss`. I tried a few different props here, but the tooltip always grabs focus when it closes.

**Comment by adidahiya** [comment]
I think you can easily fix your problem by setting `enforceFocus={false}` on the popover. We technically "fixed" the enforce focus behavior in v3.50 (it was previously broken) and as a result, started taking more control of focus upon open & close of the underlying `Overlay`... any popover which sets its open state based on focus management in the document (a rare use case) has the potential to be broken now. You can circumvent BP’s behavior by turning off `enforceFocus`. I realize this is a small breaking change, but it might be one we have to live with to get the benefits of keyboard accessibility enhancements for "free" across Blueprint's overlays.

**Comment by adidahiya** [comment]
Btw here's the code sandbox I've been using to test this. It shows both Popover & Popover2 examples: https://codesandbox.io/s/blueprint-sandbox-forked-6zp4e?file=/src/PopoverExample.tsx

**Comment by adidahiya** [comment]
I looked into this again after recently fixing some focus behavior in https://github.com/palantir/blueprint/pull/4963, and I think we can make an improvement to `enforceFocus`... in cases like this example, where the popover has `autoFocus={false}`, we can err on the side of being conservative and assume that the popover _never got focus in the first place_. So even though it has `enforceFocus={false}` (through the prop's default value), we can decide _not_ bring focus back to it after the nested tooltip closes. See the PR I just opened https://github.com/palantir/blueprint/pull/4971
