### ISSUE TITLE
[Legal]: Am I allowed to create components on another framework based on your design system?

### ISSUE THREAD

**Issue by yob-yob** [palantir/blueprint#4928]
Your design system is wonderful, I just find your design system a much better alternative than Google's Materialize Design.
The only problem that I have is that it doesn't have support for other frameworks. so...

## Question 1

I'm planning to create a UI Components Framework based from this design system using the Svelte Framework. I wanted to know if do I have the legal rights to use your design system? since the resource files (sketch) are just available in this repository, I would like to assume that it's okay...

## Question 2

I would like to ask if the resources files are up-to-date? if not, do you have plans in updating the resource files? it's currently from 2 years ago.

Thank you.

# EDIT: 

Question2 is answered, I found an updated resources on your website.

**Comment by jerrygreen** [comment]
Have you figured how to use this component library with Svelte framework?
