### ISSUE TITLE
default focus changes producing undesirable behaviors in Dialogs containing other popovers + popup menus 

### ISSUE THREAD

**Issue by zimeibian** [palantir/blueprint#4956]
**Environment**
- **Package version(s):** core 3.50.4, popover2 0.12.4
- **Operating System:** macOS, Windows 10 VM
- **Browser name and version:** Chrome on macOS, Edge on Windows 10 VM

Noticed some new issues with popup menus + Dialogs containing popovers after a recent upgrade from `core 3.48.0` -> `core 3.50.4` and `popover2 0.11.2` -> `popover2 0.12.4` that both feel potentially related to some breaking change in the default popover focus behavior: 

1. Opening a Dialog that contains a popover with `interactionKind="hover"` will now trigger the popover to open automatically -- the popover then goes into an infinite open/close loop as the hover target gains + loses focus repeatedly

2. When opening a popover menu, the first item now steals focus from the popover target so

    * if the first `MenuItem` has a submenu then the submenu is opened automatically -- if you hover/`tab` to another `MenuItem` without first mousing over the previously-focused item the submenu won't close (even if the new `MenuItem` opens its own submenu, in which case there can be multiple submenus open at the same time)
    * we can no longer support workflows where users use the keyboard to focus a popover menu target -> `enter` to quickly check the menu contents -> `enter` again to close the menu -- this was previously possible by explicitly defining `autoFocus={false}` on the popover, but it appears that `enter` on a click-triggered popover target now causes a popover with `autoFocus={false}` to close immediately after opening

**Code Sandbox w/ repros for the ^**

https://codesandbox.io/s/bp-focus-related-popover-weirdness-kbycy?file=/src/App.js

Setting `autoFocus={false}` and `enforceFocus={false}` seems to fix the issue with the infinite popover loop for the Dialogs and prevent submenus from automatically opening in popup menus (as seen in the sandbox linked above), but the issue with the multiple submenus still exist if we `tab` between the `MenuItem`s instead of hovering with the mouse + I haven't found a way to restore the `enter` to open menu/`enter` to close menu behavior we were able to support before.

**Comment by rhysbrettbowen** [comment]
I'm now hitting this when using a mutliselect element inside a dialog. Tried putting the autoFocus & enforceFocus false on both the dialog and popoverProps in multiselect but still getting an infinite loop
