### ISSUE TITLE
Update the value prop of <Radio /> to be of type React.ReactNode

### ISSUE THREAD

**Issue by marvinsum** [palantir/blueprint#4957]
This will allow rich text to be rendered for each `<Radio />` element.

**Comment by adidahiya** [comment]
@marvinsum do you mean `label`? We have a workaround where you can use `labelElement: React.ReactNode`.

`value` comes directly from React HTML input props, I'm not sure it's a good idea to override it...

**Comment by marvinsum** [comment]
Ah yes, `labelElement` works. My bad, I was looking at `IOptionProps` instead of `IRadioProps`
