### ISSUE TITLE
Unsure how to get the value of a radio field (while testing)

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#4961]
Hey there @adidahiya !  Hope all is well for you and the team :) 

I'm wondering.. I'm trying to write a cypress test right now to assert that the "negative" option is chosen in the the radio field displayed below: 

![image (1)](https://user-images.githubusercontent.com/2730609/136713477-b81d5cce-acca-438a-8eb0-e4f075ea3edf.png)

I don't seem to see a way to do so unfortunately. There's an input with the value="positive" and one with value="negative"

How can I tell which option is actually checked?

Thanks!!

**Comment by tgreen7** [comment]
you can use

```js
cy.get(`input[name="strand"][value="negative"]`).should("be.checked");
```
