### ISSUE TITLE
Popover2 will cause the page to scroll up unexpectedly

### ISSUE THREAD

**Issue by goncaloc1** [palantir/blueprint#4981]
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.51.0, @blueprintjs/popover2: 0.12.5
- __Operating System__: Any
- __Browser name and version__: Chrome, Firefox ESR (both latest)

#### Steps to reproduce

1. On a page with vertical scrollbar, scroll down;
2. Hover an item with `Popover2` component.
 
#### Actual behavior

`Popover2` will be displayed but the page will scroll up automatically and unexpectedly. 

https://user-images.githubusercontent.com/9931729/138468696-118cff94-d074-45c4-8ce3-54e738e41a72.mp4

#### Possible solution

Setting `usePortal` `Popover2` property to `false` will fix the issue but that's just a workaround.

**Comment by adidahiya** [comment]
This is a major regression, I'm looking into this ASAP
