### ISSUE TITLE
[v4] MenuItem active + hover state styling looks off

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4985]
#### Environment

- __Package version(s)__: core v4.0.0-beta.5, select v4.0.0-beta.5
- __Operating System__: macOS
- __Browser name and version__: Chrome

#### Steps to reproduce

1. [Visit v4 select docs](https://blueprintjs.com/docs/versions/4/#select/select-component)
1. Select an item in dropdown
1. Open the dropdown again, hover through items

#### Actual behavior

The active MenuItem goes from dark bg -> light bg, kind of an unexpected interaction:

![2021-10-26 11 08 29](https://user-images.githubusercontent.com/723999/138907727-c0ecba7d-b80d-415c-8ef0-01559de95412.gif)

#### Expected behavior

??

#### Possible solution

Use a slightly lighter or darker bg, but don't invert the colors when hovering over an active MenuItem

**Comment by aycai** [comment]
Sorry, scratch my previous comment - for the `select` component specifically, using the new hover state for the selected state (the light background with blue text) is the intended static state, and it will still have an `:active` state that matches the primary intent - this allows multi-select menus to retain feedback when clicking on selected menu items.
![image](https://user-images.githubusercontent.com/3513503/138918969-eae89a4e-1a59-49ad-b08f-612da6d88365.png)

**Comment by adidahiya** [comment]
Ok, cool, the design proposed in your second comment makes more sense. I'll go head and implement that.

We have some unfortunate prop naming at the moment; `<MenuItem active={true} />` actually represents the "selected" appearance. I can also go ahead and add `selected?: boolean` as a replacement and deprecate `active?: boolean` (although it won't fully go away until Blueprint 5.x; I don't want to add in additional breaking changes to v4.0 last minute).

**Comment by adidahiya** [comment]
There are some further complications -- currently, we apply the primary intent class to the MenuItem when `active={true}` and `intent` is undefined... I think we should stop doing that and instead set up the styles differently to achieve the design in your screenshot.
