### ISSUE TITLE
[v4] disabled inputs do not use disabled styling

### ISSUE THREAD

**Issue by aycai** [palantir/blueprint#4988]
This is building off of #4986 - flagged that other styles don't switch to disabled colors

#### Environment

- __Package version(s)__: core v4.0.0-beta.5
- __Operating System__: macOS
- __Browser name and version__: Chrome

#### Steps to reproduce

1. [Visit form groups docs (CSS section has an icon)](https://blueprintjs.com/docs/versions/4/#core/components/form-group.css)
2. Toggle `:disabled` state

#### Actual behavior
text and icon remain the same as the static state
![Screen Shot 2021-10-26 at 11 30 54 AM](https://user-images.githubusercontent.com/3513503/138921028-698ce5bb-f660-4b1a-b2fe-7ae56339162f.png)

#### Expected behavior
Text uses `disabled` styling
Icon uses `disabled styling

Mock:
![image](https://user-images.githubusercontent.com/3513503/138921451-da327da9-9fc4-4da1-bce6-f5d0a426e09b.png)

#### Possible solution

n/a

**Comment by adidahiya** [comment]
The CSS example section is kind of special and doesn't represent typical usage (we recommend the React component instead). To really see the disabled styles you need to toggle both `:disabled` and `.bp4-disabled` in that example.

The only bug I see after my bugfix PR https://github.com/palantir/blueprint/pull/4987 is the text color for the _placeholder_ text -- regular text gets the right disabled color:

![image](https://user-images.githubusercontent.com/723999/138922435-1c0926d7-28a8-4c22-8163-e1bb4fb4baf2.png)

**Comment by aycai** [comment]
ahh right, gotcha - and thanks for the specificity!
