### ISSUE TITLE
move wiki pages

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#5]
- [x] Release Process
- [x] Development Practices
  - [x] Coding Guidelines
- [x] Build Tasks
- [x] Editor integration
- [x] Docs Development

<br><br>
- [ ] Update CONTRIBUTING.md

**Comment by llorca** [comment]
I moved what still made sense, most of these pages are quite out-of-date. Even the ones I moved still probably contain errors, though I tried to correct as much as possible.

Let's go over it quickly next week so we can close this task.

**Comment by llorca** [comment]
Everything we wanted to move over has moved. Last step is updating CONTRIBUTING.md 👍

**Comment by adidahiya** [comment]
The [Releases & Artifacts](https://github.com/palantir/blueprint/wiki/Releases-&-Artifacts) wiki page is missing -- we should definitely port that over since it's linked at the top of the docs overview page :)
