### ISSUE TITLE
CSS on CDN

### ISSUE THREAD

**Issue by rui-infotrack** [palantir/blueprint#500]
Hello : )
Don't you guys host `blueprint.css` on CDN?

I couldn't find any so far...

**Comment by giladgray** [comment]
If all you want is the CSS file then unpkg is your best friend:
https://unpkg.com/@blueprintjs/core@1.6.0/dist/blueprint.css

(We don't yet publish a single bundled JS file so unpkg won't work for the JS files, see #303)

**Comment by adidahiya** [comment]
Let's add a link to that unpkg CSS url in the docs.

**Comment by giladgray** [comment]
I think we should just wait until #303 for that. There's little point (I think) in using Blueprint without the  JS.
