### ISSUE TITLE
Menu w/ focus and hover to open, then re-opens and closes repeatedly

### ISSUE THREAD

**Issue by costantine75** [palantir/blueprint#5000]
#### Environment

- __Package version(s)__:    "@blueprintjs/core": "^3.41.0",
- __Operating System__: Windows 10 Enterprise
- __Browser name and version__: Chrome Version 95.0.4638.54 (Official Build) (64-bit)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Introduced very recently (easily within the last two weeks), certainly exists in:
		"@blueprintjs/core": {
			"version": "3.51.3",

Not easiest to repro, but:
Using all blueprint controls!.
          <Popover2
            interactionKind={PopoverInteractionKind.HOVER}
...
content is:
  <Menu>
    <MenuItem
...

The Popover2 wrap a <Button

To repro:
1. Click on menu item root and try to hover
2. Try this over and over until it repros (shouldn't take to long)

#### Actual behavior

The menu inside the Popover2 opens, then closes, then opens, then closes, ad infinitum. See video (video can't upload, contact me and I can try to get it to you as needed).

My boss and test team repro'd independently too (on different OS)

**Comment by adidahiya** [comment]
Please create a code sandbox with a clear repro of the issue. We had some problems with menus/popovers opening and closing repeatedly, but I think they're all fixed in the latest core and popover2 packages.

**Comment by costantine75** [comment]
with all due respect: Def not.
________________________________

**Comment by costantine75** [comment]
I submitted on Friday, I have a day job. It is only noon on Monday.

Please work with people, or manage expectations.
