### ISSUE TITLE
[v4] icon font visual regressions

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#5002]
#### Environment

- __Package version(s)__: 4.0.0-beta.x

#### Actual behavior

Some icons in the icon font have are rendered poorly, with less fidelity than their SVG counterparts. For example, the "random" icon:

![image](https://user-images.githubusercontent.com/723999/139736366-83f06ac4-822d-4d2b-8adc-a6b61bc4edc0.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/723999/139736394-2549c709-5805-45f3-b9ff-a7323759d8b2.png)

#### Possible solution

- Use [oslllo-svg-fixer](https://docs.oslllo.com/svg-fixer/master) to transform the SVGs into a icon-font-ready representation before running `fantasticon`
- Use [webfont](https://github.com/itgalaxy/webfont) instead of fantasticon

**Comment by adidahiya** [comment]
Adding oslllo-svg-fixer and trying webfont still didn't solve the problem 😞  see https://github.com/palantir/blueprint/pull/5005

Here's what the icon font looks like in the Font Book app:

16px

<img width="1053" alt="Screen Shot 2021-11-03 at 11 50 19 AM" src="https://user-images.githubusercontent.com/723999/140095044-acc1ee5e-bda5-485c-800f-89152dfe30ce.png">

20px

![image](https://user-images.githubusercontent.com/723999/140095079-23b9bfd4-85b3-40c2-b045-9deb046b9e9c.png)

**Comment by Ghustavh97** [comment]
need help?

**Comment by adidahiya** [comment]
@Ghustavh97 do you have any concrete ideas / suggestions to fix this? At this point I'm considering going back to the original plan of dropping the icon font as a breaking change in v4.0.

**Comment by Ghustavh97** [comment]
@adidahiya were all the icons located in one svg file then exported to svg-fixer? because when I export the icons one by one they do come out looking fine.

Can you provide me with the reproduction steps that you took so I can look into it?

**Comment by adidahiya** [comment]
@Ghustavh97 if you look at the icon font files [here in @blueprintjs/icons@4.0.0-beta.6](https://unpkg.com/browse/@blueprintjs/icons@4.0.0-beta.6/lib/css/), you will see the visual regressions.

Check out https://github.com/palantir/blueprint/pull/5005 for my WIP attempt at fixing the problems. Most of the icons build pipeline is defined by scripts in the packages/icons/scripts/ folder.

**Comment by Ghustavh97** [comment]
@adidahiya I think I found the issue. Can you try removing this line and see if that works? https://github.com/palantir/blueprint/blob/fa33c7f8a4cc881d930b513969cbca9469d21e0e/packages/icons/scripts/generate-icon-fonts.js#L54

**Comment by adidahiya** [comment]
@Ghustavh97 wow you're right, removing that line seems to have fixed it! thanks for the help, I'll push up a fix ASAP :)

**Comment by Ghustavh97** [comment]
@adidahiya no problem
