### ISSUE TITLE
Default color palette?

### ISSUE THREAD

**Issue by dkasipovic** [palantir/blueprint#5009]
DISCLAIMER: This might be a dumb question, but I assure you I searched for this and found nothing, so I might be just being dense.

How do I get theme to be like in Blueprint docs?

**Comment by adidahiya** [comment]
What do you mean by "theme"?

**Comment by dkasipovic** [comment]
Apologies, for some reason initially buttons were blue (like bootstrap blue), not gray. I must have been doing something wrong because when I switched to dark mode, add started working, it turned out alright.
