### ISSUE TITLE
4.0.0-beta tags missing fixes included in 4.0.0-alpha-0?

### ISSUE THREAD

**Issue by forana** [palantir/blueprint#5014]
I decided to try out the 4.0 beta in my project and noticed that #3979 is still an issue there - which is strange, since its fix (#4623) merged into `v4` in April and was included in the `core@4.0.0-alpha` tag.

Looking into it - there's quite a lot that's in the `4.0.0-alpha` tag and not the `4.0.0-beta` tags: https://github.com/palantir/blueprint/compare/@blueprintjs/core@4.0.0-beta.8...@blueprintjs/core@4.0.0-alpha.0

Probably a more useful comparison is `next` and `v4`: https://github.com/palantir/blueprint/compare/next...v4

So, I'm guessing I'm missing something - but couldn't find any info on what the beta tags are supposed to be.

**Comment by adidahiya** [comment]
What was included in 4.0.0-alpha is now part of the set of changes we plan to release in Blueprint v5 -- see https://github.com/palantir/blueprint/wiki/Blueprint-v4.0-&-v5.0-semantic-swap and https://github.com/palantir/blueprint/wiki/4.x-Changelog#april-13-2021. In short, 4.0.0-alpha is no longer supported, and those "fixes" will come with v5.0.

Sorry for the delay here; we had to shift our focus to color contrast and accessibility fixes and de-prioritize [v5.0](https://github.com/palantir/blueprint/wiki/Blueprint-5.0) for the time being. I plan to return to those v5.0 changes in December or January.

**Comment by forana** [comment]
Got it - thanks!
