### ISSUE TITLE
Enable StrictMode in Blueprint 3

### ISSUE THREAD

**Issue by nrakochy** [palantir/blueprint#5025]
#### Environment

- `core 3.51.3`

#### Question

Hi there, 

Thanks for the great library 👍 Is there any upgrade path to use `StrictMode` in version 3? I see multiple tickets & PRs (for example, [here](https://github.com/palantir/blueprint/pull/4623)) to address this, as well as [the roadmap for v5](https://github.com/palantir/blueprint/wiki/Blueprint-5.0), so I see that is in active development. 

That said, is this backwards compatible w/ v3? If there was a canonical list of components that could be updated in place it would be appreciated.

On the other hand, if this is not compatible w/ v3, that would be a helpful insight as we consider upgrade options. Thanks!

**Comment by adidahiya** [comment]
We'll be compatible with React strict mode in Blueprint v5.0, ETA for which is approximately January 2022.

**Comment by nrakochy** [comment]
Ah missed the notification on this one. Thanks for the feedback, much appreciated 👍
