### ISSUE TITLE
Table with ghost cells continues to scroll when there are no more rows

### ISSUE THREAD

**Issue by mattskrobola** [palantir/blueprint#5027]
#### Environment

- __Package version(s)__: blueprint 4 core and table

#### Code Sandbox

Link to a minimal repro:
https://codesandbox.io/s/cool-benz-es9oo?file=/src/App.js

#### Steps to reproduce

Create a scrollable Table with `enableGhostCells` set to true

#### Actual behavior

Scrollbar continues to scroll when reaching the bottom of the table. Also grabbing the scrollbar and dragging down creates more ghost rows.
![scrolling](https://user-images.githubusercontent.com/13280642/142129561-0d35780f-06c0-4eef-a940-45b50d646e7c.gif)
#### Expected behavior

The scrollbar stops scrolling when it reached the bottom of the table

Notes:
Scrolling over a frozen column to the bottom of the table behaves as normal

**Comment by adidahiya** [comment]
I've isolated the bug to occur between table v3.8.0 – v3.8.1

not present in v3.8.0: https://codesandbox.io/s/modern-sound-z9ul4?file=/src/App.js
present in v3.8.1: https://codesandbox.io/s/awesome-rumple-k40zq?file=/src/App.js

**Comment by mattskrobola** [comment]
From reverting commits locally https://github.com/palantir/blueprint/pull/3771 seems to be the PR that caused this cc @adidahiya

**Comment by adidahiya** [comment]
Fixed in v4 by #5115
