### ISSUE TITLE
Resizing a frozen column creates empty space / overlaps other columns

### ISSUE THREAD

**Issue by mattskrobola** [palantir/blueprint#5028]
#### Environment

- __Package version(s)__: blueprint 4 core and table

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/quirky-mendeleev-30dm3?file=/src/App.js

#### Steps to reproduce

![resizeFrozenColumn](https://user-images.githubusercontent.com/13280642/142131580-2f2740b2-b495-4fd6-82af-1da25313bf18.gif)

The bug only appears if you pass `widths` to the Table component and update them via `onColumnWidthChanged`.
Scrolling in the table re-renders the columns normally.

#### Possible solution

Not a solution but It looks like the column header resizes 1 cycle behind each update e.g when changing the width from 100 to 200 the header width stays at 100. Then when changing from 200 to 300 the header width changes from 100 to 200.

**Comment by adidahiya** [comment]
This seems related to https://github.com/palantir/blueprint/issues/3833, likely the same cause, another regression introduced in table v3.8.1, similar to https://github.com/palantir/blueprint/issues/5027

**Comment by adidahiya** [comment]
This doesn't seem to be a problem on the `next` branch anymore, I can't repro it. Possibly fixed by #5057 or #5115. Please let me know if it's still broken after pulling in the next release (table 4.0.0-beta.14), and I'll reopen this issue.

**Comment by adidahiya** [comment]
I'm seeing this issue still present in an application after upgrading to 4.0.0-beta.14. Will need to look into it some more.
