### ISSUE TITLE
Feature request: Add a sticky columns for the table component

### ISSUE THREAD

**Issue by amitripshtos** [palantir/blueprint#503]
Hey guys!
Honsetly, your table is one of the best components I saw for react, it has really almost everything.

I really wanna use it, but the only problem I have is that it does not support sticky columns

sticky columns: Columns that stick to the left/right of the table and while dragging the x-axis, it stays in it's place.

I would like to know if you guys having this feature in your minds, and if not I would like to know if you will considerate having the feature in the future.

If not, I would like to get an advice of how to achieve this one in your table components.
Thanks!

---

edit by @adidahiya:

tags for searchability: fix, fixed, freeze, frozen

**Comment by zerovox** [comment]
Want to add a +1 to this suggestion, was able to switch my existing product over from fixed-data-table today to the blueprint table, and this is the only feature that got lost in the shuffle.

**Comment by kraf** [comment]
Does it make sense to add sticky rows to this request as well or should I create a separate issue?

**Comment by michael-yx-wu** [comment]
It should probably be two PRs but feel free to request here since the work is going to be very similar

**Comment by llorca** [comment]
Sticky rows are implicitly included here, we'll do both at the same time

**Comment by vaenow** [comment]
Thank you guys for your `Table`.  👍 
I would like to know when to release the latest version which include frozen rows/cols. 🙂

**Comment by llorca** [comment]
@vaenow we're still working on it! Watch out for this issue and upcoming releases 👍
