### ISSUE TITLE
After upgrading to @blueprintjs/core v4, menu items don't dismiss popover2

### ISSUE THREAD

**Issue by zachkirsch** [palantir/blueprint#5030]
#### Environment

- __Package version(s)__:
  ```json
        "@blueprintjs/core": "^4.0.0-beta.8",
        "@blueprintjs/popover2": "^0.11.3",
  ```
- __Operating System__: Mac
- __Browser name and version__: Chrome 95.0.4638.69

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-p5p4b?file=/src/index.tsx

#### Steps to reproduce

1. Upgrade core to 4.x
2. Create a popover2 that wraps a that renders a Menu in the popover
3. Click the button to open the popover'ed menu, and then click a menu item

#### Actual behavior

The popover doesn't dismiss

#### Expected behavior

The popover should dismiss

#### Possible solution

I'm guessing this is because the latest version of popover2 [depends on](https://github.com/palantir/blueprint/blob/afcf7ac1bc3861b6b6606e801161874761a37341/packages/popover2/package.json#L38) blueprintjs/core@3.x, so there's a mish-mash of `bp3` and `bp4` css classes:

<img width="751" alt="Screen Shot 2021-11-21 at 3 42 50 PM" src="https://user-images.githubusercontent.com/8902272/142783758-dd2a937f-e37e-4e15-a9d5-98e4ae735f98.png">

Possible solution: Upgrade popover2's dependency on @blueprintjs/core to 4.x.

**Comment by adidahiya** [comment]
@zachkirsch you need to upgrade to popover2 v1.0.0-beta.x; the 0.x range is not compatible with blueprint core 4.x

**Comment by zachkirsch** [comment]
Ah my bad, thanks :) Do you think it's valuable to throw that version onto 4.x version of the docs
<img width="290" alt="Screen Shot 2021-11-22 at 3 38 23 PM" src="https://user-images.githubusercontent.com/8902272/142932355-2f4d9c43-0e3c-4c52-b944-9bfaa8608365.png">
?

**Comment by adidahiya** [comment]
Hmm, you're right, it looks like the popover2 package doesn't have a version number in either the 3.x or 4.x docs. I'll file a bug for that.
