### ISSUE TITLE
Toast drop focus on close

### ISSUE THREAD

**Issue by HZ-labs** [palantir/blueprint#5032]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^3.51.3",
        "@blueprintjs/datetime": "^3.23.6",
        "@blueprintjs/icons": "^3.27.0",
        "@blueprintjs/popover2": "^0.12.8",
        "@blueprintjs/select": "^3.18.10",
- __Operating System__: Mac Os
- __Browser name and version__: Chrome last

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

1. Open Tost
1. Open select or focus input field
1. After closing toast - focus is droped

#### Actual behavior

https://www.loom.com/share/c072f69bea5d4ea9a3dbbfe21be32379

#### Expected behavior

After closing Toast a focus is not droped

**Comment by adidahiya** [comment]
What do you mean focus is "dropped"? I don't quite understand what's happening at the end of your screencap there... it seems like you just click the `<select>` dropdown to open it and the recording ends there.

**Comment by HZ-labs** [comment]
> What do you mean focus is "dropped"? I don't quite understand what's happening at the end of your screencap there... it seems like you just click the `<select>` dropdown to open it and the recording ends there.

on the toast closed - the select is auto closing or input lost a focus.

- Open Tost
- Open select or focus input field
- on closing toast - input lost a focus

**Comment by HZ-labs** [comment]
@adidahiya I create this sandbox.
1. Change input on Column 1 and `Tab` to next input.
2. On first input changing I showing a Toast
3. Toast is closing and returning focus to first input without my actions

How I can fix it?

Example: https://www.loom.com/share/2a6ba36af5524178b4750dbb25016c29
Sandbox: https://codesandbox.io/s/blueprintjs-toast-focus-issue-v90in?file=/src/App.js

**Comment by HZ-labs** [comment]
@adidahiya Do you have some news and this example is an understandable?

**Comment by adidahiya** [comment]
Ah yes, I see the problem now, thanks for the additional example. This is a bug introduced by https://github.com/palantir/blueprint/pull/4904, and I think it can be easily fixed by changing how we set the `shouldReturnFocusOnClose` prop for Toaster's Overlay. I'll look into it.

**Comment by tnrich** [comment]
Yep I also seem to be hitting this issue @adidahiya 

Do you know when the fix for this issue will land? 

Thank you!

**Comment by adidahiya** [comment]
I've opened a PR to fix the bug... should be released today or tomorrow

**Comment by tnrich** [comment]
Thanks for your hard work @adidahiya !
