### ISSUE TITLE
Scrolling the table body when selecting columns

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#505]
Sub-issue of #298 (but I didn't want to add it to the already pretty long list...)

### Enhancement request

- __Package version(s)__: core 1.6, table 1.3
- __Browser and OS versions__: OS X 10.11.6, Chrome 57

#### Steps to reproduce

![2017-01-17 12 30 15](https://cloud.githubusercontent.com/assets/723999/22032099/08613c5c-dcb1-11e6-99d8-036af673427a.gif)

#### Expected behavior

When creating a drag selection across table columns and I want to keep selecting beyond the visible viewport, I want the table body to scroll along with my mouse cursor. At the moment, this works pretty inconsistently, as shown in the above GIF. Once I scroll downwards a little, horizontal scrolling gets activated too, but the interaction still isn't very smooth.

Relatedly, it'd be nice to have a table option (probably in dropdown in the top left) that lets me select all columns / cells at once.

**Comment by tgreenwatts** [comment]
Related: https://github.com/palantir/blueprint/issues/950

**Comment by cmslewis** [comment]
This works as of 1.22.0! :D
