### ISSUE TITLE
Allow adding a leftElement to a NumericInput (Blueprintjs 4.0.0-beta.10)

### ISSUE THREAD

**Issue by danaugrs** [palantir/blueprint#5051]
Please allow adding a `leftElement` to a `NumericInput`!
(Blueprintjs 4.0.0-beta.10)

**Comment by adidahiya** [comment]
What is your use case? What do you want to display there which is not an icon (already supported by the `leftIcon` prop)?

**Comment by danaugrs** [comment]
I need to display a button there (with a Select for the user to select a currency). I'm currently using an `InputGroup` and have implemented part of the numeric logic in my own component. It would be nice to be able to use `NumericInput` instead, with all its conveniences.

**Comment by adidahiya** [comment]
Ok, that sounds reasonable. Out of curiosity could you share a screenshot or design mockup?

We can add a prop `<NumericInput leftElement>` which behaves the same as the one for `<InputGroup>`.

**Comment by danaugrs** [comment]
Great and sure! Here's a GIF showing it in action:

![UbifolioTransactionDialog4](https://user-images.githubusercontent.com/5261448/144657760-26a82e38-8374-4792-a490-da50c77c017f.gif)

This is from my project https://ubifolio.com/
I just put it live, still some known issues but feel free to try it out yourself!

**Comment by alex-c** [comment]
Any update on this? Adding a button as `leftIcon` works fine, but wrapping it in a `Popover2` breaks the layout:

![image](https://user-images.githubusercontent.com/1643832/172645190-c594c1aa-7245-42f5-957b-5a89e2096e55.png)

**Comment by adidahiya** [comment]
I don't quite have the bandwidth to work on this right now, but would happily take a PR. These examples of wanting to rendering a Tag or Button (optionally wrapped in a Popover2) on the left seem reasonable, and Blueprint should support this kind of layout.
