### ISSUE TITLE
Support ESLint v8 in ESLint plugin

### ISSUE THREAD

**Issue by dallonf** [palantir/blueprint#5052]
#### Environment

- __Package version(s)__: @blueprintjs/eslint-plugin@0.3.5
- __Browser and OS versions__: Browser N/A, macOS 11.6.1 

#### Feature request

[ESLint v8](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#comma-dangle) has been out for some time now - it would be great if the Blueprint plugin supported it!

**Comment by JoeDuncko** [comment]
Just wanted to leave a note here that I had some issues with `@blueprintjs/eslint-plugin` (both v0 and v1) + `create-react-app` v5.

I was getting the following error:

```
Failed to load config "react-app" to extend from.
```

After a bunch of trial and error, the solution ended up being to pin my eslint version to v8. Apparently having eslint v7 pinned in `@blueprintjs/eslint-plugin` caused cascading eslint v7s to be used throughout my dependency tree, causing weird problems.

Hope this helps someone else!


EDIT:

Guess I spoke too soon, I'm not getting this error when I try to build:

`Failed to load plugin '@blueprintjs' declared in 'package.json': Class extends value undefined is not a constructor or null`

At this point I'm just going to uninstall `@blueprintjs/eslint-plugin` until it's updated.
