### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by l1x** [palantir/blueprint#5054]
#### Environment

- __Package version(s)__:    
    "@blueprintjs/core": "4.0.0-beta.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"

- __Operating System__: MacOS
- __Browser name and version__:  Chrome

#### Code Sandbox

Link to a minimal repro: https://github.com/DataDeft/web-debug

#### Steps to reproduce

Clone repo, yarn install, yarn build, yarn serve, open the link and watch the blank page.

#### Actual behavior

It seems when using Vite as opposed to Webpack this problem surfaces. I do not know enough of frontend development to be able to investigate myself.

Uncaught ReferenceError: require is not defined
    at vendor.75daa434.js:64

#### Expected behavior

Run without error.

#### Possible solution

Not sure.

**Comment by adidahiya** [comment]
That's surprising; we ship esm modules (see the `/lib/esm/` folder in the built NPM package) and Vite should support those. It looks like similar issues / questions have been raised with Vite, like https://github.com/vitejs/vite/issues/3409. You can probably work around this issue using vite-plugin-commonjs.

**Comment by adidahiya** [comment]
Looking a bit more closely, though, it seems like these lines may be causing the problem:

https://github.com/palantir/blueprint/blob/54cb93ff67936f39b485350383cbcdb3feaaedea/packages/icons/src/iconSvgPaths.ts#L23-L24

Those are the only places we ship code referencing `require()`. I should be able to swap those back to use `import` statements instead...

**Comment by l1x** [comment]
Thanks @adidahiya! I am trying exactly that right now. :)

**Comment by l1x** [comment]
Confirmed. Your change (that you linked above) is causing this. When I move back to version 3.51.3 it works because it uses still the old import ( as opposed to require).

**Comment by adidahiya** [comment]
fixed in v4 by #5108

**Comment by l1x** [comment]
Thanks a lot @adidahiya !
