### ISSUE TITLE
Popover focus issue when target is an input

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#5070]
Hey @adidahiya and others,

I'm seeing this issue on the latest release (I believe it was introduced in 3.50.0): 

https://codesandbox.io/s/blueprintjs-toast-focus-issue-forked-c7qn4?file=/src/App.js

![image](https://user-images.githubusercontent.com/2730609/145883775-b02fc95d-fae8-45b3-920d-fa899dacb04e.png)

(and a variation of it: https://codesandbox.io/s/blueprintjs-toast-focus-issue-forked-rrdjg?file=/src/App.js )

![image](https://user-images.githubusercontent.com/2730609/145883899-a192e50e-a4df-410a-a7a6-4dc60ea3fe77.png)

This used to work as recently as 3.49.1: 

https://codesandbox.io/s/blueprintjs-toast-focus-issue-forked-ettzg?file=/src/App.js

Not sure what the fix is but I'd recommend setting up a test for it when you do fix it :) 

Thanks!

**Comment by adidahiya** [comment]
v3.50 fixed `enforceFocus` behavior, and this "fixed" behavior seems to have broken your use case. You can work around this by setting `enforceFocus={false}`.

**Comment by tnrich** [comment]
@adidahiya pretty sure that doesn't fix it for me. I'll double check

**Comment by tnrich** [comment]
@adidahiya welp I was wrong, looks like your suggestion does fix it. Going to try `enforceFocus={false}` in my project and see if that fixes things for me. Will let you know. Thanks!

**Comment by tnrich** [comment]
@adidahiya whoops was applying the `enforceFocus=false` to the wrong popover! Works great. Thanks!
