### ISSUE TITLE
Switch component in Blueprint

### ISSUE THREAD

**Issue by Montana** [palantir/blueprint#5071]
The `switch` component in Blueprint, displays no border when selected/unselected. I included this component in a React component as follows:

```javascript
import {Component} from "react";
import {Switch} from "@blueprintjs/core";
import React from "react";

class BPrintMain extends Component{

    render(){
        return (
            <Switch id="switch-input-3" label="Public"  disabled={false} />
        )
    }
}

export {BPrintMain};
```

There's still no border, I'm also including the Blueprint CSS files from the CSS of my main component the CSS:

```javascript
@import "~@blueprintjs/core/lib/css/blueprint.css";
@import "~normalize.css";
@import "~@blueprintjs/icons/lib/css/blueprint-icons.css"
```
I also tried:

```css
input, button, textarea, :focus {
    outline: none;
}
```
To no avail! Any help would be greatly appreciated. 

Cheers,
Montana Mendy

**Comment by adidahiya** [comment]
@Montana can you reproduce this issue using a code sandbox (linked in the issue template)?

In the future, please fill out the issue template. It helps to include all that information we request there like package version information.

Do you have a screenshot of the issue you're experiencing?

**Comment by Montana** [comment]
Thank you @adidahiya, after using the sandbox, I was able to figure this out. I really appreciate it.

Cheers!
