### ISSUE TITLE
Old colors and shadows support 

### ISSUE THREAD

**Issue by cstffx** [palantir/blueprint#5077]
I have noticed some significant changes in the colors of the components (buttons, checkbox, radios and inputs) in v4. I love old colors and shadows, but I can't get stuck on old versions just for that. Could support for old colors and shadows be kept in a separate theme? Is there a way to keep the old shadows?

**Comment by cstffx** [comment]
Looking at the code I found that you guys thought about it. Excellent work.

**Comment by adidahiya** [comment]
> Looking at the code I found that you guys thought about it.

I'm guessing you're referring to [`legacyColors.ts`](https://github.com/palantir/blueprint/blob/b55e258e427b5cb1ccc9f0de7317c5b66773445e/packages/colors/src/legacyColors.ts) on the `next` branch? We do export these legacy color hex values in JS in Blueprint v4.x, but we do not support the old styles in CSS. If you upgrade to Blueprint v4.x you will get the new styles and it will be tough to revert to the old v3 styles (you'd have to compile Blueprint CSS yourself and replace a lot of Sass color variables).

We might consider adding more robust / official support for Blueprint theming in the future, but this is a large undertaking and is not currently on the roadmap (related: #248, #4029).
