### ISSUE TITLE
Allow handlers for cell events

### ISSUE THREAD

**Issue by olivergeorge** [palantir/blueprint#508]
Cells don't currently support onClick, onMouseOver and onMouseOut props.  I think it's useful to add these.

My particular interest is to highlight the row (for which I need on onMouseOver & onMouseOut) and to allow the user to click on a row (onClick).

**Comment by adidahiya** [comment]
> My particular interest is to highlight the row (for which I need on onMouseOver & onMouseOut) and to allow the user to click on a row (onClick).

do the current selection APIs not address this use case? check out `selectionModes` under http://blueprintjs.com/docs/#components.table-js.api.table

**Comment by olivergeorge** [comment]
Perhaps I'm missing something.  How would you achieve either "highlight row on hover" or "on row click callback" using selection modes?

**Comment by tgreenwatts** [comment]
Closing this in favor of the using the custom contents of a cell
