### ISSUE TITLE
TimezonePicker's Input embedded in a Dialog doesn't accept text

### ISSUE THREAD

**Issue by sapphybara** [palantir/blueprint#5082]
#### Environment

- __Package version(s)__: `@blueprintjs/core: "^3.26.1"`, `@blueprintjs/timezone: "3.9.18"`
- __Operating System__: Windows 10 `20H2`
- __Browser name and version__: Edge version `6.0.1054.62`

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-scrr7?file=/src/CoreExample.jsx

#### Steps to reproduce

1. Embed a `<TimezonePicker />` inside a `<Dialog />`
1. Open the Dialog
1. Open the TimezonePicker, try to type into the input

#### Actual behavior

No text is accepted into the input

#### Expected behavior

Typing into the input should filter the timezones

#### Possible solution

Perhaps something to do with the two separate `div.bp3-portal` elements existing at once?

**Comment by adidahiya** [comment]
You forgot to include timezone package CSS.

![image](https://user-images.githubusercontent.com/723999/148421351-08242936-3e5b-4f5a-9ae5-ccd3ce43a09d.png)

Forked your sandbox and got it working here: https://codesandbox.io/s/blueprint-sandbox-forked-8gxmj?file=/src/index.tsx:200-263

**Comment by sapphybara** [comment]
This issue is not resolved, I am still unable to type into the input at the top of the `TimezonePicker` in your sandbox. Moreover, we're using blueprint `3.x`, not the `4.x` beta. And why isn't the CSS automatically included when installing `@blueprintjs/timezone`?

**Comment by adidahiya** [comment]
I updated my sandbox to use 3.x, it seems to work for me:

![2022-01-06 14 39 06](https://user-images.githubusercontent.com/723999/148441374-9f0f9e78-3b78-4c7d-863d-32bfe905a348.gif)

> And why isn't the CSS automatically included when installing @blueprintjs/timezone?

This is the case for all Blueprint packages and the "getting started" documentation instructs you to import the main CSS file for each package you install. We don't make any assumptions for you about how you will load Blueprint CSS onto the page.
