### ISSUE TITLE
EditableCell2.editableTextProps.placeholder is not working

### ISSUE THREAD

**Issue by zizizheng** [palantir/blueprint#5083]
#### Environment

- __Package version(s)__: 3.52.0
- __Operating System__: Win10
- __Browser name and version__: Chrome 96.0.4664

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprintjs-table-forked-u9up5?file=/src/DataTable.js

#### Steps to reproduce

1. check the sandbox example, it's just not working

#### Actual behavior

placeholder remains empty

#### Expected behavior

show placeholder

**Comment by adidahiya** [comment]
Looks like this is not supported; we override the `placeholder`: https://github.com/palantir/blueprint/blob/813c3d429064b77d18c2196028ccfae23f51905a/packages/table/src/cell/editableCell2.tsx#L161. But this is not documented here.

We should either document that it is unsupported, or add support for overriding the placeholder prop. Most likely the latter.
