### ISSUE TITLE
Modern CSS button oulined error

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#5088]
#### Environment

- __Package version(s)__: 3.52.0
- __Operating System__: Mac Os Monterrey
- __Browser name and version__: Chrome 

#### Code Sandbox

[Sandbox](https://codesandbox.io/s/blueprintjs-5088-nfz2y?file=/src/App.tsx)

#### Steps to reproduce

1. Create a new project 
2. Add blueprintjs to the project and include `@blueprintjs/core/lib/css/blueprint-modern.css`
3. Create a button with intent `warning` and `outlined`

#### Actual behavior

![Capture d’écran 2022-01-06 à 17 24 57](https://user-images.githubusercontent.com/9548473/148415482-ff44ce9f-555a-48bc-8cf1-7852d677be15.png)

#### Expected behavior

![Capture d’écran 2022-01-06 à 17 25 43](https://user-images.githubusercontent.com/9548473/148415600-67ab876f-3b43-4090-8907-893bf68bd68e.png)

**Comment by adidahiya** [comment]
We're not maintaining `blueprint-modern.css` anymore; all progress on the "modern" colors is being done in the `next` branch, on the 4.0.0-beta.x release line. Please upgrade to the latest 4.0.0-beta.x version(s).

**Comment by adidahiya** [comment]
It works in the [v4 docs](https://blueprintjs.com/docs/versions/4/#core/components/button):

![image](https://user-images.githubusercontent.com/723999/148422554-fe686f26-f826-4518-add3-61791b15cfc3.png)
