### ISSUE TITLE
Support for minimal and outline modifiers for Select

### ISSUE THREAD

**Issue by mishywangiepie** [palantir/blueprint#5090]
support for minimal and outlined modifiers for the button rendered by a `<Select>`.

<img width="97" alt="Screen Shot 2022-01-07 at 2 21 23 PM" src="https://user-images.githubusercontent.com/25167557/148616288-55e73aa6-1cb8-46d2-9975-e2ef5af0b5f1.png">

**Comment by adidahiya** [comment]
`<Select>` and `<Select2>` require you to render your own button. They don't render the button themselves. So if you want to display a minimal or outlined button, you simply need:

```tsx
<Select2>
  <Button minimal={true} />
</Select>
```
