### ISSUE TITLE
Nested Overlay(s) with `canEscapeKeyClose=true` closes all overlays instead of just the recent opened one

### ISSUE THREAD

**Issue by Mai-Lapyst** [palantir/blueprint#5099]
#### Environment

- __Package version(s)__: @blueprintjs/core@3.52.0
- __Operating System__: Arch Linux
- __Browser name and version__: Firefox 95.0.2

#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-bztv1

#### Steps to reproduce

1. Create an Element that uses an Overlay (such as Dialog)
2. Create an second Element that uses an Overlay inside the content of the first one (such as a Popover)
3. Open the first & second elements
4. Hit ESC
5. All overlays (dialogs / popovers) will be closed

#### Actual behavior

All overlays get closed when you hit ESC.

#### Expected behavior

That only the recent opened one gets closed.

#### Possible solution

Prevent bubbeling/propagation of the key event used to implement the close-on-Escape feature;
alternatively an new option for overlays could be added, in order to configure the behaviour.

**Comment by adidahiya** [comment]
We don't currently have support for this behavior. Open for PRs
