### ISSUE TITLE
pt-popover-target adds float:left, visually moving the targets

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#512]
I have these buttons that have a popover on them. When I hover, the span around the buttons grows by 4 pixels, which is a little gross. Pretty minor, but does anyone know why the `pt-popover-target` gets a `float: left;` on it after it's been hovered on once?

![growing_span](https://cloud.githubusercontent.com/assets/24398123/22088222/53b5ead6-dd97-11e6-95b3-042420774e8b.gif)

@cmslewis and @giladgray for thoughts

**Comment by giladgray** [comment]
@tgreenwatts  let's look at this together later this week. i know what's going on, want to figure out if it's blueprint or downstream.

**Comment by cmslewis** [comment]
Issue is specifically with button groups that contain `pt-popover-target`s as immediate children: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/popover/_popover.scss#L151

Will see if we can get rid of this now with the Popover2 graduation (#2007).
