### ISSUE TITLE
Blueprint accessibility request

### ISSUE THREAD

**Issue by Shaah** [palantir/blueprint#5135]
#### Environment

- __Package version(s)__: 3.53.0 
- __Browser and OS versions__: Broad range

#### Question

Dear Blueprint Development Team,

In connection with the topic accessibility and WAI-ARIA properties I'm posting this on behalf of my team:
- Whether there are plans for including ARIA attributes in the upcoming versions including 3.0 and 4.0?
- If yes, what's the timeline/roadmap for including these properties.

We are a German-American software company; using Blueprint since years and currently facing accessibility issues, since Blueprint components do not come with ARIA properties out of the box.

Thank you, and looking forward to hearing from you!
—
Shaahin Mohammadi 
 
(Sorry for posting this here! Didn't find any other official channels)

**Comment by adidahiya** [comment]
Are there specific aria properties you are expecting on Blueprint components/elements? In general, we try to apply all the necessary accessibility HTML attributes necessary for good WCAG / VPAT compliance out of the box with Blueprint. If there are specific gaps in this area, please list them and we can try to address them.
