### ISSUE TITLE
Set placeholder for select and suggest query.

### ISSUE THREAD

**Issue by bofa** [palantir/blueprint#5138]
#### Environment

- __Package version(s)__: Future
- __Browser and OS versions__: All?

#### Feature request

To be able to set query placeholder to custom string in Select and Suggest components. Hardcoded now is "Filter..." and "Search"

This would be useful for specific edge cases and i18n.

https://github.com/palantir/blueprint/blob/6f6310d1e226cd46a6b02fc959c62c530aff5c82/packages/select/src/components/select/select.tsx#L183

#### Examples

```
const SelectSeries = Select.ofType<Item>();

<SelectSeries
  {...props}
  queryPlaceholder="Enter query"
/>
```

**Comment by adidahiya** [comment]
Near that line in the code you linked, you can see that `{...inputProps}` is spread to the element after the default placeholder value. So you can simply do:

```
<SelectSeries inputProps={{ placeholder: "Enter query" }} />
```
