### ISSUE TITLE
Popover2 Warning - Portal uses legacy React context

### ISSUE THREAD

**Issue by edengueta** [palantir/blueprint#5139]
#### Environment

- __Package version(s)__:  core- 3.53.0, popover2- 0.13.0, react- 17
- __Browser and OS versions__:  chrome 97, ubuntu 20

#### Question

When i opened <Popover2> i  got warned:
 
Warning: Legacy context API has been detected within a strict-mode tree.
The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
Please update the following components: Blueprint3.Portal

How should i solve this?

**Comment by adidahiya** [comment]
This will be fixed in Blueprint v5, which will include full compatibility with React strict mode: https://github.com/palantir/blueprint/wiki/Blueprint-5.0

**Comment by taha1ahmed** [comment]
Hi @adidahiya, the link you've shared above says
> Blueprint 5.0 is planned for release in mid 2022
Is there any visibility how soon we'll be able to actually start using v5.0.
