### ISSUE TITLE
Feature request: Allow default "light" navbar styles with pt-dark

### ISSUE THREAD

**Issue by nerdstep** [palantir/blueprint#515]
My use case is an editor where I'm using `.pt-dark` for the theme but would like to have two navbars, one dark and one light. My current solution is to apply `.pt-dark` to all of my containers except for the one containing the default navbar, but it would be much nicer if I only had to set this once at the top of the document and then simply override the styles on the one navbar.

**Comment by giladgray** [comment]
Sorry, this just isn't practical to implement. You should stick with the approach of applying `.pt-dark` to all containers except the light one. 

We made a conscious decision for CSS sanity that once you go `.pt-dark`, you can't go back to the light.  The dark theme is implemented as a simple descendant `.pt-dark <selector>`. If we were to add a light theme escape hatch, it would likely double the total volume of CSS. We'd need to do the following _for every component and modifier_:

```css
.component { defaults } 
.pt-dark .component { dark theme }
.pt-dark .pt-light .component { light theme resets }
```
