### ISSUE TITLE
Alert doesn’t have canEscapeKeyClose nor canReturnKeyConfirm

### ISSUE THREAD

**Issue by alminde** [palantir/blueprint#517]
It would be cool if the alert component would have a `canEscapeKeyClose` prop like the dialog component has. Also having `canReturnKeyConfirm` would be doubly cool.

**Comment by llorca** [comment]
The return key sounds cool, I guess the primary button should be focused right away. The alert is already autofocused so you can tab twice to get to the confirm button.

We made a conscious decision for alerts to not be dismissible on `esc`, since users should always acknowledge the alert message (this is also why you can't click on the backdrop to dismiss an alert).

**Comment by invliD** [comment]
@llorca Is this still your current opinion? We'd love to use an alert similar to one of the docs examples, namely trashing files. I think it's reasonable to cancel the confirm alert using escape or clicking the backdrop, since it's not something the user has to acknowledge.

If the intent of Alerts is just that (information that needs acknowledgement), the docs should be updated and this example removed.

**Comment by alminde** [comment]
At least for me, there’s a fair amount of use cases where it would be awesome to be able to easily dismiss alerts by hitting escape or clicking the backdrop. Like @invliD mentions, trashing files would be one such case.

Maybe, if `canEscapeKeyClose` were a thing, its default could simply be `false`, and maybe the docs could mention something about how it’s recommended to only set it to `true` under some limited set of circumstances?

**Comment by adidahiya** [comment]
I agree with @alminde and @invliD. Might as well make the API more robust & flexible but still set good defaults that nudge users to follow our design guidelines.

**Comment by llorca** [comment]
Before I get to `canEscapeKeyClose`: the `Alert` component is opinionated by nature -- there will be specific interactions and behaviors that aren't always customizable. It's a particularity of this component, as most of our other components are atomic and completely flexible. We did a lot of research when we were building `Alert`, and I still stand behind our decisions.

From the developer standpoint, these are the two considerations I see now:
- use `Alert`, not much customization possible, trust the system to provide the ideal behaviors;
- use `Dialog`, roll your own alert and customize everything you want.

From the design system perspective, `Alert`s and `Dialog`s are mutually exclusive:
- either `Alert` is a thing, it has to be opinionated and will provide common alert patterns out of the box;
- `Alert` is not a thing, everything is done through the generic `Dialog`, and consumers can bend it to their use cases.

@invliD @alminde @adidahiya I tend to agree with `canEscapeKeyClose` at this point, I'm okay with it 👍 But if we're planning more flexibility and customization besides that, we should consider either recommending `Dialog` to consumers or straight up killing `Alert`. I see no point in Blueprint providing two modal components with the same level of flexibility that essentially do the same thing.

**Comment by adidahiya** [comment]
@llorca fair argument 👍 I defer to your call here

**Comment by adidahiya** [comment]
@llorca @giladgray is `<Alert>` actually used much internally? If not, we should just remove it.

**Comment by invliD** [comment]
I would use it quite a bit if these restrictions weren’t in place.

**Comment by giladgray** [comment]
`Alert` is damn near impossible to search for, way too much noise. no usages appeared immediately though. i'd be okay with relaxing some restrictions (like adding these props), as the minimal API is quite nice for quick popups.

**Comment by warpdesign** [comment]
@adidahiya the issue has been closed but only `canEscapeKeyClose` prop has been implemented yet, not `canReturnKeyConfirm`?
