### ISSUE TITLE
HACKHACK: tests using deprecated initMouseEvent() method

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#5173]
test-commons and the table package test harness use the [deprecated `MouseEvent.initMouseEvent()` method](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent). we should migrate to using the [`MouseEvent()` constructor](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent) instead.

**Comment by SoulPancake** [comment]
Can you please assign this issue to me @adidahiya
