### ISSUE TITLE
Unable to import css files in Next.js

### ISSUE THREAD

**Issue by collegewap** [palantir/blueprint#5182]
#### Environment

- __Package version(s)__: 3.54.0
- __Operating System__: Windows 10
- __Browser name and version__: Chrome 99

#### Code Sandbox

https://stackblitz.com/edit/nextjs-w1gosj

#### Steps to reproduce
According to the [Next.js documentation](https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules), I should be able to import blueprint js to a my component. However, when I try to do that, it fails.

#### Actual behavior

![image](https://user-images.githubusercontent.com/9767383/159161525-ea7139d3-d157-4c83-a12a-9e9573febb57.png)

#### Expected behavior

It should work!

**Note**: I am not trying to include the styles globally. I want to use blurprint.js in a particular component only.

**Comment by adidahiya** [comment]
Just remove the `~` in the import paths. Our bundler (webpack) uses those tildes to locate node modules imports, while yours (next.js) does not require them. You'll have to adapt the Blueprint documentation to your work with the particulars of your build system, but things should generally work fine out of the box:

https://stackblitz.com/edit/nextjs-lswx5o?file=pages/index.js

```
import 'normalize.css';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
```
