### ISSUE TITLE
A comma is added to menu items in the docs

### ISSUE THREAD

**Issue by absaroui** [palantir/blueprint#5190]
#### Environment

- __Package version(s)__: @blueprintjs/core 4.0.0-rc.1
- __Operating System__: Linux Mint 20.1
- __Browser name and version__: Mozilla Firefox 84.0.1

#### Steps to reproduce

Menu docs: https://blueprintjs.com/docs/#core/components/menu

#### Actual behavior

A comma is added in each menu item. The same thing is happening in MultiSelect component.

![image](https://user-images.githubusercontent.com/19497631/159370639-bb00dd45-34ac-4032-a2a2-d78f5e3e7722.png)

#### Expected behavior

No comma.

#### Possible solution

I noticed the comma is added in the menu item icon.

![image](https://user-images.githubusercontent.com/19497631/159370977-7933b70e-e655-4085-8739-133f15c3ca21.png)

**Comment by adidahiya** [comment]
Fixed by https://github.com/palantir/blueprint/pull/5189, I just haven't updated the docs site yet
