### ISSUE TITLE
React 18 is not supported as a peer dependency

### ISSUE THREAD

**Issue by milohansen** [palantir/blueprint#5205]
#### Environment

- __Package version(s)__:  @blueprintjs/core: 4.0.2
- __Operating System__:  Windows 11
- __Browser name and version__: n/a

#### Steps to reproduce

1. Upgrade `react` and `react-dom` to version 18
2. Run `npm install`

#### Expected behavior

`npm install` successfully completes.

#### Actual behavior

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1082015/160690638-6addecfd-2c4f-40be-98ad-d62992ed8837.png)

#### Possible solution

Update "peerDependencies" in [package.json](https://github.com/palantir/blueprint/blob/develop/packages/core/package.json) to support React 18.

**Comment by VadimCiv** [comment]
Same issue here. Can't update react lib 

`npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8 || 17" from @blueprintjs/core@4.0.4`

**Comment by lavrton** [comment]
@adidahiya can you do the same for `popover2` package?

**Comment by adidahiya** [comment]
@lavrton whoops, sorry, I missed that package somehow. Fixing in #5255.

**Comment by kcculhwch** [comment]
I'm having the same issue with datetime@4.4.28
-- update
I see the issue is already open here #5699
