### ISSUE TITLE
Text go beyond the Dialog boundary

### ISSUE THREAD

**Issue by eherozhao** [palantir/blueprint#5221]
#### Environment

- __Package version(s)__: "3.28.1"
- __Browser and OS versions__: Worked in BabylonJS Editor V4.1.0 and MacOS 10.15.7

#### Question
This is the code snippet of my custom component.
```
export function FailureDialog(props: FailureDialogProps) {
  const {error, onBack} = props;
  const failureTitle = `There was a problem!`;
  const text = `${error}`;
  return (
    <>
      <div className={Classes.DIALOG_BODY}>
        <p>
          <Icon icon="cross" intent={Intent.NONE} /> {failureTitle}
        </p>
        <Text>{text}</Text>
      </div>
      <div className={Classes.DIALOG_FOOTER}>
        <div className={Classes.DIALOG_FOOTER_ACTIONS}>
          <Button onClick={onBack}>Back</Button>
        </div>
      </div>
    </>
  );
}

```

When the `text` becomes longer, it will go beyond the 
```
<Dialog
      >
<FailureDialog>
</Dialog>
```
boundary. 
How should I solve it? Thank you.

**Comment by adidahiya** [comment]
@eherozhao can you please create a code sandbox to demonstrate the issue?

**Comment by eherozhao** [comment]
https://codesandbox.io/embed/blueprint-sandbox-forked-g6v73t?fontsize=14&hidenavigation=1&theme=dark 
You can use this link as a reference. The text is beyond the Text component boundary and I would like to find a way to solve it. Thank you.

**Comment by eherozhao** [comment]
> @eherozhao can you please create a code sandbox to demonstrate the issue?

https://codesandbox.io/embed/blueprint-sandbox-forked-g6v73t?fontsize=14&hidenavigation=1&theme=dark
You can use this link as a reference. The text is beyond the Text component boundary and I would like to find a way to solve it. Thank you.

**Comment by adidahiya** [comment]
If you're sticking with the `<Text>` component, just add the `ellipsize={true}` prop. Or just drop that component and use a more common `<p>` element. Your example has a very long string without any whitespace, so it will not wrap unless you apply the right CSS styles.

**Comment by eherozhao** [comment]
Is there any component provided by BlurprintJS can wrap the texts without custom CSS style? I know `ellipsize` and would like to find a way to show all text. It is not only for the long string, but also for a long sentence. The long sentence with whitespaces will also fail to be wrapped.

**Comment by eherozhao** [comment]
> If you're sticking with the `<Text>` component, just add the `ellipsize={true}` prop. Or just drop that component and use a more common `<p>` element. Your example has a very long string without any whitespace, so it will not wrap unless you apply the right CSS styles.


Is there any component provided by BlurprintJS can wrap the texts without custom CSS style? I know `ellipsize` but would like to find a way to show all text. It is not only for the long string, but also for a long sentence. The long sentence with whitespaces will also fail to be wrapped.

Also, I am not sure closing the issue without getting the agreement from the requester is a good way. Maybe have a 2 days SLA is an option.

**Comment by eherozhao** [comment]
I figured it out by adding a CSS break-word. Thank you. I hope the Text component can provide some kind of features in the future.
