### ISSUE TITLE
TimeZone Picker Issue inside dialog

### ISSUE THREAD

**Issue by ShriRamaJeyam** [palantir/blueprint#5263]
#### Environment

- __Package version(s)__: 4
- __Operating System__:  MacOS
- __Browser name and version__:  Chrome 100, Firefox

#### Code Sandbox
https://codesandbox.io/s/q34ktm?file=/src/index.tsx

#### Actual behavior
The search/filter bar in timezone picker inside dialog does not work.

#### Expected behavior
The search/filter bar in timezone picker inside dialog must work.

**Comment by adidahiya** [comment]
You need to set `enforceFocus={false}` on the Dialog. See related issues/comments like https://github.com/palantir/blueprint/issues/3854#issuecomment-557999268.
