### ISSUE TITLE
Navbar - ":disabled" class does not work on buttons

### ISSUE THREAD

**Issue by EliasGabrielsson** [palantir/blueprint#527]
### Bug report
When using `:disabled` class on a `<button>` in a `<nav>` the button is still activated.

- __Package version(s)__: `1.6.0`
- __Browser and OS versions__: Chromium, Version 55.0.2883.87 Built on Ubuntu , running on elementary 0.4 (64-bit)

#### Steps to reproduce

```
<nav className="pt-navbar .modifier">
            <div className="pt-navbar-group pt-align-left">
                <div className="pt-navbar-heading">Left</div>
            </div>
            <div className="pt-navbar-group pt-align-right">
                <button className="pt-button pt-minimal pt-icon-cog .pt-disabled"></button>
            </div>
</nav>
```

<button className="pt-button pt-minimal pt-icon-cog .pt-disabled"></button>

#### Actual behavior

Still enabled.

#### Expected behavior

Disabled as described here: http://blueprintjs.com/docs/#components.button

**Comment by llorca** [comment]
The correct line should be:
`<button className="pt-button pt-minimal pt-icon-cog" disabled></button>`

You can't put `.` in the `className` field. The `pt-disabled` class gives you disabled styles, while the `disabled` attributes disables the button.

**Comment by giladgray** [comment]
Modifiers use CSS selector syntax, where `:` denotes HTML attributes (a la `:hover` etc) and `.` denotes CSS classes (like `.pt-button`). You should remove the prefix character when applying the attribute or class to an element. 

Inspecting the HTML of example elements will show you the correct way to apply Blueprint modifiers.
