### ISSUE TITLE
Source map warnings in Create-React-App 5 

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#5274]
#### Environment

- __Package version(s)__:
     "@blueprintjs/core": "^4.2.1",
    "@blueprintjs/datetime": "^4.1.4",
    "@blueprintjs/popover2": "^1.1.4",
    "@blueprintjs/select": "^4.1.4",

- __Operating System__: Mac OS Monterey 12.2.1 
- __Browser name and version__:  Chrome Version 100.0.4896.127 (Build officiel) (x86_64)

#### Code Sandbox

https://codesandbox.io/s/romantic-swirles-f6w5g9

The issue is not visible in CodeSandbox console but you can find source map errors in browser console. May need to play with console options as css warnings can be hidden.

#### Steps to reproduce

1. Create a react app with CRA in version 5
2. Install blueprintjs and import them 
   e.g : 
   ```ts
   import '@blueprintjs/core/lib/css/blueprint.css'
   import '@blueprintjs/icons/lib/css/blueprint-icons.css'
   import '@blueprintjs/datetime/lib/css/blueprint-datetime.css'
   import '@blueprintjs/select/lib/css/blueprint-select.css'
   import '@blueprintjs/popover2/lib/css/blueprint-popover2.css'
   ```
3. Start the app 

#### Actual behavior

<img width="1199" alt="Capture d’écran 2022-04-27 à 19 04 01" src="https://user-images.githubusercontent.com/9548473/165580630-4967d2ce-2bef-4a37-8c05-c4c90830ac1d.png">

#### Expected behavior

No source map errors

**Comment by LoiKos** [comment]
I find these two issues related but i still have the problem : 

https://github.com/palantir/blueprint/issues/5111 

https://github.com/palantir/blueprint/issues/3500

**Comment by adidahiya** [comment]
@LoiKos is this still a problem in recent versions of Blueprint?

**Comment by LoiKos** [comment]
@adidahiya this is fine now. My bad i should have close this issue !
