### ISSUE TITLE
React console warning with "indeterminate" <Checkbox>

### ISSUE THREAD

**Issue by benny-medflyt** [palantir/blueprint#529]
I have a simple checkbox: `<Checkbox indeterminate={true} />`

Everything seems to work fine, but there is a warning in the browser development console:

```
Warning: Unknown prop `indeterminate` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by giladgray** [comment]
Yep this is a known React warning, but your app will continue to function as expected. 

It appears in our unit tests actually. Thanks for filing, it's easy to resolve.
