### ISSUE TITLE
[NonIdealState] `Spinner` is not visible when used as a `NonIdealState` icon

### ISSUE THREAD

**Issue by saruman1234** [palantir/blueprint#5292]
#### Environment

- __Package version(s)__: @blueprintjs/core@4.3.0

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-z3nnje

#### Steps to reproduce

I find it is common to combine `NonIdealState` and `Spinner` to create a loading state.

```tsx
<NonIdealState icon={<Spinner />} title="Loading" />
```

#### Actual behavior

The recent changes for muted `NonIdealState` icons in #5278 also affect `Spinner` when used as the icon.

The spinner appears faintly, and is quite hard to see.

![image](https://user-images.githubusercontent.com/56399322/167509255-af653da5-41b6-4333-97ea-a56c63fbc561.png)

#### Expected behavior

I would expect the spinner to appear as it does elsewhere.

#### Possible solution

The recent opacity and stroke changes for muted `NonIdealState` icons should apply to `.bp4-icon` not all `svg path` elements.

**Comment by adidahiya** [comment]
Good catch! I'll fix this ASAP.
