### ISSUE TITLE
[React 18] `ResizeSensor` cannot be used as a JSX component

### ISSUE THREAD

**Issue by ptgamr** [palantir/blueprint#5313]
#### Environment

- __Package version(s)__: 4.3.2

#### Steps to reproduce

1. Upgrade to React 18 & its `@types/react` packages
1. Got this TS error related to `ResizeSensor`

```
TS2786: 'ResizeSensor' cannot be used as a JSX component.
  Its instance type 'ResizeSensor' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'boolean | {} | ReactPortal | ReactChild | null | undefined' is not assignable to type 'ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.

```

#### Possible solution

Looking at the return type of `render()` method inside `resizeSensor.d.ts`, looks like the new type of React 18 no longer consider `{}` as a valid `ReactNode`

![Screen Shot 2022-05-24 at 2 56 52 AM](https://user-images.githubusercontent.com/1619740/169848176-4a95234c-be70-4900-89c5-640477c4135c.png)

**Comment by ptgamr** [comment]
I would love to help if possible, @adidahiya would you be able to point me how those types got generated ?

**Comment by adidahiya** [comment]
That return type seems to be generated by this line, where `React.Child.only()` apparently has an incompatibility between `@types/react` v16 <> v18:

https://github.com/palantir/blueprint/blob/85dab97343d3780d5180afe86739d0aee0236e62/packages/core/src/components/resize-sensor/resizeSensor.tsx#L67

I think you can work around it by manually annotating the return type of that `render()` function with something that is assignable to `React.ReactNode`.

**Comment by PurkkaKoodari** [comment]
The difference seems to be that React 18 specifies `ReactFragment = Iterable<ReactNode>`, while React 16 specifies `{} | ReactNodeArray`. The definition of `only` further drops the array, leading to a declared type that is an union of what's left of `ReactNode`. That then breaks when the new `@types/react` doesn't allow `{}`.

Submitting a PR in a moment to fix this + another React 18 issue I noticed.
