### ISSUE TITLE
官网的文档示例就不能支持直接在页面展示源码么，还非要点进github看源码？真的够累的...

### ISSUE THREAD

**Issue by meisuTJU** [palantir/blueprint#5319]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__:

**Comment by adidahiya** [comment]
I google translated this as:

> Can't the documentation example on the official website support displaying the source code directly on the page, or do I have to go to github to see the source code?

Right now I find it sufficient that we just link to github source code rather than embed it directly. Is there any problem with that approach? Can you not access github.com?

**Comment by meisuTJU** [comment]
> 

I can access github.com, but I hope to be able to view the source code directly under the component like antdesign( https://ant.design/components/button/ ), which will be very convenient.

**Comment by adidahiya** [comment]
Sorry, that's not a documentation feature I'm interested in building right now, as the alternative solution of navigating to the github.com source code is sufficient. I don't think it's worth the additional complexity of embedding source code.
