### ISSUE TITLE
Popover2 rendering bug on Firefox

### ISSUE THREAD

**Issue by alex-c** [palantir/blueprint#5332]
#### Environment

- __Package version(s)__: Core v4.4.0, Popover2 v1.3.0
- __Operating System__: Windows 10
- __Browser name and version__: Firefox 100.0.2 (64-bit)

#### Code Sandbox

This bug doesn't seem to appear in Code Sandbox! 

I created a minimal repository to demonstrate the problem here: https://github.com/alex-c/render-bug It can also be observed in the `demo` subproject of this repo, where I first encountered this problem: https://github.com/alex-c/blueprint-datagrid 

My attempt to recreate the situation in Code Sandbox: https://codesandbox.io/s/blueprint-sandbox-forked-fdw9jc?file=/src/Popover2Example.tsx

#### Steps to reproduce

1. `npm install`
2. `npm start`
3. Click ob the button

#### Actual behavior

On Firefox with light theme: 

![image](https://user-images.githubusercontent.com/1643832/170884949-5440bcd6-35f7-4284-a69b-6ca374447175.png)

On Firefox with dark theme:

![image](https://user-images.githubusercontent.com/1643832/170884982-2fc53bb7-d29c-4926-8cbf-041a8c45e2c4.png)

#### Expected behavior

The expected behaviour as can be seen in the Code Sandbox linked above:

![image](https://user-images.githubusercontent.com/1643832/170885325-d11b7f9f-77dc-4b68-92c4-9d785eeab2c9.png)

#### Possible solution

No idea, so far...

**Comment by alex-c** [comment]
I thought at first that it was working fine on Chrome, but now noticed that the arrow is actually missing:

![image](https://user-images.githubusercontent.com/1643832/170885499-2b44c7e9-df05-47b0-be85-3a58830e23ae.png)

**Comment by adidahiya** [comment]
Did you remember to import `"@blueprintjs/popover2/lib/css/blueprint-popover2.css"`?

**Comment by alex-c** [comment]
Hello, I did indeed forget to import the stylesheet... thanks and sorry to have bothered you with this!
