### ISSUE TITLE
FR: Add `underline` boolean prop to Tabs

### ISSUE THREAD

**Issue by ryan10132** [palantir/blueprint#534]
It would be nice if the `Tabs` React component had an underline boolean prop that added an underline if true (something for the tabs to rest on)

**Comment by llorca** [comment]
In my opinion, this is has to with styling and composition, and is not a React prop matter. We'll think about how to best support such use cases as part of our tabs refactor: https://github.com/palantir/blueprint/issues/363#issuecomment-270200926 https://github.com/palantir/blueprint/issues/261

**Comment by ryan10132** [comment]
sounds good. Should we close this out?

**Comment by llorca** [comment]
I'll let Gilad and others take a look -- we can close this out then or after we ship the new tabs 📦

**Comment by giladgray** [comment]
this seems solved by a few lines of CSS

**Comment by ryan10132** [comment]
@giladgray yes but the point was that every time I use the `Tabs` component (4-5) I add the same lines of css.
