### ISSUE TITLE
Fill prop doesn't work on MultiSelect 2 (when coming from MultiSelect)

### ISSUE THREAD

**Issue by bvandrc** [palantir/blueprint#5353]
#### Environment

- __Package version(s)__: 4.4.0
- __Operating System__: Windows
- __Browser name and version__: Chrome

#### Steps to reproduce

1. Can see this doesn't work by visiting MultiSelect2 example page https://blueprintjs.com/docs/#select/multi-select2 . "Fill container width" does not work

#### Actual behavior

MultiSelect2 `fill` prop doesn't work.

#### Expected behavior

MultiSelect2 `fill` prop to work the same as the original MultiSelect's did

**Comment by adidahiya** [comment]
Looks like Select2 and Suggest2 also have this problem:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/723999/171939472-2176ba62-0bda-46d8-be6b-c8a6b563bc55.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/723999/171939487-297ba05c-117e-4ce2-86a6-12a8cb7c409c.png">

**Comment by adidahiya** [comment]
Fixed in https://github.com/palantir/blueprint/pull/5354, and I also improved the examples for each of these so we can test the props
