### ISSUE TITLE
Will there be a DateRangeInput2 now that there is a DateInput2?

### ISSUE THREAD

**Issue by goldflag** [palantir/blueprint#5372]
I know that `Datetime2` is still in it's early stages, but I am wondering if there will be a `DateRangeInput2` since currently there is just a `DateInput2` and `TimezoneSelect` (which is really great work).

**Comment by adidahiya** [comment]
Yes, I'm working on that this week.

**Comment by adidahiya** [comment]
This was released back in July in @blueprintjs/datetime2: https://github.com/palantir/blueprint/wiki/4.x-Changelog#july-20-2022
