### ISSUE TITLE
Select's matchTargetWidth prop breaks in v4.4.0

### ISSUE THREAD

**Issue by jakejrichards** [palantir/blueprint#5374]
#### Environment

- __Package version(s)__: @blueprint/select@4.4.0
- __Operating System__: MacOS
- __Browser name and version__: Chrome 102.0.5005.115

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-5cuowz

#### Steps to reproduce

1. Upgrade @blueprint/select to `4.4.0`
1. Set `matchTargetWidth={true}` on the `Select` component

#### Actual behavior
The select popover does not match the button width.

#### Expected behavior
The select popover should match the button width.

**Comment by adidahiya** [comment]
Confirmed this is a regression.

Works with these versions:

<img width="707" alt="Screen Shot 2022-06-15 at 9 47 53 AM" src="https://user-images.githubusercontent.com/723999/173844410-1f90860f-cd1e-493a-856c-cdceb9da2003.png">

Broken here:

<img width="896" alt="Screen Shot 2022-06-15 at 9 52 41 AM" src="https://user-images.githubusercontent.com/723999/173844447-9dd16110-2874-4c2e-b55c-8a66ddfb126b.png">

**Comment by adidahiya** [comment]
Likely caused by this line change: https://github.com/palantir/blueprint/pull/5354/files#diff-3827f9b47467f2b80a99f4a695b78efe9e05bc87191267ec14e3a5c1a3a50c52L7-L15
