### ISSUE TITLE
[MultiSelect2] allow to create multiple items 

### ISSUE THREAD

**Issue by ZeRego** [palantir/blueprint#5384]
#### Environment

- __Package version(s)__:  4.2.0
- __Browser and OS versions__: 

#### Feature request

Multi select should allow the same behaviour we have in the tag input component where we can create multiple values at once. 
Multi select doesn't need to implement the same behaviour, it just needs to support creating multiple items at once. 

Existing typing
```
createNewItemFromQuery | undefined \| (query: string) => T
```
Proposed typing
```
createNewItemFromQuery | undefined \| (query: string) => T | T[]
```

#### Examples

How tag input works:

![tag input](https://user-images.githubusercontent.com/9117144/172145091-0d37b302-fe92-4be8-b612-77dcf2fed525.gif)

How multi select currently works

![multi select](https://user-images.githubusercontent.com/9117144/172145638-f6890239-dfe8-4e28-8f5f-96c49a374e9b.gif)

I would like to split the input by comma and add both `test1` and `hello` as new values.

**Comment by adidahiya** [comment]
sounds like a good feature request. accepting PRs ✅
