### ISSUE TITLE
Components typing not compatible with styled components

### ISSUE THREAD

**Issue by ZeRego** [palantir/blueprint#5387]
#### Environment

- __Package version(s)__: 4.5.1
- __Operating System__: 
- __Browser name and version__: 

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

```
import { Collapse } from '@blueprintjs/core';
import styled, { css } from 'styled-components';
 const Example = styled(Collapse)`display: grid;`;
```

#### Actual behavior

```
TS2769: No overload matches this call.
  Overload 1 of 2, '(component: AnyStyledComponent): ThemedStyledFunction<any, any, any, any>', gave the following error.
    Argument of type 'typeof Collapse' is not assignable to parameter of type 'AnyStyledComponent'.
      Type 'typeof Collapse' is not assignable to type 'StyledComponent<any, any, any, never>'.
        Type 'typeof Collapse' is not assignable to type 'string'.
  Overload 2 of 2, '(component: keyof IntrinsicElements | ComponentType<any>): ThemedStyledFunction<keyof IntrinsicElements | ComponentType<any>, any, {}, never>', gave the following error.
    Argument of type 'typeof Collapse' is not assignable to parameter of type 'keyof IntrinsicElements | ComponentType<any>'.
      Type 'typeof Collapse' is not assignable to type 'ComponentClass<any, any>'.
        Types of property 'getDerivedStateFromProps' are incompatible.
          Type '(props: ICollapseProps, state: ICollapseState) => { animationState: AnimationStates; height?: undefined; } | { animationState: AnimationStates; height: string; } | null' is not assignable to type 'GetDerivedStateFromProps<any, any>'.
            Types of parameters 'props' and 'nextProps' are incompatible.
              Property 'children' is missing in type 'Readonly<any>' but required in type 'ICollapseProps'.
```

![Screenshot 2022-06-17 at 15 06 33](https://user-images.githubusercontent.com/9117144/174316426-0b423c0c-7e77-4364-9fda-5ea3e27f09c9.png)

#### Expected behavior

No Typescript errors

#### Possible solution

Not sure what is the solution but the problem seems to have been introduced with [this PR](https://github.com/palantir/blueprint/pull/5266).

**Comment by adidahiya** [comment]
Ok. This feels like a weird quirk of HOCs like `styled`. Seems like there is no way for Blueprint components to enforce required `children` if we have to support this kind of usage. I'm open to making `children` optional again, though, if it improves the dev experience in this case.

**Comment by kamilwojtanowski** [comment]
Hello! We face the same issue, but in addition to that one, we have problems with Spinner component:
```
 'Spinner' cannot be used as a JSX component.
  Its instance type 'Spinner' is not a valid JSX element.
    139 |         <NonIdealState
  > 140 |           icon={<Spinner />}
        |                  ^^^^^^^
```
@adidahiya  I'm not sure if it is the same issue, if not I can fill a separate ticket.

**Comment by adidahiya** [comment]
@kamilwojtanowski that looks like this issue: https://github.com/palantir/blueprint/issues/5250#issuecomment-1102955684
