### ISSUE TITLE
[DateInput2] Doesn't have styling

### ISSUE THREAD

**Issue by ZeRego** [palantir/blueprint#5388]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "^4.5.1", "@blueprintjs/datetime2": "^0.2.0",
- __Operating System__: 
- __Browser name and version__: 

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

https://codesandbox.io/s/blueprint-dateinput2-css-bug-e8wo81?file=/src/index.js

#### Steps to reproduce

Import datetime2 css and use the component.
`@import "~@blueprintjs/datetime2/lib/css/blueprint-datetime2.css";`

#### Actual behavior

Date picker popup isn't styled properly

![Screenshot 2022-06-17 at 15 32 33](https://user-images.githubusercontent.com/9117144/174321120-6e7ab628-a6c6-4ee3-a78b-7cf35e704dd7.png)

#### Expected behavior

Date picker popup is styled properly

https://codesandbox.io/s/blueprint-dateinput2-using-dateinput-css-rbtgb1?file=/src/index.js

#### Possible solution

Seems like the DateInput2 still depends on the css file from DateInput. We should copy the styling from one component to the other. Perhaps the classnames should be different as well to prevent conflicts between the 2.

**Comment by adidahiya** [comment]
Just pull in `@blueprintjs/datetime/lib/css/blueprint-datetime.css` for now. They will be collapsed into a single file in Blueprint v5, but this is the approach we're taking for now, since we don't want to duplicate the DatePicker/DateRangePicker code in datetime2.

**Comment by ZeRego** [comment]
@adidahiya makes sense 👍 is there a v5 roadmap somewhere and how many active/core maintainers are there ?

**Comment by adidahiya** [comment]
https://github.com/palantir/blueprint/milestone/44 is the rough v5 roadmap but it needs to be cleaned up a bit... there's also a list of planned changes on the wiki here https://github.com/palantir/blueprint/wiki/Blueprint-5.0. Right now I'm the only active core maintainer.
