### ISSUE TITLE
[Datetime2] timezone select shows when timePrecision property is defined

### ISSUE THREAD

**Issue by ZeRego** [palantir/blueprint#5393]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "4.3.0",  "@blueprintjs/datetime2": "0.2.0",
- __Operating System__: 
- __Browser name and version__: 

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

https://codesandbox.io/s/blueprint-datetime2-timezone-bug-42m4kj?file=/src/DatetimeExample.tsx

```
import React, { useCallback, useState } from "react";
import { DateInput2 } from "@blueprintjs/datetime2";
import { format, parse } from "date-fns";

export function DatetimeExample() {
  const [dateValue, setDateValue] = useState<string | null>(null);
  const dateFnsFormat = "yyyy-MM-dd HH:mm:ss";
  const formatDate = useCallback(
    (date: Date) => format(date, dateFnsFormat),
    []
  );
  const parseDate = useCallback(
    (str: string) => parse(str, dateFnsFormat, new Date()),
    []
  );

  return (
    <DateInput2
      defaultTimezone="UTC"
      disableTimezoneSelect={false}
      timePrecision="millisecond"
      formatDate={formatDate}
      onChange={setDateValue}
      parseDate={parseDate}
      placeholder={dateFnsFormat}
      value={dateValue}
    />
  );
}
```

#### Steps to reproduce

1. set timePrecision to millisecond or second

#### Actual behavior

timezone select is visible

#### Expected behavior

timezone select should be hidden

**Comment by adidahiya** [comment]
This is intentional. Setting `timePrecision` to anything other than `undefined` will show the TimezoneSelect. If you want to hide it, use `showTimezoneSelect={false}`.
