### ISSUE TITLE
Unable to use copy feature blueprint tables

### ISSUE THREAD

**Issue by anik95** [palantir/blueprint#5399]
#### Environment
Windows 10
Node: 16.14.2
Npm: 8.5.0
Chrome

- __Package version(s)__: 
      blueprintjs/core: "^4.5.1",
    blueprintjs/table: "^4.3.1"

I am trying to copy cells from my table using clipboard data. But I am getting an error. I have used the prop 
getClipboardData={(row, col) => data[row][col]}

I tried consoling the output of the getClipboardData callback and I'm getting all the correct data. But the problem happens when I press ctrl + c, I am getting an error.

![blueprint](https://user-images.githubusercontent.com/17172760/175073804-f52de29b-901e-449c-bcc8-c26bda8e4a67.PNG)

Can someone please help me out here? Thanks in advance

**Comment by adidahiya** [comment]
Do you have a repro of this available in a code sandbox? I can't repro it in the [table docs](https://blueprintjs.com/docs/#table/features).

Looking at the code, this error would happen if [`navigator.clipboard`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) is not available, but that API should be available in all the environments supported by Blueprint.

Does the error happen if you deny the clipboard permission in the browser?

**Comment by anik95** [comment]
No I have the clipboard permission. It works fine for my react app in localhost but not in the server. Do you think it is because I am using HTTP instead of HTTPS?

**Comment by anik95** [comment]
Could you please let me know if you need any other information regarding this issue? Thanks

**Comment by spmacdonald** [comment]
I hit this today too, I think it is because not server from secure origin.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

**Comment by adidahiya** [comment]
Yep, that would do it. According to the docs linked by @spmacdonald, you need HTTPS. Closing for now, will re-open if necessary.
