### ISSUE TITLE
Initial location of `ContextMenu2` is misplaced when triggered inside a `Drawer`

### ISSUE THREAD

**Issue by GalvinGao** [palantir/blueprint#5411]
#### Environment

- __Package version(s)__: `@blueprintjs/core@4.5.1`, `@blueprintjs/popover2@1.4.1`
- __Operating System__: macOS Monterey 12.4, arm64
- __Browser name and version__: Chrome 103.0.5060.53

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 
https://codesandbox.io/s/blueprintjs-contextmenu2-in-drawer-wrong-position-w8jeu4

#### Steps to reproduce

1. Right click a ContextMenu2 trigger inside an opened drawer (in my setup the drawer was opened from right which is the default)
2. You should see that the ContextMenu is displayed at the top-most left-most position (I would guess 0, 0).

#### Actual behavior

The ContextMenu2 appears at the top-left corner.

#### Expected behavior

The ContextMenu2 should appear near where the trigger is.

#### Possible solution

- From https://github.com/palantir/blueprint/issues/4047 `johanwilson` suggests to use `boundary="viewport"` to mitigate the seemingly similar problem, however the popoverProps accepted by `ContextMenu2` explicitly doesn't includes this attribute (see https://blueprintjs.com/docs/#popover2-package/context-menu2). I've tried to just blindly ignore the TypeScript error and add such prop, but found no luck.

**Comment by adidahiya** [comment]
You'd need to override this `rootBoundary`, but that is currently not possible:

https://github.com/palantir/blueprint/blob/420abcf5b6dac677a262cb9b915189ec424d46c0/packages/popover2/src/contextMenu2.tsx#L207

I'm open to PRs to allow overriding that prop if it solves your reported issue.

**Comment by GalvinGao** [comment]
Filed a PR ;D
