### ISSUE TITLE
bp3 classes in svg icon files 

### ISSUE THREAD

**Issue by kamilwojtanowski** [palantir/blueprint#5413]
#### Environment

- __Package version(s)__: 4.x
- __Operating System__: any
- __Browser name and version__: any

#### Code Sandbox

Link to actual repro  ([blueprint code](https://github.com/palantir/blueprint/blob/develop/resources/icons/20px/shapes.svg?short_path=db03c1a)): 

#### Steps to reproduce
Read the SVG code.

#### Actual behavior

There are`bp3` classes in SVG files.

#### Expected behavior

There are only `bp4` classes  (if any) in SVG files

#### Possible solution

Maybe replace them, but since they are not working, they may not be needed anymore.

**Comment by adidahiya** [comment]
They're not classes, they're SVG ids. Dead code, but not actively harmful it seems.

**Comment by adidahiya** [comment]
The SVG files in `resources/` aren't very clean; many of them have extraneous markup. They get parsed and optimized before they get packaged into `@blueprintjs/icons` APIs. I'm not going to clean all of them up right now, but I'll remove the random "bp3-" references.
