### ISSUE TITLE
During it's exit transition, Omnibar is still visible when it disappears against dark background

### ISSUE THREAD

**Issue by DigiWorm0** [palantir/blueprint#5419]
#### Environment

- __Package version(s)__: @blueprintjs/select v4.4.1 with @blueprintjs/core v4.5.1 
- __Operating System__: Windows 11 21H2 
- __Browser name and version__: Firefox 102.0.1 

#### Code Sandbox

Minimal Reproduction: [Blueprint's own example](https://blueprintjs.com/docs/#select/omnibar) (Make sure dark-mode is on though)

#### Steps to reproduce

1. Create an Omnibar
2. Make the page use a dark background
3. Open the Omnibar
4. Close the Omnibar

#### Actual behavior

When transitioning out, Omnibar gets significantly blurred and then disappears as if it pops out of existence, 

#### Expected behavior

When transitioning out, Omnibar should get significantly blurred then smoothly fade out.

#### Possible solution

Instead of blurring when trying to fade-out, it should also transition it's opacity.

This issue is probably a bit nit-picky, but from a user's perspective it looks rather strange.

**Comment by adidahiya** [comment]
Yeah, I can see there's a bit of a white cloud visual "pop" when transitioning out. We'll need to revisit the CSS transitions here. Maybe it's more noticeable now with the darker dark theme colors in Blueprint v4.1+

![2022-07-08 07 57 43](https://user-images.githubusercontent.com/723999/177987879-d2cb2957-8af1-4161-97da-8e91ebb63b9b.gif)
