### ISSUE TITLE
Notes on patch, minor and major releases

### ISSUE THREAD

**Issue by alberto-f** [palantir/blueprint#5441]
Hello there, 

The library is working really well and has served the purpose I had in mind for v3.

Im currently updating my project to react 18. Im finding difficult to know what happens on releases. I have not been able to find notes about what changes are introduced on patch and minor releases and I think it would be really helpful when updating to newer versions.

Im saying this because checking in what version Blueprint supports react 18 was difficult. It is actually in version 4.1.0 and not in version 4.0.0. Version 4.1.0 also introduces a big change as of moving from node-sass to sass.

Being able to track these changes would help everyone. Im understanding that maybe resources are limited so it might not be doable.

This is just a suggestion as I understand that there might be million other things happening.

Thank you for the work done

**Comment by adidahiya** [comment]
The changelog lives here, it mentions all notable changes. You can easily search for "React 18" and figure out where we added support: https://github.com/palantir/blueprint/wiki/4.x-Changelog

That wiki page is also linked from the project's [CHANGELOG.md](https://github.com/palantir/blueprint/blob/develop/CHANGELOG.md).

**Comment by alberto-f** [comment]
Ok, i was not finding this page.

Thanks
