### ISSUE TITLE
Unable to load documentation page in Internet Explorer 11

### ISSUE THREAD

**Issue by rafiazman** [palantir/blueprint#5458]
#### Environment

- __Package version(s)__: -
- __Operating System__: Windows 10
- __Browser name and version__: Internet Explorer 11

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/

#### Steps to reproduce

1. Load https://blueprintjs.com/docs/ in Internet Explorer 11

#### Actual behavior

Docs page loads as a blank page with a blue line at the top.

![image](https://user-images.githubusercontent.com/7603038/180317525-535d0990-12b9-4e38-8139-8cc2d8088714.png)

#### Expected behavior

The docs page to display

**Comment by SoulPancake** [comment]
This is essentially the issue 
and there are a couple of solutions for this
Can you assign this to me?
![image](https://user-images.githubusercontent.com/70265851/188274882-38afc821-6c9f-44b2-b80b-2ab97fbcca96.png)

**Comment by adidahiya** [comment]
We are dropping support for IE11 very soon in Blueprint v5.0: https://github.com/palantir/blueprint/issues/5143

I don't see a good reason to continue supporting IE11 in the documentation site. Most of Blueprint v4.0 works in IE11, but if you want to see the docs site you'll have to use a different browser. IE11 has been deprecated for a long time anyway.

I declined [another IE11 support request](https://github.com/palantir/blueprint/issues/4569#issuecomment-1156622356) a few months ago, and I'm going to have to decline this one for the same reason.
