### ISSUE TITLE
DateInput doesn't fire onChange/onError when an empty selection is made

### ISSUE THREAD

**Issue by lucasray** [palantir/blueprint#546]
### Bug report

- __Package version(s)__: datetime 1.5.0

#### Steps to reproduce

1. Using `DateInput`, select a valid date.
2. Clear the input (by selecting all, delete), blur from the input
  2.a. Note that upon reselecting the input, the `DatePicker` popover has no selected date

#### Actual behavior

Consumer has no indication that the date selection has changed.

#### Expected behavior

Either an `onChange(undefined)` event is triggered (so `onChange` typings should be `(Date | undefined) => void`), or less desirably but still understandably `onError(undefined)` should be called.

**Comment by adidahiya** [comment]
sort of related to #504 / #524?

**Comment by lucasray** [comment]
awesome, yes I believe #524 will address this

**Comment by cmslewis** [comment]
@lucasray I just updated the PR description in #524 to declare this issue fixed by those changes. I'll close this for now, but let us know if you're still observing the same problem on the latest release (1.7 as of this writing).
