### ISSUE TITLE
Date Range Picker- set default months

### ISSUE THREAD

**Issue by ericjiya** [palantir/blueprint#5485]
#### Environment

- __Package version(s)__:  @blueprintjs/datetime, probably the latest version
- __Browser and OS versions__: Chrome, MacOS 12.4

#### Question

 I'm help to resolve the default month issue for a project. It's using the date range picker with minDate and maxDate settings. When I open it, the default shown two months are the middle value of min and max, e.g. min is 2021/11/01, max is yesterday, the default months are Mar and Apr 2022. Tried to set startDate and default Value, but didn't work. 

Can you show me an example how to set the default months as the last two month (Jun and July)?

**Comment by adidahiya** [comment]
Use the `initialMonth` prop: https://codesandbox.io/s/blueprint-sandbox-forked-q43wvk?file=/src/DatetimeExample.tsx
