### ISSUE TITLE
How to trigger context menu open on-double-click

### ISSUE THREAD

**Issue by SortaASoraous** [palantir/blueprint#5492]
#### Environment

- __Package version(s)__: Latest Blueprint
- __Browser and OS versions__: Mac OS Chrome

#### Question

As the title states: I'd like to trigger ContextMenu2 on-double-click instead of on-right-click. What would be the most efficient way to do this?

**Comment by adidahiya** [comment]
Perhaps you can use a controlled Popover2 (set the `isOpen` prop) and register a "dblclick" event listener in React with `<div onDoubleClick={...}>`
