### ISSUE TITLE
Update Core packages popper to @popperjs/core

### ISSUE THREAD

**Issue by craigboman** [palantir/blueprint#5500]
In the Core package.json there is a sub-dependency requiring an outdated popper.js package `popper.js@1.16.1`. is it possible to update the dependencies to popper v2 at @popperjs/core without breaking stuff? Just trying to clear some local CLI warnings I'm seeing around using outdated packages. Otherwise have no horse in the race.

Looking at updating: https://github.com/palantir/blueprint/blob/develop/packages/core/package.json

**Comment by adidahiya** [comment]
We've migrated to popper.js v2 in @blueprintjs/popover2. You should be using Popover2 and Tooltip2. The Popover and Tooltip components in @blueprintjs/core are deprecated and there is a [migration guide](https://github.com/palantir/blueprint/wiki/Popover2-migration). Popover2 will be merged into @blueprintjs/core v5.0 (coming soon in the next few weeks), at which point the popper.js v2 migration will be complete.
