### ISSUE TITLE
Toast should have an option to not show close button

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#5508]
#### Environment

- __Package version(s)__: 4

#### Feature request

The toast https://blueprintjs.com/docs/#core/components/toast should have a prop to not show the close button. We are showing a toast for a loading progress that has a cancel button. Users should not be able to close the toast, they should just be able to cancel it. Having a prop would be nicer than adding ugly css targeting. Maybe call it `noCloseButton`

**Comment by adidahiya** [comment]
I'm open to a PR for this. It would be better to call the new prop `isCloseButtonShown?: boolean` with a default value of `true`, just like `<Dialog>`.

**Comment by ohcnivek** [comment]
will work on this
