### ISSUE TITLE
Struggling to add data-cy to accordion item

### ISSUE THREAD

**Issue by Gayathri-Kesavakannan** [palantir/blueprint#5510]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question

Need to add data-cy attributes to accordion  button type and form item label 

Data-cy is amended to title or label text rather than attribute 

As temporary solution added data-testid 
Is there any limitation to add data-* to accordion or form ?? Can some one share sample help where to add it 
 
Thanks

**Comment by adidahiya** [comment]
We don't have "accordions" in Blueprint. Can you please share a code sandbox to demonstrate your problem (linked in the issue template)?
