### ISSUE TITLE
Dialogs are not vertically centered

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#552]
Dialogs are off center. It is particularly obvious when the dialog is larger
![image](https://cloud.githubusercontent.com/assets/24398123/22346826/5a5c6a94-e3ba-11e6-9a4a-c40ac2992f82.png)

### Bug report

- __Package version(s)__: 1.6.0
- __Browser and OS versions__: Chrome

**Comment by giladgray** [comment]
lol solid screenshot. this isn't really a "bug" because it's always been like this, since the very first Dialog iteration. i think the real issue here is resolving default dialog positioning.

**Comment by llorca** [comment]
Fair

**Comment by giladgray** [comment]
The half pixel problem will never go away... But last time I played with flexbox it seemed to work pretty well. I worry that we'll have to start encouraging folks to set explicit even dimensions

**Comment by giladgray** [comment]
I have rescheduled this for `2.x` as it's a tricky feature that we can tackle alongside some other Dialog weirdness such as scrolling support.

**Comment by llorca** [comment]
```
top: 50%;
left: 50%;
transform: translateX(-50%) translateY(-50%);
```

This is what we were using for dynamic vertical centering, and it used to position the dialog on a half pixel, making the whole thing blurry. Turns out that I can't repro the blurriness on latest Chrome, looks like good news. If flexbox doesn't work out, we can try using the snippet above again

**Comment by adidahiya** [comment]
that snippet looks good but...

> Turns out that I can't repro the blurriness on latest Chrome, looks like good news

how does it look in FF and IE?

**Comment by tgreenwatts** [comment]
@ryanmcnamara and @conradchan did some hacks to make this better for their usecase
Still pretty nasty and sad

**Comment by ryanmcnamara** [comment]
What's wrong with the dialog "sitting on a half pixel"

**Comment by llorca** [comment]
It makes the element blurry. Always align to the pixel grid for sharp visual results

**Comment by scottfr** [comment]
Any update on this issue? Is there a schedule for the 2.0 release?

**Comment by llorca** [comment]
@scottfr I'm working on it, I've been trying to make this change non-breaking so we can ship before 2.0. Otherwise expect this coming in 2.0 indeed
