### ISSUE TITLE
[DateRangeInput2] Add onOpenChange prop

### ISSUE THREAD

**Issue by standbyoneself** [palantir/blueprint#5529]
#### Feature request

It would be very helpful to add onClose (andOpen) callback or something like onVisibilityToggle while show/hide popup with calendar

#### Examples

For example, currently I am using DatePicker of Ant Design and I need to make HTTP request on datepicker close. There is `openChange` handles this

**Comment by adidahiya** [comment]
@standbyoneself DateRangeInput2 and other overlay-based components all have access to the [overlay lifecycle methods](https://github.com/palantir/blueprint/blob/f9d5b410947c80a5039755a3f1f92b1a627ecb4d/packages/core/src/components/overlay/overlay.tsx#L123-L150). You can use `<DateRangeInput2 popoverProps={{ onOpened, onClosed }}>`. [Here's a demo in a code sandbox](https://codesandbox.io/s/blueprint-sandbox-forked-30pop8?file=/src/DatetimeExample.tsx).

**Comment by standbyoneself** [comment]
Sorry I really need to read docs more carefully. Closed

**Comment by adidahiya** [comment]
No worries! This one is probably a little hard to figure out from the docs. I'll try to make it more discoverable.
