### ISSUE TITLE
Allow specification of popper padding on Popover2

### ISSUE THREAD

**Issue by tom-james-watson** [palantir/blueprint#5533]
#### Environment

- __Package version(s)__: core 4.2.0, popover2 1.1.3
- __Browser and OS versions__: Electron 19, macOS, linux, Windows

#### Feature request

I would like to be able to specify [popper boundary padding](https://popper.js.org/docs/v2/utils/detect-overflow/#padding) when using `Popover2`. There doesn't seem to be any way of doing so at the moment.

The use case is to avoid a popover from rendering flush up against the edge of the boundary, in this case the viewport.

**Comment by adidahiya** [comment]
@tom-james-watson you should be able to do that by overriding the options for the default modifiers. See an example of this in [this sandbox](https://codesandbox.io/s/blueprint-sandbox-forked-rhqjfg?file=/src/Popover2Example.tsx:605-610):

```ts
<Popover2 modifiers={{ preventOverflow: { options: { padding: 10 } } }}>
```

**Comment by tom-james-watson** [comment]
Thank you - I can confirm that works! :heart:
