### ISSUE TITLE
[DateRangeInput2]: footerElement prop does not render

### ISSUE THREAD

**Issue by fnziman** [palantir/blueprint#5537]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^4.7.0",
    "@blueprintjs/datetime": "^4.3.4",
    "@blueprintjs/datetime2": "^0.5.0",
    "@blueprintjs/popover2": "^1.5.0",
    "@blueprintjs/select": "^4.5.2",
    "@blueprintjs/table": "^4.5.0",
    "@blueprintjs/timezone": "^4.4.4",
- __Operating System__: MacOs Monterey 12.1
- __Browser name and version__: Chrome Version 104.0.5112.101

#### Code Sandbox
[Example](https://codesandbox.io/s/blueprint-sandbox-forked-crmux7?file=/src/DatetimeExample.tsx)

#### Steps to reproduce

1. add footerElement prop to DateRangeInput2 
1. ensure that it does not render

#### Actual behavior

No footer component rendered

#### Expected behavior

Render footer component

#### Possible solution

It seems that the prop is not used at all by DateRangeInput or by DateRangeInput2. Both DateInput and DateRangeInput, do render it. I think it just needs to be added

**Comment by fnziman** [comment]
Included a fix here: https://github.com/palantir/blueprint/pull/5538

**Comment by adidahiya** [comment]
Thanks for the bug report! This looks like an oversight. I'll review your PR to fix the issue.
