### ISSUE TITLE
Feature request: Expose popoverProps from IDateInputProps

### ISSUE THREAD

**Issue by lucasray** [palantir/blueprint#560]
I'd like a `DateInput` popover to overflow from an ancestor set to `overflow: auto`, so would like to be able to set `inline={false}` on the popover. Exposing a `popoverProps` property also removes the necessity to expose `popoverPosition`.

**Comment by leebyp** [comment]
Closely tied to discussion in #387

**Comment by preciselywilliam** [comment]
Is it possible to render the date input's popover as a portal? It seems I can't get it to work using popoverProps={{usePortal: true}}.
