### ISSUE TITLE
Doc: Props list documentation (autogen) broken for @blueprintjs/table package

### ISSUE THREAD

**Issue by nuco-alisharif** [palantir/blueprint#566]
### Bug report

- __Package version(s)__: Prepare Release 1.7.0 (#563)
- __Browser and OS versions__: N/A

#### Steps to reproduce

1. Visit: http://blueprintjs.com/docs/#components.table-js.api
2. For each class, list of props and details should be listed

#### Actual behavior

N/A

#### Expected behavior

N/A

**Comment by giladgray** [comment]
ok wow major oops! [this change in table/tsconfig.json](https://github.com/palantir/blueprint/pull/549/files#diff-4eb8935b51b3be64ba4ec73f9a697eb8R25) changed the contents of `dist/` to have `src/` and `preview/` subdirectories, which caused the `docs-interfaces` glob to fail.

easy to resolve, but we'll need to ship a patch as `@blueprintjs/table@1.4.0` is borked: main files are not where they're supposed to be.

we should add a task that tests the contents of the `dist/` directory to ensure this doesn't happen again.
