### ISSUE TITLE
Suggest2 menu items no longer scrollable

### ISSUE THREAD

**Issue by williamphan** [palantir/blueprint#5664]
#### Environment

- __Package version(s)__: v4
- __Operating System__: macOS
- __Browser name and version__: Chrome, Safari

#### Code Sandbox

It's not working in the documentation either. https://blueprintjs.com/docs/#select/suggest2

<img width="588" alt="image" src="https://user-images.githubusercontent.com/8607198/194865343-fc6fcc06-c34c-473f-8006-16e9ee1e2421.png">

#### Actual behavior

The whole list (suggest result) is visible and no longer scrollable. It is clipped if the results are longer than the page height.

#### Expected behavior

The list should be cut off (max-height) and scrollable if the result doesn't fit.

#### Possible solution

Add `max-height` and `overflow`. V3 works fine.

**Comment by adidahiya** [comment]
@williamphan thanks for the bug report. It's helpful if you can be more specific about the version number than simply "v4" (there are many versions under v4.x)

It looks like this bug has existed for Suggest2 for a while, at least since @blueprintjs/select v4.6.x -- I'll try to fix it ASAP.

**Comment by adidahiya** [comment]
Bug was introduced in #5369, will be fixed by #5667
