### ISSUE TITLE
End date time picker not accessible when selecting between small date ranges

### ISSUE THREAD

**Issue by ggdouglas** [palantir/blueprint#5675]
#### Environment

- __Package version(s)__: `4.11.3`
- __Operating System__: macOS
- __Browser name and version__: Chrome 106.0.5249.119
#### Code Sandbox

Link to a minimal repro: https://codesandbox.io/s/blueprint-datetime-end-range-yinb35

#### Steps to reproduce

Create a DateRangeInput2 component with a `minDate` and `maxDate` that spans less than a month and has the time picker enabled. e.g.

```jsx
<DateRangeInput2
  // ...
  minDate={new Date("2022-10-10 12:00:00")}
  maxDate={new Date("2022-10-20 12:00:00")}
  timePrecision={TimePrecision.MINUTE}
/>
```

#### Actual behavior

The time picker for the start time is visible but the end time picker is not. Only the start time can be modified from the picker in the popover.

<img width="441" src="https://user-images.githubusercontent.com/2968519/196264284-bea1bf3a-ce4f-45f8-b13c-1dab1ea37489.gif" />

#### Expected behavior

The end time picker (which only shows up in the multi-month selection view) should be visible.

#### Possible solution

Perhaps the `singleMonthOnly` type behavior can be overwritten when the `timePrecision` prop is present. Otherwise, it would be nice to have more direct control over how many month panels are rendered. Alternatively, the `timepicker` controls could be rendered outside of `datepicker-content` so that they are no longer dependent on the number of months being displayed in the popover.

**Comment by StefanoGagliardi** [comment]
Good morning, everyone,
I have known BLueprint for a while, initially used it for some projects and then having enjoyed it I decided to study the source code in depth.
If you are okay with it I would take over this issue, helping you in finding the solution and saving you time so you only have to validate the code.
In addition I was also thinking of writing an associated e2e test.
Thanks in advance @adidahiya
