### ISSUE TITLE
DateRangeInput2 doesn't work with Next.js

### ISSUE THREAD

**Issue by wbrijesh** [palantir/blueprint#5677]
#### Environment

- __Package version(s)__:  
@blueprintjs/core:        "^4.11.3"
@blueprintjs/datetime2:   "^0.7.0"
- __Browser and OS versions__: 
Firefox developer edition version 106.0b9
Mac OS 13.0 Beta (22A5331f)

#### Question

I am trying to use date range input component in a nextjs application

<img width="420" alt="Screenshot 2022-10-18 at 10 57 07 PM" src="https://user-images.githubusercontent.com/28498071/196502158-a81c33a2-f3b3-490e-92fa-b32c2227962f.png">

I get an error saying "Server Error TypeError: props.formatDate is not a function"
<img width="1014" alt="Screenshot 2022-10-18 at 10 58 58 PM" src="https://user-images.githubusercontent.com/28498071/196502567-9821126f-f4f5-43be-89e0-284d03a7686c.png">

I have installed [@blueprintjs/core](https://www.npmjs.com/package/@blueprintjs/core) and [@blueprintjs/datetime2](https://www.npmjs.com/package/@blueprintjs/datetime2) and added
`@import "~normalize.css";`
`@import "~@blueprintjs/core/lib/css/blueprint.css";`
`@import "~@blueprintjs/icons/lib/css/blueprint-icons.css";`
`@import "~@blueprintjs/datetime2/lib/css/blueprint-datetime2.css";`
`@import "~@blueprintjs/datetime/lib/css/blueprint-datetime.css";`
`@import "~@blueprintjs/popover2/lib/css/blueprint-popover2.css";`
`@import "~@blueprintjs/select/lib/css/blueprint-select.css";`

to styles/global.css

**Comment by adidahiya** [comment]
You need to supply `formatDate` and `parseDate`, they are required props. See the [props interface documentation here](https://blueprintjs.com/docs/#datetime2/date-range-input2.props-interface).
