### ISSUE TITLE
popover2 has no exported member PopperModifierOverride

### ISSUE THREAD

**Issue by andreash** [palantir/blueprint#5692]
With Popper2 1.7.4 and the new PopperModifierOverride feature I get a 

`Module '"@blueprintjs/popover2"' has no exported member 'PopperModifierOverrides'.ts(2305)`

I am using the[ example code](https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/popover2-examples/popover2Example.tsx) from your site. 

in VSCODE. Any ideas?

**Comment by adidahiya** [comment]
That export was very recently added, and it is unreleased. See the changelog: https://github.com/palantir/blueprint/wiki/4.x-Changelog#unreleased

I'll be cutting a release which includes that export some time today.
