### ISSUE TITLE
Cell truncated false throws Error

### ISSUE THREAD

**Issue by anandmani** [palantir/blueprint#570]
### Bug report

- __Package version(s)__: "@blueprintjs/table": "1.3.0"
- __Browser and OS versions__: Google Chrome Version 55.0.2883.95 (64-bit); macOS Sierra v10.12

#### Steps to reproduce

1. In Table (react) component, set a Cell's truncated prop to false

#### Actual behavior

Uncaught Error: React.Children.only expected to receive a single React element child.

#### Expected behavior

A cell with un-truncated content
![screen shot 2017-01-29 at 11 02 49 pm](https://cloud.githubusercontent.com/assets/9435853/22406311/2ec0a750-e677-11e6-998a-d95d4586780c.png)
![screen shot 2017-01-29 at 11 02 58 pm](https://cloud.githubusercontent.com/assets/9435853/22406312/2ec26a5e-e677-11e6-8bf8-ceb8c4c518ee.png)

**Comment by giladgray** [comment]
fascinating. you've given it string content, which is not "a single React element child," so of course it complains.

that said, I feel that string content should be supported... @themadcreator @gscshoyru any insight?

**Comment by michael-yx-wu** [comment]
we could perhaps relax the only child condition `LoadableContent` and instead wrap the children in a span? i imagine this could lead to some css pain.
```
<span>
  {React.Children.toArray()}
</span

an alternative would be we add a `value` prop to cell that takes string content.
