### ISSUE TITLE
Feature Request: Add Button "type" prop

### ISSUE THREAD

**Issue by prashnts** [palantir/blueprint#571]
It'd be quite nice to have a `type` `prop` on the `Button` component. Currently, it renders as `<button type="button" .../>`.

In a `form`, if there is a `<button type="submit"`, then the `onSubmit` event is fired if return key is pressed from an input field. This is a handy default behaviour which is worth keeping IMO.

I can make a PR adding a `type` prop to `Button` component and `ButtonType` (?) enum to implement this behaviour.

Thanks!

**Comment by giladgray** [comment]
Buttons most certainly support the `type` prop--they support all HTML props--it's just not listed in the documentation.

Try it yourself! `<Button type="submit" />` should work as expected.
