### ISSUE TITLE
EditableText onConfirm is not called when pressing ENTER on unchanged value

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/blueprint#573]
### Bug report

- __Package version(s)__: 1.7.0
- __Browser and OS versions__: chrome, osx

### Steps to reproduce

for an `EditableText` where `isEditing={true}`
1) Ensure element has focus
2) Press enter

Actual: the element loses focus and neither the confirm nor cancel is called the second time
Expected: 
1) the element does not lose focus at all 
or perhaps
2) the element loses focus and the cancel callback is called

In case this seems esoteric (which it does, here is the use case):

I have an `EditableText` where `""` is a forbidden value. To achieve this, I have the following code

```ts
    public render() {
        return (
            <EditableText
                isEditing={this.state.isEditing}
                value={this.state.value}
                onCancel={this.handleCancel}
                onChange={this.handleChange}
                onConfirm={this.handleConfirm}
                onEdit={this.handleStartEdit}
            />
        );
    }

    private handleStartEdit = () => {
        this.setState({ ...this.state, isEditing: true });
    }

    private handleChange = (name: string) => {
        this.setState({ ...this.state, isError: false, value: name });
    }

    private handleCancel = () => {
        this.setState({ ...this.state, isError: false, value: this.props.title, isEditing: false });
    }

    private handleConfirm = (name: string) => {
        const trimmedName = name.trim();

        if (trimmedName.length === 0) {
            this.setState({ ...this.state, isError: true });
            return;
        }

        this.setState({ ...this.state, isEditing: false });
        this.props.doSomething(trimmedName);
    }
```

If I remove all text, press enter, nothing happens (the confirm successfully blocks). However If I press enter *again* the element loses focus, and neither the confirm nor cancel callback is called. This seems like a bug to me as one of the two should definitely be called (either cancel if the element should be losing focus, or confirm if it should not).
I think this is tied up with pressing enter when the `EditableText` does not think there are changes.

**Comment by leebyp** [comment]
This is an after effect of #483. I think one of the worries there was `onConfirm` being called many times if you're just cycling through inputs with <kbd>Tab</kbd>.

On the same thread, I noticed that `onChange` is fired alongside `onCancel` & `onConfirm` too which feels weird to me.

How do folks feel about:
<kbd>Tab</kbd> <kbd>Enter</kbd> <kbd>Click away</kbd> calls `onConfirm` only
<kbd>Esc</kbd> calls `onCancel` only
<kbd>Other</kbd> cals `onChange` only

Wanna make sure that I'm not missing any reasoning from the initial implementation @giladgray @cmslewis @llorca

**Comment by giladgray** [comment]
it's very important to call `onChange` _with every change_ because that's the contract of the name, so that behavior must remain.

`onConfirm` and `onCancel` are special EditableText "events" based on user interaction, so they should be invoked on the keystrokes you mentioned above.

**Comment by leebyp** [comment]
@ryanmcnamara Apologies, this usage was not taken into account when fixing the previous issue. I've reverted the change in a new PR, and going back to the consistent approach of `blur === onConfirm` except when with <kbd>esc</kbd>. (slightly different to what you suggest since we always blur on both <kbd>enter</kbd> and <kbd>esc</kbd>)
