### ISSUE TITLE
Components are not working with next.js

### ISSUE THREAD

**Issue by erikdao** [palantir/blueprint#5761]
#### Environment

- __Package version(s)__: 4.12.0
- __Operating System__: macOS Ventura, M1 MacBook Pro
- __Browser name and version__: Chrome Version 107.0.5304.110 (Official Build) (arm64)
- __Nextjs version__: 13.0.4

#### Code Sandbox

```js
import { Button } from '@blueprintjs/core';

export default function Index() {
  return (
    <div className="">
      <h1>Home page</h1>
      <Button text='Refresh' intent='success' icon='refresh' />
    </div>
  );
}
```

#### Steps to reproduce

I'm trying a very basic nextjs setup with Blueprintjs and it seems that none of the components of the framework is working. They all produces the errors below

#### Actual behavior

```zsh
Server Error
TypeError: Class extends value undefined is not a constructor or null

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Module.__extends
(sc_server)/node_modules/@blueprintjs/core/node_modules/tslib/tslib.js (82:4)
eval
(sc_server)/node_modules/@blueprintjs/core/lib/cjs/common/abstractComponent.js (29:12)
eval
(sc_server)/node_modules/@blueprintjs/core/lib/cjs/common/abstractComponent.js (83:2)
(sc_server)/./node_modules/@blueprintjs/core/lib/cjs/common/abstractComponent.js
file://....../.next/server/app/page.js (338:1)
__webpack_require__
file://....../.next/server/webpack-runtime.js (33:42)
eval
(sc_server)/node_modules/@blueprintjs/core/lib/cjs/common/index.js (20:21)
(sc_server)/./node_modules/@blueprintjs/core/lib/cjs/common/index.js
file:///Users/erikdao/Workspace/Projects/tinymlops-project/tinymlops-webapp/.next/server/app/page.js (459:1)
__webpack_require__
file://....../.next/server/webpack-runtime.js (33:42)
eval
(sc_server)/node_modules/@blueprintjs/core/lib/cjs/index.js (20:21)
(sc_server)/./node_modules/@blueprintjs/core/lib/cjs/index.js
file://....../.next/server/app/page.js (1647:1)
```

This might be a nextjs 13 problem, but I'd appreciate any input from Blueprintjs users.

**Comment by erikdao** [comment]
Indeed this is a nextjs 13 problem!

**Comment by gurre** [comment]
__Environment__
__Package version(s):__ 4.19.2
__Nextjs version:__ 13.4.3

I've encountered the same problem which seems to be that blueprintjs is referencing the browser environment inside of `packages/core/src/common/abstractComponent.ts` as mentioned by the error.

By adding `"use client";` at the top of the file as suggested by https://nextjs.org/docs/messages/class-component-in-server-component works but is obviously not an acceptable solution as the benefits of SSR are lost.

Will Blueprintjs fully support SSR in version 5?

**Comment by adidahiya** [comment]
@gurre `AbstractComponent` is going away in Blueprint v5, to be replaced by `AbstractComponent2`'s implementation. Can you try @blueprintjs/core v5.0.0-alpha.x (whatever the latest version with the `next` tag is on NPM) and let me know if there are still issues with SSR? If there are, please file a new issue, thanks.

**Comment by eco-front-end-team** [comment]
The same here. Not compatible with Next v13 server components
