### ISSUE TITLE
Getting element ref on MenuItem

### ISSUE THREAD

**Issue by ilomon10** [palantir/blueprint#5772]
#### Environment

- __Package version(s)__: 4
- __Operating System__: Windows 10
- __Browser name and version__: Chrome Latest

#### Steps to reproduce

1. I'm trying to get element ref, from MenuItem 
`<MenuItem ref={ref => console.log(ref)}/>`
2. It return object of MenuItem (AbstractPureComponent2)

#### Expected behavior

Returning HTMLElement object

#### Possible solution

Maybe you can add innerRef so i can easily access the pure html elment reference.

**Comment by adidahiya** [comment]
Why do you need the HTML element?

**Comment by ilomon10** [comment]
to direct manipulate the element

**Comment by adidahiya** [comment]
> to direct manipulate the element

Can you please elaborate? What kind of manipulation? Styling? Layout? Resizing? Drag & drop? I need more information to make a good decision about what may need to change in Blueprint here.

**Comment by ilomon10** [comment]
I'm working with many different library, some module required to access ref (so i no need to pass each of property like onClick) for direct manipulate, like inject some event, dynamic styling, and many more.

**Comment by aikoven** [comment]
Another use case is to be able to use `scrollIntoView()` on menu items.
