### ISSUE TITLE
queryList active item breaks when createNewItemPosition set to first

### ISSUE THREAD

**Issue by jacobbel** [palantir/blueprint#5773]
#### Environment

- __Package version(s)__: @blueprintjs/select@4.5.3
- __Operating System__: Windows 10
- __Browser name and version__: Chrome latest

#### Steps to reproduce

1. View select2 on docs website https://blueprintjs.com/docs/#select/select2
2. Enable "Allow creating new items"
3. Enable "Create new positions: first"
4. Open select and type "spirited away"

#### Actual behavior

The menu item exactly matching the query is  not active, and a duplicate is created when  pressing the enter key.

#### Expected behavior

The menu item exactly matching the query should be active, and become selected upon pressing the enter key. Same as if Create new position: first is disabled.

#### Possible solution

Checking `isCreateItemRendered()` checks the current value in state instead of the newly created `createNewItem`

https://github.com/palantir/blueprint/blob/2460933e7084632f9f8b4f193fcda9fb9b3fd38f/packages/select/src/components/query-list/queryList.tsx#L330-L336

https://github.com/palantir/blueprint/blob/2460933e7084632f9f8b4f193fcda9fb9b3fd38f/packages/select/src/components/query-list/queryList.tsx#L593-L602

Simple fix is to change `wouldCreatedItemMatchSomeExistingItem` to check the `createNewItem` created locally in `setQuery`, and use the value in state elsewhere.

**Comment by adidahiya** [comment]
I can repro the bug with @blueprintjs/select v4.8.8:

![2022-11-30 10 45 47](https://user-images.githubusercontent.com/723999/204843717-a2cfe71e-dcfb-4df0-9903-07c7c856f64c.gif)
