### ISSUE TITLE
ContextMenu2 doesn't hide when clicking outside of the component

### ISSUE THREAD

**Issue by Harizriz** [palantir/blueprint#5781]
#### Environment

- __Package version(s)__: 
  - @blueprintjs/core: ^3.54.0
  - @blueprintjs/popover2: ^1.10.1
- __Operating System__: Pop!_OS 22.04 LTS
- __Browser name and version__: Google Chrome 106.0.5249.119

#### Steps to reproduce

1. Copy the ContextMenu2 primary usage in the docs and use it in my code.

```
  <ContextMenu2
            content={
                <Menu>
                    <MenuItem text="Save" />
                    <MenuItem text="Save as..." />
                    <MenuItem text="Delete..." intent="danger" />
                </Menu>
              }
          >
      {children}
  </ContextMenu2>
```

#### Actual behavior

By right-clicking, the Card component wrapped by the ContextMenu2 component, the context menu did appear properly. However, when I tried to close it by clicking outside the element, it would not close it.

#### Expected behavior

When the context menu component is visible, I should be able to close it by clicking anywhere outside the component.

#### Possible solution

Add a new props call `canOutsideClickClose` to the component with boolean values. The prop similar to the one in the Dialog component.

**Comment by adidahiya** [comment]
Those package versions are a bit surprising... @blueprintjs/popover2 v1.10 is compatible with @blueprintjs/core v4.x, not v3.x as you've listed there.

Can you repro your issue in a [code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)?

**Comment by Harizriz** [comment]
I have reproduced the behaviour with the package versions I mentioned above in this code sandbox link: https://codesandbox.io/s/hungry-fire-62h86i?file=/src/ContextMenu2Example.tsx

I also realized that the right-click popover is not working for this package version.

**Comment by adidahiya** [comment]
@Harizriz the problem there is that you're not loading @blueprintjs/core v4 CSS, which is required for @blueprintjs/popover2 components to work correctly. If you really want to use Blueprint v3 and v4 together in your application at the same time (not recommended), you'll need to configure your build system to load `blueprint.css` from _both_ v3 and v4 versions of @blueprintjs/core.

**Comment by adidahiya** [comment]
See how the ContextMenu2 overlay backdrop is styled correctly when v4 CSS is loaded on the page:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/723999/205100453-f06fcc33-d3b0-4a57-b5d8-c60c4e2d486e.png">

Those crucial styles are missing when only v3 CSS is loaded:

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/723999/205100554-63b65b4f-3cf0-418e-a854-93eabaf0cbd7.png">

**Comment by Harizriz** [comment]
I have resolved this issue by migrating to @blueprintjs/core v4 and it works as expected now.
