### ISSUE TITLE
Dialog doesn't close on Escape key if user clicks inside the Dialog

### ISSUE THREAD

**Issue by tdehollain** [palantir/blueprint#5782]
Environment:
    Package version(s): @blueprintjs/core: 4.12.0
    Operating System: macOS Ventura 13.0
    Browser name and version: Google Chrome Version 107.0.5304.110 (Official Build) (arm64)

Steps to reproduce:
1. Go to [Dialog documentation](https://blueprintjs.com/docs/#core/components/dialog)
2. Click one of the Show Dialog buttons (make sure the Prop Escape key to close is checked)
3. Click somewhere inside the dialog, or select some of the text
4. Press Esc key

Actual behavior:
The Dialog remains open

Expected behavior:
The Dialog should close

**Comment by adidahiya** [comment]
Yeah, I can confirm this is a bug. Seems related to https://github.com/palantir/blueprint/issues/2702. I'm open to PRs if anyone has the time to look into this 🙏🏽

**Comment by dylangrandmont** [comment]
Looking at the v5 docs page (same link in the original description above) I think this issue may be resolved.

Edit: however the inverse case still appears to be an issue (https://github.com/palantir/blueprint/issues/6399)

**Comment by adidahiya** [comment]
thanks @dylangrandmont, you're right, I can no longer repro this either. a similar issue / duplicate was closed recently too: #5947 

yes, #6399 is still an issue at the moment.
