### ISSUE TITLE
DateRangeInput2 in controlled mode uses previous formatted selected value

### ISSUE THREAD

**Issue by tzyl** [palantir/blueprint#5791]
#### Environment

- __Package version(s)__: @blueprintjs/datetime2 0.9.1
- __Operating System__: macOS Monterey 12.6.1
- __Browser name and version__: Google Chrome 107.0.5304.121

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/gallant-yalow-5ml2hd?file=/src/DatetimeExample.tsx

#### Steps to reproduce

The first DateRangeInput2 is in controlled mode with no time precision with close on selection false

```
      <DateRangeInput2
        closeOnSelection={false}
        formatDate={formatDate}
        parseDate={parseDate}
        value={value1}
        onChange={setValue1}
      />
```

1. Select any date range
2. While the date range is open select another date

#### Actual behavior

The input shows the previously selected date until the input is blurred / the popover is closed. If close on selection is true then this is generally not a problem because the selected value always appears correctly.

#### Expected behavior

The input should show the currently selected date. This works correctly in the second DateRangeInput2 with a time precision set.

**Comment by adidahiya** [comment]
Thanks @tzyl, I can repro this bug. Looks like it is still an issue with [datetime2 v0.9.6](https://codesandbox.io/s/pensive-cohen-7xyb6l?file=/src/DatetimeExample.tsx):

![2022-12-07 11 44 49](https://user-images.githubusercontent.com/723999/206239230-cc941d29-99b3-4d53-8bad-406cf31f14c2.gif)
