### ISSUE TITLE
Minimal button group divider shouldn't trigger onClick event when clicked

### ISSUE THREAD

**Issue by Padreramnt** [palantir/blueprint#582]
### Feature Request

- __Package version(s)__: 1.7
- __Browser and OS versions__: Chrom 55.0.2883.87; Windows 10

#### Steps to reproduce

1. `<div className="pt-button-group pt-minimal><button className="pt-button">...</button>...</div>`

#### Actual behavior

click to pt-button-group pt-minimal pt-button::after fire button.onclick event

#### Expected behavior

disable ponter-events for pt-button-group pt-minimal pt-button::after

```
@mixin pt-button-minimal-divider() {
  $divider-height: $pt-grid-size * 2;

  margin: ($pt-button-height - $divider-height) / 2;
  background: $pt-divider-black;
  width: $minimal-button-divider-width;
  height: $divider-height;
  pointer-events: none; // new css prop is here

  .pt-dark & {
    background: $pt-dark-divider-white;
  }
}
```

**Comment by llorca** [comment]
Looks like this problem will go away in 2.0: https://github.com/palantir/blueprint/issues/754
