### ISSUE TITLE
Option to keep children mounted in Collapse component

### ISSUE THREAD

**Issue by Yaojian** [palantir/blueprint#583]
I have a `Tree` component with a bunch of child nodes (more than 3000).

The performance of expand of the root node is very poor (about 3 seconds) after it has been collapsed.

I studied the blueprint code a little and thinks the root cause may stay in the `Collapse` component. `Collapse` removes all children when it is collapsed, and expand the root node causes all children have to be recreated again.

Is there any way to let the collapse just set its contents be 'hidden' instead of removing them?

**Comment by adidahiya** [comment]
Makes sense; I think it's worth looking into options on our various container components (Collapse, Dialog) that allow users to choose whether to unmount their children or just hide them with CSS for performance tuning purposes.

**Comment by giladgray** [comment]
I did a similar thing in my `Tabs` rewrite: a `renderActiveTabPanelOnly` prop.

The issue with Collapse, Dialog, etc, is that they use CSSTransitionGroup which is all about animating elements in and out _of the DOM_. As in, un/mounting is a fundamental piece of the implementation. Refactoring to not require unmounting will be quite a bit of work, but it may actually be worth it.

**Comment by acolombi** [comment]
FWIW, in some of my own fooling around with `Tree`, I found that even a flat `Tree` (i.e. one with no `hasCaret = true` nodes) can take awhile to load. In the end I wrote my own render for the `ITreeNode` data structure that doesn't use any `TreeNode`s or `Collapse`s, styling using the Blueprint Tree CSS. It's much faster this way.
