### ISSUE TITLE
Table: Update ICellRenderer and IColumnHeaderRenderer for latest DT.

### ISSUE THREAD

**Issue by ericanderson** [palantir/blueprint#585]
### Bug report

- __Package version(s)__: @blueprint/table 1.3.0

#### Steps to reproduce

1. Use latest typings from DT.
1. Notice cell renderers cannot be cast any more

#### Actual behavior

Errors:
```
file: 'file:///redacted/file.tsx'
severity: 'Error'
message: 'Type '(rowIndex: number, columnIndex: number) => Element' is not assignable to type 'ICellRenderer | undefined'.
  Type '(rowIndex: number, columnIndex: number) => Element' is not assignable to type 'ICellRenderer'.
    Type 'Element' is not assignable to type 'ReactElement<ICellProps>'.
      Type 'null' is not assignable to type 'ReactElement<ICellProps>'.'
at: '92,7'
source: 'ts'
```

#### Expected behavior

Doesnt error.

**Comment by ericanderson** [comment]
In the latest DT react, JSX.Element has changed from `React.ReactElement<any>` to `React.ReactElement<any> | null`.

This means when you have code like:
```ts
const renderCell = (rowIndex: number, columnIndex: number) =>
  <Cell>...</Cell>;
```

You have a function that returns `JSX.Element`, which is now defined as including `null`. Note, it could always be null, it just wasn't defined properly.

If you change:
```ts
export declare type ICellRenderer = (rowIndex: number, columnIndex: number) => React.ReactElement<ICellProps>;
```
to: 
```ts
export declare type ICellRenderer = (rowIndex: number, columnIndex: number) => React.ReactElement<ICellProps> | null;
```
then the cast issue goes away.

This is an issue for IColumnHeaderRenderer and possibly other parts of the code base.

**Comment by gscshoyru** [comment]
So this is not nearly as straightforward as it seems. 

First of all, the change that introduced this problem has been met with... a certain amount of backlash. It seems we're not the only people who've had this broken. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14284 . 

Second of all, it doesn't make sense for us to type the renderer this way. If we do, it implies that we're ok with a renderer function that sometimes returns null. But we are not. Our code breaks if the cell renderer returns things that are not Cells; that don't have the right set of props for us to set. We could do lots of null checks and make empty cells if we get nulls back, but it makes far more sense to enforce that we get a Cell back from the renderer with typings, here. 

Until typescript/definitelytyped figures out the right way forward here, I would suggest against using the most recent typings here -- or cast instead. We'll keep an eye on the discussion, and make sure to update our code/typings properly, as necessary, once this is resolved.

**Comment by gscshoyru** [comment]
Ok, so the relevant typings change has been reverted. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14476 . Closing this issue; please update your typings to the latest and all will be good. We'll keep an eye open for anything like this happening again.

**Comment by giladgray** [comment]
This change has been reverted in DT (per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14284#issuecomment-277869614) so I think it's safe to close this issue as a no-op. @ericanderson please follow up if you're still having troubles.
