### ISSUE TITLE
New type for IPopover2SharedProps.renderTarget creates ambiguous type where properties are resolved as unknown

### ISSUE THREAD

**Issue by dlech** [palantir/blueprint#5889]
https://github.com/palantir/blueprint/commit/8d793f6c229cf372b11b0909573f69a35692e161#r97915117

> FYI, this is a breaking change as it creates an ambiguous type. For example, since onFocus is only defined in Popover2HoverTargetHandlers and not Popover2ClickTargetHandlers, TypeScript interprets the the type of onFoucs as unknown.
> 
> It causes CI to fail like this: https://github.com/pybricks/pybricks-code/actions/runs/3993794470/jobs/6850831641#step:5:6
> 
> Source code that triggered this is here: https://github.com/pybricks/pybricks-code/blob/939ded73fa18e26ae8aeedc88d95f1c9077eccce/src/toolbar/ActionButton.tsx#L103

#### Environment

- __Package version(s)__:"@blueprintjs/popover2": "^1.12.0",
- __Operating System__: any
- __Browser name and version__: any

#### Code Sandbox

Don't have time to do this at the moment, but see link above for CI failure.

#### Steps to reproduce

1. use Tooltip2 with renderTarget as recommended in the docs: https://blueprintjs.com/docs/#popover2-package/tooltip2
1. update @blueprintjs/popover2 to v1.12.0
1. Typescript type checking breaks and code no longer compiles

#### Possible solution

Types that inherit from IPopover2SharedProps should `Omit<..., 'renderTarget'>`  and supply the correct type.

**Comment by adidahiya** [comment]
Acknowledged, I noticed this too. I'll sort out a fix, or add guidance about the breaking change this week.

**Comment by adidahiya** [comment]
@dlech @ZeRego I believe I've fixed this problem with #5907. Please test out those type changes when they release today/tomorrow.

**Comment by adidahiya** [comment]
@dlech @ZeRego I've released @blueprintjs/popover2 v1.12.1 with the fix. It seems to have fixed some compilation issues in our internal codebases. Let me know if you still experience issues with this release.

**Comment by dlech** [comment]
It fixes the issue in our case, thanks!
