### ISSUE TITLE
docs tooling uses outdated 'highlights' library

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#5895]
Blueprint docs used to highlight code using [atom/highlights](https://github.com/atom/highlights), which supported TextMate-style grammars via [atom/first-mate](https://github.com/atom/first-mate).

Although `highlights` did not have TypeScript support out of the box, we were able to add it using a library called [tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript).

Atom and its repositories were finally [sunsetted and archived at the end of 2022](https://github.blog/2022-06-08-sunsetting-atom/). This and the fact that tree-sitter has C dependencies which sometimes do not compile well on newer versions of Node.js prompted a migration away from `highlights`.

This issue tracks the removal of all highlights, tree-sitter, and TextMate related code from Blueprint.

**Comment by SoulPancake** [comment]
Is this migration completed? @adidahiya Or is there anything else to be done here

**Comment by adidahiya** [comment]
@SoulPancake it's mostly complete. There are just these deprecated styles which need to be removed in v5.0: https://github.com/palantir/blueprint/blob/61a0ef8184c28963d8c56caf23edcfd0a1163b93/packages/docs-theme/src/styles/_textmate-syntax-theme.scss#L6
