### ISSUE TITLE
Table2 doesn't detect drag events on the top of the scrolling container

### ISSUE THREAD

**Issue by abvthecity** [palantir/blueprint#5915]
In the Chrome Browser, dragging over a scrolling container causes it to auto-scroll when the cursor is near the edge of the container. However, because Table2 renders a header fixed to the top of the scrolling container, it interferes with the default behavior and dragging a payload over the top of the table does not cause the container to scroll up, whereas dragging over the bottom still does. Additionally, since the header itself isn't affected by scrolling, the target area for autoscroll should be offset from the header (but also including the header region). To fix this, the default autoscroll needs to be disabled and replaced with custom drag event listeners that account for the Table2 header offset.

**Comment by adidahiya** [comment]
I created a [sandbox](https://codesandbox.io/s/dank-paper-xrwgk8?file=/src/TableExample.tsx) that mostly demonstrates the issue. It's a bit buggy but it captures the essential problem where users can't scroll up in the table once they've scrolled down while dragging an element over its scroll container.

![2023-02-17 12 05 19](https://user-images.githubusercontent.com/723999/219717879-aa3b051d-87c1-4ba5-a36e-c9e5c2403ba7.gif)
