### ISSUE TITLE
@blueprintjs/stylelint-plugin add styelint v15 as a peer dependency

### ISSUE THREAD

**Issue by tbertrand7** [palantir/blueprint#5942]
#### Environment

- __Package version(s)__: @blueprintjs/stylelint-plugin 3.1.5
- __Browser and OS versions__: any

#### Feature request

Add stylelint v15 as a peer dependency of @blueprintjs/stylelint-plugin

#### Examples

stylelint can be upgraded to v15 in projects that use @blueprintjs/stylelint-plugin

**Comment by adidahiya** [comment]
Stylelint v15 released just last week, we haven't tried to upgrade yet.  We'll need to follow the [upgrade guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md) and ensure compatibility before adding the v15 peer dependency.

**Comment by tbertrand7** [comment]
Hi, has there been any progress on this?

**Comment by gluxon** [comment]
Hi @tbertrand7, I don't believe there's been progress on this yet, but help would be appreciated. 🙂

**Comment by adidahiya** [comment]
Blueprint users are now unblocked by the wider peer dep range in #6364, but we still need to upgrade to stylelint v15 in this repo and [stylelint-config-palantir](https://github.com/palantir/stylelint-config-palantir).
