### ISSUE TITLE
ItemRendererProps has a new unexpected required "ref" property

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#5943]
#### Environment

- __Package version(s)__: @blueprintjs/select v4.9.0

#### Steps to reproduce

Define a custom item renderer which generates `ItemRendererProps` (either by explicitly referencing that type definition, or implicitly)

#### Actual behavior

Errors like this (redacted file name):

```
[error] TypeScript error packages/**/*.tsx:215:48 - error TS2345: Argument of type '{ index: number; handleClick: () => void; query: string; modifiers: { active: false; disabled: false; matchesPredicate: false; }; }' is not assignable to parameter of type 'ItemRendererProps'.
  Property 'ref' is missing in type '{ index: number; handleClick: () => void; query: string; modifiers: { active: false; disabled: false; matchesPredicate: false; }; }' but required in type 'ItemRendererProps'.
```

#### Expected behavior

New properties should not be required when bumping a minor version of the select package. This blocks Blueprint upgrades.

#### Possible solution

Make `ref` optional in `ItemRendererProps`.

**Comment by adidahiya** [comment]
FYI @shim-flounce

**Comment by shim-flounce** [comment]
@adidahiya ah apologies, I hadn’t considered this use case - I had assumed that the only thing providing these props is Blueprint, and since we’re always passing `ref`, it’s always defined, and it’s up to the user if they want to wire it up. Thanks for fixing!
