### ISSUE TITLE
Overlays are not closed on `esc` key after clicking or focusing inside the overlay component

### ISSUE THREAD

**Issue by sher** [palantir/blueprint#5947]
I guess that the title does explain the situation.

Even `canEscapeKeyClose` prop is set to `true`, after you click on any element on the drawer, making it the event receiver, the drawer doesn't close on `esc` key press.

**Comment by adidahiya** [comment]
This applies to all overlay components, including Dialog, Popover2, and Drawer. I'll update the title.

**Comment by alexbrt** [comment]
@adidahiya Not sure if it helps, but setting `tabIndex={0}` on the child component to allow focusing it might fix it.

**Comment by adidahiya** [comment]
I can no longer repro this bug, but now we have another related one: https://github.com/palantir/blueprint/issues/6399
