### ISSUE TITLE
DateInput2 shows "Invalid date" when Displaying Chrome in Spanish and assign a variable = new Date()

### ISSUE THREAD

**Issue by pcclickbit** [palantir/blueprint#5969]
#### Environment

- __Package version(s)__: 
    "@blueprintjs/core": "^4.16.3",
    "@blueprintjs/datetime2": "^0.9.13",
- __Operating System__: Windows 11 in English
- __Browser name and version__: Chrome Version 110.0.5481.178 (Official Build) (64-bit) Displaying Chrome in Spanish

#### Steps to reproduce

1. Change Chrome Language chrome://settings/languages to Displaying Chrome in Spanish
2. const today = new Date()
3. date = today.toLocaleString()
4. DateInput2.value = date

#### Actual behavior

DateInput2 shows "Invalid date"

#### Expected behavior

DateInput2 showing the value asigned

**Comment by adidahiya** [comment]
1. please fill out the issue template. a code sandbox would be helpful here.
2. `<DateInput2>` expects an ISO string, not a locale-specific string representation of the date. See [`Date.prototype.toISOString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

**Comment by pcclickbit** [comment]
I see my error, I will use `toISOString()`
thanks
