### ISSUE TITLE
BlueprintDateRangeInput does not update hour until minute is set

### ISSUE THREAD

**Issue by spencert16** [palantir/blueprint#5977]
#### Environment

- __Package version(s)__: 4.16.3
- __Operating System__: OSX Venture 13.2.1
- __Browser name and version__: Chrome 110.0.5481.100

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Create a Date / Time parameter in Quiver. Try to set the hour of the parameter. Notice that hitting enter after setting the hour reverts back to 0.
Then set the minute and notice the minute updates, and now the hour will also update.

#### Actual behavior

Hour cannot be set in time picker until minute is set.

#### Expected behavior

Hour can be set as normal in time picker

**Comment by adidahiya** [comment]
Debugged internally, it seems like this was an issue of not providing the `timePrecision` parameter to the `DateInput2MigrationUtils.valueAdapter()` function.
