### ISSUE TITLE
Copy to clipboard for variables

### ISSUE THREAD

**Issue by leebyp** [palantir/blueprint#599]
It would be helpful to have copy to clipboard for the variables and aliases, similar to how icons and colors. This is useful for prototyping applications and components with BP stylings

**Comment by adidahiya** [comment]
Hmm, this doesn't sound super valuable IMO -- instead it would be better to make our editor plugins autocomplete imported Sass and Less symbols.

**Comment by leebyp** [comment]
This is very useful for the same reason that the colors have copy to clipboard. I want to get a rough idea of how things look by testing out the variables with browser dev tools. eg.
- I want to quickly see what `$pt-dialog-box-shadow` vs $.pt-dialog-popover` looks like
- I want experiment between `$pt-font-size` / `$pt-font-size-small` for a piece of text.

In particular, I want to tend towards these variables because I know they've been vetted with the rest of the BP ecosystem

**Comment by styfle** [comment]
You might want to use https://www.npmjs.com/package/copee
