### ISSUE TITLE
(TagInput) Placeholder misalignment due to missing padding-left

### ISSUE THREAD

**Issue by jakejrichards** [palantir/blueprint#5998]
#### Environment

- __Package version(s)__: 4.17.4
- __Operating System__: MacOSX
- __Browser name and version__: Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/keen-dream-24kwus

#### Steps to reproduce

1. Render a TagInput with a placeholder and no values

#### Actual behavior
Placeholder misaligned
![Screenshot 2023-03-06 at 1 39 53 PM](https://user-images.githubusercontent.com/36425972/223201411-79ec7f1a-bb7f-42d1-b18f-cc5eca0f9dfb.png)

#### Expected behavior
Placeholder properly aligned
![Screenshot 2023-03-06 at 1 42 40 PM](https://user-images.githubusercontent.com/36425972/223201787-e9c4a8d8-6d51-4f33-95c8-03a3e78ecd30.png)

#### Possible solution
Looks like we maybe need to update this selector to account for the new spans added here: https://github.com/palantir/blueprint/pull/5966/files#diff-7164b77e6a1ae7a7566da0e0a780fef5c01d686cb05be8f240aafd984098c94dR31
![Screenshot 2023-03-06 at 1 33 57 PM](https://user-images.githubusercontent.com/36425972/223201980-e11a236c-d48e-4603-8405-153f7e22f181.png)

**Comment by adidahiya** [comment]
Good catch, will fix
