### ISSUE TITLE
Have explanatory "first-liners" follow a consistent pattern in the docs?

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#600]
### Bug report

- __Package version(s)__: 1.7.0
- __Browser and OS versions__: N/A

#### Steps to reproduce

1. Navigate to http://blueprintjs.com/docs/.
2. Read the first line of various components' documentation.

#### Actual behavior

// Filing a low-priority thought I had in order to gather others' opinions on it.

I've noticed that the Blueprint docs are inconsistent with the writing style in the first line describing each component. (I'll call those sentences "first-liners" here.) Some first-liners that I like better:

- Dialogs present content overlaid over other parts of the UI.
- Hotkeys enable you to create interactions based on user keyboard events.
- Menus display lists of interactive items.
- Navbars present useful navigation controls at the top of an application.
- `Overlay` is a generic low-level component for rendering content above its siblings, or above the entire application.

These read nicely to me, because they each summarize in a short sentence what functionality the component enables. These sentences also each begin with the name of the respective component. The pattern is essentially `X helps you accomplish Y`, where X is the component name.

There are other first-liner patterns in the documentation, too. Some are phrased similarly to the above examples, but as more of a command:

- Add labels to inputs to enhance the usability of your forms.
- Add additional helper text to help users navigate forms and complex fields.

And some follow no particular scheme at all:

- Blueprint's custom checkboxes use an extra `.pt-control-indicator` element after the `<input>` to achieve their custom styling. You should then wrap the whole thing in a `<label>` with the classes `.pt-control.pt-checkbox`.
- Use the standard `input type="file"` along with a `span` with class `pt-file-upload-input`. Wrap that all in a `label` with class `pt-file-upload`.

Presumably, we skip the short sentence for basic components that serve as thin wrappers around native HTML elements (e.g. a checkbox, a file-upload input), because we assume users already know what functionality those components provide. But the reading experience is nevertheless a little jarring.

#### Expected behavior

I'd love every component to follow a consistent first-liner scheme that succinctly communicates why the component is helpful. Maybe we could even explore emphasizing first-liners visually (e.g. by giving them a different type treatment). Other frameworks do this to powerful effect in their documentation; the first-liner effectively becomes a form of helper text (#594 :]). The result would make for a slightly more streamlined, elegant documentation-reading experience.

But, yeah, totally a P3 at best.

**Comment by llorca** [comment]
I dig. Maybe talk to Eva see if she'd have some time to spare to fix this up?

**Comment by cmslewis** [comment]
@eparish - would love your thoughts here!
