### ISSUE TITLE
ContextMenu2 browser context menu occassionally appears

### ISSUE THREAD

**Issue by bdenhollander** [palantir/blueprint#6005]
#### Environment

- @blueprintjs/core@: 4.17.1
- @blueprintjs/popover2: 1.13.5
- Windows 10
- Chrome 110.0.5481.178

#### Code Sandbox

https://blueprintjs.com/docs/#popover2-package/context-menu2

#### Steps to reproduce

1. Hover over the `ContextMenu2` example
1. Slowly move the mouse from right to left while right clicking repeatedly

#### Actual behavior

About 1 in 25 right clicks, the browser context menu will appear on top of the ContextMenu2 menu

I noticed this while implementing the new imperative API and reproduced it on the example.

#### Expected behavior

Browser context menu is suppressed successfully. Repeating the same steps on `ContextMenu` does not show the browser's context menu.

#### Possible solution

There may be a short moment in time that the right click is propagated to the newly added overlay, before the overlay has its event set up to close the new `ContextMenu2` on right click.

1. Right click launches `ContextMenu2` and calls `preventDefault()`
2. Overlay is added quickly
3. Right click propagates to overlay
4. Right click menu appears <-- Problem might be here
5. Overlay adds event to dismiss itself on any click event

**Comment by AngryPowman** [comment]
Same issue to me, is there a temporary solution to fix this?

**Comment by bdenhollander** [comment]
> Same issue to me, is there a temporary solution to fix this?

We're sticking with the imperative usage method provided by the deprecated `ContextMenu` for now.

**Comment by adidahiya** [comment]
I couldn't repro this bug in the ContextMenu2 (declarative API) example:

![2023-03-22 09 26 23](https://user-images.githubusercontent.com/723999/226918938-f88e6073-b352-43ac-920d-cab4cd66d153.gif)

But I can repro it very occasionally in the ContextMenu2Popover (imperative API) example:

![2023-03-22 09 29 28](https://user-images.githubusercontent.com/723999/226919510-dd09e964-de22-4590-a321-943c1517544c.gif)

**Comment by adidahiya** [comment]
I can no longer repro this in the [ContextMenuPopover docs example](https://blueprintjs.com/docs/#core/components/context-menu-popover.imperative-api) (which uses the imperative API). I believe this has been fixed.
