### ISSUE TITLE
Consider adding `noUncheckedIndexedAccess` to tsconfig

### ISSUE THREAD

**Issue by dylangrandmont** [palantir/blueprint#6009]
#### Environment

- __Package version(s)__: `4.x` and `5.x`
- __Browser and OS versions__: (Applied to all, and to TypeScript >= `4.1`)

#### Feature request

The request is for `blueprint` to include `"noUncheckedIndexedAccess": true` in its `tsconfig`. The reasoning is as follows:

By default, TypeScript will not correctly infer when an array element can be undefined
```tsx
  let g: Array<number> = []
  let h = g[0] // type of h is number
```

On ~recent release of TS (`4.1`) this behaviour can be changed via a configuration
https://github.com/microsoft/TypeScript/pull/39560
https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

Unfortunately because `blueprint` ships `tsx` files directly, any library which uses `blueprint` as a dependency will be unable to set `"noUncheckedIndexedAccess": true` in its `tsconfig.ts`. Doing so will result in build time failures during the TypeScript compilation, for example

```
./node_modules/@blueprintjs/core/src/components/tree/tree.tsx:98:31
Type error: Type 'undefined' cannot be used as an index t
info  - Linting and checking validity of types .Failed to compile.

./node_modules/@blueprintjs/core/src/components/tree/tree.tsx:98:31
Type error: Type 'undefined' cannot be used as an index type.

     ): TreeNodeInfo<U> {
         if (path.length === 1) {
             return treeNodes![path[0]];
                               ^
         } else {
             return Tree.nodeFromPath(path.slice(1), treeNodes![path[0]].childNodes);
         }

```

**Comment by adidahiya** [comment]
> Unfortunately because blueprint ships tsx files directly

You shouldn't be pulling these files into your TS compilation pipeline. They are only there to provide accurate sourcemaps. Your `tsc` should only see (be given access to) the `.d.ts` files.

**Comment by dylangrandmont** [comment]
> You shouldn't be pulling these files into your TS compilation pipeline. They are only there to provide accurate sourcemaps. Your tsc should only see (be given access to) the .d.ts files.

Thanks for the reply @adidahiya. I see I am inadvertently importing some types from `@blueprintjs/core/src/components` and this is my underlying issue.
