### ISSUE TITLE
Regression for pt-text-selection-color

### ISSUE THREAD

**Issue by wangyuy22** [palantir/blueprint#6015]
#### Environment

- __Package version(s)__:  4.16.0
- __Operating System__: Mac
- __Browser name and version__: Chrome, Version 111.0.5563.64 (Official Build) (arm64)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 

#### Steps to reproduce

Select text with cursor over text that uses this CSS

#### Actual behavior

The selection color is now a dark brown-ish color

#### Expected behavior

The selection color should be blue-ish, as normally expected

#### Possible solution

Since it's a regression, go back to the previously used color for this variable

**Comment by adidahiya** [comment]
It used to be `rgba(125, 188, 255, 0.6)` in [v4.16.0](https://unpkg.com/browse/@blueprintjs/core@4.16.0/lib/scss/variables.scss)
