### ISSUE TITLE
Date Input placeholder prop

### ISSUE THREAD

**Issue by lucantini** [palantir/blueprint#602]
### Feature Request

Is it possible to pass a placeholder to the Date Input component? Today the default is MM/DD/YYYY. Can I chage this? to anything I want/need?

**Comment by giladgray** [comment]
Thanks for filing @lucantini! It does not seem supported at the moment. We'll tackle this as part of the DateInput revamp in #560.

**Comment by leebyp** [comment]
Will be fixed as part of 2.x as per the discussion in #387
