### ISSUE TITLE
Popover2 props for ColumnHeaderCell2's menuRenderer

### ISSUE THREAD

**Issue by lawsonw** [palantir/blueprint#6035]
#### Environment

- __Package version(s)__: Blueprint v 4.17.6, React v 18.2.0
- __Browser and OS versions__: Google Chrome v 101.0.4951.64, Ubuntu 18.04.6 LTS

#### Feature request

In ColumnHeaderCell2, there's a prop called `menuRenderer` that renders a Popover2 around whatever you pass into it. However, the programmer has no control over how that Popover2 functions or any of its props. I request that the capability to use Popover2 props within the `menuRenderer`/ColumnHeaderCell2 be added, or an equivalent level of control.

#### Examples

In my case, I want to be able to pass a `portalContainer` prop into it so the `menuRenderer`'s popover will only ever appear over the correct element, but I'm unable to do that as it is now. If I have something like floating windows or multiple FlexLayout tabs, the popover will appear on the wrong window or the wrong tab respectively.

I can see use for other props from Popover2, such as `placement` or `position`, being useful as well.

**Comment by rafaellichen** [comment]
For me, I end up using `ColumnHeaderCell2`'s `nameRenderer` prop for rendering my own column menu dropdown. This way I have full control over the menu dropdown target (the button) and the content (the dropdown menu). Especially when the column header cell height is not the default height or you want to display some extra information inside the column header cell, this workaround shines.
```js
nameRenderer={() => {
    return <div>
        "Start Time"
        <div style={{ position: 'absolute', ... }}>
            <Popover2 ... />
        </div>
    </div>
}}
```
<img width="384" alt="image" src="https://user-images.githubusercontent.com/15823067/232148602-ab24ebe6-6c66-494a-a7cd-de02996f25bc.png">
