### ISSUE TITLE
Column width/text overflow based TruncatedFormat

### ISSUE THREAD

**Issue by philcchen** [palantir/blueprint#604]
It might be useful to have a version of TruncatedFormat where the truncation length is dynamic based on whether cell's contents are overflowing (for example, if the column width is too small even though the content itself is less than the truncate length provided)

**Comment by giladgray** [comment]
I believe it used to do this but we removed that functionality for design consistency. It felt better to have the `...` buttons in all cells in a row, even if they aren't truncated. @themadcreator @llorca is this correct?

**Comment by philcchen** [comment]
I think this is slightly different that the original behavior (prior to https://github.com/palantir/blueprint/pull/267). Specifically, the `truncateLength` has always been a fixed width.

The combination that I would want would be `TruncatedPopoverMode.WHEN_TRUNCATED` + with a slightly more dynamic check that would reflect whether the cell's contents are either overflowing (maybe by checking scrollWidth > innerWidth?) or is above the fixed `truncateLength`

**Comment by llorca** [comment]
It's an improvement @gscshoyru and I can make at some point after #298

**Comment by michael-yx-wu** [comment]
This doesn't seem too difficult, though I'm curious if it'll noticeably table performance, especially when scrolling. Would you accept a PR for this before you finish up #298?

**Comment by llorca** [comment]
@michael-yx-wu you bet 🌟 you should sync with Geoff since you're in the same location

**Comment by giladgray** [comment]
a dynamic check on cell contents will _absolutely_ affect table performance. that's what worries me most about this request--it's computationally intensive, particularly for _every_ cell.

**Comment by michael-yx-wu** [comment]
You're right. I think it's worth trying out for the sake of prettier truncation, but I'm not confident about it not killing scroll performance :)
