### ISSUE TITLE
Normal HTML props not working on MenuItem

### ISSUE THREAD

**Issue by leebyp** [palantir/blueprint#605]
### Bug report

- __Package version(s)__: v1.7.0

#### Steps to reproduce

`<MenuItem onMouseEnter={...} />` doesn't work as expected

#### Current workaround
`<div class="pt-menu-item" onMouseEnter={...} />` manually

**Comment by adidahiya** [comment]
This could be said about a lot of our components... we don't propagate all HTML props. What's the use case here?

**Comment by joyt** [comment]
It's for synchronizing hovering on a menu item with highlighting the corresponding object elsewhere on the page

**Comment by styu** [comment]
+1 it would be nice if the `title` attribute was propagated through so we could have browser tooltips, in the case that text is cut off

**Comment by iongion** [comment]
I need to add custom attributes to MenuItem to identify actions with a single handler, I've tried adding `data-action="my.action"` but the attribute does not get transferred to the `a` element,
