### ISSUE TITLE
MenuItem / MenuItem2 enter button doesn't have same effect as click

### ISSUE THREAD

**Issue by bvandrc** [palantir/blueprint#6056]
#### Environment

- __Package version(s)__: Latest
- __Operating System__: Windows
- __Browser name and version__: Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

1. Use tab key to focus to a MenuItem that does not have the `listoption` role (in other words, a MenuItem that is not part of `Select`/`MultiSelect`)-- one good example of this is the left shortcuts in https://blueprintjs.com/docs/#datetime/daterangepicker :

![image](https://user-images.githubusercontent.com/87083504/229924669-f80cade4-4b97-41f5-8479-ee0b69b10789.png)

2. Hit enter key or space bar. Nothing happens.

#### Actual behavior

Has no effect.

#### Expected behavior

Same behavior as clicking the menu item.

#### Possible solution

PR: https://github.com/palantir/blueprint/pull/6044

**Comment by adidahiya** [comment]
Related: https://github.com/palantir/blueprint/issues/3079
