### ISSUE TITLE
Numeric Input enhancements

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#607]
Now that the `NumericInput` (#189) is merged, here are some enhancement ideas:

- [x] ~Determine how to handle a typed or pasted number that falls outside of the `[min, max]` range. Do we correct the number on blur, on <kbd>Enter</kbd>, as soon as the typed value becomes invalid, not until the next increment/decrement action?~

- [x] ~Add a `precision` prop to make precision configurable. (Right now the maximum precision is 0.1, which doesn't play nicely with `minorStepSize`s having two or more decimal places)~

- [ ] Add `format` and `parse` props to format numbers for display in a custom fashion (e.g. with currency symbols and commas: `"$14,193.85"`) and then parse typed/pasted input text in a custom fashion.

- [ ] Related to the above, but won't necessarily require more props: support typing or copy-pasting numbers with commas (or ".", depending on locale):
![image](https://cloud.githubusercontent.com/assets/443450/22570803/b84d8c9a-e951-11e6-865f-1b7f30104594.png)

Maybe:

- [ ] Add callbacks for `onMajorStep`, `onMinorStep`, `onStep` to allow developers to adjust the current value in a custom fashion. This could be useful in `DateInput` for incrementing date strings by days, months, years. If we do this, we might consider pulling out the stepping logic into a lower-level `Stepper`/`AbstractStepper` component. // CC @llorca 

~And some bugs:~

- [x] ~Tiny bit of weirdness in the numeric input (dark theme only)~ **Addressed in #632**
![image](https://cloud.githubusercontent.com/assets/443450/22613474/83ae2512-ea2d-11e6-9c49-c3abe75dc960.png)

**Comment by llorca** [comment]
- On `enter`, to be able to do some maths in the field if necessary?
- Yes, though sounds like an `AbstractStepper` type of thing
- Yes, though sounds like something generic outside of `NumericInput`

+1 on `AbstractStepper`, would be neat for `DateInput` indeed!

**Comment by cmslewis** [comment]
Adding the `precision` fix to 1.12.

**Comment by cmslewis** [comment]
Closed the sub-task about constraining typed or pasted values to `[min, max]`, because native HTML numeric inputs don't do that, and we're more or less trying to abide by the principle of least astonishment here.

**Comment by tnrich** [comment]
Hey there, I am using a blueprint NumericInput component as a page size tool:

![image](https://cloud.githubusercontent.com/assets/2730609/26659561/777bd7f8-4626-11e7-8413-debfd3fa37f4.png)

Ideally I'd only like to fire off page change requests onBlur/onEnter so as not to fire off requests while the user is actively typing in the input: 
```
<NumericInput
          onBlur={(e)=>{
            this.setState({value:e.target.value})
            setPageSize(e.target.value);
          }}
          onValueChange={(value)=>{
            this.setState({value:value})
          }}>
```

This works great if the user types directly into the input, however, when the user hits the up or down buttons, no onBlur event is fired. 

Do you all know if there is a nice way to achieve what I'd like to do?

Thank you!

**Comment by cmslewis** [comment]
Hi @tnrich, a similar request came up a few weeks ago (#1119). Maybe we can add something like `onButtonClick(valueAsNumber: number, valueAsString: string)`? Would that solve your case? Think you'd ever need to know which button (up/down) was pressed?

**Comment by tnrich** [comment]
Hey @cmslewis, thanks for the quick response! Yup, I believe that would solve my need exactly!

Thanks!

**Comment by tnrich** [comment]
Thanks @cmslewis , just to be clear, this hasn't been released yet, right?

**Comment by cmslewis** [comment]
Nope, but it'll go out in our next release (our issues just close automatically when a PR mentioning them merges).

**Comment by tnrich** [comment]
Okay, cool, thank you!

**Comment by riwu** [comment]
@cmslewis are item 3&4 completed? If not, why was this closed?
