### ISSUE TITLE
Migrate method ContextMenu.show() - doesn't work (react.render method error)

### ISSUE THREAD

**Issue by ggrelaxi** [palantir/blueprint#6117]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "4.18.0", "@blueprintjs/popover2": "1.14.0",
- __Operating System__: windows 10
- __Browser name and version__: chrome 112.0.5615.138 x64

#### Steps to reproduce

1. I try to migrate my React Component with context menu, to new BluePrint version. Use ContextMenu.show() - i get an error "ReactDOM.render is no longer supported in React 18. "

#### Actual behavior

Component work well

#### Expected behavior

Component doens't work

#### Possible solution

i have no ideas. Please help!

**Comment by adidahiya** [comment]
`<ContextMenu>`, `ContextMenu.show()`, and `ContextMenu.hide()` are all deprecated, you shouldn't use them anymore. See the docs callout:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/723999/235935389-f5282f4e-f0fb-40ab-9c12-176e025dbd87.png">

Use `<ContextMenu2>` for compatibility with future versions of React. The `showContextMenu()` imperative API for ContextMenu2 uses `ReactDOM.render` (which is deprecated, but [still supported in React 18](https://react.dev/reference/react-dom/render)).

We'll migrate the imperative API to [`ReactDOM.createRoot`](https://react.dev/reference/react-dom/client/createRoot) in Blueprint v6.0 or v7.0
