### ISSUE TITLE
Add minified bundles to distribution

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#612]
Follow-up of #303, #588. Should not include sourcemaps.

**Comment by giladgray** [comment]
the sourcemaps are already external files, not sure how much space there is to save by removing the `//#` lines?

**Comment by adidahiya** [comment]
yeah, you're right, no need to remove those lines

**Comment by giladgray** [comment]
@adidahiya so is there any work to actually do here? are you asking for a `core.bundle.min.js`?

**Comment by adidahiya** [comment]
@giladgray yeah, that's what I mean. Just a nice convenience if I want to include blueprint on a static site in production with a `<script>` tag. Low priority, I'll actually bump this down to P3.

**Comment by timelyportfolio** [comment]
Thanks so much for bundling.  The bundle is very useful for using in R.  I see that this is a low priority, but if you get around to addressing the bundle, I think I discovered a small problem.  It seems `classnames` is not included in the bundle.  I wish I knew enough about JavaScript bundling in the modern toolchain.  I could not see anything obviously wrong.  I will try to dig a little deeper.

### without `classnames`

If I use `blueprint-core` and `blueprint-table` bundles, then I get the following error.  Reproducible [example](https://bl.ocks.org/timelyportfolio/raw/54e1fe11f0c1235092976207f0146453/)

![image](https://cloud.githubusercontent.com/assets/837910/24834569/569263e0-1caf-11e7-9edc-944b8aaff53c.png)


### with `classnames` explicitly added

If I modify the above and explicitly include `<script src="https://unpkg.com/classnames"></script>`, then everything works as expected.  [example with classnames](https://bl.ocks.org/timelyportfolio/406db54218392de509c4664c5b4dec57)

![image](https://cloud.githubusercontent.com/assets/837910/24834582/a578326e-1caf-11e7-8db8-dd7172ec16fd.png)

**Comment by adidahiya** [comment]
@timelyportfolio the bundles don't include any dependencies (those listed in `"dependencies"` in package.json)... you need to provide your own global versions of react with addons, classnames, dom4, etc.

**Comment by timelyportfolio** [comment]
great to know, thanks!

**Comment by giladgray** [comment]
@adidahiya is it reasonable to close this request? i remember reaching a decision that minifying should be the responsibility of the application, not the library, as they'll have plenty of their own code to production-ize too.

**Comment by adidahiya** [comment]
No, I'm still interested in this, but it's low priority. We just need to run one extra webpack build for the CI deployment step.

**Comment by adidahiya** [comment]
This came up again, but for CSS. I am trying to build an app with web workers where workers are allowed to load blueprint styles but we want to do some dynamic processing of the stylesheet before adding it to the real DOM. It would be helpful to have a `.css` file without all the `/** */` Sass comments to reduce the CSS parsing & processing burden.

**Comment by adidahiya** [comment]
Eh, actually, in the meantime, I can get by in webpack with

```
                test: /\.css$/,
                use: [
                    "css-loader?" + JSON.stringify({ minimize: { discardComments: { removeAll: true } } }),
                ],
```

bumping back down to P3.

**Comment by giladgray** [comment]
i would love to remove those comments from the published CSS file, so i'll look into a way to do it.
