### ISSUE TITLE
Blueprint V5 alpha.1 - hotkeys "space" doesn't work

### ISSUE THREAD

**Issue by ptgamr** [palantir/blueprint#6138]
#### Environment

- __Package version(s)__: 5.0.0-alpha1
- __Operating System__: MacOS
- __Browser name and version__: Chrome

#### Steps to reproduce

Looks like a hotkey with `combo="space"` no longer working

#### Actual behavior

`onKeyDown` does not trigger

#### Expected behavior

`onKeyDown` should be triggered

#### Possible solution

Looks like in comboMatches function, it's trying to compare `key="space"` vs `key=" "`, so I guess there is a bug somewhere in parsing the key

<img width="908" alt="Screenshot 2023-05-09 at 11 58 49 PM" src="https://github.com/palantir/blueprint/assets/1619740/581e484a-b2ad-4ddd-a4d9-1981cee2ad35">

<img width="1095" alt="Screenshot 2023-05-09 at 11 59 00 PM" src="https://github.com/palantir/blueprint/assets/1619740/24066157-5264-4ab6-82b1-2958bd5c10a7">

**Comment by adidahiya** [comment]
@ptgamr thanks for the bug report. I missed this special case for the space key; we should parse the "space" combo as `event.key === " "`. I will fix it ASAP.

**Comment by adidahiya** [comment]
Fixed by #6139

**Comment by ptgamr** [comment]
@adidahiya thanks for the quick fix!
