### ISSUE TITLE
Checkbox not showing indeterminate state

### ISSUE THREAD

**Issue by bofa** [palantir/blueprint#6202]
#### Environment

- __Package version(s)__: 5.0.0-alpha.6
- __Operating System__: Windows 11
- __Browser name and version__: Chrome 113

#### Code Sandbox

[https://blueprintjs.com/docs/versions/5/#core/components/checkbox](https://blueprintjs.com/docs/versions/5/#core/components/checkbox)

#### Steps to reproduce

1. Open page
2. First checkbox in example should show indeterminate state

#### Actual behavior

Showing false state

#### Expected behavior

Show indeterminate state

#### Possible solution

Not sure what is going wrong, seams to be the same problem for a lot of versions.

**Comment by PetrusAsikainen** [comment]
Seems to be because `ref` is assigned to two different elements (both the `label` and the `input`) here. React DevTools shows the `useRef` as a `label`

https://github.com/palantir/blueprint/blob/next/packages/core/src/components/forms/controls.tsx#L124-L125

**Comment by adidahiya** [comment]
Fixed by #6208
