### ISSUE TITLE
Adding `portalContainer` to `PortalContext`/`PortalProvider`

### ISSUE THREAD

**Issue by braeden** [palantir/blueprint#6210]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Feature request

The ask is to add a React-context solution which forces all (blueprint) children that who render below a given `PortalProvider` (like `<Dialog/>`, `<Popover2/>`) to have a common `React.createPortal` container target. 

This allows for the app to have more fine-grained control over the bounds of portal background overlays & visibility when components may stay mounted in the background. 

Currently the `PortalContextOptions` interface has the following field:
```ts
interface PortalContextOptions {
     portalClassName: string | undefined
}
```

We propose expanding it with

```ts
interface PortalContextOptions {
     portalClassName: string | undefined,
     portalContainer?: HTMLElement
}
```

And subsequently drilling the result of `useContext(PortalContext).portalContainer` into `portalContainer` props of `Portal` based blueprint elements. 

But still allowing explicit overrides from individual usages , like `portalContainer={props.portalContainer ?? portalContext.portalConainter ?? document.body}`.
#### Examples

```tsx

    const ref = useRef<HTMLDivElement>(null);

    <PortalProvider portalContainer={ref}>
        <Dialog isOpen={true}>
            <span>This dialog will have a custom portal container </span>
        </Dialog>
        <div ref={ref}></div>
    </PortalProvider>,
```

**Comment by adidahiya** [comment]
Sounds good to me. Let's add this to v5.x after I merge `next` into `develop` (which should happen some time in the next week).
