### ISSUE TITLE
Tree component can’t be used without an icon loader

### ISSUE THREAD

**Issue by alex-kinokon** [palantir/blueprint#6213]
#### Environment

- __Package version(s)__: 5.0.0-beta.0
- __Operating System__:  N/A
- __Browser name and version__:  Chrome 114

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

```tsx
import { Tree } from "@blueprintjs/core";

render(<Tree contents={[ { id: 0, hasCaret: true, label: "text", childNodes: [] } ]} />)
```

#### Actual behavior
Error: Unable to load 16px icon 'chevron-right'

#### Expected behavior
Icon loads.

#### Possible solution
See https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tree/treeNode.tsx#L172. Using `<ChevronRight />` should fix it.

**Comment by adidahiya** [comment]
@alex-kinokon what JS bundler are you using? can you provide a sandbox or repro environment?

**Comment by alex-kinokon** [comment]
It might be a problem with Vite. I’ll keep you posted when I have more information.

**Comment by adidahiya** [comment]
Note that I'm changing some of the icon loader implementation right now; you might be able to get it working with the custom loader for Vite suggested in these new docs: https://github.com/palantir/blueprint/pull/6218/files#diff-6479f57171ad6f9b1ff521e1ca4acd07b04da1763ce7539b89b170650aeda750R105-R125
