### ISSUE TITLE
Static imported icons display shifted in 5.0.0-beta

### ISSUE THREAD

**Issue by tonooo71** [palantir/blueprint#6220]
#### Environment

- __Package version(s)__: 5.0.0-beta.0
- __Operating System__: Windows 10
- __Browser name and version__: Microsoft Edge 113.0.1774.42

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

- add an icon using static imports
- specify size (e.g. 32)

```
import { Bug } from "@blueprintjs/icons";

render(<Bug size={32} />)
```

#### Actual behavior

![bp5-alpha4](https://github.com/palantir/blueprint/assets/35133767/4a8e0fb8-3822-406a-b968-7adf6be7f16d)

(This is in 5.0.0-alpha.4)
(I added borders for clarity.)

#### Expected behavior

![bp5-beta0](https://github.com/palantir/blueprint/assets/35133767/c25654c4-9b7c-4438-8dd8-6483bf1601f6)

(This is in 5.0.0-beta.0)
(I added borders for clarity.)

**Comment by adidahiya** [comment]
Thanks for the bug report, I'll look into it.

**Comment by tonooo71** [comment]
Thank you for the fix!
