### ISSUE TITLE
[Tree] When label or icon in TreeNode is Element, cloneDeep cause a big performance problem

### ISSUE THREAD

**Issue by meenie-net** [palantir/blueprint#6221]
#### Environment

- __Package version(s)__: "@blueprintjs/core": "^4.18.0",
- __Operating System__: Win 10
- __Browser name and version__: Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

1. 
1. 
1. 

#### Actual behavior

When icon or label is Element(My case is input) , click each node always respond after about 1 second, but if icon or label is text, that's ok,  Chrome Dev Tool show me this:
![微信截图_20230614164338](https://github.com/palantir/blueprint/assets/22294209/78f7c898-9fa5-4a90-9cb0-80477e72723c)
![微信截图_20230614164532](https://github.com/palantir/blueprint/assets/22294209/d47f49ec-a78e-4532-8608-3d289c8349a9)

**Comment by adidahiya** [comment]
@meenie-net can you provide a code sandbox or stackblitz repro example to help me debug? Note that `cloneDeep()` is only used in the docs-app TreeExample, and is not used by the Tree component itself.

**Comment by meenie-net** [comment]
@adidahiya After restart my computer, the problem was solved itself. The control variable method confused me in the partial part so that I forgot to try the most basic solution. I will close this.
