### ISSUE TITLE
Are the CSS classes for Trees public?

### ISSUE THREAD

**Issue by chrbala** [palantir/blueprint#623]
Simply, can I expect to use CSS classes like ``pt-tree-node-caret``, ``pt-tree-node-caret-open``, ``pt-tree-node``, etc. without being surprised with breaking changes?

**Comment by llorca** [comment]
They are public indeed, as with everything you can find in `classes.ts` 👍  With that said, can't guarantee that there won't be breaking changes between major versions.

**Comment by giladgray** [comment]
as @llorca said, anything listed in [`classes.ts`](https://github.com/palantir/blueprint/blob/master/packages/core/src/common/classes.ts) is part of the public API and can be safely used in your application.

as for breaking changes, we hope our [release notes](https://github.com/palantir/blueprint/releases) and adherence to semver will ensure you'll never be _surprised_ by them 😄
