### ISSUE TITLE
Update OverlayToaster component to use ReactDOM.createRoot() for React 18 compatibility

### ISSUE THREAD

**Issue by andrewkrippner** [palantir/blueprint#6239]
#### Environment

- __Package version(s)__: 5.0.0
- __Operating System__: MacOS
- __Browser name and version__: Chrome 114.0.5735.133

#### Steps to reproduce

Use the OverlayToaster component in a React 18 application.
Observe the console warnings about ReactDOM.render() being deprecated.

#### Actual behavior

The OverlayToaster component in BlueprintJS uses the ReactDOM.render() method, which is deprecated in React 18. This causes the application to behave as if it's running React 17, according to the warning message from React.

#### Expected behavior

The OverlayToaster component should use the new ReactDOM.createRoot() method introduced in React 18, so that it can take advantage of the new features and improvements in React 18.

#### Possible solution

Update the OverlayToaster component to use ReactDOM.createRoot() instead of ReactDOM.render(). This might involve refactoring the component to accommodate the new root API, which involves creating a root and then calling render on it, as opposed to the legacy API where render is called directly with the component and container.

**Comment by adidahiya** [comment]
Thanks for the detailed issue report. Putting this on the v5.x milestone. Related: https://github.com/palantir/blueprint/issues/3979
