### ISSUE TITLE
Feature: styles for common display fields

### ISSUE THREAD

**Issue by bsr203** [palantir/blueprint#625]
While migrating from bootstrap 4 to blueprint, some analogous styles are lacking. For example.

1. static form fields
http://v4-alpha.getbootstrap.com/components/forms/#static-controls

this may be useful to display readonly fields, and also to display Display/View (CRUD) fields.

2. titles, dashboard fields
http://v4-alpha.getbootstrap.com/content/typography/#display-headings
http://bulma.io/documentation/elements/title/

User could easily style these in their app, but some classes to cover the basics would ease migration and feel uniform.

thanks,
bsr.

**Comment by llorca** [comment]
We cover headings already: http://blueprintjs.com/docs/#typography.headings

For static controls, we have `readonly` inputs that have been working well so far.

**Comment by bsr203** [comment]
ok. thanks. feel free to close, if you feel that additional styles would increase maintenance burden. I will try with `readonly`.

**Comment by llorca** [comment]
Yup, not sure what the semantic equivalent of "raw text value" in a form is besides `readonly`. We also have `:disabled` and `.pt-disabled` if you need to disable all interactions, but the text will be more lightweight. Let me know if you think of anything else and we can revisit
