### ISSUE TITLE
[v5] Hotkeys using `alt` no longer work as expected

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#6257]
#### Environment

- __Package version(s)__: 5.0.0-beta.2
- __Operating System__: OSX
- __Browser name and version__: Chrome 114.0.5735.133

#### Code Sandbox

https://stackblitz.com/edit/vitejs-vite-vsbugp?file=src%2FCoreExample.tsx

#### Steps to reproduce

1. Make a hotkey like this:

```
      {
        label: "test",
        global: true,
        combo: "alt+a",
        onKeyDown: () => {
          alert("here");
        }
      }
```

2. Attempt to trigger it with `alt+a`

#### Actual behavior

Nothing happens.

#### Expected behavior

Alert appears.

#### Possible solution

This line swapped the key combo parsing to use `event.key` instead of `event.which`: https://github.com/palantir/blueprint/pull/6106/files#diff-fec59d61737971c807d9d0b765c8d0c3ba1d1f1880cdd4b3a652ab0789d016dbR169

The `key` in the case of `alt+a` is `å`, and I suspect is also variable depending on keyboard settings. Probably shouldn't depend on `key` for parsing key combos?

**Comment by adidahiya** [comment]
I have a fix, opened a PR here: https://github.com/palantir/blueprint/pull/6301
