### ISSUE TITLE
React v18 support for version 3

### ISSUE THREAD

**Issue by nrakochy** [palantir/blueprint#6262]
#### Environment

- __Package version(s)__: `3.54`

#### Feature request

Would you consider a PR to include the React v18 typescript support into version 3? I am thinking in terms of cherry-picking the fixes from #5250 as well as #5518

Thanks for your consideration 🙏

**Comment by adidahiya** [comment]
@nrakochy no, Blueprint v3 is quite old (more than 1 year since last release) and I don't plan to backport anything to that version. Some limited backports to v4.x will be considered.
