### ISSUE TITLE
Icon Rendering Issues in Remix App after Upgrading from BlueprintJS 4 to 5

### ISSUE THREAD

**Issue by AlexGodard** [palantir/blueprint#6264]
#### Environment

- __Package version(s)__: 5.0.0
- __Browser and OS versions__: Chrome 114, Ubuntu 23.04

#### Question

I've just upgraded my Remix App from BlueprintJS 4 to 5 and I can't figure out how to get the icons to work properly.

In this [example](https://codesandbox.io/p/github/AlexGodard/remix-blueprintjs/master?workspaceId=16d2676f-810b-4f12-a9f7-b09721192eac), I have two buttons both rendering a different icon. The Download button's icon is loaded using dynamic imports, and the Search button's icon is loaded using a static import. Both of them are janky, they seem to render smaller than the size I want them to be (16px), and then once the icons fetching from the network is complete, they get sized correctly (usually 200-400ms after).

This problem seems specific to [Remix](https://remix.run/). Since Remix is using its own bundler, I can't hook up into `vite` or `webpack` to load all icons in the bundle before the first render (which is what version 4 was doing, if I understood correctly).

Any help would be appreciated.

**Comment by adidahiya** [comment]
@AlexGodard there is a variant of approach (2) described in the [Loading icons > Using dynamic imports](https://blueprintjs.com/docs/#icons/loading-icons.using-dynamic-imports) documentation which may work for your use case.

Instead of using a dynamic import to create a separate bundle "blueprint-icons-all-paths" chunk, you can use a static import via the `getIconPaths` API to replicate the behavior of Blueprint v4.x icons:

```ts
import { getIconPaths, Icons } from "@blueprintjs/icons";

Icons.setLoaderOptions({
    loader: async (name, size) => getIconPaths(name, size),
});

await Icons.loadAll();
```

Let me know if this works for you, and I will update the documentation to make this easier to find.

**Comment by AlexGodard** [comment]
Unfortunately Remix [does not support top-level await yet](https://github.com/remix-run/remix/discussions/5203). I've tried loading the icon like this:
```javascript
import { getIconPaths, Icons } from "@blueprintjs/icons";

Icons.setLoaderOptions({
  loader: async (name, size) => getIconPaths(name, size),
});

export async function loader() {
  await Icons.loadAll();
  return json({ message: "Hello World" });
}
```
In my `root.tsx` file, but still getting janky icons.

I realize that this is probably a Remix-specific issue, so if you think their repo is a better place to get help, I'll go post my issue there too.

EDIT: Posted my issue here: https://github.com/remix-run/remix/discussions/6811

**Comment by adidahiya** [comment]
Closing as "documented well enough" for now; this may be a Remix-specific issue which requires a Remix-specific solution.
