### ISSUE TITLE
Allow <i> as an alternative to <span> for icons

### ISSUE THREAD

**Issue by EmmaRamirez** [palantir/blueprint#627]
Currently, blueprintjs requires span tags for its icons. I think it would be intuitive to also allow `<i>` tags for pt-icons as well. My reasoning is as follows:

- `<i>` is used by multiple libraries, such as fontawesome and material-icons
- `<i>` has semantic meaning as more than italics, as follows from whatwg:

<blockquote>The i element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term, an idiomatic phrase from another language, transliteration, a thought, or a ship name in Western texts.</blockquote>

- It's a small css change that allows easier integration into existing systems where `<i>` is used as the primary tag for icon fonts

**Comment by llorca** [comment]
@EmmaRamirez is there anything preventing you from using `<span>`?
