### ISSUE TITLE
Tooltip2 gets stuck on on disabled HTMLSelect

### ISSUE THREAD

**Issue by luigilake** [palantir/blueprint#6271]
#### Environment

- __Package version(s)__: 4.14.3
- __Operating System__: macOS Monterey, 12.5.1
- __Browser name and version__:  Chrome 114

#### Steps to reproduce
```
<Tooltip2 content="example text" disabled={!disabled}>
    <HTMLSelect disabled={disabled} />
</Tooltip2>
```

1. Hover over the **disabled** HTMLSelect
2. Expect to see the tooltip pop up
3. Move mouse elsewhere so HTMLSelect is **not** hovered
4. Expect the tooltip to disappear

#### Actual behavior

Tooltip stays open. This behavior is similar to if you use a Button inside a Tooltip2, instead of the proper AnchorButton within the Tooltip2

#### Expected behavior

Tooltip should disappear when the disabled HTML select is no longer hovered

**Comment by adidahiya** [comment]
We can't really do anything to fix this, just like `<Tooltip disabled={true}><Button /></Tooltip>` ([see callout in AnchorButton vs Button docs](https://blueprintjs.com/docs/#core/components/buttons)). It's native browser / DOM behavior. If you need to use a Tooltip with a disabled `<select>` element, you're better off using `{ Select } from "@blueprintjs/select"`.
