### ISSUE TITLE
Right edge of table extends 1px too much

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#628]
![image](https://cloud.githubusercontent.com/assets/199754/22666782/e6d6bda0-ec6e-11e6-919a-d715da53c6a9.png)
![image](https://cloud.githubusercontent.com/assets/199754/22666794/f0f86a4a-ec6e-11e6-894a-00500c2ae7de.png)

The rightmost column is misaligned with the header. If the table is smaller than the body content, it creates a double border

**Comment by cmslewis** [comment]
@giladgray @adidahiya I'll try this as my starter bug on table.

**Comment by cmslewis** [comment]
I had opened a PR to address this, but I eventually noticed that as of the past couple days, this issue doesn't seem to appear on `master` anymore. (Not sure what changed, but I can't get it to repro.) Closing for now.

_Latest `master`:_

![image](https://cloud.githubusercontent.com/assets/443450/24163777/ca07d6d8-0e28-11e7-9730-a763e21de3f8.png)

![image](https://cloud.githubusercontent.com/assets/443450/24163788/cda59546-0e28-11e7-8441-ad307b479365.png)

**Comment by cmslewis** [comment]
@llorca et al - Did more digging. This is the commit that unintentionally fixed this issue: https://github.com/palantir/blueprint/pull/851/commits/07636359b9a47f4baaa7d69087c72ac04efd087c (allowing custom `className`s on `ColumnHeaderCell`).
