### ISSUE TITLE
Remove IE11 from autoprefixer supported browsers configuration

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#6288]
#### Environment

- __Package version(s)__: core v5.1.4

#### Feature request

According to https://github.com/palantir/blueprint/commit/0aa20c9aadc5bac043988a994e4b4da90718198c#commitcomment-122026945, it seems like we might still be telling autoprefixer to support IE11. Remove this browser may be a small performance improvement - it could reduce the size of our generated CSS file a little bit.

**Comment by SoulPancake** [comment]
> we might still be telling autoprefixer to support IE11

How do we do this?
I don't see IE11 mentioned anywhere other than the scss files themselves
How do we go about solving this? @adidahiya

**Comment by adidahiya** [comment]
I looked at this more closely and I was wrong when initially filing the issue.

I saw that our `.browserslistrc` says `last 2 versions, not dead, > 0.2%` -- and [looking this up on browsersl.ist](https://browsersl.ist/#q=last+2+versions%2C+not+dead%2C+%3E+0.2%25), I saw that IE11 still appears since its usage is 0.39% globally:

![image](https://github.com/palantir/blueprint/assets/723999/8aca0718-ce97-4fc6-9f19-c54ed58dba30)

But if you try to exclude IE 11 specifically, you notice that it's already being excluded via `not dead`:

![image](https://github.com/palantir/blueprint/assets/723999/67c20924-25b3-4cf6-adee-7b993610a7cd)

So I think we're good here! No need to fix/solve anything.
