### ISSUE TITLE
Webpack-bundled JS in NPM distribution is not browser-ready

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#631]
In #630, I tried to use the unpkg distribution of `@blueprintjs/core` 1.8.0 but couldn't find a way to access the browser globals for the core components.

**Comment by giladgray** [comment]
1. your jsbin is missing several dependencies, namely classnames and tether.
2. i'm going to internalize (remove from `externals`) tslib.
3. i'll add `browser` field to package.json
