### ISSUE TITLE
Text component doesn't correctly attach ref passed via props

### ISSUE THREAD

**Issue by maclockard** [palantir/blueprint#6320]
The [`Text`](https://github.com/palantir/blueprint/blob/cba5612d28e0ba3d13e7ff21cf94b2e25e01ebb1/packages/core/src/components/text/text.tsx) component allows for a `ref` for the underlying HTML element via including `React.HTMLAttributes<HTMLElement>` in the props. However, the component passes its own ref in [here](https://github.com/palantir/blueprint/blob/cba5612d28e0ba3d13e7ff21cf94b2e25e01ebb1/packages/core/src/components/text/text.tsx#L73-L87). This results in a ref passed to `Text` never being invoked/set.

Ideally instead this ref should compose with whatever ref is passed

**Comment by pgoldberg** [comment]
Hey @maclockard!

I may be wrong, but I actually don't think `ref` is exposed in `React.HTMLAttributes<HTMLElement>` (it would be in `React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>>`). Would you want this as a feature request?

**Comment by adidahiya** [comment]
> I may be wrong, but I actually don't think `ref` is exposed in `React.HTMLAttributes<HTMLElement>` (it would be in `React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>>`). Would you want this as a feature request?

Yeah, that sounds right. `ref` is not currently a supported prop of `<Text>`. Open to adding this prop as a feature request.

<img width="1019" alt="image" src="https://github.com/palantir/blueprint/assets/723999/42c52035-a447-43b4-9329-1348b4e1ddfb">

**Comment by maclockard** [comment]
Ahhh. Looking a bit closer at our types I think its from us being on an older version of blueprint that still uses class components, which the React types auto adds a ref prop to looking at it?

Yeah, would be great to have this as a feature request!

**Comment by adidahiya** [comment]
> React types auto adds a ref prop

With the class component implementation, you get a ref to the `Text` component instance, not the DOM node. Part of the motivation for migrating to FCs is to use `forwardRef` so that `ref` gives you access to the DOM node, like it would with intrinsic elements.

I'll take a look at your PR.
