### ISSUE TITLE
Aria expanded is unnecessary in tab

### ISSUE THREAD

**Issue by firzok** [palantir/blueprint#6332]
Based on the [documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#:~:text=When%20a%20multi%2Dselectable%20tablist%20is%20selected%20or%20active%2C%20its%20corresponding%20controlled%20tabpanel%20should%20have%20its%20aria%2Dexpanded%20attribute%20set%20to%20true%20and%20its%20hidden%20attribute%20set%20to%20false%2C%20otherwise%20the%20reverse.) I believe that the aria-expanded attribute is not necessary and can be removed from [here](https://github.com/palantir/blueprint/blame/1a433b4833cb4136f68da3683fa9b9a29d0e4a3e/packages/core/src/components/tabs/tabTitle.tsx#L64C41-L64C41)

Please correct me if I am wrong.

**Comment by adidahiya** [comment]
The "tab" role documentation you linked does seem to suggest that `aria-expanded` is superfluous. But the [`aria-expanded` documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#associated_roles) does link the attribute to the "tab" role. There's some inconsistency in MDN.

The [W3C spec for "tab"](https://w3c.github.io/aria/#tab) states that `aria-expanded` is supported. So I think it's safe to leave as an attribute.
