### ISSUE TITLE
Namespace variables

### ISSUE THREAD

**Issue by bsr203** [palantir/blueprint#636]
I was trying to mix `blueprint` with part of twitter bootstrap. Even if I import the bootstrap variables to just the component it uses, blueprint scss still picks it up. I guess that's the way sass treat global variables. 

For examples: `input-box-shadow-focus`
bs4: `$input-box-shadow-focus:         $input-box-shadow, rgba($input-border-focus, .6) !default;`
blueprint: `$input-box-shadow-focus: inset 0 1px 1px rgba($black, $pt-drop-shadow-opacity) !default;`

using bootstrap causes blueprint to use the wrong value, and set incorrect box-shadow value, which the browser ignores.

can`blueprint` use namespace for all of its variables to avoid collision.

thanks.
bsr.

**Comment by giladgray** [comment]
@bsr203 sorry buddy! using blueprint and bootstrap in sass at the same time sounds like a recipe for disaster, and an edge case of the highest order. 

we only prefix the "public" variables that end up in `dist/variables.scss`; component-level variables are considering "private" and aren't prefixed so they can be distinguished from public ones.

along the same lines, we don't have a full support story yet for our own sass APIs. at this time, the best i've got is "yes you _can_ consume the Blueprint scss files (we did what we could to make that possible #123), but we can't offer support resources. also, we reserve the right to break the Sass APIs at any time, except for items in `classes.ts` or `$pt-`-prefixed variables."

**Comment by bsr203** [comment]
@giladgray thanks for explaining the situation. I would work around this :-) I greatly enjoy this high quality library. thanks.
