### ISSUE TITLE
OverlayToaster does not accept children as props with @types/react v18

### ISSUE THREAD

**Issue by SiimTa** [palantir/blueprint#6363]
#### Environment

- Package version(s): 5.2.1
- Browser and OS versions: Windows 11

#### Problem

After migrating to version 5.x.x, I noticed that OverlayToaster does not accept children anymore. I suspect this was not intended?
There are still examples about it here: https://blueprintjs.com/docs/#core/components/toast.overlaytoaster
And also there was no mention of deprecating children and only using the recommended consumption in the changelog

**Comment by adidahiya** [comment]
@SiimTa are you using @types/react v18? Do you have a code sandbox link to repro the issue?

Removal of the children API for `<OverlayToaster>` was not intended in v5.0. I think this should be an easy fix, we just need to explicitly declare `children` as a prop in `OverlayToasterProps`, similar to this PR where we did it for other class components: https://github.com/palantir/blueprint/pull/5266

**Comment by SiimTa** [comment]
> @SiimTa are you using @types/react v18? Do you have a code sandbox link to repro the issue?
> 
> Removal of the children API for `<OverlayToaster>` was not intended in v5.0. I think this should be an easy fix, we just need to explicitly declare `children` as a prop in `OverlayToasterProps`, similar to this PR where we did it for other class components: #5266

Yes @adidahiya , `@types/react` version 18.2.21

**Comment by SiimTa** [comment]
@adidahiya Sure, here it is: https://codesandbox.io/s/blueprintjs-overlaytoaster-prop-problems-vsld8l

If you don't define any other props, it works fine. But as soon as I define anything("position" in that case), it cannot find the children prop.
