### ISSUE TITLE
Easy way to show tree-node specific context menus

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#637]
We're using `Tree` as the base for a file picker tree in our app. We want to show a right-click context menu that varies depending on the file you right click on. As far as I can tell, there's no easy way to do this right now.

Using `ITreeNodeProps#onclick` and `ContextMenu::show` won't work because some browsers don't fire `onclick` events for right clicks. There's also no way to use the current ContextMenu decorator for individual tree nodes, or to implement the methods it would require.

Let me know if I'm missing a good way to do things! But if this requires a new feature, I can see this being a worthwhile feature to add to the API of `ITreeNode`.

Proposed solution: simply add an `onContextMenu` prop to `ITreeNode` and pass it through to the underlying div.

**Comment by giladgray** [comment]
⬆️  looks like _somebody_ force pushed 😱  @JKillian busted!
