### ISSUE TITLE
Not able to close Overlay on first render if lazy `true`

### ISSUE THREAD

**Issue by SiimTa** [palantir/blueprint#6399]
#### Environment

- Package version(s): 5.3.0
- Browser and OS versions: Windows 11

#### Problem
When you try to close Overlay(drawer, dialog, alert, ...) with escape key, it will not succeed on the first render of the overlay. Next tries will work, but from accessibility perspective user may get stuck in the mentioned overlay.
You can try it out on the examples: https://blueprintjs.com/docs/#core/components/drawer

The problem is not present when `lazy` prop is set to `false`, so I guess that's a workaround until fixed.

**Comment by adidahiya** [comment]
@SiimTa thanks for the bug report. This may be slightly related to #5947.

**Comment by adidahiya** [comment]
Fixed in Overlay2 component via https://github.com/palantir/blueprint/pull/6656
