### ISSUE TITLE
Host older versions of docs site

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#64]
ideas:

- `docs/docs/<version>/index.html`?
- use https://github.com/htmlpreview/htmlpreview.github.com?

**Comment by adidahiya** [comment]
Discussed offline -- similar to https://lodash.com/docs/, we decided that we'll check in older versions of the docs site but __only limit this to one per major version__. So, every time we have a major version bump, we'll have to check in a folder containing docs for the last stable release.

**Comment by llorca** [comment]
Looks like we know what we want to do -- there doesn't seem to be any action required here. When we release 2.0 in the coming months, we'll make sure to keep the latest 1.x docs around as well. Gonna close this out.
