### ISSUE TITLE
Why is `blueprint-icons.ttf` always requested?

### ISSUE THREAD

**Issue by bitjson** [palantir/blueprint#6401]
#### Environment

- __Package version(s)__: @blueprintjs/icons@5.1.7
- __Browser and OS versions__: Chromium: 115.0.5790.171 (arm64), macOS 13.6

#### Question

I'm using `@blueprintjs/icons` in a Vite project (`yarn create vite repro-app --template react-swc-ts`) following the [static imports method](https://blueprintjs.com/docs/#icons/loading-icons.using-static-imports), e.g.:

```ts
import { Person } from '@blueprintjs/icons';

// ...

<Person size={12} />
```

When I throttle network speed and record performance in Chrome, I notice that `blueprint-icons.ttf` is the last resource requested over the network, delaying the `Load` event a little while longer:

<img width="663" alt="Screenshot 2023-09-21 at 10 15 43 PM" src="https://github.com/palantir/blueprint/assets/904007/ff9a0181-dc99-42fb-a39f-7523f7d97b72">

As far as I can tell, icons are already being rendered as SVGs before this request is even made, and I'm not certain if this file ever gets used.

Could anyone help me understand – what is the purpose of this file? Is it possible to configure `@blueprintjs/icons` to prevent the file from being requested? Thanks!

**Comment by adidahiya** [comment]
> Is it possible to configure `@blueprintjs/icons` to prevent the file from being requested?

Yes, it should be possible to avoid the font imports by omitting `blueprint-icons.css` from your bundle. You will notice that this file _only_ imports font files, so if you are not using any of the icon font APIs, you can remove any import of it:

```diff
- import "@blueprintjs/icons/lib/css/blueprint-icons.css";
```

See: https://unpkg.com/browse/@blueprintjs/icons@5.1.7/lib/css/blueprint-icons.css

**Comment by bitjson** [comment]
Ah, great, thanks for the confirmation!
