### ISSUE TITLE
Enabling portalStopPropagationEvents for a dialog cases button popovers to not work

### ISSUE THREAD

**Issue by PhoebeSzmucer** [palantir/blueprint#6428]
#### Environment

- __Package version(s)__: 4.19.0+ (since [this PR](https://github.com/palantir/blueprint/pull/6093))

#### Code Sandbox

https://codesandbox.io/p/sandbox/wizardly-leftpad-yfhw8n?file=%2Fsrc%2FCoreExample.tsx%3A22%2C56

#### Steps to reproduce

Add `portalStopPropagationEvents={["click"]}` to a dialog (or a portal) that renders a popover inside of it.

#### Actual behavior

Popover doesn't open

#### Expected behavior

Popover should open

**Comment by adidahiya** [comment]
I forked/updated your sandbox to use the latest popover2 package version and I can still repro the bug: https://codesandbox.io/p/sandbox/wizardly-leftpad-yfhw8n?file=%2Fsrc%2FCoreExample.tsx%3A22%2C56
