### ISSUE TITLE
The minDate property of DateInput not working in ideal way during the end of the day

### ISSUE THREAD

**Issue by sudharshan-tagalys** [palantir/blueprint#6430]
#### Environment

- __Package version(s)__:      "@blueprintjs/core": "3.54.0",  "@blueprintjs/datetime": "3.24.0",
- __Operating System__:  ubuntu
- __Browser name and version__:  Chrome 115.0

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/laughing-monad-dhpj4k?file=/src/index.tsx)): 

Hi Team,
I am trying to display a DateInput with minDate as 1 hour from the current time. It works in all the case, but when the time is post 11 PM, the DateInput component works in a bit weird way. On clicking the date input, the month picker show "January" and year picker shows "2024".

![image](https://github.com/palantir/blueprint/assets/104345194/6aef784c-7018-4f08-bbc3-2b3643e2a042)

#### Steps to reproduce

1. Change your system time to 11:10 PM (anytime between 11 PM  - 11:59 PM)
2. Click on the date input,

#### Actual behavior

1. Month picker in Date input showing "January" and year picker showing "2024"

#### Expected behavior
1. Month picker should show "October" and year picker should show "2023"

**Comment by adidahiya** [comment]
@sudharshan-tagalys your versions of Blueprint libraries are quite old, can you try to repro the bug in the most recent version of Blueprint? It's very unlikely that anyone will attempt to fix a bug in v3.x. We are on v5.x now.

**Comment by sudharshan-tagalys** [comment]
@adidahiya Seems like the max version codesandbox supports:
  @blueprintjs/core": "4.17.8"
  @blueprintjs/datetime": "4.4.27"
  @blueprintjs/popover2": "1.13.12"
  @blueprintjs/select": "4.9.12"
  
I have updated the codesandbox to the above-mentioned versions. I am able to reproduce the bug in 4.x too

**Comment by adidahiya** [comment]
@sudharshan-tagalys codesandbox does support v5.x. You can edit the package.json for the sandbox and manually enter the latest versions, which you can see listed here:

https://github.com/palantir/blueprint/blob/20032777f4e67858e91edf0fa301dbfc5841ceaf/packages/docs-app/package.json#L20-L29

**Comment by sudharshan-tagalys** [comment]
@adidahiya  Apologies for the confusion, I have updated the sandbox to use blueprintjs 5.x, still facing the mentioned issue.

**Comment by adidahiya** [comment]
Ok cool, thanks for updating the sandbox @sudharshan-tagalys.

I forked your sandbox to use the latest @blueprintjs/datetime2 components and I can repro the same behavior: https://codesandbox.io/s/exciting-newton-lw24tl?file=/src/index.tsx

However, taking a closer look at this, I see that the component is behaving as intended. When you set a `minDate` and `maxDate` but no `initialMonth`, the component will [pick a date that falls in the middle of the selectable range to use as the initial display month](https://github.com/palantir/blueprint/blob/a2fed894c44dfb59e2b9ed264e9f6adb819e12ac/packages/datetime2/src/components/date-picker3/datePicker3.tsx#L409-L422) in the date picker. In this case, that ends up being a date in January, which is halfway between October 2023 & April 2024 (the default max date is +6 months from now).

If you wish to have a particular initial month displayed in the calendar, I recommend using the `initialMonth` prop. You can see it working in my sandbox above.

<img width="569" alt="image" src="https://github.com/palantir/blueprint/assets/723999/e28a4531-d9d0-4824-aac5-b25d30e45974">
