### ISSUE TITLE
Ability to scroll a specific item in a tree into view

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#644]
Would like to be able to scroll a specific item in a tree into view.  This is useful for any feature where interactions outside of the tree need to reveal something inside of the tree.  Couldn't find a way to do it using the existing component.

**Comment by JKillian** [comment]
Talked this over with @giladgray and decided to go about it this way:

* Add a `Tree#getNodeRef` function to core Blueprint
* Application code can then implement this functionality themselves:
  - expand all parents of a given node
  - call `myTreeRef.getNodeRef("myNode").scrollIntoView()`
