### ISSUE TITLE
NumericInput auto-highlights text on parent component update

### ISSUE THREAD

**Issue by styu** [palantir/blueprint#647]
### Bug report

- __Package version(s)__:  1.8
- __Browser and OS versions__: Chrome 56.0.2924.87 (64-bit), Mac OSX 10.11.6

#### Steps to reproduce

1. Use `<NumericInput />` inside another React component
1. Cause the parent component to update (e.g. update the props to the parent component with the new value from the numeric input)

#### Actual behavior

Text highlights on every update

![highlightingtext](https://cloud.githubusercontent.com/assets/1143755/22757374/80635e24-ee18-11e6-877c-cf679cbd93e9.gif)

#### Expected behavior

Text should not highlight

**Comment by cmslewis** [comment]
@styu Opened a PR with a fix! Should be in by tomorrow's release.

**Comment by cmslewis** [comment]
Also, the sad face in your GIF is gut-wrenching. T_T

**Comment by styu** [comment]
@cmslewis thanks! 
and haha sorry about that, it took me a little while to realize what was happening is all x)

**Comment by kylesheely** [comment]
I'm still experiencing this issue in IE11. I can replicate it in the controlled example that was added in the docs as part of the 1.9.0 release.  http://blueprintjs.com/docs/#components.forms.numeric-input

**Comment by kylesheely** [comment]
Actually, the behavior I'm seeing is a blur/focus loop. I can only replicate it in IE11. It happens in both 1.8 and 1.9.

**Comment by cmslewis** [comment]
Hi @kylesheely, glad to see that followup clarification. ^ I found that focus-loop issue last week (see #704) and pushed a fix as part of PR #705. Coming to a theater near you in our next release, which will probably two days from now.

**Comment by kylesheely** [comment]
Thanks @cmslewis !

**Comment by timurridjanovic** [comment]
I'm still experiencing this issue in uncontrolled mode.
