### ISSUE TITLE
datetime2/DatePicker3 component - "Could not load "en-US" date-fns locale" in Vite

### ISSUE THREAD

**Issue by EduBic** [palantir/blueprint#6481]
#### Environment

- __Package version(s)__: 2.2.1
- __Operating System__: Windows 11 / dev environment: Ubuntu 22.04.2 WSL2
- __Browser name and version__: Chrome 118.0.5993.89

#### Code Sample

```tsx
// main.tsx
import ReactDOM from 'react-dom/client'
import { DatePicker3 } from '@blueprintjs/datetime2'

import "@blueprintjs/core/lib/css/blueprint.css";
import "@blueprintjs/icons/lib/css/blueprint-icons.css";
import "@blueprintjs/datetime2/lib/css/blueprint-datetime2.css";

ReactDOM.createRoot(document.getElementById('root')!).render(
  <DatePicker3 />,
)
```

The project `package.json`
```json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@blueprintjs/core": "^5.5.1",
    "@blueprintjs/datetime2": "^2.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}
```

#### Steps to reproduce

1. npm create vite@latest 
2. React + Typescript
3. npm add @blueprintjs/core 
4. npm install --save @blueprintjs/datetime2
5. npm run dev

#### Actual behavior
The DatePicker3 works as expected but the console show an error:
`dateFnsLocaleUtils.ts:35 [Blueprint] Could not load "en-US" date-fns locale, please check that this locale code is supported: https://github.com/date-fns/date-fns/tree/main/src/locale`

And the locale en-US exists.

How to solve it? Some props are needed?
I guess the problem is just a misconfiguration from my side.

Thanks

**Comment by adidahiya** [comment]
@EduBic Thanks for the report, I just realized that I was getting the same module loading error in Vite.

I went ahead and updated the [Blueprint code sandbox template](https://codesandbox.io/p/sandbox/blueprint-v5-x-sandbox-react-16-wy0ojy?file=%2Fsrc%2FDatetimeExample.tsx%3A12%2C3) to demonstrate usage of date-fns locale loading in Vite. You need to install "date-fns" as a dependency and define your own `dateFnsLocaleLoader` that accommodates for [Vite's dynamic import limitations](https://vitejs.dev/guide/features.html#dynamic-import). For example, if your code is in a `src/` directory which is adjacent to your `node_modules/`, you can use a loading pattern like this:

```tsx
import { Locale } from "date-fns";
import React from "react";
import { DatePicker3 } from "@blueprintjs/datetime2";

const loadDateFnsLocale: (localeCode: string) => Promise<Locale> = async (
  localeCode,
) => {
  const localeModule = await import(
    `../node_modules/date-fns/esm/locale/${localeCode}/index.js`
  );
  return localeModule.default;
};

export const Example: React.FC = () => {
  return (
    <DatePicker3
      dateFnsLocaleLoader={loadDateFnsLocale}
    />
  );
};
```

I realize this is non-obvious from the documentation right now. I'll go ahead and update the docs.

**Comment by Lonli-Lokli** [comment]
@adidahiya Is it possible to make date-fns completely optional? We do not have it in our app and do not plan to use it. 
We also do not need any localization.

**Comment by monken** [comment]
I was able to simplify this:

```bash
npm install date-fns@^2.30.0
```

```ts

import { enUS } from 'date-fns/locale';

function MyComponent() {
  return <DateInput3 dateFnsLocaleLoader={() => Promise.resolve(enUS)} />
}
```

**Comment by mrhether** [comment]
For most vite setups you could:
```
npm install date-fns@^2.30.0
```

```tsx
const localeLoader = async (localeCode: string) =>
  await import(`date-fns/locale/${localeCode}`);

<DatePicker3 dateFnsLocaleLoader={localeLoader} />
```
