### ISSUE TITLE
React 18 with Typescript error in Core / Overlay - No constituent of type 'ReactNode & Function' is callable.

### ISSUE THREAD

**Issue by pxmal** [palantir/blueprint#6550]
#### Environment

- __Package version(s)__:  "@blueprintjs/core": "^5.6.0", "react": "^18.2.0", "@types/react": "^18.2.37"

#### Behavior

```
node_modules/@blueprintjs/core/src/components/overlay/overlay.tsx(370,21): error TS2349: This expression is not callable.
  No constituent of type 'ReactNode & Function' is callable.

370: child = child();
```

I found the following [reply](https://github.com/palantir/blueprint/issues/5250#issuecomment-1136988510) on another issue that has/had the same problem, but I can't find anything on it.

Any advice here?

**Comment by adidahiya** [comment]
@pxmal can you please create a code sandbox demonstrating your issue? There's a sandbox template linked in the issue template, the project README, and the docs home page.

**Comment by pxmal** [comment]
Apologies. Had an import like this: `import {Overlay} from "@blueprintjs/core/src/components/overlay/overlay";`

Fixed by changing to: `import {Overlay} from "@blueprintjs/core";`
