### ISSUE TITLE
Upgrade of `@blueprintjs/core` from 5.6.0 to 5.7.0 yields errors when using `npm`

### ISSUE THREAD

**Issue by elmarsto** [palantir/blueprint#6556]
After upgrading `package.json` from 5.6.0 to 5.7.0 using `npm` (instead of, say, `yarn` or `pnpm`), the subsequent `npm install` yields:

![image](https://github.com/palantir/blueprint/assets/315987/8749cf70-fa94-47d1-9b92-f84e91aa64e2)

#### Environment

-  NixOS 23.05
- npm 9.6.7
- node v18.17.1

#### Steps to reproduce

1.  Take an existing Blueprint project which uses `npm`. In `package.json`, confirm that the version number of `@blueprintjs/core` is 5.6.0.
2.  Replace '5.6.0' with '5.7.0' in the relevant line in `package.json`.
3. Run `npm install`

#### Actual behavior

`npm install` yielded the following error:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

#### Expected behavior

I expected the build to complete normally, as it did immediately prior to the upgrade

#### Possible solution

Review all code in the 5.6.0→5.7.0 diff for the string `workspace:`, which is a protocol format supported by `yarn` and `pnpm` but not `npm`. [Stackoverflow](https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace)

**Comment by Gatix** [comment]
I'm having the same issue with yarn
```
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @blueprintjs/core@workspace:^: Workspace not found (@blueprintjs/core@workspace:^)
...
➤ YN0000: └ Completed in 1s 830ms
➤ YN0000: · Failed with errors in 1s 840ms
```

**Comment by rcbevans** [comment]
I'm seeing a load of errors like:

>Couldn't find any versions for "@blueprintjs/colors" that matches "workspace:^"
? Please choose a version of "@blueprintjs/colors" from this list: (Use arrow keys)

for colors, icons, and select.

**Comment by alex-kinokon** [comment]
https://github.com/palantir/blueprint/blob/c3fe193babe2e83f17630d3de859c9d100b2053a/packages/core/package.json#L52

**Comment by ihsw** [comment]
Had to remove the `^` from my `@blueprintjs/*` deps to fix this.

Eg:
```
    "@blueprintjs/core": "5.5.0",
    "@blueprintjs/datetime": "5.2.3",
    "@blueprintjs/datetime2": "2.2.0",
    "@blueprintjs/icons": "5.2.1",
    "@blueprintjs/popover2": "2.0.15",
    "@blueprintjs/select": "5.0.15",
```

**Comment by HitkoDev** [comment]
@adidahiya Your last release broke dependencies. Fix ASAP.

**Comment by warpdesign** [comment]
Damn it: this made me loose an hour trying to find out why I got this error :/

**Comment by allankikkas** [comment]
current packages do not install with npm due to workspace urls. clean slate, blank package.json file.

npm install @blueprintjs/core @blueprintjs/datetime2 @blueprintjs/popover2  react react-dom --save -E

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

**Comment by AnnoDomine** [comment]
Same problem on pnpm and npm.
Hope they fix this as soon as possible.

**Comment by adidahiya** [comment]
Sorry for the trouble here, looks like this was caused by a recent upgrade to Yarn v4 and its interactions with Lerna. I'll look into a fix ASAP.

**Comment by adidahiya** [comment]
Just published patch versions of all @blueprintjs libraries with fixed version ranges.

See: 
- (broken) [@blueprintjs/core@5.7.0](https://unpkg.com/browse/@blueprintjs/core@5.7.0/package.json)
- (fixed) [@blueprintjs/core@5.7.1](https://unpkg.com/browse/@blueprintjs/core@5.7.1/package.json)

**Comment by derekjobst** [comment]
Thanks!

**Comment by AnnoDomine** [comment]
Thank you so much.
