### ISSUE TITLE
Keep old documentation on blueprintjs.com/docs/

### ISSUE THREAD

**Issue by teaearlgraycold** [palantir/blueprint#656]
Currently it seems that there's no way to check the documentation for old versions of blueprint.

Ideally I'd like to see the "Releases" dropdown allow me to select the version I want to see documentation for.

This may necessitate splitting up the documentation for core/table/datetime.

**Comment by giladgray** [comment]
@teaearlgraycold sorry, we decided not to provide links to every single minor version of Blueprint 1.x. We will, however, host the latest minor version for each __major version__ (when we have more than one 😄 ). See #64 for original discussion.

You can easily access older versions of the docs site on GitHub by browsing through release tags and checking the `/docs/` directory in the root. For instance, here's the site from 1.2.0: https://github.com/palantir/blueprint/tree/release-1.2.0/docs.

**Comment by teaearlgraycold** [comment]
Alright, thanks!
