### ISSUE TITLE
Improve readability of minimal tags

### ISSUE THREAD

**Issue by pkwi** [palantir/blueprint#657]
Change text colour for minimal tags to improve contrast and readability.

**Light theme:**

**Current**

<img width="624" alt="screen shot 2017-02-09 at 7 36 29 pm" src="https://cloud.githubusercontent.com/assets/23030180/22800500/7c544f02-ef01-11e6-989f-5d1f5b5a982b.png">

**Proposal**

<img width="635" alt="screen shot 2017-02-09 at 7 38 34 pm" src="https://cloud.githubusercontent.com/assets/23030180/22800504/81d01d08-ef01-11e6-81ae-6523232d3313.png">

Default: no change
Primary: blue2 > blue1
Success: green2 > green1
Warning: orange2 > orange1
Danger: red2 > red1

**Dark Theme:**

**Current**

<img width="623" alt="screen shot 2017-02-09 at 7 40 03 pm" src="https://cloud.githubusercontent.com/assets/23030180/22800513/8a1d9576-ef01-11e6-8695-6bbd38faeffa.png">

**Proposal**

<img width="617" alt="screen shot 2017-02-09 at 7 41 48 pm" src="https://cloud.githubusercontent.com/assets/23030180/22800534/90f91514-ef01-11e6-933d-2491f4a2c049.png">

Default: no change
Primary: blue4 > blue5
Success: green4 > green5
Warning: orange4 > orange5
Danger: red4 > red5

**Comment by llorca** [comment]
This means changing the defaults in `$pt-intent-text-colors`. Colored text and colored icon next to each other will look even more different (2 shades difference vs 1 shade at the moment). We need better intent management in Sass!

**Comment by pkwi** [comment]
This is for minimal tags only. It doesn't mean we have to change the defaults. I'm sure there are ways to split these two.

**Comment by llorca** [comment]
No, this isn't actually about minimal tags. It's about the value of `$pt-intent-text-colors`/`$pt-dark-intent-text-colors` and will impact any component that's using intent text colors:
```
@each $intent, $color in $pt-intent-colors {
  &.pt-intent-#{$intent} {
    background-color: rgba($color, 0.2);
    color: map-get($pt-intent-text-colors, $intent);
     .pt-dark & {
      color: map-get($pt-dark-intent-text-colors, $intent);
    }
  }
}
```
