### ISSUE TITLE
how to remove elements's click blue border

### ISSUE THREAD

**Issue by duqingnian** [palantir/blueprint#6586]
#### Environment

- __Package version(s)__: 
- __Browser and OS versions__: 

#### Question
![border](https://github.com/palantir/blueprint/assets/2705589/3382fb93-2add-4959-b21e-6508cb64e478)
when i click every element , this blue border display. i want remove it, but i donot know how to remove it.
please help me , thanks a lot!

**Comment by adidahiya** [comment]
See the [Focus management](https://blueprintjs.com/docs/#core/accessibility.focus-management) section of the docs

![image](https://github.com/palantir/blueprint/assets/723999/1731dd00-6f33-4907-92f8-337cf9b56d86)
