### ISSUE TITLE
safeInvoke typings don't work with strict null checks

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#663]
`safeInvoke` is a useful utility function, however it's unusable with `strictNullChecks` enabled.
Since it's defined without `undefined` in mind, using it results in the following error:

```
Argument of type '((a: A) => void) | undefined' is not assignable to parameter of type '(arg1: A) => void'.
  Type 'undefined' is not assignable to type '(arg1: A) => void'.
```

This makes it completely unusable, since it expects a non-undefined function to call (rendering the method obsolete).

**Comment by JKillian** [comment]
@invliD this should fix things for you I believe: https://github.com/palantir/blueprint/pull/666/files

Give it a try though if you'd like first, I didn't have a chance to test it on a real use case with `strictNullChecks`
