### ISSUE TITLE
`MultiSelect` mutates incoming `tagInputProps` object

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#6645]
#### Environment

- __Package version(s)__: select@5.0.20
- __Operating System__: OSX
- __Browser name and version__: Chrome

#### Relevant code

https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/multi-select/multiSelect.tsx#L259C1-L264C14

Is there a reason why this prop is mutated?

**Comment by adidahiya** [comment]
Nope, that looks like an oversight. will fix
