### ISSUE TITLE
date range picker v3 (.rdp classes)

### ISSUE THREAD

**Issue by hey68you** [palantir/blueprint#6666]
#### Environment

@blueprintjs/datetime2": "^2.2.10,
Chrome Version 120.0.6099.234 (Official Build) (x86_64)
Macosx Sonoma Version 14.2.1 (23C71)

#### Question
[react-date-picker-with-blueprint.css.zip](https://github.com/palantir/blueprint/files/14024622/react-date-picker-with-blueprint.css.zip)

I guess this is a bug, but I'm not sure (maybe I'm doing something wrong?)

After selecting a start date and then hovering across the day cells they are not highlighting (changing to highlighting color).

Only if I manually add the attached .css file (with all the .rdp css classes from your example code doc-app.css)  does the hover background color work as expected

in my index.css I add the line
`@import "/src/assets/react-date-picker-with-blueprint.css";`
screenshot with manually added css
![image](https://github.com/palantir/blueprint/assets/31699161/bc05663f-0222-4b4e-9184-1c075dbc1b98)

I'm not even sure if the new date range picker is working to select a date range with mouse click and drag without that manually added .css file

**Comment by adidahiya** [comment]
@hey68you can you repro your issue in a code sandbox (linked in the issue template and the docs home page)?

You need to load `blueprint-datetime.css` and `blueprint-datetime2.css` for the "v3" components to display correctly. This is noted in the [docs](https://blueprintjs.com/docs/#datetime2).

**Comment by hey68you** [comment]
@adidahiya - thank you! 
I guess I didn't read the docs carefully enough: adding both of those .css files fixes the issue. 
I had only added the old one (not the `blueprint-datetime2.css`
