### ISSUE TITLE
Support custom Select filter component

### ISSUE THREAD

**Issue by viveleroi** [palantir/blueprint#6682]
We're using the `Select` component to replace select inputs in our forms. Since pressing a letter to jump to the first entry starting with that letter doesn't work from my tests, we're looking at using the filter functionality. 

However, we have our search form field that's customized to our specifications, and I don't see a way to provide a custom component for the filter portion of the select. We'd need support for this, as the default isn't sufficient for our needs and I can't replicate it via styling alone.

**Comment by invliD** [comment]
Could you clarify in what way the default search is not sufficient?

**Comment by viveleroi** [comment]
I needed the ability to add a custom component for the input because the default doesn't match our design or functionality guidelines.

However I personally no longer need this functionality because we wound up dropping the blueprint select library and made our own given our needs.
