### ISSUE TITLE
Enter key fails in multiple scenarios in select component

### ISSUE THREAD

**Issue by viveleroi** [palantir/blueprint#6714]
Using the Select component I've noticed multiple problems with the select:

- Pressing the enter key when the button has focus but the popover is not open opens it and then closes it as fast as the popover transition is complete
- Pressing the enter key when the popover is open has no effect, even when the arrow keys have been used to select an item

Clicking the menu works fine in both cases, so this is only an issue with the enter key. Pressing the down arrow when the popover is closed opens it just fine. So something is all wrong with the enter key logic.

I have no key handling logic so it's something internal to blueprint. I can't reproduce it in the website demo but I've stripped out our entire app and just put it into the base page and it still happens. The absolute only different is that we don't import your css. Clicking the button shows the menu fine, but hitting enter when it has focus opens the popover and then closes it.

#### Environment

- __Package version(s)__: core 5.9.1 and select 5.1.1
- __Operating System__: Windows 11
- __Browser name and version__:  Chrome 121.0.6167.184 (Official Build) (64-bit)

Even with the most minimal setup, this still happens:

```tsx
<Select<SelectInputOption>
  filterable={false}
  itemRenderer={option => <a key={option.value}>{option.text}</a>}
  items={options}>
  <button type='button'>click me</button>
</Select>
```

Looks like it's related to this line in the blueprint js:

```
onKeyDown: _this.withPopoverTargetPropsHandler("keydown", isOpen ? handleKeyDown : _this.handleTargetKeyDown)
```

When I comment that out, the menu stays open on Enter keydown.

If I leave that line but disable this setState OR preventDefault, the enter key works as expected:

```tsx
_this.handleTargetKeyDown = function(event) {
if (event.key === "ArrowUp" || event.key === "ArrowDown") {
  event.preventDefault();
  _this.setState({ isOpen: true });
} else if (utils_exports.isKeyboardClick(event)) {
  // _this.setState({ isOpen: true }); // <=== disabled this, enter key opens and closes menu just fine
  event.preventDefault(); // OR, added this
}
```

**Comment by invliD** [comment]
> The absolute only different is that we don't import your css.

Quite a bit of Blueprint's JS depends on the correct styles. Could you try adding the CSS temporarily to see if that fixes the issue?

**Comment by viveleroi** [comment]
That was probably the problem, then. However I no longer need this functionality because we wound up dropping the blueprint select library and made our own given our needs.
