### ISSUE TITLE
shouldDismissPopover should still work in MenuItems with onClick handler even when they have submenus

### ISSUE THREAD

**Issue by ab-pm** [palantir/blueprint#6725]
We are using a `<MenuItem>` with a submenu that also has a default action when you click directly on it. The submenu is usable only via hover. However, clicking on the upper menu item triggers the action but doesn't close the popover. This is [documented for `<MenuItem>`](https://blueprintjs.com/docs/#core/components/menu.menu-item):

> **`shouldDismissPopover`**:	`boolean = true`
> Whether an enabled item without a submenu should automatically close its parent popover when clicked.

I would argue that it should also dismiss the popover when the `<MenuItem>` has an `onClick` handler, despite having a submenu. I.e. going for "*an enabled item without a submenu or with an `onClick` action*".

To make it not unusable on touch surfaces, ideally a click on the submenu icon (`caret-right`) should still open the submenu and not fire the `onClick` handler. Not sure whether this is feasible though, and whether it makes sense at all or rather should be the responsibility of the `onClick` handler function to ignore the submenu icon.

For now we've worked around this issue by directly adding `<MenuItem className={Classes.POPOVER_DISMISS} …`, but I would prefer if this scenario was working out of the box with `shouldDismissPopover` defaulted to `true`.

**Comment by invliD** [comment]
This is not something we want to support. Having both an onClick and a submenu in the same menu item is an anti-pattern, as many people (accidentally or not) _click_ the item to open the submenu. While we're not actively prohibiting doing that, we also do not want to endorse that usage pattern.
