### ISSUE TITLE
Input box rendering on iOS browsers

### ISSUE THREAD

**Issue by allanjsx** [palantir/blueprint#675]
### Bug report

- __Package version(s)__: 1.8
- __Browser and OS versions__: iOS 10.2.1

#### Steps to reproduce

Launch this link using iOS browser (Safari or Chrome) http://blueprintjs.com/docs/#components.forms

#### Actual behavior

Input box boarder colors are missing. If website need to show input boxes on iOS device, it will have to switch to using a darker background as contrast.

![image](https://cloud.githubusercontent.com/assets/5211888/22866856/9838403e-f131-11e6-9250-dbc6052a1911.png)

#### Expected behavior

The input box style should be the same as how it looks on desktop browsers.

**Comment by allanjsx** [comment]
P.S. 

I know responsiveness is out of the current scope, but the component style should be compatible with different browsers.

Thanks.

**Comment by sfilargi** [comment]
Any workarounds?

**Comment by giladgray** [comment]
You are missing normalize.css. It is an external dependency listed in
package.json.

Add normalize.css before blueprint.css and you'll be good to go!

**Comment by sfilargi** [comment]
> You are missing normalize.css. It is an external dependency listed in package.json. Add normalize.css before blueprint.css and you'll be good to go!

Didn't make any difference for me

**Comment by giladgray** [comment]
ok good point, you're on the docs site so of course it has normalize.css. my bad.

honestly iOS support is lower priority than IE11 for the team, so we're not going to actively investigate this anytime soon. happy to accept PRs though! i'll bet it's an easy fix, just need to make a little `-webkit-something` tweak.

**Comment by sfilargi** [comment]
> honestly iOS support is lower priority than IE11 for the team, so we're not going to actively investigate this anytime soon. happy to accept PRs though!

Sure
