### ISSUE TITLE
FR: Handle styling for open popovers

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#681]
When popovers are open, particularly when they have `PopoverInteractionKind.CLICK_TARGET_ONLY` set, it's useful to see that the target is 'active' or 'clicked'.

**Comment by llorca** [comment]
I supposed the most straightforward way is to add support in a few of our components (buttons, icons...) for `.pt-popover-open`.

What does everybody think?

**Comment by giladgray** [comment]
does seem easiest to just add support for `.pt-popover-open .pt-button`. not sure what other components we could support? we already do [this exact thing for `Menu` submenus](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/menu/_submenu.scss#L70-L74)

**Comment by tgreenwatts** [comment]
`pt-icon` like in 
![feb-14-2017 11-07-51](https://cloud.githubusercontent.com/assets/24398123/22944541/dc0cf92e-f2a5-11e6-8ff1-1b752fd8de4e.gif)
(not the clearest gif) but often our popovers are opened via icons instead

**Comment by llorca** [comment]
That's tough because `pt-icon` doesn't have a `pt-active` concept like `pt-button`. Icon colors are often customized too... What you're showing is an icon with a color X, and with `pt-popover-open` we want the color to be darker(X). Tricky

**Comment by giladgray** [comment]
that `.pt-icon` is easy enough to style via `.pt-popover-icon`, and as @llorca says, we can't know what colors you're trying to achieve with it.
