### ISSUE TITLE
Upgrade to react-day-picker v5

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#688]
2 major releases came out recently.
https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md

**Comment by adidahiya** [comment]
Some more fixes in 5.1:

- https://github.com/gpbl/react-day-picker/issues/258
- https://github.com/gpbl/react-day-picker/issues/263

**Comment by giladgray** [comment]
gonna have to do this upgrade to remove React 15.5 prop-types warning #991
