### ISSUE TITLE
Table `Column` component doesn't respect className prop

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#690]
### Bug report

- __Package version(s)__: Blueprint table 1.6.0
- __Browser and OS versions__: Chrome 56 OSX 10.11.6

#### Steps to reproduce

1. Make a blueprint table with`Column` components that have a `className` prop set.

#### Actual behavior

Column headers don't get the class specified added in the rendered HTML.

#### Expected behavior

Column headers have the class specified added in the rendered HTML.

(Pretty sure this is a regression, this previously worked for us.)

**Comment by tgreenwatts** [comment]
@gscshoyru  ?

**Comment by samirbr** [comment]
Column [renderCell](https://github.com/palantir/blueprint/blob/master/packages/table/src/column.tsx#L51) calls [emptyCellRenderer](https://github.com/palantir/blueprint/blob/master/packages/table/src/cell/cell.tsx#L50).
```
export const emptyCellRenderer = () => <Cell />;
```
Column properties aren't passed to ```<Cell />```.

[bodyCellRenderer](https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L612) should returns
```
React.cloneElement(cell, { loading, ......columnProps } as ICellProps);
```
instead.

**Comment by JKillian** [comment]
I'm not so sure this was actually fixed. I think the idea here was that the class name provided to `Column` would apply to its header cell [here](https://github.com/palantir/blueprint/blob/32abe7978f48b3b51b3c961868c8244a902d5017/packages/table/src/headers/columnHeaderCell.tsx#L165). Right now afaict, the class name only gets applied to ever regular cell but not the header cell by default.

**Comment by tgreenwatts** [comment]
Looks like not fixed, so reopening

**Comment by tgreenwatts** [comment]
@jrafidi - icymi this is fixed now! Will be released Tuesday
