### ISSUE TITLE
Callouts don't have an API for supporting buttons

### ISSUE THREAD

**Issue by thisisalessandro** [palantir/blueprint#699]
I've seen a few callouts floating around (in Palantir) where people added a dismiss button to dismiss the callout (which is especially useful for "info" and warning callouts). Seems like a reasonable use case that should be supported.

**Comment by llorca** [comment]
That's fair, [tags](http://blueprintjs.com/docs/#components.tag) have a great implementation of a dismiss button (works for different sizes, whether the element is multiline or not...)

**Comment by giladgray** [comment]
What's the feature request here? 
There's nothing preventing you from putting a `.pt-button` in a `.pt-callout`.
We do not provide a `Callout` React component (only the CSS API) so there's nothing to "dismiss".

**Comment by thisisalessandro** [comment]
@giladgray @llorca What do you think about making callouts a component? We use them as permanent or contextual toasts, so I think the options should be more or less the same.

**Comment by llorca** [comment]
The ability of having a button to hide said callout doesn't warrant a component IMO, that's not enough functionality to justify it

**Comment by thisisalessandro** [comment]
If callouts are considered permanent/contextual toasts, shouldn't they support the same use cases? (dismissing + action)

**Comment by giladgray** [comment]
`Toast` supports nothing--it's just an empty container. `Toaster` is the component that provides all the dismiss functionality. I can't imagine an analog for `Callout` as they appear one-off, and typically reside in the document flow. 

Implementing an X button is practically trivial in React. I don't think we need to provide a new component for this.

**Comment by giladgray** [comment]
closing as there's no clear action here
