### ISSUE TITLE
[Popover] Range Slider within Popover does not render correctly

### ISSUE THREAD

**Issue by kendraknittel** [palantir/blueprint#701]
#### Steps to reproduce

With the following code, the range slider that is not inside the popover turns out fine; the range slider that is inside the popover renders incorrectly.

```ts
private render() {
    return (
      <div className="container">
        <Popover
          popoverClassName="slider-popover"
          content={this.renderSlider()}
          position={Position.BOTTOM_RIGHT}
        >
          HELLO PRESS ME
        </Popover>
        <div
          className="slider-container"
        >
          <RangeSlider
            max={100}
            min={0}
            value={[0, 100]}
            onChange={() => {}}
            stepSize={1}
            labelStepSize={25}
            showTrackFill={false}
          />
        </div>
      </TabPanel>
    )
  }

  private renderSlider = () => {
    return (
      <div
        className="slider-container"
      >
        <RangeSlider
          max={100}
          min={0}
          value={[0, 100]}
          onChange={() => {}}
          stepSize={1}
          labelStepSize={25}
          showTrackFill={false}
        />
      </div>
    );
  }
```

with .less file:
```less
.slider-container {
  padding: 25px;
  padding-bottom: 15px;
  width: 385px;
}

.slider-popover {
  width: 385px;
}
```

#### Actual behavior

Component does not render correctly until it is interacted with. If the component has the same css styling but is not inside a popover, it will render fine. Resets to this broken look every time a popover is re-opened.
![image](https://cloud.githubusercontent.com/assets/14883799/23047975/049708ee-f481-11e6-81dc-06727c026ec4.png)

#### Expected behavior

Component should render correctly before any interaction, as soon as the popover is opened.
![image](https://cloud.githubusercontent.com/assets/14883799/23047988/1513d4c2-f481-11e6-8ed2-c14de9846b53.png)

#### Temporary Solution

Figured out that this is tied to the transition of the popover from closed to open. The slider's position is computed based on the popover size which changes as the popover opens. When the popover finally opens, it doesn't get recomputed because the size is a `el.getClientHeight()` call vs a prop. - needs to force a re-render once the animation is done.

Right now our workaround is `setTimeout(() => this.setState({popoverDidOpen: true}), 150)`

**Comment by giladgray** [comment]
good news! this seems to be resolved with popper.js / #1202

**Comment by dougaraujos** [comment]
Hi, this problem also occurs inside Collapse component. Any fix?
