### ISSUE TITLE
EditableText cannot receive other event handlers (eg. onContextMenu)

### ISSUE THREAD

**Issue by ecwyne** [palantir/blueprint#702]
https://github.com/palantir/blueprint/blob/master/packages/core/src/components/editable-text/editableText.tsx#L276-L291

As it is written, it is not possible to pass in other event handlers. I would like to alter the behavior of onContextMenu within an EditableText

**Comment by giladgray** [comment]
moving to 2.x where we will consider props spreading more whole-heartedly across the codebase.

**Comment by ecwyne** [comment]
Thanks @giladgray 

Let me know if there is any way I can help!
