### ISSUE TITLE
[Numeric Input] Fix two failing cursor-placement unit tests in Firefox

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#703]
### Bug report

- __Package version(s)__: v1.8.0
- __Browser and OS versions__: Firefox 51.0.1 on OS X 10.11.6

#### Steps to reproduce

1. Run `karma-unit-core` from terminal.
2. Go to `localhost:9876/debug.html` in Firefox.
3. Observe test results for `<NumericInput>`

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/443450/23085649/b2ac7b0c-f51d-11e6-8e0f-7e7061c32fe2.png)

#### Expected behavior

All tests pass in all browsers.

_(Note: all tests currently pass in Safari and Chrome and Phantom)_

**Comment by cmslewis** [comment]
P3 because the failing tests aren't build-breaking, and they relate to behavior that isn't that important. Maybe a better move is to just disable those tests for now?

**Comment by giladgray** [comment]
No need to disable the tests since we don't run them in FF during CI build (they're not build-breaking, as you said). Seems more useful to have them enabled but failing in FF, which represents actual behavior.
