### ISSUE TITLE
Showing multiple toasts in quick succession flows over top of screen

### ISSUE THREAD

**Issue by ashleymercer** [palantir/blueprint#7034]
#### Environment

- __Package version(s)__: @blueprintjs/core 5.13.1
- __Operating System__: Windows Server 2016
- __Browser name and version__: Chrome 130.0.6723.70

#### Code Sandbox

https://codesandbox.io/p/sandbox/jovial-galois-x8727d

Relevant code is in `src/App.tsx` - if you increase the `waitInterval` to one second then the toasts animate smoothly, but if we don't wait (`waitInterval = 0`) then they get stuck.

#### Steps to reproduce

1. create an `<OverlayToaster>`
2. send multiple toast messages to it in quick succession

#### Actual behavior

Animation seems to stop early and some toast messages flow over the top of the screen.

#### Expected behavior

All toast should finish animating correctly into the correct position.

#### Possible solution

This seems to be some timing issue: if we insert an arbitrary wait between sending toasts then they animate correctly.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Lonli-Lokli** [comment]
same happens with my project, unfortunately we cannot control error toasters

**Comment by Lonli-Lokli** [comment]
@jscheiny it still happens with my app
