### ISSUE TITLE
Cannot use loading and skeleton classes on custom content within table

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#706]
## Bug report

- Package versions: `Table 1.6.0`
- Browser and OS versions: Only appears to result in CSS bugs in Chrome 56. Renders properly in Safari. Using OS X 10.11.6.

#### Steps to reproduce

1. Use the `pt-loading` class on some element `x` within BP table (e.g. header content).
2. Use the `pt-skeleton` class on some child element of `x`.

#### Actual behavior

Note that the animation from the skeletons in the custom header content does not go away even after the text has loaded and we are no longer applying the `pt-skeleton` class. The "highlight" finally goes away once we interact with the page somehow (e.g. clicking, resizing, etc.).
![wlvli](https://cloud.githubusercontent.com/assets/3681045/23134104/8c515680-f761-11e6-8657-5c50ced9be64.gif)

#### Expected behavior

There should be no lingering animation effects. I believe this is the relevant piece of CSS in BP Table that's resulting in this Chrome bug: https://github.com/palantir/blueprint/blob/9077435f3d90cf4abc37714ef914fdd2351396df/packages/table/src/table.scss#L35

#### Workaround

Not using this parent-child combination of `pt-loading` and `pt-skeleton` appears to "resolve" the issue.

#### Why is this happening?

It's potentially due to this [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=666710). Try viewing the demo in the issue in Chrome, Firefox, and Safari.

**Comment by tgreenwatts** [comment]
@cmslewis is this still an issue?

**Comment by cmslewis** [comment]
I don't know. Let me play today.

**Comment by cmslewis** [comment]
Will re-open for the moment.

**Comment by michael-yx-wu** [comment]
I've updated the link to `table.scss` to the proper commit
