### ISSUE TITLE
`map-marker` icon is not horizontally centered

### ISSUE THREAD

**Issue by benrucker** [palantir/blueprint#7064]
The `map-marker` icon is not centered within the SVG viewport. This seems to only be a problem with the default icon size of 16px, because I don't see this issue on the [Icons List page](https://blueprintjs.com/docs/#icons/icons-list) which uses 20px icons. This is causing problems for a design I am trying to implement that assumes that the map marker icon is properly centered.

#### Environment

- __Package version(s)__: 5.14.0
- __Operating System__: MacOS
- __Browser name and version__: Chrome v130.0.6723.117 

#### Code Sandbox

https://codesandbox.io/p/devbox/distracted-http-5k3hg6 

#### Actual behavior
Icon is not centered
<img width="400" alt="image" src="https://github.com/user-attachments/assets/03710d00-9bd1-4ee5-b98b-8118deb45163">

#### Expected behavior
Icon is centered
<img width="500" alt="image" src="https://github.com/user-attachments/assets/ab5f968e-6f3a-4c40-9e2b-cb898420a4e5">

#### Possible solution

Edit the SVG so that the icon is centered within the SVG viewport.

**Comment by ggdouglas** [comment]
Thanks for the flag! This is fixed by #7066
