### ISSUE TITLE
active prop on Button

### ISSUE THREAD

**Issue by DrewDennison** [palantir/blueprint#710]
Hello,

What's the general thought around an `active` prop on a `Button`? Currently I'm using `classnames` to set `<Button className={cx({'pt-active': var})}>` and it would be nice to just be able to use `<Button active={var}>`

Totally understand if it doesn't make sense to set the button's active state via a prop.

Thanks! 
Drew

**Comment by giladgray** [comment]
I think that makes sense! How do you feel about contributing a PR?

**Comment by DrewDennison** [comment]
Sweet! Great, I'll work on a PR
