### ISSUE TITLE
Toast action colors have low contrast

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#713]
### Bug report

- __Package version__: 1.9.0
- __Browser and OS versions__: Mac OS X, Chrome Version 58.0.3014.0 canary (64-bit)

#### Steps to reproduce

1. Open a toast with an intent and an action

#### Actual behavior

![2017-02-21 17 11 34](https://cloud.githubusercontent.com/assets/723999/23187456/d78ee76e-f858-11e6-8bed-0e38439a6652.gif)

#### Expected behavior

Better text contrast in action text

**Comment by llorca** [comment]
@adidahiya Chrome issue? Everything looks fine on latest `master`

**Comment by pkwi** [comment]
I can reproduce this bug on Chrome 58.0.3021.0 (Developer Build) (64-bit) but everything is fine on 56.0.2924.87 (64-bit) version.

**Comment by adidahiya** [comment]
Alright this is probably a Chrome bug related to CSS transitions then. I've seen similar things in past canary builds. Closing for now; we can re-open if we see it with official v58
