### ISSUE TITLE
Button, ButtonGroup, Select are not aligned vertically

### ISSUE THREAD

**Issue by lijiaqigreat** [palantir/blueprint#716]
Different widget has different value for vertical-align. For example, ButtonGroup has "baseline" by chrome default, Button has "middle", Select has "middle"
This is a style that I think is undesirable. Please ignore the dropdown arrow in example. I can't get icon to work in jsfiddle

-@blueprint/core@1.9.0
-Linux, Latest Chrome as well as Firefox

#### Steps to reproduce
https://jsfiddle.net/f43s95rf/

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/2196866/23202877/193283c4-f8ae-11e6-998f-83c53bcaf6ed.png)

#### Expected behavior

![image](https://cloud.githubusercontent.com/assets/2196866/23202993/9a486b90-f8ae-11e6-8292-6039f53f92c2.png)

**Comment by llorca** [comment]
What is the ideal scenario? Everything `baseline` or everything `middle`?

**Comment by lijiaqigreat** [comment]
@llorca I'd say everything should be middle. Since if widgets of different size are put together, it usually looks best to align middle. But I don't think have the experience or knowledge to have a well-thought suggest.

**Comment by giladgray** [comment]
@lijiaqigreat have you tried making the row containing these elements `display: flex`? that should sort out your layout challenges real quick via `align-items`.

**Comment by lijiaqigreat** [comment]
@giladgray it worked! thanks. Feel free to close this ticket, or change them to middle anyway. Since it might be a bug in other scenarios.

**Comment by adidahiya** [comment]
+1, it would be nice to fix this for non-flex scenarios too
