### ISSUE TITLE
Use style overflow: auto in certain components in JS Table to deliver better UI when mouse is attached

### ISSUE THREAD

**Issue by blakegong** [palantir/blueprint#720]
Currently, since *TruncatedFormat* and *Table* components are using `overflow: scroll`, although they display beautifully with no mouse attached:

![screen shot 2017-02-23 at 6 41 48 pm](https://cloud.githubusercontent.com/assets/3624869/23255891/32d189ec-f9f8-11e6-8b3d-39828cb3139d.png)

It becomes somewhat unnecessary and imperfect when you plug in the mouse. The scroll bars for X and Y are always shown in this case, even for a not overflowed component:

![screen shot 2017-02-23 at 6 41 08 pm](https://cloud.githubusercontent.com/assets/3624869/23255989/a27f3e9c-f9f8-11e6-96e3-9e9b9d21590d.png)

By using `overflow: auto` on those components, the visual effect of those components are always displayed beautifully whether mouse is attached or not.

May I know is there any concern for using `overflow: scroll`? If not, I can go ahead and submit a PR for this :D

**Comment by llorca** [comment]
@themadcreator any particular reason why we used `overflow: scroll` here?

**Comment by blakegong** [comment]
Actually [this line](https://github.com/palantir/blueprint/blob/master/packages/table/src/table.scss#L113) should be changed to `overflow: auto` also. If you pay closer attention to the differences between the two pictures in the original post... And there might be more unnecessary `overflow: scroll` in this project. Should I raise another issue for that?

**Comment by llorca** [comment]
@blakegong Yes, please file an issue with the other instances that need to be changed
