### ISSUE TITLE
Add an api to allow `Hotkeys` component to change the `globalHotkeysGroup` text

### ISSUE THREAD

**Issue by ysmood** [palantir/blueprint#721]
If you want to display another language other than English, it will be a problem.

And of course other components that have fixed text inside should also expose an api to allow alteration.

**Comment by llorca** [comment]
@ysmood I was just looking at that, there's a public method you can import and use to customize `globalHotkeysGroup`:
```
import { setHotkeysDialogProps } from "@blueprintjs/core";

// somewhere in your file
setHotkeysDialogProps({ globalHotkeysGroup: "your custom string" });
```
Does it solve your issue?

**Comment by ysmood** [comment]
Sure, it does. A little bit hack though.

**Comment by llorca** [comment]
Yeah it's not super standard but that's how the API is structured now. We will revisit in the future
