### ISSUE TITLE
table does not work with react-hot-loader

### ISSUE THREAD

**Issue by brunesto** [palantir/blueprint#723]
### Bug report

- __Package version(s)__:  @blueprintjs/table@1.6.0
- __Browser and OS versions__:	54.0.2840.100

#### Steps to reproduce
running app with HMR  react-hot-loader@3.0.0-beta.6

#### Actual behavior

Crash because of check in table.js:265
``  var isColumn = cType.prototype === column_1.Column.prototype || column_1.Column.prototype.isPrototypeOf(cType);``
``                if (!isColumn) {``
``                   throw new Error(ERROR_MESSAGE); // Children of Table must be Columns``

the check fails, because react-hot-loader will proxy all React Components

Please could you remove this check (or make it optional) to support react-hot-loader? I seems to me anyway that this line is the only place where this kind of prototype check occurs in blueprintjs

Thanks

**Comment by adidahiya** [comment]
yeah, I've been thinking we should remove those checks since they don't really do anything useful in practice. we could try switching it to a `console.warn` at least, since it is almost always non-blocking (the table will still work)

**Comment by mmoutenot** [comment]
Hi all, this seems to [throw again](https://github.com/palantir/blueprint/blob/develop/packages/table/src/table.tsx#L892) via https://github.com/palantir/blueprint/pull/1587, and per https://github.com/gaearon/react-hot-loader/issues/304 it's breaking whenever I try and render the Table component.

I always render my columns wrapped in `<Column/>` but the prototype seems to be `<PureComponent/>`. Has anyone else run into this?

**Comment by giladgray** [comment]
@mmoutenot this might be fixed by #2099? see #2095

**Comment by mmoutenot** [comment]
@giladgray looks like it! I'll test as soon as it's merged.
