### ISSUE TITLE
Slider label shows floating point rounding errors

### ISSUE THREAD

**Issue by as-com** [palantir/blueprint#725]
### Bug report

- __Package version(s)__: 1.9.0 
- __Browser and OS versions__: Firefox Developer Edition 53.0a2 (also happened in other browsers) 

#### Steps to reproduce

1. 
```
<Slider 
  onChange={(value) => { this.setState({ value }) }} 
  value={this.state.value}
  stepSize={0.1}
/>
```
(http://www.webpackbin.com/Ek8qyKYFG)

2. Drag slider around

#### Actual behavior

![slider-fp](https://cloud.githubusercontent.com/assets/3819625/23319122/592a056e-faa3-11e6-8a87-1e2720ac48f3.gif)

#### Expected behavior
Slider label displays expected step values.

Perhaps this could be fixed by rounding to the number of significant digits given in `stepSize`.

**Comment by giladgray** [comment]
this is easily handled by a custom `renderLabel`, but is not supported out-of-the-box currently.

```jsx
<Slider renderLabel={(value) => value.toFixed(2)}` />
```

**Comment by giladgray** [comment]
when using fractional (<1) steps, you pretty much have to do the above code.

we'd also happily accept a PR to add a `precision` prop.
