### ISSUE TITLE
searchbox styling in safari

### ISSUE THREAD

**Issue by Evanion** [palantir/blueprint#735]
Some times the searchbox stylign breaks in Safari. I don't know if there is styling missing.. or if it doesn't get loaded .. but I have also noted that the `::-webkit-search-cancel-button` is visible and black.

You can see it in action here: https://saints-gaming.com

### Bug report

- __Package version(s)__: 1.9.0
- __Browser and OS versions__: macOS 10.12.3 - Safari 10.0.3

#### Steps to reproduce

add a navbar with a searchfield

#### Actual behavior
The searchbox doesn't render the same way as in chrome etc.
the box is white (have pt-dark globally) and have the incorrect text-size and height.

#### Expected behavior
same styling as in chrome

#### Solution
Add `-webkit-appearance: none;`to .pt-input class

**Comment by llorca** [comment]
If you change to `type="text"`, it fixes it somehow. We use `type="search"` for [our search input](http://blueprintjs.com/docs/) and somehow there's no problem

**Comment by giladgray** [comment]
@Evanion are you including `normalize.css` in your application? The exact same markup is used on our docs site with no problems, which suggests your app is missing a piece.

**Comment by giladgray** [comment]
@Evanion you are indeed missing normalize.css, which includes styles for this exact case: https://github.com/necolas/normalize.css/blob/master/normalize.css#L393-L400.

Add that stylesheet to your page and you're good. Easiest way: `<link href="https://unpkg.com/normalize.css@5.0.0" rel="stylesheet" />`.
