### ISSUE TITLE
Removing nodes from Tree broken

### ISSUE THREAD

**Issue by JKillian** [palantir/blueprint#741]
My bad on this one 😞 

If a node is removed from a `Tree`, [`nodeData` here](https://github.com/palantir/blueprint/blob/47e8b61dd7f7be491859c24312fb188a13a8eccf/packages/core/src/components/tree/tree.tsx#L126) will be undefined and an error will get thrown for trying to access `id`.

I probably won't have time to fix this today if it's critical, but will definitely make time tomorrow.

**Comment by giladgray** [comment]
@JKillian fix thyself on the morrow, good lad!
