### ISSUE TITLE
Table has blurry text

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#742]
![image](https://cloud.githubusercontent.com/assets/24398123/23382708/2752c768-fcf8-11e6-8ae7-05e97469af86.png)

EDIT: Here's a better snapshot of how egregious this bug is:
![image](https://cloud.githubusercontent.com/assets/443450/23973651/50a0f29a-0994-11e7-9587-8eb3ccdea437.png)

Possibly related to performance issues

Seen on Chrome on Mac & on Chrome on Windows, not on IE Edge

**Comment by llorca** [comment]
Poking with `will-change` in the inspector fixes it

**Comment by blakegong** [comment]
Hi @llorca, it is not working after changing `will-change` to all values possible.

The `Table` in my case is displayed in a `Dialog` which only shows up when user clicks a button. It looks like the `Table` is rendered for a much smaller width and height, like it is picking up width and height values during the popup effect of the animation.

Same as @tgreenwatts as it only appears on Chrome not Safari. And in my case, only Chrome on external monitors have this problem, internal monitor works fine. Tested on Mac with both Chrome and Chrome Canary.

**Comment by tgreenwatts** [comment]
Thinking about it more, I've only seen this when the table is in a dialog

**Comment by cmslewis** [comment]
Relevant YouTube video about `will-change`: https://www.youtube.com/watch?time_continue=87&v=iSvUlSpIbNk

**Comment by cmslewis** [comment]
Removing `will-change: transform` from `bp-table-body-scroll-client` and `bp-table-container` (in the inspector) fixes the issue for me.

**Comment by blakegong** [comment]
Thanks Chris. Works like a charm! Didn't notice the second `will-change` on the outside `bp-table-container`.

**Comment by cmslewis** [comment]
@giladgray @llorca @themadcreator Is the preferred solution here to remove `will-change` for a `Table` inside a `Popover`, or is the solution to remove `will-change` on `Table` in general?

**Comment by blakegong** [comment]
@cmslewis Personally I only encountered this issue when using `Table` inside a `Dialog`, thus would prefer to remove `will-change` on `pt-dialog pt-table-container` condition as a workaround. But if it is a more general issue of course it is up to you guys to decide :)

**Comment by llorca** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

`will-change` is here for perf reasons (trying to hit 60 FPS everywhere), but we're probably misusing it. At this point, I'd be happy to remove it for now to fix this issue, and then properly investigate perf in general (https://github.com/palantir/blueprint/issues/390)
