### ISSUE TITLE
Component request: DateTimeInput

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#748]
related to #523

**Comment by llorca** [comment]
+1, we need the ability to turn on/off the time picking piece in both date picker and date range picker

**Comment by brsanthu** [comment]
Also we need the ability to request for explicit way for user to indicate that they are done with selection. This is helpful when datetime is used with some other input controls in controlled mode.

**Comment by adidahiya** [comment]
> Also we need the ability to request for explicit way for user to indicate that they are done with selection.

@brsanthu depending on your use case, you might just want to build a DateTimeInput yourself and get full control over the `input`, `Popover`, `DatePicker`, and `TimePicker` interactions. This is all currently doable, it just requires some glue code. No guarantees that the proposed `DateTimeInput` will exactly meet your needs, since it's meant to be a convenience component composed of other smaller atomic components.

**Comment by llorca** [comment]
Being "done with selection" depends a lot on your app and your UI context. I don't think there's one right solution that Blueprint should provide, instead you can achieve whatever behavior is best on your own with controlled mode

**Comment by brsanthu** [comment]
@adidahiya and @llorca thank you. Will try out and update how it goes.

**Comment by michael-yx-wu** [comment]
are there plans to support timezone selection in the `DateTimeInput`?

**Comment by adidahiya** [comment]
@michael-yx-wu we don't have any timezone components right now. filed #890
