### ISSUE TITLE
Support `pt-fill` in new components

### ISSUE THREAD

**Issue by leebyp** [palantir/blueprint#751]
- [ ] DateInput
- [x] NumericInput
- [x] file upload

**Comment by llorca** [comment]
I'll take a look at it this week

**Comment by orecus** [comment]
Same issue with the `<DateInput />` component, would be great if `pt-fill` was supported on all types of input/form -controls/groups.

**Comment by neevany** [comment]
please consider `<DateRangeInput/>` too.

**Comment by llorca** [comment]
@giladgray date inputs and date range inputs are wrapped around a pt-popover-target. That target needs to be width 100% in order for `.pt-fill` to work, problem is that it's a parent of the control group/input group. Do you see any nice way of supporting `.pt-fill` for date inputs and date range inputs before we get to https://github.com/palantir/blueprint/issues/724?

**Comment by cetra3** [comment]
What's the update on this particular request? I've managed to work around it by:

* Adding width: 100% on `pt-popover-target`
* Adding `pt-fill` to the `inputProps` of the DateTime component

**Comment by cmslewis** [comment]
@cetra3 we just haven't prioritized this lately given our limited resources and other concerns. We'd welcome a contribution if you'd like to open a PR!

**Comment by llorca** [comment]
@cetra3 no update for `DateInput` yet because of `.pt-popover-target`. Your workaround is appropriate but won't work for us since not all popover targets should fill their parent by default.
Look out for updates on https://github.com/palantir/blueprint/issues/724

**Comment by cetra3** [comment]
Thanks for the responses.  Yes, I agree, the `pt-popover-target` change wouldn't be suitable in a general sense, hence the workaround.  

If the plan is to refactor the popover as in #724 I think I can hold out until that is solved.
