### ISSUE TITLE
Skeleton loading contrast issues

### ISSUE THREAD

**Issue by sonovawolf** [palantir/blueprint#752]
From Saad (can't find your account if you have any :( ):
>at the risk of being a broken record: i'm happy for us to work out some alternative / more sophisticated thing, but at bottom, i'm just asking for the visual appearance of the skeleton to make it (much) more obvious that something is happening.

**Comment by llorca** [comment]
Could maybe bump a shade in the light theme! Dark theme seems fine to me, what do you think?

**Comment by pkwi** [comment]
+1 for the contrast change. 

@thisisalessandro @llorca should probably run a quick test on that old screen I was using.

**Comment by llorca** [comment]
@thisisalessandro @pkwi can one of you look at that and tell me what exactly needs change? I can then go update the code

**Comment by michael-yx-wu** [comment]
I remember trying to nail down the colors with @pkwi and @llorca a few months ago. We decided on a single set colors with some transparency so we wouldn't have to choose different colors for light and dark theme. Once you decide which colors you like for light / dark and whether we want to actually use to different color ranges, let me know and I'd be happy to fix
