### ISSUE TITLE
Remove separators between buttons in minimal button groups

### ISSUE THREAD

**Issue by thisisalessandro** [palantir/blueprint#754]
Separators are used between each minimal button in a button group, and thus cannot be used to separate minimal button groups.

**Comment by llorca** [comment]
Even better, a way to show or hide individual separators within a button group, e.g. a single button group with blocks of related buttons separated by a divider

**Comment by giladgray** [comment]
`.pt-divider`

**Comment by adidahiya** [comment]
@llorca Is this still relevant for 2.0?

**Comment by llorca** [comment]
pretty sure yes, it's a visual break. I think GG is on it, if not I can look at it later this week or next

**Comment by giladgray** [comment]
Fixed in #2098
