### ISSUE TITLE
[Toast] Really long strings in toast messages break layout

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#762]
### Bug report

- __Package version(s)__: 1.10.0
- __Browser and OS versions__: Chrome/OSX

#### Steps to reproduce

Use a really long string without any whitespace in the body of a toast mesasge

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/723999/23530349/4a46e4ba-ff6f-11e6-954e-9d6a9b499207.png)

#### Expected behavior

Not 100% sure... maybe we can change some whitespace or line breaking CSS to make this work

**Comment by michael-yx-wu** [comment]
would `word-break: break-all; white-space: break-word` be enough to forcibly break long words and wrap normal words?
