### ISSUE TITLE
Max width and whitespace styles on TruncatedPopover

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#763]
TruncatedPopovers can go off the screen because there is no max width 

@michael-yx-wu suggested

```
max-width: <something that will fit on most screens>
white-space: wrap
```

**Comment by michael-yx-wu** [comment]
This seems related to #762

**Comment by gscshoyru** [comment]
@michael-yx-wu @tgreenwatts this appears to already be implemented -- the table popover already has a set max-width -- https://github.com/palantir/blueprint/blob/master/packages/table/src/cell/formats/_formats.scss#L53 -- and whitespace is configurable -- by default it is set to "pre" but can be set to "normal" (i.e. wrap as normal) with a configuration option: https://github.com/palantir/blueprint/blob/master/packages/table/src/cell/formats/truncatedFormat.tsx#L32 . Is there anything further that should be done here? What am I missing?

**Comment by tgreenwatts** [comment]
Original discussion: https://pl.ntr/er

**Comment by tgreenwatts** [comment]
Not 100% sure, I think the ask is to make a smaller max-width then - 600px is a lot I think - and add `white-space: wrap` option which it doesn't sound like we have today

**Comment by gscshoyru** [comment]
There's no such thing as `white-space: wrap` . See https://developer.mozilla.org/en-US/docs/Web/CSS/white-space . `normal` is what you want, and what we already have an option for. 

600px is pretty small, honestly -- even extremely old screens are at least 800px wide. Most these days are much much larger. We can make it smaller, but at a certain point limiting the max width limits readability as well.

**Comment by tgreenwatts** [comment]
Alright well let's wait for @michael-yx-wu then, it's been too long for me to remember

**Comment by michael-yx-wu** [comment]
600px is about half the screen size of a 13in laptop screen. When the popover is that large, it can't fit on the screen. I think we have two options:

- Don't support people using this component on windows 600px wide or less
- Dynamically adjust the max width of the popover to be some percentage of the window size (because it seems it's not one size fits all)

**Comment by gscshoyru** [comment]
I'm not sure how you're getting from "half the screen size" to "can't fit on the screen", but ok. 

There aren't easy ways to do either of the things you list here. And the popover should adjust its size automatically so it always stays on the screen if you activate the word wrapping feature -- can you try that first and see if the max width change is needed still?

**Comment by llorca** [comment]
Even with a very large screen, we shouldn't go above ~700px -- long lines makes readability hard. Since we're already setting `max-width`, it seems like the action here is to change the `white-space` defaults to `normal` in order for text to wrap on multiple lines. (Why does it default to `pre` in the first place? What problem does `pre` solve exactly?)

This, plus `useSmartPositioning={true}` on the popover should solve this issue. I noticed `useSmartPositioning` is [valueless](https://github.com/palantir/blueprint/blob/master/packages/table/src/cell/formats/truncatedFormat.tsx#L118), is it equivalent to `true`?

**Comment by gscshoyru** [comment]
`pre` means pre-formatted -- in other words, obey the whitespace and newlines already present in the string of text, which is actually pretty unusual for html to do. I do agree that it's a rather... weird default, but given that it _is_ the default and that we already have an option to change it, swapping the default to go the other way would probably break other people's code that expected the default to work as it currently does. If you all are ok with this, I can just swap the default, though, 

Checking the rendered javascript, `useSmartPositioning` is in fact set to true. That is a really strange and confusing sytnax there, though, I'd much rather be explicit about it.

**Comment by llorca** [comment]
I do think it's worth changing the default. Seems more useful for `pre` to be opt-in than opt-out (I've only seen once instance or `pre` being useful: cells containing formatted JSON)

**Comment by adidahiya** [comment]
+1 for changing the default white-space and accepting the small break

> That is a really strange and confusing sytnax there, though, I'd much rather be explicit about it.

it's meant to mirror HTML attributes, the spec for which is awkward for whatever legacy reasons. lucky for you the latest tslint-react enforces being verbose here https://github.com/palantir/tslint-react/releases/tag/2.5.0

**Comment by gscshoyru** [comment]
I agree that that _should_ be default, but am just worried about introducing a backcompat break. That said, you're probably right that almost everyone is already setting it themselves since the pre-formatted case is a rarity, so I'll swap the default behavior, but we should keep an eye on this.
