### ISSUE TITLE
FR: Overflow Ellipsis component

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/blueprint#765]
It would be nice to have a component that added the "pt-text-overflow-ellipsis" *and* a title attribute on hover. I think the overhead of having to do both things (and not a component that does both for you) actually stops devs from doing it. Cases where this could be used are numerous.

**Comment by ryanmcnamara** [comment]
Going to take a shot at this, hopefully will have something up today

**Comment by giladgray** [comment]
@ryanmcnamara what's wrong with simply putting `.pt-text-overflow-ellipsis` and a `title` attribute _always_ if you know it _might_ be long? much simpler than detecting overflow and conditionally adding attribute.

**Comment by ryanmcnamara** [comment]
It's definitely simpler, and there's nothing wrong with it, but detecting the overflow (in a component) is very easy to do and I think worth it. To a user, having a title tooltip on content for no reason is a little strange (at least I think so). 

It could also be a simple ER that we add on top of the component.

**Comment by llorca** [comment]
Note that the `title` tooltip only shows up after hovering for a few seconds. I doubt a user would hover a few seconds over a text that's not truncated (even then, it's not a problem), that's why I kinda like the simplicity of Gilad's proposal

**Comment by michael-yx-wu** [comment]
Showing a tooltip in some cases _may_ be more consistent with the application's styles, so I understand why @ryanmcnamara is proposing this FR. That being said, I don't think BP is the right place for this component since this applications may differ here

**Comment by llorca** [comment]
My view is that such a component is generic enough to live in Blueprint, I'm just wondering if it's overkill or not

**Comment by tgreenwatts** [comment]
For SA, Ryan already has this in `compass-components`, so we're taking a feature that the Navigation team uses and considering moving it into Blueprint
