### ISSUE TITLE
Popover retriggers after being closed

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#771]
### Bug report

- __Package version(s)__: 1.10.0
- __Browser and OS versions__: macOS, Chrome 56
- Related to 920 internal?

#### Steps to reproduce

1. Select an end date in the date range input and move your mouse right after

#### Actual behavior

The popover is dismissed but since the mouse is moving, it retriggers.

![bug](https://cloud.githubusercontent.com/assets/199754/23571976/f98bb02a-0020-11e7-8743-d38a450ac720.gif)

#### Expected behavior

The popover closes completely.

#### Additional notes

Somehow this only happens in the date range input. Date input is fine.

**Comment by cmslewis** [comment]
I have a solid hunch why this is happening. Investigating now.
