### ISSUE TITLE
Context Menu in Dark Theme

### ISSUE THREAD

**Issue by veenedu** [palantir/blueprint#776]
'Content Menu' in 'Dark theme' is White however popups are dark. Check below images.
Is this expected behaviour or a bug?  I was expecting Context menu to be dark in dark theme like popovers.

Same can be reproduced by going to docs page
http://blueprintjs.com/docs/#components.popover
and change theme to dark from top

![screen shot 2017-03-04 at 3 42 03 pm](https://cloud.githubusercontent.com/assets/13888291/23577939/96e648be-00f1-11e7-951c-71f03cdb3e11.png)

![screen shot 2017-03-04 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/13888291/23577943/9d33d132-00f1-11e7-8383-8c90de95bb6a.png)

**Comment by opavader** [comment]
happens with popovers as well.
![b](https://cloud.githubusercontent.com/assets/14859766/24026712/1dac462c-0ae9-11e7-8b40-d594bf01747a.jpg)
