### ISSUE TITLE
Table ResizeHandle isotest doesn't run in CI

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#781]
Consistently seeing this test pending:

```
[23:57:09] Starting 'isotest-table'...


  Table isomorphic rendering
    ✓ <Cell>
    ✓ <EditableCell>
    ✓ <JSONFormat>
    ✓ <TruncatedFormat>
    ✓ <Draggable>
    ✓ <CopyCellsMenuItem>
    - <ResizeHandle>
    ✓ <DragSelectable>
    ✓ <ColumnHeaderCell>
    ✓ <RowHeaderCell>
    ✓ <EditableName>
    ✓ <Table> (40ms)


  11 passing (93ms)
  1 pending
```

**Comment by giladgray** [comment]
this line skips the test, i don't remember why. https://github.com/palantir/blueprint/blob/master/packages/table/test/isotest.js#L24

**Comment by giladgray** [comment]
probably because the component has very exacting props/children requirements that are hard to meet in the confines of the isotest environment.
