### ISSUE TITLE
New Feature: Tab2 component support for composition

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#782]
In our application, to be able to isolate any compatibility issues and also address any potential gaps, we are putting our own wrapper around open source components. So the api that gets used in rest of the application is wrapper api.

This has been working fine but facing an issue with Tab2 component. When I wrap `Tabs2` and `Tab2` in wrappers, let's call them `OurTabs` and `OurTab` and use them, tab component doesn't work. I think this is because Tabs2 internally check if children are instance of Tab2 component and since our wrappers doesn't pass that check, it just treats them as any other element.

We would like to be able to extend `Tabs2` and provide a overridden implementation of `isTab` to check if that instance of `OurTab`. As long as `OurTab` provides some of the same props like `id` etc., it should work.

So ask is that, how can we extend `Tabs2` and override `isTab` method?

Thanks for your help.

**Comment by adidahiya** [comment]
1. in `OurTab`, are you using `React.cloneElement` to clone `Tab`?
2. we could relax our filter [here](https://github.com/palantir/blueprint/blob/1632022bf1928dcce48c5f5ec262b4eda8154d54/packages/core/src/components/tabs2/tabs.tsx#L183) to just issue a development warning for non-Tab children instead of filtering them out completely

**Comment by brsanthu** [comment]
@adidahiya We are not using cloning but rendering the Blue print tab in its render method. For ex., here is the full code for Tab2 wrapper. Yes, relaxing that condition or providing an option to override that is considered as a tab with updated `isTab` method would be nice.

```
import { Tab2 as BpTab2 } from '@blueprintjs/core';
import * as React from 'react';
import * as classNames from 'classnames';

export interface OutTabProps {
    id: string;
    label: string;
    className?: string;
    disabled?: boolean;
}

export const OutTab: React.SFC<OutTabProps> = (props) => {
    return (
        <BpTab2
            id={props.id}
            className={classNames('sui-tab', props.className)}
            disabled={props.disabled}
            panel={<div>{props.children}</div>}
        />
    );
};
```

**Comment by giladgray** [comment]
warning for non-Tab children is not correct because those are happily supported by the component. i think allowing custom `isTab` filtering or actually cloning the `Tab2` element are the best answers.

**Comment by brsanthu** [comment]
@giladgray can you please suggest how do I go about cloning the `Tab2`?

**Comment by brsanthu** [comment]
I could implement wrapper for Tab2 component. I'm going over the our child tab and for each of our child tab, I'm creating new instance of Bp tab. It is working as expected. Here is the source for those two wrappers.

//SuiTabs.tsx
```
import { Tabs2 as BpTabs2, Tab2 as BpTab2} from '@blueprintjs/core';
import { SuiTab, SuiTabProps } from './SuiTab';
import * as React from 'react';
import * as classNames from 'classnames';
import './SuiTabsStyle.scss';

export interface SuiTabsProps {
    id?: string;
    className?: string;
    vertical?: boolean;
    selectedTabId?: string | number;
    onChange?: (newTabId: string | number, prevTabId: string | number) => any;
}

function isTab (child: React.ReactChild) {
    return (child as JSX.Element).type === SuiTab;
}

export const SuiTabs: React.SFC<SuiTabs> = (props) => {
    return (
        <BpTabs2
            id={props.id || ''}
            className={classNames('sui-tabs', props.className)}
            vertical={props.vertical}
            onChange={props.onChange}
            selectedTabId={props.selectedTabId}
        >
            {
                React.Children.map(props.children, child => {
                    if (isTab(child)) {
                        const suiTab: any = (child as JSX.Element).props as SuiTabProps;
                        return (
                            <BpTab2
                                key={suiTab.key}
                                id={suiTab.id}
                                className={classNames('sui-tab', suiTab.className)}
                                disabled={suiTab.disabled}
                                panel={<div>{suiTab.children}</div>}
                                title={suiTab.label}
                            />
                        );
                    }
                    return child;
                })
            }
        </BpTabs2>
    );
};
```

//SuiTab.tsx
```import * as React from 'react';

export interface SuiTabProps {
    id: string;
    label: string;
    className?: string;
    disabled?: boolean;
}

export const SuiTab: React.SFC<SuiTabProps> = (props) => {
    return (
        <span>This should not be rendered!</span>
    );
};
```

//Usage
```
                <SuiTabs>
                    <SuiTab id='react' label='React'>
                        <span>Hello React</span>
                    </SuiTab>
                    <SuiTab id='angular' label='Angular'>
                        <span>Hello Angular</span>
                    </SuiTab>
                    <SuiTab id='ember' label='Ember'>
                        <span>Hello Ember</span>
                    </SuiTab>
                </SuiTabs>
```
