### ISSUE TITLE
New Feature: Frozen Columns in React Table

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#793]
Mechanism to freeze one or two columns on the left of the table would be really helpful. We are adding a non-functional column called `Actions`, which shows checkbox for users to select the row. We would like this column to be visible always even when user scrolls right.

Not sure if that is always possible to achieve with current version.

**Comment by llorca** [comment]
Yep, we very much want this, just haven't had time to build it yet. Closing as dupe of #503

**Comment by brsanthu** [comment]
thx @llorca will follow other issue.
