### ISSUE TITLE
Show popover arrow when pinned

### ISSUE THREAD

**Issue by Que3216** [palantir/blueprint#798]
### Bug report

Blueprint v1.11.1 and below (all version of Blueprint), all browsers.

#### Steps to reproduce

1. Go to http://blueprintjs.com/docs/
2. Go to the popovers section, set position to top right, pin to window, and content to 'Popover Example'

![image](https://cloud.githubusercontent.com/assets/793481/23661251/1304b8be-0344-11e7-89fe-475ebfd12d28.png)

3. Make the window really thin, and open the popover so that it gets pinned

#### Actual behavior

The arrow doesn't show

![image](https://cloud.githubusercontent.com/assets/793481/23661306/3cb6f05a-0344-11e7-9696-bc6d4e8755ed.png)

#### Expected behavior

The arrow should show

**Comment by Que3216** [comment]
Would it be possible to get a fix for this?

**Comment by adidahiya** [comment]
@Que3216 we have a few other urgent priorities at the moment, but we'd take a PR that allows this to be configurable in `<Popover>`. something like `showArrowWhenPinned: boolean`

**Comment by giladgray** [comment]
Popover in 2.0 using Popper.js handles this quite differently.
Reopen if still relevant.
