### ISSUE TITLE
Select all option in table 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#806]
Allow users to cmd+A or click on the upper left corner in order to select their whole table
This will help so users can select all and resize all easily 

Excel does it this way

**Comment by llorca** [comment]
@gscshoyru are their APIs for consumers to build this already? If so, great, we just need to hook `cmd+a` to it

**Comment by gscshoyru** [comment]
I'm not sure what you mean by API for consumers to build this already means? Table selection does already support the ability to select-all, yes, there's just no way to do it at present unless you have externally controlled selection via props -- which I don't think is the ask here. 

Adding a cmd+a hotkey to select all should be... rather straightforward. We may also want to make it such that clicking the top-left corner does this as well.

**Comment by giladgray** [comment]
i think this was implemented in #822
