### ISSUE TITLE
Feature Request: Capability to customize complete row rendering

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#808]
With cell render, we can completely customize how a cell looks/behaves. However, with current capability it is not possible to customize complete row. For ex., for particular type of rows (based on the row content), we may want to render completely different content, may be without any cells but just a one div covering whole row.

**Comment by giladgray** [comment]
I'm not sure this request is practical to implement. There's enough virtual magic going on inside the `Table` that we may not be able to relinquish this sort of control. @themadcreator @gscshoyru can provide more insight?

**Comment by giladgray** [comment]
closing as impractical to implement, but we will likely tackle "merged cells" at some point in the future.

**Comment by brsanthu** [comment]
Thank you for looking into it.
