### ISSUE TITLE
Feature Request: Accordion Component

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#814]
Please consider adding Accordion component. 

Here are some react based implementations.

1. https://react-component.github.io/collapse/examples/simple.html
2. https://github.com/glennflanagan/react-collapsible

**Comment by adidahiya** [comment]
Blueprint has [a Collapse component](http://blueprintjs.com/docs/#components.collapse) which should generally satisfy this need. You can compose an Accordion out of Collapse if you choose. Including an Accordion in the core components is pretty low priority for us and I'm not sure we even want to maintain it ourselves (could be a separate independent project / package).

**Comment by giladgray** [comment]
Closing this as https://github.com/palantir/blueprint/issues/814#issuecomment-285405477 above pretty much sums up why we won't be building an `Accordion`. That first linked example is nothing more than several sibling `Collapse`s, and an "accordion" is a simple state layer that ensures only one `Collapse` is open at a time.

**Comment by brsanthu** [comment]
Thank you @adidahiya and @giladgray. Makes sense. Will try to implement internally based on collapse.

**Comment by dandv** [comment]
I was also looking for an accordion component, and wanted to chime in.

* the updated link to Collapse is https://blueprintjs.com/docs/#core/components/collapse
* it would help to add the bit in the second comment to the documentation, so those who search for "accordion" at blueprintjs.com do find that page plus the explanation of how to build one.

**Comment by mmz15** [comment]
For what it's worth, and though a little late, I second @dandv. Being able to search for 'accordion' and being redirected to collapse would've saved me a good few minutes. Awesome work on the library thus far.

**Comment by Lonli-Lokli** [comment]
I would say Section component is closer to Accordion child than Collapse
