### ISSUE TITLE
Make interfaces and components in code blocks act as links

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#817]
As an example, in the following image it'd be nice if the circled sections were clickable and would redirect to the relevant sections in docs. There are many places where this would need to happen so I imagine it's a pretty huge change. Belying this enhancement request is the fact that certain interfaces, while referenced, do not exist on the docs page. Perhaps undocumented interfaces warrant a separate ticket?

![screen shot 2017-03-09 at 1 50 45 pm](https://cloud.githubusercontent.com/assets/3681045/23765541/8a06df5a-04cf-11e7-8425-717ff7a180ab.png)

Marking as P3 because in most instances, the search box is sufficient if not a slightly more tedious way of getting to the same destination.

#### BP version: 1.11.1

**Comment by giladgray** [comment]
ooooh yeah @llorca and i have thought about this one a lot. definitely a feature we want to add 📖

**Comment by giladgray** [comment]
whoa guess what #2041 will fix this issue precisely!

**Comment by michael-yx-wu** [comment]
Amazing :)
