### ISSUE TITLE
FR: EditableText should have configurable cancel and confirm keys

### ISSUE THREAD

**Issue by waltonseymour** [palantir/blueprint#819]
I'm looking to use ESC to confirm rather than undo the text I've written.

Making the keys configurable would solve this problem for me.

**Comment by leebyp** [comment]
The keys that we choose for the interactions are pretty standard across the web. I wonder if theres a case of customising our implicit shortcuts across all the components.

This particular case doesn't sound like a normal interaction - is there something restricting the use of <kbd>enter</kbd>?

**Comment by giladgray** [comment]
@waltonseymour what's the status of this issue? i remember we discussed offline. please update and close if it's resolved.

**Comment by waltonseymour** [comment]
Was able to get a workaround with `onCancel `
