### ISSUE TITLE
Table row resizing should show guideline, like columns

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#821]
### Bug report

- __Package version(s)__: table 1.8.1

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/723999/23807411/95de5f5a-0593-11e7-9fb2-7bdb89bf865c.png)

#### Expected behavior

show a guideline like columns:

![image](https://cloud.githubusercontent.com/assets/723999/23807430/a61fc610-0593-11e7-8f89-ac20cbf97827.png)

**Comment by tgreenwatts** [comment]
Fixed as part of other work!
