### ISSUE TITLE
Shift selection mode for table regions

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#823]
This would mitigate #505 because you could make one selection, scroll over to the end of your range, and then make another selection in the <kbd>Shift</kbd> mode of interaction.

Part of #298, but I'd like to track it separately.

**Comment by cmslewis** [comment]
Opened #1071 as a first pass that doesn't consider the focused cell when expanding the selection. Added some TODOs in that PR that refer back to this ticket.

Next, we'll need to pass the current focused-cell coordinates into DragSelectable (as well as the `enableFocus` flag?) and change the selection-expansion logic accordingly.
