### ISSUE TITLE
Hotkeys: preventDefault and stopPropagation props

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#824]
I see a lot of `Hotkey` handlers that look like this ([source](https://github.com/palantir/blueprint/blob/69316ea4ba1f22c6df358f7769de2d4a23b57d49/packages/table/src/table.tsx#L504-L510)): 

```tsx
<Hotkey combo="cmd+a" onKeyDown={this.handleSelectAllHotkey} />

private handleSelectAllHotkey = (e: KeyboardEvent) => {
    // prevent "real" select all from happening as well
    e.preventDefault();
    e.stopPropagation();

    this.selectAll();
}
```

Wouldn't it be neat if they could look like this:

```tsx
<Hotkey combo="cmd+a" preventDefault stopPropagation onKeyDown={this.selectAll} />
```

**Comment by cmslewis** [comment]
If there were a `preventDefault` prop (e.g.), would we want to invoke `e.preventDefault()` on _both_ `keyup` and `keydown`, or just one of those?

**Comment by llorca** [comment]
If consumers provide `keydown`, we invoke those on `keydown`, same for `keyup`?
