### ISSUE TITLE
Icons. New classes with pt-input-group. Usage of two fonts

### ISSUE THREAD

**Issue by jackkainov** [palantir/blueprint#834]
### Bug report

- __Package version(s)__: 1.11.1
- __Browser and OS versions__: Chrome Version 56.0.2924.87

#### Steps to reproduce
1. Create a span with `pt-icon-standard pt-icon-add` class
2. Create a span with `pt-icon-large pt-icon-add` class
3. Create a span with `pt-icon pt-icon-add` class
4. Create a div with `pt-input-group` and put an input html element with a span with a `pt-icon-standard` or `pt-icon-large` class inside

#### Actual behavior

- All icons should use *one* font
- `pt-icon-standard` and `pt-icon-large` should work with `pt-input-group` 

#### Expected behavior
- Some classes use 'Icons16', others use 'Icons20', which leads to two requests instead of one
- icons used inside a `pt-input-group` class are not places in the correct way.
![image](https://cloud.githubusercontent.com/assets/7371747/23907846/9674d984-08d2-11e7-9517-da168f722c72.png)

**Comment by llorca** [comment]
One sized icons that you scale at different sizes are bad practice. We ensure visual crispness by hinting icons at __two sizes__, for cases when your UI is either "regular" size or "large". The fact that the current implementation is achieved through 2 separate fonts will change in 2.0, where we plan on supporting SVG icons directly: https://github.com/palantir/blueprint/issues/365

As for input groups, we already support regular and large size, icons included. Please go over the documentation: http://blueprintjs.com/docs/#components.forms.input-group
