### ISSUE TITLE
Tabs2 NPEs if passed `null` amongst children.

### ISSUE THREAD

**Issue by AndyMoreland** [palantir/blueprint#838]
Goal: conditionally render a tab.

### Bug report

- __Package version(s)__: 1.11.1

#### Steps to reproduce

```
<Tabs2>
{ null }
</Tabs2>
```

#### Actual behavior
Exception

```
Uncaught TypeError: Cannot read property 'type' of null
    at isTab
```

#### Expected behavior

Don't render the tab.

**Comment by giladgray** [comment]
😱 and i'll bet `undefined` doesn't work either from looking at the code

**Comment by AndyMoreland** [comment]
yeah most likely! :-)
