### ISSUE TITLE
Focus outline should not hide on hover

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#842]
### Bug report

- __Package version(s)__: Blueprint v1.12.0
- __Browser and OS versions__: OS X Chrome 56

#### Steps to reproduce

1. Focus on a button via <kbd>Tab</kbd>
1. Now hover over it with the mouse.

#### Actual behavior

Focus outline hides on hover. Here's a janky example from focus state in a dropdown menu:

![2017-03-15 13 40 59](https://cloud.githubusercontent.com/assets/443450/23970015/b0764dfa-0985-11e7-886f-76868059b06b.gif)

#### Expected behavior

Focus outline should still be visible.

**Comment by evansjohnson** [comment]
![Screenshot 2024-06-25 at 1 54 26 PM](https://github.com/palantir/blueprint/assets/14102129/296a979c-cac1-4b8c-b277-0b1755ec89f6)

This seems to no longer reproduce
