### ISSUE TITLE
[Popover] Popover sometimes detaches from navbar in docs

### ISSUE THREAD

**Issue by LittlePony** [palantir/blueprint#845]
### Bug report

- __Package version(s)__: 1.12
- __Browser and OS versions__: chrome, firefox, windows, linux

#### Steps to reproduce

1. open http://blueprintjs.com/docs/
2. scroll down 2-3 lines
3. few (4-5 ) clicks "releases" button  at headbar and stay popover opened.
4. scroll again
#### Actual behavior

popover detaches from headbar and scroll with block.

**Comment by cmslewis** [comment]
Gah, I only got this to repro once in like 3 minutes of testing. No idea what the problem is.

**Comment by llorca** [comment]
@cmslewis I have consistent repro steps:
1. Open http://blueprintjs.com/docs/
2. Scroll down a bit
3. Quickly click 3 times on the "Releases" button
4. Scroll more

![screen recording google chrome](https://user-images.githubusercontent.com/199754/27757074-2a741bde-5db2-11e7-9020-d09f97e0b88e.gif)

**Comment by LittlePony** [comment]
It can be reproduced with any Popover and scrolling body. Not only Doc or Navbar related.

**Comment by LittlePony** [comment]
another reproducion of this bug - popover will not scroll with scrolling div as parent inside fixed body

**Comment by giladgray** [comment]
pretty sure `Popover2` resolves this, and the new docs site #2243 no longer has a navbar along the top at all.
