### ISSUE TITLE
checkboxes/radios intent is missing

### ISSUE THREAD

**Issue by bbenezech** [palantir/blueprint#855]
`.pt-control-indicator.pt-intent-primary` does nothing.
It looks quite easy to port `.pt-input.pt-intent-primary`'s behaviour (visually it works fine).

On a related topic, `.pt-input.pt-intent-primary` works fine on selects, but it is not documented.

Should I hack my way through or do you guys think it should be added for consistency?

Many thanks, you really nailed the web application UI niche like no-one before did. 
I no longer see big flat Bootstrap buttons when I close my eyes at night, really cannot thank you enough.

**Comment by brsanthu** [comment]
We need this to work for checkboxes/radioboxes so we implemented our own. Here is how it looks.

![image](https://cloud.githubusercontent.com/assets/842964/24019897/2b75768a-0a57-11e7-9868-a41f22962d59.png)

![image](https://cloud.githubusercontent.com/assets/842964/24019912/396af44a-0a57-11e7-8643-615f4a3978a5.png)

**Comment by llorca** [comment]
Thanks guys! So what would you expect, say, `.pt-control-indicator.pt-intent-danger` to look like on checkboxes and switches? Same as currently for the "off" state, and the "on" state should get the color from the corresponding intent?

**Comment by bbenezech** [comment]
@llorca I was thinking about the usual border-shadow on the input itself. It's discreet but noticeable.
@brsanthu solution also looks nice.

**Comment by brsanthu** [comment]
One other thing to consider is sometimes radio group is part of one input rather than individual. For ex., in above screenshot, it is multiple values for one question. If user didn't choose any of those values, then whole list is in error not individual options.
