### ISSUE TITLE
Delete force-hardware-acceleration() mixin when Chrome will-change bug fixed 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#859]
Reminder to move to `will-change: transform` and delete our the `force-hardware-acceleration` mixin once Chrome's blurry-text bug is fixed:

- **Demo:** https://www.youtube.com/watch?v=iSvUlSpIbNk
- **Chome bug:** https://bugs.chromium.org/p/chromium/issues/detail?id=596382

As of this writing, the mixin is used in `table.scss` to improve scrolling performance on big `Table`s.

**Comment by ellisio** [comment]
This is considered fixed according to the Chrome bug report. Time to remove this maybe?
