### ISSUE TITLE
Hover on long column headers

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#864]
Allow users to hover over their column headers to see the full column title
![image](https://cloud.githubusercontent.com/assets/24398123/24123786/2aa6925a-0d7e-11e7-9b4c-5c85ac39b816.png)

**Comment by llorca** [comment]
Looks like a great candidate for `<Text ellipsize>`

**Comment by llorca** [comment]
Looks like a great candidate for `<Text ellipsize>` cc @ryanmcnamara

**Comment by cmslewis** [comment]
@tgreenwatts was this fixed?

**Comment by tgreenwatts** [comment]
I think it should be the apps responsibility, seems like too many custom headers to do this ourselves. Happy to reopen if you think otherwise
