### ISSUE TITLE
Disabled minimal button appears with background in IE 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#865]
### Bug report

- __Package version(s)__: v1.12.0
- __Browser and OS versions__: IE11

IE: 
![image](https://cloud.githubusercontent.com/assets/24398123/24127493/4571062e-0d92-11e7-9672-993a5f006a05.png)

Expected/Chrome:
![image](https://cloud.githubusercontent.com/assets/24398123/24127500/522f66e4-0d92-11e7-836c-92d408a7824f.png)

Background shows up on just the disabled button

**Comment by llorca** [comment]
Only a problem for `<button>`, not `<a>`? 🤷‍♂️ 

I bet changing `inherit` to `none` would fix it: https://github.com/palantir/blueprint/blob/master/packages/core/src/components/button/_common.scss#L317

**Comment by tgreenwatts** [comment]
Oooh here is the opposite for regular button - Anchor doesn't appear disabled but Button does! 
![image 2](https://cloud.githubusercontent.com/assets/24398123/24166753/92dc3812-0e31-11e7-8ce2-bc47c1c44730.png)

**Comment by llorca** [comment]
^ That's not a bug, anchors simply don't support `:disabled` (the attribute)
