### ISSUE TITLE
[Popover] Smart Position popovers don't work well 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#870]
To reproduce:
In the docs, choose to position the popover Bottom Left
Turn on smart position
Make screen appropriately small
Expected: Popover moves to a better position
Actual: Popover stays in bottom left

I've also seen Popovers smart position above when they have plenty of room to position below which was their default. 

Many other smart position issues 

One internal workaround: https://pl.ntr/es

**Comment by adidahiya** [comment]
perhaps we should change the default constraint to `[{ to: "window", attachment: "together"}]` and remove the `useSmartPositioning` prop in the next major version?

**Comment by tgreenwatts** [comment]
Didn't we deprecate `useSmartPosition` ? Can we close this now?

**Comment by cmslewis** [comment]
Closing given that `useSmartPositioning` is deprecated as of v1.15.0
