### ISSUE TITLE
[DateInput] Add support for className prop

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#878]
### Bug report

- __Package version(s)__: DateTime 1.9.1

#### Steps to reproduce

1. Set `className` on date input class.

#### Actual behavior

Class name does not show up on the input or the popover element.

#### Expected behavior

`className` should show up on the input or the popover target element (should probably be able to class names to both?).

**Comment by giladgray** [comment]
seems like `<DateInput className>` gets sent to the `DatePicker`: https://github.com/palantir/blueprint/blob/master/packages/datetime/src/dateInput.tsx#L159-L160

**Comment by leebyp** [comment]
Will be fixed as part of 2.x as per the discussion in #387

**Comment by adidahiya** [comment]
dupe of #387
