### ISSUE TITLE
Table's `columnWidths` typings disagree with the doc comment

### ISSUE THREAD

**Issue by seansfkelley** [palantir/blueprint#879]
[From `Table`](https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L92..L98):

    /**
     * A sparse number array with a length equal to the number of columns. Any
     * non-null value will be used to set the width of the column at the same
     * index. Note that if you want to update these values when the user
     * drag-resizes a column, you may define a callback for `onColumnWidthChanged`.
     */
    columnWidths?: number[];

If the doc comment is right, the type should be `(number | null | undefined)[]` (assuming by "non-null" is means "non-null, non-undefined"). Otherwise, the doc comment should be changed to agree with the typings.

**Comment by giladgray** [comment]
worked fine pre-`strictNullChecks` (which we still haven't enabled internally) 😄 

good catch @seansfkelley!
