### ISSUE TITLE
selectedTabId doesn't change on creating new tab group

### ISSUE THREAD

**Issue by agaurav** [palantir/blueprint#888]
### Bug report

- __Package version(s)__: `1.13`
- __Browser and OS versions__:  `chrome  57.0.2987.110 (64-bit)`, `Arch Linux-4.10.5-1`

#### Steps to reproduce

1. Inside a react component create a `tabs2` component from passed props, the generated `tabs2` properties are tab group id, tab ids & their panel data
e.g. factory function below

``` typescript

private makeDashConf = (conf: INodeMetricConf): JSX.Element => {
            const dashTabs = Object.keys(conf).map(
                (metricGroupId) => {
                    const tabPanel = <pre>
                        <code>
                            {this.props.nodeId}
                            {JSON.stringify(conf[metricGroupId], null, 2)}
                        </code>
                    </pre>
                    return <Tab2
                        key={metricGroupId}
                        id={'dashTab-' + metricGroupId + this.props.nodeId}
                        title={conf[metricGroupId].name}
                        panel={tabPanel}
                    />
                }
            )
            return (
                <Tabs2
                    animate={true}
                    id={"NodeExplorerGroups-" + this.props.nodeId}
                    renderActiveTabPanelOnly={true}
                    defaultSelectedTabId={'dashTab-cpus' + this.props.nodeId}
                >
                    {dashTabs}
                </Tabs2>);
        };

public render() {
        const dashTabs = this. makeDashConf(this.props.conf);

        return (
            <div style={{ overflowY: 'scroll', height: '80vh' }}>
                {dashTabs}
            </div>
        );
}

```

2. Change the passed prop from the parent of this component (for above e.g. the `conf` prop)

#### Actual behavior
On change of passed `props`  new tabs & tab group is generated but the `selectedTabId` state is retained when an already used `conf` is passed again.

Screenshots from react-dev-tool:

![a1](https://cloud.githubusercontent.com/assets/1772870/24321500/2bee91ea-1174-11e7-8100-4e9f5fca37ad.jpg)

![a2](https://cloud.githubusercontent.com/assets/1772870/24321502/3137e188-1174-11e7-96f9-df6bfa0d5265.jpg)

`selectedTabId` doesn't change while `Tabs2 id` & `defaultSelectedTabId` have changed.

#### Expected behavior
Either the SelectedTabId should take the `defaultSelectedTabId` value or it should retain it from the tab group of same id not the previous one.

**Comment by giladgray** [comment]
this is not a bug, it's actually expected behavior for uncontrolled react components. see https://facebook.github.io/react/docs/uncontrolled-components.html#default-values and http://goshakkk.name/controlled-vs-uncontrolled-inputs-react/

`defaultSelectedTabId` only works on the initial load of the component; this is consistent with how React HTML elements handle `defaultValue`. if you want to change the selection later, **you must use controlled mode.**

a clever workaround for this case (since you seem to be changing the tabs themselves considerably) is to assign a `key` to the `Tabs2` and change it when you change the tabs. changing the `key` will cause a new instance to be created and the new `defaultSelectedTabId` will be respected during that initial load.

**Comment by agaurav** [comment]
@giladgray make sense, thanks for the unique `key` approach. 

Though will adding the following check in `componentDidUpdate` [here](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/tabs2/tabs2.tsx#L153) a good idea ? 
I am using a similar workaround but via controlled mode.

``` typescript
const newTabs = this.getTabChildren();

const tabExists = ( tab :{id: string}): boolean => {
   return tab.id === this.state.selectedTabId;
};

if (newTabs && newTabs.length > 0 && newTabs.findIndex(tabExists) < 0) {
   const selectedTabId = this.props.defaultSelectedTabId || newTabs[0].props.id;
   this.setState({selectedTabId});
}
```

**Comment by giladgray** [comment]
my understanding of `defaultValue` in React components is it only applies on the initial load, and will never be applied again. there's no concept of reverting to a default value.

also, changing the entire `Tabs` structure is a major edge case and could be considered an anti-pattern (consistency above all else). so i'm not interested in adding logic to support this.

as a result, @agaurav i think changing the `key` is the simplest and most reliable way of achieving your goal here.
