### ISSUE TITLE
Can' find a double click callback function on Table

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#892]
I am using `<Table />`  component but I couldn't find a place to register double click function. There is only `onSelection` prop I can use. Is there a way to register a double click function?

**Comment by tgreenwatts** [comment]
@gscshoyru ?

**Comment by giladgray** [comment]
pretty sure the Table does not support custom double-click listeners.

@zhaoyi0113 what are you trying to achieve? please describe the feature request more fully so we can better estimate implementation cost.

**Comment by zhaoyi0113** [comment]
Below screen shot is a list of connection on my application. They are rendered inside `<Table>` component. What I want to do is to allow user double-click each item and open a dialog to show some information. How can I achieve this on Table cell?

<img width="126" alt="screen shot 2017-03-29 at 9 20 54 am" src="https://cloud.githubusercontent.com/assets/3355579/24430161/094f8532-1461-11e7-9788-77c353ca49e8.png">

**Comment by giladgray** [comment]
can you simply render a custom element inside `Cell` with your own `onDoubleClick` handler?

**Comment by zhaoyi0113** [comment]
It should work. Thanks for your response.

**Comment by tnrich** [comment]
Hey @giladgray , I'm encountering the following issue:

![image](https://cloud.githubusercontent.com/assets/2730609/26657182/37c179a6-4617-11e7-9c5c-a1bca5d9383a.png)

As you can see, the clickable region does not actually expand to the edges of its containing div which results in some clicks not working if you click on the edge of a cell. 

My code is just like what you said to do above:
```
      <Cell>
          <span
              className={"clickable-cell"}
              onDoubleClick={() => {
                onDoubleClick(row, rowIndex, history);
              }}
            >
              {cellData}
            </span>
      </Cell>
```

This makes me think we'll need to have a way to pass the onDoubleClick prop directly to the blueprint provided Cell component.

Thanks!

**Comment by nagylzs** [comment]
Isn't it slow for huge tables?
