### ISSUE TITLE
Hovering parent menu issue on submenus

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/blueprint#898]
### Bug report

- __Package version(s)__: 1.13 core
- __Browser and OS versions__: Mac OSX 10.11.6

#### Steps to reproduce

![mar-28-2017 13-56-07](https://cloud.githubusercontent.com/assets/3452559/24427093/9d2ebc44-13be-11e7-9c53-bf3c68ff0a08.gif)

Done on the docs page: When hovering the parent of an opened submenu, I would expect the submenu to stay open

**Comment by ryanmcnamara** [comment]
OSX does it like so:
![mar-28-2017 13-56-07](https://cloud.githubusercontent.com/assets/3452559/24427229/168b0e08-13bf-11e7-9f3a-311bdb5ebaaf.gif)

**Comment by giladgray** [comment]
seems fixed in 2.0
