### ISSUE TITLE
[Table] wrapText should be enabled automatically when rows are resized

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#901]
### Problem

The current table cell wrapping experience is not great because the feature has to be manually enabled:

![2017-03-28 21 27 57](https://cloud.githubusercontent.com/assets/723999/24434737/59a55ec4-13ff-11e7-8228-9ac2de9dd819.gif)

Since we don't do any automatic text wrapping (expand row heights to fit multiline cell contents, which would be ideal) and instead rely on end users to manually resize rows when they wish to see wrapped content, blueprint table can be smarter out of the box about when to wrap cell text.

### Proposal

Automatically enable `wrapText` on Cells when their rows have been expanded from the default row height.

**Comment by llorca** [comment]
Can we reenable it if the row is resized to its original default/min height?

**Comment by adidahiya** [comment]
> Can we reenable it if the row is resized to its original default/min height?

Yeah, we should probably re-enable it if it's resized to within some threshold of the default height (don't expect users to resize pixel-perfect).

Also that makes me wonder if rows should have a "reset height" context menu action on row headers?

**Comment by llorca** [comment]
> Also that makes me wonder if rows should have a "reset height" context menu action on row headers?

Might as well, seems like a useful utility at this point 👍 Not sure if it happens automatically or not, but don't forget to put it in the right click menus too.

Additionally, if the row is resized within -/+ 10px of its original height, we could snap it back to its original height and disable wrapping?

**Comment by tgreenwatts** [comment]
bleh on 'reset rows heights' as a context option, I'd think maybe double click on the row edge would be better - expands the first time, collapses the second
I don't see how it will work if I resize 10 rows individually, and then resize 1 back to it's original height.

If anything a "Wrap text"/"Unwrap text" option in the context menu still makes sense even if we wrap automatically.

**Comment by adidahiya** [comment]
reset row height context menu action -- ok I agree that double-clicking might make sense instead, but notice that google sheets doesn't do this (double clicking row edges doesn't do anything)

> If anything a "Wrap text"/"Unwrap text" option in the context menu still makes sense even if we wrap automatically.

@tgreenwatts why? the point of doing it automatically is so that users don't have to think about it but they still get good UX

**Comment by tgreenwatts** [comment]
Automatically doing it for the user, but allowing them an escape hatch if that wasn't the functionality they wanted. Excel does it automatically for me, but I still could manually click the buttons if I wanted

Also I'm a bit skeptical of how good we're going to be at unwrapping for the user - what if they've scrolled and now they are in a new area that they want to view unwrapped, although I can't imagine they would unless wrap/unwrap resized things automatically for them. (which is what I really want)

**Comment by adidahiya** [comment]
> what if they've scrolled and now they are in a new area that they want to view unwrapped

`wrapText` would only be automatically set at a _cell_ level, not a column level (that's how the internals of it work). I still fail to see a situation where the escape hatch is needed. Can you provide a concrete example?

**Comment by tgreenwatts** [comment]
Not without playing with it, although I see little harm in having it in the menu, but I think this would be better to just try out and see how it feels

**Comment by adidahiya** [comment]
> I see little harm in having it in the menu

I think there is _some_ harm because the option doesn't do the intuitive thing that users have come to expect from spreadsheet applications (automatically compute necessary row heights) -- in this way I think we had a poor rollout of this feature.

**Comment by tgreenwatts** [comment]
But what is the harm in having the explicit to to wrap or unwrap text? Even if we do it automatically, we should still have the option

**Comment by adidahiya** [comment]
Adding unnecessary options to the UI adds undue complexity. You may be thinking that adding this option to the column header helps with discoverability of text wrapping, but it doesn't do that either &mdash; users still have to somehow discover the linked row resizing feature we added (#802).

I feel pretty strongly about this, we should catch up offline if you want to discuss further.

**Comment by gscshoyru** [comment]
@adidahiya -- I'm not sure this issue makes sense. Wrap text is set by the cell renderer on a per-cell basis -- are you suggesting we override/ignore the specified prop if the row height is different? 

Additionally -- neither excel nor google docs work this way. They _do_ automatically resize rows when you turn cell wrapping on (which we've provided the `resizeRowsByTallestCell` method in #960 for, which is a heuristic until we get better perf) -- but they don't do it the other way around. I'm not so sure we should do this.

**Comment by tgreenwatts** [comment]
+1 but I'm happy to wait to play with what we've got in a prod environment and see if we're doing enough

**Comment by adidahiya** [comment]
Alright, I'll concede that we should try `resizeRowsByTallestCell` in practice and see if it provides a good enough UX in our target applications before implementing this feature.

> Wrap text is set by the cell renderer on a per-cell basis -- are you suggesting we override/ignore the specified prop if the row height is different?

@gscshoyru essentially, yes. I don't think wrap text makes sense for individual cells, despite the fact that we decided to put that prop on `<Cell>`. The way the props interfaces are designed shouldn't constrain UX decisions (instead, they should be driven by the desired UX).

**Comment by gscshoyru** [comment]
@adidahiya excel and google sheets both let you set text wrapping on individual cells. Why should we be any different here? I'm not sure I agree that what you describe is the wanted UX. 

And if it _is_ the wanted UX -- then at what level should the wrapping be? I can think of good cases for per-row wrapping, in addition to the obvious per-column ones.

**Comment by tgreenwatts** [comment]
I'm inclined to close this as 'won't fix'. I don't think we should be in the business of changing any properties on resizing. I haven't heard any apps directly requesting this either
