### ISSUE TITLE
Add IRegion to docs

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#902]
I am using `<Table>` component as below:

```
const renderCell = (rowIndex : number) => {
      return <Cell>{profiles[rowIndex][1].alias}</Cell>;
    };
    return (
      <div className="profileList">
        <Table
          allowMultipleSelection={false}
          numRows={this.props.size}
          isRowHeaderShown={false}
          selectionModes={SelectionModes.ROWS_AND_CELLS}
          isColumnResizable={false}
          isRowResizable={false}
          defaultColumnWidth={1024}
          onSelection={region => this.onSelection(region)}>
          <Column  renderCell={renderCell} />
        </Table>
      </div>
    );
```

Is there a way for me to make a cell selected programatically? I want to make the first added cell selected by default.

**Comment by adidahiya** [comment]
Yes, you can switch table selection to controlled mode by supplying the prop `selectedRegions: IRegion[]` (see [Table JS API](http://blueprintjs.com/docs/#components.table-js.api.table)). In your case you would supply a single region which contains the first cell only.

It looks like `IRegion` and its dependent interfaces don't show up in the docs, so you'll need to refer to the JSDoc comments on the interfaces: https://github.com/palantir/blueprint/blob/868659b0d3165bd0c2db9d7bd04289ab32bfd1c6/packages/table/src/regions.ts#L105

**Comment by tgreenwatts** [comment]
Is there any action remaining here?

**Comment by adidahiya** [comment]
we should get `IRegion` and its dependent interfaces to show up in the docs. @giladgray

**Comment by zhaoyi0113** [comment]
It works fine now. Thanks for your help.

**Comment by adidahiya** [comment]
keeping this open for the remaining action on docs

**Comment by llorca** [comment]
@zhaoyi0113 from comment above, let us do the quick documentation update before closing this issue. Thanks!
