### ISSUE TITLE
[Table] A possibility to persist the sort direction icon in the column header 

### ISSUE THREAD

**Issue by michshat** [palantir/blueprint#903]
Thank you for library - components are top notch :) 

Quick question, not sure if it's something that already supported. Is there a way persisting a column sort order icon `asc` or `desc`? 

![image](https://cloud.githubusercontent.com/assets/13825309/24465463/13dacc90-147b-11e7-9a8e-d2deb13ee4c9.png)

**Comment by giladgray** [comment]
What do you mean "persist?" As a _library_, we cannot support persisting state across page reloads--that is the responsibility of your _application_.

**Comment by michshat** [comment]
@giladgray sorry i wasn't clear, i may still not am :) ... 
Use case:
1. there is a table and it supports data sorting
2. user mouse over on the 'Rikishi' column and eclipses are shown
3. user clicks the 'Sort Asc' option from the popup
4. table data is sorted by Rikishi in ascending order
5. table header 'Rikishi' is showing an 'asc'  icon next to column header name

Step 5 is it possible?

Thanks again!

**Comment by michshat** [comment]
There are two properties that might help me to achieve that - `isActive` and `menuIconName`. When column sort is triggered setting `columnHeaderState` to `isActive` to true; and changing `menuIconName` to corresponding sort icon.

`
export interface IColumnHeaderState {
    isActive: boolean;
}
`

**Comment by cmslewis** [comment]
@michshat I see what you mean. That could be a nice feature, though here are some challenges:

- Each column header already contains a visual affordance for a context menu (i.e. a dropdown-menu trigger icon), so I'd hesitate to include a sort-direction icon as well - headers would get very busy very quickly.

- Further, what you're describing is a great example of a feature that works differently in a basic table (which often shows an icon indicating which column is sorted and how) vs a spreadsheet (which typically doesn't include any such visual indication). Our `Table` component sits somewhere in between the two, so we have to make a thoughtful design decision here.

EDIT: Just saw your latest comment. That's a resourceful approach for now, but I wouldn't say it's a beautiful solution in the general case.

**Comment by michshat** [comment]
@cmslewis  @giladgray  Your feedback is much appreciated. It answers my question :) Thank you!

**Comment by tnrich** [comment]
Hey there, it looks like there is ...almost... a way to do this:

```
<ColumnHeaderCell
        name={
          <span>
            {displayName + "  "}
            {ordering &&
              (ordering === "asc"
                ? <span className={"pt-icon-standard pt-icon-arrow-down"} />
                : <span className={"pt-icon-standard pt-icon-arrow-up"} />)}
          </span>
        }/>
```
The one thing that is a bummer is that now the title tooltip for the header gets messed up:
![image](https://cloud.githubusercontent.com/assets/2730609/26236791/fefef37c-3c26-11e7-9d74-e64f43c7402a.png)

even if I add a title to the span I'm adding it doesn't work.. 

I'd still like this ability if anyone has figured out a way to do this.

Thanks!
