### ISSUE TITLE
[NumericInput] Add support for rightElements in NumericInput

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#908]
Please add support for passing down `rightElement` prop. We would like have this capability to show a label like USD or other currency code while using this control as Money Input.

**Comment by llorca** [comment]
@cmslewis quick fix?

**Comment by adidahiya** [comment]
we'd accept a PR for this, not a priority at the moment

**Comment by cmslewis** [comment]
@brsanthu Had a minute so just knocked this out.

**Comment by brsanthu** [comment]
@cmslewis thank you.

**Comment by tgreen7** [comment]
What is the status on this?

**Comment by giladgray** [comment]
@tgreen7 there is no status on this and it is not on the team's priority list. 
we'd welcome a PR (hence the label).
