### ISSUE TITLE
DateInput doesn't allow entering value under 1997

### ISSUE THREAD

**Issue by VeroBergeron** [palantir/blueprint#912]
- __Package version(s)__: 1.13.0

#### Steps to reproduce

1. Go to : [Date Input documentation](http://blueprintjs.com/docs/#components.datetime.dateinput)
2. Try to select a year under 1997

#### Actual behavior
![dp](https://cloud.githubusercontent.com/assets/16781092/24523545/5cbe6764-1561-11e7-9668-4c9f5f900a27.PNG)
Cannot select a year before 1997.
Also, there doesn't seem to be a right icon any longer. 

#### Expected behavior
Should be able to select any year and have the icon appear (necessary to use the date Input without opening the calendar on focus)

**Comment by tgreenwatts** [comment]
That's 20 years ago, the default minimum
![image](https://cloud.githubusercontent.com/assets/24398123/24524568/ebc96be0-154b-11e7-8a2a-1a811ef88e37.png)

You can update to whatever minimum you'd like

**Comment by VeroBergeron** [comment]
Oh boy, my bad. Anything you can do about the icon?

**Comment by giladgray** [comment]
@VeroBergeron what do you mean "about the icon?"

**Comment by llorca** [comment]
@VeroBergeron we recently removed the icon for consistency with the date range input, but you can still use the `rightElement` prop and add your own `<Button className="pt-minimal" intent={Intent.PRIMARY} iconName="calendar" />` and give it the behavior you desire

**Comment by VeroBergeron** [comment]
![dp2](https://cloud.githubusercontent.com/assets/16781092/24525491/7b2ce340-1568-11e7-9548-f5edda45ad77.PNG)

This icon doesn't seem to appear anymore. When you set openOnFocus to false there doesn't seem to be a way to open the popover.

**Comment by cmslewis** [comment]
Hi @VeroBergeron, we're tracking that very issue in #867 for our next major release. Also, see @llorca's most recent comment above, which came in around the same time you submitted yours. It's still possible to bring back the icon; if you choose not to include it, be sure to keep `openOnFocus=true`.

**Comment by tgreenwatts** [comment]
Good to close this ticket now?
