### ISSUE TITLE
Support focus cell for editable cells 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#914]
Follow up to https://github.com/palantir/blueprint/pull/718 
One piece of https://github.com/palantir/blueprint/issues/298

**Comment by tgreenwatts** [comment]
This is resolved now @gscshoyru ?

**Comment by gscshoyru** [comment]
I'm... not sure exactly what this issue was for, but it's either fixed or subsumed by other issues, I think it's good to close.

**Comment by cmslewis** [comment]
One weirdness: the focus (`activeElement`) moves from the editable cell back the beginning of the document tree when you press <kbd>Tab</kbd>.

![2017-10-05 12 16 05](https://user-images.githubusercontent.com/443450/31247943-030cde44-a9c7-11e7-9932-8578c3a44792.gif)

Sounds like a separate issue though.

**Comment by gscshoyru** [comment]
Yeah, all separate sets of bugs here.
