### ISSUE TITLE
radiogroup does not work with HMR

### ISSUE THREAD

**Issue by brunesto** [palantir/blueprint#919]
### Bug report

- __Package version(s)__: 
  "@blueprintjs/core": "^1.13.0",

- __Browser and OS versions__:

#### Steps to reproduce

using  webpack HMR  and  react-hot-loader (^3.0.0-beta.2), any RadioGroup will fail

#### Actual behavior

crash because of line 76 of in blueprint/packages/core/src/components/forms/radioGroup.tsx

    if (radio.type !== Radio) {
                    throw new Error(Errors.RADIOGROUP_RADIO_CHILDREN);
     }

react-hot-loader will proxy the components so the type differ and the test fails

I guess this is the same problem as in https://github.com/palantir/blueprint/issues/723

#### Expected behavior
either  skip the test against component type, or  instead of throwing an exception just log a warning

**Comment by adidahiya** [comment]
👍 instead of throwing an error, let's just `console.warn`

**Comment by giladgray** [comment]
this means `Tabs` and `Tabs2` will also have problems with HMR. if we can't safely assert child type (and it does seem a brittle check), then we need to rethink some of those APIs, which is a larger feature...

**Comment by brunesto** [comment]
the RadioGroup works fine with these HMR setups: 
https://github.com/nicksp/redux-webpack-es6-boilerplate and https://github.com/gaearon/react-hot-boilerplate
so it might be a problem of my HMR setup... i am still looking at it

**Comment by brunesto** [comment]
Indeed it was a problem in my configuration. As I understood it, babel-loader was running on node_modules folder, and hence the react-hot-loader/babel plugin was collecting the blueprintjs components as candidates for proxying.

The solution was simply to make sure that babel does not run on node_modules

For my use case (using blueprintjs as a library) I dont see a problem anymore with HMR, so I am closing the issue.
Thanks
