### ISSUE TITLE
FR: Add default number and date formatting in the table 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#923]
This will require some specing out

Current world: consumers of the table are free to render whatever they like, but this means that apps can easily be inconsistent in how they display things like numbers and dates

Let's supply a few sane default formats

**Comment by giladgray** [comment]
we've talked about doing text formatting in core #788, that seems like a better place for this feature.

**Comment by giladgray** [comment]
in fact @llorca mentions this exact use case in the description of #788 so i'm going to close this as a dupe.
