### ISSUE TITLE
Decorators should not mutate existing classes

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#931]
Following up on https://github.com/palantir/blueprint/issues/925#issuecomment-290940413

Higher order components should wrap existing components, not mutate their prototype directly. Check out the pattern documented in [react-bits](https://github.com/vasanthk/react-bits/blob/master/patterns/15.higher-order-component.md).

Thinking about this also makes me hesitant about implementing https://github.com/palantir/blueprint/issues/724 since that situation is similar. It's a little different because that one deals with the real DOM rather than the component tree. There, we are proposing switching from an element composition approach to one where we more directly mutate child elements, which sounds antithetical to the direction I'd like to go with decorators in the public API.

---

List of components to fix:

- [ ] HotkeysTarget
- [ ] ContextMenuTarget

**Comment by giladgray** [comment]
i've been looking into this and it's much more challenging to implement these decorators _without_ mutating. for instance, `HotkeysTarget` replaces the `render` method and makes great use of the fact that it's called within the component instance so it can easily invoke `renderHotkeys`. without mutation, this requires a `ref` to get the instance and a lot more lifecycle juggling to make sure things happen at the right time.

make me wonder if the hotkeys API is truly the best API for the feature in React?

also typings for HOCs are very obnoxious cuz you want the HOC to be a transparent outer layer, but i have not yet figured out how to express this in TS...

**Comment by adidahiya** [comment]
Some references for typing higher order components:

- [react-redux `@connect`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bf499af3ddd42df4859e8e07768b7b1652414e93/types/react-redux/index.d.ts#L49-L56)
- [react-dnd decorators](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dnd/index.d.ts#L37-L58)

There's probably also some useful JS reference there on whether you need to get a ref and what you need to do with the lifecycle. Getting a component ref doesn't sound so bad to me (you're not doing any DOM manipulation). What lifecycle juggling is required?
