### ISSUE TITLE
[Popover] Popover closes erroneously when given a react-select child

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#935]
### Bug report

- __Package version(s)__: core 1.13.0
- __Browser and OS versions__: Chrome 56 OSX El Capitan

#### Steps to reproduce

1. Make a popover with `PopoverInteractionKind.CLICK`
1. Put a react-select dropdown in it
1. Click an option in the Select component

#### Actual behavior

Popover closes, even though the content of the react-select options is rendered within the popover.

#### Expected behavior

Popover stays open.

**Comment by jrafidi** [comment]
To make this more interesting: I see this work exactly once.  After the first time working, all following attempts fail and close the popover immediately.

**Comment by sixinli** [comment]
this crash pretty badly with select2 too 😢

**Comment by sixinli** [comment]
versions:
`blueprint core` 1.13.0 (works in 1.0.0)
`select2` 3.5.x

error in console:
``Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.``

it does seem like the order of the dom nodes are different - the popover used to be rendered inside `div.pt-portal span` and now it renders to the top level (under `body`)

**Comment by Que3216** [comment]
Getting this issue too

**Comment by nchen63** [comment]
@giladgray this bug is blocking us from upgrading beyond v1.2. Is it possible to bump the priority on this?

**Comment by adidahiya** [comment]
@sixinli @nchen63 is there anything useful in the full stack trace? that select2 error probably warrants a separate issue from this one

**Comment by giladgray** [comment]
👨‍⚕️ _boom diagnosed:_ 

![image](https://cloud.githubusercontent.com/assets/464822/26702924/ff92dcb2-46db-11e7-8e7a-a05a6c96129b.png)

`e` is the event from clicking on a react-select option inside a `Popover`, as handled by [`Overlay#handleDocumentClick`](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/overlay/overlay.tsx#L321-L322), and it's coming from an element that _is no longer in the `body`._ this means it also isn't inside the overlay container, so `canOutsideClickClose` instructs the overlay to close itself.

an easy workaround is using `PopoverInteractionKind.CLICK_TARGET_ONLY`, which disables Overlay `canOutsideClickClose`.

```tsx
<Popover content={<Select ... />} interactionKind={PopoverInteractionKind.CLICK_TARGET_ONLY}>
```

**Comment by giladgray** [comment]
Two potential fixes:

1. add that `e.target.closest("body")` check to [`Overlay#handleDocumentClick`](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/overlay/overlay.tsx#L321-L322)
2. expose `canOutsideClickClose` on `Popover` props

**Comment by giladgray** [comment]
A third potential fix: Blueprint's own `Select` from #1159 😱

**Comment by qcharlieshi** [comment]
Has there been a fix for this? I tried using popover2 to see if popperjs would solve these issues but no luck.

Having any type of input or popover that bleeds over the initial popover will cause it to close.

**Comment by cmslewis** [comment]
@qcharlieshi nope, no fix implemented yet.

**Comment by trivektor** [comment]
+1

**Comment by adidahiya** [comment]
This is an old issue, we recommend building select components using `@blueprintjs/select`. If you have specific problems please file a new issue and use the bug report template.
