### ISSUE TITLE
[DateInput] Popover continually re-opens after selection when wrapped in a pt-label

### ISSUE THREAD

**Issue by luastoned** [palantir/blueprint#939]
### Bug report

- __Package version(s)__: datetime@1.11.0
- __Browser and OS versions__: FF54 Win10

#### Steps to reproduce

Wrap DateInput in a label tag like so:
```
<label className="pt-label>Pick a date: <DateInput/></label>
```
#### Actual behavior

1. Select valid date, watch the popup close, then reopen for no reason
2. Repeat step 1 indefinitely

#### Expected behavior

Select valid date, watch the popup stay closed

**Comment by llorca** [comment]
@luastoned weird things can happen when wrapping inputs within labels. Use the more verbose form structure instead: http://blueprintjs.com/docs/#components.forms.labels.form-groups

**Comment by luastoned** [comment]
Bug referenced in https://github.com/palantir/blueprint/issues/884

**Comment by cmslewis** [comment]
Folding this into #884.
