### ISSUE TITLE
[InputGroup] Refactor API to extend HTMLInputProps

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#943]
We should refactor `IInputGroupProps` to extend from `HTMLInputProps`, so that users can add custom callbacks on focus, on blur, and so on. The problem at present is that `IInputGroupProps` already extends from `IControlledProps`, which exposes props that conflict with some of those also included in `HTMLInputProps` (in particular: `onChange`, `defaultValue`, and `value`). Here's the exact set of errors you see:

```
[ts]
Interface 'IInputGroupProps' cannot simultaneously extend types 'IControlledProps' and 'HTMLProps<HTMLInputElement>'.
  Named property 'defaultValue' of types 'IControlledProps' and 'HTMLProps<HTMLInputElement>' 
  are not identical.

[ts]
Interface 'IInputGroupProps' cannot simultaneously extend types 'IControlledProps' and 'HTMLProps<HTMLInputElement>'.
  Named property 'onChange' of types 'IControlledProps' and 'HTMLProps<HTMLInputElement>' are 
  not identical.

[ts]
Interface 'IInputGroupProps' cannot simultaneously extend types 'IControlledProps' and 'HTMLProps<HTMLInputElement>'.
  Named property 'value' of types 'IControlledProps' and 'HTMLProps<HTMLInputElement>' are not 
  identical.
```

EDIT: There may be a better way to achieve this; the goal is primarily to expose the HTML Input lifecycle callbacks somehow.

**Comment by giladgray** [comment]
i wonder about adding something like `htmlProps` as a generic way for Blueprint components to support arbitrary spreads?

**Comment by cmslewis** [comment]
^ Definitely think that's worth exploring.

**Comment by llorca** [comment]
in the React types, we use `HTMLProps`, but there's also `HTMLAttributes` (`HTMLProps` minus the React attributes). We should probably always use `HTMLAttributes`
