### ISSUE TITLE
i18n - Is it possible to translate the components?

### ISSUE THREAD

**Issue by diegobfernandez** [palantir/blueprint#949]
If so are there any documentation on how can I do it? It's the only thing preventing me from adopting this awesome toolkit!

**Comment by diegobfernandez** [comment]
Miss clicked the close button :/

**Comment by giladgray** [comment]
@diegobfernandez what, specifically, is preventing you from adopting Blueprint here? We don't provide i18n utilities ourselves but it should be very easy to add one of many [react i18n implementations](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=react+i18n&*). You're responsible for i18n-ing your content in the end, anyway.

Components should support i18n by exposing props to customize any strings, and I think we already do a decent job of this. Please let us know if you find hardcoded strings and we'll be happy to add props (or, better, accept PRs doing so)!

**Comment by diegobfernandez** [comment]
My major concern was the Date component. But reading the docs again I found that it's based com react-day-picker and their docs specifies how to do i18n. Also the sort function of the table, but I now I get where the "Sort" text come from.

I would suggest to put somewhere in the docs that any text/label can be override.

Can this issue stay open to track the docs update suggestion?

**Comment by llorca** [comment]
I suppose we can add a note in our already existing "Internationalization" section, what do you think @giladgray? http://blueprintjs.com/docs/#typography.intl
