### ISSUE TITLE
[DateInput] Popover shows date off-by-one when typing

### ISSUE THREAD

**Issue by styu** [palantir/blueprint#955]
### Bug report

- __Package version(s)__: 1.13.0
- __Browser and OS versions__: Chrome 56.0.2924.87, MacOS El Capitan

#### Steps to reproduce

with the following (simplified) code:

```
const valueAsDate = new Date(this.state.value);
<DateInput
    canClearSelection={false}
    disabled={disabled}
    format="MMM DD, YYYY"
    initialMonth={this.today}
    maxDate={this.maxDate}
    minDate={this.minDate}
    onChange={this.handleDateInputChange}
    popoverPosition={Position.RIGHT}
    value={valueAsDate}
/>

private handleDateInputChange = (selectedDate: Date) => {
        this.setState({  value: moment(selectedDate).format("YYYY-MM-DD") });
}
```

1. Type in the date into the input box (e.g. Mar 23, 2017)

#### Actual behavior

1. The popover will show Mar 22, 2017 selected

#### Expected behavior

1. Mar 23, 2017 is selected instead

**Comment by giladgray** [comment]
@styu hmm i wonder if this is timezone-related? like, it's Mar 23 in your city but Mar 22 in UTC (because it's late in the day or something). datetime components do not handle timezones well #890. where in the world are you? does this repro consistently throughout the day?

**Comment by styu** [comment]
I was in PDT when I tried it, but that seems strange since Date objects
should all be in the browser time zone no? And we're sending the input a
Date object created from just a string

**Comment by cmslewis** [comment]
@styu do you still see this?

**Comment by cmslewis** [comment]
So here's what I'm seeing:

```
selectedDate:     Sun Feb 15 2015 00:00:00 GMT-0800 (PST)
this.state.value: 2015-02-15
valueAsDate:      Sat Feb 14 2015 16:00:00 GMT-0800 (PST)
```

Looks like `onChange` is receiving the correct date; it's the `new Date(...)` value that's erroneous. From the Date docs on MDN ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)):

> **Note:** parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

Looks like this works fine:

```tsx
new Date(2015, 02, 15) // returns proper date in PST: Sun Mar 15 2015 00:00:00 GMT-0700 (PDT)
```

Closing as the component isn't behaving incorrectly. **However**, we could use better docs here. Will open a follow-up issue.
