### ISSUE TITLE
Blueprint Table Requests

### ISSUE THREAD

**Issue by asronline** [palantir/blueprint#964]
Hey,

We're trying to use Blueprint table more for the Quip-style spreadsheet use-case and noticed there were a few features that would really help make our workflow useful:

- Ability to format cells within a table (like making text bold), this doesn't seem possible in the Editable Content cell
- Automatic word-wrap within cells
- Consistent way to add/delete rows and columns (people will come up with ways of doing it fragmenting the space)
- No excessive table BG if there are not enough columns. I'd rather have columns automatically stretch to fill the gap (attached below). 
![screen shot 2017-04-07 at 4 45 05 pm](https://cloud.githubusercontent.com/assets/5412738/24823294/ad7fa900-1bb1-11e7-8768-d05b3c747bed.png)
- Ability to move around cells (including column headers) with arrow keys
- Ability to resize rows by dragging them
- Ability to merge cells

Thanks!
— Ammaar

**Comment by llorca** [comment]
> Ability to format cells within a table (like making text bold), this doesn't seem possible in the Editable Content cell

✅ It's possible to style specific cells, check out this [Editable content](http://blueprintjs.com/docs/#table-js.editable-content) example in the docs: one of the cell has a class added to it with additional styles.

> Automatic word-wrap within cells

✅ Check out [`wrapText`](http://blueprintjs.com/docs/#table-js.cell) for cells.

> Consistent way to add/delete rows and columns (people will come up with ways of doing it fragmenting the space)

✅ That's already possible and easy, but we can look at providing a good set of basic table default actions, agree

> No excessive table BG if there are not enough columns. I'd rather have columns automatically stretch to fill the gap (attached below)

✅ Not super down on modifying the state of one column based on table size... I do think [`fillBodyWithGhostCells`](http://blueprintjs.com/docs/#table-js.table) would work wonders though.

> Ability to move around cells (including column headers) with arrow keys

✅ If you enable the focus cell with [`enableFocus`](http://blueprintjs.com/docs/#table-js.table), you'll be able to use arrow keys to move the focus cell around

> Ability to resize rows by dragging them

✅ Check out the [Formatted content](http://blueprintjs.com/docs/#table-js.formatted-content) example.

> Ability to merge cells

🙅‍♂️ I think that's the scary item that we don't support yet but may need to in the future. Curious, can you clarify your use case around merging cells?

Sorry you missed some of that stuff, we'll improve the table interactive examples in the docs to enable better feature discovery

**Comment by asronline** [comment]
I went through some of the above with Taryn and she actually said they were not supported. Specifically formatting in Editable content, arrow keys etc. @llorca

**Comment by tgreenwatts** [comment]
Editable cell content formatting - @cmslewis had said this wasn't possible in table today, I'll let him comment/update when I get response from him
Word-wrap - better coming soon #929 
Add/delete rows consistency - Not sure what this looks like from the table side, seems like the interaction is pretty app specific
Stretching table - Personally I agree there should be the option to either stretch to fill, filed to discuss #969
Moving around cells - not currently supported for editable cells
Resize rows by dragging - newly supported!
Merge cells - Possible, but a ways out so let's talk more closer to that time

**Comment by cmslewis** [comment]
If I said that, I didn't mean to! I don't actually know enough about EditableText at the moment to know for sure. I do remember saying it seems like it's possible to format text given that there's an example of an editable <h1> in the docs, IIRC.

On Apr 10, 2017, at 10:09 AM, tgreenwatts <notifications@github.com<mailto:notifications@github.com>> wrote:


Editable cell content formatting - @cmslewis[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cmslewis&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=-xHM_msPNZ5Ueek6I-8Uf3C2NKIdRgHQEGOCuANP978&m=ROn5GouqQLLp1OvWx1WfpodUVFzgB3M6Gl__gjhstk4&s=4LQ2an34f3exWGuvXJfMaQoMgOm9DRhgor_pdNLfzoM&e=> had said this wasn't possible in table today, I'll let him comment/update when I get response from him
Word-wrap - better coming soon #929[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_blueprint_issues_929&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=-xHM_msPNZ5Ueek6I-8Uf3C2NKIdRgHQEGOCuANP978&m=ROn5GouqQLLp1OvWx1WfpodUVFzgB3M6Gl__gjhstk4&s=gDV4wFj9dQMqUU9QCL35ezFKoohlvYsXYvhAOcASzmE&e=>
Add/delete rows consistency - Not sure what this looks like from the table side, seems like the interaction is pretty app specific
Stretching table - Personally I agree there should be the option to either stretch to fill, filed to discuss #969[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_blueprint_issues_969&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=-xHM_msPNZ5Ueek6I-8Uf3C2NKIdRgHQEGOCuANP978&m=ROn5GouqQLLp1OvWx1WfpodUVFzgB3M6Gl__gjhstk4&s=lOgSFOq3V6SSNYyCCB3DHxSreC19dkU8QTxsGog168s&e=>
Moving around cells - not currently supported for editable cells
Resize rows by dragging - newly supported!
Merge cells - Possible, but a ways out so let's talk more closer to that time

**Comment by tgreenwatts** [comment]
Cool looks like it's possible, we can work with you directly to get it working @asronline

**Comment by giladgray** [comment]
@asronline mind posting a quick update on the status of your requests in this issue?

**Comment by tgreenwatts** [comment]
I believe we can close this in favor of the individual tickets
