### ISSUE TITLE
Table, EditableCell event handlers

### ISSUE THREAD

**Issue by DuratarskeyK** [palantir/blueprint#965]
Greetings. Is there any reason, why onConfirm, onChange and onCancel of EditableCell receive only the text? There's no way to identify the cell in which change has happened except by creating a closure with cell identifications. And this has to happen on each re-render as well. So for each cell there are unique functions with their own closures and those functions are recreated on each re-render. For small tables you can ignore that, but if your table is big, this is sheer madness.

**Comment by adidahiya** [comment]
> if your table is big, this is sheer madness

as with any performance concern, I'd be curious to see perf benchmarks here.

but to address the problem at hand, there's probably something clever we can do with React context and pass through cell coordinates from Table to EditableCell so it can send them along in its onConfirm, onChange, and onCancel callbacks.

**Comment by pawsong** [comment]
In my case, I wanted to check if ctrl key is pressed on confirm, so tried to find where I can get keyboard event object and had no luck. Passing raw event object along with text value might be helpful :)
