### ISSUE TITLE
Update docs on DateInput description

### ISSUE THREAD

**Issue by rnadrag** [palantir/blueprint#966]
Since the calendar icon was removed from the `DateInput` component, the docs should be updated to not reference it anymore.

Two places were I noticed it is still mentioned:

- `The DateInput component is an input group with a calendar button that shows a DatePicker in a Popover.`

- `openOnFocus: If true, the popover will open when the user clicks on the input. If false, the popover will only open when the calendar icon is clicked.`

 (I assume this prop will go away completely as always needs to be true but still worth changing the docs if it is going to be around)

**Comment by cmslewis** [comment]
@rnadrag yep, will remove the `openOnFocus` prop in 2.0: #867
