### ISSUE TITLE
Button Tooltip doesn't hide

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#967]
I am using a `<Button>` inside `<Tooltip>` as below

```
<Tooltip
    content="Explain"
    intent={Intent.PRIMARY}
    hoverOpenDelay={1000}
    tooltipClassName="pt-dark"
    position={Position.BOTTOM}
>
    <Button
        className="pt-icon-help pt-intent-primary"
        disabled={true}
    />
</Tooltip>
```
When I move mouse on that button, I am able to see the Tooltip content `Explain` but it didn't disappear after I move mouse outside of the button. It works fine if I change `<Button>` to be `<AnchorButton>`. Is there anything special for `<Button>` on tooltip?

**Comment by giladgray** [comment]
@zhaoyi0113 there is indeed something special about disabled buttons, as [the red callout on this docs page](http://blueprintjs.com/docs/#core/components/button.javascript-api) explains. 

in short, `AnchorButton` doesn't use the `disabled` attribute so it still permits the events that `Tooltip` needs to function properly.

**Comment by zhaoyi0113** [comment]
Thanks for your response. That makes sense.

**Comment by thelastnode** [comment]
Is it possible to add a lint rule or dev mode warning for this? Seems to come up regularly:  #1179 #1591
