### ISSUE TITLE
Autocomplete on Icon classes

### ISSUE THREAD

**Issue by leebyp** [palantir/blueprint#968]
It could be useful to have typescript autocomplete for icons in the same way as we do for `Classes.xxxx`

With the autocomplete, we can also rework the components that take in `iconName` (which currently expects the part after `pt-icon-`)

**Comment by giladgray** [comment]
this already exists! we have `IconClasses` for the `"pt-icon-*"` string and `IconContents` for the unicode character. they're both generated from `icons.json` in the [gulp build](https://github.com/palantir/blueprint/blob/master/gulp/icons.js#L30-L33).

**Comment by leebyp** [comment]
perfect! can we create a `iconName` type by doing something similar?

**Comment by adidahiya** [comment]
most APIs accept either an icon name _or_ icon class (we strip the `pt-`)... so not sure if it's useful to have another enum called `IconNames`. perhaps we proxy `IconClasses` into simply `Icons`

**Comment by giladgray** [comment]
i don't see a need for any additional work here. `iconName={IconClasses.<AUTOCOMPLETE>}`

**Comment by leebyp** [comment]
Oh nice, i didn't realise that we pipe the prop through `Classes.iconClass`. In that case, a docs update is likely enough rather than the full enum.
