### ISSUE TITLE
DateRangeInput ignores locale prop

### ISSUE THREAD

**Issue by Thymo** [palantir/blueprint#970]
### Bug report

- __Package version(s)__: 1.12.0
- __Browser and OS versions__: Chrome 56.0.2924.87

#### Steps to reproduce

```
import React, {PropTypes} from 'react';
import { DateInput, DateRangeInput } from '@blueprintjs/datetime';
import LocaleUtils from 'react-day-picker/moment';

import moment from 'moment';
import 'moment/locale/nl';

const DateRangeInput = (props) =>
  <DateRangeInput
    localeUtils={ LocaleUtils }
    locale="nl"
  />
```

#### Actual behavior

The DateRangePicker uses the "en" locale instead of the "nl" locale.

#### Expected behavior

Should pass locale prop to DateRangePicker in DateRangeInput.
There is no problem when using DateInput.

**Comment by cmslewis** [comment]
@Thymo thanks for the issue. Will investigate shortly, hopefully this week.
