### ISSUE TITLE
Ghost and loading cells styling doesn't divider between row headers and row contents

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#972]
Seen on Chrome & Table 1.10
With row headers, but without any actual rows, ghost cells don't show the divider between the row headers and the row contents

![image](https://cloud.githubusercontent.com/assets/24398123/24927163/e341ae2c-1eb2-11e7-825b-8b86d7bf7738.png)

Related context: https://pl.ntr/eI

**Comment by llorca** [comment]
Any pointers on how to repro / what's different with this table? Doesn't repo on the docs: http://blueprintjs.com/docs/#table-js.table-loading-states

**Comment by michael-yx-wu** [comment]
The docs don't render tables with 0 "real" rows. This is only crops up if you're rendering a table that only contains ghost cells.

**Comment by tgreenwatts** [comment]
Yep, reproed by setting the docs example to 0 rows and ghost cells
![image](https://cloud.githubusercontent.com/assets/24398123/24930039/fbd7078e-1ebc-11e7-9f20-e5c832486cfc.png)
