### ISSUE TITLE
EditableText fires wrong callbacks when blurring via ESC key

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#975]
### Bug report

- __Package version(s)__: core 1.14
- __Browser and OS versions__: Chrome, macOS Sierra

#### Steps to reproduce

1. `<EditableText isEditing={/* controlled */} defaultValue="abc" />`
1. type, change value to `"xyz"`
1. hit <kbd>ESC</kbd>

#### Actual behavior

- `onConfirm` fired with `"xyz"`
- `onCancel` not fired
- new value stays in input

#### Expected behavior

- `onConfirm` _not_ fired
- `onCancel` fired
- input value reverts to the last confirmed value

---

related: #573, #483

**Comment by cmslewis** [comment]
@adidahiya Seems like this has been fixed? The following test passes:

```tsx
it("calls onCancel, does not call onConfirm, and reverts value when escape key pressed", () => {
    const cancelSpy = sinon.spy();
    const confirmSpy = sinon.spy();

    const OLD_VALUE = "alphabet";
    const NEW_VALUE = "hello";

    const component = shallow(
        <EditableText
            isEditing={true}
            onCancel={cancelSpy}
            onConfirm={confirmSpy}
            defaultValue={OLD_VALUE}
        />,
    );
    component.find("input")
        .simulate("change", { target: { value: NEW_VALUE } })
        .simulate("keydown", { which: Keys.ESCAPE });

    assert.isTrue(confirmSpy.notCalled, "onConfirm called");
    assert.isTrue(cancelSpy.calledOnce, "onCancel not called once");
    assert.isTrue(cancelSpy.calledWith(OLD_VALUE), `unexpected argument "${cancelSpy.args[0][0]}"`);
    assert.strictEqual(component.state().value, OLD_VALUE, "did not revert to original value");
});
```

**Comment by cmslewis** [comment]
Improved tests in #1310 to verify this.
