### ISSUE TITLE
Restore docs syntax highlighting

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#98]
Seems to have disappeared again:
<img width="516" alt="screen shot 2016-11-11 at 6 04 14 pm" src="https://cloud.githubusercontent.com/assets/199754/20234914/476e7272-a839-11e6-9aae-3da8081c5b8f.png">

**Comment by giladgray** [comment]
oh it's gone gone. i've got to clean up the syntax package and publish it for real.
