### ISSUE TITLE
MenuItem should truncate before `label`

### ISSUE THREAD

**Issue by garetmckinley** [palantir/blueprint#984]
If you have a max width set on a menu and also a `label` set, the text for that `MenuItem` gets truncated underneath the label, causing an ugly mess.

![screen shot 2017-04-13 at 5 18 12 pm](https://cloud.githubusercontent.com/assets/1624279/25024777/4c25e032-206d-11e7-842b-f8711e68873e.png)

I'm not sure the best way around this, but I'll definitely update this issue with any solutions I find. I would suggest simply adding a larger right padding on the menu items, but that doesn't account for items without the label included. Maybe it should detect when a label is present and automatically add a larger right padding? I guess the issue there is that a plain jsx component can be passed in the `label` attribute, so the actual padding required is mostly unknown.

**Comment by llorca** [comment]
We do logic for this in `InputGroup`, what do you think about supporting it in menus too @giladgray?

**Comment by giladgray** [comment]
another option is to refactor styles to use flexbox: left and right icons would be fixed size and the text would grow to fill all space.

**Comment by garetmckinley** [comment]
I think the flexbox refactor is a real solid solution :+1:

**Comment by llorca** [comment]
Agree. Quite low priority for us at the moment as we're not constrained by `max-width`s and long labels -- we'd happily accept a contribution!

**Comment by tnrich** [comment]
I'm also hitting this but I don't believe I've included any special css to set max-width: 
![image](https://user-images.githubusercontent.com/2730609/34694570-6b21d976-f47c-11e7-9d20-bc4fcb3dc219.png)
