### ISSUE TITLE
Docs missing on Sketch Kit assets 

### ISSUE THREAD

**Issue by eyalw** [palantir/blueprint#990]
Hi, I noticed in the Sketch core kit some elements that I can't find in the docs. like the Dropdown Search element. Where can I find docs on this?

![image](https://cloud.githubusercontent.com/assets/608669/25070600/b261b926-22ab-11e7-815d-a2fc6720f763.png)

**Comment by llorca** [comment]
Hi Eyal, good catch! The Sketch Kits are built ahead of the React components, which is why some of the Kit assets may not have a React implementation yet.

Regarding this particular dropdown component, you can follow along as we plan and build it: https://github.com/palantir/blueprint/issues/118

**Comment by eyalw** [comment]
@llorca thanks for the super fast reply!
