### ISSUE TITLE
NonIdealState margin issues

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/blueprint#994]
When creating a non ideal state that has a description and does not have a title, the internal margin is off. It looks like this: 
![image](https://cloud.githubusercontent.com/assets/3452559/25099691/380f53f6-2362-11e7-844a-d19308814fbd.png)
it should look more like this:
![image](https://cloud.githubusercontent.com/assets/3452559/25099699/403a4874-2362-11e7-92bd-6b5ef46585b2.png)

**Comment by llorca** [comment]
I thought we fixed that a while back, guess it's still a problem.

@giladgray Can we try to be smart about it this time, and do something like
```
.pt-non-ideal-state > *:not(:last-child) {
  margin-bottom: $pt-grid-size * 2;
}
```
